### ISSUE TITLE
Updating nuget to 5.7.0 on Linux completely breaks nuget

### ISSUE THREAD

**Issue by bender-the-greatest** [NuGet/Home#10027]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.7.0

dotnet.exe --version (if appropriate): 3.1.402

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Ubuntu 20.04.1 LTS

Worked before? If so, with which NuGet version: My Linux distribution contains a `nuget` package but this is at version `2.8.7`. I was running into a dependency issue trying to install a dependency for a PS module I'm working on, and was directed to upgrade to a newer version of NuGet.exe. After upgrading to `5.7.0` (I can't target a specific version to update to with this version of the client, only the latest), I can no longer use the `nuget` command at all, not even to list usage information, instead getting the errors in the attached log.

## Detailed repro steps so we can see the same problem

From Ubuntu 20.04.1

1. `sudo apt install -y nuget`

2. `nuget --version # Displays 2.8.7`

3. `sudo nuget update -self # Currently installs 5.0.7`

4. `nuget --version` # see errors in the attached log

After completing step 3 any `nuget` command barfs up the same stacktrace.

### Verbose Logs

Can't provide verbose logs as I don't think any parameters are even being processed at the point of the error. Output in the log is the same regardless of the verbosity specified.

[nugeterror.log](https://github.com/NuGet/Home/files/5212821/nugeterror.log)

**Comment by kartheekp-ms** [comment]
As per [doc](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#nugetexe-cli), `nuget.exe, is the command-line utility for Windows that provides all NuGet capabilities; it can also be run on Mac OSX and Linux using Mono with some limitations.`.

Please use [`dotnet.exe` CLI](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#dotnetexe-cli) `works on all platforms (Windows, Mac, and Linux) and provides core NuGet features such as installing, restoring, and publishing packages`.

**Comment by luisten** [comment]
I'm having the exact same problem. @kartheekp-ms your comment doesn't help to resolve the issue. 
Is there any workaround or additional dependency on Linux that is required to get this running?

@bender-the-greatest were you able to find a solution?

**Comment by zivkan** [comment]
@luisten looking at the original issue's attached log, I see:

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

Since System.Net.Http is an assembly that ships in the runtime, that suggests to me there's something wrong with the mono runtime being used, not NuGet. Looking at [Mono's 3.0.0 release notes](https://www.mono-project.com/docs/about-mono/releases/3.0.0/#45-profile), I see "Newly introduced assemblies (System.Net.Http, System.Threading.Tasks.Dataflow)", and since 3.0.0 was released in 2012, possibly a very old version of Mono is being used.

I suggest following the official installation instructions: https://www.mono-project.com/download/stable/#download-lin

Note that in the past we also had a case where Ubuntu's mono binary was broken: https://github.com/NuGet/Home/issues/9541

So, unless you're on a Microsoft supported version of Mono, we can't provide support, and I suggest you talk to Canonical for Ubuntu support.

If you're on Xamarin's official build of Mono, they ship their own version of nuget.exe ([click here](https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main/binary-amd64/Packages) and search for nuget), which I suggest you use, since that's the version they tested and validated as weorking for version of mono. If you're still having problems, I suggest contacting github.com/mono/mono.

**Comment by ogxd** [comment]
> As per [doc](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#nugetexe-cli), `nuget.exe, is the command-line utility for Windows that provides all NuGet capabilities; it can also be run on Mac OSX and Linux using Mono with some limitations.`.
> 
> Please use [`dotnet.exe` CLI](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#dotnetexe-cli) `works on all platforms (Windows, Mac, and Linux) and provides core NuGet features such as installing, restoring, and publishing packages`.

dotnet cli is not a 1 to 1 replacement of Nuget. It gives way to install / update / remove packages for a given project, however it does not allow things like pushing or downloading `.nupkg`, which is useful for a variety of things like tooling or CI, which (nowadays) usually runs on linux docker images.
