### ISSUE TITLE
VS Rebuild doesn't reinstall changed packages into global-packages (In last version 16.8.0 preview 3.1)

### ISSUE THREAD

**Issue by Denis535** [NuGet/Home#10060]
I have solution with 2 projects. 
First project produces nuget package into local repository. 
Second project consumes this package.
I had to rebuild the project for the modified package to be reinstalled into `global-packages`.

But today I've updated Visual Studio to version 16.8.0 preview 3.1. And now rebuild doesn't reinstall the modified package. I'm forced to clear `global-packages` manually.

**Comment by nkolev92** [comment]
@Denis535 

Afaik, this behavior is consistent. NuGet *never* reinstalls packages in the global packages folder. 

How does the second project consume the first one?

**Comment by Denis535** [comment]
@nkolev92 
Here is example.
[NuGetLibrary.zip](https://github.com/NuGet/Home/files/5283317/NuGetLibrary.zip)

Create "Local" source (I use path C:\NuGet\Repository). 
Pack "NuGetLibrary" project. My "Push" target will push it into local source.
Rebuild "NuGetLibrary.Console". If global-packages already has an old package then "NuGetLibrary.Console" will use this old 
package. In previous VS I haven't this problem!!!

Also be careful, nuget may install package from nuget.org. It's not my package!!!

**Comment by nkolev92** [comment]
@Denis535 

NuGet wouldn't replace a correctly installed package. 

What you are describing is the expected behavior in both 16.7 and 16.8. 

I think this doc well describes the NuGet installation process: https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process

Do you still have 16.7 on your machine? 

If you are seeing anything similar to what your describing with the old version, I'd love to help understnad the behavior.

**Comment by Denis535** [comment]
You know better.

[The difference between build and rebuild](https://stackoverflow.com/a/17781143/4805491):
- Build: Compiles code files (DLL and EXE) which are changed.
- Rebuild: Deletes all compiled files and compiles them again irrespective if the code has changed or not.

So, probably rebuild should not do something with packages. At least it will be faster. 
But sometimes it can lead to problems. So, I would prefer that **re**build does **re**install packages.

**Comment by nkolev92** [comment]
We appreciate the feedback @Denis535. 

The restore that NuGet tends to run in VS is designed to be as seamless as possible, and while there is a slight difference between `build` and `rebuild` restores right now, see https://github.com/NuGet/Home/issues/6987, I'm not confident hiding an aggressive and expensive action such as package reinstallation behind rebuild is the best approach at this point. 

I think among https://github.com/NuGet/Home/issues/6987 and https://github.com/NuGet/Home/issues/6579, I hope your problem is captured.

Closing as dup https://github.com/NuGet/Home/issues/6579.

**Comment by gioce90** [comment]
Hi @Denis535 . I've faced your same problem. To avoid to be forced to clear global-packages manually, I recently make my solution public by releasing a package called NuJet (https://github.com/gioce90/NuJet). It enhances the inner-loop development and testing process for NuGet packages, especially in local workflows.

Feel free to check it out—I’d love to hear your feedback!
