### ISSUE TITLE
NuGet.config not flexible

### ISSUE THREAD

**Issue by dylanfj700** [NuGet/Home#10061]
Can't have multiple nuget.config in a solution folder, one in each project folder, a bit like "composer" if we talk about PHP.
Example: in PHP you can have this
- /home/Solution1/
  - project1/
    - composer.json
    - vendor/
  - project2/
    - composer.json
    - vendor/

That's a shame .

**Comment by heng-liu** [comment]
Yes, we share one NuGet.Config for all projects in one solution.
May I know why you need multiple NuGet.Config? 
And why putting all sources in one NuGet.Config doesn't work for you? Thanks!

**Comment by dylanfj700** [comment]
Sometimes, I need two differents versions of package in the same solution for more projects

**Comment by dylanfj700** [comment]
> Yes, we share one NuGet.Config for all projects in one solution.
> May I know why you need multiple NuGet.Config?
> And why putting all sources in one NuGet.Config doesn't work for you? Thanks!

**Comment by heng-liu** [comment]
Hi @nkolev92 , do you know if there is any way to install two different versions  of packages in the same solution?

**Comment by aortiz-msft** [comment]
@DylanFJ  - If you could please share an example of the config files, we'd be able to point you in the right direction.

**Comment by dylanfj700** [comment]
> @DylanFJ - If you could please share an example of the config files, we'd be able to point you in the right direction.

The example of nuget.config ?

**Comment by zivkan** [comment]
NuGet.config cannot be used to specify package versions. It's generally used to set package sources for the solution. There's no issue having different projects in a solution use different versions of a package. You can do this though the Package Manager UI, or otherwise. The "Manage Packages for solution" even shows you the version each project uses, which can be different:

![image](https://user-images.githubusercontent.com/5030577/95123575-0978a880-0707-11eb-87ab-e5e3b1f7f423.png)

So, either we don't understand your scenario, or your request is already possible.
