### ISSUE TITLE
Warning ‘RestoreManagerPackage’ package did not load correctly occurred and PM UI Menus disappeared when updating all packages for ASP.NET Web Single Page Application (.NET Framework)

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10087]
## Details about Problem
NuGet version: NuGet Client Release-5.8.x\5.8.0.6873
VS Version: Main\30528.160
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Open VS and click “Create a new project” button and click the template “ASP.NET Web Application (.NET Framework)”.
2. Type the project name, click “Create” button and create a “Single Page Application”.
3. Open project PM UI, go to “Updates” tab, check “Select all packages” check-box and click “Update” button.
4. Click “OK” button in the prompt “Preview Changes” window and click the “restart” button in PM UI.
## Expected
Updating is successful without any error.
## Actual
Warning ‘RestoreManagerPackage’ package did not load correctly occurred and PM UI Menus disappeared as below screenshot. 
![RestorePackage](https://user-images.githubusercontent.com/20632625/94575966-660f3a00-02a7-11eb-91d7-c86ac2ba354c.JPG)
![image](https://user-images.githubusercontent.com/20632625/94576328-cb632b00-02a7-11eb-9de4-7ca3802bdab1.png)
## Note
It started to repro from NuGet Dev\5.8.0.6865.

**Comment by dtivel** [comment]
To be clear, the warning I get in step 4 of the repro steps that prompts to restart is this:
![image](https://user-images.githubusercontent.com/12734758/94615148-19ead800-025c-11eb-9aca-c99b0500f866.png)

**Comment by v-luzh** [comment]
@dtivel, yes you are right. You will see the warning dialog and PM UI gone after clicking the "Restart" button.

**Comment by dtivel** [comment]
@v-luzh, I could not repro this.  I tried:

* release-5.8.x\5.8.0.6873 on latest int preview
* release-5.8.x\5.8.0.6873 on Version 16.8.0 Preview 4.0 [30529.64.d16.8]

After restarting, NuGet worked fine.  I restored and built just fine.  I opened PM UI with the "Manage NuGet Packages..." command in Solution Explorer.

What you observed is a package load failure.  I can't say why the failure occurred here; however, in the past I've found that it was caused by devenv.exe.config not getting updated by the VSIX installation.  That results in a failure on first launch of VS after installing the VSIX, unlike this issue.

If and only if you can still reproduce this, can you please send me (via email) your devenv.exe.config file?  It will be under %LOCALAPPDATA%\Microsoft\VisualStudio in 16.0_xxxx folder.  Mine was in a 16.0_1803ffbf folder.  You'll know it's the right file if you look through it and see the installation path for your VS preview installation.  In this example, I installed preview 4 under c:\program files (x86)\microsoft visual studio\2019\preview4:
```XML
<dependentAssembly>
	<assemblyIdentity name="NuGet.Credentials" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
	<codeBase version="5.8.0.6873" href="c:\program files (x86)\microsoft visual studio\2019\preview4\common7\ide\commonextensions\microsoft\nuget\NuGet.Credentials.dll"/>
</dependentAssembly>
```

FWIW, running "devenv /setup" in an elevated developer command prompt specific to the target VS installation should resolve this issue.  My understanding is that something like this should happen automatically at the end of VSIX installation.

**Comment by dtivel** [comment]
@v-luzh, after installing or uninstalling a VSIX please run `devenv /setup` from a Visual Studio developer command prompt specific to the VS instance you are targeting.

If this problem still persists, please reactivate this issue with updated repro steps.

**Comment by v-luzh** [comment]
@dtivel Thanks for your introduction. We will try running "devenv /setup" from a Visual Studio developer command prompt after installing or uninstalling a VSIX.
