### ISSUE TITLE
GetInstalledPackages throws for PackageReference projects when assets file doesn't match project TFMs

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10081]

**Comment by nkolev92** [comment]
Adding a couple of tags so we see it during perf sync-ups :) 

You don't have to attend them, it's for my own awareness.

**Comment by aortiz-msft** [comment]
@erdembayar - Could you please sync with @zivkan on next steps for this issue?

**Comment by erdembayar** [comment]
@aortiz-msft @zivkan 

After spending some time I manipulated asset files  and I was not able to repro this problem. Then after talking with @zivkan 
 again we realized problem was fixed by @birgithi recently. 
 Instead of exception it was returning empty transitive packages which is expected behavior.
![image](https://user-images.githubusercontent.com/8766776/105788030-80df7b80-5f34-11eb-8257-6be3c739492c.png)

Here is problem fixed by replacing `First` with `FirstOrDefault`. on
https://github.com/NuGet/NuGet.Client/blob/0c74f91ac665ec5661ff2cdbbbba5869496ea322/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L274 with [commita#e66d2685](https://github.com/NuGet/NuGet.Client/commit/055f4b86569ea5402cbeca9b3497eae7fd7bc8ab#diff-5fae96e8312674fe53149dbdb5a5f036aea82698a5aeff49617e8e7ae66d2685)
