### ISSUE TITLE
Can not load assembly "Nuget.Versioning" in Azure Functions

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#10118]
When I add "Nuget.Versioning" package to an Azure Function project, in runtime I get an exception, when I try to use SemanticVerion class: 
"System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'NuGet.Versioning, Version=5.7.0.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified."

NuGet package version 5.7.0.7 (also tried preview version)
VS version: VS Community 2019 (16.7.3)
OS version: win10 v1909
Azure Function: .net core 3.1, function version is V3

1. Create HTTP-triggered Azure Function V3

2. Add Nuget.Versioning package

3. Create an instance of SemanticVersion class

4. Run

**Comment by zivkan** [comment]
This is happening because of the Azure Functions SDK, rather than NuGet. Here's a bug I encourage you to upvote: https://github.com/Azure/azure-functions-host/issues/6650

Having a quick chat with someone who worked on the SDK, they suggested using the MSBuild property `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` in your csproj, and this worked for me.

Ultimately it happens because Azure Functions itself uses NuGet.Versioning, and so it trims assemblies it thinks that your app doesn't need. Unfortunately, when you use one of the assemblies it uses, and cleans up itself, then the assemly you need is missing.
