### ISSUE TITLE
Roslyn Analyzer suggestion "install with package manager" opens NuGet to wrong tab

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1218224/selecting-install-with-package-manager-opens-nuget.html) / https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1230203._

---
When editing my .NET app if a Roslyn analyzer appears with a helpful suggestion that the code I am attempting to write is not possible because I am missing a package and gives me a helpful suggestion to "install with package manager" it then tries to open NuGet manager.

This is where I hit a problem that I could reproduce easily. If the last time I used package manager I left my tab on for example "installed" it would be the tab that the analyzer would open and try to search for the missing package. This would show no results.

But obviously it should have switched to "Browser" since the package was not in my solution.

---
#### Feedback Bot on 10/14/2020, 03:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2020, 01:04 PM: 

<p>Thanks for creating this issue! We figured it’s covering the same as <a target='_blank' href="https://github.com/NuGet/Home/issues/7309">another one</a> we already have. Thus, we closed this one as a duplicate. We’ve transferred all votes from this ticket to the other one. For more information, see also our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

#### kapenaga [MSFT] on 10/14/2020, 02:05 PM: 

<p>This issue is currently being investigated and could be because of <a target='_blank' href="https://github.com/NuGet/Home/issues/7309">another one</a> we already have. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by kartheekp-ms** [comment]
Repro steps

1. Created `.NET Core Console App`
2. Installed `StyleCop.Analyzers` package to the project.
3. Type `JObject` in `Program.cs` file
4. Click on `Install Package Newtonsoft.json` > `Install with package manager..`
5. Navigated to PM UI installed tab with `Newtonsoft.Json` in search box.

![1](https://user-images.githubusercontent.com/52756182/96045661-1ee88380-0e27-11eb-883e-c36c6780f216.png)
![issue](https://user-images.githubusercontent.com/52756182/96046004-a3d39d00-0e27-11eb-87eb-c7d128343a12.png)

This could be because of [another issue](https://github.com/NuGet/Home/issues/7309) we already have.

**Comment by donnie-msft** [comment]
We don't own this menu. I believe Roslyn owns it
https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/AddImport/CodeActions/InstallWithPackageManagerCodeAction.cs

I don't believe the https://github.com/NuGet/Home/issues/7309 issue is quite the same. It focuses on VS defaults.
Basically, Roslyn should be able to pass an argument to us. Perhaps it always depended on the last closed tab to be Browse... and that's bad.

**Comment by kartheekp-ms** [comment]
Assigned feedback ticket to Roslyn team as per @donnie-msft comment.

**Comment by donnie-msft** [comment]
Putting this back on our side.
 Roslyn's [PackageInstallerServiceFactory.ShowManagePackagesDialog](https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs#L659) calls [IVsSearchProvider.CreateSearch](https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/VisualStudio/Core/Def/Packaging/PackageInstallerServiceFactory.cs#L675-L676).

The search API invokes our [NuGetPackageManagerControlSearchTask.Start()](NuGetPackageManagerControlSearchTask). I believe we need to automatically set the current tab to Browse here, since the Search API generally assumes it's "Browsing" packages.

Future improvement would be to allow an API parameter to specify which tab to Search.

**Comment by donnie-msft** [comment]
Adding a rough estimate. Haven't dug into it yet.

**Comment by aortiz-msft** [comment]
Please try to fix opportunistically for 17.0; otherwise we will have to fix in 17.1

**Comment by donnie-msft** [comment]
Released in VS 17.0.31729.192.

Also, a Roslyn fix no longer requires the package source be named exactly "nuget.org" to trigger this Codefix suggestion in VS.
https://github.com/dotnet/roslyn/pull/56606
