### ISSUE TITLE
Missing KoreBuild 

### ISSUE THREAD

**Issue by rhires** [NuGet/Home#1015]
Hello. Trying to build on Mac OS X. I did a Google search and found this very same issue, and following the link I found that someone said it was fixed, but alas, I'm having the same issue with a freshly cloned repo on my system. KoreBuild is just not there:
./build.sh
Unable to find package 'KoreBuild'.
Installing 'Sake 0.2'.
Successfully installed 'Sake 0.2'.
./build.sh: line 31: packages/KoreBuild/build/dnvm.sh: No such file or directory
./build.sh: line 35: dnvm: command not found

I saw that it's in some older versions...but given they are older versions, I'm not sure that they're appropriate for the latest and greatest. I also did a bit of searching to see about getting KoreBuild separately, but it isn't a separate NuGet package, and I'm not sure where else I could get it.

**Comment by emgarten** [comment]
This bug should be logged on: https://github.com/aspnet/Home/issues

**Comment by emgarten** [comment]
@rhires you need to install DNX to build NuGet3.  You can find help on that here: https://github.com/aspnet/home

**Comment by rhires** [comment]
Thank you. I have aspnet installed, and have beta6 running on my Mac, and was even able to successfully get EF working. It seems to be an issue w/ NuGet missing KoreBuild. Maybe an issue w/ the build scripts?

If you look at [https://github.com/NuGet/Home/issues/955](#955) <https://github.com/NuGet/Home/issues/955%5D(#955)> at my last (kinda rambly) comment, you can see what happened when I did find KoreBuild and installed in manually. I’m not sure if that’s a related issue or not, but I find it worth mentioning.

**Comment by emgarten** [comment]
KoreBuild is on https://www.myget.org/F/aspnetvnext/api/v2

It looks like build.sh is missing that extra parameter that build.cmd has.

**Comment by yishaigalatzer** [comment]
We will take a PR for this, but for now building NuGet on a Mac is not a top priority for the team.

**Comment by kuncevic** [comment]
Having similar issue on Windows.

```
d:\Projects\src\EntityFramework>build.cmd
The system cannot find the path specified.
The system cannot find the path specified.
fail: Could not find a part of the path 'd:\Projects\src\EntityFramewor
k\packages\KoreBuild\build'.
fail: Stack trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String origina
lUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`
1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at Sake.Engine.Loader.DefaultLoader.Load(Options options)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

@emgarten Just tried to run `.nuget\NuGet.exe install KoreBuild -ExcludeVersion -Source https://www.myget.org/F/aspnetvnext/api/v2 -Out packages` 
but getting error `Unable to find package 'KoreBuild'.` 
So looks like the `KoreBuild` is not there

UPDATE:
Just added `https://www.myget.org/F/aspnetvnext/api/v2` in to vs2015 nuget sources then run `build initialize` and all looking good now.

**Comment by yishaigalatzer** [comment]
Thanks for the update @riapp

**Comment by danielgary** [comment]
This appears to be broken again.  I am unable to find KoreBuild in https://www.myget.org/F/aspnetvnext/api/v2

**Comment by emgarten** [comment]
@danielgary NuGet no longer uses KoreBuild. Make sure you are using the latest repo which is: NuGet.Client

**Comment by erlis** [comment]
Ok, I know the bug was closed. I've found this because in my quest to find how to build my Asp.Net 5 project I get to know about Sake & KoreBuild. On the few examples I've found they are using NuGet to restore the KoreBuild package, but now KoreBuild is not a package anymore O_o. Here you are saying `NuGet no longer uses KoreBuild` and my question is: What are you using then? It looks like I should not be looking into KoreBuild anymore but no idea on what direction should I move. 

Any hint will be appreciated. 

Thanks!!

**Comment by yishaigalatzer** [comment]
ASP.NET still uses it I believe. https://github.com/aspnet

For us we use msbuild and a simple powershell script to coordinate our builds, it is a matter of taste of course. The reason we moved away from kore build and sake was that they are developed by the asp.net team for their use, particularly korebuild. It was not properly documented, and many things we needed (like signing for example) where done in a very specific way to what the asp.net team needs, and we find that it takes too long to adapt to our needs, mostly because of the documentation issue, but also because it wasn't mature enough for us to take a dependency on.

Now I wouldn't be in a position to advise you on korebuild yes or no, but in general I believe it is not intended to become a real supported product at this moment.

@davidfowl might be able to add more insights
