### ISSUE TITLE
Using NuGet offline | Disable certificate check

### ISSUE THREAD

**Issue by ComanderKai77** [NuGet/Home#10161]
I'm using NuGet on a Windows maschine without internet connection and a local repository manager (Nexus).
The problem is that NuGet tries to verify the certificates even if the repository is trusted.

For example I want to download Newtensoft.Json from my repository server.
The download is fast but after the download NuGet tries to verify the certificat / signing and contacts digicert.com in this case resulting in a timeout.
The hole proccess to download and trying to verify the package takes nearly 3 minutes which is way too much.

Is there a way to disable certificate checking completly and speed up the proccess?

NuGet version: 5.7.0.6726
msbuild version: 16.7.0.37604
Windows 10

**Comment by nkolev92** [comment]
Hey @ComanderKai77 

Are you getting a NU3028 at all? 

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028 contains information for how to handle scenarios where the machine has no access to the verification servers, but normally I would've expect for you to get a warning rather than a time out.

**Comment by ComanderKai77** [comment]
Thank you @nkolev92.
I was getting a NU3034
`WARNUNG: NU3034: Package 'Newtonsoft.Json 12.0.3' from source 'Source xy': This package is signed but not by a trusted signer.`
but setting `NUGET_CERT_REVOCATION_MODE` fixed it.
