### ISSUE TITLE
Add support for authenticated feeds as MSBuild properties (and pass throughs from upstream tooling)

### ISSUE THREAD

**Issue by ericsampson** [NuGet/Home#10178]
Currently there are MSBuild properties for [`RestoreSources` and `RestoreAdditionalProjectSources`](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild) which are used by the `restore` target.

However, these do not support authenticated feeds, which has become painful due to the increased use of same (Azure Artifacts, GitHub Packages, etc).

Feature request would include:
1. New MSBuild properties added to be able to specify the credentials for the respective sources specified by the existing two parameters (order sensitive matching?)

2. enable setting these same credentials via the upstream tooling:
- dotnet msbuild -restore --property:NEWPROP=TOKEN --property:RestoreSources=blah
- dotnet restore --api-key TOKEN1 --source blah1 --api-key TOKEN2 --source blah2
- dotnet build (same)
- same behavior for nuget.exe and msbuild.exe (I think?)

I'm not 100% sure if `RestoreSources` and `RestoreAdditionalProjectSources` themselves can be delimited (by what?), and how that interacts with the new properties being able to support multiple tokens in the same manner. And how that influences the dotnet/msbuild argument design, if any. For instance, I'm not sure if current behavior for the dotnet restore `source` parameter to support being itself a delimited string?

The original customer request came from [Twitter](https://twitter.com/Nick_Craver/status/1319289808087252997) via @NickCraver and @m0sa.

**Comment by NickCraver** [comment]
I think the restore with a given prop works, but agree it doesn't work for `n`, it'd need to somehow be associated with a feed, like say we could do `<RestoreAdditionalPackageSources>` with a key/credentials section or....I'm not sure really, but the interface needs to be `n`, and associated to the feed somehow.

You could in theory use any non-allowed URL characters as a delimiter, but that feels a bit hacky. Or, something like `https://{apiKey}@example.com/feed/blah`, in which case NuGet would need support but the MSBuild bits wouldn't need to shift (though you'd need to URL-encode the pass-phrase and that may be painful).

I don't have a specific solution in mind here since passing variables at the command line is inherently linear. However, if `<RestoreSources>` (or whatever) was multi-level, it might look a lot like `nuget.config` does today and have the cardinality needed to support the use cases. For example:
```xml
<RestoreSources>
    <Feed Url="https://feed1.examples.com/..." Username="..." Password="..." />
    <Feed Url="https://feed2.examples.com/..." Username="..." Password="..." />
</RestoreSources>
```
And like anything property-based, it could be `Password="$(Feed1Key)"`, and `/p:Feed1Key={GITHUB_TOKEN}`, or the URL could be a param...or anything really. I am unsure if an existing MSBuild `/p:` syntax supports an element with multiple attributes like this (not that I've ever tried to use at least), but that'd be an option too.

Anyway, just some ideas to get the discussion rolling on this!

**Comment by ericsampson** [comment]
It looks like `RestoreSources` is [documented](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties) to currently accept a semi-colon delimited list, FWIW. Given that it supports N sources, I'm not sure what the distinction is between it and `RestoreAdditionalProjectSources` then. meh.

For our use case, I'd definitely prefer to have the source and token in two separate parameters rather than having to smush (and potentially encode) them together in the build system as something like `https://{apiKey}@example.com/feed/blah`. 

Thanks for the spitballing Nick : )

**Comment by ericsampson** [comment]
@NickCraver does this proposal look familiar? :)
https://github.com/NuGet/Home/issues/6045#issuecomment-337814965

**Comment by nkolev92** [comment]
hey all, 

Thanks for the discussion. 

We have a duplicate ask in https://github.com/NuGet/Home/issues/6045.
