### ISSUE TITLE
im a noob at this, but i cant get this command line to work.

### ISSUE THREAD

**Issue by jerrylindstrom** [NuGet/Home#10180]
Yea so i have a problem with this command. i had to this for school and the teacher said that we should follow the tutorials but i dont understand what i should do now since the tutorial doesnt explain it. im using visual studio 2019.

if you need any more info i can send a picture

Very helpful if you can zip a project and paste into this issue!

![nimetön](https://user-images.githubusercontent.com/45565768/96981886-6908ed80-1528-11eb-9566-9ff3fca76f44.png)

**Comment by donnie-msft** [comment]
Does that nupkg file exist in the directory you're in?

**Comment by jerrylindstrom** [comment]
The problem is that i have no idea. I dont think ive created a file with
that extension. But i dont know how to make one either :/

**Comment by sintecnos-lucabiffi** [comment]
@jerrylindstrom try to follow some tutorials on how to create a nuget package and how to push it. You'll need nuget spec + nuget pack before the push. Or simply get an existing nuget package somewhere else so you can try to push it.
Your push is probably failing because you didn't create or provide a _.nupkg_ to push.

**Comment by jerrylindstrom** [comment]
Oh yea thats true, ill have to look into it. Thank you for the help :)

**Comment by aortiz-msft** [comment]
@jerrylindstrom - Here's a good place to start: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli.

Would love feedback on how easy the onboarding docs are.
