### ISSUE TITLE
There should be some error or warning in Error List or Output window when trying to install a package already packed with an invalid embedded icon format

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10310]
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.6969
VS Version: Master\30719.130
OS: Windows-10-Enterprise-19H2
## Detailed repro steps 
1.	Make a package (called InvalidFwPackage) with an invalid embedded icon format before fixing of bug 9311 (please follow the steps of the bug).
2.	Create a Console (.NET Framework 4.8) project in VS and open the PM UI.
3.	Click the settings button on PM UI and add the invalid package source into “Options->NuGet Package Manager->Package Sources”.
4.	Select the invalid package source in the “Package sources” dropdown list in PM UI and go to “Browse” tab to try to install it.
## Expected
There should be some error or warning in Error List or Output window.
## Actual
The package already packed with an invalid embedded icon format can be installed without any error or warning as below.
![ExistInvalidIcon](https://user-images.githubusercontent.com/20632625/99805950-36c6cc00-2b78-11eb-8dfe-168953238b43.JPG)
## Note
1.It is not a regression, we think that should be a part of the fixing of bug 9311.
2.InvalidFwPackage is the package with an invalid embedded icon format created before fixing of bug 9311.
[InvalidFwPackage.zip](https://github.com/NuGet/Home/files/5573816/InvalidFwPackage.zip)

**Comment by donnie-msft** [comment]
@v-luzh Anything in the Output (Package Manager) window? I think sometimes we write to Output and not also to Error List.
@dominoFire is this a regression from https://github.com/NuGet/Home/issues/9311?

**Comment by nkolev92** [comment]
This is not a regression, and honestly while you could argue inconvenience, not something worth fixing at this point.

NuGet covers the complete lifecycle of packages, creation primarily through pack, and consumption through install/restore. 

At creation time NuGet may do certain validations and raise:

* Errors:
  * The id contains invalid characters. 
  * License file cannot be found in package.
  * Icon file cannot be found in package. 
  * Platforms are missing a version . 

* Warnings: 
  * Assembly outside of lib folder.
  * Assembly in `lib/`
  * LicenseUrl is deprecated. 

Not all errors and warnings are made the same. Some are critical to the consumption of the package, such as a valid id and a valid version. 
Others such as icon presence are important as far as `package quality` goes, but they not usage blockers.

Restore/installation is significantly more permissive and that's by design. 
Restore requires the package id, version and nuspec schema to be honored. 
The rest of the failures will be detected if deemed important for using the package for building. 

This is all to say that, *restore* & *install* do not do the same validations as pack. 
And this is a good design, because a lot of the pack validations are a point in time decision, so it's likely that there are packages that were already created prior to these validations, so unless this is an absolutely critical, breaking problem, we'd just ignore it. 

Now the restore side behavior is not perfect and there are bugs, like https://github.com/NuGet/Home/issues/1385, but the general approach of *not doing the same validations* at restore time stands.

**Comment by v-luzh** [comment]
@donnie-msft,there is no error or warning in Output (Package Manager) window either. 
@nkolev92, thanks for sharing your opinion. We mean there should be some error or warning similar with NU5045 in Error List/Output window when installing an exist package (created already) with invalid package format. Update the title. Please close it if you think that is not worth fixing.

**Comment by donnie-msft** [comment]
@nkolev92 Could the UI detect that nothing was installed in a simpler way without getting specific errors. The UI could expect 1 install and see 0 installs occurred?

**Comment by zivkan** [comment]
@donnie-msft the package was installed. It's just the package icon shows the NuGet default, because the package contains an invalid icon.

@v-luzh was suggesting that the package should not be installed, but I'm with @nkolev92 on this. The package consumer has nothing actionable they can do. And the primary purpose of a package is to add assemblies, content and/or msbuild files to the build. The package icon is just a visual convenience that is not the "primary business activity" of a package manager, so it seems unfriendly to me to prevent a package consumer from using an otherwise valid package, just because the package author made a mistake with the icon (and the package source didn't reject it on upload).

I'd say this is by design.

**Comment by donnie-msft** [comment]
zivkan, thanks for clarifying.

I have a suggestion to add status indicators to these icons. I believe this may resolve the concern: https://github.com/NuGet/Home/issues/10122
