### ISSUE TITLE
IntermediateOutputPath doesn't affect some NuGet related files

### ISSUE THREAD

**Issue by tmds** [NuGet/Home#10333]
When setting `IntermediateOutputPath`, most files that are by default put under `obj` are placed at that location, except for some files that are NuGet related.

Reproducer:

```
$ dotnet new console -o console --no-restore
```
Add this to console.csproj:
```
    <IntermediateOutputPath>/tmp/intermediate</IntermediateOutputPath>
```
Now:
```
$ dotnet build
```
Most files moved to `IntermediateOutputPath`:
```
/tmp/intermediate/
└── net5.0
    ├── apphost
    ├── console.AssemblyInfo.cs
    ├── console.AssemblyInfoInputs.cache
    ├── console.assets.cache
    ├── console.csprojAssemblyReference.cache
    ├── console.csproj.CoreCompileInputs.cache
    ├── console.csproj.FileListAbsolute.txt
    ├── console.dll
    ├── console.GeneratedMSBuildEditorConfig.editorconfig
    ├── console.genruntimeconfig.cache
    ├── console.pdb
    └── ref
        └── console.dll
```
Some remained under `obj`:
```
obj/
├── console.csproj.nuget.dgspec.json
├── console.csproj.nuget.g.props
├── console.csproj.nuget.g.targets
├── project.assets.json
└── project.nuget.cache
```

**Comment by zivkan** [comment]
@tmds [MSBuild reads these files from `MSBuildProjectExtensionsPath`](https://github.com/dotnet/msbuild/issues/1603) due to MSBuild import ordering issues. Furthermore, as described in that issue, you will need to set that path either in `Directory.Build.props`, or change the `Sdk` syntax in your csproj so that you can change its value before the SDK's props are imported.

Although it's not the easiest to find, it's [documented on our page about msbuild based restore](https://docs.microsoft.com/nuget/reference/msbuild-targets#restore-properties).

**Comment by tmds** [comment]
> you will need to set that path either in Directory.Build.props

This doesn't work for me because $(Configuration) is not yet set, and I want to change the path based on that.

> or change the Sdk syntax in your csproj so that you can change its value before the SDK's props are imported.

ok.
It would be nice if this would be possible using the default Sdk import.
