### ISSUE TITLE
.NET 5: Unable to install some .NET tools (dotnet tool install)

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10349]
Issue description https://github.com/dotnet/sdk/issues/14547#issue-743150997

@msallin I am unable to reproduce this issue on WSL (Windows Subsystem for Linux) and Windows. Executed `dotnet tool install PowerShell --tool-path ./tools/ -v d` command on WSL and on Windows with a different value for `--tools-path`. Both the commands succeeded. 

Transferring this issue to `NuGet` side. If you can provide us a repro that could be great to troubleshoot this issue.

_Originally posted by @kartheekp-ms in https://github.com/dotnet/sdk/issues/14547#issuecomment-737585358_

**Comment by msallin** [comment]
I'm also unable to reproduce it when not using our Jenkins-Slaves. In the meantime, I tried to use NuGet directly (without Artifactory). It's the same result.

**Comment by zkat** [comment]
This really seems like something funky's going on with your Jenkins, but it's not clear to us what kind of configuration issue might be causing it, or if it's something more serious going on with your Jenkins machine. Any chance you could dig into it further and see if there's a way to isolate a repro that we can look into? The error itself makes sense to us but not how you might have gotten there.

**Comment by msallin** [comment]
Hi

I'm not able to reproduce it. As I've no clue what the problem might is, I've no idea how I could setup an environment.
You state that "The error itself makes sense to us but not how you might have gotten there."
Why do you think the error makes sense? When does this happen and how does it play together?

I see different speculations in the original ticket:
- Race condition (or not, because it was in an old version)?
- ACL issue (I don't think so)?
- Blocked ports (I think this could be, however, still the exception is misleading IMHO)?
- User error (don't know what that means)?

**Comment by zkat** [comment]
The missing file is a temp file that should have been written, and it's part of some atomic-writes code for extraction. Stuff like this tends to be because of some weirdness with filesystems going on, or operating system locks, but you're not on Windows, so it's hard to think of why that temp file might not be getting written, much less only on a particular configuration (your Jenkins machine). Without a more concrete repro that we can look into further, I'm afraid there's not much we can do here :/

Is there any chance you can test on a _different_ Jenkins machine with a similar setup, to see if we can isolate it to that particular machine?

**Comment by kartheekp-ms** [comment]
This may or may not be related. But looking at this [comment](https://github.com/NuGet/Home/issues/3324#issuecomment-256293851) about long paths in Jenkins environment, I just wanted to check you are experiencing this issue [due to long paths](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path).

**Comment by msallin** [comment]
I am on vacation and will come back to it afterwards.

I wanted to remind about what is known:
- It worked with .NET Core 2.0, 2.1, 3.0 and 3.1 (and still does)
- It doesn't work with .NET 5.0
- It is not slave depended (however, every slave uses the same docker image)
- Reset all caches (directories which are mounted & recreate the slave) doesn't change anything
- Setting env.NUGET_CERT_REVOCATION_MODE = 'offline' is a workaround
- It seems that only global tools from NuGet.org are affected but not own global tools (we don't sign our packages, that may be the reason)

**Comment by msallin** [comment]
> This may or may not be related. But looking at this [comment](https://github.com/NuGet/Home/issues/3324#issuecomment-256293851) about long paths in Jenkins environment, I just wanted to check you are experiencing this issue [due to long paths](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path).

See paths in the logs: https://github.com/dotnet/sdk/issues/14547#issue-743150997
I don't think they are a problem. And, as stated, it works for all NuGet packages expect for global tools and it works for .NET 3.1

**Comment by aortiz-msft** [comment]
> Setting env.NUGET_CERT_REVOCATION_MODE = 'offline' is a workaround

In NET5.0 we added package signature verification, so this might be related.

@kartheekp-ms  - Would you mind trying to repro this problem locally?

**Comment by zivkan** [comment]
Triage: Closing stale issue as no repro.

Please create a new issue if this problem persists.

**Comment by msallin** [comment]
Still the same issue with the newest sdk version.

**Comment by kartheekp-ms** [comment]
@msallin - When you say newest sdk version, I imagine it is `net6.0` sdk. In this [comment](https://github.com/dotnet/sdk/issues/14547#issuecomment-732114012) you have mentioned that `The problem is "solved" by using env.NUGET_CERT_REVOCATION_MODE = 'offline'. `  We disabled package signature verification on Linux/Mac as announced in https://devblogs.microsoft.com/nuget/net-5-nuget-restore-failures-on-linux-distributions-using-nss-or-ca-certificates/ blog. Are logs still showing that the restore is failing after waiting for a few minutes? For e.g. [`One example is PowerShell. After ~17min it fails with the following error message. `](https://github.com/dotnet/sdk/issues/1454709)

**Comment by msallin** [comment]
A mistake on my side. All fine now. Thank you!
