### ISSUE TITLE
Is there a "hidden" property that can be set for contentFiles?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#10355]
When reporting a [VS problem](https://developercommunity2.visualstudio.com/t/Solution-Explorer-is-showing-nuget-packa/1271799?port=1025&fsid=47c8a867-5f1b-4af4-ab23-1a1b841d2219&entry=myfeedback#TPIN-N1276054), I was told that the reason for the unwanted behavior (contentFiles showing up as project files in sln explorer) was that a package was incorrectly authored and should have included the files as "hidden" instead of "contentFiles". 

I cant find a hidden attribute or element in the nuspec.xsd.  Is the info I was given correct and the documentation is out of date, or is the opposite true?

**Comment by kartheekp-ms** [comment]
> contentFiles showing up as project files in sln explorer

We have another tracking [issue](https://github.com/NuGet/Home/issues/4856) for this request. As per this [comment](https://github.com/NuGet/Home/issues/4856#issuecomment-705802910), `contentFiles` are already visible under package nodes and the tracking issue linked above is to remove content files from the rest of the tree. Please feel free to comment in the linked issue or upvote so that we can prioritize it based on the customer impact.

![image](https://user-images.githubusercontent.com/52756182/101424269-a1ce0d80-38af-11eb-80e5-a7b9bae80cb7.png)


I don't see `hidden` option for [`contentFiles`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files). The closest attribute is to `exclude` under `contentFiles` element to exclude files from the package for e.g. see [doc](https://docs.microsoft.com/en-us/nuget/reference/nuspec#example-contentfiles-section) which is not the ask here.

**Comment by StingyJack** [comment]
@kartheekp-ms  the ask here had a few facets, which I think you have addressed all of except for the one thats a MSFT internal matter (why and how the MSFT developer community triage team member came to be misinforming a customer in this way), and my involvement with that stops as soon as I can get your (or someone at MSFT's) word that it will be followed up on and addressed.

**Comment by kartheekp-ms** [comment]
@StingyJack - I didn't make it explicit here as it is an internal matter. I will discuss about this in our internal team meeting and address the feedback. Thank you.
