### ISSUE TITLE
How do I define an internal assembly in a NuGet package?

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10381]
---
**Issue moved from dotnet/sdk#14906**
- Please respond to @lg2de.

---

_From @lg2de on Wednesday, December 9, 2020 5:12:25 PM_

I want to define a NuGet package that contains two assemblies, one that is directly referenced by the consumer of my package and another one that is only needed at runtime and its APIs should not be visible to the consumer.

I've created a github repository to demonstrate the constellation in detail:
https://github.com/lg2de/NuGetDependencyDemo

The assembly `BaseLibrary` is directly referenced by the assembly `DependentLibrary`.
`BaseLibrary` is an external assembly not available as NuGet package.
From `DependentLibrary` my NuGet package is created.

When creating project just referencing the NuGet package, the assembly `BaseLibrary` is missing in the build output. (In the mentioned repository you can find this constellation [here][1].)
Of course, in this case the application raises an `FileNotFoundException` for `BaseLibrary`.

So I've added is to my NuGet package [using targets file directive][2].

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)BaseLibrary.dll" Visible="false">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

The assembly now available in the output folder, but I still get the same `FileNotFoundException`.
This seems to be new behavior in dotnetcore: Assemblies are not implicitly loaded.
The assembly is missing in `ConsoleWithNugetReference.deps.json`.

To solve this now have to [load manually before it is first used][3].

```c#
var location = Path.GetDirectoryName(typeof(Program).Assembly.Location);
AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.Combine(location!, "BaseLibrary.dll"));
```

All this is very complicated and tedious!

So, how can I define a NuGet package that contains two assemblies, one that is directly referenced by the consumer of my package and another one that is only needed at runtime and its APIs should not be visible to the consumer?

  [1]: https://github.com/lg2de/NuGetDependencyDemo/tree/11962aa812a566efbb5782876692ebb1df574fa9
  [2]: https://github.com/lg2de/NuGetDependencyDemo/commit/0d67ebaf3648d06322844f03a99609dd642506b7
  [3]: https://github.com/lg2de/NuGetDependencyDemo/commit/e2dbc8c0265217164f4022347f1c7e65125e4c7a

**Comment by donnie-msft** [comment]
@lg2de The layout for a package in this scenario is described here: https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects
Let us know if that gets you on the right track. Unfortunately, I don't believe we have any tooling to help author a package in this layout.

**Comment by lg2de** [comment]
Hey @donnie-msft, thanks for your response. I think it goes in right direction. There is described a difference between compile and runtime assets. That is what I need.

The page is a bit confusing to me. I had to read the article several times to understand what it was actually trying to describe.
Further it would be great to have information whether this also applies to dotnetcore and net5.0.

> I don't believe we have any tooling to help author a package in this layout.

Does this mean I (just) need to write my own nuspec file?

Do I really need to add some assemblies twice (resulting into double space consumption)?

**Comment by donnie-msft** [comment]
Hello. I think based on this line, I would assume any Core (and NET5) TFM would work, since they always use PackageReference.

> When a project uses a package with PackageReference 

Regarding tooling, I was relaying a comment from @zivkan, who can hopefully clarify. 
zivkan, we may need to clarify these docs..? Especially if what I just said is a wrong interpretation :)

**Comment by zivkan** [comment]
If you want your package to be compatible with package consumers using packages.config, then unfortunately yes, the only way to create the `<references>` section, as per the docs, is to use a custom nuspec file.

If you're fine with only supporting package consumers using PackageReference, then no, it's not necessary to use a nuspec, but you'll still need to do quite a bit of customization in your project file. Firstly, our MSBuild pack targets [doesn't have a built-in way to include project reference output assemblies](https://github.com/NuGet/Home/issues/3891), so you'll need to use one of the workarounds provided in that issue.

Then, you'll need to find a way to copy the assembly(ies) you want to be provided to the compiler into the `ref/<tfm>` folder, as per the instructions in the doc Donnie linked. I'd suggest using [the TargetsForTfmSpecificContentInPackage extensibility](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage). Note, that [`net5.0-windows` TFMs need to be handled carefully](https://github.com/NuGet/Home/issues/10063), and need to be handled a little differently.

Finally, the instructions that Donnie linked, puts all the runtime assemblies in `lib/<tfm>`. This means that package consumers using packages.config will be able to use your package, including the assemblies you don't wish for them to access directly. In order to prevent this, and completely block packages.config projects from using your package, you should set the [`IncludeBuildOutput` property to false](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#output-assemblies), and use `TargetsForTfmSpecificContentInPackage` to copy all your runtime assemblies somewhere under `runtimes/` instead. According to the [.NET team's runtime identifiers docs](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#rid-graph), all RIDs eventually map back to the `any` RID, so you should be able to put your assemblies in `runtimes/any/<tfm>/lib/*.dll` if you don't need RID specific assemblies. If you do need RID specific assemblies, then you can't use assemblies in `lib/<tfm>/` anyway, and you'll still need to do this.

My advice to any package author doing something non-trivial is to work at the problem "backwards". nuget.exe allows you to pack a folder and the folder structure becomes the package structure. Maybe NuGet Package Explorer is another way. Or just start off with a simple nupkg and use any zip program to modify the contents of the file. Anyway, start off with a folder with contents
```text
ref/net5.0/my.dll
runtimes/any/net5.0/lib/my.dll
runtimes/any/net5.0/lib/other.dll
```
use `nuget.exe pack` to create this into a nupkg, and test this nupkg in a sample project. If this works as you desire, then you know the desired package layout, and then start trying different things in your csproj to get `msbuild -t:pack` or `dotnet pack` to generate the same package layout. Spending a lot of time trying to get msbuild pack to generate a package, just to find out that the package layout doesn't do what you want will increase frustration.

Also, consider what problem you're really trying to solve by preventing your package customers from accessing the "internal" assemblies. If you control the other assemblies, maybe you can achieve a similar result by changing everything from `public` to `internal` and use `InternalsVisibleTo` to give your public API assembly access, and then you don't care if your internal DLL is passed to your package customers' csc.exe, because they won't have any public APIs to call anyway. Or maybe trying to prevent package customers from calling APIs on the internal assemblies is just technical idealism that doesn't really matter. Particularly if the public APIs in your internal library are stable. Anyway, above I outlined the steps you can take if you wish to pursue this.

**Comment by bitbonk** [comment]
> Do I really need to add some assemblies twice (resulting into double space consumption)?

I have this question too. Did I miss the answer to to this, here? To me it looks like that I always (even if I do not need packages.config support) have to put the assemblies that should be referenced both at compile time and at runtime into `ref\<ftm>` _and_ `lib/<tfm>`. This is redundant and would increases the size of the nuget pakage unnecessarily.

**Comment by aortiz-msft** [comment]
Closing since the original question has been answered. Please feel free to post additional questions as new issues.
