### ISSUE TITLE
Optionally validate PackageDescription and throw if not set

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#10405]
`PackageDescription` is always set to a default value if both `Description` and `PackageDescription` are empty: https://github.com/NuGet/NuGet.Client/blob/5e1970e323f9f55794c6a77562c5535c12d5c2a4/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L35.

It's not uncommon to require a project to set a PackageDescription and throw if none is set. Instead of every consumer adding an InitialTarget for the validation, NuGet should validate the property before the `PackTask` is invoked. Because this would be a breaking change, the validation could be an opt-in via an msbuild property, i.e. `<ValidatePackageDescription />`.

**Comment by zkat** [comment]
I agree that, in an ideal world, this would be both required and not-defaulted. I don't really see a point in having a default description here, but that's what we've got right now. Unfortunately, this would be a breaking change, and I don't think the value outweighs the cost in this case. An opt-in in this case would probably be pointless, because if you're remembering to opt-in, you may as well remember to add a custom description.

As such, I'm going to be closing this. Thanks for taking the time to submit it!

**Comment by ViktorHofer** [comment]
@zkat NuGet.exe emits a warning and that's what I believe would be appropriate here as well: Emitting a warning, if the package description isn't explicitly set to indicate that a default description will be used.

That shouldn't be a breaking change then?

**Comment by ViktorHofer** [comment]
ping @zkat
