### ISSUE TITLE
Unexpected build assets picked for net5.0-windows

### ISSUE THREAD

**Issue by huoyaoyuan** [NuGet/Home#10418]
## Details about Problem

NuGet product used: Visual Studio

VS version (if appropriate): 16.8.3/16.9P2

OS version (i.e. win10 v1607 (14393.321)): 19042

Worked before? N/A

## Detailed repro steps so we can see the same problem

Context: https://github.com/dotnet/reactive/issues/1461

Package: System.Reactive 5.0.0

The package structure:
```
lib\
- (Other frameworks)
- netcoreapp3.1\...
- net5.0\...
- net5.0-windows10.0.19041\...
build\
- netcoreapp3.1\...
- net5.0\...

(no build\net5.0-windows10.0.19041 present)
```

When installing into `net5.0-windows10.0.18362`, `lib\net5.0` and `build\net5.0` are selected, as expected. But when installing into `net5.0-windows10.0.19041`, `lib\net5.0-windows10.0.19041` is selected with `build\netcoreapp3.1`, results in incompatible behavior. `lib\net5.0-windows10.0.19041` is expected to work with `build\net5.0`.

Please confirm if this is a bug, or a counter-intuitive behavior.

Note: the VS project system UI doesn't show the targets from `build\netcoreapp3.1`, but displays a warning icon.
WinUI project can only be built with VS build, not `dotnet build`.

**Comment by zkat** [comment]
This seems to actually be a Pack issue right now?

Looking at the nuspec for System.Reactive:

![image](https://user-images.githubusercontent.com/17535/104793132-0fdedd80-5756-11eb-9235-83795d555abf.png)

**Comment by huoyaoyuan** [comment]
Yes it should be. NuGet Package Explorer doesn't show `frameworkReference` tag so I didn't mention it.

This looks like to be intentional. They explicit sets `UseWPF`. But it makes it unusable for WinUI.

Can there be any indications to force `net5.0` instead of `net5.0-windows10.0.19041` get picked?

**Comment by zkat** [comment]
Alright, so I'm not really sure where this issue is coming from, but I know it's somewhere in the restore _while creating the Reactive package_.

I found this in the binlog:

![image](https://user-images.githubusercontent.com/17535/105614288-53040680-5d7d-11eb-8d17-2bc4b6544e31.png)

Which suggests this is what's causing this to happen:

![image](https://user-images.githubusercontent.com/17535/105614353-a70eeb00-5d7d-11eb-97a7-002f6c9abc66.png)

So... this seems to run pretty deep, and the only clue I have at this point is that this is happening through the inclusion of some other package that's forcing it, or it's a bug in dotnet/msbuild or something?

/cc @nkolev92 @zivkan in case this rings a bell and they know how to follow the thread further.

**Comment by huoyaoyuan** [comment]
This should be the package requiring reference in unfriendly form. NuGet is working correctly here.

**Comment by zivkan** [comment]
@zkat if you wanted to find where `_EnableWindowsDesktopNetCoreFrameworkReferences` is being defined, you have a few options:

1. In the binlog viewer, right click the csproj, and there should be an option similar to "preprocess". This will copy-paste all imported msbuild files into one huge project file, which you can then use any text search
2. You can generate the preprocess file on the command line as well with `msbuild -pp:project.txt` or `dotnet msbuild -pp:project.txt`, then open `project.txt` in your favorite text editor.
3. If you feel it's likely that the propery comes from the .NET SDK, rather than a package, you can use your favorite text editor to search the .NET SDK install directory
4. In this case, `_EnableWindowsDesktopNetCoreFrameworkReferences` is unique enough such that a GitHub code search [uniquely identifies it coming from the dotnet/wpf repo](https://github.com/search?q=_EnableWindowsDesktopNetCoreFrameworkReferences&type=code) : https://github.com/dotnet/wpf/blob/08c104b43528c7feb646c5094f612556fcdb6dd7/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets#L59-L62

Having frameworkReferences be defined in the package so that consuming projects get it as well made sense in netcoreapp3.1 where there weren't separate TFMs for "desktop" and "console" apps, but it makes less sense with net5.0 and later. On the other hand, perhaps the WPF and WinUI teams need to take this into account and improve their SDKs to take into account how NuGet works and how customers expect to use packages. I don't know if you had intended to follow up with partner teams to improve customer experience, or just trying to figure out if there was a NuGet bug or not. As the customer mentioned, NuGet is working as designed (frameworkReference was designed for .NET Core 3.x).

> Can there be any indications to force net5.0 instead of net5.0-windows10.0.19041 get picked?

@huoyaoyuan no, but there's a [feature request](https://github.com/NuGet/Home/issues/7416) for this that you could upvote (👍).
