### ISSUE TITLE
Package source path completely ignored in latest NuGet Package Manager versions

### ISSUE THREAD

**Issue by NGame1** [NuGet/Home#10429]
Hi there, 
VS2019 and also the latest V2017 updates for Windows with the new versions of NuGet Package Manager version having an issue with downloading location. 

I specified package source path to 
E:\Nuget but still NuGet package manager save packages to 
C:\Users\{UserName}\.nuget\packages
C:\Microsoft\Xamarin\NuGet
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages

How can I specify just one path, JUST ONE to store all NuGet packages there?
Or, at least change the default "C:\Users\{UserName}\.nuget\packages" path to my own path?

**Comment by ramtinak** [comment]
Hi,
I'm facing this problem too, 
It seems changing folder in the Visual Studio settings for Nuget Package Manager doesn't effect anything. I have VS 19 and 17 as well but both of them has this problem.
I even removed the .nuget in `C:\Users\{UserName}\` folder but it will create it again after first attempt to download something from Nuget.

Please fix this problem.

Thanks in advance.

**Comment by heng-liu** [comment]
Hi, the package source path in VS is specifying where do you want to download packages from.
However, the global-packages folder is where NuGet installs any downloaded package. Each package is fully expanded into a subfolder that matches the package identifier and version number. Projects using the PackageReference format always use packages directly from this folder. When using the packages.config, packages are installed to the global-packages folder, then copied into the project's packages folder.
Please refer to the following documents for more details:
 [What happens when a NuGet package is installed?](https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process)
[Managing the global packages, cache, and temp folders](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
