### ISSUE TITLE
[Question] How to obtain the list of project references changed to package references during nuget pack?

### ISSUE THREAD

**Issue by TheNybbler** [NuGet/Home#10473]
I need to get a list of project references that are transformed into package references when building a solution in Visual Studio. Is there an extension point in the Nuget.Pack.Targets file that can provide me with these details?

I've asked the [same question on StackOverflow](https://stackoverflow.com/questions/65808800/how-to-obtain-the-list-of-project-references-changed-to-package-references-durin), and there is more detail there on the scenario that I'm trying to resolve.

NuGet product used (Visual Studio):
Product version: 16.8.3

**Comment by JonDouglas** [comment]
Hey @TheNybbler 

Thanks for opening an issue!

Because this is a question, we encourage you to use Stack Overflow and Microsoft Q&A. If you don't get an answer in a week or so, please open a "GitHub Discussion"!

You can learn more about this here:

https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue

Thus we're closing this issue for now.
