### ISSUE TITLE
Add integration tests for all `dotnet new` templates

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#10553]
This is one of the corrective actions related to https://github.com/NuGet/Client.Engineering/issues/727

**Comment by zivkan** [comment]
This issue does not explain what the expectations are, and the linked issue is also missing sufficient context for anyone who either was not in the meeting, or forgot the details of the meeting.

The problem was that packing a Razor classlib project failed.

So, the goal is not to write integration tests for the `dotnet new` command, the goal is that we should have tests that restore and pack relevant project types available in `dotnet new`, so projects that work "differently" than a simple classlib project are tested.
