### ISSUE TITLE
Are the mixed TFM issues should be reported by Nuget?

### ISSUE THREAD

**Issue by Csharp-Girl** [NuGet/Home#10637]
Given a project whose dependency tree is described as follows:
![Case1](https://user-images.githubusercontent.com/80234440/110269927-b1203c80-7fff-11eb-847a-4552f776ea4c.png)

According to the "direct dependency wins" rule, C 2.0.0 (TFW: Standard 2.1) can be actually installed instead of C 1.0.0 (TFW: Standard 2.0). In such scenario, B 1.0.0 (TFW: Standard 2.0) will reference C 2.0.0  (TFW: Standard 2.1).

However, in principle, the Standard 2.0 projects cannot depend on the Standard 2.1 packages (backward compatibility criteria).
I have tested this case on the latest version of nuget, and it did not report any warnings.
Is this case safe for the client projects? 

Thanks for your help.

Best regards.

**Comment by Csharp-Girl** [comment]
@nkolev92 hi, could you give me some insights? I am confused about this scenario. Thank you.

**Comment by zivkan** [comment]
yes, it's safe to do. Well, ultimately it's up to C's package author "doing the right thing", but usually it should work.

TFMs are used to define what APIs that Base Class Libraries (BCL) provide at compile time. Technically, I think only NuGet uses it for package/project compatibility, and the .NET SDK uses it to determine which "reference assemblies" to pass to the compiler. So, I think that the compiler itself doesn't care about what target framework each assembly was provided, although I'm not so confident about that. Remember that what's being compiled in your example is "project", not "B". During "project"'s compilation, "b" is already compiled, hence the fact that it references c.dll, and a different version of c.dll is being used for "project"'s compilation is not important.

At runtime, the "main"/entry point assembly's Target Framework is read to determine which runtime to load, but after that target framework doesn't matter. The runtime has no idea that B.dll was compiled against C.dll's .NET Standard 2.0, and I'm fairly confident it doesn't check what target framework other assemblies were compiled with. You can verify this yourself by using the tool "IL Spy" to load/decompile an assembly, and look at the "references" node to see what metadata it has about the other assemblies it calls into.

Therefore, as long as the new assembly has the same APIs, or is a superset of the APIs that B.dll was compiled against, there's no problem.  .NET Standard was designed such that each version is a superset of previous versions, so that will work. Therefore, it's just up to C.dll. As long as it doesn't use any `#if` blocks to provide public APIs in its .NET Standard 2.0 version, which do not exist in the .NET Standard 2.1 version, then there should be no risk of runtime errors. Even if C.dll does have some netstandard2.0-only APIs, as long as B.dll doesn't call them, there still won't be runtime errors.

What we have seen in the past, especially with packages adding initial support for .NET Standard in the early days of .NET Core, was their .NET Framework assemblies would have the filename `package.dll`, but then they'd name their .NET Standard version of their assembly `package.netstandard.dll`.  This is a big problem, because then another package, which only has .NET Standard assemblies will have a reference to `package.netstandard.dll`, but when an app using .NET Framework uses both packages, it will use `package.dll`. When the second package tries to call into the first package, it will fail at runtime because `package.netstandard.dll` doesn't exist on disk. So, if you're authoring a package, make sure that it always keeps the same assembly name, both within the package (different TFMs should use the same filename), and across different package versions as well.

**Comment by Csharp-Girl** [comment]
@zivkan Thanks a lot for your detailed explanations. I learned a lot from your comments. : )

**Comment by erdembayar** [comment]
I'm closing this one since I believe it's already answered. 
But definitely let us know if it's not. Thank you for your feedback and happy coding!
