### ISSUE TITLE
Upgrade NuGet.Client arcade version to 6.0

### ISSUE THREAD

**Issue by crummel** [NuGet/Home#10646]
Arcade-powered source-build requires Arcade 6.0 or higher.  NuGet.Client will need to be upgraded to support ArPow.

**Comment by erdembayar** [comment]
@crummel 
Hi. Thank you for your contribution. It looks you already have PR created. Can you self assign ticket for yourself?

**Comment by nkolev92** [comment]
@erdembayar 
He can't assign, he's not part of the org.

**Comment by zivkan** [comment]
Also the pull request explicitly says that it won't work/can't be tested until this issue is complete. The PR does not fix this issue.

@crummel I've looked into onboarding to the Arcade SDK about a year ago, but due to NuGet's heavy build customization in our `build/*` directory, adding the Arcade SDK broke our build and seemed to require a lot of effort to get working. In addition, from my very limited knowledge of Arcade, it appears to be fundamentally incompatible with all our release scripts, so we'll have to rewrite those too. And this means that our ability to service existing releases that are still in LTS will be significantly impacted.

What's the timeframe that onboarding onto the Arcade SDK is required? Will DncEng/SourceBuild teams be creating pull requests to onboard NuGet.Client onto Arcade, or do you require us to change our schedule to do this work ourselves?

**Comment by aortiz-msft** [comment]
Closing as per last comment from zivkan.
