### ISSUE TITLE
Clients terminate the restore procedure, when any DNS failure is met.

### ISSUE THREAD

**Issue by zhhyu** [NuGet/Home#10661]
## Details about Problem

NuGet product used: NuGet.exe

Product version: 5.6.0

It seems that clients terminate the restore procedure, when any DNS failure is met.

## Repro steps and/or sample project

For example: "NuGet Gallery" (https://github.com/NuGet/NuGetGallery)
1. Clone the repository;
2. Update "NuGet.config" to use the only feed: "apidev.nugettest.org";
3. Clear local caches: `dotnet nuget locals all --clear`
4. Run a clean solution restore: `nuget restore .\NuGetGallery.sln -NonInteractive -Verbosity detailed`

("apidev" feed is in a not stable status, and the intermittent DNS failures are expected but not all times. Retry is needed to reproduce this issue.)

### Verbose Logs

One sample of failure logs:

![image](https://user-images.githubusercontent.com/41028779/111098861-966b2d80-8501-11eb-8e29-38c5a5851f52.png)

**Comment by nkolev92** [comment]
Copying my response from the e-mail: 

NuGet PackageReference restore fails fast on the first network failure, that's [documented](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-and-sources) and is consistent across all tools.   
packages.config is more permissive to network failures and will try to reach all sources.

What you are suggesting the problem is here?

**Comment by nkolev92** [comment]
By default all the NuGet requests retry 3 times, https://github.com/NuGet/NuGet.Client/blob/0158a5946a2e425943ac4f93e50e491a18b6f4e0/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceRequest.cs#L58. 

As such intermittent failures should be handled.
