### ISSUE TITLE
textfile.nuspec failing to build the project after upgrading to Visual Studio 2019 16.9.1 from Version 16.8.7

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10663]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/textfilenuspec-failing-to-build-the-pro/1368425)._

---
[regression] [worked-in:16.8.0]
I have a .NET standard project which is having textfile.nuspec. When i was building the project it is failing with error. 
After updagrading to latest Visual studio 2019 16.9.1. It was working without any issues on 16.8.X
 
Task Parameter:RestoreOutputPath=C:\temp\Formatters\MyProject\obj\
1>    C:\Program Files\dotnet\sdk\5.0.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : Object reference not set to an instance of an object.
1>    System.NullReferenceException: Object reference not set to an instance of an object.
1>       at NuGet.Packaging.PackageBuilder.<>c.b__173_1(NuGetFramework groupFramework)
1>       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
1>       at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
1>       at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
1>       at NuGet.Packaging.PackageBuilder.ValidateReferenceAssemblies(IEnumerable`1 files, IEnumerable`1 packageAssemblyReferences)
1>       at NuGet.Packaging.PackageBuilder.Save(Stream stream)
1>       at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
1>       at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
1>       at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
1>       at NuGet.Commands.PackCommandRunner.RunPackageBuild()
1>       at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner)
1>       at NuGet.Build.Tasks.Pack.PackTask.Execute()
1>  Done executing task "PackTask" -- FAILED.
1>Done building target "GenerateNuspec" in project "MyProject.csproj" -- FAILED.
1>

Thanks and Regards,.
Som

---
#### Feedback Bot on 3/14/2021, 07:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mayerj** [comment]
We also ran into this, possibly with the change from nuget.exe 5.8.1 to nuget.exe 5.9.0.  It appears that this is due to the following nuspec file content:

```
<references>
  <reference file="output1.dll" />
  <reference file="output2.dll" />
  <reference file="output3.dll" />
</references>
```

The following PR https://github.com/NuGet/NuGet.Client/pull/3691 seems to make the TargetFramework no longer optional (or at least, this code path doesn't handle it)

https://github.com/NuGet/NuGet.Client/pull/3691/files#diff-c01d3caec0c8d4f43277fdc62db8f461cfa430fdadfd6f92d46804dfbe666c20R574

I worked around it by adding a group:

```
<references>
  <group targetFramework="net45">
    <reference file="output1.dll" />
    <reference file="output2.dll" />
    <reference file="output3.dll" />
  </group>
</references>
```

This was the callstack that nuget.exe was failing with:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Packaging.PackageBuilder.<>c.<ValidateReferenceAssemblies>b__173_1(NuGet.Frameworks1204688.NuGetFramework groupFramework)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at NuGet.Packaging.PackageBuilder.ValidateReferenceAssemblies(IEnumerable`1 files, IEnumerable`1 packageAssemblyReferences)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by somtiwari** [comment]
Thanks mayerj. Its fixed the issue.

**Comment by fjoppe** [comment]
I encountered this error due to another cause. 
The filename of my nuspec file, did not end in ".nuspec".

ie. I took an nuspec original "example.nuspec", did some string find/replace and generated "example.nuspec.updated". 

Then I packed with: 
`dotnet pack mydir/my.csproj -c Release -p:NuspecFile=example.nuspec.updated" -p:NuspecBasePath="mydir"`

Caused this error. Renaming "example.nuspec.updated" to something that ends in ".nuspec" solved the problem.

Solution:
`dotnet pack mydir/my.csproj -c Release -p:NuspecFile=example.foruse.nuspec" -p:NuspecBasePath="mydir"`
