### ISSUE TITLE
Pack from Visual Studio doesn't work with embedded readme

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#10668]
## Details about Problem

NuGet product used: Visual Studio
Product version: private build 5.10.0.7298
https://devdiv.visualstudio.com/_apis/resources/Containers/7402507/VS15?itemPath=VS15%2FNuGet.Tools.vsix

## Repro steps and/or sample project

1. Create a SDK-based project (class library targeting .NET Standard 2.0 is easy way)
1. Create a README.md file in the .project
1. Open the .csproj and edit it to look something like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
```

Right click on the project node and click Pack.

Look in the produced .nupkg for a README.md ✔️ and for a `<readme>` element in the .nuspec ⚠️.

The file is there but the .nuspec is not having the `<readme>` element.

Here is my example project: [ICanHazReadme.zip](https://github.com/NuGet/Home/files/6167766/ICanHazReadme.zip)

**Comment by michael-hawker** [comment]
Just saw the announcement about the [readme file support here](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/). We already include [a readme in our project](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/main/Microsoft.Toolkit.Uwp.UI.Controls/Microsoft.Toolkit.Uwp.UI.Controls.csproj#L14) as Visual Studio supports this behavior.

It would be great to have seen this be picked up by NuGet by default as well...

FYI @chgill-MSFT

**Comment by chrisraygill** [comment]
Hi @michael-hawker! Do you mean you would like NuGet.org to display the README.txt file supported by Visual Studio if it's included in the nupkg the same way it does a README.md in the new experience?

**Comment by michael-hawker** [comment]
@chgill-MSFT yeah that's what I was thinking. If a package already has a readme.txt then it'd be cool to have that be provided in the Readme section on NuGet.org unless the package provider has provided these new metadata properties to specify an alternate filename.

**Comment by chrisraygill** [comment]
Thanks for the suggestion, @michael-hawker! I'm curious though, do you see a utility in continuing to use the README.txt now that README.md files are supported? Is there anything stopping you from changing the .txt extension to .md and calling it a day?

There is some difference in functionality. The README.md file won't pop up when installing the package the same way the README.txt does, but I'm not sure that's necessary since a link to the README is surfaced in the package details pane.

**Comment by michael-hawker** [comment]
@chgill-MSFT with WinUI (and since we have it as a dependency in the Windows Community Toolkit) there are specific changes for resources developers need to make to their project to use the library. Therefore, we want the file to pop-up in Visual Studio to instruct the developer to do so.

Only having it at install time or on the website wouldn't be sufficient, but having both or having more details available on the website as a separate readme would also be beneficial. However, we still need/want the pop-up behavior to ensure developers are getting the immediate info they need to successfully use the library.

**Comment by zkat** [comment]
This is fixed & shipped
