### ISSUE TITLE
Remove deprecated field "owners" from VS UI Details Pane

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#10666]
## Details about Problem

Even if the field "owners" in the `.nuspec` file has been deprecated, the NuGet UI in Visual Studio shows this field when the `nuspec` is created from the `csproj` and consumed directly in VS.

Visual Studio version: 16.10.0 Preview 1

## Repro steps and/or sample project

1. Create a C# .NET 5 project with the following nuget attributes:
```
<PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateNuspecDependsOn>$(GenerateNuspecDependsOn);SetPackageVersion</GenerateNuspecDependsOn>
        <PackageOutputPath>..\nuget</PackageOutputPath>

        <PackageId>MyComponent</PackageId>
        <Version>1.0.0</Version>
        <Authors>Raffaele Rialdi</Authors>
        <Company>Raf</Company>
        <PackageTags>.NET </PackageTags>
        <Description>Abcdef</Description>
</PropertyGroup>

```
2.  Publish the library / package in a local folder
3.  Reference the package from another project. The UI in VS shows the `owners` field:
![image](https://user-images.githubusercontent.com/5183152/111519167-1a6a2300-8757-11eb-9b13-90aaded7f0d4.png)

The `owners` field is not shown when browsing the public nuget website.

/cc @anangaur

**Comment by heng-liu** [comment]
Hi @loic-sharma , according to this [blog](https://devblogs.microsoft.com/nuget/managing-package-owners/), Owners is deprecated from .nuspec, but it's still used when nuget.org repo signs the package, right?

**Comment by heng-liu** [comment]
I repro with two different packages and two kinds of sources:
Check **Newtonsoft.Json** in VS UI:
1. When the source is nuget.org:
![image](https://user-images.githubusercontent.com/45407901/112073110-9afe9a00-8b30-11eb-96c7-52a653f442af.png)

2. When the source is a local path:
![image](https://user-images.githubusercontent.com/45407901/112073085-8b7f5100-8b30-11eb-8eab-18ee17ed1531.png)

Check **Microsoft.Extensions.Logging** in VS UI:
1. When the source is nuget.org:
![image](https://user-images.githubusercontent.com/45407901/112073252-f03aab80-8b30-11eb-8060-e083f86bb4aa.png)

2. When the source is a local path:
![image](https://user-images.githubusercontent.com/45407901/112073383-398afb00-8b31-11eb-88c2-889a0f3b7165.png)

So it looks like,
when the source is a local path, it's using the owners in .nuspec file (Microsoft.Extensions.Logging has owners in .nuspec file, while Newtonsoft.Json doesn't have owners in .nuspec file.), which seems not right, if the owner field is already deprecated from .nuspec file. 
when the source is nuget.org, the owners are not shown. I'm not sure if this is right, as the owners info is still needed for package signing usage.

**Comment by loic-sharma** [comment]
Hello, this is a little confusing since owners information may come from several sources:

1. [.nuspec `owners` element](https://docs.microsoft.com/en-us/nuget/reference/nuspec#owners) - This is deprecated as per the docs. This value is controlled by the package's author and should not be trusted as it is susceptible to impersonation attacks. We've seen third-party authors package Microsoft code and claim the author/owner is Microsoft. My understanding is that this value should never be shown in Visual Studio.
2. [Search API's `owners` property](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result) - This is the package's owners according to the package source. On nuget.org, these owners are the account names that own the package. In other words, this value is controlled by the package source and can be trusted. This value is always up-to-date and should be used to display owners information in Visual Studio whenever possible.
3. [Repository signature `nuget-package-owners` attribute](https://github.com/NuGet/Home/wiki/Repository-Signatures-and-Countersignatures-Technical-Specification#the-nuget-package-owners-attribute) - Package sources that repository sign packages, like nuget.org, can include the package's owners in the signature. On nuget.org, these owners are the account names that own the package when the package was uploaded. In other words, this value is controlled by the package source and can be trusted. The repository signature's owners information can be used to configure [trusted signers](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#trustedsigners-section), so the owners should be shown in the `nuget verify` or `dotnet nuget verify` command. You can display this owners information on Visual Studio too if you'd like, but do note that this value may be stale if the package's owners changed after the package source created the repository signature.

**Comment by heng-liu** [comment]
Thanks for the detailed explanation! @loic-sharma 
I didn't check the code so I'm not sure how do we display owner in VS UI for packages from different sources.
But the behavior is different from what we expected.

**Comment by donnie-msft** [comment]
Related: https://github.com/NuGet/Engineering/issues/3805

**Comment by raffaeler** [comment]
@donnie-msft the link is not accessible outside MS people (HTTP 404)

**Comment by nkolev92** [comment]
Team Triage: Assigning to @chgill-MSFT.

**Comment by nkolev92** [comment]
Team Triage: Remove the owners field from the UI.

**Comment by zivkan** [comment]
> Team Triage: Remove the owners field from the UI.

I wasn't at that meeting. I find the decision unusual. The `owners` field is the only way for nuget.org to communicate which nuget.org account is responsible who uploaded the package, and who can upload updates. It's not uncommon for customers to repackage Microsoft assemblies and list Microsoft in the `author` field. If we don't show `owner`, then customers using Visual Studio will have little way to know if the package is really an official Microsoft package or if someone else uploaded a package that put Microsoft in the `authors` field (I think customers don't understand the blue tick).

Perhaps we should hide the `owners` field from local sources, but in my opinion it's valuable for HTTP sources.

**Comment by raffaeler** [comment]
@zikvan according to @loic-sharma :
> [.nuspec owners element](https://docs.microsoft.com/en-us/nuget/reference/nuspec#owners) - This is deprecated as per the docs. This value is controlled by the package's author and should not be trusted as it is susceptible to impersonation attacks.

My considerations:
* If that field is deprecated, anyone should assume to not use it at all. IMO a deprecated field is something that will be removed in the future and that I should not use anymore.
* In addition to be deprecated, it is also untrustable as susceptible to impersonation attacks. For sure, I don't want to see such information in any kind of UI (VS, nuget.org, local repos that could be used by third parties). 
* I agree the info about the user/organization who uploaded the package is relevant. But this should be inherited by the user account used from the nuget.org (or other repo) authentication, certainly not from a manifest compiled by hand.

Did I miss something else?

**Comment by zivkan** [comment]
`owners` is deprecated in the nuspec (so, for package authors creating packages), but not the HTTP protocol that Nuget Client (VS, dotnet cli) talks to remote NuGet feeds over HTTP.

Other elements that are different between nuspec and HTTP Protocol (registration and search resources) are deprecated package messages and vulnerability information.

**Comment by raffaeler** [comment]
@zivkan what are the other ways to set the `owners` field out of the nuspec?
I don't get how can I "consume" that field if "publishing" it is deprecated.

**Comment by zivkan** [comment]
Package authors are not supposed to set it. NuGet feeds (severs) are.

That is, people implementing [NuGet's HTTP API](https://docs.microsoft.com/nuget/api/overview). Specifically the [search resource](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource) has an `owners` field in the response, and maybe the [package metadata](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource) resource (for better or worse, due to the design of how nuget.org works, it was easier from a technical point of view for them to not maintain owners in the package metadata resource, so they documented the resource as not containing the `owners` field. But from an idealist point of view, I don't agree with that decision. Again, due to technical implementation details, NuGet.Client reuses the same data type for both search and package metadata resources, so NuGet.Protocol is capable of getting owners from both. Which resource VS's PM UI, or other apps like Rider, choose to source owners from is an independent technical implementation detail).

[Loic's earlier comment](https://github.com/NuGet/Home/issues/10666#issuecomment-806033343) already explained that the `owners` field from the search service should be trusted, and recommended displaying it. So my comments 2 days are is not a new recommendation, hence I don't understand why an internal discussion on the 28th of March recommended removing it.
