### ISSUE TITLE
Manage NuGet packages for solution extremely slow

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10674]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Manage-NuGet-packages-for-solution-extre/1371226)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.7 (I think)]
After installing the latest version of Visual Studio 2019, the Manage NuGet packages for the whole solution is terribly slow.
I have a solution with 70+ projects in it, and in previous versions I had no issue when managing the NuGet packages for the solution. But now, when opening, Visual Studio freezes for some minute or so, and after that it needs even more time to load the information of the NuGet packages. When all is done, it again takes some 20 seconds when I select a new NuGet package to see its information.
Also, switching from package source freezes the GUI and is very slow.
CPU usage for Visual Studio normally is around 15% (when doing nothing), but it peeks at 40% when opening the Nuget Package manager for the solution. Also the network traffic goes to 100% for a few seconds.

---
#### Feedback Bot on 3/16/2021, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NeilMacMullen** [comment]
Will second this.  Can take many minutes for upgrade list to recalculate even if it's *already* been calculated and all you've done is switched tabs or upgraded a single package.

**Comment by aortiz-msft** [comment]
Closing this issue on GitHub since we will track it in https://developercommunity.visualstudio.com/t/Manage-NuGet-packages-for-solution-extre/1371226

**Comment by kartheekp-ms** [comment]
I added a comment in VS Feedback ticket https://developercommunity.visualstudio.com/t/Manage-NuGet-packages-for-solution-extre/1371226#T-N1410192 incase if that helps other customers landing on this issue.

@NeilMacMullen - Can you please provide more details? It could be great if you can fill-up the new issue template https://github.com/NuGet/Home/issues/new so that we can reproduce the issue and prioritize the work based on customer impact.

**Comment by NeilMacMullen** [comment]
@kartheekp-ms   thanks for following up on this.

# Details about the problem

As described above, Visual Studio Nuget manager pane is unusably sluggish for any operation.  Here's a gif of me switching back and forth between Updates and Consolidate tabs.  Yes, it's in realtime and it really does take over a minute to switch back and forth a couple of times.  What's not seen in this gif is VS "graying out" repeatedly as this is occurring.

![slownuget](https://user-images.githubusercontent.com/9131337/116523911-ab8ff600-a8ce-11eb-9745-52bb048ad9d7.gif)



# Product version
The very latest VS Preview. I'm not sure this is a regression - performance has  never been _good_ as far as I can remember (many years and VS versions)  but it's now reaching the point of completely unusable.  :-(

## Repro steps and/or sample project
I suspect you need a solution more typical of  real-world codebases.  Ours has around 150 projects.  The vast majority are shared libraries which are consumed by a number of different application types (console tools, guis, azure functions, webapps etc).  Libraries are all targetting .netstandard2.0, applications target .net5, 4.72, netcore 3 etc though I suspect the dependency diagram is more relevant than the targetting.  

This isn't machine-specific  or directly involved with any extension; I see the same issue on different machines, including ones where I have no VS extensions installed.

Although in this particular example I happened to have a lot of packages that needed updating, the UI is also sluggish even when all packages are up to date.


### Verbose Logs
I'd be happy to supply diagnostics if you can suggest the best way to collect them for the UI.

**Comment by kartheekp-ms** [comment]
The original issue tracked here has been fixed in the latest preview version that can be downloaded from https://visualstudio.microsoft.com/vs/preview/. Hence closing this issue.

@NeilMacMullen - Thank you for providing additional details. Yeah, I can see from your recording that the responsiveness of the UI is not great. We had an internal discussion about your issue. Can you please refer to https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019 doc and report a VS feedback ticket? The built-in Feedback Tool allows you to easily add diagnostic information that helps our teams to diagnose and fix the issues.

**Comment by NeilMacMullen** [comment]
@kartheekp-ms I have raised an issue with a diagnostic recording at https://developercommunity.visualstudio.com/t/nuget-ui-is-exceedingly-slow/1411002

**Comment by NeilMacMullen** [comment]
Unable to comment on the feedback issue since that is now closed but just wanted to say thanks for addressing this issue! The UI is significantly more responsive in the August preview :-)

**Comment by costa100** [comment]
This issue resurfaced in VS 2019 16.11.8. The nuget window is insanely slow, it takes minutes to fully display it.

**Comment by echuck66** [comment]
I concur. VS2019 *version 16.10.3

**Comment by cadilhac** [comment]
Slow with 16.11.8 here.

**Comment by zivkan** [comment]
I appreciate you made the effort to give us feedback, but there are so many variables that without additional information it's simply not actionable. Almost everyone has at least one HTTP source configured, which therefore means that your network connection and the server load/response time contribute to perceived performance. But I have no idea if the delay you experienced is HTTP related, or something else.

The single most helpful thing you can do is to [use Visual Studio's report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022), and step 8, using "Record your actions to reproduce the issue" is absolutely critical. This will record an ETL trace, which lets us analyze where time was spent.

Unfortunately, at this time NuGet doesn't provide almost any context to what it's doing, so analyzing the ETL traces is extremely difficult (at best we can only guess what was going on). Alongside whatever other work I will do over the next few months, I currently intend on working on PM UI performance. My first steps will be to add ETW events to make the ETL trace more usable, allowing us to understand the cause of performance issues. However, once Visual Studio 2022 is updated with these ETW events, it will require customers such as yourself to update to that version of Visual Studio, and then provide feedback with a recording, so I can investigate. However, even before I add new ETW events, reporting a problem with a recording will let me gain more experience analyzing ETL traces and I might be able to make some conclusions with the information already available.

**Comment by mjolka** [comment]
I found that, in my case, NuGet in Visual Studio is slow because it is throttled to 2 concurrent HTTP requests. I have 83 packages installed, which results in 900 API calls when I go to the installed packages screen. These calls take 3 minutes to complete. Increasing the number of concurrent requests to 64, the API calls complete in 15-20 seconds.

If you want to test how much this throttling might be affecting you, it can be bypassed by running a proxy - for example, running [Fiddler](https://www.telerik.com/fiddler/fiddler-classic) with the "Capture HTTPS CONNECTs" option enabled. Make sure to restart Visual Studio after starting the proxy.

If this throttling is the cause of slowness for you, I've opened an issue to track it here: https://github.com/NuGet/Home/issues/11923.

**Comment by cadilhac** [comment]
On my side, I realized that I could fix the issue by moving the mouse fast anywhere on the screen. Not very logical but eh...

**Comment by jesperordrup** [comment]
Still a problem in VS 2019 v 16.11.10 

After packages are installed (which took extreme long time) pm starts removing packages, uninstalling. These steps are also slow. Each task below takes between 2-5 minutes:

Removed package 'Serilog.Formatting.Compact.1.0.0' from 'packages.config'
Successfully uninstalled 'Serilog.Formatting.Compact.1.0.0' from fatdetnu
Removed package 'Serilog.Formatting.Compact.Reader.1.0.3' from 'packages.config'
Successfully uninstalled 'Serilog.Formatting.Compact.Reader.1.0.3' from fatdetnu
Removed package 'Serilog.Sinks.Async.1.3.0' from 'packages.config'
Successfully uninstalled 'Serilog.Sinks.Async.1.3.0' from fatdetnu
Removed package 'Serilog.Sinks.File.4.0.0' from 'packages.config'
Successfully uninstalled 'Serilog.Sinks.File.4.0.0' from fatdetnu
Removed package 'Serilog.Sinks.Map.1.0.0' from 'packages.config'
Successfully uninstalled 'Serilog.Sinks.Map.1.0.0' from fatdetnu
Removed package 'Superpower.2.0.0' from 'packages.config'
Successfully uninstalled 'Superpower.2.0.0' from fatdetnu
Removed package 'UmbracoCms.8.14.1' from 'packages.config'

**Comment by kartheekp-ms** [comment]
@jesperordrup If possible, please try to install VS 2022 and let us know if you are experiencing similar issues. As suggested in https://github.com/NuGet/Home/issues/10674#issuecomment-1001805408 `The single most helpful thing you can do is to` [use Visual Studio's report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)`, and step 8, using "Record your actions to reproduce the issue" is absolutely critical. This will record an ETL trace, which lets us analyze where time was spent.`

**Comment by windhandel** [comment]
> Unfortunately, at this time NuGet doesn't provide almost any context to what it's doing

The above statement is part of the problem. This is a tool written by and for developers. Were you to expose some built-in diagnostic tools we'd all be able to use them.

Writing good software isn't just about writing good software. We need to be able to debug the tool without having to escalate every single issue because we've been given robust tools to do so.

**Comment by panuoksala** [comment]
> On my side, I realized that I could fix the issue by moving the mouse fast anywhere on the screen. Not very logical but eh...

Fun fact. I have the same issue in VS2022 and the problem is solved by moving mouse/clicking things on UI.
