### ISSUE TITLE
[CPVM] Wrong version restored for transitive dependency

### ISSUE THREAD

**Issue by MichaeIDietrich** [NuGet/Home#10676]
## Details about Problem

NuGet packages that are referenced transitively seem not to be restored with the expected version defined in the `Directory.Packages.props`.

Tested with .NET SDK 5.0.201.

## Repro steps and/or sample project

1. Clone this repo: https://github.com/MichaeIDietrich/CpvmTransitiveDependencies

solution structure:
`App1.csproj` <- `Microsoft.AspNetCore.Authentication.JwtBearer` <- `Microsoft.IdentityModel.Protocols.OpenIdConnect`
`App2.csproj` <- `Microsoft.IdentityModel.Protocols.OpenIdConnect`

(<- means references)

Both NuGets are defined in the `Directory.Packages.props`. CPVM is enabled in the `Directory.Build.props`.

2. Run `dotnet publish src\`

Version of `publish\App1\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` is `6.7.1`.
Version of `publish\App2\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` is `6.8.0`.

I would have expected both to be `6.8.0`, since that's the version defined in the `Directory.Packages.props`.

Can you confirm this is a bug or do I have a misunderstanding of what CPVM is meant to do here?

**Comment by nkolev92** [comment]
Hey @MichaeIDietrich, 

The transitive pinning feature was met with some resistance and we got lots of mixed feedback about the feature and it was disabled in https://github.com/NuGet/Home/issues/10132 and https://github.com/NuGet/NuGet.Client/pull/3719.
Reenabling it is tracked in https://github.com/NuGet/Home/issues/10389.

For now, this is an expected behavior. 

Please upvote the issue and please voice your opinion whether you think pinning should or should not be the default.
