### ISSUE TITLE
TfmSpecificPackageFile .targets file is causing NU1012 when running dotnet pack with 5.0.201

### ISSUE THREAD

**Issue by Keboo** [NuGet/Home#10724]
## Details about Problem

```
dotnet --list-sdks
3.0.101 [C:\Program Files\dotnet\sdk]
3.1.402 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 1.0 

## Repro steps and/or sample project
I have a WPF NuGet package that contains a custom .targets file to extend the build process of consumers. The full project is [XAMLTest](https://github.com/Keboo/XAMLTest), but I have created a smaller [sample project](https://github.com/Keboo/PackIssue) the reproduces the issue as well. In order to get the targets files into the needed `build\<tfm>` directory I have been using the [TfmSpecificPackageFile](https://docs.microsoft.com/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage) extensibility to inject the targets files. 

In the repository I have included a global.json file for switching between 5.0.100 and 5.0.201. The following steps work under 5.0.100, but throw a NU1012 when run with 5.0.201

1. Set .NET version in global.json
2. Run dotnet pack

With 5.0.100 a NuGet package is generated with the targets file placed within build\<tfm>\.
With 5.0.201 I received the error
>  C:\Program Files\dotnet\sdk\5.0.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU1012: Some included files are included under TFMs which are missing a platform version: net5.0-windows [D:\Dev\PackIssue\PackIssue\PackIssue.csproj]

I have attempted to determine how to properly set the "platform version" that it cares about, but have been unable to find the needed configuration value to set. Perhaps it is as simple as knowing the needed configuration?
The issue only reproduces when using `net5.0-windows` removing the `-windows` allows for the package to be built successfully as well. However, since my goal is to distrubte a WPF package this is not a viable solution for me as I need to set `<UseWPF>true</USeWPF>`.
In my XAMLTest project, I am able to use the same `TfmSpecificPackageFile` extensibility with `.exe` and `.json` files without an error on both 5.0.100 and 5.0.201. 

[VerboseLog.txt](https://github.com/NuGet/Home/files/6259457/VerboseLog.txt)

**Comment by zivkan** [comment]
I had a very quick look, perhaps too quick and I didn't fully understand the issue, but it seems to me to be related to https://github.com/NuGet/Home/issues/10063.

That thread has some suggestions. Some are proposals that are not implemented, but others are more verbose proposals that should work today.

An alternative is to specify yourself which platform version, you want to use, rather than letting the .NET SDK pick the default for you. If you want to use the .NET SDK's default, change your `TargetFramework` to `net5.0-windows7.0`. Picking a Windows 10 SDK version will allow you to use Windows 10. APIs in your library, but will also require people using your package to target the same version or higher.

**Comment by Keboo** [comment]
@zivkan thank you. Yes, changing the `TargetFramework` to `net5.0-windows7.0` does appear to address the problem. 

Is there some documentation to explain this? I had been using [this table](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms) for setting up the target frameworks.

**Comment by zivkan** [comment]
This is the design spec that the various teams based their own component's implementation on: https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

Here's where the SDK sets the default value: https://github.com/dotnet/sdk/blob/e6494d1d529fa00e76693b6d7d8f6ef9401b3e4f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets#L27-L30

But I don't follow the NuGet docs updates closely, and I don't follow dotnet docs at all, so I'm not sure where/if it's documented on docs.microsoft.com.

**Comment by nickhoeferpickpro** [comment]
I don't understand... why is it appending an extra 7.0 at the end?
If i want a library to target multiple frameworks then i put this in my csproj:

`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net7.0;net7.0-windows</TargetFrameworks>`
but when i do that the lib folder in the generated nupkg file will actually contain "net7.0", "net7.0-windows7.0", and "net48".

This is an issue for me because i have a targets file trying to reference the framework like this: 
`	<UsingTask TaskName="SomeTask"
               AssemblyFile="$(MSBuildThisFileDirectory)..\lib\$(TargetFramework)\SomeDLL.dll" />`

So if a consuming application uses that library and it targets net7.0-windows, then it will fail because it won't be able to find the folder for "net7.0-windows" because its actually "net7.0-windows7.0"
