### ISSUE TITLE
How to reference nuget libsodium dll?

### ISSUE THREAD

**Issue by Chewhern** [NuGet/Home#10763]
Currently I am working on a .Net standard binding that aims to call libsodium(coded in C language) in .Net(Cross platform), the binding was done, however, whenever I want to call any of the binding's functions (using DLLImport) the binding failed to locate the dll of libsodium regardless of which binding's functions I called.

I would like experts/people here to help to solve the issues or provide suggestions. The nuget package I published was called ASodium.

This is my csproj file, the source code is available on my github repository.

```
<Project Sdk="MSBuild.Sdk.Extras/2.0.54">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472;netcoreapp3.1</TargetFrameworks>
    <Authors>Chew Lik Hern</Authors>
    <Version>0.4.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ASodium</AssemblyName>
    <PackageId>ASodium</PackageId>
    <PackageTags>libsodium</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Chewhern/ASodium</RepositoryUrl>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <OutputType>Library</OutputType>
    <PackageProjectUrl>https://github.com/Chewhern/ASodium</PackageProjectUrl>
    <icon>Salt.jpg</icon>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>libsodium for .net</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="libsodium" Version="1.0.18" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
```

**Comment by zivkan** [comment]
Your package is fine.

Testing your ASodium package in an SDK style project, everything works.

Testing your package in a non-SDK style project, with PackageReference, and changing the project's "platform target" to either x86 or x64, it also works.

The non-SDK project system does not support packages with `runtimes/*` files, which is what your package's dependency, `libsodium`, uses, when using `AnyCPU`.

Non-SDK style projects using `packages.config`, rather than `PackageReference` also does not support packages with `runtimes/*` files. The `runtimes/*` folder in packages was a new feature added for PackageReference (well, project.json, back in .NET Core 1.0 preview days).

If either of the two scenarios above where I said "it works" is not working for you, we need more details, ideally a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). If the project you were testing was one of the other two scenarios that I said is not supported, well, it's not supported.

**Comment by Chewhern** [comment]
Thanks for letting me know extra information and knowledge, all the nuget package i built before version 0.4.0(tested just now), it has been a frustrating experience for me cuz the nuget package I built failed to locate the dll.

**Comment by Chewhern** [comment]
Thanks for letting me knowing the extra information and knowledge, the nuget package i built before 0.4.0(just tested) or 0.5.0(tested yesterday on linux vps) all failed to locate the libsodium dll. It was really a frustrating experience.

**Comment by Chewhern** [comment]
There's something funny that I realized only now .., the test project, I put the libsodiumdll straight into the application folder, that's why it works.., when the moment I don't put the libsodiumdll into the application folder it doesn't work anymore..

The test project actually calls random function from ASodium but the platform is actually .Net Framework 4.7.2 (C# Winform), I tested the same thing on my linux vps as i stated, it works on 0.4.0 and 0.5.0 version, but when I do it the same on the targeted .Net Framework 4.7.2 (C# Winform), I couldn't get it to work. 

Microsoft Visual Studio Community 2019
Version 16.7.7

Microsoft .Net Framework Version 4.8.03752

Does it matters on the Visual Studio version?
