### ISSUE TITLE
Offer push functionality through the public API

### ISSUE THREAD

**Issue by millokeller** [NuGet/Home#10762]
Issue [NuGet/Home#9821](https://github.com/NuGet/Home/issues/9821) changed the public API of `NuGet.CommandLine.XPlat` to `internal`. 

We use `NuGet.CommandLine.XPlat` to push packages to a company internal NuGet feed by a direct call of the executable:
```CSharp
private static bool PushPackage(string nupkgFile, string apiKey, string serverUrl, string timeout)
{
    var exitCode = Program.Main(new[] { "push", nupkgFile, "-k", apiKey, "-s", serverUrl, "-t", timeout });
    return exitCode == 0;
}
```
With the [introduced changes in v4.8.0](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.8) this call is not possible anymore. Since I cannot find I workaround to push NuGet packages without including NuGet.exe, I would like to request it as new feature.

**Comment by zivkan** [comment]
Most of our commands, including push, are available in the `NuGet.Commands` package. Here's the push command runner: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/CommandRunners/PushRunner.cs

NuGet.CommandLine.XPlat is the entry point for the dotnet CLI. It's not intended to be a public API, and is a package only because of the process for how NuGet gets inserted into the .NET SDK.

**Comment by millokeller** [comment]
Thank you for pointing this out. Your suggestion is exactly what I was looking for.
