### ISSUE TITLE
packages.lock.json contentHash different from manually generated value

### ISSUE THREAD

**Issue by JanKrivanek** [NuGet/Home#10787]
## contentHash in packages.lock.json not reproducible via manual steps

ContentHash seems to be base64 encoded sha512 hash (at least based on the source: https://github.com/NuGet/NuGet.Client/blob/d3a633a04da7cd83900498334ec5e7650a52fa86/src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs#L460).
We want to use this value for our SBOM files and be able to reproduce it via our logic in isolated environment. However the base64 encoded SHA512 hash differs from the contentHash in packages.lock.json

NuGet Version: 5.7.0.6726

## Repro steps and/or sample project

```
$filePath = "C:\trash\delete\NugetsSBOM\packages\Newtonsoft.Json.13.0.1\Newtonsoft.Json.13.0.1.nupkg"

$content = Get-Content -Encoding byte $filePath

[System.Convert]::ToBase64String( [System.Security.Cryptography.SHA512]::Create().ComputeHash($content) )
```
result: g3MbZi6vBTeaI/hEbvR7vBETSd1DWLe9i1E4P+nPY34v5i94zqUqDXvdWC3G+7tYN9SnsdU9zzegrnRz4h7nsQ==
contentHash: ppPFpBcvxdsfUonNcvITKqLl3bqxWbDCZIzDWHzjpdAHRFfZe0Dw9HmA0+za13IdyrgJwpkDTDA9fHaxOrt20A==

```
{
  "version": 1,
  "dependencies": {
    ".NETFramework,Version=v4.5": {
      "Newtonsoft.Json": {
        "type": "Direct",
        "requested": "[13.0.1, 13.0.1]",
        "resolved": "13.0.1",
        "contentHash": "ppPFpBcvxdsfUonNcvITKqLl3bqxWbDCZIzDWHzjpdAHRFfZe0Dw9HmA0+za13IdyrgJwpkDTDA9fHaxOrt20A=="
      }
    }
  }
}
```

Generated via: `nuget restore NugetsSBOM.sln -UseLockFile`

Is this expected?
How exctly is the `contetHash` calculated?

**Comment by zivkan** [comment]
The implementation of getting the content hash is here: https://github.com/NuGet/NuGet.Client/blob/1328b1db6ef99fd0f0c7cf9201e4c75a366a88dd/src/NuGet.Core/NuGet.Packaging/Signing/Archive/SignedPackageArchiveUtility.cs#L593

It is designed to not change the hash when the package is signed/resigned, because when using lock files the content hash needs to remain the same. When signing a package, the signature needs to go somewhere, and the is in the nupkg like any other file. Hence, when using other tools that don't know about NuGet's "content hash" algorithm, it won't generate the same hash. This all was implemented before I joined the team, but I believe it's also the reason it's called "content hash" and not "file hash" or "package hash", because the file hash will change every time the package is signed.

So, this is all working as designed. In particular, if your organization creates packages and pushes them to nuget.org, you will see that the package later downloaded from nuget.org has a different file hash, because it now contains nuget.org's repository signature, but the same content hash, as the file you created on your build machine.

**Comment by JanKrivanek** [comment]
Thank you @zivkan for prompt and detailed reply!
Understood on the scenario and chosen implementation.
In our case we need a file hash for providing integrity check without relying on the toolset (that might be compromised in specific scenarios) - similarily as the hash in npm package-lock.json files. Seems like we'll need to generate those ourselves.

Thanks
Jan
