### ISSUE TITLE
Username and Password ignored after HTTP -> HTTPS redirect [command line]

### ISSUE THREAD

**Issue by rossipedia** [NuGet/Home#1079]
Sample session:

```
> nuget
NuGet Version: 2.8.60318.667
...

> type %AppData%\Nuget\Nuget.config
<?xml version="1.0" encoding="utf-8"?>
<configuration />

> nuget install Some.Internal.Package -Source "http://build.stackexchange.com/httpAuth/app/nuget/v1/FeedService.svc/" -OutputDirectory "%CD%\packages" -Verbosity detailed
Please provide credentials for: http://build.stackexchange.com/httpAuth/app/nuget/v1/FeedService.svc/
UserName: bross
Password: *
Please provide credentials for: http://build.stackexchange.com/httpAuth/app/nuget/v1/FeedService.svc/
UserName: bross
Password: *
Please provide credentials for: http://build.stackexchange.com/httpAuth/app/nuget/v1/FeedService.svc/
UserName: bross
Password: *
Please provide credentials for: http://build.stackexchange.com/httpAuth/app/nuget/v1/FeedService.svc/
UserName: Password: ^C
>

```

And from Fiddler:

![](http://i.imgur.com/0ndqguQ.png)

<strike>However, if I supply `https` instead of `http` for the `-Source` parameter, the package is installed just fine</strike>

**Comment by yishaigalatzer** [comment]
@rossipedia we are deprecating support for http on our server (nuget.org), and it is probably a good idea to use https to begin with anyways.

We are going to take a look at this for command line 3.1.X, to make the decision could you share how urgent this is (it seems to be not urgent since you have a workaround, but I want to be sure)

**Comment by rossipedia** [comment]
It's been holding me up for the past 2 days. It seems to be also related to [this issue](https://github.com/JetBrains/teamcity-nuget-support/issues/6) on the TeamCity nuget feed (I work with @NickCraver). 

To correct my original post, I was mistaken. Supplying `https` indeed does _not_ download the package just fine. I get stuck in an endless loop of supplying credentials, as the Nuget command line does not supply what I type in at the prompt to the actual request for the `.nupkg` file.

**Comment by yishaigalatzer** [comment]
This does seem to be an issue with this server. You could consider
1. Push the bits to a file share
2. Remove authentication requirements

**Comment by NickCraver** [comment]
There was a complication on @rossipedia's testing here he was unaware of. Just after his initial test, we moved our **TeamCity** server (our NuGet feed host) in preparation for a data center failover coming up. 

In case anyone else with the same circumstances happens upon this, I'll post the resolution: 
Since we terminate SSL in HAProxy (a proxy in front of TeamCity), it does not receive an HTTPS request itself. As a result, the NuGet feed is served fine over `https://` but all absolute links rendered for packages are `http://`. To resolve this, you need to modify the `/<TeamCityDir>/conf/server.xml` section to include the last 3 elements to make it behave properly behind an SSL-terminating proxy.

    <Connector port="8080" protocol="org.apache.coyote.http11.Http11NioProtocol"
               connectionTimeout="60000"
               redirectPort="8543"
               useBodyEncodingForURI="true"
               socket.txBufSize="64000"
               socket.rxBufSize="64000"
               tcpNoDelay="1"
               secure="true"
               scheme="https"
               proxyPort="443"
     />

Can you please close this out? I think we're all set and I apologize for the sysadmin side screwing things up here :)

**Comment by yishaigalatzer** [comment]
Thanks Nick! Awesome of you to resolve this with such a detailed response.
