### ISSUE TITLE
Cannot use embeded PackageReadmeFile when using snupkg for symbols

### ISSUE THREAD

**Issue by meziantou** [NuGet/Home#10791]
## Details about Problem

NuGet product used: dotnet.exe

Product version: 6.0.0-preview.3.21201.4

Worked before? If so, with which NuGet version: 🤷‍♀️

## Repro steps and/or sample project

- `dotnet new classlib`
- Create a non-empty `readme.md` file
- Edit the csproj

````
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>New_folder</RootNamespace>        
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
</PropertyGroup>

<ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
</ItemGroup>

</Project>
````

- `dotnet pack`

````
Microsoft (R) Build Engine version 16.10.0-preview-21181-07+073022eb4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  NewFolder -> C:\Users\mezia\Desktop\NewFolder\bin\Debug\net6.0\NewFolder.dll
  Successfully created package 'C:\Users\mezia\Desktop\NewFolder\bin\Debug\NewFolder.1.0.0.nupkg'.
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5039: The readme file 'readme.md' does not exist in the package. [C:\Users\mezia\Desktop\NewFolder\NewFolder.csproj]
````

# Additional information

- It can generate the package if you remove `<SymbolPackageFormat>`
- There is no issue with the `<PackageIcon>` nor `<PackageLicenseFile>` properties, so it seams to be only for the PackageReadmeFile

**Comment by BlackGad** [comment]
snupkg package format strongly limited with content filter by extensions (*.pdb and some more)

**Comment by zkat** [comment]
We need to look into what we do here for licenses.

**Comment by MarkStega** [comment]
Confirming the same issue with a Net5 project and "Microsoft (R) Build Engine version 16.10.0-preview-21175-01+afd0b6210 for .NET" as the build engine.

**Comment by campersau** [comment]
Maybe this is check `!PackageTypes.Contains(PackageType.SymbolsPackage)` which is already in [`ValidateLicenseFile`](
https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L709)
and [`ValidateIconFile`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L745) needs to be added to [`ValidateReadmeFile`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L867) too.

Also in [`PackageMetadataXmlExtensions`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs) the [`readme`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs#L83) element is always added whereas the elements for [`licenseUrl`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs#L71) and [`icon`](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs#L73) are not because of the same check [here](https://github.com/NuGet/NuGet.Client/blob/2136302f54479707befc9fac65af19e1772c7827/src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs#L52) `!PackageTypes.Contains(PackageType.SymbolsPackage)`.

**Comment by loic-sharma** [comment]
This blocks many popular projects from adopting embedded READMEs, including:

* Newtonsoft.Json
* Serilog
* AutoMapper
* NUnit
* NLog
* Polly
* RestSharp
* CsvHelper
* SixLabors.ImageSharp
* And lots more :(

The silver lining is that snupkg adoption is great with our most popular packages! 😅

**Comment by loic-sharma** [comment]
For folks following this thread, the fix should be released in a few weeks in .NET 6 RC2.

**Comment by uladz-zubrycki** [comment]
Facing similar case, but instead of skipping `snupkg` generation `dotnet pack` generates `nupkg` (with `readme.md` successfully embedded) and then fails with `error NU5039: The readme file 'readme.md' does not exist in the package.`

Generates both without `SymbolPackageFormat`.

Would be cool to have this issue mentioned in the [documentation](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile) until fixed. Wasted a few hours here.

``` 
 Successfully created package 'Package.nupkg'.
C:\Program Files\dotnet\sdk\5.0.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5039: The readme file 'readme.md' does not exist in the package. [Package.csproj]
```

```
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET

.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
```

**Comment by zkat** [comment]
@v-zubritsky that's https://github.com/dotnet/project-system/issues/7642, which is a separate bug. You can work around it by just adding an empty `PackagePath`.

**Comment by uladz-zubrycki** [comment]
@zkat I had empty `PackagePath` already, didn't work. Also tried `/`, some custom path like `/docs` and `.` – all with no luck. But it did work after I removed the `SymbolPackageFormat`, that's why I've drawn a conclustion that it's the same root cause.

**Comment by zkat** [comment]
@v-zubritsky can you file a separate bug for this so we can track and triage it separately?

**Comment by uladz-zubrycki** [comment]
@zkat Sure thing.

https://github.com/NuGet/Home/issues/10791

**Comment by loic-sharma** [comment]
Hello everyone, [.NET 6 RC2 has been released](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-2/) with this fix. You can download it here: https://dotnet.microsoft.com/download/dotnet/6.0

**Comment by TheCodeTraveler** [comment]
Thanks @loic-sharma! I can confirm that, using .NET 6 RC, it now works for my NuGet Packages (when it hadn't been working before .NET 6 RC2)! 

I just published both with their NuGet Readme + snupkg 🎉 

- [AsyncAwaitBestPractices](https://www.nuget.org/packages/AsyncAwaitBestPractices/)
- [AsyncAwaitBestPractices.MVVM](https://www.nuget.org/packages/AsyncAwaitBestPractices.MVVM/)

**Comment by thargy** [comment]
Fixed for me too. 👍🏻

**Comment by RehanSaeed** [comment]
I still seem to be having issues:

- Build: https://github.com/RehanSaeed/Serilog.Enrichers.Span/pull/79/checks?check_run_id=3892346871
- PR: https://github.com/RehanSaeed/Serilog.Enrichers.Span/pull/79

```
Successfully created package '/home/runner/work/Serilog.Enrichers.Span/Serilog.Enrichers.Span/Artefacts/Serilog.Enrichers.Span.1.4.1-preview.0.7.nupkg'.
Error: /home/runner/.dotnet/sdk/6.0.100-rc.1.21463.6/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error NU5039: The readme file 'README.md' does not exist in the package. [/home/runner/work/Serilog.Enrichers.Span/Serilog.Enrichers.Span/Source/Serilog.Enrichers.Span/Serilog.Enrichers.Span.csproj]
An error occurred when executing task 'Pack'.
Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
	.NET Core CLI: Process returned an error (exit code 1).
Error: Process completed with exit code 1.
```

My directory structure:

```
Source
  Serilog.Enrichers.Span
    Serilog.Enrichers.Span.csproj
README.md
```

Any ideas where I'm going wrong?

**Comment by Apostolique** [comment]
@RehanSaeed It won't work unless you upgrade to .NET 6 RC2. That's the version with the fix. You're still on .NET 6 RC1.
