### ISSUE TITLE
nuget restore can fail after running choco install

### ISSUE THREAD

**Issue by lokst** [NuGet/Home#10804]
## Details about Problem

(Please let me know if there is a better place where I should file this issue)

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): NuGet.exe

Product version:  5.9.1.11

Worked before? If so, with which NuGet version: 5.8.1.7021

## Repro steps and/or sample project

1. On a Windows system where there is no user-wide NuGet.config file, run `choco install` for any package. This will generate a user-wide NuGet.config file with no configured feeds
2. Next, run `nuget restore` to restore packages hosted on nuget.org. This will fail because the empty user-wide NuGet.config file will be respected (as per https://github.com/NuGet/NuGet.Client/pull/3907), causing the nuget.org feed to not be used

## Verbose Logs

Example log excerpt from running `nuget restore`. We can see that the nuget.org feed is not used.

```
Errors in packages.config projects
    Unable to find version '1.0.1-Preview' of package 'Microsoft.WinAppDriver.Appium.WebDriver'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Microsoft.WinAppDriver.Appium.WebDriver.1.0.1-Preview' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '4.2.1' of package 'Castle.Core'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Castle.Core.4.2.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '1.2.0' of package 'MSTest.TestAdapter'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'MSTest.TestAdapter.1.2.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '1.2.0' of package 'MSTest.TestFramework'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'MSTest.TestFramework.1.2.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '3.8.0' of package 'Selenium.Support'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Selenium.Support.3.8.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '3.8.0' of package 'Selenium.WebDriver'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Selenium.WebDriver.3.8.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
    Unable to find version '10.0.3' of package 'Newtonsoft.Json'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Newtonsoft.Json.10.0.3' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.

NuGet Config files used:
    C:\Users\circleci\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.FallbackLocation.config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by lokst** [comment]
Also noted that there is an issue filed in the Chocolatey repository about this behaviour of Chocolatey to create an empty user-wide NuGet.Config file (https://github.com/chocolatey/choco/issues/2233). I'm not sure where the overall issue of incompatibility between `choco install` and `nuget restore` should be addressed (on NuGet's end or on Chocolatey's), so I'd still like to keep this issue open for now so that NuGet maintainers can weigh in 🙂

**Comment by kartheekp-ms** [comment]
@lokst - I am sure you may be aware of this work around. As mentioned in the https://github.com/NuGet/Home/issues/10586#issuecomment-815347707, You can add `NuGet.Config` to your repo or pass the [configuration file to the restore command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore#options) to fix this issue. In general, it is a good practice to not to rely on the `system/user` level `NuGet.Config` file.

https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied doc is a great resource to learn more about how NuGet settings are applied.

**Comment by lokst** [comment]
@kartheekp-ms Thank you for weighing in! Yes, I'm aware of the workarounds you mentioned. As there are users who do not define their own NuGet.Config files, I wanted to file this issue to raise awareness about it with NuGet maintainers and also check if there are currently any intentions to address it from NuGet's end, though I understand if there may not be any such plans for now.

**Comment by zivkan** [comment]
It's unfortunate that this is having a negative impact on customers that use choco before using any official nuget client. However, the behaviour changed by design to fix [this issue](https://github.com/NuGet/NuGet.Client/pull/3907) for customers who do not use choco. This has been particularly noticeable since the "Dependency Confusion" blog post came out earlier this year and many customers want to remove nuget.org from their nuget.config to apply the suggested mitigation.

Since the two are mutually exclusive, either require non-chocho users to have to remove nuget.org twice, or have choco users either run NuGet before running choco or manually add nuget.org until https://github.com/chocolatey/choco/issues/2233 is fixed, I propose this issue is closed as by-design. It's not possible to make both scenarios work at the same time, and arguably choco is doing the less technically correct thing here.

https://github.com/NuGet/Home/issues/10586 and https://github.com/actions/virtual-environments/issues/3038 are other related issues, specifially about GitHub Actions and Azure Pipelines hosted CI agents who were affected by choco's empty nuget.config.

**Comment by matt-richardson** [comment]
Can nuget output a warning if there are no sources defined? The behavior at present is pretty annoying.

**Comment by zivkan** [comment]
@matt-richardson an issue already exists for that idea: https://github.com/NuGet/Home/issues/2472

It doesn't have a single upvote 😞

**Comment by matt-richardson** [comment]
Thanks for pointing that out. I've added a vote. 
I would still recommend that that be considered as part of the breaking change that this introduced.
We sunk a lot of time into trying to figure this out - a warning would have immediately point us in the right direction.

**Comment by yannduran** [comment]
Yeah I've added a "vote" too, if by vote you mean a thumbs up. Can I suggest that you don't rely on "votes" to fix a fundamental flaw as voting suffers from a discoverability issue. I only came across this issue by accident as I was searching for the answer as to why my new VS 2022 Preview 1 install had no nuget.org package source, only a Microsoft Offline one instead.

I really don't understand why Chocolatey would add an **empty** config file in the first place, but checking that users can actually use Nuget is Nuget's responsibility, don't you think?

Nuget could do two things for this:
1. Check that a nuget.org package source actually exists (the Microsoft Offline one doesn't count) and add it if not.
2. Check and remove any exact package source duplicates.

This would ensure that both Chocolatey and non-Chocolatey users are catered for.

**Comment by zivkan** [comment]
@yannduran  your proposal is effectively to re-introduce the bug fixed by https://github.com/NuGet/NuGet.Client/pull/3907, which is a scenario that customers not using chocolatey were increasingly experiencing following the "dependency confusion" blog post, "3 ways to mitigate risk when using private package feeds" whitepaper, and others. Hence, it unfortunately does not cater for customers who do not use chocolatey and adds security risk. I understand it's inconvienent for chocolatey customers to determine why their NuGet restores aren't using nuget.org, but it's a lower risk than customers who are trying to secure their supply chain and unknowingly use an additional package source because the tooling opted in without their consent.

Chocolatey have since stopped writing the nuget.config file, at least in their source code, I don't know if they have published a new version of their binary with the fix, so this shouldn't be an ongoing problem as everyone updates.

**Comment by yannduran** [comment]
@zivkan that was not my intention at all. I was suggesting that Nuget should **_warn_** customers if there's no nuget.org package source once the package sources have all been evaluated. This is simply the **responsible** thing to do.

Are you saying that people are not using nuget.org and are only wanting their own package sources? If people are savvy enough to add their own package source, they should be savvy enough to simply remove the nuget.org one if they don't want it. Isn't there a way for them to remove nuget.org the same way they add their own package sources? Apart from the UI obviously, which is self-explanatory.

In a new VS install, I expect Nuget to just work, out of the box, and I don't think that's an unreasonable expectation.

Don't get me wrong, I think this should be **fixed** by Chocolatey so they don't cause the problem in the first place. As of yesterday when I installed VS 2022 Preview 1 it's still a problem. However, I think it's Nuget's responsibility to not just leave customers in the dark when something like that does happen (no matter who caused it), not knowing that it's been removed by some other software package.

Why are you prioritising the use case where customers who **don't** want to use nuget.org over those who **_do_**, but who aren't aware that some other software package has caused a problem?

**Comment by zivkan** [comment]
> I was suggesting that Nuget should warn customers if there's no nuget.org package source

Your first message doesn't mention the word "warn". In fact, it explitly said "and add it if not".

> Are you saying that people are not using nuget.org and are only wanting their own package sources?

Yes, that the recommendation number 1 in the "3 ways to mitigate risk when using private package feeds" whitepaper.

> If people are savvy enough to add their own package source, they should be savvy enough to simply remove the nuget.org one if they don't want it. Isn't there a way for them to remove nuget.org the same way they add their own package sources?

Yes, the NuGet bug that was fixed was when a customer who did not use chocolatey removed the package source, and then NuGet added it back again. This was also a problem on CI machines where someone set up a script to remove nuget.org in the CI script, but if they didn't do it twice, it wouldn't take effect.  So the customers are savvy enough to remove the package source, but from their point of view, it didn't work.

> In a new VS install, I expect Nuget to just work, out of the box, and I don't think that's an unreasonable expectation.

I agree, and that's exactly NuGet's designed behaviour.  When there is no user-profile nuget.config, NuGet creates it with nuget.org as a default package source.

Unfortunately when unofficial tooling, such as chocolatey, modify machine state in a way that is indistinguishable to NuGet from a customer who voluntarily removed nuget.org as a package source, we're limited in what we can do. We can have an "arms race" and add a mitigation, until some other 3rd party tool bypasses that mitigation, then NuGet adds another mitigation, and so on.

> Why are you prioritising the use case where customers who don't want to use nuget.org over those who do, but who aren't aware that some other software package has caused a problem?

Because there isn't a single axis to optimize. Ease of use is one, security is another, flexibility is another. Any implementation has a finite size in this multi-dimensional optimization space. New features and bug fixes that have nothing to do with setting up default nuget.config on new machines or modifying package sources, are also important. A trade off has to be made.

I don't intend for my messages to sound dismissive, I'm sorry if it does. I'm trying to explain the situation up to now. I'm grateful that you shared your opinion, and our programme managers and team lead hopefully will see this feedback, and take it into account with all the other feedback we get. If improving the experience of customers using one particular 3rd party tool becomes a priority, we'll implement a change, and if it has an unintended negative impact on some other subset of customers, I'll explain it to them as well.

**Comment by noseratio** [comment]
It's sad this issue has been closed. I landed here because a Twitter friend pointed me at this thread. Prior to that, I had wasted about an hour to figure out what was going on.

Got a fresh clean Windows 11 machine, installed Chocolatey, latest .NET SDK 6 RC, latest VS2022 RC.  Tried creating a simple .NET project:

```
dotnet new winforms -n app
dotnet add app package Microsoft.Web.WebView2 --version 1.0.1056-prerelease
```
Got this error:

> error: NU1101: Unable to find package Microsoft.Web.WebView2. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages

After many blind trials, I eventually solved it like this:

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

Regardless of whether it was Chocolatey or anything else that screwed my default `nuget.config`, a properly worded error message could have saved me an hour.

In contrast, Rust team treats unhelpful compiler/build messages as bugs that should be fixed, that's why their error messages are insanely useful.
