### ISSUE TITLE
Issues while packing custom nuget package by using nuget exe v5.9.1

### ISSUE THREAD

**Issue by Abishake968** [NuGet/Home#10845]
### Describe the bug

I created lib folder structure like lib\net5.0-windows\AssemlyName.dll and nuspec file parallel to lib folder. We have multiple assemblies in lib folder so, we added "references" tag in  nuspec file then try to create a nuget package by using a command "nuget.exe pack" with nuget.exe v5.9.1. I faced below two issues.

![image](https://user-images.githubusercontent.com/36999537/117294632-7e27e700-ae90-11eb-9c99-5c3c995e11ba.png)

**Nuspec File:**

![image](https://user-images.githubusercontent.com/36999537/117295135-1756fd80-ae91-11eb-918c-31dd6ddf7f72.png)

"Object reference not set to an instance of an object" issue is occurred.

We have checked the nuspec file and removed "references" tag and above issue is not occurred again i tried to pack below issue is occurred.

"NU1012: Some included files are included under TFMs which are missing a platform version: net5.0-windows"
Please provide the solution for this two issues.

Note: This issue occurred while we tried latest nuget.exe 5.9.1 version but this worked in nuget.exe 4.9.4

### To Reproduce

1. Create a nuspec file with references tag.
2. Create a lib folder with net5.0-windows.
3. Run the command **nuget.exe pack**

### Screenshots

![image](https://user-images.githubusercontent.com/36999537/117294976-eaa2e600-ae90-11eb-8e70-922d9145e817.png)

![image](https://user-images.githubusercontent.com/36999537/117295250-3c4b7080-ae91-11eb-86e2-9c2f07499f4f.png)

**Comment by donnie-msft** [comment]
May be related to https://github.com/NuGet/Home/issues/10724
Though, not sure why it would work in v4.9.4.
/cc @zkat

**Comment by zivkan** [comment]
NuGet 4.9 doesn't know anything about net5. It might "work", but it's missing contextual information about which version of Windows, so NuGet can't do proper compatibility checks when installed in projects.

The target framework `net5.0-windows` (notice I didn't call it a TFM - target framework moniker) is valid in a csproj. When you don't specify which version of Windows, the .NET SDK provides a default, and NuGet uses that to generate `lib/net5.0-windows7.0/your.dll`. If you're not going to pack via csproj, then you'll need to append the platform version number yourself.

edit: the null reference exception is a bug we need to fix

**Comment by erdembayar** [comment]
Closing as duplicate of existing [VS feedback](https://developercommunity.visualstudio.com/t/Issues-while-packing-custom-nuget-packag/1415347#T-N1418620). I and zivkan already answered this question. Null exception part is recently [fixed](https://github.com/NuGet/Home/issues/10685).
If you still have question question then feel free to engage on existing VSFeedback.

**Comment by EmilAlipiev** [comment]
@zivkan can you not just give simple example? what is a Platform version?  if you mean like below, i am still getting the error. what is wrong with the declaration below?

```
<files>
		<!--Android-->
		<file src="SamsungAccessorySDK-Maui\bin\Release\net7.0-android\SamsungAccessorySDK-Maui.dll" target="lib\net7.0-android" />
		<file src="SamsungAccessorySDK-Maui\bin\Release\net7.0-android\SamsungAccessorySDK-Maui.pdb" target="lib\net7.0-android" />
	</files>
```

https://github.com/EmilAlipiev/SamsungAccessorySDK.Net/blob/master/SamsungAccessorySDK-maui.nuspec

**Comment by EmilAlipiev** [comment]
@erdembayar your linked VS feedback is unfortunate. A MS employee is giving a code answers with images knowing image links are getting lost in time.

**Comment by zivkan** [comment]
@EmilAlipiev the simple example is to not use your own nuspec to create packages, instead pack with `dotnet pack`, and let the .NET SDK inform NuGet of the platform versions. For example, I know that when using `net7.0-windows` as your `<TargetFramework>`, the .NET SDK will add `<TargetPlatformVersion>7.0</TargetPlatformVersion>` (not in your project file, it does this behind the scenes), so that when Nuget parses the project TargetFrameworkMoniker and TargetPlatformMoniker before packing, it will create `lib/net7.0-windows7.0/project.dll`.

What the default TargetPlatformVersion is for `-android`, I have no idea. It's possible the MAUI team change the default version each new version of .NET too (well, technically they could change it any time, but hopefully they don't break combability mid-version).

Sorry I missed that the original issue author using nuspec and nuget.exe pack rather than dotnet pack. Like most people, I have a lot more work to do than time to do it, and in a rush I missed that important detail in my previous comment.

Some people don't like the MSBuild based pack and want to keep using nuspec files, and if you're in that circumstance as well, then the best feedback I can provide is if you don't want to use tools that automate process for you, you need to know the process well enough to repeat that automation yourself. In this case, here is the spec where platform identifier, version, and moniker was added to NuGet's compatibility checks: https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

**Comment by nickhoeferpickpro** [comment]
I don't understand... why is it appending an extra 7.0 at the end?
If i want a library to target multiple frameworks then i put this in my csproj:

`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net7.0;net7.0-windows</TargetFrameworks>`
but when i do that the lib folder in the generated nupkg file will actually contain "net7.0", "net7.0-windows7.0", and "net48".

This is an issue for me because i have a targets file trying to reference the framework like this: 
`	<UsingTask TaskName="SomeTask"
               AssemblyFile="$(MSBuildThisFileDirectory)..\lib\$(TargetFramework)\SomeDLL.dll" />`

So if a consuming application uses that library and it targets net7.0-windows, then it will fail because it won't be able to find the folder for "net7.0-windows" because its actually "net7.0-windows7.0"
