### ISSUE TITLE
Add embedded release notes

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#10841]
# Background

The release notes experience is less than ideal today as the release notes are included in the project file directly. For example:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>

    <PackageReleaseNotes>Hello world</PackageIcon>
  </PropertyGroup>

</Project>
```

This approach has a few flaws:

* Large release notes will clutter your project file.
* The release notes is not ideal for rich experiences like links, tables, etc...

Some projects, like Akka.net, circumvent this using build magic: https://github.com/akkadotnet/akka.net/blob/e0f860430e92d9300f9e20f5a4480e67e01cc61a/build.fsx#L180

See: https://twitter.com/Aaronontheweb/status/1390392196592017412?s=20

# Proposal

Recently, the NuGet client added support for embedding icons, licenses, and READMEs into the package itself: https://github.com/NuGet/Announcements/issues/29. These are separate files are inserted ("embedded") into the package itself. In particular, the README supports markdown, which lets authors provide rich content.

Package authors should be able to write release notes in a separate file that is then packed into the package. This new embedded release notes should support markdown.

**Comment by anangaur** [comment]
Or support for Changelog.md?

**Comment by Aaronontheweb** [comment]
So for an example of what do in our release process today:

https://github.com/akkadotnet/akka.net/blob/dev/RELEASE_NOTES.md#1419-april-28-2021

Our build script grabs the section of markdown for the matching NuGet package version and injects it into the `<PackageReleaseNotes>` field as full markdown. Just making it so that section could include markdown would be a great way of supporting this retroactively in package build systems without the need for additional files.

**Comment by nkolev92** [comment]
I think we can call this a dup of https://github.com/NuGet/Home/issues/1203.

**Comment by loic-sharma** [comment]
Closing this as a dupe
