### ISSUE TITLE
NuGet GC performance push for dev17

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#10843]
I started looking into NuGet restore allocations, as they are causing large GC pause times in the wild. I'm looking at a trace of Orchard Core in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1278814.

Method|Description|Fix|Percentage % | Tracking issue|
---|---|---|---|----
~`TokenSegment.TryMatch`~|~Creates lots of `Dictionary<TKey, TValue>`~|~Can we be more efficient here and share between content items?~|16%| 
~`TokenSegment.TryMatch`~|~Substrings path many times over~|~Can we pass though string segment (value, startIndex, length) and operate on that instead of creating in between string?~|11.1%| 
~`RemoteDependencyWalker.ChainPredicate`~|~Boxes a List<LibraryRange>.Enumerator & LibraryRange[] enumerator via RemoteResolveResult.Dependencies~|~Can we just turn this into a List<Library>?~|4.4%|  https://github.com/nuget/home/issues/10918
~`TokenSegment.TryMatch`~|~Resizes ContentItem.Properties while adding a property~|~Set a better default capacity~|4.1% | https://github.com/NuGet/Home/issues/10969
~`RemoteDependencyWalker.CreateGraphNode`~|~Very large amounts of allocating async state machine (&lt;CreateGraphNode&gt;d__3)~|~Move from recursive function to iteration/loop to walk the graph~|~3.8%~| https://github.com/NuGet/NuGet.Client/pull/5624|
~`TokenSegment.TryMatch`~|~Concats `_token + "_raw"` while adding a property~|~Do we need "raw" properties?~|3.5% | https://github.com/NuGet/Home/issues/10969
~`VersionFormatter.Format`~|~Very inefficient, uses combo of `StringBuilder` + `string.Format`~|~Replace `string.Format` usage with `StringBuilder.Append` and `StringBuilder.AppendFormat`~|2.2%|https://github.com/NuGet/Home/issues/11014
~`RemoteDependencyWalker.CreateGraphNode`~|~Creates List<Task> that is resized a bunch~|~Give it a better capacity~|~1.6%~|https://github.com/NuGet/NuGet.Client/pull/5963|
`FrameworkNameProvider.TryGetPortableProfile`|Very heavy on HashSet allocations|Do we need them?|0.5%

**Comment by davkean** [comment]
tag @nkolev92 @jebriede

**Comment by nkolev92** [comment]
This is amazing, thanks @davkean !

Quickly running through some of the problem areas I'm familiar with:

> TokenSegment.TryMatch

The frequency that this API is called with should be reduced with the wider LockFileTargetLibrary caching. 

> RemoteDependencyWalker.ChainPredicate	

RemoteResolveResult.Dependencies should be a list. This has been on the chopping block but we had refrained because of public API changes.

> Resizes ContentItem.Properties while adding a property	
> Concats _token + "_raw" while adding a property	

Raw was added for pack validation purposes. We didn't pay enough attention to how costly this might be, https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/Rules/InvalidUndottedFrameworkRule.cs. 

We can consider removing the `_raw` part and rethinking the rule or only adding the raw value for the tfm segment. 
I think by not adding a raw value for all token, we'd do away with the resizing as well, as I don't think any convention has more than 10 tokens: https://github.com/NuGet/NuGet.Client/blob/7c3e405560f2826ff3f5b1a59cda79da31a55641/src/NuGet.Core/NuGet.Packaging/ContentModel/ManagedCodeConventions.cs#L412, but we can double check.

> FrameworkNameProvider.TryGetPortableProfile	

This one is super costly because it adds 10-50ms on *every restore*. 
This is where we spend ~40% of the core restore time for new projects with no dependencies. 
Idk if we can do away with it, but certainly we need to rethink it.

**Comment by nkolev92** [comment]
The `TryMatch` issues are also tracked by: https://github.com/NuGet/Home/issues/8428!

**Comment by nkolev92** [comment]
@jebriede I've made this an epic, can you please add the relevant issues that are being fixed under this epic?

**Comment by nkolev92** [comment]
I added the relevant issues under the epic + added a new column that links to the respective issues for the allocation hot spots noted by @davkean 

If you are curious to see all issues, you'd need ZenHub right now.

**Comment by nkolev92** [comment]
With https://github.com/NuGet/NuGet.Client/commit/1a7aa2dd343562168a221b1da959f1704a784e32 now merged, it's worth reevaluating the priorities of the above. 

The linked change reduces the frequency of `TokenSegment.TryMatch` calls in large solutions. 
In OrchardCore, we go from 57164  to 2769 computations.

Latest tests suggest savings in GB for a completely clean restore.

**Comment by davkean** [comment]
We should pay attention to the contention of that cache to see if it shows up both in thread time and CPU (overhead of Monitor.Enter)

**Comment by nkolev92** [comment]
Done now. 
Updated in the issue body.
