### ISSUE TITLE
Nuget retrive package from git source code.

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#10879]
We like Rust lang and golang with git , their package management tools can retrive packages from plain git source code repo.

You should not have build the package and publish it into nuget.
You just reference a git repo.

for go

```
go get -d example.com/mod@master
go list -m -json example.com/mod@abcd1234
```

for Rust

```
[dependencies]
rand = { git = "https://github.com/rust-lang-nursery/rand" }
```

We hope .net have the same ability.

Not much more required we have a central   NuGet repoistory.

**Comment by zkat** [comment]
Thanks for the feature request!

After talking about it, we decided this is not something we'll be able to get to in the foreseeable future, as it presents significant challenges (due to NuGet being binary-based instead of source-based like go get and cargo).

As such, I'm going to close this issue. Have a good one!

**Comment by ghost** [comment]
Thank you .
