### ISSUE TITLE
.nupkg.metadata locked and being used by another process

### ISSUE THREAD

**Issue by jjmanton** [NuGet/Home#10882]
## Details about Problem

We will occasionally see a log message when restoring a large solution (250+ projects, with many hundreds of nuget packages) where the restore fails because `.nupkg.metadata` is being used by another process. This occurs on our build server, running on Core 2019.

Currently all projects are net48, but we have recently started mixing in some netstandard libraries as well. Is there some possibility of conflict?

NuGet product used: nuget.exe

Product version: Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework

Worked before? If so, with which NuGet version: We haven't seen this as a version dependent issue.

## Repro steps and/or sample project

Restore a large solution with many dependencies. We see this lock infrequently, but it will still fail our build maybe 1 in 20 times.

### Verbose Logs

```
build	19-May-2021 10:44:23	         The process cannot access the file 'E:\agt01\COM-CN-BAWAP\src\Bin\Packages\system.appcontext\4.3.0\.nupkg.metadata' because it is being used by another process.
```

**Comment by zkat** [comment]
We don't read this file ourselves, we only write it. If the file is being locked, it might very well be due to something in your environment like antivirus software, search indexing services, or network sync services like OneDrive.

Unless you can track down something in NuGet itself, there's too many moving parts for us to make a determination about what might be causing this.

**Comment by jjmanton** [comment]
@zkat Interesting. So I checked with the build team, and we use a "clean" Server Core 2019 image. The team who builds our CI images doesn't believe there is anything that could be touching these files.

Interesting you mention write-only. So would the suggestion be that something is locking the file before NuGet writes to it? Or would NuGet write this file more than once? We are restoring to a specified directory that is empty on build start. Something like this `nuget.exe restore sln -PackagesDirectory "/path/to/checked-out/src/bin/packages"`

I have a theory, but I wanted to see if this is even possible - 
1. We start with a clean directory and build, passing the parameters to NuGet to restore to a subfolder on this clean directory
2. NuGet starts restoring the Package `system.appcontext` for one of our net48 projects
3. NuGet is doing a parallel restore, and starts restoring `system.appcontext` for one of our netstandard projects simultaneously
4. The first restore has the lock open on `. nupkg.metadata` because it is writing the file?

Is the above scenario possible?

**Comment by jjmanton** [comment]
@zkat I did some digging, and found that NuGet DOES in fact read the .nupkg.metadata file. Looks to be used to get the package SHA512 hash when restoring and generating a lock file. From an outside perspective, I would think it should read the sha512 file, but I am not as familiar with the inner workings here.

Can you provide any guidance on next steps for me to investigate?

Here is an example stack trace if it's helpful - 
<img width="1454" alt="Screen Shot 2021-09-22 at 11 42 38 AM" src="https://user-images.githubusercontent.com/1005494/134376876-8337b552-fec3-433c-8528-8a8bda0597a1.png">

**Comment by tomascubeek** [comment]
The same problem is randomly happening on our side. Any (planned) progress here?

**Comment by jjmanton** [comment]
I found why we are seeing this more often than others. 

When restoring, we specify a custom location to place the packages. This leads to many packages being copied and unpacked, and potentially in parallel. It seems that two restores could attempt to unpack a nuget package at the same time, and there is not a clear way to know if a nuget package has completed being unpacked/unzipped. 

A possible solution might be to create a temporary file, something like `.unpacking`, while it is creating the nupkg.metadata, the sha512 file, and others, then deleting this file once complete. Other restore processes could look for this marker and block until the restore is complete. 

@tomascubeek Do you happen to be specifying a restore location, or are globally clearing packages frequently?

**Comment by zivkan** [comment]
NuGet has a class named [ConcurrencyUtilities](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/ConcurrencyUtilities.cs) that is used to make sure only one process is extracting the global packages folder at a time. However, it uses a file in the temp directory, so it requires all processes to use the same temp directory.

**Comment by zivkan** [comment]
Today I was trying to figure out why this might happen, but I just can't. We [open the file with `File.OpenRead`](https://github.com/NuGet/NuGet.Client/blob/bc11fd124fd87b55532742db2a56f4a324288bcb/src/NuGet.Core/NuGet.Packaging/NupkgMetadata/NupkgMetadataFileFormat.cs#L29), which I "hoped" would open the file without `FileShare.Read`, but on both [.NET Framework](https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,769) and [.NET (Core)](https://github.com/dotnet/runtime/blob/f41b259d779466068d5f7b1a16608e74e26a5e46/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L263) it does use `FileShare.Read`, and writing a really basic unit test that tries to read the same file in multiple threads in parallel, it doesn't reproduce the exception.

My next guess was that maybe when extracting a package, we write to the expected filename, and maybe a parallel restore process tries to read it before the process that created it closes the file. However, looking at our extraction code, [we generate a random filename for a temporary file](https://github.com/NuGet/NuGet.Client/blob/bc11fd124fd87b55532742db2a56f4a324288bcb/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L427), [write the file contents to the temporary file](https://github.com/NuGet/NuGet.Client/blob/bc11fd124fd87b55532742db2a56f4a324288bcb/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L501), and [the last thing the method does before exiting is move the temporary file to the real filename](https://github.com/NuGet/NuGet.Client/blob/bc11fd124fd87b55532742db2a56f4a324288bcb/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L550). Since the temp file and real file are in the same directory, I'd expect the `File.Move` to be atomic, without being locked. Therefore, it doesn't appear this root cause is feasible.

So, I can't figure out how/why this might be happening, and therefore not really sure what to change to ensure it doesn't happen again. If anyone who experiences this can manage to capture it happening in a PerfView trace, or a ProcMon capture, that would really help. But for now, I'm going to move on to other work.
