### ISSUE TITLE
[DCR]: Support TargetFramework/TargetFrameworkIdentifier/TargetFrameworkVersion for vcxproj if PackageReference capability is set.

### ISSUE THREAD

**Issue by jlaanstra** [NuGet/Home#11009]
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### Current Behavior

NuGet currently ignores any set TargetFramework/TargetFrameworkIdentifier/TargetFrameworkVersion etc if the project extension is vcxproj, and always returns Native, v0.0.

Teams that want to enable PackageReference support for UAP projects using the project system support as explained in https://github.com/dotnet/project-system/issues/2491 would be better suited by setting the TargetFrameworkMoniker to UAP,Version=v10.0 but this is currently not possible.

### Desired Behavior

If the PackageReference capability is set, NuGet doesn't always ignore TargetFramework/TargetFrameworkIdentifier/TargetFrameworkVersion etc if the project extension is vcxproj.

### Additional Context

Internal Microsoft teams have been struggling with the lack of proper Nuget PackageReference support. The limited support that seems to be available through the project system is great. This change would make the experience just a little bit better.

**Comment by heng-liu** [comment]
As of now, it seems we only support PackageReference for C++/CLI projects. (Refer to https://github.com/NuGet/Home/blob/dev/proposed/2021/NuGet-CPPCLI-Support.md)

**Comment by zivkan** [comment]
C++/CLI PackageReference support is still in development, not yet available.

C++ projects don't officially support PackageReference, and we need the C++ project system team to buy-in and make some changes for it all to work end to end. There's a duplicate issue, but this comment specifically you may be interested in: https://github.com/NuGet/Home/issues/8874#issuecomment-659702172

**Comment by jlaanstra** [comment]
@zivkan I'm aware of the explicitly supported scenario for C++/CLI projects under development. However other C++ projects can enable this themselves without official support and it would be nice if NuGet didn't get in the way.

If the project says it has the PackageReference project capability, then why would NuGet pretend it knows better and ignore the values for TargetFramework/TargetFrameworkIdentifier/TargetFrameworkVersion, just because my project file has a certain extension? 

For reference, I have a working example here: https://github.com/jlaanstra/CppWinRT-PackageReference

**Comment by zivkan** [comment]
Because every single native C++ project falsely claims to be .NET Framework (from memory 4.0). You can get an MSBuild binlog to check, or "pre-process" the project file.

This might be due to the fact that MSBuild and the Microsoft.Common.props and targets were created for .NET, not to be a generalised build tool, and VC++ adopted MSBuild, and possibly have to pretend to be .NET Framework so ProjectReferences pass compatibility checks. 

Regardless, packages with `build/native/packageId.props` wouldn't work, and NuGet package compatibility wouldn't work, for native projects without NuGet special casing projects with file extension vcsproj. The code that does this is shared between Visual Studio and PackageReference, hence why PackageReference makes this same detection, despite C++ projects not officially supporting PackageReference.

**Comment by jlaanstra** [comment]
> Because every single native C++ project falsely claims to be .NET Framework (from memory 4.0). You can get an MSBuild binlog to check, or "pre-process" the project file.

Indeed, the default is .NET Framework v4.0

> Regardless, packages with build/native/packageId.props wouldn't work, and NuGet package compatibility wouldn't work, for native projects without NuGet special casing projects with file extension vcsproj. The code that does this is shared between Visual Studio and PackageReference, hence why PackageReference makes this same detection, despite C++ projects not officially supporting PackageReference.

I understand what you are saying here: because of the .NET Framework 4.0 defaults, NuGet has to special case for the native TFM to work as it does today.

However, https://github.com/NuGet/NuGet.Client/pull/4076/files limited the special casing of vcxproj by checking for ClrSupport=NetCore. My proposal is to also limit the special casing if the project explicitly tells the project system that it supports PackageReference as shown at https://github.com/jlaanstra/CppWinRT-PackageReference/blob/9d55f61475460422ee30464d9e4b24f4c95e4d74/build/NuGet.targets#L5. Once someone explicitly sets this project capability I think it's ok to assume that they also know to set the proper values for TFM etc, so that the project doesn't claim to be .NET Framework 4.0 anymore :).

**Comment by zivkan** [comment]
Do you work on the C++ UWP project system?  If so, please reach out to us internally. I'm not deeply involved with the C++/CLI work, so I'm not sure if there are additional things that need to be taken into consideration, or if your proposal is in itself, sufficient. All I know is that for C++/CLI there's a bunch of work on the C++ project system side that needs to happen, in additional to changes in NuGet itself.

At a minimum we (NuGet) would need a way to tell the difference between a C++ UWP project and a native project.  TargetFramework[Identifer|Version|Moniker] is not sufficient due to the .NET Framework 4.0 claim.

I'll also ping someone more knowlagable than me about all this to see if he thinks we should re-open this issue, or have a discussion first.

**Comment by nkolev92** [comment]
For better or worse, PackageReference support is 2 fold. Commandline and VS and we have to consider both scenarios.

In VS, I think the biggest challenge here is actually ensuring that project system that loads the project supports what NuGet would need for PackageReference. 
The C++ team has been fairly consistent in their messaging that they don't want PackageReference support for vcxproj, so this kind of conflicts that.

All that being said, I don't think we should rely on the capability item because those tend to be project-system things. We'd need a commandline version as well. 

Finally, enabling transitivity would be something that we would have to consider. 
The build targets are a big reason of what makes PackageReference work.

**Comment by jlaanstra** [comment]
> In VS, I think the biggest challenge here is actually ensuring that project system that loads the project supports what NuGet would need for PackageReference.

Based on https://github.com/NuGet/NuGet.Client/pull/3644, C++ is a custom CPS project system and that PR suggests this would work.

> All that being said, I don't think we should rely on the capability item because those tend to be project-system things. We'd need a commandline version as well.

That's a good point. I suppose you could look at the value of ProjectRestoreStyle? 

> Finally, enabling transitivity would be something that we would have to consider.

Can you elaborate on what you mean by this? Isn't transitivity automatically enabled with PackageReference?

**Comment by nkolev92** [comment]
I worded that badly. 

We'd need to ensure that transitivity is done picked up correctly. 

Yes, with PR you get it automatically, but project to project transitivity matters as well, as there's an msbuild/build tasks component there that needs validated.

**Comment by mingkuang-Chuyu** [comment]
I hope to support it as soon as possible. The NuGet TFM feature is currently implemented through scripts, but it’s not very convenient to use. 

As for vcpkg, it cannot solve our needs. I have also tried to use vcpkg, but it can only solve some simple problems and is not suitable for advanced users like us.

**Comment by mingkuang-Chuyu** [comment]
In fact, I think the supporting work is not complicated. I maintain a branch separately, and C++ can use all the features of PackageReference.

The biggest problem now is that some teams are unwilling to support this work, even if it only requires minor changes. For them, vcpkg can solve all the problems.

I think this is ridiculous, and I feel sad for them...

I can proudly say that although they developed vcpkg, their knowledge of vcpkg is not as good as mine, and their knowledge of MSBuild is not as good as mine!

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8874. 

We missed this some time back.
