### ISSUE TITLE
Add additional tests for package namespaces (PackageReference) restore

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11038]
https://github.com/NuGet/NuGet.Client/pull/4149#pullrequestreview-708764573

Similarly to packages.config, we should a bunch of other scenarios.

For example:

* Add tests for `RestoreSources` in project file. 
* Add tests for dotnet add package, which calls restore itself.
* Add  tests restore `-source`.  (This comment will be addressed in https://github.com/NuGet/Home/issues/10948)

Update: 

- [x] dotnet add package tests including `RestoreSources` and `-SourceUri` https://github.com/NuGet/NuGet.Client/pull/4225
- [x] PMC tests - added one install and one update PMC test in https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-pmc-tests-pr-namespaces
- [x] Restore Sources tests for nuget.exe and dotnet.exe. - `Restore Sources tests for nuget.exe` are also added by Erick in https://github.com/NuGet/NuGet.Client/pull/4214. I added couple of tests in the PR linked to this issue to tests `dotnet.exe` restore sources scenario.
- [x] Source option tests for nuget.exe and dotnet.exe. @erdembayar added tests for these scenarios in https://github.com/NuGet/NuGet.Client/pull/4214
- [x] End to end tests (EndToEnd or Apex specifically doesn't matter), Implicit restore/solution restore. Instlal/Update are covered in an above point.

**Comment by nkolev92** [comment]
Moved this to the next sprint. 

I would prioritize these tasks for the next sprint @kartheekp-ms

**Comment by nkolev92** [comment]
Epics shouldn't have estimates themselves, but rather add up from the issues owned by it.

**Comment by nkolev92** [comment]
@kartheekp-ms What is leftover here? 

I tweaked in order to make planning obvious. Adding back the estimate.

**Comment by kartheekp-ms** [comment]
Made some progress on this task: Added couple of tests for PMC Install/Update package scenarios for source mapping feature https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-pmc-tests-pr-namespaces

I will create PR's next sprint.

**Comment by nkolev92** [comment]
Please note that @erdembayar has a task about PMC tests in https://github.com/NuGet/Home/issues/11187. 

Can you please consolidate and ensure that you're both not doing the same work/have dup issues? 

Thanks!

**Comment by kartheekp-ms** [comment]
@erdembayar here is the progress made on this issue so far.
- [x] dotnet add package tests including `RestoreSources` and `-SourceUri` https://github.com/NuGet/NuGet.Client/pull/4225
- [ ] PMC tests - added one install and one update PMC test in https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-pmc-tests-pr-namespaces - The new 2 tests passed on CI. As Nikolche mentioned above, you can combine this work with https://github.com/NuGet/Home/issues/11187
- [x] Restore Sources tests for nuget.exe and dotnet.exe.
- [ ] Source URI tests for nuget.exe and dotnet.exe.
- [ ] End to end tests (EndToEnd or Apex specifically doesn't matter)

Please let me know if I am missing anything.

**Comment by erdembayar** [comment]
@kartheekp-ms @nkolev92 @aortiz-msft 
I tried to create test cases for PR type for Apex, End2end test. 
But it looks we need whole new way of testing for package source mapping. Because each test for PR restore automatically put restored package into GPF but it pollutes restore environment for next package source mapping test. 
So we have 3 choices:
* Remove restored packages from GPF at end of test. But there're transitive packages so not straight forward. Most likely not practical.
* Create new GPF with prepopulated necessary packages for each test then clean up at end of each test. But it'll increase our repository size by 100Mbs and it'll slow our tests.
* Each test use new unique packages. Most likely not practical.

Maybe put it on hold for now, we need discussion next week on this.

**Comment by kartheekp-ms** [comment]
@erdembayar - Can we use a custom `globalPackageFolder` setting the `nuget.config` file for every test so that the machines folders are untouched?

https://github.com/NuGet/Samples/blob/main/PackageSourceMappingExample/nuget.config#L6

**Comment by erdembayar** [comment]
> @erdembayar - Can we use a custom `globalPackageFolder` setting the `nuget.config` file for every test so that the machines folders are untouched?
> 
> https://github.com/NuGet/Samples/blob/main/PackageSourceMappingExample/nuget.config#L6

That is the 2nd option I proposed. In order to build NetCoreConsoleApp we need prepopulate `Microsoft.NETCore.App, microsoft.codeanalysis.csharp` etc quite many packages.

**Comment by erdembayar** [comment]
@kartheekp-ms 
I noticed allmost all except 1 netcore Apex tests are skipped/disabled due to being flaky test. Not sure if I add more test then it may add more flaky tests.

For example:
https://github.com/NuGet/NuGet.Client/blob/1af032a9a12c530ef434e9ea1a53cd93348e1146/test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs#L202-L209

https://github.com/NuGet/NuGet.Client/blob/1af032a9a12c530ef434e9ea1a53cd93348e1146/test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NetCoreProjectTestCase.cs#L31-L38

**Comment by erdembayar** [comment]
Maybe we need to find solution leveraging Dartlab(download needed packages during machine provision instead of adding to repository) for this since Apex tests are [moving to 1ES](https://github.com/NuGet/Client.Engineering/issues/1069).

**Comment by nkolev92** [comment]
We could consider adding our own templates, potentially ones that target .NET Framework instead. 

Updating the used apex version might be a good idea s well.

We could investigate how other people run tests like that. 

In general though, we should isolate the tests from impacting the global packages folder. 

It really is the same feedback we've often had on the unit/integration tests themselves.
