### ISSUE TITLE
[Bug]: registration endpoint does not always report upper correctly

### ISSUE THREAD

**Issue by rogerfar** [NuGet/Home#11061]
### NuGet Product Used

NuGet.exe

### Product Version

Nuget API

### Impact

Other

### Repro Steps & Context

Browse to this repository:
https://www.nuget.org/packages/Serilog.Exceptions/
Latest version is 7.0.0

But when browsing to the registration metadata:
https://api.nuget.org/v3/registration5-semver1/serilog.exceptions/index.json

It reports 5.4.0 as the upper, which can be accessed:
https://api.nuget.org/v3/registration5-semver1/serilog.exceptions/5.4.0.json

But not 7.0.0:
https://api.nuget.org/v3/registration5-semver1/serilog.exceptions/7.0.0.json

It returns a 404.

I have checked a few 100 packages and this one seems to be the only one with this issue.

**Comment by rogerfar** [comment]
Now, it does work for `https://api.nuget.org/v3/registration5-gz-semver2/serilog.exceptions/index.json` because it's semver 2, but shouldn't the default `RegistrationsBaseUrl` from `https://api.nuget.org/v3/index.json` not switch to semver2 at some point?

**Comment by zivkan** [comment]
`RegistrationsBaseUrl` is not the default, rather it is the backwards compatible resource for the oldest NuGet clients that didn't support the `resource/version` syntax.  Changing this URL to point to the semver2 folder structure will break these old clients that don't support semver2, gzip, or any other feature that was added to the package metadata resource since the initial release.

See also our docs: https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource
