### ISSUE TITLE
Tooltip of the installed vulnerable/deprecation package versions’ warning icon is not clear

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11103]
## Details about Problem
VS Version: Main\31528.327
NuGet Version: Dev\6.0.0.166
OS Version: Windows-10-Enterprise-21H1
## Repro steps
1. Create a solution with two C# Console App (.NET Framework 4.8) projects in VS.
2. Right-Click the solution in the Solution Explorer and select the “Mange NuGet Packages for Solution”
3. Go to “Browse” tab and search for a vulnerable package - refer to the packages list in [GitHub Advisory Database](https://github.com/advisories?query=ecosystem%3Anuget) (e.g. “RestSharp”).
4. Install version “106.10.0” (vulnerable) into the first project and version “106.10.1” (vulnerable) into the second project.
5. Hover on the warning on the right of the “Installed” tab and observe the tooltip.
6. Add a deprecation package source https://apidev.nugettest.org/v3-index/index.json and search for a deprecation package (e.g. “afine”).
7. Install deprecated version “10.0.0” into the first project and the deprecated version “11.1.1” into the second project.
8. Hover on the warning on the right of the “Installed” tab and observe the tooltip.
## Expected
The tooltip should be clear (e.g. saying like: “You have 2 vulnerable/deprecated package versions installed”) in step5/step8.
## Actual
The tooltip is not clear: “You have 2 vulnerable/deprecated package(s) installed” in step5/step8.
![image](https://user-images.githubusercontent.com/20632625/127447100-e7750f47-452e-49af-96f5-85328c4d43bc.png)
## Notes:
It is not a regression bug.

**Comment by chrisraygill** [comment]
@jebriede 

For the expected tooltip, let's go with:

“You have {0} vulnerable package versions and {0} deprecated package versions installed.”
“You have {0} vulnerable package versions installed.”
“You have {0} deprecated package versions installed.”

The tooltip should be the same regardless of if it's in the solution or project level PMUI since the additions of "versions" makes it accurate in both instances.

I purposefully removed the "(s)" in favor of keeping it plural because the VS design guidelines state things that could be plural or singular should always use the plural form as per https://devdivdesignguide.azurewebsites.net/processes/craftsmanship-checklist/#style.
