### ISSUE TITLE
[Pack][Doc] A confused error shows when running “dotnet pack” with incorrect option “-p:TargetFrameworks=net45”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11106]
## Details about Problem
VS Version: Main\31529.265
NuGet Version: Dev\6.0.0.168
OS Version: Windows-10-Enterprise-21H1

## Repro steps
1. Launch VS and create a new C# Class Library (.NET 6.0).
2. Open the Developer Command Prompt and cd to the project path.
3. Run command “dotnet pack -p:TargetFrameworks=net45”.

## Expected
The error should make sense (such as: we can’t pack a .NET 6.0 package into .NET Framwork 4.5).

## Actual
A confused error shows as below.
![image](https://user-images.githubusercontent.com/20632625/127632771-6dd841e2-9f06-45bd-84a8-bd57b02d6a4b.png)

**Comment by erdembayar** [comment]
I can repro this. It looks error message need to be improved.

**Comment by nkolev92** [comment]
This issue is....interesting. Let's use that word! :) 

1. When a new project is created, the TargetFramework property is the one that's set, and it's value in this case is `net6.0`. 
1. TargetFrameworks property is used by both NuGet & SDK to dispatch inner builds. 


When both `TargetFramework` and `TargetFrameworks` are set, things can get weird. 

Usually, you'd only have one set and the other one could be inferred from the other, ie TargetFramework inferred from TargetFrameworks. 

Now the issue is that TargetFramework is set as well, so it effectively renders `TargetFrameworks` as unimportant. 

You can easily repro this issue with something like: 

```xml

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net45;net46</TargetFrameworks>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

``` 

The issue is that net5.0 is being treated as the framework value at build time. 
Restore on the other hand, when batching sets `TargetFramework` as a global property, effectively overriding the value in the project file. 

Static graph restore doesn't run into this problem, but only standard restore does. 
I'd argue this is not important enough to fix, given that no one has complained about it in over 4.5+ years.

To have a representative test case, please replace `TargetFrameworks` with `TargetFramework`.
