### ISSUE TITLE
[Bug]: The package version dropdown in the VS PMUI package details pane doesn't show which versions are deprecated in the Browse tab, but does in the other tabs

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#11129]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.0 preview 3

### Worked before?

I think so, but not sure which version. Bug exists in 16.11 preview 3.

### Repro Steps & Context

**Repro**

1. Got to the VS PMUI Browse tab
2. Search for WindowsAzure.Storage (all versions are deprecated)
3. Select WindowsAzure.Storage to open the package detail pane
4. Click on version dropdown menu
5. Notice that none of the version numbers show "(Deprecated)" next to them

![image](https://user-images.githubusercontent.com/15097183/128244692-51fbed36-3b0b-474b-b4f1-216913d5b5dc.png)

**Expected behavior**

In the Browse tab, the version dropdown menu should show which versions are deprecated. This currently works in the Installed and Updates tabs as shown:

![image](https://user-images.githubusercontent.com/15097183/128244802-72bf5be8-ade6-44a9-92a0-24647d267f49.png)

This should work in both the project and solution level PMUI windows.

**Comment by aortiz-msft** [comment]
@martinrrm - Would you please take a look at this one? Feel free to sync with @jebriede

**Comment by donnie-msft** [comment]
I believe this bug may be because `PackageItemViewModel.UpdatePackageStatus()` is only called with a collection of installed packages. Browse tab should also be loading this metadata for packages not yet installed, so I'm not sure how this was designed to work. Perhaps I'm missing something...
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/ViewModels/PackageItemViewModel.cs#L689
/cc @jebriede @martinrrm

**Comment by martinrrm** [comment]
Deprecated and Vulnerabilities information is available in Browse tab in versions dropdown.
