### ISSUE TITLE
[Bug]: VS Credential Provider Incorrectly Setting Value of `isRetry`

### ISSUE THREAD

**Issue by leong-desco** [NuGet/Home#11210]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Microsoft Visual Studio Professional 2019 Version 16.10.3 (NuGet Package Manager 5.10.0)

### Impact

It's more difficult to complete my work

## Problem

The [documentation](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio#creating-a-nuget-credential-provider-for-visual-studio) for NuGet credential providers for Visual Studio (NCPVS) states that the value of the `isRetry` parameter should be set to true "if credentials were previously requested for this Uri, but the supplied credentials did not allow authorized access."

[Other](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers#input-parameters) Microsoft documentation (albeit not specifically for VS, but still for NuGet credential providers) states that "[IsRetry] indicates that this attempt is a retry of a previously failed attempt."

For context, we have an on-premise authenticated NuGet feed that is configured to disallow anonymous access. That is, each user must provide an Nuget-specific username & password when accessing that NuGet feed. Each time an operation is performed on the  feed from within the Visual Studio Package Manager UI (e.g. list all packages, install a package), we're presented with a 401 Unauthorized challenge. Then, if valid credentials are presented, the challenge flow proceeds successfully, but if not, we are met with a 403 Forbidden.

I can verify that my NCPVS is being called with `isRetry == false` for the first operation, and then `isRetry == true` for all subsequent operations. This is contrary to what I would expect -- I would expect `isRetry == false` for all of the subsequent requests because the NuGet-specific username and password remains the same, so there is no reason why the set of credentials should not be authorized. Indeed, after debugging my NCPVS, the reason for setting `isRetry == true` is not because the credentials were explicitly forbidden, but rather because the request to the NuGet feed returned a 401 challenge.

Setting `isRetry == true` only upon encountering a 403 makes sense because a NuGet feed that requires authentication should be forcing the NuGet client (whether that be VS, `NuGet.exe`, etc.) to authenticate with a 401 request each time we "hit" that protected NuGet feed. I believe that NuGet should only retry if the provided credentials were explicitly forbidden, not if we were simply presented with a 401 challenge.

As it stands right now, the existing implementation will cause our NCPVS to have its [GetCredentialAsync](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio#getcredentialasync) method with `isRetry == true`. Becuase there's no other way of determining whether the reason for setting `isRetry == true` was because of a 401 Unauthorized, 403 Forbidden, or something else, we always assume the worst case (i.e. a 403 caused by stale credentials) and obtain new credentials from our internal service. This causes unnecessary delay in returning correct credentials from the credential provider, and strain on our internal services.

## Proposed Solution

The logic for determining what value to assign `isRetry` is at [`CredentialService.cs:93`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Credentials/CredentialService.cs#L93). From inspection, I'm deducing that the `_retryCache`'s purpose is to record which credential providers have authenticated with which URLs. The `_retryCache` for a given credential provider and URL will be set to true if the NCPVS has attempted to authenticate with this URL before, irrespective of the [reason](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Credentials/CredentialService.cs#L77) (e.g. Unauthorized, Proxy, Forbidden).

I propose that the `isRetry` variable should only be set to true if the [`type`](https://gist.github.deshaw.com/leong/bfc381e551cbbadfc029071de05a92bc#file-credentialservice-cs-L77) argument to the `GetCredentialsAsync` method is `type == CredentialRequestType.Forbidden`. Indeed, in [NuGet's source code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Credential/CredentialRequestType.cs#L18-L21) for `CredentialRequestType.Forbidden`, it states that "A different set of credentials could solve this failure". Indeed, this is consistent with the documentation quoted in the first two paragraphs of this bug report. Thus, it makes sense only to set `isRetry` to `true` if the following conditions are met:

```csharp
diff --git a/src/NuGet.Core/NuGet.Credentials/CredentialService.cs b/src/NuGet.Core/NuGet.Credentials/CredentialService.cs
index 2524dd0a1..c6fe34461 100644
--- a/src/NuGet.Core/NuGet.Credentials/CredentialService.cs
+++ b/src/NuGet.Core/NuGet.Credentials/CredentialService.cs
@@ -90,7 +90,7 @@ public CredentialService(AsyncLazy<IEnumerable<ICredentialProvider>> providers,
                 cancellationToken.ThrowIfCancellationRequested();
 
                 var retryKey = RetryCacheKey(uri, type, provider);
-                var isRetry = _retryCache.ContainsKey(retryKey);
+                var isRetry = (type == CredentialRequestType.Forbidden) && _retryCache.ContainsKey(retryKey);
 
                 try
                 {
```

**Comment by zkat** [comment]
Hey there! Nice sleuthing, and thanks for taking the time to do that. It sounds like you have a solution in mind, so how about sending us a PR with your proposed patch and we can discuss further? :)

**Comment by nkolev92** [comment]
Tweaking some of the labels as this is not VS only. It's a general issue with authentication and applies to commandline scenarios as well.

**Comment by zivkan** [comment]
https://github.com/NuGet/Home/issues/11801 was a duplicate, and had 2 upvotes at the time it was closed.

**Comment by zivkan** [comment]
I had a brief chat with @kartheekp-ms, and I'm also using this as an excuse to use Mermaid for the first time 😁.  But keep in mind I consider my knowledge of NuGet's credential provider to be almost zero.

Let's consider the timeline where the server uses HTTP basic auth (so not Azure Active Directory, or other OAuth2 where the cred provider will validate username/password before passing back the token to NuGet). The customer has two accounts, one has access to the feed, the other does not. The first time the customer enters the wrong password.

```mermaid
sequenceDiagram
  autonumber
  actor Customer
  participant CredProvider
  participant NuGet
  participant Server
  NuGet->>Server: no auth header
  Server->>NuGet: HTTP 401
  NuGet->>CredProvider: isRetry: false
  CredProvider->>CredProvider: Check for cached token
  CredProvider->>Customer: Prompt for username/password
  Customer->>CredProvider: Enters NoAccessAccount, wrong password
  CredProvider->>NuGet: HTTP BASIC Combo1
  NuGet->>Server: Auth: HTTP BASIC Combo1
  Server->>NuGet: HTTP 401
  NuGet->>CredProvider: isRetry: true
  CredProvider->>Customer: Prompt for username/password
  Customer->>CredProvider: Enters NoAccessAccount, correct password
  CredProvider->>NuGet: HTTP BASIC Combo2
  NuGet->>Server: Auth: HTTP BASIC Combo2
  Server->>NuGet: HTTP 403
  NuGet->>CredProvider: isRetry: true
  CredProvider->>Customer: Prompt for username/password
  Customer->>CredProvider: Enters CorrectAccount, correct password
  CredProvider->>NuGet: HTTP BASIC Combo3
  NuGet->>Server: Auth: HTTP BASIC Combo3
  Server->>NuGet: HTTP 200
```

The proposed change in the original comment, I believe, will change step 10 above to `isRetry: false`. However, in my opinion, looking at the sequence diagram, that it is a retry, because the first credentials provided were incorrect.

> ecuase there's no other way of determining whether the reason for setting isRetry == true was because of a 401 Unauthorized, 403 Forbidden, or something else, we always assume the worst case (i.e. a 403 caused by stale credentials) and obtain new credentials from our internal service.

Shouldn't stale credentials return HTTP 401 (Unauthorized)?  Otherwise, how are you supposed to tell the difference between "OAuth2 token is stale" vs "token is valid, but user does not have access to this feed".

Anyway, I think that NuGet and the Credential Providers talk via JSON, right?   In my opinion, we should add "LastHttpResponseCode" as a new property, so that CredProviders can guess between "token has expired" and "this user doesn't have access".  Hopefully credential providers don't deserialize in strict mode, otherwise this idea would break them 😨

**Comment by kartheekp-ms** [comment]
Great diagram Andy. I love using Mermaid too.

The question that I have is should the `retry` be set to `true` for `sequence no:16` in the diagram?

**Comment by zivkan** [comment]
On the topic of expired OAuth2 tokens, doing just a quick search, I found this interesting StackOverflow answer about refreshing OAuth2 tokens: https://stackoverflow.com/a/30826806/2843065

It claims that Facebook retuns HTTP 467 Invalid access token, whereas LinkedIn and PayPal return HTTP 401 Unauthorized. I'm not an auth expert, but I'm guessing it might be possible that all HTTP 401 (or 467) can be treated as "refresh token", since "invalid username/password combo" should be handled within the cred provider, and the cred provider will never provide nuget with a token until the username/password is fixed.

Anyway, it also says that the OAuth2 spec recommends that responses contain an `expires_in` field. I'm not sure if "field" means HTTP header or something else.  If it is an HTTP header in the response, maybe NuGet should monitor this and when it's smaller than some threshold, keep an internal flag so that the next HTTP request should talk to the CredProvider again with `isRetry: false`.
