### ISSUE TITLE
[Bug]: Corrupt package cache downloads result in error when reading nupkg: 'Number of entries expected in End of Central Directory...

### ISSUE THREAD

**Issue by Redth** [NuGet/Home#11226]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet.* .NET Libraries API/Client - 5.10.0

### Worked before?

Unsure

### Impact

Other

### Repro Steps & Context

There is an intermittent problem with corrupt package (nupkg/zip) downloads in the package cache where invoking some of the NuGet Client API's from the .NET Libraries on NuGet results in an error:

```
Workload installation failed: Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
```

I've observed this using the NuGet Client API libraries myself with the `CopyNupkgFileToAsync(..)` method: https://github.com/Redth/dotnet-maui-check/blob/main/MauiCheck/AcquirePackagesCommand.cs#L196

After deleting the package cache, and trying again, it often works as it downloads a new version to the cache which happens to not be corrupt.

This is becoming an increasingly frequent problem with `dotnet workload` commands ( See https://github.com/dotnet/sdk/issues/20849 ).

It's possibly more frequent and/or related to using NuGet package feeds hosted on Azure DevOps.

It seems like the client API should be doing some sort of validation on packages it downloads before writing them to any cache to avoid caching a corrupt zip file.

**Comment by wli3** [comment]
@zivkan ring a bell?

**Comment by zivkan** [comment]
This is the only other issue I can find that's a bit similar, but in this case it was files in Visual Studio's offline feed that were corrupt: https://github.com/NuGet/Home/issues/11089

Otherwise, no, I'm not aware of any other customers reporting this to NuGet directly. Seems strange that after 10 years this is becoming a problem now, but it would be good time find a plan to deal with it. Unfortunately I don't have any immediate, obvious ideas that won't harm performance.

**Comment by AraHaan** [comment]
Perhaps what nuget could do is download a hash to a specific package and version (which is the actual hash of the package) and then when it tries to cache it it then hashes the package that is cached with the downloaded hash file (that is also written to that cache folder with the package). I think that could be an option. As for hashing algorithm would crc32 be doable since it can be done using a specific cpu instruction for it on most modern cpus (which I think should be fast to do and calculate)?

**Comment by zivkan** [comment]
From https://github.com/dotnet/sdk/issues/20849#issuecomment-960920701

The .NET CLI is telling Nuget to use `DirectDownload = true`, and I can't find anything that resets the stream position to the beginning of the file, so I think what's happening is the retry is writing the second download attempt at a non-zero offset, so then the zip file's central directory offsets are all wrong.
