### ISSUE TITLE
[Feature]: Support ECDSA certificates for package signing

### ISSUE THREAD

**Issue by vcsjones** [NuGet/Home#11232]
### NuGet Product(s) Involved

NuGet.exe, dotnet.exe

### The Elevator Pitch

Currently, nuget package signing is limited to RSA signing. Attempting to sign with an ECDSA certificate results in:

> error: NU3013: The signing certificate has an unsupported signature algorithm.

ECDSA signatures are smaller, more secure, and generally regarded as an improvement over RSA.

### Additional Context and Details

Windows Authenticode and many, many other signing specifications have supported ECDSA for several years.

**Comment by vcsjones** [comment]
I took a look through the package signing code and I don't think adding ECDSA would be difficult and would be happy to do so myself. (It's a considerable amount of work, but it isn't especially difficult just to get ECDSA working in the CMS).

What would be difficult is I think this would mean revving the package signing version. Currently there is only one version. Older clients would not understand ECDSA signatures. `NuGet.Server` would probably need to get smart about ECDSA certificates, but interestingly enough it does not currently reject an ECDSA certificate on a user profile.

Given the above, is there interest in accepting a community proposal / contribution for this?

**Comment by blowdart** [comment]
One other thing to consider is that the [PIV standard](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-78-4.pdf) only specifies support for 2048 keys, or ECDSA keys. The standard for code signing certificates increased the RSA key size to 3096. So right now, to support nuget signing, you cannot store the private key on a Yubikey or other portable hardware device using the PIV standard, so you either have the private key in the certificate store locally (thus increasing the risk of a supply chain attack), or you use an HSM, KeyVault or whatever random secret mechanism your build pipeline uses, increasing the cost and complexity for developers, as well as presenting another supply chain attack route.

**Comment by aortiz-msft** [comment]
Hey @dtivel , any thoughts? Breaking older clients seems like big problem.

**Comment by dtivel** [comment]
Yes, adding support for ECDSA will break older clients.  I think we'll have to service older clients.

**Comment by zooba** [comment]
Presumably breaking older clients would just mean that they can't validate those signatures?

My next three years of releases to Nuget will have to be unsigned, because my code signing certificate only supports ECDSA. This means that older clients will fail in exactly the same way, but newer clients will also fail. Everyone loses 🤷‍♂️

**Comment by levicki** [comment]
@aortiz-msft This issue needs much higher priority.

Certificate Authority/Browser (CA/B) Forum’s [new key storage requirements](https://cabforum.org/2022/04/06/ballot-csc-13-update-to-subscriber-key-protection-requirements/) which start being enforced from **July 1st, 2023** prescribe that private keys must be stored in non-exportable form (USB tokens, HSMs, cloud service, etc).

Given that majority of PIV based USB tokens do not support RSA keys larger than 2048 bits that effectively means phasing out RSA keys and replacing them with ECDSA. Many CAs are already issuing only ECDSA keys because of this, and right now we can't use those keys to sign nuget packages.

I understand the concern about breaking old clients, but IMO the inability to sign nuget packages and establish the chain of trust is much worse than just the inability of old clients to verify newly signed packages.

They should upgrade their clients if they want to stay in the game, and Microsoft who voted yes on the CA/B proposal in question should put their money where their mouth is and support ECDSA signatures now.

**Comment by aortiz-msft** [comment]
@dtivel @nkolev92

**Comment by dtivel** [comment]
NuGet won't be adding ECDSA support for package signing at this time.  I understand that ECDSA offers some advantages over RSA, but they're not enough to tip the scale in favor of doing it.

Some PIV standard Yubikeys don't support larger RSA keys, but as I understand it, those tokens don't conform with CAB Forum's new storage requirements.  HSM's support the new requirements and support larger RSA keys.
