### ISSUE TITLE
[Bug]: Pack fails when adding readme file but not using snupkg

### ISSUE THREAD

**Issue by timheuer** [NuGet/Home#11271]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

6.0.100-rc.1.21458.32, VS 2022 Preview 5

### Impact

I'm unable to use this version

### Repro Steps & Context

Sample repo (use packbug branch): https://github.com/timheuer/alexa-skills-dotnet/tree/packbug

I'm adding the readme information via the project properties UI in Visual Studio 2022.  It generates:

`<PackageReadmeFile>readme.md</PackageReadmeFile>`
and
```
  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
    </None>
  </ItemGroup>
```

After executing `dotnet pack` or using right-click pack:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU5039	The readme file 'readme.md' does not exist in the package.	Alexa.NET	C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	
```
The file is indeed there.  Video
![2021-09-24_14-59-59](https://user-images.githubusercontent.com/4821/134744065-77d8dbee-eb9a-4961-b0a4-9f1bdac43b02.gif)
:

**Comment by anangaur** [comment]
Seems like a blocking issue for README adoption using Visual Studio. @chgill-MSFT, can we prioritize fixing this for VS 2022 GA.

**Comment by heng-liu** [comment]
Hi @timheuer , thanks for taking time filing this issue!
I could repro with your branch.
I haven't looked into it much, but just tried to make the following change then seems the packing is successful:
Changed
```
  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
    </None>
  </ItemGroup>
```
into:
```
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath=""/>
  </ItemGroup>
```
Could you try this and see if that would unblock you? Thanks!

**Comment by timheuer** [comment]
Yes indeed this does unblock -- I just wanted to make sure I logged the issue of what the tools are generating appearing to be invalid settings.  I'm unblocked with your workaround of fixing the tool-generated proj settings.

**Comment by heng-liu** [comment]
Looks like the error is caused by missing `PackagePath` property.
Do we need to call that out in our [doc](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)? @chgill-MSFT @zkat

**Comment by chrisraygill** [comment]
When I tried packing a README with VS 17.0 preview 5, it generated the `<PackagePath>` property.

Maybe project systems already fixed this? 

![image](https://user-images.githubusercontent.com/15097183/134960031-bec1e617-f355-459a-95e2-4cc614b0a3df.png)

**Comment by timheuer** [comment]
@chgill-MSFT put the readme.md file at the same location as the proj file and then do the same action...this seems to be the trigger.  When I tried it with a file outside of that location it does appear to generate the `PackagePath` attribute correctly...but when the MD file is at the root project-relative path seems to be the issue.

**Comment by aortiz-msft** [comment]
@zkat  - Could you please take a look?

**Comment by chrisraygill** [comment]
I was able to repro Tim's issue when adding the readme.md file to the same location at the proj file. For reference, here are a few different scenarios:

**README is in same directory as proj file**
<img src="https://user-images.githubusercontent.com/15097183/134973019-96797d70-a05f-4fc6-a4b8-7cc58a44f0da.png" width="500">

**README is in solution root directory**
<img src="https://user-images.githubusercontent.com/15097183/134974136-94949a61-b99d-45dc-b0f9-40334bfb6539.png" width="500">

**README is outside repo solution root directory**
<img src="https://user-images.githubusercontent.com/15097183/134974320-d97001e4-8d2d-480d-9f0a-96fee6c2931b.png" width="500">

In addition to omitting the `<PackagePath>` element, it looks like referencing a file in the proj file directory also changes `<None Include="">` into `<None Update="">`.

Unfortunately, this bug seems to extend to any embedded package element including icons and licenses:

<img src="https://user-images.githubusercontent.com/15097183/134977145-f1caecf6-c78d-40dc-ae3a-7b6bafc9f274.png" width="500">

Do we know if this is a bug on our side or project systems? 

+ @miyanni who implemented the README property into the package properties menu.

**Comment by chrisraygill** [comment]
Confirmed that this behavior is a regression in 17.0. This scenario worked fine for icons in VS 16.11 and used the proper "include" and added the "PackagePath".

The bug exists in both 17.0 preview 3 and 5, so it was probably introduced with the new project system menu.

<img src="https://user-images.githubusercontent.com/15097183/134979491-b35bab4b-974a-46e6-869c-88612146f5dc.png" width="500">

**Comment by zkat** [comment]
I guess it's a project system issue?

**Comment by chrisraygill** [comment]
I filed this issue in the project systems repo to track since it looks like the bug is on their side:

https://github.com/dotnet/project-system/issues/7642

Thanks for bring this to our attention @timheuer!

**Comment by aortiz-msft** [comment]
Transferred issue to https://github.com/dotnet/project-system/issues/7642

**Comment by MiYanni** [comment]
General Question: Why would an empty `<PackagePath></PackagePath>` item attribute have significance?

This project file is primarily used by MSBuild, and in that system, an empty value and an omission of the attribute are the same. Shouldn't that be the case here? If it isn't, it should be fixed on the NuGet packing side of things. When reading the documentation, it was not obvious that an empty value for the attribute was required; the docs made it seem like that the default for this would understand it as empty. Also, the value `"/"` makes this a bit more confusing too; is that would be equivalent to empty, correct?
