### ISSUE TITLE
Uninstall of packages fails

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1131]
Uninstall of packages fails in some projects. Have not yet found the cause, but I have a repro:

* Clone `https://github.com/NuGet/NuGetGallery`
* Update to commit `f26abfe69158835dc72613ef4b546f9dd79c5b21` (`git reset --hard f26abfe69158835dc72613ef4b546f9dd79c5b21`)
* Try uninstalling NInject after opening the solution in VS2015

**Comment by emgarten** [comment]
@maartenba what is the output in the console? Is this from the UI or PS?

**Comment by maartenba** [comment]
From the UI, not seeing any output :(

**Comment by emgarten** [comment]
Here are the steps I tried
1. Build/Restore packages 
2. Launch NuGet UI for NuGetGallery
3. Select installed
4. Select Ninject 
5. Select uninstall from the drop down - 3.2.0
6. Uninstall (only the preview option selected)

The output window and error window show the message:
Unable to uninstall 'Ninject.3.2.0' because 'Ninject.MVC5.3.2.1, Ninject.Web.Common.3.2.0' depend on it.

After removing all other ninject packages Ninject 3.2.0 uninstalls fine.

There are some known scenarios where the error is hidden in the error list, so it may not be obvious what the failure message is. There are bugs for this already.

**Comment by maartenba** [comment]
In that case this may be a dupe. Will see if I can trap an error.

**Comment by maartenba** [comment]
I did upgrade my NuGet extension this week so not sure if that fixed it, am unable to reproduce the issue.
