### ISSUE TITLE
[Bug]: [Bug Bash] There is an inconsistency between the tooltip and the details info about the vulnerability number

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11314]
### NuGet Product Used
Visual Studio Package Management UI

### Product Version
NuGet Client Dev\6.1.0.18

### Impact
It bothers me. A fix would be nice

### Repro Steps & Context
1.	Create a C# Console App (.NET core) project via VS.
2.	Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3.	Select package source: Nuget.org
4.	Search a vulnerable package (refer to GitHub Advisory Database, e.g. “Microsoft.ChakraCore”) in the package list and choose a vulnerable version (e.g. 1.11.18) in the “Version” dropdown list.
5.	Install the vulnerable package and go to “Installed” tab.
6.	Hover on the tooltip icon on the left of the installed vulnerable package version and compare to the details info on the right panel about the vulnerability number.
### Expected: 
They should be consistent.

### Actual: 
There is an inconsistency between the tooltip and the details info of the vulnerability number as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/137472790-fbaf6139-c731-4744-87e6-139f61adfa2c.png)
### Notes: 
1. It is not a regression.

**Comment by jebriede** [comment]
@chgill-MSFT I think we should close this bug unless we're hearing customer feedback. To say the package version has "a" vulnerability does not actually mean it has "one" vulnerability which the bug is reporting. It is true that when there are one or more vulnerabilities with X severity, that the package version has "a" vulnerability. We could change "...a vulnerability..." to "...one or more vulnerabilities..." but before making the message more verbose, I think we should wait to see if there is customer feedback. Thoughts?

**Comment by chrisraygill** [comment]
This issue is too minor for most customers to find worth complaining about.

I think the string is fine as it is. Like JP said, it is a true statement and should be sufficient to motivate customers to learn more by selecting the package. Tooltips are just meant to communicate what a symbol means - and this sufficiently accomplishes that task.

**Comment by jebriede** [comment]
Closing bug as by design. Please see comments by @jebriede and @chgill-MSFT above.
