### ISSUE TITLE
Installed packages load slowly and does not show up at all in case of network failure(s)

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1139]
Installed packages load slowly and does not show up at all in case of network failure(s)

From a customer:

<i>When I go to the installed packages, it takes a very very long time just to access the network. Meanwhile the list of packages is blank.
Then, in the case there is a network failure (and this happens very often with nuget, probably because of timeouts), there is an error regarding the access to the network and we cannot manage the currently installed packages</i>

**Comment by raffaeler** [comment]
Thank you Deepak for filing the bug

**Comment by feiling** [comment]
@raffaeler, could you tell us the version of nuget you're using (select Tools -> Extensions and Updates, then select NuGet and you'll get the build version of NuGet)? We made some improvements recently so that user can work with installed packages even if s/he is offline. I didn't see the behavior you described with the latest build.

**Comment by raffaeler** [comment]
As I told Yishai, the version number is 3.1.60724.766 which, afaik, is the latest.

**Comment by raffaeler** [comment]
I just sniffed with Fiddler the requests. I opened nuget for the solution and, as the last time I was managing the installed packages, it started with the same kind of request.
Even if the filter combobox is "Installed", this is what happened:
- nuget asked me the credentials for the proxy (I did not change the password since the last time and my credentials were persistent, so this is unexplicable)
- fiddler shows 80 requests (with http status 407 and 200 after auth)
- finally the screen updates and shows me the installed packages.

Please, never ever access the network to manage local packages.

**Comment by batkuip** [comment]
Having the same issue.  It's firing 50+ requests to urls like https://api.nuget.org/v3/registration1/microsoft.aspnet.identity.entityframework/index.json 
each response is about ~100 Kb - so you end up downloading 5Mb every time you open the screen.

It also doesn't seem to cache the package icons - which means scrolling through the list is a very painful experience.

Actually it's even worse - when you uninstall a package - it refreshes the entire list - so again you have to wait

**Comment by yishaigalatzer** [comment]
Moving this to the next release, it doesn't look like we can make this change in time for locking down 3.2

**Comment by grokys** [comment]
+1: this is painful - it sends a request for each installed package, taking over 30 seconds for a project with many dependencies. I would assume they could be bundled into a single request in order to speed things up.

**Comment by yishaigalatzer** [comment]
@feiling please make sure that installed packages can show up right away and network calls required to just fill in extra data (like upgrade available). We can also push for a single API like @grokys suggests, we should probably set up a design discussion with @joyhui and @johnataylor for what an improved API for speeding up the UI looks like.

**Comment by raffaeler** [comment]
Can you confirm that in VS2015 there is still the chance for nuget not to ask the proxy user/pwd?
I cannot repro this but today VS2015 hanged while retrieving the list of icons of the installed packages.
After more than 5 minutes of waiting, I had to end task and restart vs...

**Comment by yishaigalatzer** [comment]
We are tracking the issue with image icons separately, but this is a great insight. I didn't think that was the case @zhili1208 I think we can get more traction now. Thanks @raffaeler !

**Comment by johnataylor** [comment]
we are going to use #2089 to track the perf issue from here
