### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Alexander248365** [NuGet/Home#11540]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 2019

### Impact

Other

### Repro Steps & Context

The Windows Forms project contained MSAL library files: 
using System.Windows;
using Microsoft.Identity.Client;
using Microsoft.Identity.Client.Desktop;

VS gave an error: Must Use PackageReference.

A post at https://stackoverflow.com/questions/58540212/how-to-solve-the-error-must-use-packagereference suggested to 

Migrate packages.config to PackageReference for References and Package.Config. My project did not have Package.Config, so only References were updated. Once it was done, many basic classes lost their links to assemblies.

Then I successfully restored the packages, as per your instructions, and everything got restored well.

Regards,
Alexander

**Comment by nkolev92** [comment]
Hey @Alexander248365 

Thanks for filling this. I'm not sure I can follow what the issue you're facing is exactly.


The error message `Must Use PackageReference` is *not* provided by NuGet itself, but rather the package, which NuGet cannot control. 

Can you provide a repro of your problem so we can determine if there's anything NuGet could/should be doing differently.

**Comment by LifeScienceMan** [comment]
Hi Nikolche, 

 

 

First of all, thank you for supporting NuGet!

 

You are correct: error Must Use PackageReference was reported by Visual Studio. 

 

The action suggested to resolve this issue was to Migrate two items to PackageReference. 

 

Once I did it, many objects in the project lost links, and I had to restore the project files from the created backup.

 

I thought NuGet does this migration and thus reported this issue to NuGet. Please ignore the issue if Vs is responsible for it.

 

I hope it clarifies.

 

 

Regards,

Alexander

 

 

Alexander Werner, Ph.D.,

Systems Architect

Relasoft Solutions Inc.

 <http://www.relasoft.net/> www.relasoft.net

P: (416) 783-1027

F: (416) 783-2147

**Comment by nkolev92** [comment]
Hey @Alexander248365, 

It's the package itself that raises the message, not the tooling. 
So somewhere in the package there's some logic that's raised. It's not the tooling that's forcing that. 

> The action suggested to resolve this issue was to Migrate two items to PackageReference.

Oh there was an action prompt? NuGet doesn't usually do that. 

If you'd like you can provide more detail and we can continue digging. 
If not, I can close this as external. 

Thanks.

**Comment by LifeScienceMan** [comment]
Hi Nikolche,

 

 

There was no prompt from NuGet, it was an external suggestion.

 

If Migration to new packages is done by VS and not by NuGet, the issue can be closed as external.

 

 

Regards,

Alexander

**Comment by nkolev92** [comment]
Closing per OPs comment.
