### ISSUE TITLE
The filter for installed packages does not work correctly

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#1154]
The following is a screenshot from a project in the solution which has only three packages installed. This is correct:
![image](https://cloud.githubusercontent.com/assets/5183152/9203346/eca1f440-4056-11e5-8fa9-cf4ba2b23ca0.png)

When instead I open the installed nuget packages for the solution, nuget client tells me that all the packages are installed in every project.
In other words the checkboxes are wrong.

![image](https://cloud.githubusercontent.com/assets/5183152/9203364/07c49052-4057-11e5-9d5e-edf39f1d8a6e.png)

It looks like the filter for the project does not work.

**Comment by yishaigalatzer** [comment]
@raffaeler I tried this just now and it shows the right thing, I think you are confused with what the checkboxes mean - It says **Select which projects to apply changes to** which means checked checkboxes means the install operation will add these packages.

We are tracking an improvement to the UI by changing the checkbox look, to make it clearer that is means install, but I think the behavior is as expected. Please re-open if you disagree

![image](https://cloud.githubusercontent.com/assets/1238711/9206680/13e0897e-401e-11e5-9c74-2b44a2005698.png)

**Comment by raffaeler** [comment]
The checkboxes currently are maked for all the projects: the ones that already have those packages and the ones that dont's. This strategy have multiple problems:
- If I have multiple projects in the solution, I don't see which one have the packages because the checkboxes are all checked
- In a solution with multiple projects, it rarely makes sense to add the packages to every project. For example you may have one webapi project and several class libraries. You do not want to add webapi to all.
- If I have to just add one package to one project, I have to deselect all the checkboxes... at this point if I uncheck the project which already had the package installed, will it be uninstalled?

IMHO it is confusing and useless. At least provide the same behavior as it had VS2013 client.

**Comment by yishaigalatzer** [comment]
That's not what it does. Projects are selected only if the packages are not installed. Existing projects are either filtered out of disabled (grayed out).

Take a second look.

Confusing - yes
Useless, i don't follow

**Comment by raffaeler** [comment]
Sorry for the late response...
I gave a second look. When I open the nuget packages for the solution the first package is selected and the checkbox with "33 project(s)" is checked and all the projects in the checked list view are checkes.
Then I click on another package and back to the previous one.
The checkbox on "33 project(s)" is now a black square. Now the list of the checked list view has all the project checked but one which is "unselected" (why?)
At this point I pick "uninstall" from the combo and then back "install". Now all the checkboxes are unselected.

Honestly I am afraid to use such a UI. I really worried to mess the entire solution ...

**Comment by yishaigalatzer** [comment]
Let me try and summarize your findings and you concern.

You end up in a case where selection is changing when you flip between two packages in the installed list. That looks like a bug.

When you select uninstall and return to install, we unselected all the packages (good), but we never select them again (sounds OK-ish), because I'm not sure you want us to change the selection again.

We should re-consider how to deal with selection (how much to remember across selection changes), and fix the bug you found (can you repro it regularly, and sure its not a misclick of somekind? I assume so, just want to be diligent, I couldn't repro it).

But I don't think there are major concerns with applying the action.

If you want to be 100% sure, checkin before you make such a massive change to the project, it is probably a good idea anyways.

If you can point me at a good repro for the selection, we can definitely get it fixed pretty much immediately.

**Comment by raffaeler** [comment]
I will try to repro in a solution ad-hoc and let you know

**Comment by deepakaravindr** [comment]
Thanks, @raffaeler! Filed https://github.com/NuGet/Home/issues/1308 to track the issue with the black square
