### ISSUE TITLE
NuGet.exe on MAC show more than 1 result for latest version when using local feeds

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11576]
I used `nuget.exe` version 6.0.0 with mono.
![image](https://user-images.githubusercontent.com/8766776/153082135-252ba0d2-b514-4bb6-a104-821f7da27ecd.png)

`newBestPackageA` show 2 versions for MAC, but it doesn't happen for MAC only 1 package version per packageId.
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/5bd766e9-30fc-4c5b-8d74-80aba3ad2489)

Here is on Windows, issue doesn't exist: 
![image](https://user-images.githubusercontent.com/8766776/153077268-7b51fbc6-9080-41db-86e8-05f5e17b1091.png)

If this fixed then need to unskip 1 MAC test here: https://github.com/NuGet/NuGet.Client/pull/4447

Related issue: https://github.com/nuget/home/issues/11579

**Comment by erdembayar** [comment]
@heng-liu 
Is it known bug?

**Comment by zivkan** [comment]
Triage: Validate if it might affect restore. If not, we can lower the priority.

**Comment by zivkan** [comment]
Root cause is this method: https://github.com/NuGet/NuGet.Client/blob/f5d7dc371d8a54a9fe0869698e5c4f29dcb7d981/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalPackageSearchResource.cs#L168-L172

The assumption "that similar items occur in order" is not true on Linux or Mac. Only Windows returns files in alphabetical order, so this method is basically broken by design.

While debugging up to this point feels like 90% of the work, to "fix" this requires more memory to sort ourselves. I'm worried if there are any customers with a huge numbers of packages in a folder, which would make this slow.

But the good news is that since this is in the "local search resource", which Restore doesn't use, there's no risk of this causing a wrong version to be used in restore, even if floating versions are used. For this reason, I'm removing the Priority 1 label, and perhaps we can discuss this briefly at triage. I'm guessing it's always been like this, and I don't remember any customer complaints (@erdembayar did you search for duplicates before creating this issue?)

**Comment by erdembayar** [comment]
> I'm guessing it's always been like this, and I don't remember any customer complaints (@erdembayar did you search for duplicates before creating this issue?)

I searched for dup, couldn't find one. No one complained about it, because not many customers use MAC for .netframework development, especially with local feed. Even `Priority 3 label` could be applicable considering mono is in maintenance mode.

**Comment by zivkan** [comment]
Team triage meeting: Customers haven't reported this issue, so closing this.
