### ISSUE TITLE
[DCR]: Provide context as part of the prompt that asks users to enter their credentials

### ISSUE THREAD

**Issue by rub8n** [NuGet/Home#11581]
### NuGet Product(s) Affected

Visual Studio Package Management UI

### Current Behavior

NuGet related auth prompts inside Visual Studio do not identify themselves as such and leave users wondering why Visual Studio is "randomly" asking for their credentials.

### Desired Behavior

Calls to show NuGet related auth prompts should identify themselves as coming from NuGet and surface that information to users in a discoverable manner.

**Comment by kartheekp-ms** [comment]
- [ ] ~https://github.com/NuGet/Home/issues/11859~
- [ ] ~https://github.com/NuGet/Home/issues/11860~

**Comment by kartheekp-ms** [comment]
@rub8n - In the latest version of VS 2022, we added `NuGet (AzDO feed name) needs your credentials. ` text to the authentication prompt with the help of other partner teams.
![image](https://user-images.githubusercontent.com/52756182/188788546-0332ec8c-2591-4467-be8f-23990e0997bf.png)
I propose to close this issue because the new functionality addresses the desired behavior mentioned in the issue description `Calls to show NuGet related auth prompts should identify themselves as coming from NuGet and surface that information to users in a discoverable manner`. What do you think?

**Comment by rub8n** [comment]
Yes, this is a big improvement! Thanks to everyone involved!
