### ISSUE TITLE
[Bug]: msbuild 17 restores package version 14.2.3.0 when version 14.2.3 is requested, worked with msbuild 16

### ISSUE THREAD

**Issue by martinsuchan** [NuGet/Home#11593]
### NuGet Product Used

MSBuild.exe

### Product Version

msbuild 17.0.0.52104

### Worked before?

msbuild 16.11

### Impact

I'm unable to use this version

### Repro Steps & Context

I have a .NET 4.6.1 WPF project with packages.config referencing one old nuget DevExpress.Xpf.PivotGrid 14.2.3.

When I used 'nuget restore sln' with VS2019/msbuild 16 installed, the package version 14.2.3 got restored into 
**packages/DevExpress.Xpf.PivotGrid.14.2.3**

but after installing VS2022/msbuild 17, it downloads package version 14.2.3.0 instead and restores it into folder
**packages/DevExpress.Xpf.PivotGrid.14.2.3.0**

This effectively breaks our solution, it cannot be built with VS2022, because files are now located in different path and because package version 14.2.3.0 has a bit different dlls,

I guess this can be solved by switching to PackageReference or SDK style project, but it should be fixed in my opinion to match the behavior of VS2019/msbuild 16.

**Comment by martinsuchan** [comment]
Updated the description after some investigation:
We use 2 private nuget repositories. One has package **DevExpress.Xpf.PivotGrid 14.2.3** and the second one has **DevExpress.Xpf.PivotGrid 14.2.3.0**
packages.config has DevExpress.Xpf.PivotGrid 14.2.3 in it.

With msbuild 16 the correct nuget package **DevExpress.Xpf.PivotGrid 14.2.3** was resolved and downloaded, but with msbuild 17 it looks like it downloads **DevExpress.Xpf.PivotGrid 14.2.3.0** instead, thinking it's the same version and because the the server with version 14.2.3.0 has faster response time?

Updated expected behavior:
- if app requires package version 14.2.3 and both 14.2.3 and 14.2.3.0 is available, then only 14.2.3 must be downloaded and used.
- show warning when package with different version number is downloaded

**Comment by martinsuchan** [comment]
Update: I discovered in nuget specification that 14.2.3.0 and 14.2.3 versions are considered identical after normalization.
And it looks like this problem happened when one of our nuget servers was temporarily down and the wrong package was downloaded into the nuget cache.

**Comment by kartheekp-ms** [comment]
@martinsuchan - What happens when a nuget server that has `14.2.3` package is down when restore is executed in `VS 2019/msbuild 16` tooling is used. I guess the behavior should be the same as VS 2022/msbuild 17 tooling but could be wrong.

As per my understanding this is by design because as per [doc](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#where-nugetversion-diverges-from-semantic-versioning), `NuGetVersion supports a 4th version segment, Revision, to be compatible with, or a superset of`, [System.Version](https://docs.microsoft.com/en-us/dotnet/api/system.version). `Therefore, excluding prerelease and metadata labels, a version string is Major.Minor.Patch.Revision. As per version normalization described above, if Revision is zero, it is omitted from the normalized version string. `

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
