### ISSUE TITLE
[Bug]: error: File does not exist (true) while executing dotnet nuget push command

### ISSUE THREAD

**Issue by renemadsen** [NuGet/Home#11601]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet Version: 6.0.200

### Worked before?

dotnet version: 6.0.102

### Impact

Breaks github build scripts, since it's erroring out, even thought there is no problem.

### Repro Steps & Context

Publish a package to nuget.org with the commad like:

`dotnet nuget push /home/runner/work/eform-sdk-dotnet/eform-sdk-dotnet/artifacts/Microting.eForm.5.4.30.nupkg -k ${{secrets.NUGET_SECRET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true`

Working edition can be see here: https://github.com/microting/eform-sdk-dotnet/runs/5204099665?check_suite_focus=true#step:8:1

Broken can be seen here: https://github.com/microting/eform-sdk-dotnet/runs/5219100462?check_suite_focus=true#step:8:1

Doing the above, results in an error: "error: File does not exist (true)." even thought the package was pushed and published as expected.

**Comment by Piedone** [comment]
Noticed with [Orchard Core](https://github.com/OrchardCMS/OrchardCore/issues/11196) too. It's definitely a 6.0.102 -> 6.0.200 bug.

You don't need to try to push to a remote feed, local publishing has the same error: `dotnet nuget push 'src/**/*.nupkg' -n true -s C:\local-path --skip-duplicate`

This is only coming up when `-n true` is specified. Workaround: just specify `-n`.

**Comment by kartheekp-ms** [comment]
In https://github.com/NuGet/NuGet.Client/pull/4326 PR, we removed accepting values for `--no-symbols` and  `--disable-buffering` options in `dotnet nuget push` command because they the values were not useful. I think it will be good to check why the command is throwing `error: File does not exist (true).` after the package has been pushed.

**Comment by erdembayar** [comment]
@renemadsen 
Thank you for your feedback.
There was implementation bug with `-n`. If you check [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push#:~:text=dotnet%20nuget%20push%201%20Name%202%20Synopsis%203,to%20reduce%20memory%20usage.%20...%206%20Examples.%20) options like `-n` doesn't need any parameter. So previous behavior of `-n` asking for any parameter such as  `true` is bug, we recently [rectified it](https://github.com/NuGet/NuGet.Client/pull/4326) to make our doc and implementation match. 
So please just use `-n|--no-symbols` and `-d|--disable-buffering` without any parameter because that parameter not used in our logic.

**Comment by erdembayar** [comment]
We called out in [Release note Known Issues](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.1#known-issues)
