### ISSUE TITLE
[Bug]: Null Reference exception when loading/refresh any Tab of the PM UI

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#11644]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Version 17.2.0 Preview 2.0 [32222.421.main]

### Worked before?

17.2.0 Preview 2.0

### Impact

I'm unable to use this version

### Repro Steps & Context

Using a new solution, I incidentally stumbled upon a null reference exception in PM UI. I've identified the location in the code already below.

Filed VS Feedback: https://developercommunity.visualstudio.com/t/object-reference-null-when-opening-package-manager/1683498

I'm assuming for now that it's a regression, as this code was changed recently in https://github.com/NuGet/NuGet.Client/pull/4119
![image](https://user-images.githubusercontent.com/49205731/156683251-76eaba45-dfad-4108-a857-4a7d8748c339.png)

![image](https://user-images.githubusercontent.com/49205731/156683122-cfa83abd-ab41-4361-b9b9-7012fbccb004.png)

**Comment by erdembayar** [comment]
Donnie hit this by random chance, it's hard to repro manually, and offline discuss points it existed since VS16.9. 
Good thing is we have very nice long stack call tree.
@donnie-msft Can I remove `RegressionDuringThisVersion` label since it looks existing issue before https://github.com/NuGet/NuGet.Client/pull/4119?
