### ISSUE TITLE
[Bug]: .NET Restore on MacOS prefixes filenames with foldernames instead of placing in subfolders

### ISSUE THREAD

**Issue by dotMorten** [NuGet/Home#11667]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.200

### Worked before?

Not sure

### Impact

I'm unable to use this version

### Repro Steps & Context

From commandline on MacOS run:

```
mkdir test
cd test
dotnet new console
dotnet add ./ package MSTextX.UnitTestRunner --version 2.0.0-preview1
```
Open up the nuget cache folder `~/.nuget/packages/mstestx.unittestrunner/2.0.0-preview1`
Notice that instead of files being in a folder structure, they are all in the same folder with their folder names prefixing the filenames and backslashes in the name:

![image](https://user-images.githubusercontent.com/1378165/157795207-629bed61-3abe-4390-af4e-83630e107f35.png)

Repeat the same with v1.4.0 of the same nuget package, and you'll see a more meaningful folder layout:
![image](https://user-images.githubusercontent.com/1378165/157795255-5ff16b35-bd1d-4d72-bdd9-01f74f554429.png)

Repeat the same thing on Windows, and there is no issue and the nupkg gets unzipped correctly. I didn't find anything obviously different about the two packages, but obviously something in the newer package is tripping up the unzipper.

**Comment by JonDouglas** [comment]
I took a quick look and saw some diffs in the two packages you mention. Can you confirm that the 2.0.0-preview1 package does not include anything extra such as `_rels` here as a top-level folder?

![image](https://user-images.githubusercontent.com/1288848/157899684-9ad1f14f-f0c1-496a-b0f4-2f97320d3a04.png)

https://nuget.info/packages/MSTestX.UnitTestRunner/2.0.0-preview1

I took a quick glance at some data and didn't see any usage of this top level folder in any packages. Might be a red herring, but that's a two minute look before we can officially triage. Thanks.

If would be especially helpful to know what you may have changed package-wise from these versions with a diff tool. That would help us investigate further in addition.

**Comment by dotMorten** [comment]
I honestly have no idea what the _rels folder is or why it got there.  One difference could be that I think I sign packages differently now which includes unpacking and repacking the nuget to sign the assemblies inside as well. I can’t remember if I did it that way with 1.4.0 (although fairly certain I did)

**Comment by JonDouglas** [comment]
@dotMorten Sounds good, can you confirm for us if removal of that folder resolves the original behavior? That way we might be able to add a rule to check for it and warn/error the user in pack or push.

**Comment by dotMorten** [comment]
Sure. I’m out for the week though and didn’t bring my Mac so will have to be next week

**Comment by zivkan** [comment]
I'm not 100% sure, but I'm quite confident the issue is that the nupkg is being created with `\` path separators instead of `/` separators (possibly the other way around, I can't remember, but I think that's unlikely otherwise the bug wouldn't happen in this way).

The zip file format is very basic, and doesn't contain the concept of a folder. It even allows duplicate entries with the same filename. Every entry is just a string path, and it's up to programs that read/write zip files to implement their own conventions, with nothing more than hope (not even recommendations) that they implement the same conventions. NuGet will normalize paths on pack (my memory is to use `/`). This bug report makes it look like we don't normalize path separators on extraction.

As Jon pointed out, the lack of `_rels` makes it clear that this nupkg was not created by nuget, but some other program had zipped it. The `_rels` folder (plus at least one other file in the package) is from the [Open Packaging Conventions](https://en.wikipedia.org/wiki/Open_Packaging_Conventions#Package,_parts,_and_relationships), which early versions of NuGet supported, but I think we're no longer compliant with.

**Comment by jeffkl** [comment]
Version 2.0.0-preview1 of the package MSTextX.UnitTestRunner doesn't appear to be available anymore, perhaps it had an issue?  Have you tried different version of the package?

**Comment by dotMorten** [comment]
@jeffkl ? It is still there: https://www.nuget.org/packages/MSTestX.UnitTestRunner/2.0.0-preview1

**Comment by jeffkl** [comment]
Sorry I clicked on a link https://github.com/dotMorten/MSTestX which had taken me to MSTest.TestFramework which is a different package.

I did notice that version 1.4.0 of MSTestX.UnitTestRunner seems have a better package layout
https://www.nuget.org/packages/MSTestX.UnitTestRunner/1.4.0

Do you know how version 2.0.0-preview1 of the package was created?  Are you able to confirm if version 1.4.0 of the package does not exhibit the behavior you described?

**Comment by dotMorten** [comment]
1.4.0 doesn’t exhibit the behavior. There really shouldn’t be much of a difference between the two except this one now includes net6 preview stuff and newer tooling. It could be the signing workflow changed since (which does unpack sign assemblies and repack nuget using power shell, but fairly certain that happened with 1.4.0 too).
Regardless the zip looks fine and unzips fine on Windows

**Comment by jeffkl** [comment]
Very interesting, are you able to recreate the package with steps I can follow to get a package that has the wrong path separators?  I want to investigate further but need to understand how the package ended up in this state.  I think once the package is created like that, NuGet doesn't know it needs to do anything different.  But if we can figure out how it ended up with the wrong directory separators then I can see why.

**Comment by dotMorten** [comment]
Sure. Clone this branch:
https://github.com/dotMorten/MSTestX/tree/maui
Then right-click pack the `TestAppRunner` project in a release build.
Next run through the signing script. Here's the batch script used (You can likely skip the actual signing if you don't have a sign certificate - I'm guessing it's the re-packing that could potentially be the culprit, but if not place signtool.exe and nuget.exe in a `.\tools\` subfolder)
```
for /f "delims=" %%i in ('dir *.nupkg /b/s') do (
        mkdir %TEMP%\nuget_sign_unpack
	tar -xf %%i --directory %TEMP%\nuget_sign_unpack
	for /f "delims=" %%j in ('dir %TEMP%\nuget_sign_unpack\*.dll /b /s') do (
	   "tools\signtool.exe" sign /fd SHA256 /s My /n "MY_SIGNING_CERT_NAME" /tr http://timestamp.digicert.com /td SHA256 %%j
	)
	powershell Compress-Archive %TEMP%\nuget_sign_unpack\* %%i.zip
	move /Y %%i.zip %%i
	rmdir %TEMP%\nuget_sign_unpack /S /Q
	"tools\nuget.exe" sign %%i -CertificateStoreName "My" -CertificateSubjectName "MY_SIGNING_CERT_NAME" -Timestamper http://timestamp.digicert.com
)
```

**Comment by dotMorten** [comment]
Just realized I still have the package before signing and after signing (but prior to uploading to nuget.org):
 - [BeforeSigning.zip](https://github.com/NuGet/Home/files/8290410/BeforeSigning.zip)
 - [AfterSigning.zip](https://github.com/NuGet/Home/files/8290422/AfterSigning.zip)

The `_rels` folder is present in both.

**Comment by jeffkl** [comment]
@dotMorten yes that signing logic is most likely the problem.  You're extracting the `.nupkg`, signing files, and then compressing the files again.  NuGet pack normalizes the path separators, so it works cross-platform but I'm not sure if PowerShell's `Compress-Archive` does that.

Most signing operations will look in existing archives and sign assemblies in place without having to do this operation.  I'm not very familiar with `signtool.exe` so I'm not sure if it will do that.  But if not, you'll need to sign these files _before_ the pack operation happens so that the package is in the expected format.  Let me know if you can't get that to work and I can look into it further.

**Comment by dotMorten** [comment]
@jeffkl Yes I could sign as part of the build, but that goes against several recommendations. `nuget sign` doesn't sign stuff inside the package, and `signtool` doesn't sign nuget packages.
I'll try and use a better zip tool instead.
Thanks

**Comment by jeffkl** [comment]
@nkolev92 do you have better recommendations here?

**Comment by nkolev92** [comment]
Nothing major. 
In most of the builds in NuGet and dotnet, the process is restore -> build -> sign -> pack.

**Comment by jeffkl** [comment]
I'm going to close this issue as by design.  It is not supported to manually unzip a `.nupkg`, modify the contents, and then simply zip it again manually.  This leads to the file potentially not being in the correct layout and not guaranteed to work on other platforms.

**Comment by dotMorten** [comment]
Thanks Jeff. I concur this actually appears to be a powershell compress issue if anything. Sorry for not realizing that sooner. I couldn’t find where to log this instead. It doesn’t look like the powershell repo actually contains the compression stuff.
