### ISSUE TITLE
[Bug]: Generated path property not set for custom targets

### ISSUE THREAD

**Issue by ermshiperete** [NuGet/Home#11725]
### NuGet Product Used

MSBuild.exe

### Product Version

16.11.2.50704

### Worked before?

not sure

### Impact

It's more difficult to complete my work

### Repro Steps & Context

When building the following project with `msbuild /t:ReportVariables l10n.proj` the property `PkgNuGet_CommandLine` isn't set.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks/>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.CommandLine" Version="6.1.0" GeneratePathProperty="true" />
  </ItemGroup>
  <Target Name="ReportVariables" DependsOnTargets="restore">
    <Message Text="PkgNuGet_CommandLine=$(PkgNuGet_CommandLine)" />
  </Target>
</Project>
```

#### Expected result:
because of specifying `GeneratePathProperty="true"` in `PackageReference` I expect `PkgNuGet_CommandLine` to be set to a path.

#### Actual result:
`PkgNuGet_CommandLine` is empty

### Verbose Logs

[output.txt](https://github.com/NuGet/Home/files/8445481/output.txt)

**Comment by nkolev92** [comment]
Those properties are set by restore, so they won't be available in the restore evaluation which is what can happen if restore wasn't run. 

Restore can't be affected by what it generates, otherwise you risk an infinite loop (restore -> generate assets that invalidate restore -> generate assets that invalidate restore etc.)

The thing missing in your scenario is that the target you have runs in the *outer* build, meaning with TargetFramework not set. 
Given that you have multiple frameworks, each one has it's own copy of PkgNuGet_Commandline. 

If you run ` msbuild /t:ReportVariables /p:TargetFramework="net461"` it works. 

Here's some inner/outer build examples I've written for some demos: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
    <SpecialProperty>DefaultValue</SpecialProperty>
  </PropertyGroup>

  <Target Name="SpecialTarget">
    <Message Text="Running SpecialTarget." Importance="High" />
    <Message Text="TargetFrameworks: $(TargetFrameworks)" Importance="High" />
    <Message Text="TargetFramework: $(TargetFramework)" Importance="High" />
    <Message Text="SpecialProperty: $(TargetFramework)" Importance="High" />
  </Target>

  <PropertyGroup>
    <SpecialProperty Condition="'$(TargetFramework)' == 'net5.0' ">net5.0 build</SpecialProperty>
    <SpecialProperty Condition="'$(TargetFramework)' == 'net6.0' ">net6.0 build</SpecialProperty>
  </PropertyGroup>

  <Target Name="GetTargetFrameworksAsItems"
    Returns="@(TargetFrameworksAsItems)">
    <ItemGroup Condition=" '$(TargetFrameworks)' != '' ">
      <TargetFrameworksAsItems Include="$(TargetFrameworks.Split(';'))" />
    </ItemGroup>
  </Target>

  <Target Name="SpecialDelegatingTarget" DependsOnTargets="GetTargetFrameworksAsItems">
    <MSBuild
      Projects="$(MSBuildProjectFullPath)"
      Targets="SpecialTarget"
      Properties="TargetFramework=%(TargetFrameworksAsItems.Identity);">
    </MSBuild>
  </Target>

</Project>
```
