### ISSUE TITLE
Remove net45 and net40 targets from the NuGet build

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#11830]
These are outdated and out of support frameworks.
 
Currently VS 2022 doesn't even give you the option to install the framework components for .NET Framework 4.0 - 4.5.1, which means that you have to jump through hoops to get those targeting packs installed. 

See : https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

> Starting with Visual Studio 2022, Visual Studio no longer includes .NET Framework components for .NET Framework 4.0 - 4.5.1 because these versions are no longer supported. Visual Studio 2022 and later versions can't build apps that target .NET Framework 4.0 through .NET Framework 4.5.1. To continue building these apps, you can use Visual Studio 2019 or an earlier version.

I understand that there are other reasons for targetting net45 in particular, `NuGet.Packaging.Extraction`, but I think that can be addressed by using older versions of the package that have already been published. 

In particular both @drewgillies and @lukka both ran into issues over the last 2 weeks trying to build the product.

* Note that removing these extra frameworks removes 5 different builds, so it'd speed up the build quite a bit.

**Comment by nkolev92** [comment]
Related https://github.com/NuGet/Home/issues/8416. 

cc @zivkan

**Comment by zivkan** [comment]
> I think that can be addressed by using older versions of the package that have already been published.

The problem is if we make bug fixes, or other relevant features. For example, if we ever change the `.nupkg.metadata` file to add additional information that is **required** for fallback folders to work, then we'd need to backport the feature to the branch that still supports NuGet.Packaging.Extraction. Of course, if that never happens, then we don't need to support the package. But we can't know until we need to.

I think that installing VS2019 just to get .NET Framework 4.5 and 4.0 installed (or use Chocolatey, or WinGet) isn't unreasonable, and reduces the risk of NuGet.Packaging.Extraction getting difficult to maintain. Maybe we need to add this information to the readme.md, so it's easier to discover this issue and a way to resolve it. Having said that, VS Setup is the only customer I'm aware of that needs the package, so if they're ever able to upgrade to .NET 6 or higher, then we can drop this project, and therefore unsupported versions of netfx. Until then, I'm very skeptical about removing those TFMs and saying that NuGet.Packaging.Extraction is only supported in old versions that are hard to service.

**Comment by drewgillies** [comment]
@zivkan @nkolev92 If net40 and net45 do need to be there, installing from VS 2019 isn't too bad if you avoid all workloads and just select the two targeting packs. It's done in a few minutes.

**Comment by nkolev92** [comment]
> The problem is if we make bug fixes, or other relevant features. For example, if we ever change the .nupkg.metadata file to add additional information that is required for fallback folders to work, then we'd need to backport the feature to the branch that still supports NuGet.Packaging.Extraction. Of course, if that never happens, then we don't need to support the package. But we can't know until we need to.

I'm not sure I agree with the sentiment that it is difficult to service all versions.

If the last version on which we leave NuGet is an LTS version one through either VS or .NET SDK, then we will be maintaining the build on that branch. 

How often would we try to service NuGet.Packaging.Extraction?
How often has .nupkg.metadata changed? Is the change a breaking change or is it a nice to have? 

> For example, if we ever change the .nupkg.metadata file to add additional information that is required for fallback folders to work

Fallback folders have existed for 5 years and there's only been 1 required change and that was more than 2.5 years ago. 

If we play the odds, I think we're more likely to arrive at a point where there's no net45 requirement instead of having to port another fix to nuget.packaging.extraction. 

Note that given how nuget.packaging.extraction is serviced, the bar is lower than the standard VS servicings.

**Comment by jeffkl** [comment]
I can fix the build errors by referencing [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies) so you no longer need VS 2019 workloads installed to build.

https://github.com/NuGet/NuGet.Client/compare/dev-jeffkl-reference-microsoft-netframework-referenceassemblies?expand=1

Can I send a PR?

**Comment by nkolev92** [comment]
PR would be great. I'd still love to remove these targets altogether from our latest builds.

**Comment by zivkan** [comment]
> I can fix the build errors by referencing [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies)

This doesn't work in VS, so it's still necessary to install VS2019 just for the two netfx targeting packs, if you want to build NuGet.sln in VS2022.

And on the CLI, the .NET SDK (usually) automatically adds the reference assemblies. Again, this doesn't work in VS. If you use Project System Tools to get a binlog from within VS, you can see in the design time build that the SDK adds the reference assemblies as a package reference, but then also runs targets that fails the build because the reference assemblies are missing, preventing the project from working. I reported this months ago, but they consider it a scenario that was never supported (you've always needed the targeting pack installed in VS). https://developercommunity.visualstudio.com/t/NET-Project-System-not-using-implicit-R/1572167

**Comment by jeffkl** [comment]
@zivkan That's funny that the error fails the design time build so Project System doesn't even restore the project to get the reference assemblies.  How about I add conditions to just not build `net40` and `net45` in Visual Studio?  It will still build everything from the command-line but make our build work in VS.

**Comment by jeffkl** [comment]
This is what it would look like: https://github.com/NuGet/NuGet.Client/compare/dev-jeffkl-reference-microsoft-netframework-referenceassemblies?expand=1

**Comment by zivkan** [comment]
Works for me. Did you test on a VM that does not have the .NET Framework targeting packs installed, to verify that it actually works for potential contributors who try?

**Comment by jeffkl** [comment]
> Did you test on a VM that does not have the .NET Framework targeting packs installed

Yes, I've been hitting this error since I joined the team because I don't have VS 2019 installed.  I never understood what was going on so I've been ignoring the error.  The changes fixed the errors for me!

**Comment by nkolev92** [comment]
I don't think we should do the building in visual studio change.
It will invalidate no-op restore and cause a full restore.

We shouldn't have different behavior in VS and commandline builds.

**Comment by zivkan** [comment]
team triage meeting: @aortiz-msft agrees with @nkolev92.  We'll remove net45 and net40, and if we need to service NuGet.Packaging.Extraction, we'll do it from whatever `release-*` branch had the last published package.
