### ISSUE TITLE
[Bug]: Sdk Nugets cannot use Path properties of referenced packages

### ISSUE THREAD

**Issue by dagasparmsft** [NuGet/Home#11872]
### NuGet Product Used

MSBuild.exe

### Product Version

msbuild 16.11.2.50704

### Worked before?

Never

### Repro Steps & Context

Hello,

I am attempting to create a new nuget SDK that takes dependencies on the content of other nugets. However, the path property for the package is never resolved even though I see that the project *.nuget.g.props is generated with the path properties. Am I calling my target too soon after restore or is this a bug?

```xml
<PackageReference Include="ZuluJDK.OSS" Version="1.8.203" GeneratePathProperty="true" />
...
  <Target Name="InsideSDK" AfterTargets="Restore">
     <Message Text="JDK home is $(PkgZuluJDK_OSS)" />
  </Target>
```

**Comment by dfederm** [comment]
This is not a bug but a matter of ordering.

`AfterTargets="Restore"`, so this runs after the restore target, but still "part of the restore execution".

When restoring, at the very beginning the generated g.props files do not exist yet. The projects are evaluated and the Restore target runs, which generates the g.props files. Then your target hooks to the restore target and runs, but remember at the time of MSBuild evaluation, the g.props files did not exist yet, so no `Pkg*` properties will be defined.

**Comment by zivkan** [comment]
As the above comment says, on a clean machine, when restore starts, your package is not on disk, so your package's targets can't be included. [MSBuild's docs on How MSBuild builds projects](https://docs.microsoft.com/visualstudio/msbuild/build-process-overview?view=vs-2022) explains that imports are evaluated before targets are executed. Therefore, after NuGet's restore task finishes, the package's props and targets files are not imported in order to execute the `AfterTargets="restore"` target.

When the project/package has already been restored, you might notice that the `project.nuget.g.props` file (and targets file) include conditions ` '$(ExcludeRestorePackageImports)' != 'true' ` on every item group, property group, and import group. During command line restores, NuGet sets this property to true, in order to prevent packages from changing the restore graph and therefore preventing a second restore from having the same outcome as the first restore.

The MSBuild `restore` target should be the only one setting `ExcludeRestorePackageImports`, so your own targets file can use any other target name for `AfterTargets` or `BeforeTargets`, just not `restore`.
