### ISSUE TITLE
dotnet build does not find the latest package according to a matching pattern

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#11898]
---
**Issue moved from dotnet/msbuild#7718**
- Please respond to @MikeSchulze.

---

_From @MikeSchulze on Sunday, June 19, 2022 5:20:40 PM_

### Issue Description
At first mybe i'm wrong but from official documentation it looks like a bug and is not working as described.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

I want to use beta packages in my project included by a pattern to get the latest package
The package is build by this config
`    <PackageVersion>2.3.0-beta.$([System.DateTime]::Now.ToString('yyyyMMddHHmm'))</PackageVersion>`

and referenced in my project file as 
```
	<ItemGroup>
		<PackageReference Include="gdUnit3CSharpModule" Version="2.3.0-beta.*"/>
	</ItemGroup>`
```
The build output says
```
 Primärverweis "gdUnit3CSharpModule, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
             Der aufgelöste Dateipfad ist "C:\Users\xxx\.nuget\packages\gdunit3csharpmodule\2.3.0\lib\netstandard2.1\gdUnit3CSharpModule.dll".
             Ein Verweis wurde im Suchpfad "{HintPathFromItem}" gefunden.
             Dieser Verweis ist nicht CopyLocal, da Private für mindestens ein Quellelement auf "false" und für kein Quellelement auf "true" festgelegt war.
```
and when i checked the local packages at `C:\Users\xxx\.nuget\packages\` it contains the latest beta version
```
19.06.2022  18:59    <DIR>          .
19.06.2022  18:59    <DIR>          ..
05.06.2022  16:26    <DIR>          2.3.0
18.06.2022  14:02    <DIR>          2.3.0-beta.202206181130
19.06.2022  10:14    <DIR>          2.3.0-beta.202206191008
```

But the build uses the `2.3.0` instead of `2.3.0-beta.202206191008`

### Steps to Reproduce
See description below

### Expected Behavior
I ecpect from documentation https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#floating-versions the latest beta version is used to build.

### Actual Behavior
It loads the main version instead of the addressed beta version.

### Versions & Configurations
Using:
dotnet --version
6.0.101

dotnet nuget --version
NuGet Command Line
6.0.0.280

using Visual Studio Code: 1.68.1

My project file:
```
<Project Sdk="Godot.NET.Sdk/3.3.0">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.1</TargetFrameworks>
		<LangVersion>10.0</LangVersion>
		<!--Force nullable warnings, you can disable if you want-->
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<!--Disable warning of invalid/incompatible GodotSharp version-->
		<NoWarn>NU1701</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<!--Required for GdUnit3-->
		<PackageReference Include="gdUnit3CSharpModule" Version="2.3.0-beta.*"/>
	</ItemGroup>
</Project>
```
The published nuget packages 
https://www.nuget.org/packages/gdUnit3CSharpModule/

**Comment by rainersigwald** [comment]
---
**Issue moved from dotnet/msbuild#7718**
- Please respond to @rainersigwald.

---

_From @rainersigwald on Monday, June 20, 2022 2:42:06 PM_

I'm going to move this to NuGet for the final word, but I think this is intentional behavior. By the `semver` spec, `2.3.0` is a higher compatible version of `2.3.0-beta`, so it might be considered a better match. The `2.3.0` version is available on NuGet.org, but unlisted (https://www.nuget.org/packages/gdUnit3CSharpModule/2.3.0), which is why it's not visible on the "versions" tab of the package page.

**Comment by MikeSchulze** [comment]
@rainersigwald the problem has no assignment, any update here?

**Comment by kartheekp-ms** [comment]
As per [doc](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning), `the version without any suffix will always take precedence over pre-release versions`.

For example, consider following version for a package. The version 1.0.1 takes precedence over pre-release versions. I think that explains why you are experiencing this issue and it appears to be by design.

```
1.0.1
1.0.1-zzz
1.0.1-rc
1.0.1-open
1.0.1-beta.12
1.0.1-beta.5
1.0.1-beta
1.0.1-alpha.2
1.0.1-alpha
```

If the latest stable version is already out then how about incrementing the package version to something like `6.3.1-beta*` so that NuGet always resolves prelease versions until `6.3.1` version is published?

**Comment by MikeSchulze** [comment]
Hi @kartheekp-ms thanks for the anwser, i now the version sorting.
But i used a pattern to macht only the beta versions
`<PackageReference Include="gdUnit3CSharpModule" Version="2.3.0-beta.*"/>`
but still got the `2.3.0` version instead

**Comment by kartheekp-ms** [comment]
This appears to be by design for me. As per https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions#how-do-floating-versions-work,

- Floating versions are not regex, despite the usage of * in the floating version grammar. Likewise, calling them wild card versions can be misleading as well. Floating version ranges have a semantic meaning that's applied when determining a match that's different from what a regex does.
- Given a version 5.0.0-preview.1, the 5.0.0 will be referred to as the stable part and preview.1 will be referred to as the prerelease part. The first - in a version/version range is the separator between the stable and prerelease parts.
- When specifying a floating version, stable versions are always allowed. See [example](https://nugettoolsdev.azurewebsites.net/5.5.0-floating.7611/find-best-version-match?versionRange=1.1.0-*&versions=1.1.0-beta%0D%0A1.1.0). For 1.1.0-* with 1.1.0-beta and 1.1.0 available, the selected version is 1.1.0.

Find best version match tool https://nugettools.azurewebsites.net/6.0.0/find-best-version-match?versionRange=1.1.0-beta*&versions=1.1.0-beta-1%0D%0A1.1.0%0D%0A can also be used to verify which version is resolved by NuGet.

https://api.nuget.org/v3-flatcontainer/gdunit3csharpmodule/index.json returns version 2.3.0 also. The issue you are experiencing was reported earlier and closed as by design https://github.com/NuGet/Home/issues/10931

In https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package, it is mentioned that unlisted packages may still be discovered in the following specific scenarios:

- Package restore using floating versions (for example, 1.0.0-*), if the latest available package matching the version or dependency constraints is an unlisted package.

**Comment by MikeSchulze** [comment]
First of all thank you for your detailed answer, this is very confusing.
I see here that many developers can't cope with this kind of resolution, and the logic behind it is a mystery to me.
Why you strictly forbid deleting packages, I also find very restrictive. Especially if you just want to test something and the packages are not yet in use, I would like to have the possibility to delete them pernament again.

The current case shows that listing out packages only leads to more confusion, as an explicitly "deleted" package is resolved by recovery

It leads to frustration and just saying that this is the way we went and documented is not really helpful.

To workaround i see only the way to increase the version.

Thanks for your time

**Comment by zivkan** [comment]
We should document this better, tracking issue: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1862
