### ISSUE TITLE
packages.lock.json conflict for two .csproj in same folder

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#11908]
If I have two .csproj files in the same directory, that include different subsets of *.cs files, and I enable `RestorePackagesWithLockFile`, the resulting packages.lock.json files will conflict, overwriting each other.

There needs to be an easy way to rename one of the conflicting packages.lock.json files by setting an MSBuild property.

**Comment by zivkan** [comment]
Hi @KirillOsenkov 

firstly, in the future, please use our issue templates. Since you believe this isn't a capability NuGet already has, I think the feature request template would be appropriate.

Secondly, our [lock file extensibility docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#lock-file-extensibility) list `NuGetLockFilePath` as an MSBuild property where you can set the lock file name. Additionally, it also says that:

> NuGet supports project specific lock file `packages.<project_name>.lock.json`

so if you create an empty file with that name, then NuGet will detect it and use it automatically, without having to set the `NuGetLockFilePath` property.

I know that it's not easy to find find the right docs, but NuGet doesn't get the benefit of technical writers, like many other Microsoft products, and we don't get a reduced workload to spend more time on docs 🤷
