### ISSUE TITLE
[Bug]: Visual Studio fails to load SDKs in global.json that is next to project but not solution

### ISSUE THREAD

**Issue by benwitman** [NuGet/Home#11946]
### NuGet Product Used

MSBuild.exe

### Product Version

Microsoft.Build.NuGetSdkResolver 6.2.1.2

### Worked before?

6.0.1.1

### Impact

I'm unable to use this version

### Repro Steps & Context

Create a MsBuild project that uses custom SDK
Put a global.json next to that project which specifies the version of that SDK
Create a solution for that MsBuild project and save that solution the parent directory
Load the solution in Visual Studio and it says it cannot find the SDK

**Comment by benwitman** [comment]
@jeffkl this feels like a unintended? behavior change of [4380](https://github.com/NuGet/NuGet.Client/pull/4380)?

**Comment by jeffkl** [comment]
Duplicate of https://github.com/NuGet/Home/issues/11747

@benwitman this was an intentional behavior change so that the .NET SDK resolver and the NuGet-based MSBuild project SDK resolver respect the same global.json discovery.  In the entire .NET ecosystem, it is only supported to have a single global.json which should be placed at or near the root of the repository.  It is not supported to have multiple global.json files with differing configurations.

**Comment by benwitman** [comment]
@jeffkl I guess that makes sense.  Note: in this case we do have a single global.json in the repository, it just so happens that the solution file is in the directory above where it is stored.

**Comment by jeffkl** [comment]
@benwitman the logic if the SDK resolver should start looking in the directory of the solution file and then walk up to all parent directories until it finds a `global.json` or the root of a drive.  The new logic just starts looking next to the solution file first a solution file exists in the context, otherwise it looks next to the project and walks up the tree.

> in this case we do have a single global.json in the repository, it just so happens that the solution file is in the directory above where it is stored.

This should work just fine as long as the solution file is in any directory below your `global.json`, is that not what you're seeing?
