### ISSUE TITLE
[Cross-platform sign Verify] The expected error/warning disappeared after restoring the project on Mac

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11940]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.3.0.102

### Impact

It bothers me. A fix would be nice

## Repro steps
1. Git clone [https://github.com/NuGet/Entropy.git](https://github.com/NuGet/Entropy.git)
2. Set the following parameters in “pathOnUnix.ps1” file:
    a. The SDK channel must be: 6.0.4xx
    b. The SDK version should be:  latest
    c. Add a -Quality/--quality argument with a value of: signed
3. Cd /home/nuget/Desktop/SDKPatchTool/ and type in command './patchOnUnix.ps1'
4. Create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile`
5. Sign a package:` NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>` on NuGet path.
6. Copy the.pfx file/.cer file and signed package from the above Windows machine to Mac machine.
7. Add the certificate to trusted store: 
`sudo security add-trusted-cert -d -r trustRoot -k "/Library/KeyChains/System.keychain" "<cerFilePath>"`
8. Trusted Certificate:  
     a. Copy the PFX file to your Mac machine.
    b. Open a Terminal window and execute:
    `    openssl pkcs12 -in <PfxFilePath> -out <PemFilePath> -nokeys`
        When prompted, enter the PFX password.
    c. Open the PEM file created in step 3.
   d. Copy the entire block labelled with BEGIN CERTIFICATE/END CERTIFICATE:
-----BEGIN CERTIFICATE-----
…
-----END CERTIFICATE-----

  e. In the versioned directory of your patched .NET SDK open ./trustedroots/codesignctl.pem.
  f. At the end of the file on a new blank line, paste the copied certificate in PEM format.
  g. Save the file.

8. Create a project, add package reference in the .csproj file
```
  <ItemGroup>
    <PackageReference Include="<packageName>" Version="<packageVersion>" />
  </ItemGroup>
```
9. Add the feed (path contains the signed package), set required mode in nuget.config file with trusted signers list:
  ```
  <packageSources>
      <add key="<anyname>" value="<signed package parent folder>" />
     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
   </packageSources>
   <config>
    <add key="signatureValidationMode" value="require" />
   </config>
  <trustedSigners>
     <author name="JamieZhang">       
         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```
10. Clear the cache: <patchedSDKPath>`./dotnet nuget locals all –clear`.
11. Delete the <projectPath>/obj folder if there is any.
12. Set the envrioment:
  `export DOTNET_NUGET_SIGNATURE_VERIFICATION=true`
13. Go inside the project folder, verify the package by running restore: <patchedSDKPath>`./dotnet restore <projectpath>/<projectname>.csproj`

## Expected
The expected error/warning should show after restoring the project.

## Actual
The expected error/warning disappeared after restoring the project.

**Comment by dtivel** [comment]
This bug is confusing for a couple reasons:
* In step 4 you create a certificate and in step 5 you sign a package with that certificate.  However, in step 7a you create a _new_ certificate and trust that certificate in steps 7f-h.  I think you meant to trust on macOS the certificate you created in step 4, which means you don't need to create a new certificate in step 7.
* The expected error/warning is unclear from the bug report.  Can you be explicit about what the expected error/warning is?  I assume from the trusted signer fingerprint of `AAAAA` that the expected error on macOS is `error NU3034: Package '...' from source '...': This package is signed but not by a trusted signer.`, but it would be good for you to confirm.  If it is the expected error, then it is by design behavior that this error is not raised with my PR because the new default restore behavior on macOS is to not verify signed packages.  You can enable signed package verification during restore by executing the following before restore:

   `export DOTNET_NUGET_SIGNATURE_VERIFICATION=true`

**Comment by erdembayar** [comment]
@v-longmin
Is this bug still valid?

**Comment by v-longmin** [comment]
@erdembayar Sorry, I didn't description the repro steps clearly on before bug report. So, I update the repro steps on this bug, following the latest repro steps, the expected warning(e.g. ![image](https://user-images.githubusercontent.com/40230425/177700410-1dafd81e-d833-4a95-9304-f1023f8b20d3.png)) or expected error(e.g.![image](https://user-images.githubusercontent.com/40230425/177700546-174b1182-1bae-429c-8aae-500f9f94d0c0.png)) still not repro.

**Comment by dtivel** [comment]
First, the fact that no warnings/errors display during restore on macOS when signature verification is disabled is expected behavior.  So, I think we should close this bug.

Second, for the test pass, we should not be enabling signature verification (`DOTNET_NUGET_SIGNATURE_VERIFICATION=true`).  If you're verifying behavior with verification enabled, then you need to set the environment variable.  If you're verifying default behavior where verification is disabled, then you should not set it.  There is value verifying the behavior when signature verification is enabled, but I don't think the test pass is supposed to verify the non-default behavior.  Please correct me if I'm mistaken.  Step 12 does not belong.

Also, step 7 should not be present.  Step 8 is sufficient.

Here's what I did:

# On Windows
1.  In a command prompt, execute:
```text
git clone https://github.com/NuGet/Entropy.git
pushd .\Entropy\TestCertGenerator
pwsh .\CreateTestCertificate.ps1 -GenerateCerFile -Password password -AddAsTrustedRootAuthority
```
2.  Where `<PackageFilePath>` is the file path for a test package and `<PfxFilePath>` is the file path for the newly created .pfx file, execute:  `dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath> --certificate-password password --overwrite`
3.  Copy the signed package and the .cer file to a macOS machine.

# On macOS
1.  In a Terminal prompt, execute:
```bash
curl -sSL https://dot.net/v1/dotnet-install.sh -o ~/Downloads/dotnet-install.sh
chmod +x ~/Downloads/dotnet-install.sh
~/Downloads/dotnet-install.sh --channel 6.0 --version latest --quality GA --install-dir ~/Desktop/cli6.0 --no-path
~/Downloads/dotnet-install.sh --channel 6.0.4xx --version latest --quality daily --install-dir ~/Desktop/cli6.0.400 --no-path
export DOTNET_MULTILEVEL_LOOKUP=0
mkdir ./test && pushd ./test
~/Desktop/cli6.0/dotnet new console
```
2.  Get the SHA-256 fingerprint of the .cer file with the following:
```PowerShell
pwsh Get-FileHash -Algorithm SHA256 <CerFilePath> | Format-Table -AutoSize
```
3.  Where `<PackageDirectoryPath>` is the directory path for the test signed package and `<CertificateFingerprint>` is the SHA-256 fingerprint obtained in the previous step, add the following content as NuGet.config in the test directory:
```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local" value="<PackageDirectoryPath>" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="signatureValidationMode" value="require" />
  </config>
  <trustedSigners>
    <author name="Me">
      <certificate fingerprint="<CertificateFingerprint>" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
    </author>
  </trustedSigners>
</configuration>
```
4.  Where `<CerFilePath>` is the file path for the .cer file, execute in a Terminal window:
```bash
openssl x509 -inform der -in <CerFilePath> -outform pem -out ./cert.pem
```
5.  In the newly created ./cert.pem file, copy the entire block labelled with `BEGIN CERTIFICATE`/`END CERTIFICATE`:
```text
-----BEGIN CERTIFICATE-----
…
-----END CERTIFICATE-----
```
7.  Open ~/Desktop/cli6.0.400/sdk/6.0.400/trustedroots/codesignctl.pem, paste the copied certificate on a new line, and save the file.
8.  In a Terminal prompt pathed to the test project directory, execute:
```bash
~/Desktop/cli6.0/dotnet nuget locals --clear all && rm -r -f ./obj
~/Desktop/cli6.0/dotnet restore -v detailed
~/Desktop/cli6.0.400/dotnet nuget locals --clear all && rm -r -f ./obj
~/Desktop/cli6.0.400/dotnet restore -v detailed
```

The results between .NET 6.0 GA and .NET 6.0.400 are the same:  no warning/error.

Note:  you do not need to patch the 6.0.400 daily build as it already has my changes.

**Comment by v-longmin** [comment]
We verified the issue on .Net SDK 7.0.110, this issue doesn't repro, so close it, thanks.
