### ISSUE TITLE
v2 publish endpoint needs to be read from v3 index.json

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#1202]
The v2 publish endpoint needs to be read from the v3 index.json

Otherwise users who have configured package restore from v3 will be expected to configure a different uri for publishing packages. This is confusing and unreasonable.

Instead the new nuget.exe should pick the publish endpoint from the index.json.

**Comment by jmyersmsft** [comment]
I would strongly prefer that this _not_ use the LegacyGallery entry in the index, but instead use a new entry ("LegacyPushService"?), so that implementations that are only implementing v2 push as a stop-gap until a proper v3 push is available don't have to implicitly promise that they implement a full v2 service.

**Comment by deepakaravindr** [comment]
@jmyersmsft 
Yes. Push is a different endpoint and we will not use LegacyGallery entry for that

**Comment by jmyersmsft** [comment]
cool, thanks :)
