### ISSUE TITLE
[Bug]: [Bug Bash] The version of a deprecated package “Microsoft.NetCore.App” is empty and the “Update” button is available in Browse tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12057]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.4.0.51

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\32825.32
NuGet Version: Dev\6.4.0.51
OS Version: Windows-11-Enterprise-21H2 ENU

#### Detailed repro steps
1. Create a “C# Web Driver Test for Edge (.NET Core)” project in VS.
2. Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3. Click the “Browse” tab and search package “Microsoft.NetCore.App” in the filter.
4. Click the searched package in the list and observe the right panel.

#### Expected
The version of a deprecated package “Microsoft.NetCore.App” should not be empty. The “Update” button should not be available if the empty version is expected.
#### Actual 
The version of a deprecated package “Microsoft.NetCore.App” is empty and the “Update” button is available as below screenshot. 
![image](https://user-images.githubusercontent.com/20632625/186883485-25eb4947-e802-475d-a34e-1ebee660fd44.png)
#### Note:
It doesn’t repro on NuGet Client 5.11.2.2.

**Comment by donnie-msft** [comment]
@martinrrm could you take a look today to help understand the prioritization? What happens when clicking Update, for example?

**Comment by martinrrm** [comment]
If you click update nothing happens, I can reproduce this bug. The problem is that `Microsoft.NetCore.App` doesnt have a OriginalString property and the combobox breaks. I created the application, and some packages are as package reference to the .csproj, but not this one and its being displayed as a top-level dependency.

![image](https://user-images.githubusercontent.com/43253759/186946890-152e0adf-633e-4b16-854b-18b73696d364.png)
![image](https://user-images.githubusercontent.com/43253759/186946948-18a236c6-5919-4f74-a9bf-880561236ac3.png)

**Comment by nkolev92** [comment]
Is this a regression?

**Comment by martinrrm** [comment]
I think it is, it should be like this since the combobox version was merged

**Comment by nkolev92** [comment]
Regression during this version (6.4), or from a previous version (6.3)?

We might want to get the fix in 6.4 regardless.

**Comment by martinrrm** [comment]
This should be present in 6.3 too

**Comment by nkolev92** [comment]
Ok, so it was a bug in 6.3. Given the lack of reports, then maybe we don't need it patched.

**Comment by nkolev92** [comment]
Given that this affects Maui projects, we want to take this in 6.4
