### ISSUE TITLE
[Bug]: View License dialog does not display license content

### ISSUE THREAD

**Issue by mbranscomb** [NuGet/Home#12060]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Package Manager 6.3.0
Microsoft Visual Studio Enterprise 2022
Version 17.3.2
VisualStudio.17.Release/17.3.2+32819.101

### Worked before?

Unknown

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Repro

- Open VS2022 
- Choose New Project
- Create new WPF Application from project template
- Choose .NET 6 (Long-term support)
- Right click project > Manage NuGet packages for project
- Search for `Microsoft.TestPlatform`
- Select `Microsoft.TestPlatform`
- Check project
- Click Install
- Click OK
- On License Acceptance dialog click View License link

Outcome

![image](https://user-images.githubusercontent.com/3381768/186989161-b981790b-9cc7-421d-90d3-d1a7ef72f539.png)

Expectations

License text is visible in dialog (previous behavior)

Context

Use of our NuGet package (https://www.nuget.org/packages/Esri.ArcGISRuntime.WPF) requires license acceptance.

**Comment by zivkan** [comment]
for triage: I was able to reproduce. The package contains an embedded license.

There are at least 2 problems:

1. Getting embedded licence doesn't work

[`NuGetPackageFileService.GetEmbeddedLicenseAsync` tries to get a URI from an in-memory cache](https://github.com/NuGet/NuGet.Client/blob/b396ad8b56c089ec3fa189f1013530d237a0e8c2/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetPackageFileService.cs#L123), but when I tried debugging, the key wasn't in the cache. The code path has no fallback when the key is not in the cache, which suggests to me that NuGet isn't using it like a cache at all.  This causes the service to return null, instead of a stream, and [the other end gets a null string as the file contents](https://github.com/NuGet/NuGet.Client/blob/b396ad8b56c089ec3fa189f1013530d237a0e8c2/src/NuGet.Clients/NuGet.PackageManagement.UI/Models/LicenseFileText.cs#L39), which in turn gets passed to `GenerateParagraphs`, which then throws a null reference exception.

2. The UI shows the "loading license file" message, even though the code threw an exception and it's no longer attempting to load the license file contents.

**Comment by mbranscomb** [comment]
@zivkan @nkolev92 Is the best repo/location for this issue? Would be great to see it solved in an upcoming release of VS.

**Comment by nkolev92** [comment]
Yes, @mbranscomb this is the right repo. 

We prioritize investigations based on community engagement such as comments and up-votes. 
This is not on our immediate (think, a month or two) backlog right now, but we'd like to have it solved.

**Comment by artemkoloskov-admin** [comment]
Same issue here, EULA.txt is included in the package, but when the package is being installed, although EULA.txt is present in [user]/.nuget/packages/[package]/[version]/ the dialog window just shows 
![image](https://user-images.githubusercontent.com/102773427/216002429-b392e14e-b31a-4e27-87fb-c9f04d84e62b.png)

**Comment by BretJohnson** [comment]
Isn't this a legal / compliance issue, not showing licenses?
Also, per the original problem report, this is a regression.

It's of course up to the NuGet team, but I'm a bit surprised that those two things aren't enough to make it meet the fix bar.

In any case, I was just weighing in here as it came up in this Twitter thread: https://twitter.com/khellang/status/1633468315208130561?s=20. Thx.

**Comment by BretJohnson** [comment]
FYI - The Microsoft.Data.SqlClient package has the same issue.
![image](https://user-images.githubusercontent.com/245892/223914549-e4eb6f38-61ca-4179-b1fa-9be612bf98b5.png)

**Comment by JimBobSquarePants** [comment]
Can we please get some feedback here. The issue is critical from a legal perspective.

**Comment by artemkoloskov-admin** [comment]
What is most irritating is that links to license urls are deprecated for 4 years already, so you kind of need to use files, but it doesn't work and is not being worked on.
