### ISSUE TITLE
[Bug]: 'http' package source warning cannot be suppressed

### ISSUE THREAD

**Issue by drieseng** [NuGet/Home#12071]
### NuGet Product Used

NuGet.exe

### Product Version

6.3.0

### Worked before?

6.2.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

As of version 6.3.0, NuGet discourages the use of HTTP package sources. While I understand that you want to encourage HTTPS package sources, I think it's a mistake to force this upon users. That is another discussion though.

Currently, there are several commands in the command-line client that provide no way to suppress the NU1803 warning.
One such example is `nuget install`.
If you use that command to install a package from a HTTP package source, you'll the following warning:
```txt
WARNING: You are running the 'install' operation with an 'http' source, 'http://proget/nuget/nis-unstable/'. Support for 'http' sources will be removed in a future version.
```

We are using a local package source (proget), and will not migrate to HTTPS in the coming months (and we wouldn't if not for the decision that the NuGet team forces upon us).  Until then, these warnings will continue to pollute our build logs.

Would it be possible to add an option suppress this warning. I propose to implement this in such a way that any given warning or (non-critical) error can be suppressed.

I also think it would have been better to add *NU1803* as prefix in the warning message that is produced.

**Comment by donnie-msft** [comment]
@kartheekp-ms  could you help assign priority?

**Comment by kartheekp-ms** [comment]
I propose to close this issue by `design`. I added triage discussion label incase if the team has different feedback.

> As of version 6.3.0, NuGet discourages the use of HTTP package sources. While I understand that you want to encourage HTTPS package sources, I think it's a mistake to force this upon users. That is another discussion though.

There are few comments in https://devblogs.microsoft.com/nuget/https-everywhere/ blog post expressing the same concern.

> Currently, there are several commands in the command-line client that provide no way to suppress the NU1803 warning.
One such example is nuget install.

We can suppress `NU1803` by adding it to `<NoWarn>` in the project file as per https://devblogs.microsoft.com/nuget/https-everywhere/#comment-232. As far as I know, `NoWarn` is applicable to `restore` and `pack` operations but not for other NuGet operations. I think the decision to not add `NU1803` for all the commands is by design because the warning can't be suppressed and [docs](https://docs.microsoft.com/nuget/reference/errors-and-warnings) also state that `The errors and warnings listed here are available only with` [PackageReference-based](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) `projects and NuGet 4.3.0+. NuGet also honors MSBuild properties to suppress warnings or elevate them to errors. `

> Would it be possible to add an option suppress this warning. I propose to implement this in such a way that any given warning or (non-critical) error can be suppressed.

As communicated in the [blog post](https://devblogs.microsoft.com/nuget/https-everywhere/#what-you-can-expect), `We will upgrade that warning into a new error when a non-HTTPS source is used. You will be able to opt-out of this behavior for the time being to help migrate to HTTPS sources`. I think what this means is that customers will be able to opt-out of NuGet raising errors for HTTP feeds (I assume we will continue to warn), but the solution will not be generic enough to opt-out of any given warning or (non-critical) error.

**Comment by donnie-msft** [comment]
Thanks, Kartheek. I'll leave this issue open for now, since the feedback from the Blog posts isn't captured in another issue that I can see.

**Comment by zivkan** [comment]
Is this issue a duplicate of https://github.com/NuGet/Home/issues/12013?  That issue is older and has more upvotes.

**Comment by donnie-msft** [comment]
> Is this issue a duplicate of #12013? That issue is older and has more upvotes.

Good find, yes I think that's not about Kubernetes specifically, so I'll duplicate this to https://github.com/NuGet/Home/issues/12013. 
Thanks!
