### ISSUE TITLE
[Bug]: [Cross-platform Sign Verify] Command “powershell.exe  -Command Compress-Archive -Path” failed to execute since .nupkg is not supported

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12117]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 7.0.100-rtm.22476.1

### Impact

It's more difficult to complete my work

## Repro steps: 
1. Execute the [pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29).
2. Add trust for the certificate:` .\dotnet\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath>`
3. Sign the test package:` .\dotnet\dotnet nuget sign .\<PackageId>\bin\Debug\<PackageId>.1.0.0.nupkg --overwrite --certificate-path <PfxFilePath> --timestamper http://timestamp.digicert.com/`
4. Verify that the previous step succeeded with no warnings or errors.
5. Modify the signed package:` powershell.exe  -Command Compress-Archive -Path .\NuGet.config.template -Update -DestinationPath .\<PackageId>\bin\Debug\<PackageId>.1.0.0.nupkg`

## Expected:
The command should be executed successfully.

## Actual:
The command failed to execute as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/192493744-7b5a5cbd-92d6-4d49-9a6d-2c3311696ca8.png)

## Note:
It is not a regression.

**Comment by erdembayar** [comment]
I can repro this. But I'm not really sure if it's actual NuGet bug or not.

```
trace:                   Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:                   Valid from: 11/9/2006 4:00:00 PM to 11/9/2031 4:00:00 PM

Successfully verified package 'TestCertGenerator.1.0.0'.
C:\NuGetProj\Entropy\TestCertGenerator [main ≡ +3 ~0 -0 !]> powershell.exe -Command Compress-Archive -Path .\NuGet.config.template -Update -DestinationPath C:\NuGetProj\Entropy\TestCertGenerator\bin\Debug\TestCertGenerator.1.0.0.nupkg
Compress-Archive : .nupkg is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:1
+ Compress-Archive -Path .\NuGet.config.template -Update -DestinationPa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.nupkg:String) [Compress-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Compress-Archive
```

**Comment by nkolev92** [comment]
Team Triage: This seems like a test bug. 

@dtivel or @heng-liu which one of you owns this test scenario?
Can you please take a look?

**Comment by heng-liu** [comment]
Sorry for the late reply!
This is from step 4 of [Cross-platform verify:  tampered signed package](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FCross-platform%20verify%3A%20%20tampered%20signed%20package%7CEC78D709-CBFC-4ECD-B068-85DE4584FF38%2F%29), right?
If so, my understanding is, this is to tamper a signed package and tried to verify it (should fail the verification).
Since the [-DestinationPath](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.3#-destinationpath) option of powershell Compress-Archive command  should be a zip file, and .nuget is actually a zip file. We could rename the .nupkg into .zip before running this command, and then pass the .zip file in this command. And we could rename the .zip file back into .nupkg after running this command.
Pls correct me if there is anything wrong @dtivel . Thanks!

Hi, @v-longmin, could you help verify if that works? Thanks! Pls let me know if there is anything not clear.

**Comment by dtivel** [comment]
@heng-liu is correct.  I updated step 4 in the test case.  Reopen if it's still an issue after following the updated instructions.

**Comment by v-longmin** [comment]
@heng-liu We verified it on Dotnet 7.0.101, it works well, thanks.
