### ISSUE TITLE
Details for Installed MAUI packages are missing NuGet Project PM UI

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#12130]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Details-for-Installed-MAUI-packages-are-/10119414)._

---
[severity:It's more difficult to complete my work]
Repro Steps:

1. Open Visual Studio 2022 17.3
2. Create a New MAUI App
3. Let Visual Studio finish all background tasks
4. Right click on Project, 'Manage NuGet Packages...'

Expected: PM UI shows package details on Installed Tab, on Details pane when the package is clicked

Actual: No details info shown.

**NOTE**: This works well in Solution PM UI.

---
#### Feedback Bot on 8/14/2022, 07:39 PM: 

(private comment, text removed)
#### Feedback Bot on 8/18/2022, 01:21 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by erdembayar** [comment]
Could be related to https://github.com/NuGet/Home/issues/12057

**Comment by nkolev92** [comment]
This is likely fixed on latest dev. 

@dominoFire 

Can you validate please? We'd likely want to service the fix if we confirm that.

**Comment by dominoFire** [comment]
Issue seems to be fixed by https://github.com/NuGet/NuGet.Client/pull/4844

Using NuGet build excluding the PR

![image](https://user-images.githubusercontent.com/1192347/194443329-705f2a30-3dc3-49e1-84cd-a2257baa9147.png)


Using NuGet build including the PR
 
![image](https://user-images.githubusercontent.com/1192347/194443064-8e09cf2f-e70d-423c-9d31-9d483a1fc1a9.png)
