### ISSUE TITLE
long numeric "<pre-release identifier>" not supported

### ISSUE THREAD

**Issue by richard-post** [NuGet/Home#12237]
### NuGet Product Used

dotnet.exe

### Product Version

7.0.100 e12b7af219

### Impact

It's more difficult to complete my work

### Repro Steps & Context

**Context**
It seems that NuGetVersion does not support a long numeric <pre-release identifier>.  I think this is valid according to semver2:
```
<dot-separated pre-release identifiers> ::= <pre-release identifier>
                                          | <pre-release identifier> "." <dot-separated pre-release identifiers>

<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>
```

**Repro**
Build any project using version _0.12.0-SOF-628.**0410957**+1021_
`dotnet publish src/server/server.csproj /p:Version=0.12.0-SOF-628.0410957+1021`

### Verbose Logs

```shell
(in) RestorePackagesConfig 'False' (TaskId:39)
13:25:37.498     1>C:\Program Files\dotnet\sdk\7.0.100\NuGet.targets(132,5): error : '0.12.0-SOF-628.0410957+1021' is not a valid version string. (Parameter 'value') [C:\source\repo\server\src\server\server.csproj]
                     System.ArgumentException: '0.12.0-SOF-628.0410957+1021' is not a valid version string. (Parameter 'value')
                        at NuGet.Versioning.NuGetVersion.Parse(String value)
                        at NuGet.Commands.MSBuildRestoreUtility.GetVersion(IMSBuildItem item)
                        at NuGet.Commands.MSBuildRestoreUtility.GetPackageSpec(IEnumerable`1 items)
                        at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
                        at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
                        at NuGet.Commands.MSBuildRestoreUtility.GetDependencySpec(IEnumerable`1 items)
                        at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log) (TaskId:39)
                   Done executing task "RestoreTask" -- FAILED. (TaskId:39)

Full log:
https://gist.github.com/richard-post/c5974a89e3e2a7b978a265082b516eef
```

**Comment by zivkan** [comment]
@richard-post [item 9 of the SemVer spec](https://semver.org/#spec-item-9) says:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Numeric identifiers MUST NOT include leading zeroes.** Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

I bolded the relevant part, but to me the bold text doesn't stand out clearly, so here is the relevant part:

> Numeric identifiers MUST NOT include leading zeroes

**Comment by richard-post** [comment]
Thank you. I would expect it to be interpreted as an alphanumeric in that case. But it's clear that in your viewing of the standard it is expected behavior, thank you for the info and we now know we have to change it on our side.

**Comment by zivkan** [comment]
In theory we could change NuGet to treat it as a character string. But then packages created that use this will break older versions of NuGet, probably with really awful error messages. I'm thinking of scenarios where a package has a dependency on another package with a prerelease leading zero. It's one thing to get a "not a valid version string" when packing your own project, at least you can guess it's probably your own project's version string. But if you were restoring a project where none of the versions in the project use a leading zero, it will be really difficult to determine that the problem is a customer is using an old client where a transitive dependency has a leading zero, which was not allowed before, but is allowed in higher versions.

So then extra work would be required to make packages with leading zeros, or that have dependencies where the version has a leading zero, require a minimum client version. I know that NuGet already has this capability (otherwise it wouldn't prevent older clients from trying to use the package and crashing when parsing the version number), but no new feature used it since I joined the team, so I don't know how easy/hard it would be to use.

However, I'm not sure when exactly NuGet implemented semver2, but I don't remember any issues before this one reporting this issue in the 4 years I've been in the team. So I'm afraid I just don't think it's worth the effort without upvotes or duplicate requests.
