### ISSUE TITLE
Unable to remove a package that doesn't exist

### ISSUE THREAD

**Issue by Irgy0** [NuGet/Home#12250]
### NuGet Product(s) Affected

NuGet.exe

### Current Behavior

I am on a machine which is not and cannot be connected to the internet. When I attempt to remove a package that's listed as installed, but isn't present on the machine, it tries to first restore the package, fails, and the package continues to be shown as installed.

### Desired Behavior

There should be some way to uninstall a package that isn't even installed in the first place, without having to install it first.

### Additional Context

As best I can tell I am in an unrecoverable state. I cannot restore the packages without the internet. I cannot uninstall the packages without restoring them. So I am stuck with these packages and dependencies forever.

When I try to build the code, it first attempts to restore the packages, and floods me with errors that it can't do so. The build then completes despite these errors. I can disable the automatic downloading of packages, and the build completes without error, but I still haven't solved the underlying problem.

If anyone could advise how to manually edit the solution and/or project files, plus whatever other files I would need to edit, to get it into a correct state, that would be much appreciated.

**Comment by erdembayar** [comment]
Thank you for filing this issue.
Could be able to share any error log or screenshot after removing sensitive information (I assume machine is air gapped for some reason)? At this moment now sure what is going. Is it sdk style project or packages.config style project? If it's sdk style then most likely you can just manually edit it on VS or VScode to remove package ref, if it's package.config style project then just open that one to remove the package reference. Also, there're transitive dependencies your direct dependency brings in then it's more complicated, because you still may need to download. Do you have org/corporate package package source feed?

**Comment by zivkan** [comment]
> if it's package.config style project then just open that one to remove the package reference

This is not correct. With packages.config, NuGet (tells the VS project system to) modify the project with with `<Reference` to assemblies, `<import` of msbuild files, if the package contains `content/*`, then those packages are copied into the project with an appropriate MSBuild item type, which is reversed on uninstall. If the package contains `tools/uninstall.ps1`, then that is exucuted, which might theoretically modify the project file. However, all of these requires the contents of the package to be known, so the exact steps to uninstall can be determined.

This is why packages.config needs packages to be restored in order to uninstall. Someone determined enough to do it all manually could, but there's too much complexity to have simple instructions and the exact steps are package specific.

For PackageReference, yes, it's just one line in the project file that can be deleted.

**Comment by Irgy0** [comment]
Sorry I'm now over 1000km away from the machine myself, but I can get someone to get a screenshot if it helps? The gist of it was though that I would open the nuget package manager in Visual Studio, see the missing package I wanted to remove, either click on the "X", or select it then click uninstall (same result either way). It would then say it was trying to download the package, fail of course, and pop up a yellow message box at the top saying it failed to update the package, and no change gets made.

I tried the command line approach as well, and had the analogous problem, it would try to download the package I'm trying to remove, fail, and tell me it's unable to uninstall it.

From a bit of Googling, I had the impression this is entirely expected behaviour. As far as I read the situation, it needs to download the package, or at least find the package in cache, to know what's in the package, to know what to remove when it uninstalls. It's just a problem in my own rather specific situation. Clearly whoever copied this code across should have removed the unneeded packages from the source code itself when they had the chance, rather than just neglecting to copy them over, but it's too late now to fix that. I think another workaround/way out would be to manually put those packages in the cache on the machine, so it then knows what to remove, but I'd need to better understand how they're kept.

So I'm not convinced a screenshot will tell you any more than what I have, though it might say it a little more clearly. But if I'm wrong I can get someone local to do it for me.

**Comment by zivkan** [comment]
@Irgy0 as I tried to explain in my comment, if the project uses PackageReference, then you can just edit the csproj with any text editor, remove the one line, and be done. Some people believe VS should do this by default, other people prefer VS validating that the new restore graph works and to block install/uninstall actions that would cause restore to fail if completed.

However, if your project uses packages.config, then what you're asking for is technically impossible to do correctly without restoring the package first.

If your project uses packages.config, the edits to both the csproj and packages.config files are needed, but the exact changes depends on the contents of the package. This is why the package has to be restored before uninstalling, so NuGet knows what changes are needed.

If you, or your colleagues, are sufficiently confident, you can try to analyze the project file (csproj) and delete lines you believe come from the package (both `<Reference` and `<Import` statements will include a path similar to `..\packages\{packge_id}.{version}\`, but "content" from packages copied into the project don't have any paths to indicate they came from a package). There is no existing feature to do this. Unless you can find a way to restore the package first, your only option is to edit the files in a text/xml editor manually.

**Comment by nkolev92** [comment]
Thank you very much for your feedback.
This is a design limitation within packages.config, and as such the only way forward would be to manually make the changes in the packages.config and project files. 

At this point, we don't believe we'll be able to fix this. 
If possible, we suggest moving from packages.config to PackageReference with latest Visual Studio to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
