### ISSUE TITLE
NuGet.config permission issue on Linux for dotnet nuget commands

### ISSUE THREAD

**Issue by Sam13** [NuGet/Home#12255]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 6.0.402 and above

### Worked before?

.NET SDK 6.0.401 and below

### Impact

I'm unable to use this version

### Repro Steps & Context

Taking over https://github.com/dotnet/sdk/issues/29098

### Describe the bug
Having a _nuget.config_ which belongs to another user and group but chmoded 777.
Running e.g. ```dotnet nuget add source``` will produce the error message:
```
error: NuGet.Config is malformed. Path: '/nuget.config'.
error:   Unable to set permission while creating /nuget.config, errno=1.
```
but file is changed: Package source is added.
When supplying additional credentials the package source is added but the credentials aren't.

I expect that the command works without error since _nuget.config_ file is chmodded 777.

This starts to happen with .NET SDK 6.0.402 - all prior versions of .NET SDK 6 work.

### To Reproduce
I have created an example with Docker:
- Clone https://github.com/Sam13/dotnet-sdk-nuget-config-permission-issue
- Run ```./reproduce-issue.sh``` in a Linux bash.
- See comments in shell scripts for further details.

### Exceptions (if any)
```
error: NuGet.Config is malformed. Path: '/nuget.config'.
error:   Unable to set permission while creating /nuget.config, errno=1.
```

### Further technical details
- Works with .NET SDK 6 < 6.0.402
- Does not work with .NET SDK 7

### Verbose Logs

```shell
+ docker run --rm --user 1000 -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -e HOME=/tmp dotnet-sdk-nuget-config-permission-issue-repro:latest bash -c './container.sh || cat /nuget.config'
+ whoami
test-user
+ ls -l /nuget.config
-rwxrwxrwx 1 root root 70 Nov 18 08:53 /nuget.config
+ cat /nuget.config
<?xml version="1.0" encoding="utf-8"?><configuration></configuration>
+ dotnet nuget add source https://mytestsource -n TestSourceName --configfile /nuget.config
error: NuGet.Config is malformed. Path: '/nuget.config'.
error:   Unable to set permission while creating /nuget.config, errno=1.


Usage: dotnet nuget add source [arguments] [options]

Arguments:
  PackageSourcePath  Path to the package source.

Options:
  -n|--name                       Name of the source.
  -u|--username                   Username to be used when connecting to an authenticated source.
  -p|--password                   Password to be used when connecting to an authenticated source.
  --store-password-in-clear-text  Enables storing portable package source credentials by disabling password encryption.
  --valid-authentication-types    Comma-separated list of valid authentication types for this source. Set this to basic if the server advertises NTLM or Negotiate and your credentials must be sent using the Basic mechanism, for instance when using a PAT with on-premises Azure DevOps Server. Other valid values include negotiate, kerberos, ntlm, and digest, but these values are unlikely to be useful.
  --configfile                    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help                       Show help information
```

**Comment by erdembayar** [comment]
@Sam13 
It looks docker/bash scripts issue rather than dotnet/nuget issue, docker is not my expertise but I managed to make it work, probably you need to improve further.
https://github.com/erdembayar/DockerTest1/commit/9fc722507f7e44c7dbd066f9d3b502fb9afd55c3

```
++ id -u
+ docker run --rm --user 1000 -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -e HOME=/tmp dotnet-sdk-nuget-config-permission-issue-repro:latest bash -c './container.sh || cat /nuget.config'
+ whoami
+ ls
someuser
7e3318d9-ef0c-46a4-8ffe-9389ab6be2cc
8c8bff3a-a60e-49fb-ac2c-97ea8c28bc55
MSBuildTemproot
container.sh
+ echo '<?xml version="1.0" encoding="utf-8"?><configuration></configuration>'
+ ls
7e3318d9-ef0c-46a4-8ffe-9389ab6be2cc
8c8bff3a-a60e-49fb-ac2c-97ea8c28bc55
MSBuildTemproot
container.sh
nuget.config
/tmp
+ pwd
+ dotnet nuget add source https://mytestsource -n TestSourceName --configfile ./nuget.config
Package source with Name: TestSourceName added successfully.
+ ls -l nuget.config
-rw------- 1 someuser root 176 Nov 18 23:53 nuget.config
+ cat nuget.config
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="TestSourceName" value="https://mytestsource" />
  </packageSources>
</configuration>
```

**Comment by Sam13** [comment]
@erdembayar, in your example the NuGet config is now owned by the user which is executing the _dotnet add source_ command.

```
-rw------- 1 someuser root 176 Nov 18 23:53 nuget.config
```

According my experience this works. You proved it.

In my real world scenario I don't want to change the owner of the nuget.config because it's a prebuilt image.
This image does not know under which user it is going to be executed.

The question still remains why the _dotnet nuget_ command does not work altough the file is chmodded 777 which makes it accessible for everyone...

You can also reproduce that without Docker just under ordinary Linux. I have choosen Docker for this example to make it easily reproducible.

**Comment by Sam13** [comment]
@erdembayar Could it be that the behavior of NuGet changed in order that the _NuGet.config_ file is somehow recreated when the ```dotnet nuget add source``` command is executed?
This would require additional write permissions on the directory and may cause the command to fail.

**Comment by zivkan** [comment]
> The question still remains why the dotnet nuget command does not work altough the file is chmodded 777 which makes it accessible for everyone...

@Sam13 the security fix from October started using `chmod` to set `700` permissions on the file. When making announcements, and commits, we're not allowed to publicly go into too many details, to not make it overly easy for malicious actors to exploit machines that haven't been patched. So, I don't want to get into too many details, but `nuget.config` files can contain secrets, so actions that modify the file will also change its permissions. Due to layers of abstraction, it was difficult to only do this when secrets are being used, hence it's being done on all `nuget.config` file saves.

Unfortunately this is one of those cases where for security reasons we "need" to do something that can cause some problems. If you're sure that `chomod 777` is something you want to do (and is safe), can you do it after running `dotnet nuget add source`, not before? Can you help us better understand the scenario why you want multiple different user accounts to be able to read and/or modify a single nuget.config file? Normally we'd expect each user account to have their own `~/.nuget/NuGet/nuget.config`. The ["computer" or "machine" shared config locations](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) need admin/root access to modify and we expect these to be created by an installer, or group policy, that uses a pre-created xml file, not using `dotnet` CLI commands. Perhaps this was an oversight, but security concerns of the most common usage still needs to be accounted for, so I'm not sure how we'd change NuGet if we wanted to support this scenario. In case it's "normal" for docker to copy files using the host machine's UIDs, but then run the image with a different UID, I don't have almost any docker experience, so firstly this would surprise me, but secondly I need someone to help me understand how docker works so we can design a solution that meets both host machine and docker image security concerns.

**Comment by Sam13** [comment]
@zivkan 
Thanks for the detailed description.
If using own NuGet configuration file per user account is the recommended practice I will adapt to it.

When using Docker you don't know what user the container might run so you cannot create this file beforehand.
Now I just run `dotnet nuget list source` to create the initial configuration and afterwards add my source credentials to this file.
