### ISSUE TITLE
PrivateAssets flow incorrectly to transitively pinned centrally managed dependencies

### ISSUE THREAD

**Issue by marcin-krystianc** [NuGet/Home#12270]
### NuGet Product Used

dotnet.exe

### Product Version

7.0.100

### Worked before?

no

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

For project:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" PrivateAssets="Compile;Runtime" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" PrivateAssets="Compile" />
  </ItemGroup>
</Project>
```
and `Directory.Packages.props`:
``` xml
<Project>
    <ItemGroup>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageVersion Include="Newtonsoft.Json.Bson" Version="1.0.2" />
        <PackageVersion Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    </ItemGroup>
</Project>
```

The expected content of `centralTransitiveDependencyGroups` is:
``` json
"centralTransitiveDependencyGroups": {
    ".NETStandard,Version=v2.0": {
      "Newtonsoft.Json": {
        "include": "Runtime, Compile, Native, BuildTransitive",
        "version": "[13.0.1, )"
    }
  }
}
```
, but the SDK 7.0.100 produces empty `centralTransitiveDependencyGroups`.

PS:
I'm going to submit a PR with a fix.

**Comment by jeffkl** [comment]
@marcin-krystianc I don't think I understand what you're saying in the description.  PrivateAssets should end up in a `suppressParent` section of the `centralTransitiveDependencyGroups` section of `project.assets.json`.  I did the following:

Test.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" PrivateAssets="Compile;Runtime" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" PrivateAssets="Compile" />
  </ItemGroup>
</Project>
```

Directory.Packages.props
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageVersion Include="Newtonsoft.Json.Bson" Version="1.0.2" />
    <PackageVersion Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
  </ItemGroup>
</Project>
```

And the assets file has this:

```json
"centralTransitiveDependencyGroups": {
    ".NETStandard,Version=v2.0": {
      "Newtonsoft.Json": {
        "include": "Runtime, Compile, Native, BuildTransitive",
        "suppressParent": "Runtime, Compile",
        "version": "[13.0.1, )"
      }
    }
  }
```

NuGet takes the union of `PrivateAssets`, in this case `Compile;Runtime` and `Compile` so the `"suppressParent": "Runtime, Compile"` is correct.

But your example looks totally different and says that you get an empty `centralTransitiveDependencyGroups` section?  Can you please clarify so I can understand better?

**Comment by marcin-krystianc** [comment]
> But your example looks totally different and says that you get an empty centralTransitiveDependencyGroups section? Can you please clarify so I can understand better?

Ah, I think I've been playing with different examples which led to messing up my description. You are right, that my original example doesn't make sense 😞  
It should be:

---
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" PrivateAssets="All" />
  </ItemGroup>
</Project>
```
and `Directory.Packages.props`:
``` xml
<Project>
    <ItemGroup>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageVersion Include="Newtonsoft.Json.Bson" Version="1.0.2" />
        <PackageVersion Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    </ItemGroup>
</Project>
```

The expected content of `centralTransitiveDependencyGroups` is:
``` json
"centralTransitiveDependencyGroups": {
    ".NETStandard,Version=v2.0": {
      "Newtonsoft.Json": {
        "include": "Runtime, Compile, Native, BuildTransitive",
        "version": "[13.0.1, )"
      }
    }
  }
```
, but the SDK 7.0.100 produces empty `centralTransitiveDependencyGroups`.

---

The rationale is that adding `PrivateAssets="All"` only to one PackageReference shouldn't cause the `Newtonsoft.Json` to be excluded from `centralTransitiveDependencyGroups`. Only when `PrivateAssets="All"` is added to all of the PackageReference(s) , it should cause the `Newtonsoft.Json` to be excluded from `centralTransitiveDependencyGroups`.

**Comment by jeffkl** [comment]
@marcin-krystianc I think I'm convinced we need this fixed but I want to get consensus on the output.  Assuming PackageA and PackageB reference the same PackageC.

The default PrivateAssets if you don't specify anything is `Build | ContentFiles | Analyzers`, so `Default` below means that.


| PackageA | PackageB | PackageC |
|------------|------------|-----------|
|  (Default) | `PrivateAssets="All"` | `PrivateAssets="Build;ContentFiles;Analyzers"`|
| `PrivateAssets="Compile;Runtime"` | `PrivateAssets="Runtime"` | `PrivateAssets="Runtime"` |
| `PrivateAssets="All"` | `PrivateAssets="Runtime"` | `PrivateAssets="Runtime"` |
| (Default) | `PrivateAssets="Runtime;Build;ContentFiles"` | `PrivateAssets="Build;ContentFiles"` |
| `PrivateAssets="None"` | `PrivateAssets="Runtime"` | `PrivateAssets="None"` | 

So I'm going to push a commit to your branch to get it updated and have the test try a few different permutations.

**Comment by marcin-krystianc** [comment]
> So I'm going to push a commit to your branch to get it updated and have the test try a few different permutations.

Sure, adding more tests is always a good idea :-) I can also do it if you want.

**Comment by jeffkl** [comment]
> Sure, adding more tests is always a good idea :-) I can also do it if you want.

I'm still experimenting so it'll probably just be easier to push the branch then explain what I'm after.  I'll do it soon...

**Comment by jeffkl** [comment]
I finally think I got it figured out.  You're absolutely right that the assets should be the intersection.  However, the missing piece was that _transitive_ dependencies have different defaults than direct dependencies.  This was causing some confusion for me when I was updating the unit test and getting unexpected results.  But I think I have it figured out so I force pushed to your branch.  I'll get this reviewed and merged next week.  Thanks again for the contribution, I hope taking over the branch doesn't make you think we are any less grateful.  I think in this case the scenario was just too complicated to understand without me getting myself involved.  Your contribution is greatly appreciated!

**Comment by qlikTERror** [comment]
Sorry for commenting on this old issue, but I would like some clarification because I believe I'm encountering a problem related to the previously described scenario where *PackageA* and *PackageB* both reference *PackageC*, and the `PrivateAssets` property for *PackageC* is determined by the intersection of the settings in *PackageA* and *PackageB*.  

My questions are:  

1) If *PackageA* and *PackageB* do specify a custom `PrivateAssets` value for their reference to *PackageC*, shouldn’t this default value also be considered after their interesection result? If they are not letting flow the compile assets for example, the pinned dependency to PackageC should not let it flow too. In fact it should be even excluded from current compilation.
2) If I reference *PackageA* and *PackageB* directly but not *PackageC*, this likely means I do not intend to use *PackageC* in my code or in dependent projects. In such cases, wouldn't it be preferable for the pinned dependency to allow only runtime assets to flow, rather than promoting *PackageC* as a primary dependency? Why has NuGet historically handled this differently?  

Regarding question (2), I have always found it problematic that NuGet automatically promotes transitive dependencies to primary dependencies. This contradicts principles of encapsulation and abstraction—my code should depend only on explicitly declared primary dependencies, not on their transitive dependencies. Exposing transitive dependencies increases the risk of unintended usage, leading to long-term maintenance issues.  

I recently spent two days removing outdated dependencies from our projects because, in the past, certain package versions had specific transitive dependencies, which unintentionally became part of our dependency tree. The project itself should have been dependent only on primary dependencies, and I had to correct cases where transitive dependencies were used directly—mostly in extension methods.  

A common counterpoint to question (2) is that if both *PackageA* and *PackageB* reference *PackageC*, they may need to expose compile-time assets. I do have such cases in my codebase, particularly where we maintain extension projects that augment third-party libraries. In these cases (i.e. *PackageA* augments *PackageC* and depends on it) we configure `PrivateAssets` as follows on the dependencies of the extension project:  

PackageC, aka the third party library to augment:  
```xml
PrivateAssets="contentfiles; analyzers; build; buildMultitargeting"
```  
For all other dependencies: 
```xml
PrivateAssets="compile; contentfiles; analyzers; build; buildMultitargeting"
```  

This ensures that extension projects function correctly while keeping other dependencies encapsulated, but still required for the runtime.

Would appreciate any clarification on this, cause I am evaluating the option to open an issue about this topic.
