### ISSUE TITLE
Is it possible to make the --ignore-failed-sources option a global configuration?

### ISSUE THREAD

**Issue by pedoc** [NuGet/Home#12338]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe, NuGet SDK, Other/NA

### The Elevator Pitch

Currently, we can explicitly add the ``--ignore-failed-sources`` parameter when using the command line to ignore some non-existing paths. But this does not work for ``VS``.

Is it possible to add this option to global config file or ``Nuget.config`` file?

**Comment by aortiz-msft** [comment]
Hi @pedoc. We do not recommend pervasive use of this flag because it may lead to inconsistent (i.e. non-deterministic) results. For example, connectivity issue or some other transient issue with one of the sources may lead to different versions of dependencies being used. This is why we've made a conscious decision to NOT make this option available in NuGet.config.

**Comment by pedoc** [comment]
> We do not recommend pervasive use of this flag because it may lead to inconsistent (i.e. non-deterministic) results

Ok, so I figured I could add the functionality from source and build myself.
The next question is, how do I replace the default nuget implementation in VS with my own compiled version?

thanks
