### ISSUE TITLE
Nuget not searching in custom package sources

### ISSUE THREAD

**Issue by nielscup** [NuGet/Home#12358]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

nuget 6.4.0.117

### Worked before?

seems to work in 6.3.1.1, but on a different laptop

### Impact

I'm unable to use this version

### Repro Steps & Context

I have added a custom package source. If I search in nuget package manager, I find my package. If I install the package it fails with the following error:

```
Restoring packages for .NETStandard,Version=v2.1...
  GET https://api.nuget.org/v3-flatcontainer/mypackage.test/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/mypackage.test/index.json 125ms
Resolving conflicts for .NETStandard,Version=v2.1...
Unable to find package mypackage.test. No packages exist with this id in source(s): nuget.org
Package restore failed. Rolling back package changes for 'FormsApp1'.
```
In the logging I see that package manager only searches in nuget.org and not in my custom sources.

I am using VS for mac 17.4.2.
NuGet Version: 6.4.0.117

**QUESTION: How do I install a different version of Nuget?** I want to try version 6.3.1.1 to check if this works on the same laptop.

**Comment by nielscup** [comment]
**I solved this issue by installing [VS2019](https://my.visualstudio.com/Downloads?q=Visual%20Studio%202019%20for%20Mac).**

When installing VS2019 it replaces VS2022. But you can install VS2022 Preview alongside. After installing VS2019, the package manager works correctly in VS2019 as well as VS2022 Preview.

So either Nuget 6.4.0.117 or the installation of VS2022 is broken as this was a fresh install on a new laptop.

**Comment by donnie-msft** [comment]
Glad you were able to get unblocked already! My guess, without any knowledge of your solution or environment, is that some `nuget.config` on your machine had a `<Clear />` in the packageSources node, and it then added nuget.org as a package source. Probably by reinstalling VS, the relevant config file was replaced and didn't have this `<Clear/>`, and that's why you no longer experience this behavior. For more information, see https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

I'll close for now, but if you find evidence contrary to the above, please pass along the details so we can attempt to repro the problem.

**Comment by nielscup** [comment]
I think your guess may be quite accurate. Thanks for the info, if this happens again I know where to look now.
