### ISSUE TITLE
NuGet UI design improvements

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1236]
Here are some screenshots from the wiki

https://github.com/NuGet/Home/wiki/NuGet-UI-design-meeting-notes-August-20-2015
https://github.com/NuGet/Home/wiki/NuGet-UI-design-meeting-notes-August-21,-2015

NuGet 3.1.1
![image](https://cloud.githubusercontent.com/assets/1238711/9420470/e3579c98-481a-11e5-9365-4e00bfa674e6.png)

As early as NuGet 3.3
![image](https://cloud.githubusercontent.com/assets/1238711/9420463/cb253e82-481a-11e5-8e1c-204bb2fd7d85.png)

**Comment by yishaigalatzer** [comment]
Current UI (3.1.1)
![image](https://cloud.githubusercontent.com/assets/1238711/9447468/59d67136-4a4c-11e5-9a71-5f62c1083713.png)

Sketch from the meeting
![image](https://cloud.githubusercontent.com/assets/1238711/9447328/a956d8dc-4a4b-11e5-8c6a-4920ab6c28ee.png)

Second part of the meeting. The design does not yet address Update-All, and Update selected packages or the right side of the screen

**Comment by kmcginnes** [comment]
The best UX I've seen for package management is GitHub's Atom text editor.

They have two separate views. The first one shows the installed packages.

<img width="1033" alt="screenshot 2015-08-24 15 46 53" src="https://cloud.githubusercontent.com/assets/212862/9451997/92e8caf2-4a77-11e5-854f-da15fb44fc0d.png">

Search is large and clear. It breaks up the list based on the source, in their case from the community or from GitHub. In NuGet's case it would be the different package sources. Another nice touch is each source list is collapsable.

It has very clear information in the individual tiles. The version is easy to find. The package id is the title. No confusion about what's the package name versus the package id. There's just the package id. The author is easy to find. Basically, all the information I care most about is right there.

Then, the actions I need the most are easily accessible. For NuGet I would want an option for uninstall and upgrade, but only if an upgrade is available. This main upgrade button would update all projects with the package installed in the solution to the latest version.

The settings button would transition to a more detailed view. Atom's example falls down a bit here because their package management is much simpler than NuGet's.

<img width="1033" alt="screenshot 2015-08-24 16 16 50" src="https://cloud.githubusercontent.com/assets/212862/9452743/a157b27a-4a7b-11e5-8ed3-8b5ef320660f.png">

One of the best features of this view is that it will reach out the project's URL and look for a readme.md file and shows it if it exists. I can not recommend adding this enough.

NuGet's settings view would allow me to choose what projects this package should be installed on. It would also allow me to upgrade/downgrade to a specific version. I'm sure there are many other scenarios to cover, but the point is that all the less common options go within this view.

Atom's other view is the package browser. This is where you search for packages to install.

<img width="1033" alt="screenshot 2015-08-24 15 47 07" src="https://cloud.githubusercontent.com/assets/212862/9452003/980aaafa-4a77-11e5-90b9-f1ccc1a8c70b.png">

I like how searching for a new package to install is completely separate from managing my installed packages. NuGet has this separation already, but I don't believe it goes far enough. The information I want to see when searching for a new package is different than the information I want to see for installed packages.

**Package Browsing**
- Package ID
- Description
- Author
- Version (stable or prerelease depending on option)
- Number of downloads
- Actions: Install

**Managing Installed Packages**
- Package ID
- Description
- Author
- Installed Version
- Actions: Uninstall, Upgrade, Settings

I know the parallels are not exact between NuGet's and Atom's package management, but there are many great UX elements that can be lifted from Atom. I hope this post will at least get you thinking a bit outside the box. And don't be afraid of using icons in lieu of text for recognizable things. They're a tiny detail, but they make a huge improvement on the appearance of the UI when used correctly.

**Comment by yishaigalatzer** [comment]
I realize I forgot to include the design discussion items

https://github.com/NuGet/Home/wiki/NuGet-UI-design-meeting-notes-August-20-2015

https://github.com/NuGet/Home/wiki/NuGet-UI-design-meeting-notes-August-21,-2015

Adding them here and on top for future readers.

**Comment by daveaglick** [comment]
+1 for adding buttons to each individual package for available actions, but why only show the buttons for the selected package? It seems like that's just adding an unnecessary click by making you select a package before clicking the install/update/etc button. If the concern is over accidentally taking some action if all the buttons are displayed, the new popup preview screen should provide the necessary escape hatch.

**Comment by phillip-haydon** [comment]
@kmcginnes not just Atom. I love Atom's and Brackets.

![image](https://cloud.githubusercontent.com/assets/895629/9470051/b3e4a194-4b7c-11e5-903f-d5877a67300d.png)

![image](https://cloud.githubusercontent.com/assets/895629/9470089/eb47939e-4b7c-11e5-8cc1-6561fbbfb640.png)

**Comment by yishaigalatzer** [comment]
The buttons would show up all the time.

Selected packages will have another global button that applies to all of them.

To the folks that post pictures of other managers: This is a discussion about the short term suggestions for updating the UI, as presented in the wiki and not an overhaul. Please keep the discussion focused.

**Comment by phillip-haydon** [comment]
So this discussion is about bandaid solutions and not making something usable. Ok, my bad.

**Comment by yishaigalatzer** [comment]
@phillip-haydon thanks. The discussion is about pragmatic steps to come up with a short term solution. If you want to help you are more than welcome.

**Comment by daveaglick** [comment]
I obviously can't speak for the original commenters, but I would suggest that the NuGet team consider some of the praise for the UI in alternate package managers within the context of this discussion. I'm guessing it wasn't suggested that the entire NuGet UI be drastically overhauled to look just like one of these other ones, but that there are UI elements which can be adopted or conventions which can be learned from to make the NuGet UI better.

For example, when looking at the UI for Brackets posted by @phillip-haydon, what I see isn't drastically different from what's already being proposed. For example, there's a "tab" section across the top with available and installed sections. The packages are listed underneath the tabs with action buttons to the right of each package as appropriate for that package. Altogether, not that different.

So what could "pragmatic steps to come up with a short term solution" could we extract from this? I see a few:
- I rather like the way Brackets includes author information underneath the package name without having to click or expand for further details. That could help narrow packages down to the "official" ones more quickly at a glance without having to click on each one. Could something like this be added to the VS NuGet API? I think this suggestion certainly falls under the category of smaller short-term changes...
- Another difference is the way the updates tab is handled. In the proposed NuGet UI, the available updates are listed in a separate tab whereas Brackets combines the updates and installed tabs. Instead, Brackets differentiates using a little numerical badge on top of the installed tab to show you how many packages (if any) have updates. I like having the count of updates visible without having to actually open the tab. Perhaps this could be incorporated as a number in parenthesis after the update tab name in the new NuGet UI. Again, this wouldn't necessarily be a massive UI overhaul.

Hopefully you can see how exactly the kind of small, focused, short-term changes you're looking to implement can be derived by examining what other package management UIs do. Often times, a very small and subtle change can make a world of difference towards making an interface more usable. I think it would be a mistake to look at the existing NuGet UI as the only source of inspiration for how things could be improved.

**Comment by csharpfritz** [comment]
An item that should be improved is the appearance of the current installed version number of a package.  Feedback indicates that customers find it difficult to find the currently installed version number

**Comment by yishaigalatzer** [comment]
@daveaglick @phillip-haydon yes this is the spirit.

Specifically to the comments:

> rather like the way Brackets includes author information underneath the package name without having to click or expand for further details. That could help narrow packages down to the "official" ones more quickly at a glance without having to click on each one. Could something like this be added to the VS NuGet API? I think this suggestion certainly falls under the category of smaller short-term changes...

That sounds great. Will incorporate it into our next iteration

> another difference is the way the updates tab is handled. In the proposed NuGet UI, the available updates are listed in a separate tab whereas Brackets combines the updates and installed tabs. Instead, Brackets differentiates using a little numerical badge on top of the installed tab to show you how many packages (if any) have updates. I like having the count of updates visible without having to actually open the tab. Perhaps this could be incorporated as a number in parenthesis after the update tab name in the new NuGet UI. Again, this wouldn't necessarily be a massive UI overhaul.

The idea is that the Browse tab will show packages online, but will still mark the installed packages, so you can uninstall, or update them. Can you please clarify if you have another idea in mind for this?

Count of updates available also sounds like a nice touch, it will probably be lazy calculated because it takes extra network traffic to find out if the packages actually have newer versions or not.

**Comment by kmcginnes** [comment]
@daveaglick Thanks for your comments. I couldn't have put it better myself. My only goal was to provide inspiration for ideas that could be incorporated into the short term.

**Comment by kmcginnes** [comment]
I've mocked up a [semi-functional version](https://github.com/kmcginnes/PoC.NuGetWpf/tree/master) of what I was thinking for the NuGet left side pane.

I think the additions that I've made would be fairly simple to add on to what already exists in NuGet 3.1. If adding the action buttons is the part holding up a release I would suggest replacing the buttons with static text fields with the same information in the same location.

**Added information**
- Download count
- Published date
- Author
- Installed version (in the uninstall button)
- Latest version (in the upgrade/install button)

<img src="https://raw.githubusercontent.com/kmcginnes/PoC.NuGetWpf/master/nuget-left-pane.PNG" width="625" alt="Mockup of NuGet left pane and search">

**Comment by yishaigalatzer** [comment]
@kmcginnes thanks for the effort that looks cool. We where thinking about using icons rather than large buttons, but we should take a second look, this suggestion is very interesting.

**Comment by frankradocaj** [comment]
My main issue with the Nuget UI is the loading/refreshing locks up the screen, (and occasionally I get the "App not responding" message). Can the loading be done in a non-UI thread?

**Comment by yishaigalatzer** [comment]
It is mostly done on a background thread, would help if you can open a separate issue and provide more details of your setup (package sources, project type, packages installed) and location.

Also did you give 3.2 RC a try?

**Comment by gdennie** [comment]
The query language for Nuget is entirely inadequate for the current size of the repository and the evolving naming convention. I suggest a dot delimited naming query language similar to file name filter as in, "FunScript.*.Binding.lib". The meta characters of the language would be as follows:

.     name segment delimiter (dot)
-     match any sequence of name characters within name segment (asterisk)
  ?    match any one name character within name segment (question mark)
  ^    begins an exclusionary name segment criteria - (carat)

Presently, I am finding that if I cannot locate the correct list of characters of the Nuget package name, the GUI console is almost useless.

**Comment by csharpfritz** [comment]
Some feedback has been received that suggests a Refresh button for the package list.  For a local repository, especially a local folder, this would be a valuable addition

**Comment by nkolev92** [comment]
A bunch of things have changed in this area, but there's plenty of still relevant feedback in the thread. 
So keeping it open.

**Comment by donnie-msft** [comment]
Fairly old thread, and for the most part, the UI redesign proposed is implemented. There are many other threads with more recent/relevant feedback, so closing this one.
