### ISSUE TITLE
push command doesnt work with NuGet.exe 3.2.0

### ISSUE THREAD

**Issue by bhuvak** [NuGet/Home#1237]
Basic push command returns 404 with nuget.exe 3.2.0 ( against V2 source).
It happens both with -source command and when the source is specified in the config.

nuget.exe push does not work when the input is **https://www.nuget.org/api/v2/Package**

**Comment by yishaigalatzer** [comment]
@deepakaravindr this sounds like something that should just work. Can you verify and fix if necessary?

**Comment by deepakaravindr** [comment]
Verified that nuget.exe push does not work when the input is https://www.nuget.org/api/v2/Package

PushCommandResource ends up doing a GET request because it treats the input as a package source. However, https://www.nuget.org/api/v2/Package is not a package source and only accepts PUT requests. This is the bug
