### ISSUE TITLE
Password cannot contains double-quote

### ISSUE THREAD

**Issue by emeric-martineau** [NuGet/Home#12429]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version : 6.4.0.123

### Worked before?

I don't know

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Just add source with user and password (using Powershell):
```
.\nuget sources add -name ZZZZZ -source xxxxxxxxx/index.json -username "test-nuget" -password 'azerty"'
```

If change password without double-quote, it works.

If I use -StorePasswordInClearText, password is encrypted (but it's can be normal)

### Verbose Logs

```shell
Nothing return with with `-verbosity`
```

**Comment by zivkan** [comment]
@emeric-martineau if you create a console app that echos `Program.Main(string[] args)`'s `args` back to the console, does your test console app echo back the values you expect?

In the past similar requests have usually turned out to be PowerShell not passing arguments to NuGet (or other .NET apps) in a way that .NET apps can understand, or in other rare cases, customers thinking that cmd.exe's quote handling working differently to how they beleive.

Your bug report doesn't mention what shell you're using. The `.\` suggests it's on Windows, not Mac or Linux, so probably either cmd.exe or PowerShell, but who knows maybe you're using bash or something else still.

**Comment by emeric-martineau** [comment]
Thanks @zivkan for your question. I have updated issue. I use Powershell.

**Comment by zivkan** [comment]
@emeric-martineau you missed the first half of my comment where I asked you try a console app.

When I try this code:

```cs
Console.WriteLine("Number of args: " + args.Length);
for (int i = 0; i < args.Length; i++)
{
    Console.WriteLine($"Arg {i}: " + args[i]);
}
```

and I run this command: `.\echo.exe sources add -name ZZZZZ -source xxxxxxxxx/index.json -username "test-nuget" -password 'azerty"'`, I get this output:

```cs
Number of args: 10
Arg 0: sources
Arg 1: add
Arg 2: -name
Arg 3: ZZZZZ
Arg 4: -source
Arg 5: xxxxxxxxx/index.json
Arg 6: -username
Arg 7: test-nuget
Arg 8: -password
Arg 9: azerty
```

As we can see, the `"` in arg 9 never made it.  Therefore, the problem is that Windows PowerShell (5) doesn't escape quotes the way that most programs, including .NET apps, except.  NuGet.exe can't use a quote in your password if it doesn't get it from the calling shell.

If I try PowerShell (Core,  version 7.3.2), it works.

**Comment by emeric-martineau** [comment]
@zivkan I don't forget you half of comment, let me let install dotnet :)

I have run program and you right, I need add \ before double-quote and it works!

Many thanks for your help

**Comment by zivkan** [comment]
@emeric-martineau sorry if my previous comment came off as rude. I'm rushing to try to get more things finished in the day, not that it's an excuse.

**Comment by emeric-martineau** [comment]
@zivkan don't worry. Your help was very appreciate. 👍
