### ISSUE TITLE
dotnet restore behavior change from 6.0.404 to 6.0.405 in Linux

### ISSUE THREAD

**Issue by jackj-msft** [NuGet/Home#12431]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet SDK 6.0.405

### Worked before?

dotnet SDK 6.0.404

### Impact

I'm unable to use this version

### Repro Steps & Context

Describe the bug
dotnet SDK 6.0.405 will fail the build if the NuGet feed specified in NuGet.config cannot be reached.
The same version on Windows does not experience this behavior.
Older versions of Linux SDK also do not experience this behavior

To Reproduce
Create a new C# project without any PackageReferences
Create NuGet.config with an unreachable feed
Pin dotnet SDK to 6.0.405
Execute dotnet build
Expected:
5. Successful build

Exceptions (if any)
error NU1301: Unable to load the service index for source ...
Failed to restore *csproj

**Comment by nkolev92** [comment]
Hey @jackj-msft 

Quick testing doesn't suggest any differences between 6.0.404 and 6.0.405 of the SDK. 
NuGet didn't change between those 2 versions: https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.3. 

Have you validated that the configurations are the same on your machine? Any other potential differences? 
Is this something you can repro locally?

**Comment by jackj-msft** [comment]
I just tested it and the behavior change was from 6.0.403 to 6.0.405
here is the screenshot.

![image](https://user-images.githubusercontent.com/75868393/218957431-4f19711a-a04f-44d7-bd46-4cbc46be0a0b.png)

**Comment by zivkan** [comment]
@jackj-msft if you try to run `dotnet add package NuGet.Versioning` with the 6.0.404 SDK, does that actually work?

As Nikolche mentioned, the version of NuGet did not change across those SDK versions:
https://github.com/dotnet/sdk/blob/v6.0.402/eng/Version.Details.xml#L124
https://github.com/dotnet/sdk/blob/v6.0.403/eng/Version.Details.xml#L124
https://github.com/dotnet/sdk/blob/v6.0.404/eng/Version.Details.xml#L124
https://github.com/dotnet/sdk/blob/v6.0.405/eng/Version.Details.xml#L124

My guess is that the project you're using only uses packages that are available in the earlier versions of the SDK (either as an "offline" source, or a "fallback folder"), but not the newer SDK. Since NuGet can't find the package(s) locally with the newer SDK, it tries to make HTTP requests which it was not doing with the older SDK. That's why running some kind of command to test if NuGet can make successful HTTP requests with the older SDK is useful.

Note that the .NET SDK can ask NuGet to download some packages that your project does not directly reference. Runtime packages are a common example when publishing, but might happen at restore if the project specifies RuntimeIdentifier(s)
