### ISSUE TITLE
cannot add readme in the .nuspec

### ISSUE THREAD

**Issue by amastrobera** [NuGet/Home#12446]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 5.6.0.6591

### Worked before?

I don't know

### Impact

It's more difficult to complete my work

### Repro Steps & Context

- Create a project (C# Library for .Net Framework 4.8).
- create a nuspec file, and add the `readme` tag [as described ](https://learn.microsoft.com/en-us/nuget/reference/nuspec)
- type `nuget pack`

I described everything in [this issue](https://github.com/amastrobera/geom_sharp/issues/23)

### Verbose Logs

```shell
Attempting to build package from 'GeomSharp.nuspec'.

The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd' has invalid child element 'readme' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'. List of possible elements expected: 'references, copyright, frameworkReferences, repository, requireLicenseAcceptance, licenseUrl, frameworkAssemblies, iconUrl, packageTypes, title, developmentDependency, description, summary, serviceable, tags, dependencies, contentFiles, language, releaseNotes' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'. This validation error occurred in a 'readme' element.
```

**Comment by zivkan** [comment]
@amastrobera the [readme section of the nuspec reference](https://learn.microsoft.com/en-us/nuget/reference/nuspec#readme), which you linked says "Supported with NuGet 5.10.0 preview 2 and above", but in the bug report, you reported using NuGet version 5.6.  Please download a newer version of nuget.exe from https://www.nuget.org/downloads, and try again.

`nuget.exe pack` doesn't support PackageReference, so you would need to investigate if it's possible for you to [migrate to PackageReference](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference), but if you can, then after a one-time effort doing the migration, you can also migrate to SDK style projects (which can target .NET Framework, you don't have to target .NET (Core) or .NET Standard, and then use `dotnet pack`. This way, you're less likely to have NuGet.exe version problems, since if you keep Visual Studio, or the .NET SDK, up to date, then `dotnet` will also contain NuGet updates for new features and bug fixes.
