### ISSUE TITLE
Automatically use Windows proxy settings

### ISSUE THREAD

**Issue by Eli-Black-Work** [NuGet/Home#12444]
### NuGet Product(s) Affected

NuGet.exe

### Current Behavior

When invoked from the command line via the `dotnet` command, NuGet appears to not respect the Windows system proxy settings.

For example, running `dotnet publish` from the command line automatically restores a project's NuGet packages, and the restores happen without respecting the Windows system proxy settings, resulting in errors like `error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.`

### Desired Behavior

I'd like to request that NuGet use the system proxy settings by default.

**Comment by zivkan** [comment]
@Bosch-Eli-Black my understanding of the way that Fiddler (Classic?) works is by configuring itself as the system proxy. When I edit a `csproj` file to use a package that doesn't exist, then run `dotnet restore` or `dotnet publish` while Fiddler is open, I can see in Fiddler's log that it intercepted requests to api.nuget.org, meaning NuGet, in the `dotnet` cli, successfully used the system proxy.

Interestingly, I also got the "unable to load the service index" error when I first tried, but this is because I haven't used Fiddler in multiple years, so the self-signed certificate it used had expired. After using the built in "reset fiddler certificates" feature, restore started working. So, the error message needs to be improved, there should be info about why the service index couldn't be loaded (in my case TLS certificate trust couldn't be established), but once it was set up correctly in Windows, then it Just Worked.

Several web browsers don't use Windows' certificate store, and instead have a different certificate validation store, so your web browser working doesn't give enough information.  If you create a .NET 6 or 7 console app that does something like `await new HttpClient().GetStringAsync("https://api.nuget.org/v3/index.json")`, does it also throw an exception, or does that work? My thinking is that your organisation's certificate used for HTTPS interception has not been correctly trusted  to work for all apps.

**Comment by Eli-Black-Work** [comment]
@zivkan Thanks for the help! 🙂

This is embarrasing, but... `dotnet publish` suddenly started working for me, too.

The first time that I ran `dotnet publish`, it failed with `error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json`. I then tried running `dotnet msbuild -restore`, which worked. After a bunch more experimenting with various commands, I tried running `dotnet publish` again, and now it works!

I'm not sure what happened. Glad that it's working now, though. Thank you again for the help 🙂

**Comment by zivkan** [comment]
@Bosch-Eli-Black NuGet only makes HTTP requests for packages that are not already available locally. If msbuild restore worked, then the packages are available locally (in the global packages folder) and the dotnet cli will no longer need to make HTTP requests for the same packages. But if you don't fix the underlying issue, it's likely that the next time NuGet in the dotnet CLI tries to make a request, that it will fail with the same error.

I know some relevant Windows settings (in particular, TLS ciphers) have different settings for 32bit processes vs 64bit processes, but if you have VS2022 installed, then both the dotnet cli and msbuild should be 64-bit. I don't have an immediate idea why msbuild restore would work, while dotnet restore wouldn't.
