### ISSUE TITLE
[Bug]: CPM fails with NU1008 but none of the package references contain an explicit version

### ISSUE THREAD

**Issue by Youssef1313** [NuGet/Home#12480]
### NuGet Product Used

Other/NA

### Product Version

VS 17.6 P1

### Impact

I'm unable to use this version

### Repro Steps & Context

https://github.com/MartinZikmund/uno-11641-repro

Building in Visual Studio shows:

```
Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items:
 Microsoft.Windows.SDK.BuildTools;Uno.Core.Extensions.Logging.Singleton;Microsoft.WindowsAppSDK;Uno.WinUI;Microsoft.Extensions.Logging.Console.
```

However, none of the `PackageReference`s contain an explicit version.

cc @MartinZikmund

**Comment by erdembayar** [comment]
Yes, I can repro this, looks like regression from 17.4(or 17.5 I don't remember which version was exactly, it did work before VS17.6). The sample project did compile with previous VS version but doesn't compile anymore with VS 17.6 Preview.
![image](https://user-images.githubusercontent.com/8766776/224882464-12350d38-744a-4882-9f5e-d4068d1484ea.png)

cc @jeffkl

**Comment by jeffkl** [comment]
This is caused by a failing design-time build.  In this case, the SDK is logging an error about a missing manifest file.

![image](https://user-images.githubusercontent.com/17556515/225136700-a85b2e1c-d43f-4b46-963b-d608069ed094.png)

This target runs before the targets needed by NuGet and the `PackageVersion` items are not collected.

In your case, you have chosen to place `AndroidManifest.xml` in a custom directory and the SDK defaults to the project directory. The fix is to set the `<AndroidManifest>` property to indicate to the SDK where it is:

```xml
<PropertyGroup>
  <AndroidManifest>Android\AndroidManifest.xml</AndroidManifest>
</PropertyGroup>
```

Setting that fixed the design-time build and restore succeeded for me.


Please see this issue: https://github.com/dotnet/project-system/issues/8318

Related to https://github.com/NuGet/Home/issues/11748

**Comment by erdembayar** [comment]
@jeffkl 
I'm just curious how did you get design time build binlog?

**Comment by Youssef1313** [comment]
@erdembayar It could be by https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022
