### ISSUE TITLE
Allow resolving cousin dependency conflicts at a higher level

### ISSUE THREAD

**Issue by jsteinich** [NuGet/Home#12509]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

Given the following dependencies:

- My Project -> Package A -> Package B -> Package C (>=3.7 && < 3.8)
- My Project -> Package D (>= 3.3) -> Package C (>= 3.3 && < 3.4)
- Package D (3.7) -> Package C (>= 3.7 && < 3.8)

attempting to resolve `My Project` will result in a version conflict for `Package C`.

### Desired Behavior

Allow `My Project` to resolve a newer version of `Package D` which does meet the constraints required by `Package B`.
This would not violate any of the constraints while still choosing the lowest version of dependencies.

### Additional Context

It's possible to workaround this by directly referencing `Package C` in `My Project`; however, that is both an extra step and additional contextual understanding needed when simply trying to upgrade direct dependencies.

**Comment by jebriede** [comment]
It's unclear to me how Package D is related to Package B in the example provided in the description. It appears the example shows Package D being a direct dependency for 'My Project' and Package C is the only dependency Package B has so if I'm understanding the example correctly, the behavior described in Desired Behavior wouldn't apply to this example.

Here's a link to the section in a post on how NuGet resolves dependencies that's related to this scenario: https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution#direct-dependency-wins. Hopefully this will help explain the expected behavior.

**Comment by jsteinich** [comment]
Package B and Package D share a direct dependency, but are otherwise unrelated.

The unexpected piece is holding Package D to a particular version even though it violates other constraints given that the dependency wasn't specified as an exact version. If I had instead specified My Project -> Package D (3.3) the error makes perfect sense. Since the requirement was instead (>= 3.3), my expectation is that a higher version would be chosen such that the other constraints would be satisfied.

Even mentioning an upgrade to Package D in the error message would be an improvement as it currently only mentions picking a version for Package C (which is really just an implementation detail being exposed).

**Comment by jebriede** [comment]
[Team Triage] Thank you @jsteinich for creating the issue. This is currently by design. As a best practice, we expect package authors for .NET to not specify an upper boundary unless there's a really good reason for it such as a breaking change. In turn, NuGet always tries to use the lower version for each dependency that satisfies all the conditions from the dependency graph. Let us know if you have other questions.
