### ISSUE TITLE
Impossible to get Nuget dependency tree

### ISSUE THREAD

**Issue by azerios** [NuGet/Home#12576]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.14

### Impact

None

### Repro Steps & Context

Dear,

I'm using .netcore 6 version 6.0.14 in my project and I wanted to extract the dependency tree of Nuget packages like here : https://stackoverflow.com/questions/44944172/net-core-dependency-tree

Unfortunatly since 3-4 months these changes are not working and export an empty tree.

Is it possible to check if it's not only me who have this issue ?
I can't update to .netcore 7 or 8 because my company only use LTS versions

Regards

**Comment by erdembayar** [comment]
Hi @azerios 

It looks like that one is using some custom target.
We already have dotnet built-in feature for listing dependencies. Please take a look at https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package

Please let me know if it resolves your problem.

**Comment by azerios** [comment]
Hello,

The export format as tree shape/format/design isn't present so it's not clear enough compare to my link.

I can't see all childs/references of each package so if I need to find which packages from my solution has Azure.Identity in their references it's impossible to have here.

Regards

**Comment by erdembayar** [comment]
It looks https://stackoverflow.com/questions/44944172/net-core-dependency-tree is leveraging 
RunResolvePackageDependencies task from msbuild.  It looks there was breaking change with that one: https://learn.microsoft.com/en-us/dotnet/core/compatibility/msbuild#change-description

Since it's `msbuild` feature I believe you need to file issue on https://github.com/dotnet/msbuild

Also we have tracking issue for enabling this feature. https://github.com/NuGet/Home/issues/11553
Please upvote there, we prioritize based on user upvotes and engagements.

**Comment by azerios** [comment]
I applied the workaround and I manage to get my tree as wanted.

Regards
