### ISSUE TITLE
FloatRange throws Argument null exception on previously valid constructor

### ISSUE THREAD

**Issue by maridematte** [NuGet/Home#12618]
### NuGet Product Used

NuGet SDK

### Product Version

6.7.0-preview

### Worked before?

6.6

### Impact

I'm unable to use this version

### Repro Steps & Context

We are using the `FloatRange` in our code [as seen here](https://github.com/dotnet/templating/blob/9ad6c6fc78fbfe50f4327a84a79b0f0641f37bbe/src/Microsoft.TemplateEngine.Edge/Installers/NuGet/NugetApiPackageManager.cs#L212). Before the update we had no issues with this constructor, and later used to check for correct package versions. After the update, this constructor throws a `ArgumentNullException`.

We have a use case on the `dotnet new` CLI command line and some templates are currently (after preview 4) generating incorrectly.

**Comment by jeffkl** [comment]
@zivkan this is caused by https://github.com/NuGet/NuGet.Client/commit/1076013158838e52b5c5b7a1757e2817e5987003#diff-a937a05cc915a23ce829c85775de54814b2429da9cc23b961d8e0af966af0357R59-R62.  

The default constructor calls the overload with a `null` value for `releasePrefix` and the overload throws an `ArgumentNullException` if `IncludePrerelease` is `true` but `releasePrefix` is `null`.  And `IncludePrerelease` is `true` if the user [passes in certain float behaviors](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/FloatRange.cs#L89-L99).

Should we revert or do you have time to fix it?
