### ISSUE TITLE
A way to exempt a project from `GlobalPackageReference` nuget inclusions

### ISSUE THREAD

**Issue by Benjin** [NuGet/Home#12656]
### NuGet Product(s) Involved

MSBuild.exe

### The Elevator Pitch

My repo is using a number of `GlobalPackageReference`s to clean up our projects, but we have a new project that needs to be exempted from that.  I'd like to be able to add a property to exclude _just this project_ from those `GlobalPackageReference`s.

Either complete or specific exclusion would work for my scenario, but I think both would be nice to have available:

`<IncludeGlobalPackageReferences>false</IncludeGlobalPackageReferences> <!-- defaults to true -->`
`<GlobalPackageReference Exclude="Newtonsoft.Json" />`

**Comment by nkolev92** [comment]
Note that GlobalPackageReference is merely MSBuild. 

```
  <ItemGroup Condition="'$(ManagePackageVersionsCentrally)' == 'true' And '$(RestoreEnableGlobalPackageReference)' != 'false'">
``` 

https://github.com/NuGet/NuGet.Client/blob/c4275569eab53147319abe1a2f65282e462db650/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#LL95C78-L95C113

Please note that GlobalPackageReference conditions won't be evaluated for old style csproj projects due to Visual Studio limitations, so to exclude GlobalPackageReference out of those projects you may need to condition a file import, which are the conditions that are evaluated for items in those projects. 

cc @jeffkl

**Comment by Benjin** [comment]
During my attempt to produce a minimal repro, I found that `<GlobalPackageReference Remove="Newtonsoft.Json">` works, so the functionality I'm looking for already exists.

**Comment by tcartwright** [comment]
Where did you place the <GlobalPackageReference Remove="Newtonsoft.Json">? In the project under an ItemGroup? That errors for me.

**Comment by bdukes** [comment]
I was in the scenario of an old non-SDK project that I needed to opt-out of a package, the simplest way ended up being adding a `Directory.Packages.props` to the project folder with `<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>` in it (see [commit](https://github.com/dnnsoftware/Dnn.Platform/pull/7006/changes/62b3f78710d5bca01b13b1a6d7cc479cda60985a)).
