### ISSUE TITLE
Deprecated info will flash for less than one second in the right penal when clicking package “Microsoft.Net.Http” with a non-deprecated version in the package list

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12661]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.7.0.83

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Open VS and create a F# Console Application (.Net Framework 4.8.1) project. 
2. Right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI. 
3. Click “Browse” tab and select the “nuget.org” from Package source drop-down list.
4. Search the package “FSharp.Net.Http” in the filter and click the package in the package list.
5. Install the package “FSharp.Net.Http” and go to the “Installed” tab.
6. Click the package “Microsoft.Net.Http” whose latest version is not a deprecated.

#### Expected:
Deprecated info should not show in the right penal since the latest version is not a deprecated.
#### Actual:
Deprecated info will flash for less than one second in the right penal as below record.
![DeprecatedInfoFlash](https://github.com/NuGet/Home/assets/20632625/00f0913c-cf31-4eb2-b761-62886eaa401f)

#### Notes:
1.Repro rate: 100%.
2.It is not a regression bug since it reproes on 17.5.4 Preview 1.0 [33530.505.d17.5]+ Dev\6.5.0.154.
3.The issue will not repro when clicking the same package “Microsoft.Net.Http” in the "Browse' tab. It only reproes when the package is a transitive package.

**Comment by nkolev92** [comment]
@martinrrm Can you please take a look?

**Comment by martinrrm** [comment]
@nkolev92 Can repro this bug in 6.7.0.17, probably not a recent regression (if it is). What happens is that the view loads the view with information of the installed version and then it selects the latest available.

I'm going to look what is the expected behavior, since it's the installed tab I have the feeling that we always select the installed version.

**Comment by martinrrm** [comment]
The error is weird, transitive packages that end with `0` in this example `2.0.20710` have an Identity with an extra `.0` -> `2.0.20710.0` which is breaking the `SelectedVersion` attribute in the combobox, investigating why is only in the TransitiveDependencies, this also affects non-deprecated packages but since the deprecation message is never appearing is not as visually obvious.
