### ISSUE TITLE
Audit security vulnerabilities without adding nuget.org as package source 

### ISSUE THREAD

**Issue by bitbonk** [NuGet/Home#12698]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

Starting with .NET 8, `dotnet restore` can warn about security vulnerabilities in referenced packages.
[According to the docs](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#audit-for-security-vulnerabilities) this will only work when adding nuget.org as a package source.

> Additionally, to retrieve the known vulnerability dataset, ensure that you have the NuGet.org central registry defined as one of your package sources:

Please make it possible to use the security audit feature of `dotnet restore` without having to add nuget.org as a package source. Nuget.org should not implicitly become a package source but just the source for the known vulnerability dataset.

### Additional Context and Details

The company I work for maintains their own feed which contains a curated list of packages mirrored from nuget.org that are safe/allowed to be use in the company. The direct use of nuget.org as a package source is prohibited.

**Comment by JonDouglas** [comment]
This is currently on our existing roadmap as an enhancement. Thanks for filing it so others can track too.

**Comment by zivkan** [comment]
(please see the next comment as well) Please upvote this comment if it's ok in your environment to use nuget.org as a vulnerability data source, just not a package source. For example, something like:

```xml
<configuration>
  <packageSources>
    <clear />
    <add key="contoso" value="https://pkgs.dev.azure.com/contoso/ITDept/nuget/v3/index.json" />
  </packageSources>
  <vulnerabilityDataSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  <vulnerabilityDataSource>
</configuration>
```

**Comment by zivkan** [comment]
Please upvote this comment if you can't use nuget.org at all (for example it's blocked at the firewall).

In this scenario the package vulnerability data may need to be downloaded locally and NuGet should read it off-disk

**Comment by zivkan** [comment]
The documentation should be updated to make it more clear that it's not technically necessary to use nuget.org as a package source. NuGet will try to get package vulnerability data from any configured source (well, only HTTP(S) sources, implementing NuGet's V3 protocol). Since this is very early days, so far nuget.org is the only package source we're aware of that implement the protocol.

**Comment by bitbonk** [comment]
Sorry for upvoting the comment so late. Using nuget.org solely as a vulnerability source does work in our context.

FYI: We are using the Packages feature of on-premise Azure DevOps Server as the nuget package source. It would indeed be nice if all vulnerability information available on nuget.org would be available there too. It would make it easier to maintain the nuget.config files as we would not have to add `vulnerabilityDataSource` to it.

**Comment by Mrxx99** [comment]
@zivkan 
> (please see the next comment as well) Please upvote this comment if it's ok in your environment to use nuget.org as a vulnerability data source, just not a package source. For example, something like:
> 
> ```xml
> <configuration>
>   <packageSources>
>     <clear />
>     <add key="contoso" value="https://pkgs.dev.azure.com/contoso/ITDept/nuget/v3/index.json" />
>   </packageSources>
>   <vulnerabilityDataSource>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
>   <vulnerabilityDataSource>
> </configuration>
> ```
> 

This would be fine as long as the restore/build will NOT fail when the vulnerabilityDataSource is not found. Scenario here is: Developers would have access to nuget.org (for vulnerability) but build servers don't. So the warnings would only be produced locally for devs, but that would be ok.

**Comment by zivkan** [comment]
@Mrxx99 I can imagine that other developers will want to know when a vulnerability data source is not available, because the absence of vulnerability warnings makes it look like none of the packages that were restored have known vulnerabilities. But if the only vulnerability data source is not available, then NuGet Audit didn't even run. So, this scenario will have warning NU1905. You can elevate it to an error, use `TreatWarningsAsErrors` but list NU1905 in `WarningsNotAsErrors`, or NoWarn it if you like, depending on your individual scenario. For example `<NoWarn Condition=" '$(CI)' == 'true' ">$(NoWarn);NU1905</NoWarn>`.

Also FWIW, in my PR I named the xml element `auditSource`.  That's much shorter and easier to type than `vulnerabilityDataSource`.

**Comment by hickford** [comment]
I think this feature is broken https://github.com/NuGet/Home/issues/14096

My NuGet.config looks like this:

```xml
<configuration>
    <packageSources>
        <clear />
        <add key="hippo" value="https://artifactory.example.com/artifactory/api/nuget/v3/hippo/index.json" />
    </packageSources>
    <auditSources>
        <clear />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    </auditSources>
</configuration>
```

but nuget.exe gives no vulnerability information.
