### ISSUE TITLE
Change nuspec generation when a package project is referencing another package project

### ISSUE THREAD

**Issue by ilya-scale** [NuGet/Home#12703]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe

### Current Behavior

I have PackageA dotnet project and PackageB dotnet project in one solution. PackageB is referencing PackageA (as a project).

When I do run `dotnet pack` what happens now is that the project reference is converted to a package reference in nuspec file like that:

    <dependency id="PackageA" version="<PackageBVersion>" exclude="Build,Analyzers" />

### Desired Behavior

It feels much more natural if the behaviour is changed to:

    <dependency id="PackageA" version="<PackageAVersion>" exclude="Build,Analyzers" />

since PackageB version does really have no direct connection to PackageA.

### Additional Context

If this is planned, it would be at least useful to have a possibility to affect the resulting Package A version number somehow. I have tried adding both Package reference (to specify the version) and the project reference, but that does not work so well. I get errors during restore if I use package.lock.json

**Comment by kartheekp-ms** [comment]
I am unable to reproduce the behavior mentioned in the issue description. I have created a project `ClassLibrary9` with a project reference to `ClassLibrary1` and they both are targeting `net6.0`.

ClassLibrary1.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.0</Version> <!-- Specified version number property -->
  </PropertyGroup>
</Project>
```

ClassLibrary.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

Executed `dotnet pack command on classlibrary9.csproj` which generated `ClassLibrary9.1.0.0.nupkg`

```
dotnet pack .\ClassLibrary9.csproj
MSBuild version 17.7.0-preview-23320-09+d30eef85d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\7.0.400-preview.23322.28\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-suppo
rt-policy [C:\Users\{username}\source\repos\ClassLibrary9\ClassLibrary9\ClassLibrary9.csproj]
  ClassLibrary1 -> C:\Users\{username}\source\repos\ClassLibrary9\ClassLibrary1\bin\Debug\net6.0\ClassLibrary1.dll
  ClassLibrary9 -> C:\Users\{username}\source\repos\ClassLibrary9\ClassLibrary9\bin\Debug\net6.0\ClassLibrary9.dll
  The package ClassLibrary9.1.0.0 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
  Successfully created package 'C:\Users\{username}\source\repos\ClassLibrary9\ClassLibrary9\bin\Debug\ClassLibrary9.1.0.0.nupkg'.
```

The resulting nupkg has the following nuspec content with version `2.0.0` for `ClassLibrary1` dependency.

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>ClassLibrary9</id>
    <version>1.0.0</version>
    <authors>ClassLibrary9</authors>
    <owners></owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework="net6.0">
        <dependency id="ClassLibrary1" version="2.0.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```
Let me know If I missed something.

**Comment by ilya-scale** [comment]
I think you are missing the version on ClassLibrary9, if you e.g. set it to 2.5.0 or 3.0.0 maybe then it will behave this way? I do additionally use dotnet 7 which is probably using another version of nuget behind the scenes?

If that does not work I can try to make a simplified version of my files to reproduce the issue.

**Comment by zivkan** [comment]
@ilya-scale Kartheek's response is correct from my understanding of NuGet's behaviour as well.

The only way I can think of to get the behaviour you described is if you pack with `dotnet pack -p:Version=2.0.0`. However, MSBuild properties defined on the command line are what MSBuild calls global properties, and they will override any properties set in props and targets files. Therefore, I'm not aware of any way for NuGet, using "normal" MSBuild APIs, to get the version of a package reference when there's a Version global property. If you're setting your package version in this way (global/command line property), you'll need to find a different solution.

If you're not packing with a global property explicitly setting the `Version` property, please provide us with a sample, because it's supposed to determine the ProjectReference's version at pack time.

**Comment by ilya-scale** [comment]
@zivkan Thanks for the explanation, you are right and I indeed have the `-p:PackageVersion=$NUGET_VERSION` in my command. I did not think though that it was causing this issue since I thought it only affect my package, but somehow it does affect the reference as well.

Is it expected behavior that it does it like that? I guess having the package version should really only affect the package you are building, not the references?

**Comment by zivkan** [comment]
yes, it's expected. During pack, we use MSBuild to check what referenced project versions are, so that we can put in the correct version in the dependency: https://github.com/NuGet/NuGet.Client/blob/d9293e2655c908e692941337fd7df203e0e96c9e/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L329-L349

This is just how MSBuild works, as per their documentation: https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2022#global-properties. In particular this quote, which applies to how NuGet gets properties from project references:

> Global properties are also forwarded to child projects unless the RemoveProperties attribute of the MSBuild task is used to specify the list of properties not to forward.

**Comment by ilya-scale** [comment]
I see, it is kind of quite unexpected that it behaves this way, but I just need to not send this value explicitly and use the csproj value, thanks for help!

**Comment by erdembayar** [comment]
> I see, it is kind of quite unexpected that it behaves this way, but I just need to not send this value explicitly and use the csproj value, thanks for help!

If I understand correct this issue is resolved. Please feel free to comment or open a new issue if needed.
