### ISSUE TITLE
Package restore failed. Rolling back package changes for 'Flagsmith'.			

### ISSUE THREAD

**Issue by venkateshsoftnet** [NuGet/Home#12701]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 2022

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. I was trying to add Flagsmith nuget package through visual studio (2019) then I received the below error.
**Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Flagsmith 5.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**				

2. I tried to add the same package via another VS (2022) then I received different issue now
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'Flagsmith'.				

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  Flagsmith -> Flagsmith (>= 5.0.1).	Flagsmith	C:\KamernetWeb\proj\NetCore\KamernetAPI\Flagsmith\Flagsmith.csproj

**Comment by kartheekp-ms** [comment]
> I was trying to add Flagsmith nuget package through visual studio (2019) then I received the below error.
Severity Code Description Project File Line Suppression State
Error Could not install package 'Flagsmith 5.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am able to reproduce the same error for a console project targeting `.NET Framework 4.5` both in Visual Studio 2019 and 2022.

> I tried to add the same package via another VS (2022) then I received different issue now.
Error NU1108 Cycle detected.
Flagsmith -> Flagsmith (>= 5.0.1). Flagsmith C:\{username}\proj\NetCore\KamernetAPI\Flagsmith\Flagsmith.csproj

I am able to reproduce the same error for a console project targeting `.NET 6` (net6.0). In this case the error is because project name is same as package name that you are trying to install. I created a new project with the name `ConsoleApp1` targeting `net6.0` and installed the `Flagsmith` package successfully. _Can you please change the project name and try installing the package?_
```
Restoring packages for C:\Users\{username}\source\repos\Flagsmith\ConsoleApp1\ConsoleApp1.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/polly/index.json
  OK https://api.nuget.org/v3-flatcontainer/polly/index.json 117ms
  GET https://api.nuget.org/v3-flatcontainer/polly/7.2.3/polly.7.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/index.json 133ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/6.0.0/microsoft.extensions.logging.abstractions.6.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/polly/7.2.3/polly.7.2.3.nupkg 17ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/6.0.0/microsoft.extensions.logging.abstractions.6.0.0.nupkg 30ms
Installed Polly 7.2.3 from https://api.nuget.org/v3/index.json with content hash DeCY0OFbNdNxsjntr1gTXHJ5pKUwYzp04Er2LLeN3g6pWhffsGuKVfMBLe1lw7x76HrPkLxKEFxBlpRxS2nDEQ==.
Installed Microsoft.Extensions.Logging.Abstractions 6.0.0 from https://api.nuget.org/v3/index.json with content hash /HggWBbTwy8TgebGSX5DBZ24ndhzi93sHUBDvP1IxbZD7FDokYzdAr6+vbWGjw2XAfR2EJ1sfKUotpjHnFWPxA==.
Installing NuGet package Flagsmith 5.0.1.
Writing assets file to disk. Path: C:\Users\{username}\source\repos\Flagsmith\ConsoleApp1\obj\project.assets.json
Successfully installed 'Flagsmith 5.0.1' to ConsoleApp1
Successfully installed 'Microsoft.Extensions.Logging.Abstractions 6.0.0' to ConsoleApp1
Successfully installed 'Newtonsoft.Json 13.0.1' to ConsoleApp1
Successfully installed 'Polly 7.2.3' to ConsoleApp1
Executing nuget actions took 330 ms
Time Elapsed: 00:00:00.9342507
========== Finished ==========
```
