### ISSUE TITLE
NU1004 The project's runtime identifiers have changed - ".NETFramework,Version=v4.8/win-arm64" 

### ISSUE THREAD

**Issue by fowl2** [NuGet/Home#12711]
Not sure if this should be here or [dotnet/runtime](https://github.com/dotnet/runtime) but the error starts with "NU" so I'm starting here :)

Have started receiving this error message building my non-sdk style project:

> NU1004: The project's runtime identifiers have changed from. Project's runtime identifiers: win;win-arm64;win-x64;win-x86, lock file's runtime identifiers win;win-x64;win-x86.The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.

Example project snippet:
``` xml
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{A18391D4-B581-4B3E-9022-0F4ED54FD7C1}</ProjectGuid>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>

```

I was under the understanding that arm64 support was only being added to .Net Framework 4.8.1 (note the extra .1) to avoid this kind of problem.

The workaround is to regenerate the `packages.lock.json` file which adds in  the `".NETFramework,Version=v4.8/win-arm64": {` part. Not sure if this break building the project in older versions of Visual Studio, etc. Regardless it's unexpected and unwanted churn to have a broken build like this.

Nuget Version:  6.6.1+f4f3bb12a1ccbb974bca9b115a7b7291a7d6fb39.f4f3bb12a1ccbb974bca9b115a7b7291a7d6fb39
Platform: Azure DevOpos Hosted Agent 20230620.1.0 (windows-2022)

**Comment by zivkan** [comment]
@fowl2 This is due to Visual Studio's build tools adding `win-arm64`as a default RID: https://github.com/dotnet/NuGet.BuildTasks/pull/156

As you can see from the pull request, they don't contition this to happen only on .NET Framework 4.8.1 or above, it's always added when the `RuntimeIdentifiers` property isn't already set. If you don't agree with this behaviour, you could try creating an issue in that repo (despite the name, the repo is owned by a different team in Microsoft, not the NuGet team, they just named it like that because it reads the file that NuGet writes), but I think you'd have better luck reporting it to developercommunity.visualstudio.com (via Visual Studio's report a problem feature).

Therefore, another mitigation is to set the `RuntimeIdentifiers` in your own project explicitly, so you're not subject to changing defaults.

From NuGet's point of view, NuGet is running as instructed. It's told to restore a few RIDs, including `win-arm64`, and it's also told to restore in locked mode, and the lock file doesn't contain the the arm64 RID. Therefore, sorry if this seems blunt, but it's not a NuGet bug, so I'm closing this here.
