### ISSUE TITLE
SourceLink configured incorrectly for NuGet.*.dll binaries shipping with VS

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#12745]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.6

### Worked before?

not a regression

### Impact

It's more difficult to complete my work

### Repro Steps & Context

For Visual Studio 17.6.5, the NuGet binaries shipping in `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet` aren't working well with SourceLink.

For example, if you consider NuGet.Commands.dll, the pdb Guid is `5c317681-5168-4e3a-983e-6e469ba96795`, and the Pdb path is `D:\a\_work\1\s\artifacts\NuGet.Commands\obj\release\net472\NuGet.Commands.pdb`. 

I am able to download the pdb from symweb NuGet.Commands.pdb/5C31768151684E3A983E6E469BA967951/file.ptr, which redirects to `...\D1568DA8B119BD3DBCCFD3AA34A882C37A72E6ADC9F8005F65C48CD8E41E00\nuget.commands.pdb` (ask me for the full path on Teams)

The pdb is legacy PDB, not a portable PDB. If you open the .pdb in notepad and search for "github", you will only find this piece of Json:
```json
{"documents":{"D:\\a\\_work\\1\\s\\submodules\\NuGet.Build.Localization\\*":"https://raw.githubusercontent.com/NuGet/NuGet.Build.Localization/239d0ae2156f12ffdba272fcb1ea3d2fb9da4e81/*"}}
```

Other document paths are stored in a format such as `D:\a\_work\1\s\src\NuGet.Core\NuGet.Commands\SignCommand\ISignCommandRunner.cs` which can't be used to download the sources from GitHub via SourceLink.

To be able to properly debug into NuGet binaries shipping with VS it is important to have SourceLink configured properly, as well as ideally consider portable Pdbs.

**Comment by erdembayar** [comment]
Comment for team mates, I already contacted offline and verified above pdb informations. Please ask from me for details.

**Comment by KirillOsenkov** [comment]
Interesting finding: NuGet.Versioning.dll seems to be configured correctly. It has two entries (as expected):

```
{"documents":{"D:\\a\\_work\\1\\s\\*":"https://raw.githubusercontent.com/NuGet/NuGet.Client/0fa557836fa35aee7d60776ef0c88176dbcd22ac/*","D:\\a\\_work\\1\\s\\submodules\\NuGet.Build.Localization\\*":"https://raw.githubusercontent.com/NuGet/NuGet.Build.Localization/239d0ae2156f12ffdba272fcb1ea3d2fb9da4e81/*"}}
```

Notice the first entry for regular files `D:\\a\\_work\\1\\s\\*` is present for NuGet.Versioning.dll but is missing for NuGet.Commands.dll.

NuGet.Versioning.dll must be doing something right, and NuGet.Commands.dll must be doing something wrong.

**Comment by erdembayar** [comment]
Since pdb for `NuGet.Versioning.dll` is good, so we need to compare them to find out what is going on.

**Comment by zivkan** [comment]
> To be able to properly debug into NuGet binaries shipping with VS it is important to have SourceLink configured properly, as well as ideally consider portable Pdbs.

Neither ilmerge nor il-repack (the last time I checked) supports portable pdbs, and since nuget.exe is a thing we have to support, using portable pdbs isn't feasible. At least, not without a significant increase in build script complexity, which would take time away from other features and bugs, so I don't see that effort getting prioritized.

**Comment by KirillOsenkov** [comment]
OK, let's keep legacy pdbs, but we still need to fix SourceLink.

**Comment by zivkan** [comment]
FWIW, I figured out the problem is the ilmerge of nuget.exe

https://github.com/NuGet/NuGet.Client/blob/0a6eb8ffcc20f9e7a801044ea1550b72e3309d47/eng/pipelines/templates/Build_and_UnitTest.yml#L143-L148

Because of the localization technology we use, we have to first build the product, then run some localization tool. But since nuget.exe is ilmerged, we can't ilmerge until after the localization satellite assemblies are created. The ilmerge appears to be re-writing all the net472 dlls (that nuget.exe uses, so VS extension net472 binaries are safe, as appear to be netstandard2.0 binaries).

I haven't yet looked at the binlog of the ilmerge target. Just an FYI in case someone else wants to have a look.

**Comment by zivkan** [comment]
@KirillOsenkov @davkean is this still a problem?

I've just spent the last 2 hours investigating, just to discover that NuGet.Protocol.dll in VS17.9 appears to have sourcelink. And when I download all the pdbs from our latest build's artifacts, and I grep for raw.githubusercontent.com, every pdb contains it.

I'm trying to write a program or script that will detect when the pdb is missing sourcelink, so I can make the build fail, but now I'm looking for examples of pdbs with missing sourcelink in order to test the failure.

It appears that I deleted my branch where I validated that sourcelink was missing after ilmerge last year.

**Comment by davkean** [comment]
Look at the internal thread; "NuGet source indexing" from early this week.

**Comment by KirillOsenkov** [comment]
I did update ILRepack to properly support portable and embedded pdbs, and to merge SourceLink entries.

You can use the pdb tool to view SourceLink information:
https://www.nuget.org/packages/pdb/1.0.0
(https://github.com/KirillOsenkov/MetadataTools/tree/main/src/Pdb)

`dotnet tool update -g pdb`

`pdb NuGet.Versioning.dll http://symweb` will download the pdb from symweb, and then `pdb NuGetVersioning.dll` will show whether the pdb has a SourceLink record.

However I'm noticing that the tool has a bug where it doesn't show SourceLink from native pdbs. I'll be fixing that soon.

But to confirm, yes, the latest NuGet.Protocol.pdb does appear to have a SourceLink record.

**Comment by KirillOsenkov** [comment]
I have updated the `pdb` tool to read SourceLink entries from legacy pdbs:
![image](https://github.com/NuGet/Home/assets/679326/9a85dfb1-fb6e-40f3-ba3b-19b08a6f25bf)

I think we can close the issue now.

@davkean if you could forward the internal thread to me I'd be curious to take a look.

**Comment by KirillOsenkov** [comment]
This still appears to be a problem (at least for `NuGet.Commands.dll` and `NuGet.Build.Tasks.dll`). It is painful to debug into NuGet.
