### ISSUE TITLE
NU1905 warning for non-NuGet feed with .NET 8 preview 6 update

### ISSUE THREAD

**Issue by adammorr** [NuGet/Home#12747]
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild version 17.7.0+5785ed5c2

### Worked before?

MSBuild version 17.7.0-preview-23281-03+4ce2ff1f8

### Impact

Other

### Repro Steps & Context

1. Create a .NET project that targets `8.0.100-preview.6.23330.14`
2. Use a package source that isn't NuGet, such as Artifactory
3. Set `<NuGetAudit>true</NuGetAudit>` in your project
4. `dotnet build` which then produces the error

This may be expected but as it's a change in behaviour between .NET 8 preview 5 and preview 6, I thought I would flag it

### Verbose Logs

```
MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
C:\Code\MyProject.csproj : error NU1905: Warning As Error: NuGetAudit is enabled, but no package sources contain known vulner ability data. [C:\Code\MyProject.sln]
  Failed to restore C:\Code\MyProject.csproj (in 393 ms).

Build FAILED.
```

**Comment by erdembayar** [comment]
@adammorr 
Have you looked into mitigation part of https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1905 ?

**Comment by zivkan** [comment]
> This may be expected but as it's a change in behaviour between .NET 8 preview 5 and preview 6, I thought I would flag it

Changes in behaviour within previews are acceptable, especially for brand new features that we couldn't 100% complete by the first insertion (is it better to deliver nothing until a big feature drops in the future, or provide incremental improvements over time?  The industry, for better or worse, overwhelmingly prefers release an MVP and then incremental improvements).

If you don't explicitly enable Audit, then Audit will still run when NuGet can find a vulnerability database, but NU1905 won't warn. This means that people upgrading from .NET 7 SDK to .NET 8 SDK (even if they don't retarget their projects to net8.0) will get the NU1901-NU1904 warnings, and if they also use TreatWarningsAsErrors, it will break their build, but we're documenting it in the docs page, and since this is a security related feature it's been deemed acceptable. We're trying to balance "no surprises" vs "security".

NU1905 was added so that if you enable NuGetAudit, and therefore expect that you'll get vulnerable package reports, you don't have a false sense of security when NuGet's unable to check since it doesn't have a vulnerability database to use. Some people will find it unintuitive if they intentionally reference a package with a known vulnerability and don't get a warning. NU1905 tells them why, and will hopefully reduce our support workload from customers asking us why NuGet didn't detect the known vulnerability, as well as providing us with information that would otherwise be difficult to debug.

Also, as the "warning as error" message suggests, NuGet treats it as a warning, but your project probably uses TreatWarningsAsErrors. So, you have options like NoWarn or WarningsNotAsErrors to stop this warning from causing restore failures.

The company that implements Artifactory, or any other NuGet server, can implement the [Vulnerability Info Resource, part of the NuGet Server API](https://learn.microsoft.com/en-us/nuget/api/vulnerability-info), and we also have additional information/suggestions/ideas in our new [server implementation guide](https://learn.microsoft.com/en-us/nuget/api/implementation-guide#known-vulnerabilities-database-vulnerabilityinfo).

We also have a feature request to provide vulnerability data without using a package source: https://github.com/NuGet/Home/issues/12698  This was called out in the original feature spec, but also needs time to design and implement. We didn't want to prevent customers who use package sources that do implement the VulnerabilityInfo resource from using Audit until this other feature is also implemented.

**Comment by adammorr** [comment]
That all makes sense, thank you both for the explanations and recommendations 👍
