### ISSUE TITLE
NuGet restore ignores build folder of consumed nuget package when buildTransitive folder is also present

### ISSUE THREAD

**Issue by davidnemeti** [NuGet/Home#12804]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

MSBuild version 17.6.3.22601, Visual Studio 2022 Version 17.6.6, nuget.exe 6.0.0.280

### Worked before?

As far as I know, it has never worked.

### Impact

It's more difficult to complete my work

### Issue Description

When building a project which consumes a `MyPackage` nuget package with both `build` and `buildTransitive` folders present, MSBuild does not import the `MyPackage.targets` file from **`build`** folder (or at least its `target`s do not get executed), but imports only the `MyPackage.targets` file from **`buildTransitive`** folder.

### Steps to Reproduce

The **consumer project**'s `Consumer.csproj`:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MyPackage" Version="1.0.0" />
  </ItemGroup>
</Project>
```

The **nuget package**'s `MyPackage.csproj`:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <PackageId>MyPackage</PackageId>
    <Version>1.0.0</Version>
    <Authors>your_name</Authors>
    <Company>your_company</Company>
  </PropertyGroup>
  <ItemGroup>
    <None Include="MyBuild.targets" Pack="true" PackagePath="build/$(PackageId).targets" />
    <None Include="MyBuildTransitive.targets" Pack="true" PackagePath="buildTransitive/$(PackageId).targets" />
  </ItemGroup>
</Project>
```

The **nuget package**'s `MyBuild.targets`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="MyInitBuild">
  <Target Name="MyInitBuild">
    <Message Importance="High" Text="MyInitBuild" />
  </Target>
</Project>
```

The **nuget package**'s `MyBuildTransitive.targets`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="MyInitBuildTransitive">
  <Target Name="MyInitBuildTransitive">
    <Message Importance="High" Text="MyInitBuildTransitive" />
  </Target>
</Project>
```

Note that `MyBuild.targets`'s target (`MyInitBuild`) and `MyBuildTransitive.targets`'s target (`MyInitBuildTransitive`) have different names, so **there is no target name collision** which could cause that only one of these targets are executed.

### Expected Behavior

I expect that both `MyBuild.targets` file and `MyBuildTransitive.targets` file are imported into the consumer project, thus both `MyInitBuild` target and `MyInitBuildTransitive` target are executed, so when building the consumer project the build output has both the `MyInitBuild` message and the `MyInitBuildTransitive` messages (the order does not matter).

So the build output should be either:
```
MyInitBuild
MyInitBuildTransitive
```

or:
```
MyInitBuildTransitive
MyInitBuild
```

### Actual Behavior

It seems that only `MyBuildTransitive.targets` file is imported into the consumer project, or at least only `MyInitBuildTransitive` target is executed, so the build output has only the `MyInitBuildTransitive` message.

### Analysis

The problem seems to be that **`nuget restore`** creates a **`Consumer.csproj.nuget.g.targets`** in `Consumer` project's `out` folder, which only imports `buildTransitive\MyPackage.targets`, but does not import `build\MyPackage.targets`.

Current `Consumer.csproj.nuget.g.targets`:
``` xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)mypackage\1.0.0\buildTransitive\MyPackage.targets" Condition="Exists('$(NuGetPackageRoot)mypackage\1.0.0\buildTransitive\MyPackage.targets')" />
  </ImportGroup>
</Project>
```

`Consumer.csproj.nuget.g.targets` should import both `build\MyPackage.targets` and `buildTransitive\MyPackage.targets`.

Desired `Consumer.csproj.nuget.g.targets`:
``` xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)mypackage\1.0.0\build\MyPackage.targets" Condition="Exists('$(NuGetPackageRoot)mypackage\1.0.0\build\MyPackage.targets')" />
    <Import Project="$(NuGetPackageRoot)mypackage\1.0.0\buildTransitive\MyPackage.targets" Condition="Exists('$(NuGetPackageRoot)mypackage\1.0.0\buildTransitive\MyPackage.targets')" />
  </ImportGroup>
</Project>
```

**Comment by KalleOlaviNiemitalo** [comment]
The wiki page [Allow package authors to define build assets transitive behavior](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior) says:

> `buildTransitive` flag will internally also exclude `build` flag to maintain the consistency across both folders.

which prevents the build logic from being imported twice, if a package author adds identical files to both folders in order to support old versions of NuGet that do not recognize the `buildTransitive` folder.  So the current behaviour may be by design.

If you added `ExcludeAssets="buildTransitive"` to the PackageReference, then perhaps that would allow NuGet to use the `build` asset instead; but I'm not sure whether this would also affect the assets of the packages on which your package depends.

> Note that `MyBuild.targets`'s target (`MyInitBuild`) and `MyBuildTransitive.targets`'s target (`MyInitBuildTransitive`) have different names, so **there is no target name collision** which could cause that only one of these targets are executed.

AFAIK, NuGet does not check whether the file names in the `buildTransitive` folder are the same as in the `build` folder.  Does some documentation say otherwise?

Are you asking for a feature that lets your package detect whether it is referenced directly or transitively?

**Comment by davidnemeti** [comment]
> The wiki page [Allow package authors to define build assets transitive behavior](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior) says:
> 
> > `buildTransitive` flag will internally also exclude `build` flag to maintain the consistency across both folders.

Thanks, although I have read this document, however it seems that I have overlooked that bit of information you just quoted. It is now clear that this behavior is by design.

> which prevents the build logic from being imported twice, if a package author adds identical files to both folders in order to support old versions of NuGet that do not recognize the `buildTransitive` folder. So the current behaviour may be by design.

Indeed, supporting both the old and the new versions of NuGet unfortunately requires ignoring the `build` folder if `buildTransitive` folder is present.

> If you added `ExcludeAssets="buildTransitive"` to the PackageReference, then perhaps that would allow NuGet to use the `build` asset instead; but I'm not sure whether this would also affect the assets of the packages on which your package depends.

Actually, no: if I add `ExcludeAssets="buildTransitive"` to the `PackageReference`, then neither `build\MyPackage.targets` nor `buildTransitive\MyPackage.targets` are imported.

But it would not be suitable for my scenario anyway, because I want to consume both `build\MyPackage.targets` and `buildTransitive\MyPackage.targets`.

> > Note that `MyBuild.targets`'s target (`MyInitBuild`) and `MyBuildTransitive.targets`'s target (`MyInitBuildTransitive`) have different names, so **there is no target name collision** which could cause that only one of these targets are executed.
> 
> AFAIK, NuGet does not check whether the file names in the `buildTransitive` folder are the same as in the `build` folder. Does some documentation say otherwise?

By mentioning that "*there is no target name collision*" I was just emphasizing that seeing only one of the desired messages in the build output was not due to some kind of *target name collision* inside the targets files. I was just referring here to MSBuild's behavior that having two `Target`s (not `.targets` file, but `Target` inside `.targets` file) with the same name causes the latter `Target` hiding the former `Target`. But by looking into the generated `Consumer.csproj.nuget.g.targets` file it is clear that only one of the messages could appear in the build output, since only one of the targets files is imported.

> Are you asking for a feature that lets your package detect whether it is referenced directly or transitively?

In my scenario I have **different** `build\MyPackage.targets` and `buildTransitive\MyPackage.targets` files, and I wanted to achieve that:
- a **direct** consumer of the nuget package would consume **both** `build\MyPackage.targets` and `buildTransitive\MyPackage.targets` files,
- an **indirect** (transitive) consumer of the nuget package would consume **only** `buildTransitive\MyPackage.targets` file.

# Solution proposal

I think there is a solution which makes it possible to support old, legacy versions of NuGet, while also making my advanced scenario possible.

**NuGet restore** should check whether the content of the `build\$(PackageId).targets` file and content of the `buildTransitive\$(PackageId).targets` file inside the nuget package are the same.
- If the contents are the **same** then this is the "**supporting legacy nuget versions**" case, so only `buildTransitive\$(PackageId).targets` (for **direct** and **indirect** consumers) should be imported.
- If the contents are **different** then this is the "**advanced**" case, so both `build\MyPackage.targets` (for **direct** consumers only) and `buildTransitive\MyPackage.targets` (for **direct** and **indirect** consumers) should be imported.

How does that sound?

**Comment by KalleOlaviNiemitalo** [comment]
Comparing the file contents might cause trouble, if the file in build/ imports the file in buildTransitive/ or vice versa; the files won't be identical then, but NuGet should not import both.  I don't remember how MSBuild reacts to a double import of the same file, though.

Might it be safer to configure the behaviour via some new flag in nuspec?  I assume it would not need to be configured per target framework.  OTOH, changing the nuspec XML structure would make such packages harder to produce using older versions of .NET SDK, because of the XML schema validation.

**Comment by KalleOlaviNiemitalo** [comment]
Thinking about alternative solutions:

- Make NuGet generate a per-package MSBuild property or item that indicates whether the dependency is direct or transitive.  The package can then check that and decide what to do.  And if the package detects that the property or item does not exist at all, then it knows that an older version of NuGet is being used and the information is not available.
- Make the package check for `PackageReference` items.  I guess that won't work if `packages.config` is being used instead.  Also, items cannot be referenced in the Condition of an Import (error MSB4099).
- Make the package read the `project.assets.json` file, via the public class NuGet.ProjectModel.LockFileFormat.  That seems to have enough information for distinguishing between direct and transitive dependencies.  But would using this NuGet library risk some kind of assembly version conflict?  Also, reading the file would require a Target, which might be too late for some purposes.

**Comment by nkolev92** [comment]
Team Triage: As pointed out, this is currently by design. 
We don't intend to have NuGet read the content of any of the files within the nupkg and look for differences. NuGet relies on folder conventions for choosing files. 

Allowing different behavior for packages that's installed as transitive vs direct dependency may lead to difficult to predict behavior, which we wouldn't want to support.

**Comment by gavinltomra** [comment]
For the sake of posterity and web searches that find this issue, given the existing behaviour of loading only one of the two files, you can accomplish what you wanted by making one of them import the other; or both could import a third file with shared content.

Having said that, I do think nuget made a different design mistake with this feature: it's been a perennial thorn in my side when migrating projects from classic to PackageReference when everything breaks because the package only provided build and not buildTransitive.  It would have been much more frictionless if (for transitive refs) nuget had loaded buildTransitive or build, whichever found first; this way all ye olde packages would still work but newer packages could choose to block it or provide different content by supplying a transitive file explicitly.  But that ship has probably sailed.
