### ISSUE TITLE
nuget.org package source missing from Visual Studio

### ISSUE THREAD

**Issue by bansalsushant** [NuGet/Home#12809]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

Visual Studio 2022

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Hi,

I am from the MSIX/App Streaming team, and we have built a plugin for Visual Studio.

During testing – we have come across this weird issue that nuget package source has been missing sometimes from Visual Studio. I setup a fresh Visual Studio 2022 community and faced this issue. Someone else also reported the same.

I was able to fix it by manually adding nuget package source but I am not sure if everyone will do that.

I also came across a stackoverflow thread where developers have reported the same issue. [c# - NuGet package sources missing - Stack Overflow](https://stackoverflow.com/questions/69045231/nuget-package-sources-missing)

Is this the expected behaviour? If not, can someone please look into this?

**Comment by donnie-msft** [comment]
Hello, could you confirm whether you have a `<clear/>` in your `<packageSources>` node in your solution's `nuget.config`, if you have one? See https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources

Also, did the VS install create a machine-wide config at `%appdata%\NuGet\NuGet.Config ` described here https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses?

**Comment by bansalsushant** [comment]
Can you tell me how can I check the solution's nuget.config?

VS did create a machine-wide config at %appdata%\NuGet\NuGet.Config. Adding it below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
</configuration>
```

**Comment by donnie-msft** [comment]
> Can you tell me how can I check the solution's nuget.config?

Solution config location is mentioned in the first instruction in the doc I linked: https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

> VS did create a machine-wide config at %appdata%\NuGet\NuGet.Config. Adding it below:

Is this the file that you are saying you added `nuget.org` to, and you think it should have already been there?

**Comment by bansalsushant** [comment]
I am not able to find any solution config at that location.

No - I added it manually using the steps mentioned in the solution of: https://stackoverflow.com/questions/69045231/nuget-package-sources-missing. I did not add it to any file. I don't know if the file existed before or not - but nuget package source was missing in Visual Studio.

I am happy to get on a call and discuss this further.
I want to understand if this is the expected behaviour - if so, we will add some kind of a FAQ in our documentation.

**Comment by donnie-msft** [comment]
If there's no solution config, then the user-level config should apply next. I tried deleting mine, then when running a NuGet Restore (by building a solution in VS), VS automatically recreated this config for me, and it contains `nuget.org`. Could you try this same repro, then share the content of yours? I'm curious if it creates an entirely blank `nuget.config`, or what exactly it's generating.

If you are reliably reproducing this, please use the Report a Problem feature in VS to submit a ticket to us with logs, repro steps, etc., so maybe we can find some way to reproduce as well.

**Comment by bansalsushant** [comment]
I tried deleting my user-level config and it was indeed recreated for me on building the solution. But the same was not happening during first install - until I added nuget manually.

I can tell you the steps that I did (and same was followed by a customer who faced this issue):
1. Install a fresh copy of Visual Studio Community 2022.
2. Create a new project and try to build it -> it won't build and show a nuget dependency error.

**Comment by zivkan** [comment]
As previously discussed in this issue, NuGet will create the user-level config when it doesn't already exist, at the time that NuGet tries to load the file. However, in case a customer already has a customized user-level config file, we do not modify the file when installing VS, VS Code, the .NET SDK, or any other product. It's strictly "create on first read, if it doesn't already exist".

There was a bug in (many years) old versions of NuGet.Configuration.dll that would create the user-level config without nuget.org as a package source. For better or worse, other products embedded this broken version of NuGet.Configuration.dll in their apps, and hence if any of those apps ran before NuGet's official tools, it would create the "bad" config, and then NuGet thinks "oh, this customer is running in a company that forbids accessing nuget.org directly".

We're aware of 2 tools that had this problem, but to the best of our knowledge, both have been fixed:
* Chocolatey
* PowerShell's PowerShellGet (Install-Module)
  *  We only validated the newest build on Windows 11 no longer creates the "bad" nuget.config. I don't know if Windows 10, or other versions of Windows, still ship a version of PowerShellGet that creates the nuget.config without nuget.org.


Obviously, this is not an exhaustive list of all apps that use NuGet.Configuration.  If you search your computer for NuGet.Configuration.dll, you might find other apps with it. If you actually do this, please let us know which other apps ship NuGet.Configuration.dll. We can test ourselves, and then try to contact the software vendor to get it updated.

If you happen to remember what apps you installed/ran BEFORE running VS for the first time on the fresh computer, this will trim down the potential apps that might be creating the nuget.config before NuGet's official tooling does. On the other hand, if you install the .NET SDK first, and run `dotnet nuget list sources` before using Chocolatey, PowerShellGet, or any other tool, then NuGet will create the "correct" nuget.config, and those other tools won't cause problems. This advice mostly helps people who create VM images via scripts/automation.

Otherwise, I'm afraid that this is a `WontFix` issue for us. Pro-actively adding nuget.org to user-level nuget.cofig files that don't have any package source is a no-go, since it would be a security issue for companies that explicitly don't want nuget.org there. I don't have any other ideas, than asking customers to help track down what software created the nuget.config before nuget, then contacting the software vendor and ask them to fix it.

**Comment by bansalsushant** [comment]
Understood. Thanks for the explaination.

Searching for NuGet.Configuration.dll resulted in the following: 
![image](https://github.com/NuGet/Home/assets/15215151/ade9b582-5915-4a83-959c-03c8f058463a)

While this happened on a fresh install of Visual Studio, the desktop is being used for a year so I have tons of apps that I installed prior to Visual Studio and will be tough to pin point the source that caused it.

Basis your explanation, it makes sense that it be 'WontFix' for you. I will add a FAQ in our documentation, and in case we face this issue going forward, I will bump this up. :)

**Comment by donnie-msft** [comment]
Thank you for checking, as it will now help others understand this behavior as well. Let us know if you have further issues!

**Comment by RespectMathias** [comment]
Had the same problem but with enterprise, I ended up manually adding the missing source back in. It was a clean install of windows and Visual Studio 2022 enterprise. Kind of annoying hope it doesn't happen again in the future when you think it's there by default.

Edit: I see the issue now based on zivkans response, it's because I used Install-Module in PowerShell 5.1 before installing Visual Studio.

Note to self: install Visual Studio/SDK first before messing with PowerShell.

**Comment by glopesdev** [comment]
> We only validated the newest build on Windows 11 no longer creates the "bad" nuget.config.

This is still a problem on the default configuration of Windows Sandbox, which ships with PowerShell 5.1 installed by default for some reason. This really should be flagged in an update ideally.
