### ISSUE TITLE
Nuget Command does not update solution level packages

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1281]
@miguelalho

In a large solution, i have nuget restore enabled, which adds the .nuget\ folder to my solution folder. I use a couple of solution level packages that include tools used by the solution or by the build process. These packages, when added to the solution, are referenced in the .nuget\packages.config file.

I'm trying to update a specific package that is referenced in the .nuget\package.config (and therefore NOT referenced by any specific project), with a command line call. It's a package that my team generates with some application artifacts that get added in the final build. Because its added at the solution level, I was trying to run (from my solution folder):

.nuget\Nuget.exe update .nuget\packages.config

This command returns a (localized) message:

Unable to locate project file for 'C:<path to solution>.nuget\packages.config'.

The config file is there, so the param seems to be read correctly. This issue is similar to two that were on the codeplex issues list:

https://nuget.codeplex.com/workitem/3118
https://nuget.codeplex.com/workitem/3848

These are marked as closed, but whatever the fix, it doesn't seem to support this situation.

Also, I tried cloning this repo to run the code in debug, but there are a series of dependencies (namely Nuget.Configuration 3.0.0-beta) that can't be resolved. Any Ideas?

**Comment by deepakaravindr** [comment]
@hubuk referenced this issue in NuGet/Home#783 on Jun 14

NuGet.exe update command does not work for packages.config without a project file. #783

**Comment by yishaigalatzer** [comment]
@miguelalho @bhuvak 

Sorry for the trouble, we moved the bits around a bit (and we plan some more moves in the next months to consolidate repos)

The nuget command line is built from https://github.com/nuget/nuget.packagemanagement

**Comment by yishaigalatzer** [comment]
And we are going to move again in another effort to do more consolidation to https://github.com/nuget/nuget.client later this week

**Comment by darinso** [comment]
I am using nuget with Unity3d. And there is a lot of troubles created because Unity overwrite project file before building and ignore any additional references in it. Moreover Unity reads dll inside specific folder itself and has troubles with same name dlls. So I created nuget.config, packages.config files and write .bat to restore packages (and remove unused targets) in one click. But I cannot update them to a newer version without manualy restoring and updating packages in the VS. All I need is abillity to update package vesions in package.config to the last version. Correct me if I`m wrong, but now there is  no way to update packages without any project file. I will be grateful for any help.

**Comment by harikmenon** [comment]
@darinso : have you considered using project.json? https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

**Comment by darinso** [comment]
Yes, it will help. Thank you!

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
