### ISSUE TITLE
Dependencies listed inaccurately

### ISSUE THREAD

**Issue by mpmarven** [NuGet/Home#12828]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio Version 17.7.1, NPM 6.7.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We recently decided to update several Azure packages and this migration has caused us issues on previous attempts and we ended up rolling back.  

Upon updating these packages we noticed runtime errors such as 
"Could not load file or assembly 'System.Memory, Version=4.0.1.1"

As part of the migration all of our projects had been updated to 4.5.5, so something still had a dependency on 4.5.4.  

It appears as though the culprits are 
Azure.Identity 1.9.0
Azure.Security.KeyVault.Secrets 4.5.0 

However on both the nuget website and the NPM UI in visual studio the dependencies are listed as "System.Memory (>= 4.5.4)".  It appears as though this should actually be == or <= 4.5.4 and not >=.  

I encountered a similar issue with two google packages:
Google.Api.Gax.Grpc 4.4.0 says it has a dependency on "Google.Apis.Auth (>= 1.60.0 && < 2.0.0) but again due to runtime errors I had to drop Google.Apis.Auth back down to 1.60.0 to resolve the errors.  So it seems like this should be == 1.60.0 or <= 1.60.0.

**Comment by kartheekp-ms** [comment]
I think this issue has to be reported individual package authors because they specify dependencies while packing the project. Package authors can follow [guidance](https://learn.microsoft.com/nuget/concepts/package-versioning#version-ranges) while specifying version ranges for package dependencies.

| Package name | source repository URL |
| ------- | ------ |
| Azure.Identity | https://github.com/Azure/azure-sdk-for-net |
| Azure.Security.KeyVault.Secrets | https://github.com/Azure/azure-sdk-for-net |
| Google.Api.Gax.Grpc | https://github.com/googleapis/gax-dotnet |

I found the source repository URL in nuget.org package details view. For e.g., I clicked on green highlighted link to find out the source repository for `Azure.Security.KeyVault.Secrets` package in nuget.org.

![image](https://github.com/NuGet/Home/assets/52756182/bfd7729c-84c2-4e4d-93ba-8e2a321a78e5)

Another option to report about these runtime errors to package authors is to click `Contact Owners` link in nuget.org (see black arrow mark in the above screenshot)

If you think, I have misunderstood something please re-open this issue.
