### ISSUE TITLE
Prerelease version with -<num><text> should not precede -<higher_num>

### ISSUE THREAD

**Issue by emphasis87** [NuGet/Home#12827]
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI

### Current Behavior

Create and publish package versions:
1.0.0-beta.9
1.0.0-beta.11
1.0.0-beta.12 
1.0.0-beta.12a
1.0.0-beta.13
1.0.0-beta.14

Search for the package, the result:
1.0.0-beta.12a
1.0.0-beta.14
1.0.0-beta.13
1.0.0-beta.12
1.0.0-beta.11
1.0.0-beta.9

### Desired Behavior

I would prefer this ordering:
1.0.0-beta.14
1.0.0-beta.13
1.0.0-beta.12a
1.0.0-beta.12
1.0.0-beta.11
1.0.0-beta.9

**Comment by kartheekp-ms** [comment]
@emphasis87 I've spent some time trying to reproduce this behavior using the Visual Studio Package Management UI. However, I was unable to find a package exhibiting the ordering issue you described within the timeframe I tested. To help us narrow down and investigate this further, could you kindly provide the specific package name where you observed this behavior?

**Comment by emphasis87** [comment]
@kartheekp-ms I have created a nuget package Emphasis.ExampleVersioning and pushed it to nuget.org.
https://www.nuget.org/packages/Emphasis.ExampleVersioning/1.0.0-beta.10#versions-body-tab
https://github.com/emphasis87/ExampleVersioning
![nuget-ExampleVersioning](https://github.com/NuGet/Home/assets/20699185/fd224b26-310f-4715-9e13-2af3b5b1c123)
![vs-ExampleVersioning](https://github.com/NuGet/Home/assets/20699185/7f7d907c-b4d1-4a03-a0a1-ec76672b885d)

**Comment by kartheekp-ms** [comment]
Thanks to @zivkan for notifying me offline about the SemVar standard that defines sorting order. 

As per
[Semantic Versioning 2.0.0 guidance](https://semver.org/#spec-item-11), I think the sorting order that the customer noticed is by design.

Given versions: "1.0.0-beta.12a" and "1.0.0-beta.14"

Both versions have the prefix "1.0.0-beta.".
After that prefix, we need to compare the identifiers "12a" and "14".
According to semver:

- Identifiers consisting of only digits are compared numerically.
- Identifiers with letters or hyphens are compared lexically in ASCII sort order.
- Numeric identifiers always have lower precedence than non-numeric identifiers.

The identifier "12a" is a mix of numbers and letters, which makes it a non-numeric identifier. On the other hand, "14" is purely numeric.

Given that non-numeric identifiers have a higher precedence than numeric ones: `1.0.0-beta.12a` is greater than `1.0.0-beta.14`.

I am leaning towards closing this issue as by design.

**Comment by emphasis87** [comment]
I see, that is unfortunate, I still think the behavior is unintuitive, but I understand.

**Comment by zivkan** [comment]
As per above, the SevVer spec is explicit that this should be the sort order.
