### ISSUE TITLE
Ambiguous project name when using PackageID parameter

### ISSUE THREAD

**Issue by CoenraadS** [NuGet/Home#12901]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK:  Version:   7.0.200

### Impact

It's more difficult to complete my work

### Repro Steps & Context

[example.zip](https://github.com/NuGet/Home/files/12702218/example.zip)

In the zip file is a solution with 2 projects

`ProjectC`, which has a ProjectReference to `ProjectD`

Neither projects have `PackageID` defined in their `.csproj` files

When running the command `dotnet pack .\src\ProjectC\ProjectC.csproj -p:PackageID=Example`

The following error is shown `error : Ambiguous project name 'Example'.`

Running the same command without `-p:PackageID=Example` works ok

Removing the reference to `ProjectD` also fixes it, but I don't see anything in `ProjectD` which would cause an ambiguous reference.

### Verbose Logs

[log.txt](https://github.com/NuGet/Home/files/12702289/log.txt)

**Comment by CoenraadS** [comment]
To workaround, I can use `<PackageId>` in my `.csproj` files, and omit it from the CLI. It was just unexpected.

**Comment by jeffkl** [comment]
Unfortunately, setting MSBuild global properties at the command-line has this sort of side effect.  Since they're set globally, they are set for each project that is built.  People hit the same issue when they specify something like `/Property:OutputPath=SomePath`, this sets the `OutputPath` property to the same location for all projects that are built causing issues where two files can collide.

You should only be specifying these properties in each project or to a dynamic value in something like Directory.Build.props.  I'm closing this for now as there isn't much NuGet can do about this particular issue.
