### ISSUE TITLE
Unable to update native packages

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1291]
@iladan

Having a C++ project which is using nuget package CppNative.1.0.0.0.nupkg targeting framework "native". Packages.config looks like:

   package id="CppNative" version="1.0.0.0" targetFramework="Native" 

Runing _nuget.exe update CppNative SolutionName.sln_ 
Result (using nuget.exe of version 2.8.5): 
WARNING: Could not install package 'CppNative 2.0.0.60'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Problem:**
Package is not updated, but removed.

This bug has been moved from https://github.com/NuGet/NuGet.CommandLine/issues/10

**Comment by yishaigalatzer** [comment]
Looks like we need to fix nuget.exe update to recognize that the TFM is "native" or enable a flag to select the TFM when running nuget.exe update.

**Comment by grahamtodd** [comment]
Do we have any idea when this might be addressed?  I was in the midst of trying to migrate our c++ projects across to TeamCity and publishing/consuming nuget packages, and this issue kind of fundamentally breaks things.

**Comment by yishaigalatzer** [comment]
Unfortunately not :( we are locked into many other items. Would gladly take a pr for this

**Comment by grahamtodd** [comment]
Pardon my ignorance.  What is a pr?

**Comment by yishaigalatzer** [comment]
Pull request.

**Comment by forderud** [comment]
I'm also encountering the same problem with NuGet 3.4.2 when attempting to update NuGet dependencies in a C++ project from the command line.

**Comment by Malvineous** [comment]
Just came across this with NuGet 3.4.4.  Trying to update native NuGet packages in a C++ build that has nothing to do with .NET results in:

```
For adding package 'xxx' to project 'myproject.vcxproj' that targets 'net40'.
WARNING: Could not install package 'xxx'. You are trying to install this package into a
  project that targets '.NETFramework,Version=v4.0', but the package does not contain
  any assembly references or content files that are compatible with that framework. For
  more information, contact the package author.
```

Performing the update through Visual Studio works, just not via the command line, so it can't happen automatically on the build server.

The irony is that when people ask how to get NuGet package restore to update packages to the latest version the answer always comes back that package restore isn't meant for this because updated packages might break the build.  When it is explained that it's happening on a build server precisely to check whether the build works with the latest dependency versions, the response then is to run `nuget update` to do this.  Which, due to this bug, doesn't actually work :-P
