### ISSUE TITLE
[NuGet.Versioning] SemanticVersion.HasMetadata should indicate that Metadata is not null when true

### ISSUE THREAD

**Issue by amis92** [NuGet/Home#12949]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Versioning v6.7.0

### Worked before?

no

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. `dotnet new console -f net6.0 -o NugetVersioningHasMetadataRepro`
2. `cd NugetVersioningHasMetadataRepro`
3. `dotnet add package NuGet Nuget.Versioning --version 6.7.0`
4. In `Program.cs` write:
    ```csharp
    var x = NuGet.Versioning.SemanticVersion.Parse("1.0.0");
    var output = x.HasMetadata ? x.Metadata[0..Math.Min(4, x.Metadata.Length)] : string.Empty;
    ```

What I expected:
5. Build with no warnings.

What I got:
5. Observe build warnings on `x.Metadata`: `Program.cs(2,30): warning CS8602: Dereference of a possibly null reference.`

**Comment by amis92** [comment]
Just a really, really small papercut. The PR is already opened.

PS Setting up this project on Windows without Visual Studio to contribute just this small fix was too complicated for me, I had to resort to editing build.props/targets to just run a single test project on a single framework. :/ I understand there's a lot of legacy, but I also know that feedback like that is accounted when prioritizing, so there you go. :)

**Comment by zivkan** [comment]
> The PR is already opened.

woohoo!  🥳 

Also, sorry for missing it. I added all the nullable annotations a few months ago, and it's very slow and time consuming to go through every API in the entire project and annotate everything (plus fix all compiler warnings related to code the compiler thinks might not be null safe).

> PS Setting up this project on Windows without Visual Studio to contribute just this small fix was too complicated for me

What errors were you getting? and what commands were you running? It's not a quick process to set up a new VM (and make sure it doesn't get VS pre-installed) just to test. There's a few things that I can think of that we can't change without making working on NuGet miserable:

1. strong named assemblies

I can't remember if it's *configure.ps1* or *build.ps1*, but one of the two will disable strong name verification for the two strong name keys we use. We don't have access to the private keys, so have no choice but to disable strong name verification, because .NET Framework requires it, and VS runs on .NET Framework, hence we have to do this for local development. Other repos might be able to use PublicSign instead of DelaySign, but unfortunately nuget.exe is ilmerged, and ilmerge doesn't support public sign. Also the docs on PublicSign explicitly say that .NET Framework isn't supported, so the risk-adverse part of me would be scared to use it, even if ilmerge wasn't a problem.

If *configure.ps1* didn't set up the strong name validation exception, then we need to change that, because *build.ps1* will definately look for VS & msbuild. Plus the strong name validation is a once per user-account setting, not something that needs to run every build.

2. VSIX build only works on msbuild

Visual Studio compoents are usually installed by a `.vsix` file, and the VS SDK only runs on .NET Framework, and hence msbuild. However, I would expect that `dotnet build .\nuget-commandline-withtests.slnf` should work. Same for `dotnet build` or `dotnet test` in any of the `test\NuGet.Core.*` directories/projects.  Luckily the vsix project shouldn't be referenced by any of the test projects, so I would have expected `dotnet test` to work for any of our test projects. Well, as of a few months ago. We used to have a bunch of non-SDK style projects, and therefore could only build with msbuild.exe and run tests via our `build/build.proj` file. But now all projects have been converted to SDK style (even if the VS SDK doesn't technically support it), and I think all test projects should be runnable with `dotnet test`.


If it's something other than the above two, we can probably improve it.  I'd love to make it easier to contribute from Linux, but the problems I'm thinking of don't exist when building on Windows.

If *configure.ps* needs msbuild and doesn't work with the dotnet CLI, then that's something we can probably fix, but we need to be aware of the problem first 😁

**Comment by amis92** [comment]
`configure.ps1` tried to disable strong name but it caused UAT/Admin-Privilege request and I do not have Admin access on my windows. No resources to spin up VM as well. :<

**Comment by zivkan** [comment]
Oh, well that's a problem. Disabling strong name validation does require admin access, to write to HKLM registry settings. So unfortunately for you there's really no alternative than to remove .NET Framework as a target if you want to build & test NuGet, which also means that you'd be unable to build & debug our VS extension, should you wish to contribute to it for some reason.
