### ISSUE TITLE
[Bug Bash] The vulnerability InfoBar does not display in the Solution Explorer window when the transitive package is a vulnerable package

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13001]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.9.0.27

### Impact

It bothers me. A fix would be nice

#### Repro Steps:       
1. Create a F# Console App (.NET Core) -- .NET 8.0 project.   
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.   
3. Select the package source: “Nuget.org” in the “Package source:” drop-down box.   
4. Go to the "Browse" tab and search package “Microsoft.AspNet.WebApi.Client”.  
5. Select package version “4.0.30506” and install the package. 
 
#### Expected:        
The InfoBar should display at the top of the Solution Explorer window since the transitive package “Newtonsoft.Json” is a vulnerable package. 

#### Actual:        
The InfoBar doesn’t display at the top of the Solution Explorer window as below: 
![image](https://github.com/NuGet/Home/assets/84695155/a1ae0194-8ebe-4c8e-83db-f11a3ad9171a)

#### Notes:    
1.The repro rate is 100%.  
2.This is not a regression since it is a new feature.

**Comment by zivkan** [comment]
For some additional information, solution explorer & restore are designed to only check transitive packages when `NuGetAuditMode` is set to `all`: https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages#setting-a-security-audit-mode

I don't know if PM UI should honor this property, or if it should always check transitive packages

**Comment by jebriede** [comment]
@zivkan 
> I don't know if PM UI should honor this property, or if it should always check transitive packages

It's by design that the PM UI always shows vulnerability info for transitive dependencies since we always show transitive dependencies, we want to also show details about any vulnerabilities they may have.

**Comment by nkolev92** [comment]
Team Triage: 

This is currently by design. 

* The package manager UI always shows transitive dependencies and the respective vulnerability data.
* Restore will respect the NuGetAuditMode property and only raise warnings for the respective audit mode. We think it's ok that restore & PM UI are disjoint
* Solution Explorer today is populate via the restore data. One could argue that Solution Explorer is more about showing information like the PM UI, and maybe could be showing vulnerability warnings.

We want to leave this issue open and wait for upvotes.

**Comment by CiciLi1** [comment]
This issue is fixed on VS Main\35222.175 + NuGet Client Dev\6.12.0.82. I will close this bug soon.
