### ISSUE TITLE
[Bug Bash] Vulnerability InfoBar won’t show at the top of Solution Explorer window for C# UWP project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13000]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.9.0.27

### Worked before?

Didn't work since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	Create a C# UWP project in VS and open the PM UI of the project.
2.	Open Solution Explorer window in VS.
3.	Go to “Browse” tab and install a vulnerable package (e.g. Newtonsoft.Json -version 12.0.2).
4.	Observe the top of the Solution Explorer window.
#### Expected:
There should be vulnerability InfoBar showing at the top of the Solution Explorer window.
#### Actual:
No vulnerability InfoBar showing at the top of the Solution Explorer window as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/d0b752b2-2dee-4a8f-a520-fb6d7046127b)
#### Note:
1.The repro rate is 100%.  
2.It is not a regression bug since it’s a new feature.

**Comment by jebriede** [comment]
I was able to reproduce this on a UWP (Universal Windows) App. The issue did not repro with a .NET Core Console App.

**Comment by nkolev92** [comment]
The root cause is that UWP projects are not SDK based and as such there's no restore happening after the package installation. The vulnerability bar is raised as response to restore happening. 
We could have the same problem in situations where we have a vulnerability and then we fix it, but the vulnerability bar does not go away. 

On the implementation side, simply listening to the restores done by the PM UI/PMC is probably not enough.
The package installation restores the subset of projects needed for the operation, that is, the project itself in addition to every project that references it. That subset of projects is *not* what restore does, which is restore every project in the solution. 
Instead of "solution has vulnerabilities", internally, we'll likely have to track "project has vulnerabilities" instead. 

This likely has the same root cause as https://github.com/NuGet/Home/issues/12862. 

@martinrrm if think these are equivalent, feel free to duplicate this to the old one.

**Comment by CiciLi1** [comment]
This issue is fixed on VS Main\35222.175 + NuGet Client Dev\6.12.0.82. I will close this bug soon.
