### ISSUE TITLE
FrameworkReducer.GetNearest() reports an error for net60 and net472 ever since version 5.6.0 preview 2

### ISSUE THREAD

**Issue by siegfriedpammer** [NuGet/Home#13038]
### NuGet Product Used

NuGet SDK

### Product Version

5.6.0-preview.2.6489 and later

### Worked before?

5.6.0-preview.1.6483 and earlier

### Impact

I'm unable to use this version

### Repro Steps & Context

I am using the `FrameworkReducer.GetNearest(NuGetFramework framework, IEnumerable<NuGetFramework> possibleFrameworks)` to check whether there is a framework compatible with a chosen target in a list of possible frameworks.

Scenario: Main Project uses .NET 6.0; Library uses .NET 4.7.2 and the main project references the library.

The `FrameworkReducer` instance is created using it's default ctor and uses built-in mappings, no custom overrides.

So for the library, `FrameworkReducer.GetNearest` is called as follows:
(using strings and collection-literals pseudo-syntax for brevity)
`var chosen = reducer.GetNearest("net6.0", [ "net472" ]);`

The expected output would be chosen == "net472", but the result is null; i.e., an error.

Note that, Visual Studio, MSBuild, NuGet and the .NET Runtime are **completely fine with compiling, executing and debugging a net60 program that references a net472 library**.

Problem can also be reproduced here:
https://nugettools.azurewebsites.net/5.6.0-preview.1.6483/get-nearest-framework?project=net60&package=net472 (works as expected)
https://nugettools.azurewebsites.net/5.6.0-preview.2.6489/get-nearest-framework?project=net60&package=net472 (no longer works)

Here is the list of changes between these two versions:

https://github.com/NuGet/NuGet.Client/compare/5.6.0.6483...5.6.0.6489 and from the commit message it seems that this commit broke the algorithm: https://github.com/NuGet/NuGet.Client/commit/162e23520da60ead3868b48b097731b1e405a5e4, however, I am unable to verify or pin-point the cause further, as the commit changes a lot of things all over the place.

Is this a bug or is this expected? Is FrameworkReducer the correct API to solve my problem? Is there some other API I can use to answer the question: "Can framework X be referenced/used by framework Y?"

Thank you for your help!

**Comment by zivkan** [comment]
This is by design. I don't want to write a 1000 word essay explaining the history of these things, but before .NET 5 and "[one .NET](https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/)", the `net` name was for .NET Framework. However, [with .NET 5 and later, this `net` prefix now maps to `.NETCoreApp`, not `.NETFramework`](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#why-is-net-50s-tfi-still-mapped-to-netcoreapp).

Hence no, `net6.0` (`.NETCoreApp,Version=v6.0`) is not compatible with `net48` (`.NETFramework,Version=v4.8`), since the `TargetFrameworkIdentifier` is different (`.NETStandard` is special cased, and has extra rules, but is not the framework being compared in your example). The .NET Framework has APIs that don't exist on .NET (Core), especially for early versions of .NET Core, so it's theoretically possible for a .NET Framework to throw a `MethodNotFoundException` if a .NET (Core) app tries to run it. There are other APIs that do exist in .NET (Core), but always throw `PlatformNotSupportedException`, so similarly, a package might not be compatible.

> Note that, Visual Studio, MSBuild, NuGet and the .NET Runtime are completely fine with compiling, executing and debugging a net60 program that references a net472 library.

Only because of a feature called "[asset target fallback](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#assettargetfallback)", which [can be turned off](https://github.com/dotnet/sdk/blob/3d93fa3762172ba2d77696e3136d803d54861d9c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L180).

The way that NuGet implements this internally is NuGet will first do a package compatibility check with the project's `TargetFramework`, and if that results in the package not being considered compatible, it will try all the `AssetTargetFallback` TFMs one by one, and if any is compatible with the package, [NuGet will raise the NU1701 warning](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701). In other words, `FrameworkReducer` doesn't know anything about Asset Target Fallback. It's something that is implemented by other code.

**Comment by siegfriedpammer** [comment]
Thank you for your detailed answer. Note that I am fully aware of the complicated history of .NET and .NET Standard. I was under the impression that asset target fallback would be handled by `FrameworkReducer`, but guess I was wrong. Would you be able to point me to the code that handles it, so I can try to mimic VS behavior in my application? Thanks!

**Comment by zivkan** [comment]
I wasn't clear in my previous message, sorry. The .NET Standard compatibility should be built-in to `FrameworkReducer`, so you don't need to emulate that. To emulate asset target fallback, you could do something like:

```cs
NuGetFramework bestMatch = frameworkReducer.GetNearest("net6.0", packageTfms);
if (bestMatch is null)
{
  bestMatch = frameworkReducer.GetNearest("net481", packageTfms);
}
```

The bit of NuGet that does the equivalent is in [`LockFileUtils.CreateLockFileTargetLibrary`](https://github.com/NuGet/NuGet.Client/blob/707c46e558b2b027d7ae942028c369e26545f10a/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L58). It starts off by [creating an ordered list of target frameworks to check](https://github.com/NuGet/NuGet.Client/blob/707c46e558b2b027d7ae942028c369e26545f10a/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L78) (the project TFM, followed by asset target fallback TFMs). Then it [iterates that ordered list](https://github.com/NuGet/NuGet.Client/blob/707c46e558b2b027d7ae942028c369e26545f10a/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L84), and [stops on the first TFM where the package has compatible assets](https://github.com/NuGet/NuGet.Client/blob/707c46e558b2b027d7ae942028c369e26545f10a/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L114-L118).

**Comment by siegfriedpammer** [comment]
Thank you very much!
