### ISSUE TITLE
update-package Sequence contains no matching element

### ISSUE THREAD

**Issue by Rand-Random** [NuGet/Home#13069]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

dotnet 8.0.1
Visual Studio 17.8.2

### Worked before?

Yes, prior to Visual Studio 17.8.x

### Impact

I'm unable to use this version

### Repro Steps & Context

No real steps involved all updates through visual studio will bring this error message, and it doesn't mater if I try to update with console or user interface.

### Verbose Logs

```shell
update-package -Project yyyy
Restoring packages for xxx\yyyy.csproj...
  GET https://api.nuget.org/v3-flatcontainer/aaaa/index.json
  GET https://nuget.telerik.com/v3/package/aaaa/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/aaaa/index.json 170ms
  OK https://nuget.telerik.com/v3/package/aaaa/index.json 591ms
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3/vulnerabilities/vulnerability.base.json
  CACHE https://api.nuget.org/v3/vulnerabilities/vulnerability.update.json
update-package : Sequence contains no matching element
At line:1 char:1
+ update-package -Project yyyy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Time Elapsed: 00:00:02.9676439
```

**Comment by zivkan** [comment]
@Rand-Random please use Visual Studio's "report a problem" feature, and please use the ["record your steps feature" as document in step 8 of the docs](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022#trace). This will record a stack trace for the exception, which is greatly help us track down the issue.

**Comment by Rand-Random** [comment]
@zivkan 

Here you can find the report
https://developercommunity.visualstudio.com/t/update-package-Sequence-contains-no-matc/10534009?port=1025&fsid=df7acb17-aaad-47db-9cfc-4b7435c43b0e

Edit:
Note that I did use the user interface while recording and not the console, as I said both produce the same error.

**Comment by zivkan** [comment]
Thank you for providing the recording! 

This appears to be the stack trace where the exception is first thrown:

```text
Name
   ||               + nuget.packagemanagement.ni!NuGet.PackageManagement.NuGetPackageManager+<ExecuteNuGetProjectActionsAsync>d__85.MoveNext()
   ||                + nuget.packagemanagement.ni!NuGetPackageManager.ExecuteNuGetProjectActionsAsync
   ||                 + nuget.packagemanagement.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[NuGet.PackageManagement.NuGetPackageManager+<ExecuteNuGetProjectActionsAsync>d__86](<ExecuteNuGetProjectActionsAsync>d__86 ByRef)
   ||                  + nuget.packagemanagement.ni!NuGet.PackageManagement.NuGetPackageManager+<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
   ||                   + nuget.packagemanagement.ni!NuGetPackageManager.ExecuteNuGetProjectActionsAsync
   ||                    + nuget.packagemanagement.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[NuGet.PackageManagement.NuGetPackageManager+<ExecuteNuGetProjectActionsAsync>d__87](<ExecuteNuGetProjectActionsAsync>d__87 ByRef)
   ||                     + nuget.packagemanagement.ni!NuGet.PackageManagement.NuGetPackageManager+<ExecuteNuGetProjectActionsAsync>d__87.MoveNext()
   ||                      + nuget.packagemanagement.ni!NuGetPackageManager.ExecuteBuildIntegratedProjectActionsAsync
   ||                      |+ nuget.packagemanagement.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[NuGet.PackageManagement.NuGetPackageManager+<ExecuteBuildIntegratedProjectActionsAsync>d__91](<ExecuteBuildIntegratedProjectActionsAsync>d__91 ByRef)
   ||                      | + nuget.packagemanagement.ni!NuGet.PackageManagement.NuGetPackageManager+<ExecuteBuildIntegratedProjectActionsAsync>d__91.MoveNext()
   ||                      |  + system.core.ni!System.Linq.Enumerable.First[System.__Canon](System.Collections.Generic.IEnumerable`1, System.Func`2)
```

Unfortunately, the method [`NuGetPackageManager.ExecuteBuildIntegratedProjectActionsAsync`](https://github.com/NuGet/NuGet.Client/blob/release-6.8.x/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L3214-L3456) is quite long, however there is only [a single call to `.First`](https://github.com/NuGet/NuGet.Client/blob/399af99fa98a10547d201b7c5b5535cdfc5a92d9/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L3291)

This method restores the project with the updated/installed package(s), then checks the result, trying to find the package ids that were modified. It's hard to understand how the project can be restored with a package being installed, but then the package that was installed wasn't part of the restore result.  Well, that's my understanding just reading the code, not debugging it.

So, this bug will need more analysis, time I don't have at the moment.

@Rand-Random if you are somehow able to create a sample project that reproduces the bug, using only packages available on nuget.org  (if you uninstall all private packages, then try to upgrade a package available on nuget.org, does it still happen?), then if you could zip up the project (we don't need any code files, just the csproj, and anything else needed for that csproj to restore) that would help us.

Otherwise, when someone has more time to investigate, hopefully they'll be able to figure out how this error scenario occurred.

**Comment by Rand-Random** [comment]
Thanks for looking into the issue.
I will come back to you, if I find the time to prepare a demo application, for now I manually edited the csproj file with the latest version.

**Comment by zivkan** [comment]
We have a recording with a stack trace showing the exception happening. I think someone should make an effort at reproducing the bug before it gets closed as stale.

**Comment by nkolev92** [comment]
Assigning to hotseat to repro as per https://github.com/NuGet/Home/issues/13069#issuecomment-1869550959

**Comment by Rand-Random** [comment]
So... after some headache I was finally able to replicate the issue, I have attached my solution.
[ConsoleApp159.zip](https://github.com/NuGet/Home/files/14205946/ConsoleApp159.zip)

Steps to replicate are simple
1) open solution
2) build solution
3) manage nuget packages for solution
4) update them all

**Comment by nkolev92** [comment]
Great news! I was able to repro this! Thanks @Rand-Random! This was regressed by the conditional package reference updating work (which this particular project is).

Now I've got even better news, if you download the latest version of Visual Studio, you should be good. 
https://github.com/NuGet/NuGet.Client/commit/ecf0277bb4d48c5c8501189dca4c2126ed4563a5, which is 17.9 has the fix, in particular this line: https://github.com/NuGet/NuGet.Client/blob/b6b8cdd34c91d7bd464bef35fb46631cf8db34cd/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L3222.

**Comment by Rand-Random** [comment]
Can confirm, it is fixed. Thanks.
