### ISSUE TITLE
`FrameworkReducer` does not create same result as `dotnet restore` command line

### ISSUE THREAD

**Issue by lg2de** [NuGet/Home#13064]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Frameworks 6.8.0

### Worked before?

no

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create a project with target framework net8.0-windows
2. Add reference to `Steema.TeeChart.NET` in version 4.2023.11.17
3. `dotnet restore`

The package `Microsoft.WinForms.Designer.SDK` is restored because it is an [indirect dependency of `Steema.TeeChart.NET` for the target framework `net6.0-windows7.0`](https://www.nuget.org/packages/Steema.TeeChart.NET/4.2023.11.17#dependencies-body-tab).

4. Create a console app (I've used target framework `net6.0`, but I think this is not relevant.)
5. Add reference to `NuGet.Protocol` in version `6.8.0` (I'm explicitly using `NuGet.Protocol` and implicitly using `NuGet.Frameworks`.)
6. Run the tests below.

Both tests should succeed, but one fails.
The failing test exactly reproduces the exact package definition of the example `Steema.TeeChart.NET` and which is successful in `dotnet restore`.
The successful tests is slightly different and maybe shows the glitch in the definition of the sample package.

Anyway:
1. Why `dotnet restore` works differently from using `FrameworkReducer` from `NuGet.Frameworks`?
2. Is it correct that the package specifies "net6.0-windows7.0" as dependency target platform?

Failing test is using "net6.0-windows7.0" as dependency target platform:
```cs
[Fact]
public void GetNearest_UsingWindows7_WindowsSpecificTargetUsed()
{
    var frameworkReducer = new FrameworkReducer();
    var projectTargetFramework = NuGetFramework.Parse("net8.0-windows");
    var frameworks = new List<NuGetFramework>
    {
        NuGetFramework.Parse("net6.0"),
        NuGetFramework.Parse("net6.0-windows7.0"),
        NuGetFramework.Parse(".NETFramework,Version=v4.0"),
        NuGetFramework.Parse(".NETFramework,Version=v4.8")
    };
    
    var nearest = frameworkReducer.GetNearest(projectTargetFramework, frameworks);

    nearest!.ToString().Should().Be("net6.0-windows7.0");
}
```

Successful test is using "net6.0-windows" without "7.0":
```cs
[Fact]
public void GetNearest_UsingWindows_WindowsSpecificTargetUsed()
{
    var frameworkReducer = new FrameworkReducer();
    var projectTargetFramework = NuGetFramework.Parse("net8.0-windows");
    var frameworks = new List<NuGetFramework>
    {
        NuGetFramework.Parse("net6.0"),
        NuGetFramework.Parse("net6.0-windows"),
        NuGetFramework.Parse(".NETFramework,Version=v4.0"),
        NuGetFramework.Parse(".NETFramework,Version=v4.8")
    };
    
    var nearest = frameworkReducer.GetNearest(projectTargetFramework, frameworks);

    nearest!.ToString().Should().Be("net6.0-windows");
}
```

**Comment by zivkan** [comment]
NuGet is both an SDK (libraries that can be used in any app), but also a tool (a component of the .NET SDK, Visual Studio, etc). When NuGet is part of the .NET SDK, or Visual Studio, there can be interactions that are not obvious that technically fall outside NuGet's responsibilities.

In this case, from https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#os-versions:

> A TFM without an OS version will be interpreted as the lowest OS version that was supported by the corresponding netX.Y version.

This "lowest OS version" is not known to NuGet, and therefore is not part of `NuGet.Framework.dll`. This allows the .NET SDK, and its workloads, to change the minimum OS version without changing NuGet, or even add/remove supported OSs (for example, ios, maccatlyst, android, etc were not in .NET 6, but were added via MAUI in .NET 7).

If you [debug your MSBuild project](https://msbuildlog.com), you'll see that the .NET SDK sets the platform version before NuGet's restore runs. This is also why `dotnet pack` on a project that has `<TargetFramework>net8.0-windows` will create package file `lib/net8.0-windows7.0/my.dll`, rather than using `net8.0-windows`, as specified in the project file.

If you use `NuGetFramework` to parse `net8.0-windows`, it will result in Windows version 0.0. Since 0.0 is less than 7.0, it is not considered compatible, by design.

If you're going to use NuGet's libraries in your app, and you wish to replicate logic in the .NET SDK, then unfortunately you're also required to replicate the logic, which in this case means determining which OS (windows) version you want to tell FrameworkReducer you want to be compatible with.

**Comment by lg2de** [comment]
Thanks for you explanation. Can you please help with answering the following questions:
1. Is there an API of .NET SDK which makes available the platform decision you have described?
2. Where can I find the mapping between "windows7.0" and the public Windows Version name?

**Comment by zivkan** [comment]
It looks like the .NET SDK is setting the platform version for windows here: https://github.com/dotnet/sdk/blob/79618e76b72b0f3bd8b28a36b3a69b574fe306dd/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets#L32-L35

I don't know about all the MAUI platforms. I'd expect somewhere in the MAUI repo: https://github.com/dotnet/maui

Note that for Windows, it actually maps to the Windows SDK version number (well, the same is true for all platforms, it's the Android SDK version number, or iOS SDK version number), which is disjoint from the versions of Windows that the app can run on. For example, Windows 11 had a version number 10.0.22000 when it was first released. But a package built against the 10.0.22000.194 Windows SDK can still run on Windows 10, (I think using a polyfill when needed? or there are runtime checks to see if an API is available), so a package built against `net8.0-windows10.0.22000.194` doesn't mean it needs Windows version 10.0.22000 to run.

This makes it hard for people trying to use NuGet packages as runtime plugins, but NuGet is designed to be a development time tool, not a runtime plugin tool.
