### ISSUE TITLE
NuGet restore always touched the project.assets.json file even no content is changed when it needs log error messages.

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#13098]
### NuGet Product Used

Other/NA

### Product Version

Visual Studio 17.9

### Worked before?

not sure

### Impact

Other

### Repro Steps & Context

Try to create a project with NuGet package reference to 'Newtonsoft.Json' 12.0.3.

Close/reopen the solution, the project.assets.json file is touched every time, with extra evaluation and design time builds.  Touching the file without any content change would lead the project system to constantly discard project cache state, and repeat the NuGet restore logic.

The restore logic should skip updating the file in this case (as long as the original file matching the end result.)

### Verbose Logs

```shell
in the assets file with this section:

  "logs": [
    {
      "code": "NU1903",
      "level": "Error",
      "message": "Warning As Error: Package 'Newtonsoft.Json' 12.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr",
      "libraryId": "Newtonsoft.Json",
      "targetGraphs": [
        ".NETCoreApp,Version=v3.1"
      ]
    }

it would keep being updated, even the content is not changed.
```

**Comment by lifengl** [comment]
loop in @nkolev92, @davkean

**Comment by nkolev92** [comment]
I can repro this. 

- You need set `TreatWarningsAsErrors` somewhere, because other NU1903 will be a warning, and you won't run into issues since no-op will kick in, so we won't even consider writing.
- This is only an issue when the restore has failed. When a restore has failed, the no-op check is skipped and restore is attempted again. 
- In this case, that restore completes with the same failed result (due to TreatWarningsAsErrors), the equality check doesn't seem to work: https://github.com/NuGet/NuGet.Client/blob/cabdb9886f3bc99c7a342ccc1661d393b14a0d1d/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreResult.cs#L214


If we don't have the failed restore scenario, I tried this by deleting the project.nuget.cache between instances thus skipping no-op, we get to the assets file again and the write does happen, so that confirms that there's an issue in the assets file equality check.

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/tree/dev-nkolev92-readLogsProperly should be the fix. 
I'll add some tests and PR it. Not sure when it'll make it.

**Comment by nkolev92** [comment]
Digging more, this probably needs a bigger change to avoid accidental/future bugs. 

Warnings such as NU1603 do not suffer from this problem, but seems like audit warnings like the one in the example do (which explains why we've not seen this problem before). 

I see that @zivkan sets ProjectPath in https://github.com/NuGet/NuGet.Client/blob/95f6e0c8b7bd627862a08dcf60f43397f42723ca/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/AuditUtility.cs#L169. 

@zivkan Do you remember what problem you were trying to solve with that?

I think our logic could use some cleanup to make sure we don't run into issues with new warnings, because right now it's fragile, and there's no way we could've predicted the impact of setting 1 extra property.

**Comment by zivkan** [comment]
> Do you remember what problem you were trying to solve with that?

I believe it's so that on command line restores, the messages tell you which project the message is relevant to.

Consider a solution restore, if there's a message saying package X has a known vulnerability, you might not know which project it's related to, especially if you're not using CPM. If multiple projects reference the same package, then it's confusing why NuGet repeats the same message multiple times.

By specifying the project for the warning, it's all a lot clearer.

**Comment by nkolev92** [comment]
I'm guessing we'll need to ensure the project path is always set in the collector logger, instead of setting it independently.
