### ISSUE TITLE
.netrc support

### ISSUE THREAD

**Issue by benluelo** [NuGet/Home#13202]
### NuGet Product(s) Involved

NuGet.exe, dotnet.exe

### The Elevator Pitch

Currently, the only way to authenticate with a source requiring plain password credentials is by putting the raw credentials in the nuget.config, which is obviously an issue if these files are stored in source control. It would be convenient if nuget/dotnet would read the .netrc to fetch credentials.

The private source I'm using is GitLab.

**Comment by kartheekp-ms** [comment]
We recently updated our documentation on authenticating with private NuGet feeds in the pull request at [PR #3201](https://github.com/NuGet/docs.microsoft.com-nuget/pull/3201). I believe these changes have not yet been merged into the live version. Could you please review the [consuming packages from authenticated feeds document](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/consuming-packages-authenticated-feeds.md) in the meantime? It outlines various methods for authentication, excluding the use of .netrc file credentials. These alternatives help avoid storing plain text passwords in nuget.config, which is the least preferred option due to security concerns.

**Comment by benluelo** [comment]
Nice, I had no idea about the environment variable option. I did read somewhere that it's possible to tell the nuget.config to read an environment variable (`<add key="ClearTextPassword" value="%NUGET_PASSWORD%" />`), which works fine for my usecase.

**Comment by nkolev92** [comment]
Closing per @kartheekp-ms's response. 

For future addtions, we prefer making as many cross platform solutions as possible.
