### ISSUE TITLE
Visual Studio package manager does not respect "no_proxy" configuration

### ISSUE THREAD

**Issue by kosa-gyula-77** [NuGet/Home#13227]
The Windows proxy credentials dialog always pops up when I try to browse a package source in Visual Studio for which I set `no_proxy` in `C:\Users\me\AppData\Roaming\NuGet\NuGet.Config`:

```
<configuration>
  <config>
    <add key="no_proxy" value="https://artifactory.mycompany.net" />
```

![image](https://github.com/NuGet/Home/assets/20680759/16e9796a-dcd3-45bd-be16-1ce3c37373a6)

The package source

- is hosted by Artifactory
- requires authentication
- `packageSourceCredentials` is set in NuGet.Config using an Identity Token for Artifactory as password.

Windows proxy settings:

- Automatically detect settings OFF
- Use setup script ON
- The script sets DIRECT for *.mycompany.net

Microsoft Visual Studio

- Professional 2022 (64-bit)
- Version 17.8.6

Additional info

- May be related to https://github.com/dotnet/sdk/issues/22942

**Comment by nkolev92** [comment]
Hey @kosa-gyula-77, 

- Were you ever succesful in setting up the nuget proxy bypass? In other words, do any previous versions work?
- What happens when you clear the packages and you try to restore with `msbuild` or nuget.exe restore? 
Does it succeed?

**Comment by SteveJoseph-AIP** [comment]
I'm getting this exact same problem , what is the solution?

**Comment by kosa-gyula-77** [comment]
> I'm getting this exact same problem , what is the solution?

@SteveJoseph-AIP Unfortunately I have not found a solution for the issue yet so I started to use a self-hosted package service other than Artifactory.

**Comment by SteveJoseph-AIP** [comment]
FYI - We got this working by giving my github account admin rights on the private packages.

**Comment by drewid** [comment]
I am having this same issue, and this is REALLY frustrating and has been happening for months.  Not sure since what version.
I am getting prompted with the "Proxy Authentication Required" window even though I have tried the following:

1) have visual studio set to not use a proxy for the package url in nuget.config - for add key="no_proxy"
2) entered in the popup window the password token and checked "remember my password" - does not remember it, gets prompted later
3) have the password token stored as an api key in nuget.config
4) have the password token stored in the nuget.config file as a username and password
5) am logged into Visual Studio with both Azure account and github account (which has admin rights for the package)
6) have even set the authentication to web browser since someone said the windows auth broker doesn't work

**NOTHING WORKS**.  I am about to dramatically expand the scope/reach of using the packages and this is a HORRIBLE and annoying user experience.

There are enough people online with this issue where someone should help further troubleshoot.  I'm happy to help.

**Comment by drewid** [comment]
Unfortunately, it seems that there is confusion under the hood when credential prompts are needed.
The window says "Proxy Authentication Required" but that is misleading.  It seems to use that window **no matter what** type of authentication is needed.

1) If you use packageSourceCredentials with the matching packageSource and ClearTextPassword with token it works.
2) Otherwise, nothing else matters
3) No matter what you put in for Proxy ignore, API key, etc. it does not matter.

When I just did the straight packageSourceCredentials with an appropriate token I'm not getting prompted anymore.

```
    <packageSources>
        <clear />
        <add key="github-xyz" value="https://nuget.pkg.github.com/xyz/index.json" protocolVersion="3" />
    </packageSources>
    <packageSourceCredentials>
        <github-xyz>
            <add key="Username" value="asdf" />
            <add key="ClearTextPassword" value="token" />
        </github-innovengine>
    </packageSourceCredentials>
```

So - net, net - there is 100% a bug it seems where the authentication prompt being used is NOT displaying a correct prompt, and it is misleading

**Comment by DeliaMoulin** [comment]
Hello, I have the same problem and I would like to use your solution in which file you add that : 
 <packageSources>
        <clear />
        <add key="github-xyz" value="https://nuget.pkg.github.com/xyz/index.json" protocolVersion="3" />
    </packageSources>
    <packageSourceCredentials>
        <github-xyz>
            <add key="Username" value="asdf" />
            <add key="ClearTextPassword" value="token" />
        </github-innovengine>
    </packageSourceCredentials>
Thank you !

**Comment by DeliaMoulin** [comment]
Hello I add the same problem in which file do you add you code ? 
```
    <packageSources>
        <clear />
        <add key="github-xyz" value="https://nuget.pkg.github.com/xyz/index.json" protocolVersion="3" />
    </packageSources>
    <packageSourceCredentials>
        <github-xyz>
            <add key="Username" value="asdf" />
            <add key="ClearTextPassword" value="token" />
        </github-innovengine>
    </packageSourceCredentials>
```
I would like to try. 
Thank you !

**Comment by secretwpn** [comment]
This is still an issue in Visual Studio 2022 `17.14.15`and the ticket should be reopened.
Also the workaround suggested by @drewid does not seem to work anymore.

**Comment by rostacik** [comment]
I can report I see the same thing with VS 2022 v17.14.18
