### ISSUE TITLE
SourceRepository.GetResourceAsync should be cancellable.

### ISSUE THREAD

**Issue by Drake53** [NuGet/Home#13234]
### NuGet Product(s) Affected

NuGet SDK

### Current Behavior

Calling `SourceRepository.GetResourceAsync<FindPackageByIdResource>(cancellationToken);` without an internet connection throws FatalProtocolException after a timeout of 5 seconds, even if cancellationToken.IsCancellationRequested is true.

### Desired Behavior

If cancellation is requested before the timeout, the task should cancel early and throw TaskCancelledException instead of FatalProtocolException.

### Additional Context

Using NuGet.Protocol v6.8.0

**Comment by nkolev92** [comment]
Each resource acquisition is done by a provider, so each provider would need to handle this separately (and a lot do).

This probably needs some cancellation token propagation, but the notable thing is that there's no hard rule about how often a cancellation token should be checked. 
It's really when it's convenient/recoverable, and that may not always be within that 5s timeout.

**Comment by zivkan** [comment]
~Note, in fixing this, I made a breaking change in NuGet.Protocol. `SourceRepository.GetResource<T>()` and `SourceRepository.GetResourceAsync<T>()` (the overloads that do not take a cancellation token) have been marked as obsolete. If your project treats warnings as errors, then using these overloads will be treated as errors.  The fix is to pass a cancellation token. Anyone not wanting to implement cancellation can pass in `CancellationToken.None` themselves, making it clear it's a choice on the calling side.~

I forgot our repo uses the Banned API Analyzer, so I just banned usage of the no-CancellationToken APIs within our repo. This means there's no breaking change to NuGet Client SDK customers.
