### ISSUE TITLE
NU3028 NU3037

### ISSUE THREAD

**Issue by totszwai** [NuGet/Home#13252]
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, Other/NA

### Product Version

6.9.1.3

### Impact

I'm unable to use this version

### Repro Steps & Context

On a freshly installed Windows 11 laptop, installed latest Visual Studio 2022, installed latest .NET SDK.
Loaded an old project (from 2 months ago) and tried to restore the NuGet packages, nothing worked!

Ran the command
`dotnet nuget locals --clear all`

Tried to restore again, and same result. This seems to be come kind of common reoccurring bug/issue with NuGet???? 

![image](https://github.com/NuGet/Home/assets/4440365/dcda3fe9-ebf0-47d0-9089-fd4c9c884079)

![image](https://github.com/NuGet/Home/assets/4440365/c3a5d7b1-cef7-46b6-8cdb-7f63e4fdf57a)

```
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.201\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [C:\Program Files\dotnet\sdk]
  8.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by zivkan** [comment]
@totszwai The docs for [NU3037](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3037) and [NU3028](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028) both say that on Windows might have certificate problems the first time, and has a link to [another docs page, on retries](https://learn.microsoft.com/en-us/nuget/reference/signed-package-verification-options#retry-untrusted-root-failures).

Have you tried increasing the retries?

**Comment by totszwai** [comment]
Well, I seem to circumvent the problem by adding the actual `NuGet.Frameworks` package (newer) under `Dependencies`... but I shouldn't need to do that... it did not have such a package before and it was working. What's weirder is that, I didn't even add the package to the UnitTest project, it was added in ONE of the other shared projects....

It is as-if, by downloading a newer NuGet framework would allow Visual Studio to use the newest one available, skipping the expired 5.11.0 one...? Perhaps NuGet could try to update itself if its expired?

![image](https://github.com/NuGet/Home/assets/4440365/29652d92-b222-42be-9b18-10ad970ca1c7)

**Comment by zivkan** [comment]
all the packages are signed by the same nuget.org repository certificate. So, as soon as the root CA certificate is available on your machine to validate any one of the signed packages, then all of them are going to work.

**Comment by totszwai** [comment]
> all the packages are signed by the same nuget.org repository certificate. So, as soon as the root CA certificate is available on your machine to validate any one of the signed packages, then all of them are going to work.

Ok... so I guess there is nothing else on the consumer side to be done... is there some capability/ability for NuGet to update the root CA cert or at least throw a better error message telling the consumer/developer that, they should get (WHERE?) and install the root cert into the trusted store?

Because it doesn't look like the original suggestion of increasing the retries would do any good either.

**Comment by totszwai** [comment]
Guys, what do I do? The problem is happening in other packages.
Which cert do I need to add it to trusted? How can I even find which cert it is being used????

![image](https://github.com/NuGet/Home/assets/4440365/581c03db-f08e-4963-8dea-3731cd59d830)

**Comment by totszwai** [comment]
@zivkan Where can I download this cert manually such that I could add it to the trust store??

Symantec SHA256 TimeStamping Signer - G3

Is not available anywhere... tried to Google it.

![image](https://github.com/NuGet/Home/assets/4440365/a7c598b9-2489-4f9f-bad1-b3e8600dbec9)

**Comment by zivkan** [comment]
First thing I'd do is make sure your computer's clock is the correct time. If your computer thinks it's the wrong year, then certificates that should be trusted may no longer be because it thinks the root CA cert is out of validity (unless there's some other mechanism for expired cert chains to still be trusted, I'm not an expert on X509 cert chains). Although, if this was the case, I suspect there'd be a good chance that web browsing wouldn't work either. But still, it's quick and simple to check.

Otherwise, you can do this:

From your screenshot, the first package listed is System.Security.Cryptography.Openssl version 5.0.0.

So, step 1 I go to https://www.nuget.org/packages/System.Security.Cryptography.OpenSsl/5.0.0 and click the "download package" on the right hand side.

step 2, I on the command line, I do `dotnet nuget verify -v:d system.security.cryptography.openssl.5.0.0.nupkg`.

It will output 4 certificate chains. First the package author's signature, followed by the package author's timestamping service certifacate chain. The 3rd is the repository (counter-)signature, followed by the repository's timestamp service certificate chain.

Your screenshot shows Nuget is complaining about "The repository countersignature validity period has expired". Actually this is ok, because this happens, but the second one "repository countersignature's timestamping certificate is not trusted by the trust provider". So, the repository countersignature timestamping certificate is the 4th on that `dotnet nuget verify` output, and the root CA is the last one in the chain:

```text
trace:             Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
trace:             SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
trace:             Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
trace:             Valid from: 2008-04-02 2:00:00 AM to 2037-12-02 12:59:59 AM
```

So, this is the certificate that I expect to see trusted. Certs usually use SHA1 fingerprinting, so in PowerShell I can do this: `Get-Item Cert:\LocalMachine\Root\3679CA35668772304D30A5FB873B0FA77BB70D54` and it returns me a cert where the subject matches the name that `dotnet nuget verify` had output on the line starting "Subject Name".

However, on Windows apparently this doesn't mean that the certificate data is actually available for chain validation, only that Windows knows that it exists. Windows needs to actually download the certificate, and since the internet can be unreliable sometimes, and it turns out that Windows' internal RPC mechanisms also aren't 100% reliable either, that's why we [added cert validation retries](https://learn.microsoft.com/en-us/nuget/reference/signed-package-verification-options#retry-untrusted-root-failures), as previously mentioned.

However, if the retries didn't help, then it's a Windows configuration issue, and being on the NuGet team, I'm not an expert on Windows system administration. While Microsoft's developer tools division talk directly to customers, as I am now, getting a hold of people in the Windows division is not so easy. If your company pays for Microsoft premium support, you could file a ticket through your official support representative.

Otherwise, I'd suggest just doing "normal" problem identification.  If you tried the same powershell `Get-Item cert:...` and it didn't return you a cert, I did a quick web search "windows reset trusted certificates" and it showed me results that look like it might work. You could ask your company's helpdesk if they use Windows Group Policy to remove trust for specific certificate. Both of the package's timestamp certs were signed by a Symantec certificate, and I think there was some controversy about symantec certificates a while ago. Perhaps an over-eager domain admin/security person is distrusting all symantec certificates in your company's managed computer.

However, if Windows knows about the cert (it's in the cert store), then you can try using Wireshark to monitor network activity when you run `dotnet nuget verify` or any other action that causes these signed package verification failures. I suggest Wireshark, because I don't know if Windows is downloading these certificates over HTTP, or some other TCP or UDP protocol. Honestly, there's a really good chance that it's HTTP, otherwise companies that block all traffic at the firewall, except for their HTTP proxy, wouldn't be able to download the certificates. In this case you can probably use Fiddler, or some other HTTP monitoring tool, and validate if you can see whatever HTTP request Windows is making to try to download the certificate, and you might get more information about why the download is failing.

Finally, I'm out of ideas. NuGet uses .NET (and in some scenarios P/Invokes some win32 APIs) to do certificate validation. But ultimately it's up to Windows to 1. know which root certificates should be trusted and 2. validate the certificate chains NuGet provides when we call the APIs. We have so few customers complain about this not working (since we added the retries), that I'm not aware of any further investigations, so I don't know what else to suggest, or know anyone else who might have more insight. Windows is supposed to trust the root CA certificate, and we don't work in the Windows division. We just call APIs like any developer in the world, working at any company, can.

**Comment by totszwai** [comment]
The cert isn't even there in the certificate store? This is a brand-new Windows 11 laptop (it was reset recently, ~1 month) with the latest update.

![image](https://github.com/NuGet/Home/assets/4440365/ede9533c-8c1c-4f64-8e2c-f59b533932fe)

That cert is missing.

**Comment by zivkan** [comment]
Do any of these suggestions help? https://www.bing.com/search?pglt=2083&q=reset+windows+trusted+certificates&cvid=1d770824a8ec4c69aee2843fa567345e&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQ6QcYQDIGCAIQABhAMgYIAxAAGEAyBggEEAAYQDIGCAUQABhAMgYIBhAAGEAyBggHEAAYQDIGCAgQABhAMgcICRBFGPxV0gEINTU5OGowajGoAgCwAgA&FORM=ANNAB1&PC=U531

**Comment by totszwai** [comment]
Hello,

I manually download and installed the certificate and is ok now.
https://www.tbs-certificates.co.uk/FAQ/en/verisign-universal-root.html

Thank you.

**Comment by pjmorel** [comment]
Hello. Had the same issues with an empty Azure Functions project, tried to download and install the certicate, but it did not work unfortunately. Any ideas?

**Comment by DamirLisak** [comment]
I encountered the same problem with WINE Linux. Since I want to compile .NET projects that require Microsoft.NET.Sdk.WindowsDesktop on Linux, I run dotnet build with Wine cmd. I've experimented with all environment variables, and none are used by msbuild.
(CERT_TRUST_REVOCATION_STATUS_UNKNOWN, NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY, DOTNET_NUGET_SIGNATURE_VERIFICATION, NUGET_CERT_REVOCATION_MODE, NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY)
Why is this even described in the documentation as working, but it's not implemented at all?
Or has anyone found a solution in the meantime how to deactivate this verification?
(The other way, copying Microsoft.NET.Sdk.WindowsDesktop into the Linux SDK directory, unfortunately only works as long as no XAML needs to be compiled, because the PresentationBuildTasks.dll links system DLLs from Windows unmanaged.)

**Comment by zivkan** [comment]
@DamirLisak my guess is that under Wine, the trusted root certificates would be the underlying hosts's certificates, not Microsoft's trusted certificates. The difference is that Microsoft's cert bundle keeps expired root CAs, so that code signing validation can still validate that the root CA was trusted at the time that the binary was signed (assuming the signature also includes a trusted timestamp server signature), even if the root CA certificates are now expired. Meanwhile Apple and Mozilla appear to only care about HTTPS certificates, not code signing, and will remove all root CA certs that have expired.  This makes it impossible to validate code signing that happened when those certificates were valid.

In the .NET SDK, we solve this by [shipping Microsoft's cert bundles in the SDK itself](https://github.com/dotnet/sdk/tree/main/src/Layout/redist/trustedroots) on Linux and Mac, and NuGet's package validation loads these bundles explicitly.  But if wine tricks NuGet into thinking it's running on Windows rather than Linux, then we assume that the win32 APIs to validate code signing certificates will work.  You could try getting your Linux host to trust the same certs as these two bundles, and then see if NuGet in WINE will validate the package signatures.

[Earlier in this issue](https://github.com/NuGet/Home/issues/13252#issuecomment-1979210267), and [also in our wki](https://github.com/NuGet/Home/wiki/Signing-certificate-is-not-trusted-by-the-trust-provider), I showed examples on how to determine what the certificate chain for a signed package is, so you can figure out which certificate you need to look for in your operating system's trusted CA list. Again, on Linux and Mac, the .NET SDK will ship Microsoft's cert bundle, so just make sure you're using an up to date .NET SDK. On Windows, NuGet expects the operating system to trust expired trusted CA certificates.

> Why is this even described in the documentation as working, but it's not implemented at all?

The first identifer you listed is a win32 error code, not a configuration. The other 3 all have NUGET somewhere in the name, and since [NuGet is open source](https://github.com/NuGet/NuGet.Client), it's easy to do a code search and see that all of them are being used.  So I don't understand your "but it's not implemeneted at all" statement. The source code shows that it is.

> Or has anyone found a solution in the meantime how to deactivate this verification?

The only way to disable signed package validation is with the `DOTNET_NUGET_SIGNATURE_VERIFICATION` environment variable, as documented at https://learn.microsoft.com/en-us/dotnet/core/tools/nuget-signed-package-verification.  But it only works on Linux and Mac, as documented. If NuGet thinks its running on Windows because of WINE, NuGet expects that the .NET APIs (and the underlying win32 APIs) will have Microsoft's full trusted CA list, and will always do signed package validation.

**Comment by DamirLisak** [comment]
@zivkan thanks for the reply! I'll continue to try out your suggestion.
Now when you say it and read it again, I see that you can't disable DOTNET_NUGET_SIGNATURE_VERIFICATION on Windows.
But what's the reason why you can't disable this certificate validation on Windows, but only on Linux and Mac? (Anyone who wants to enable this switch in Windows is knowingly accepting a potential risk.)

**Comment by zivkan** [comment]
It was designed and implemented before I joined the team, so I don't know. Here are the original public specs for the whole signed package feature: https://github.com/NuGet/Home/wiki/Package-signing

I don't know if any of the linked documents addresses your question about why it can't be disabled while accepting the risk of tampered packages.

**Comment by enderprism** [comment]
I'm a Linux (EndeavourOS, Arch-based) user trying to contribute to a .NET application that relies on Windows APIs (WinForms specifically, it seems). The application is called [TiXL](https://github.com/tixl3d/tixl/).
It turns out that enabling the `EnableWindowsTargeting` flag and using the .NET build from Microsoft (instead of my distro's packages, as it patches out some modules) allows it to compile correctly without using WINE. However, it can't run because the APIs don't exist on Linux.
So I end up running this application with the `dotnet` CLI through WINE, and it works fine, with one exception: this application also uses the `dotnet` CLI to compile code on the fly while it's running.
I'm running into the same issue with the `dotnet` CLI through WINE spitting out `NU3028` and `NU3037` errors.
I'll try trusting Microsoft's cert bundle and see if that works.

**Comment by enderprism** [comment]
Trusting Microsoft's cert bundle got rid of all `NU3028` and `NU3037` errors!

**Comment by DamirLisak** [comment]
@enderprism, since your project is netcore you can build it with VS Code on Linux if you copy the necessary windows dependent sdk packages from the wine directory to the linux dotnet packs folder where all other packs are located. Use [this guide here](https://github.com/iplus-framework/iPlus-Examples/blob/main/Misc/Linux-Setup-Guide/07-developer-tools.md#building-wpf-project-on-linux-with-vs-code). So you can compile it with vs code on linux.
VS Code in wine you only need for legacy netframework 4.8 project. To avoid the nuget certificate problem in wine, you can share your nuget packages directory from linux with wine. You also can open netframework 4.8 projects (you have to switch of modern dotnet and disable C# Dev Kit in the .vscode/settings.json of your solution. dotnet restore should download the right packages. What you can't is to compile it in Linux because netframework 4.8 has a lot of dependencies which are related to windows. Have good a good luck!

**Comment by DamirLisak** [comment]
@enderprism Another idea would be to switch to the V2 NuGet API. Perhaps that will work. With V3, a lot of validations were added. For example, you'll encounter download problems with NuGet and workloads in Visual Studio if you're running a Windows virtual machine via KVM and it's located on its own network (NAT). The reduced MTU size, DNS timestamps, etc., have a huge impact on whether you can download NuGet packages or not.

**Comment by enderprism** [comment]
as i said, trusting the certificate bundle on my host linux system fixed the issue in WINE.

**Comment by heroes3lover** [comment]
> Hello,
> 
> I manually download and installed the certificate and is ok now. https://www.tbs-certificates.co.uk/FAQ/en/verisign-universal-root.html
> 
> Thank you.

thank you, you save my life.
