### ISSUE TITLE
[.NET 9 Preview 3] no-op restore is no longer a no-op

### ISSUE THREAD

**Issue by jonathanpeppers** [NuGet/Home#13269]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 9.0.100-preview.3.24126.2

### Worked before?

.NET SDK 9.0.100-preview.2.24122.3

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We discovered here a test failure: https://github.com/xamarin/xamarin-android/pull/8763

The underlying cause appears to be:
```
The restore inputs for 'UnnamedProject' have changed. Continuing restore.
```

This was an incremental build with no changes to the project.

Digging deeper, the offending build seems to have some NuGet sources listed twice:
```diff
++https://api.nuget.org/v3/index.json
++https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json
https://api.nuget.org/v3/index.json
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json
```
So there must be something that adds extra feeds, making the no-op restore skip? so it runs a full restore?

### Verbose Logs

Here are two `.binlog` files, `install2.binlog` restores as expected, `install3.binlog` does not:
[nuget-noop.zip](https://github.com/NuGet/Home/files/14421956/nuget-noop.zip)

**Comment by nkolev92** [comment]
Hey @jonathanpeppers, 

Where do you see that delta? 

The thing that determines whether a restore should happen is a nuget.dgspec.json file in the obj folder, before and after. 
If it's easy for you to upload that, it would really speed up our investigation. 

If you can't, one of us can try to run the test locally.

**Comment by jonathanpeppers** [comment]
We have just one `nuget.dgspec.json` at the end as an artifact, let me see if I can grab a copy at different stages of the test.

**Comment by jonathanpeppers** [comment]
Yeah, I think I see a difference in the files: [obj.zip](https://github.com/NuGet/Home/files/14426314/obj.zip)

Comparing the two folders with WinMerge:

![image](https://github.com/NuGet/Home/assets/840039/ffdf8e4a-37e8-4a99-bbd9-022a51cc2804)

The problem also occurred here, maybe the diff is smaller:
* https://github.com/xamarin/xamarin-android/pull/8767
* https://github.com/dotnet/installer/compare/0a73f814e1...e416bb08d1
* https://github.com/nuget/nuget.client/compare/8b658e2eee6391936887b9fd1b39f7918d16a9cb...39c4f37d4baa00ee0b815fb394de7d51a58b17ab

**Comment by nkolev92** [comment]
Thanks @jonathanpeppers 

That's really, really helpful!

**Comment by nkolev92** [comment]
I was unable to figure out where the regression is, but I did make some progress.

GetRestoreSettingsTask seems to return *different* values for the sources, but the inputs are the same. 
This is happening for Library1 only.

I was able to reproduce a duplicate nuget.config, but both with 6.9 and 6.10 of NuGet (so not a regression within the commits above). To reproduce this, I just added the same source with different ids in the nuget.config.
Unfortunately, I don't understand why it'd differ from run to run.

I attempted to debug the test, but I was unable to, since it's requiring a commercial build, but I'm having a tough time making progress on that.

The contributing instructions seem to be outdated: https://github.com/xamarin/xamarin-android/blob/main/Documentation/building/windows/instructions.md#running-specific-nunit-tests.

I originally thought it'd be something like: https://github.com/NuGet/NuGet.Client/pull/5620, but I'm still not sure why the same inputs would change the output.

@jonathanpeppers Any advice you can provide here? 
I was hoping to get a repro disconnected from the test infrastructure with the SDK, or at least something I can try to debug within the test.

Unfortunately the binlogs are not enough to figure out where the regression is.

**Comment by jonathanpeppers** [comment]
@nkolev92 it doesn't feel like the problem here would be specific to Android, but maybe just our `NuGet.config` usage?

Let me see if I can make a simpler repro with two class libraries and a console app.

**Comment by zivkan** [comment]
A few months ago I refactored `PackageSourceProvider`, in order to make it easier to implement `auditSources`. The previous `PackageSourceProvider` code had a specific API to deduplicate sources based on source URL (value). I thought I couldn't find evidence of it actually being used, so I changed it to only deduplicate on source key. Maybe this is what's happening here.

I'm very busy with other work, that is well behind "schedule", so I haven't tried myself, but try a repro where nuget.config has two package sources with different keys, but the same url.  You can also check `dotnet nuget list source` in the android repo, and see if it lists different sources with the same url/value.

**Comment by nkolev92** [comment]
I checked source deduping with 6.9 only, since I assumed that any regressions would've been introduced in 6.10, but may we already have that problem in 6.9. 

I'll check against 6.8.

**Comment by nkolev92** [comment]
@zivkan 

6.8 doesn't have any duplicate sources. 

So https://github.com/NuGet/NuGet.Client/commit/1942c17866695ae1175ec3d8b42a6b41bcd6a9c9#diff-93482a8631efd30f5df833baa903bcf342fb99a2e93cf9a3dea6a672b44d3a61L81 definitely introduced a problem. 

I'm still not sure why this would lead to a break in no-op though. So while that needs fixed, there's probably something else going on here.

**Comment by zivkan** [comment]
It's the end of my day, so I'm not going to investigate in the next few hours, but to test the hypothesis that my change broke something, you can create a console app that references NuGet.Configuration, use Settings.LoadDefaultFrom("path to android repo"), then use `PackageSourceProvider.LoadPackageSources`, and write the list to console.  Then change the NuGet.Configuration package version to the previous GA version and check again.

I think this should be an "easy" way to validate, and if it does show a difference, as long as your debugger is using microsoft's symbol server, you should be able to debug into NuGet's source.

**Comment by nkolev92** [comment]
> It's the end of my day, so I'm not going to investigate in the next few hours, but to test the hypothesis that my change broke something, you can create a console app that references NuGet.Configuration, use Settings.LoadDefaultFrom("path to android repo"), then use `PackageSourceProvider.LoadPackageSources`, and write the list to console. Then change the NuGet.Configuration package version to the previous GA version and check again.
> 
> I think this should be an "easy" way to validate, and if it does show a difference, as long as your debugger is using microsoft's symbol server, you should be able to debug into NuGet's source.

That's basically what I did, and meant to say in https://github.com/NuGet/Home/issues/13269#issuecomment-1969579821. 

For the same set of configs, the API now returns more sources than it did in 6.8.

**Comment by jonathanpeppers** [comment]
@nkolev92 did you see a duplicate source in our `NuGet.config`? I could fix that in our repo for now.

This happened during an MSBuild integration test, perhaps it generates a `NuGet.config` with a duplicate:

* https://github.com/xamarin/xamarin-android/blob/0d489b157453f19bb2d1f9567e30d2b40de1bf9d/NuGet.config#L10
* https://github.com/xamarin/xamarin-android/blob/0d489b157453f19bb2d1f9567e30d2b40de1bf9d/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs#L420-L421

**Comment by jonathanpeppers** [comment]
Ok, I found:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
...
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
...
    <add key="testsource2" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by nkolev92** [comment]
We're making good progress here!

One thing I'm having trouble understand is why the restore would change within the same version. 

This feels like one of those that'd be consistent within the same version, but buggy when comparing say 6.9 and 6.10 of NuGet. 

basically, the change we've confirmed may have regressed something, I'm not confident that's all.

**Comment by jonathanpeppers** [comment]
Trying this for now: https://github.com/xamarin/xamarin-android/pull/8772

**Comment by nkolev92** [comment]
After more investigation, I think https://github.com/NuGet/NuGet.Client/pull/5666 is sufficient. 

```cs

        [Fact]
        public void LoadPackageSources_DeduplicatesBasedOnValue()
        {
            // Arrange
            using TestDirectory testDirectory = TestDirectory.Create();

            const string sourceUrl = "https://contoso.test/nuget/index.json";
            const string contents = $@"<configuration>
  <packageSources>
    <add key=""s1"" value=""{sourceUrl}"" />
    <add key=""s2"" value=""{sourceUrl}"" />
  </packageSources>
</configuration>
";
            var path = Path.Combine(testDirectory.Path, Settings.DefaultSettingsFileName);
            File.WriteAllText(path, contents);

            Settings settings = new Settings(testDirectory.Path);

            // Act
            List<PackageSource> sources = LoadPackageSources(settings);

            // Assert
            sources.Should().HaveCount(1);
        }
```

Returns 2 in both the commit before Andy's change and latest dev.
