### ISSUE TITLE
"Duplicate frameworks found" when restoring using static graph

### ISSUE THREAD

**Issue by snorrk** [NuGet/Home#13312]
### NuGet Product Used

MSBuild.exe

### Product Version

17.9

### Worked before?

Unknown

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Restoring a minimal Microsoft.Net.Sdk project succeeds when RestoreUseStaticGraphEvaluation is false but fails with `Duplicate frameworks found: 'net40, net40'` when RestoreUseStaticGraphEvaluation is true.

### Repro

1. Copy the following to "Project.proj"
```xml
<Project Sdk="Microsoft.Net.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net48</TargetFrameworks>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
  </PropertyGroup>
  <Target Name="CreateManifestResourceNames" />
  <Target Name="CoreCompile" />
</Project>
```
2. Run `msbuild /restore /p:RestoreUseStaticGraphEvaluation=false Project.proj` which results in `Build succeeded`
3. Run `msbuild /restore /p:RestoreUseStaticGraphEvaluation=true Project.proj` which results in `Invalid restore input. Duplicate frameworks found: 'net40, net40'. Input files: Project.proj`

**Comment by martinrrm** [comment]
I can repro it in my local machine

**Comment by martinrrm** [comment]
@snorrk Hi! I investigated a little bit and looks that the problem is that your project extension `.proj` doesn't import the necessary targets, basically is not supported to have a `.proj` extension and `Microsoft.NET.Sdk` project. Can you try do rename the project file to `.csproj` and see if it works? Thanks!

**Comment by snorrk** [comment]
Not being able to restore using static graph with Microsoft.NET.Sdk is the point of this issue.

[Sdk.targets](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets#L29-L31) says:

> This means support for different languages could either be supplied via an SDK or via a NuGet package

This does not work when static graph is enabled (but does when it is disabled).

I believe that is a bug, the behavior should be consistent regardless of the static graph setting?

**Comment by jeffkl** [comment]
@snorrk what happens when you build the project?

```
D:\repros\duplicate-net40>msbuild /clp:v=n;summary;forcenoalign
MSBuild version 17.9.5+33de0b227 for .NET Framework
Build started 3/12/2024 3:18:20 PM.

Project "D:\repros\duplicate-net40\Project.proj" on node 1 (default targets).
C:\Program Files\Visual Studio 2022\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1248,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [D:\repros\duplicate-net40\Project.proj]
_CleanRecordFileWrites:
  Creating directory "obj\Debug\".
Done Building Project "D:\repros\duplicate-net40\Project.proj" (default targets) -- FAILED.


Build FAILED.
```

Since the project file's extension is `.proj`, the `Microsoft.NET.Sdk` does not import the C# targets that enable multi-targeting.  Since the value of `<TargetFrameworks />` isn't interpreted by the SDK when the project file extension isn't `.proj`, it defaults to .NET Framework v4.0.

https://learn.microsoft.com/dotnet/core/project-sdk/overview#project-files

If you're building a C# library or application, the project file must end in `.csproj`.  If your project is not compiling an C# program or library, consider [Microsoft.Build.NoTargets](https://github.com/microsoft/MSBuildSdks/blob/main/src/NoTargets/README.md).
