### ISSUE TITLE
Getting "The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type" error on reinstall

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#1342]
NuGet Package Manager 2.8.60723.765 for VS2013.

In Package Manager Console:

```
PM> Update-Package -Reinstall Ninject
update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ update-Package -Reinstall Ninject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ update-Package -Reinstall Ninject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ update-Package -Reinstall Ninject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ update-Package -Reinstall Ninject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ update-Package -Reinstall Ninject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
```

What is this?

**Comment by yishaigalatzer** [comment]
We will take a look today. Not sure, this looks like a bug either in the NuGet extension or the ninject package. Are you hitting this on other packages as well?

**Comment by zhili1208** [comment]
@evil-shrike I can't repro this issue, Can you please provide your current package source, packages.config file,nuget.config? thanks

**Comment by zhili1208** [comment]
And Ninject version please.

**Comment by evil-shrike** [comment]
I'm afraid it's not related to a particular package. I tried to reinstall different packages from nuget.org and it worked fine. But when I'm trying to reinstall a package from my source with authentication Nuget fails with the mentioned error.
Packages are installed from that source in nuget manager/console just fine. Only reinstall (`update-package -reinstall`) fails.

**Comment by zhili1208** [comment]
looks like it's something related to package source. is it possible to provide an repro source for us?

**Comment by evil-shrike** [comment]
I created a source "test" for you in our Artifactory server - https://artifacts.croc.ru:

```
nuget sources Add -Name test -Source https://artifacts.croc.ru/api/nuget/test
```

user/pwd - test/11111

The source has a package - Moq.

```
PM> install-Package moq -source test
'Moq 4.0.10827' already installed.
Adding 'Moq 4.0.10827' to Server.
Successfully added 'Moq 4.0.10827' to Server.

PM> Update-Package moq -reinstall -source test -project server
Reinstalling 'Moq 4.0.10827' in project 'Server'.
Update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:1
+ Update-Package moq -reinstall -source test -project server
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
```

**Comment by zhili1208** [comment]
did some investigation on this problem, I think the root cause is NuGet send an OData search query request to server for searching moq 4.0.10827 but got 404 during reinstall. install-package use another API, that's why install works. Looks like some server issue

**Comment by evil-shrike** [comment]
@zhili1208 did you catch a request? can you share a failing URL ?

**Comment by zhili1208** [comment]
@evil-shrike you can try this, https://artifacts.croc.ru/api/nuget/test/Packages?$filter=Id%20eq%20%27moq%27%20, this is searching moq in server, and also you can try nuget.org one:
https://www.nuget.org/api/v2/Packages?$filter=Id%20eq%20%27moq%27%20

**Comment by NeverOddOrEven** [comment]
I am also getting this error when I try to update package paths in a csproj file:
Update-Package [packagename] -IgnoreDependencies -Reinstall -ProjectName [projectname]

**Comment by zhili1208** [comment]
what's your package source and nuget version?

**Comment by NeverOddOrEven** [comment]
Package Manager Console Host Version 2.8.60723.765
NuGet Version: 2.8.60717.93

Oddly enough, when I change my source to nuget.org the command works. 
When I change my source to an artifactory 3.4.1 host, it results in:

Update-Package : The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
At line:1 char:15
- Update-Package <<<<  log4net -Reinstall -IgnoreDependencies -ProjectName blah
  - CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

I could see this feasibly being artifactory (3.4.1 is old) or Package Manager Console not handling the response from artifactory 3.4.1 correctly. I'm naive to the nuget internals/mechanisms though, so that's just a guess.

PM> $error[0].Exception
The current value 'NuGet.DataServicePackage' type is not compatible with the expected 'System.String' type.
PM> $error[0].Exception.StackTrace
   at System.Data.Services.Client.DataServiceContext.ResolveTypeFromName(String wireName, Type userType, Boolean checkAssignable)
   at System.Data.Services.Client.AtomMaterializer.ResolveByCreating(AtomEntry entry, Type expectedEntryType)
   at System.Data.Services.Client.AtomMaterializer.ResolveOrCreateInstance(AtomEntry entry, Type expectedEntryType)
   at System.Data.Services.Client.AtomMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at System.Data.Services.Client.ProjectionPlan.Run(AtomMaterializer materializer, AtomEntry entry, Type expectedType)
   at System.Data.Services.Client.AtomMaterializer.Read()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGet.DataServicePackageRepository.Exists(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.Exists(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.VisualStudio.VsPackageSourceRepository.Exists(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.Exists(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.VisualStudio.FallbackRepository.Exists(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.Exists(IPackageRepository repository, String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.Exists(IPackageRepository repository, IPackageName package)
   at NuGet.VisualStudio.VsPackageManager.ReinstallPackageInProject(IProjectManager projectManager, IPackage package, Boolean updateDependencies, Boole
an allowPrereleaseVersions, ILogger logger)
   at NuGet.VisualStudio.VsPackageManager.ReinstallPackage(IProjectManager projectManager, String packageId, Boolean updateDependencies, Boolean allowP
rereleaseVersions, ILogger logger)
   at NuGet.PowerShell.Commands.UpdatePackageCommand.PerformReinstalls(IProjectManager projectManager)
   at NuGet.PowerShell.Commands.UpdatePackageCommand.ProcessRecordCore()
   at NuGet.PowerShell.Commands.NuGetBaseCommand.ProcessRecord()

**Comment by zhili1208** [comment]
DataServicePackageRepository.Exists(String packageId, SemanticVersion version) is checking whether this package exists in server. it sent an OData query to get this package but didn't get right response. From my understanding, it looks like a server issue.

**Comment by NeverOddOrEven** [comment]
Thanks zhili. I appreciate the help.
