### ISSUE TITLE
CPM causes redundant recompilation

### ISSUE THREAD

**Issue by MarkKharitonov** [NuGet/Home#13461]
### NuGet Product(s) Affected

Other/NA

### Current Behavior

Before CPM each project lists (typically) the versions of the packages it uses. Suppose we have a unit test project that depends on Moq. A change in its version should not cause recompilation of the entire solution. And this is the behavior we have without CPM, if we reference the version explicitly in the respective `PackageReference`.

After moving to CPM we have to mention the version in the central `Directory.Packages.props` file, which is a dependency of each and every project in the solution. So, changing the version of Moq there causes recompilation of all the projects.

For the case of unit tests we can resolve it by structuring the unit test projects in a dedicated sub directory and placing their own `Directory.Packages.props` file there, which could also import the top level one. So, this particular scenario has a workaround.

However, this scenario can be true for any project depending on a unique package. CPM introduces the regression that an update of its package version is now "the business" of all the projects.

### Desired Behavior

A desired behavior would be to recompile only those projects which depend on the package which version was updated. 

(Of course, projects depending on the recompiled ones will be recompiled as well, but that is the usual and expected behavior).

**Comment by martinrrm** [comment]
@jeffkl Can you help me triage this issue? I'm not sure if this is something we already have planned

**Comment by jeffkl** [comment]
Since `Directory.Packages.props` is imported by MSBuild, it gets added to the `MSBuildAllProjects` property.  If any MSBuild import is newer than the output of a project then it will rebuilt [due to this declaration](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L37).  Unfortunately, this is by design at the moment.  A user could place any MSBuild logic in `Directory.Packages.props` that actually affects the compilation such as adding a new target that needs to run. 
For example, I add this to my `Directory.Packages.props`:

```xml
<Target Name="MyCustomTarget" BeforeTargets="CoreCompile">
  <Message Text="Example" />
</Target>
``` 
If the CoreCompile target didn't consider `$(MSBuildAllProjects)` as an input, my projects won't re-run compilation and I would be scratching my head.  Obviously, sometimes its desirable to trigger a rebuild and sometimes it isn't.  But editing an MSBuild import currently always triggers a rebuild.

**Comment by MarkKharitonov** [comment]
The rationale and the mechanism of it is totally clear to me. However, it may not be clear to all who read the CPM documentation and do not realize this regression in the behavior of a common scenario - a NuGet version is changed for a package. Before CPM only the touched project and its dependents are recompiled. When using CPM it is the entire solution. For big solutions containing unit test projects (which usually do not carry a lot of dependents) this is a big deal, as any change in the versions of the packages consumed by the unit tests, will now recompile all the business logic.

The CPM documentation should indicate that and provide workarounds, e.g. structuring the solution in a way that consolidates all the unit tests under a single folder and allows for a hierarchy of `Directory.Packages.props` files. 

But not everything can be resolved with restructuring, so the side effect of recompiling it all is there all the time.

At least this should be emphasized.
