### ISSUE TITLE
NuGetPackageRoot and other Pkg_* variables from GeneratePathProperty only present after first 'dotnet restore'

### ISSUE THREAD

**Issue by NoTuxNoBux** [NuGet/Home#13513]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.301

### Impact

It bothers me. A fix would be nice

#### Context

We have a task that runs after `dotnet restore` to handle some post-processing. To address it, we use `GeneratePathProperty` so we are able to use its path in `UsingTask` regardless of where it is installed. However, the first time we restore the project, we always get an error because the variable expands to an empty value.

This doesn't appear to be related to `GeneratePathProperty` because `NuGetPackageRoot` is also empty during that run.

#### Reproduction Steps

1. Create `NuGetErrorCase.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YUICompressor.NET.MSBuild" Version="3.0.0" GeneratePathProperty="true" />
    </ItemGroup>

    <Target Name="DoTest" AfterTargets="Restore">
        <Message Text="Package path = '$(PkgYUICompressor_NET_MSBuild)'..." Importance="high" />
        <Message Text="NuGetPackageRoot = '$(NuGetPackageRoot)'..." Importance="high" />
    </Target>
</Project>
```

2. Run `dotnet restore`, output:

```
  Determining projects to restore...
  Restored /home/werk/Downloads/nuget-case/NuGetErrorCase.csproj (in 172 ms).
  Package path = ''...
  NuGetPackageRoot = ''...
```

3. Run `dotnet restore` again, output:

```           
  Determining projects to restore...
  All projects are up-to-date for restore.
  Package path = '/home/werk/.nuget/packages/yuicompressor.net.msbuild/3.0.0'...
  NuGetPackageRoot = '/home/werk/.nuget/packages/'...
```

To reproduce again just remove `bin` and `obj` and the problem returns.

This sounds similar to #9150, but we're not using MSBuild directly and using only using `dotnet restore`. We're not sure about how this is handled internally, but variables magically appearing from the second restore is very non-obvious to us. The workaround we have been using up until now is 'just run twice', but as you can imagine it's not a great workaround :sweat_smile: .

#### Additional Flatpak .NET 8 Weirdness

There is further weirdness occurring with these variables since the above is what happens for me on Arch Linux using .NET 8 from the native repositories (`dotnet-sdk` package), and also happens on Windows 11. However, if I run the above steps with [sandboxed Flatpak .NET 8](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet8) from `org.freedesktop.Sdk.Extension.dotnet8`, the variables are never filled in and step 2 is all that happens. How is this possible? Is there some kind of .NET SDK extension that is needed for these variables to be filled in?

This might be a different problem specific to the Flatpak, though, but I'm not sure how to 'debug' it to know whether I should report it here or to the Flatpak extension repository.

**Comment by baronfel** [comment]
@NoTuxNoBux I think you're hitting a fundamental problem with your model of how build (including Restore) works. To understand the problem you need to understand how MSBuild builds projects.

MSBuild operates in stages - there are two stages that are of interest for this conversation:
* evaluation - when the project file is read and any Imports are calculated and followed to produce a _complete_ model of the project, along with all known available Targets
* execution - when a given target is actually found and invoked on an evaluated project model, triggering execution of any of its dependencies prior to target execution.

Why does this matter for your report? Because the `Pkg_` properties are generated as part of the _execution_ of the Restore target and put into a `.props` file that is conditionally-Imported. This means that in order to actually have access to those generated properties, a new _evaluation_ of the project must occur.  This is one of the main reasons why we do not recommend that users try to hook or extend Restore, and it's also why simple usages of msbuild like `dotnet build /t:Restore;Build` may not work - the targets are both run in the same 'evaluation context'.

So in the general case I would not expect your customizations to work, based on what you have written here. If you do rely on the `Pkg_` properties you need to rework your setup/usage to instead happen sometime during the execution of the Build target.

Regarding your Flatpak .NET 8 weirdness, nothing comes immediately to mind. If you could capture a [binlog](https://aka.ms/binlog) that would help us see exactly what is causing the behavior you see.

**Comment by NoTuxNoBux** [comment]
@baronfel Thanks for the explanation, this makes sense. I have changed my approach to the following, which doesn't suffer from the same problem:

```
dotnet msbuild -target:DoTest -restore SomeCSharpProject
```

My main goal was to have a single command that restores packages and does post-processing on the packages after restore, which this also seems to achieve, without hitting the aforementioned error.

The Flatpak issue also doesn't seem to occur with this new approach - I don't understand why the original behaviour was different, but judging from your explanation and documentation it was always going to be flaky, so I consider that issue solved as well :slightly_smiling_face: .
