### ISSUE TITLE
Missing and inconsistent warnings NU190x about vulnerabilities with MSBuild restore in Visual Studio and command-line

### ISSUE THREAD

**Issue by carlos-quintero** [NuGet/Home#13521]
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild 17.10.4+10fbfbf2e, Visual Studio 2022 17.10.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

* Using Visual Studio 2022, in Options window, NuGet Package Manager > General check the checkbox "Allow format selection on first package install"
* Create a blank solution and add 4 projects to it as follows
* Add a "Class Library" project named "ClassLibrarySdkStyleNet8" targetting NET 8. Add to it the NuGet package Newtonsoft.Json 12.0.3 (which is vulnerable). Therefore, this project will use SDK style and PackageReference. 
* Add a "Class Library (.NET Framework)" project named "ClassLibraryClassicStyleNetFramework48PackagesConfig" targetting .NET Framework 4.8. Add to it the NuGet package Newtonsoft.Json 12.0.3 (which is vulnerable) using Packages.config when prompted. Therefore, this project will use classic style and packages.config.
* Add a "Class Library (.NET Framework)" project named "ClassLibraryClassicStyleNetFramework48PackageReference" targetting .NET Framework 4.8. Add to it the NuGet package Newtonsoft.Json 12.0.3 (which is vulnerable) using PackageReference when prompted. Therefore, this project will use classic style and PackageReference.
* Add a "Class Library (.NET Framework)" project named "ClassLibrarySdkStyleNetFramework48" targetting .NET Framework 4.8. Using the Upgrading Assistant, convert it to SDK project style. Add to it the NuGet package Newtonsoft.Json 12.0.3 (which is vulnerable). Therefore, this project will use SDK style and PackageReference.

### Problem 1

Compile the solution in Visual Studio

Result:

In the Error List and in the Output window, you get warning NU1903 only for these two projects (the ones that use SDK-style):
* ClassLibrarySdkStyleNetFramework48
* ClassLibrarySdkStyleNet8

It would be helpful to get the warning also for the two projects using the classic style

### Problem 2

Open a command prompt, change to the folder of the solution and execute:

`"<path>\MSBuild\Current\bin\msbuild.exe" -t:Restore`

Result:

You get warning NU1903 only for these three projects (the ones that use PackageReference):
* ClassLibrarySdkStyleNetFramework48
* ClassLibrarySdkStyleNet8
* ClassLibraryClassicStyleNetFramework48PackageReference

It would be helpful to get the warning also for project using packages.config

**Comment by zivkan** [comment]
Hi @carlos-quintero, sorry about the slow reply time. Thank you for taking the time to provide us feedback! 

I didn't create the non-SDK style project that's migrated with the Upgrade Assistant, as it just becomes an SDK style project that isn't fundamentally to the other SDK style project, but for quick reference, here's the solution I ended up with: [gh13521.zip](https://github.com/user-attachments/files/15906806/gh13521.zip)

Regarding the non-SDK style PackageReference project not showing the warning in the Error List window in VS, I have a specific issue about it here:
* https://github.com/NuGet/Home/issues/12800

You appear to be the first customer who noticed the issue, so I'd appriciate if you could add a 👍 reaction to the original comment in that issue, so that it can start moving up [the list of all issues sorted by 👍](https://github.com/NuGet/Home/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)

I can't find an existing issue about packages.config warnings disappearing from Visual Studio's Error List window, but from what I know about NuGet's implementation, I think it's probably the same root cause as for non-SDK style PackageReference projects, so I don't feel like creating another issue for it. But while I was following the repro steps, I did see the packages.config project's warning in the error list after the first build after installing the package.

Finally, regarding the command line restore not warning about the packages.config project, that's by design. Restore as an MSBuild task was created for PackageReference, so if you pay close attention, you'll see that the solution packages folder isn't created (assuming you delete it before running the MSBuild restore). In VS 16.5 we added a flag `-p:RestorePackagesConfig=true`: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-packagereference-and-packagesconfig-projects-with-msbuild

It wasn't enabled by default due to an abundance of caution in case it causes any restore failures and therefore appears to be a breaking change from affected customers point of view. Hence you need to provide the argument on the command line. Personally, I very much recommend this `msbuild -t:restore -p:RestorePackagesConfig` over `nuget.exe restore`, and it should just be a once-off CI pipeline change.

I'm labeling this issue as "waiting for customer", because I believe I addressed all the points from this issue, so allowing you an opportunity to reply before the issue gets closed.

**Comment by carlos-quintero** [comment]
Hi

- I have added a 👍 reaction to the original comment in that issue #12800
- I was aware of the need to use `-p:RestorePackagesConfig=true` with msbuild to restore projects using packages.config. Somehow I forgot about it completely when reporting this issue. Certaintly I have it in the CI pipeline and it works as expected, reporting vulnerabilities of ASP.NET Framework 4.x projects (using packages.config that cannot be migrated officially to PackageReference)

So, you can close this issue and work on issue #12800

**Comment by nkolev92** [comment]
Closing as dup https://github.com/NuGet/Home/issues/12800 per the conversation.
