### ISSUE TITLE
NuGet fails because of invalid characters in User-Agent header

### ISSUE THREAD

**Issue by GGG-KILLER** [NuGet/Home#13531]
### NuGet Product Used

dotnet.exe, NuGet SDK

### Product Version

9.0.100-preview.4.24267.66

### Worked before?

No

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Install NixOS latest version (24.11 Vicuña).
2. Attempt to restore nuget packages for a project.
3. Unable to restore packages due to special character in header since the release name (Vicuña) is added to the HTTP header.

### Verbose Logs

```shell
/nix/store/lax73wx0qp7v2wpydc0bii5hszj1dys5-dotnet-core-combined/sdk/9.0.100-preview.4.24267.66/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/nix/store/jd1kkgy9psy5km4m6k0drbzd7i3vqga6-dotnet-sdk-9.0.100-preview.4.24267.66/sdk/9.0.100-preview.4.24267.66/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/nix/store/jd1kkgy9psy5km4m6k0drbzd7i3vqga6-dotnet-sdk-9.0.100-preview.4.24267.66/sdk/9.0.100-preview.4.24267.66/dotnet.dll -maxcpucount -target:Restore -tlp:default=auto -verbosity:m -verbosity:diag ./m3u8-dl.sln
    Determining projects to restore...
    /home/ggg/Git/GGG-KILLER/m3u8-dl/src/m3u8-dl.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    Failed to restore /home/ggg/Git/GGG-KILLER/m3u8-dl/src/m3u8-dl.csproj (in 5.76 sec).
    /home/ggg/Git/GGG-KILLER/m3u8-dl/test/m3u8-dl.Test.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    /home/ggg/Git/GGG-KILLER/m3u8-dl/src/m3u8-dl.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
    Failed to restore /home/ggg/Git/GGG-KILLER/m3u8-dl/test/m3u8-dl.Test.csproj (in 11.61 sec).
```

**Comment by GGG-KILLER** [comment]
@SuperSandro2000 has already investigated this issue and pinpointed the issue to `NuGet.Protocol` adding the release name to the user agent: https://github.com/NixOS/nixpkgs/issues/315574#issuecomment-2157012978

This blocks usage of the .NET SDK entirely in NixOS due to this lack of sanitization. This was also an issue in the Azure SDK and was fixed as follows: Azure/azure-sdk-for-net#44386.

**Comment by purepani** [comment]
As mentioned in https://github.com/dotnet/runtime/issues/102819#issuecomment-2159444111, the string passed to  HttpClient [here (I think)](https://github.com/NuGet/NuGet.Client/blob/dc2e3b27170c779e3c01a7306504fb83cb4ef147/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs#L66) needs to sanitize the string.

**Comment by purepani** [comment]
Related issue: https://github.com/NuGet/Home/issues/11995

**Comment by purepani** [comment]
Also, I wanted to ask if this is a bug with being sent when `DOTNET_CLI_TELEMETRY_OPTOUT` is set to 1. I wouldn't think that this information should be used for anything other than telemetry, so I would guess that it shouldn't be sent in this case.

**Comment by baronfel** [comment]
@purepani not all tools may be handling/looking for the .NET CLI-specific opt out. If NuGet has a separate opt-out internally (cc @zivkan?) then the .NET CLI should be responsible for setting whatever that mechanism is based on the CLI's opt-out settings. We're happy to do this, just need guidance.

**Comment by purepani** [comment]
I spent some time looking for a nuget-specific opt out, and I wasn't able to find one when I was searching through the documentation and code base, but of course I don't know the code base that well and could be wrong. Regardless, if it does exist, it should maybe be made more obvious, and if it doesn't, I definitely think adding it would be a good idea since, as far as I can tell, this is just telemetry data.

**Comment by GGG-KILLER** [comment]
I believe for now the focus should be on making this usable on NixOS 24.11.
The quick method would be to do the same as done in Azure SDK (Azure/azure-sdk-for-net#44386) and URL Encode the distro name.

**Comment by zivkan** [comment]
A change to NuGet was merged a few days ago, as can be seen in the github issue timeline, and it was [merged into the .NET SDK's main branch two days ago](https://github.com/dotnet/sdk/pull/42138).

Can someone using NixOS try a [daily build](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md) of the .NET 9 SDK, and reply here if it now works for you?  if you run `dotnet nuget`, the version listed on the first line must be 6.12.0.26 or higher, otherwise you're running a version of the .NET SDK without the fix and therefore I don't expect it to work.

I need confirmation that the fix works before I can even request to backport to the .NET 8 SDK (no promises I'll get approval even if it is confirmed to work).

**Comment by GGG-KILLER** [comment]
@zivkan sorry, I no longer can test it since we've decided to change the release name to remove the non-ascii letter.

We'd need it to be backported to .NET 6 as well and this fix ended up coming after we merged it.

I can still test it if you want but there's no need for backporting anymore.

**Comment by purepani** [comment]
I think the intention was to change it back once this is fixed, so we should still test this if possible

**Comment by GGG-KILLER** [comment]
> I think the intention was to change it back once this is fixed, so we should still test this if possible

The issue is that unless if this gets backported to both .NET 6 and 8 we won't be able to reverse the change.

I'll see if I can test it in the meanwhile

**Comment by zivkan** [comment]
As previously mentioned, I can't get approval to backport the fix unless I have evidence it works (and even then, it's up to senior executives to decide if they accept the risk of unintended bugs).

FWIW, you can build projects targeting .NET 6 with the .NET 8 SDK, it's not necessary to use the same version of the SDK as you want your app to use at runtime.

Otherwise, the change is in the .NET 9 SDK. I think it'll be available in preview 7, but it might not be until RC1.
