### ISSUE TITLE
Wrong documentation in Create UWP package (C#)

### ISSUE THREAD

**Issue by HO-COOH** [NuGet/Home#13586]
### NuGet Product Used

NuGet.exe

### Product Version

N/A

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

[Link here](https://learn.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs)

Obviously, you are not packaging any `dll` files in the `nuspec` file
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/42881734/c404a1cc-de30-4542-a4b6-a3f7d97a44bd)

But in the result screenshot, there are `dll` files out of nowhere
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/42881734/dbef26a7-ef5b-4a27-95f2-accdd7834a82)

I get redirected by [this](https://github.com/NuGet/docs.microsoft.com-nuget/issues/3310)

**Comment by jgonz120** [comment]
The DLLs in that screenshot are for the package which is being packed. One for each of the targeted runtimes supported. These DLLs are necessary for users to be able to use the package. Is there a different result you were expecting?

**Comment by zivkan** [comment]
@jgonz120 the first screenshot shows the nuspec includig `.winmd` files, not `.dll`.  The `.dll` assemblies will only work (maybe?) for .NET UWP apps, but `.winmd` will work for both .NET and also C++ UWP apps.

**Comment by jgonz120** [comment]
@zivkan oh, I assumed because the other packages include the DLLs without specifying them in the nuspec they were meant to show up. Now that I followed the tutorial, I'm no longer seeing the DLLs:
![image](https://github.com/NuGet/Home/assets/5552792/5a44eb38-b1fc-4352-bd11-88bd127eaece)

So we should just update the doc?

**Comment by zivkan** [comment]
It was originally reported in the docs repo, but because the docs team were planning to turn off issues in the docs repo (which they have done since then), they instructed people to re-create the issues here (and the docs person, I think his account name is something like mikejo5000) created a bunch here.

We don't have a new issue template for docs, hence why all the docs issues that were recreated in home were created with the bug template.

**Comment by HO-COOH** [comment]
So, can anyone direct me to the right place to file documentation issue? I have a bunch of others I want to raise.  I don't want to use the feedback link, because I want to track the updates. And I think the feedback just get mostly ignored anyways.

**Comment by zivkan** [comment]
All the docs pages on learn.microsoft.com have feedback buttons at the top and bottom of the page. However, I'm confident it's not public, so you won't' be able to track them.

**Comment by HO-COOH** [comment]
> All the docs pages on learn.microsoft.com have feedback buttons at the top and bottom of the page. However, I'm confident it's not public, so you won't' be able to track them.

That does not answer my question tho. I want to know if this is the correct place to file documentation issues.

**Comment by donnie-msft** [comment]
> > All the docs pages on learn.microsoft.com have feedback buttons at the top and bottom of the page. However, I'm confident it's not public, so you won't' be able to track them.
> 
> That does not answer my question tho. I want to know if this is the correct place to file documentation issues.

I had to find out myself, as this process changed in recent days. No, please do not file docs issues in the Home repo. Instead, on any docs page, use the Thumbs Down button and provide the detail in the form that appears. The feedback for docs is recorded from that point. /cc @Mikejo5000

Product issues are still to be filed here on GitHub.
