### ISSUE TITLE
UWP restore throws a null reference exception on anotar.nservicebus.fody

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1358]
Steps
1. Create a new UWP app
2. install-package anotar.nservicebus.fody -version 2.19.0

Result

```
PM> install-package anotar.nservicebus.fody -version 2.19.0
Restoring packages for 'App22'.
Restoring packages for c:\users\juste\documents\visual studio 2015\Projects\App22\App22\project.json...
install-package : Object reference not set to an instance of an object.
At line:1 char:1
+ install-package anotar.nservicebus.fody -version 2.19.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
```

This also repros when adding the package to the project.json file manually.

The package installs fine into a C# console app. It does not contain any compatible items for UWP, but that does not look like the cause of the failure here.

**Comment by yishaigalatzer** [comment]
Looks like the cause is that packages with a nuspec not matching the package name fail to restore.

The suggested fix is to use SingleOrDefault to figure out the nuspec name, and if it fails try to find it by name (which is tricky).

Current project.json restore code does a FirstOrDefault, which works in most cases but is incorrect, and can pick arbitrary nuspecs if there are more than one of them.

Given that this is something we might allow in subfolders, the solution might be to just scan for items at the root of the package rather than all items.

**Comment by yishaigalatzer** [comment]
CC @davidfowl this likely needs to be fixed for DNU as well, or we can just wait until we merge.

**Comment by emgarten** [comment]
This is in nuget.client for 3.3.
