### ISSUE TITLE
Make 'why' command available in NuGet.Commands

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [NuGet/Home#13639]
### NuGet Product(s) Affected

NuGet SDK

### Current Behavior

`dotnet nuget why` can only be used from the CLI, as the API is internal in `NuGet.CommandLine.XPlat`.

### Desired Behavior

`dotnet nuget why` command should be available as public in `NuGet.Commands`.

### Additional Context

We want to use the results of the `dotnet nuget why` command in automated reports for our developers.
We therefore desire to use the NuGet SDK to get the "why" data programmatically and make several processes easier.

**Comment by nkolev92** [comment]
Team Triage: 

As a tool first, we want to focus on the code velocity and ease of updating the why command. By adding it to NuGet.Commands, we lose some of that ability, because we can no longer making breaking API changes, should new requirements for the why command come along. 
At this point, we prefer to leave the code in NuGet.Commandline.Xplat. 

You are welcome to file an issue requesting a machine readable version of dotnet nuget why.
