### ISSUE TITLE
[Cross-platform Dotnet NuGet Sign] The error “invalid value for’--certificate-fingerprint’ option” displays instead of error NU3001 when signing with certificate search criteria yields no certificate matches

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13651]
### NuGet Product Used

dotnet.exe, NuGet SDK

### Product Version

.NET SDK 8.0.400- rtm.24367.3 patching with NuGet Dev\6.12.0.33

### Worked before?

It is a regression since it didn't repro on 8.0.400-preview.0.24324.5 patched with Dev\6.11.0.110.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	[Patch dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703) (--SDKChannel 8.0.4xx and Nupkgs is from [Pipelines - Run 6.12.0.33 artifacts (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9905933&view=artifacts&pathAsName=false&type=publishedArtifacts))
2.	Use the patched "dotnet.exe" to sign a package. Where <PackageFilePath> is the test package path, sign the test package: 
               On Windows:  `.\dotnet.exe nuget sign <PackageFilePath> --overwrite  --certificate-fingerprint abc  --timestamper http://timestamp.digicert.com/ -v n` 
               On Linux/macOS:` ./dotnet nuget sign <PackageFilePath> --overwrite  --certificate-fingerprint abc  --timestamper http://timestamp.digicert.com/ -v n` 
3.	Verify the output of the previous step.
#### Expected Result:
The error below displays.
`Error: NU3001: No certificates were found that meet all the given criteria. For a list of accepted ways to provide a certificate, visit https://docs.nuget.org/docs/reference/command-line-reference." `
#### Actual Result:
The error “invalid value for’—certificate-fingerprint’ option” displays instead of error NU3001 as the screenshot below.
![image](https://github.com/user-attachments/assets/6930deaa-ee32-4937-8e7f-15f5e0500d04)
#### Notes:
It reproes on Windows/Linux/MacOS.

**Comment by kartheekp-ms** [comment]
This behavior is expected. In the https://github.com/NuGet/NuGet.Client/pull/5895 PR, we updated the `dotnet sign` command behavior to raise a warning if insecure `SHA-1` hash is passed to the `--certificate-fingerprint` option. The certificate fingerprint passed in the test case, `abc`, is not a valid SHA-1 hash, hence a new error message is added (step 1). Please update the test case to pass a dummy SHA-1 hash, `89967D1DD995010B6C66AE24FF8E66885E6E03A8`, so that the command will warn about the usage of SHA-1 along with the error message:

```
Error: NU3001: No certificates were found that meet all the given criteria. For a list of accepted ways to provide a certificate, visit https://docs.nuget.org/docs/reference/command-line-reference.

```
The new behavior is explained as follows.

1. Validates the certificate fingerprint to ensure it uses either the SHA-1, SHA-256, SHA-384, or SHA-512 algorithm. Throws an error otherwise.
2. Raises a warning if a SHA-1 certificate fingerprint is provided. This warning will be promoted to an error in the future.
3. While searching for a certificate from the local store, if a SHA-1 hash is provided, finds the certificate using the existing API, i.e., `store.Certificates.Find(X509FindType.FindByThumbprint, options.Fingerprint, validOnly);`
4. If a SHA-256, SHA-384, or SHA-512 certificate fingerprint is provided, loops through the certificates in the store to find the certificate with the matching hash.

If you would like to create another test to verify only the NU3001 error is raised, simply pass a SHA-256 hash to `--certificate-fingerprint` option. Here is a dummy SHA-256 hash: `5485cc9c6c8b4e6982083fbd696a7d3cf0466579b4f92b56477fd2a24f9cdeaaf0b2c7fdbdd4c18a1e8a80f22ac404e9`.

**Comment by v-luzh** [comment]
@kartheekp-ms, thanks for your update. We have updated the test case.
