### ISSUE TITLE
NuGet Error: Unable to parse version value '2.0.0-beta.3' from 'packages.config

### ISSUE THREAD

**Issue by jsquire** [NuGet/Home#13750]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#45718](https://github.com/Azure/azure-sdk-for-net/issues/45718).

## Details

Hello,

After I installed Azure.AI.OpenAI 2.0.0-beta.3 I receive the following build errors. Anyone else seen and been able to resolve this issue. I can't seem to find any information regarding this error and it may not be specific to this package. It seems to be any package with 4 segments in the version. Any idea how to fix this?

>C:\Projects\SMTMVC\.nuget\nuget.targets(92,9): error : Unable to parse version value '2.0.0-beta.3' from 'packages.config'.
3>C:\Projects\SMTMVC\.nuget\nuget.targets(92,9): error MSB3073: The command ""C:\Projects\SMTMVC\.nuget\NuGet.exe" install "C:\Projects\SMTMVC\SMTMVC\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\Projects\SMTMVC\ "" exited with code 1.

### Environment

MVC project targeting the .NET Framework 4.8 in Visual Studio 2022 (Version 17.11.0), Nuget Package Manager (Version 6.11.0).

**Comment by jeffkl** [comment]
I'm not able to reproduce this.  I suspect you have some encoded value or something in your `packages.config`.  

packages.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Azure.AI.OpenAI" version="2.0.0-beta.3" targetFramework="netstandard2.0" />
</packages>
```

Output
```
>nuget install packages.config -outputdirectory %cd%\packages
Feeds used:
  C:\Users\jeffkl\.nuget\packages\
  https://api.nuget.org/v3/index.json

Restoring NuGet package Azure.AI.OpenAI.2.0.0-beta.3.
  GET https://api.nuget.org/v3-flatcontainer/azure.ai.openai/2.0.0-beta.3/azure.ai.openai.2.0.0-beta.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/azure.ai.openai/2.0.0-beta.3/azure.ai.openai.2.0.0-beta.3.nupkg 38ms
Installed Azure.AI.OpenAI 2.0.0-beta.3 from https://api.nuget.org/v3/index.json to C:\Users\jeffkl\.nuget\packages\azure.ai.openai\2.0.0-beta.3 with content hash hKd6Z3vyJ1DmBitCwwJMXEOs2zcq89tXjApcIYMNJSCgRKC0bRi4JON78R2/Vz+IPdsYdA/MT/0p/+llYnDwbw==.
Adding package 'Azure.AI.OpenAI.2.0.0-beta.3' to folder 'D:\Repros\packages_config\packages'
Added package 'Azure.AI.OpenAI.2.0.0-beta.3' to folder 'D:\Repros\packages_config\packages'
```

**Comment by jzahoor** [comment]
I'm having the same issue but with a different NuGet package: `OpenAI --version 2.1.0-beta.1`

Note that the issue is not in installing the package but when **building** the solution.

Here's the exact error for me: _Unable to parse version value '2.1.0-beta.1' from 'packages.config'._
Microsoft Visual Studio Enterprise 2022 Version 17.11.4
Microsoft .NET Framework Version 4.8.09032
NuGet Package Manager   6.11.0

**Comment by jzahoor** [comment]
> I'm not able to reproduce this. I suspect you have some encoded value or something in your `packages.config`.
> 
> packages.config
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <packages>
>   <package id="Azure.AI.OpenAI" version="2.0.0-beta.3" targetFramework="netstandard2.0" />
> </packages>
> ```
> 
> Output
> 
> ```
> >nuget install packages.config -outputdirectory %cd%\packages
> Feeds used:
>   C:\Users\jeffkl\.nuget\packages\
>   https://api.nuget.org/v3/index.json
> 
> Restoring NuGet package Azure.AI.OpenAI.2.0.0-beta.3.
>   GET https://api.nuget.org/v3-flatcontainer/azure.ai.openai/2.0.0-beta.3/azure.ai.openai.2.0.0-beta.3.nupkg
>   OK https://api.nuget.org/v3-flatcontainer/azure.ai.openai/2.0.0-beta.3/azure.ai.openai.2.0.0-beta.3.nupkg 38ms
> Installed Azure.AI.OpenAI 2.0.0-beta.3 from https://api.nuget.org/v3/index.json to C:\Users\jeffkl\.nuget\packages\azure.ai.openai\2.0.0-beta.3 with content hash hKd6Z3vyJ1DmBitCwwJMXEOs2zcq89tXjApcIYMNJSCgRKC0bRi4JON78R2/Vz+IPdsYdA/MT/0p/+llYnDwbw==.
> Adding package 'Azure.AI.OpenAI.2.0.0-beta.3' to folder 'D:\Repros\packages_config\packages'
> Added package 'Azure.AI.OpenAI.2.0.0-beta.3' to folder 'D:\Repros\packages_config\packages'
> ```

The issue is during build and not during install of the package.

**Comment by limdv** [comment]
I was able to resolve this by updating my NuGet.exe manually

**Comment by jzahoor** [comment]
You had to manually update NuGet even though Visual Studio is showing that it's using the latest version of NuGet?

So I tried your approach and updated it manually. The issue still remains when _**building**_ the solution.

**Comment by limdv** [comment]
I thought the version displayed in visual studio was used in each project but since we created this project in an older version of VS the actual nuget.exe inside the file system under the solution was old.

**Comment by zivkan** [comment]
If this is happening during build, not during an explicit restore, your project is probably using a feature that was last available in VS 2013.  I strongly recommend you undo it, using the instructions I wrote here: https://stackoverflow.com/a/54245600/2843065

Considering this has been removed since VS2015, there's really no reason to keep using it. It slows down your build by doing unnecessary restore checks every build, even though VS has already restored. If you don't already have a restore step in your CI scripts, you will need to add a `msbuild your.sln -t:restore -p:RestorePackagesConfig=true` step.

**Comment by jzahoor** [comment]
Thank you, @zivkan !! It now works for me :) 👍 💯 

I was in the middle of attempting the solution posted here when your response came in: 
https://stackoverflow.com/questions/54235147/missing-file-nuget-targets-on-existing-project/54245600#54245600

It looks like that answer was along the same lines as your solution. This is the only thing that worked for me and it was because my projects were migrated from an older VS so they carried the obsolete entries with them.

Thanks again!!
