### ISSUE TITLE
Losing <SpecificVersion>False</SpecificVersion>

### ISSUE THREAD

**Issue by dradovic** [NuGet/Home#1380]
When I update a NuGet package whose reference is set to be

```
<SpecificVersion>False</SpecificVersion>
```

this line gets removed from the project (csproj) file.

IMHO, reference properties such a "Specific Version" and "Copy Local" should be preserved.

**Comment by yishaigalatzer** [comment]
### What is going on

The process of updating a package is to uninstall and reinstall it, so this can not work. In project.json (NuGet3) we are moving to a mode where NuGet does not touch the csproj file at all (where scenarios you are describing are partly the inspiration for the change). But we don't plan to make a change for this in packages.config scenarios, because it is not clear that we should or shouldn't preserve it.

Here is an example why we shouldn't get in the middle of this.

Package install as reference a.dll
an install.ps1 script add CopyLocal="false"

The package owner realizes that was a mistake and removes the install.ps1 script, and releases version 2 of the package, expecting that there is no CopyLocal defined on the reference.
(So yes I can see both sides, but in this case I would opt to not changing a behavior).

### What can you do

You probably need to come up with a different way to define the settings in your csproj file. Instead of putting them on the reference that we know if going to change, we are going to use an msbuild feature that lets you apply the settings to a reference.

You can go with the approach outlined by this [SO](http://stackoverflow.com/questions/841913/modify-msbuild-itemgroup-metadata) post and use an msbuild target.

**Comment by dradovic** [comment]
Thanks for the clarification and thanks for trying to make it better in NuGet3 :)
