### ISSUE TITLE
Allow PackagePath lib\any

### ISSUE THREAD

**Issue by CoenraadS** [NuGet/Home#13808]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

If I have a .csproj with e.g.

```
 <PropertyGroup>
   <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
 </PropertyGroup>
 
   <ItemGroup>
    <Content Include="lib\foo.dll">
      <Pack>true</Pack>
    </Content>
  </ItemGroup> 
```

Then the output in the nupkg is:

  - File:    content/lib/bc-fips-1.0.1.dll
  - File:    contentFiles/any/net48/lib/bc-fips-1.0.1.dll
  - File:    contentFiles/any/netstandard2.0/lib/bc-fips-1.0.1.dll
  
The assembly is included 3 times, and not de-duplicated, ballooning the nupkg size  

If I use: `TargetsForTfmSpecificBuildOutput`

```
  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeFoo</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <Target Name="IncludeFoo">
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)foo.dll">
      </BuildOutputInPackage>
    </ItemGroup>
  </Target>
```

I still get 2 copies

### Desired Behavior

Allow something like:

```
   <ItemGroup>
    <Content Include="lib\foo.dll">
      <Pack>true</Pack>
      <PackagePath>lib\any</PackagePath>
    </Content>
  </ItemGroup> 
```

So the .dll only has to be included once. 

I read https://learn.microsoft.com/en-us/nuget/create-packages/native-files-in-net-packages#compile-assets but it wasn't really clear to me. It says I recommends using ref, but ref/any also is disallowed from my experiments.

My goal is to package the FIPS dll https://www.bouncycastle.org/download/bouncy-castle-c-fips/ into a nuget package, and ensure consumers calling fips code via the package will also work, so the dll has to be present for compilation and runtime.

**Comment by zivkan** [comment]
The purpose of target frameworks, is to provide a kind of guarantee that if your project is targeting a framework that is compatible with the package's target framework, so that there is little chance that your app fails at runtime with "method not found" exceptions.

Therefore, your proposal to have a `lib\any\*.dll` would either violate this "promise" that NuGet makes, or the `lib/any/` assemblies would only be allowed to be compiled against the absolute smallest set of APIs that are available in all target frameworks.

However, there is no such API set.  The docs for .NET Standard show that .NET Standard 1.0 is only supported from a .NET Framework 4.5. .NET Framework 4.0 and earlier are not compatible with .NET Standard 1.0. That makes .NET Framework 1.0 the next best candidate, but .NET (Core) is not fully compatible with .NET Framework 1.0. Also .NET Nano Framework is not compatible with any Microsoft target framework, so even if there was a lowest common denominator for .NET Framework, .NET Standard and .NET (Core), it still wouldn't meet the compat requirements for .NET Nano Framework.  Finally on compatibility, native C++ projects support NUGet packages (to some extent), and .NET assemblies in `lib/` certainly wouldn't be compatible with C++ projects.

However, from a more practical point of view, if your package is targeting .NET Standard 2.0 and .NET Framework 4.8, unless you have `#if` conditional compilation, you can drop the net48 TFM from your package, since .NET Framework 4.8 implements .NET Standard 2.0, as per the .NET Standard docs. NuGet doesn't do static analysis of your assemblies to validate if they're the same. Technically that might be possible, if someone puts in enough effort, but frankly, I think it's much easier for the package author to take responsibility. If you only want 1 assembly in your package, and you're happy with the TFM compatibility that .NET Standard gives you, then target only that. Therefore, you don't need a `lib/any`, since `lib/netstandard2.0` already gives you that from a practical point of view (for most .NET projects).

Regarding your original title, asking Nuget to de-duplicate assemblies, if you were to do a byte-by-byte comparison, you'll find that the netstandard2.0 ad net48 files do not have the same content. WHen you build, the .NET SDK adds an assembly attribute saying what target framework it was compiled for, and since they were compiled against different target frameworks, they will have different values, and there the files do not have the same contents.

I followed the link to Bouncy Castle's website, and downloaded bc-fips-1.0.2.dll. When I look at it in ILSpy, I see it has the assembly attribute saying it was compiled for .NET Framework 4.5.2. So, it technically belongs in a `lib/net452/` package directory. Therefore, it's entirely possible that it's using .NET Framework APIs that are not available in .NET (Core), and if you were to try to use the dll in a .NET 6 or .NET 8 app, NuGet and .NET cannot make any promises that it will actually work. This is the point of Target Frameworks, to reduce risk of compatibility issues, and giving an almost, but not quite, promise.

**Comment by CoenraadS** [comment]
Thanks for the detailed response
