### ISSUE TITLE
[Bug Bash] The installed package from offline source should not be shown in “Installed” tab anymore after the source is disabled

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13981]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.13.0.84

### Worked before?

It is not regression since it reproes on D16.11\34601.136.

### Impact

It bothers me. A fix would be nice

#### Details about problem
NuGet Version: Dev\6.13.0.84
VS Version: Main\35603.65
OS: Windows-11-Enterprise-23H2

#### Notes:   
1.	The repro rate is 100%.  
2.	It is not regression since it reproes on D16.11\34601.136.
#### Repro Steps:    
1.	Create a “C# Console App (.NET 9.0)” project.    
2.	Right-click the project in Solution Explorer window and select "Manage NuGet Packages…" menu item to open the PM UI.   
3.	Click the settings button, go to “Package sources” tab and make sure two package sources (“nuget.org” and “Microsoft Visual Studio Offline Packages”) are available. 
4.	Go back to the PM UI, click “Browse” tab and select the source “Microsoft Visual Studio Offline Packages” from Package source drop-down list. 
5.	Install a package (e.g. Microsoft.NETCore) with the latest version (5.0.2 in this case).
6.	Click the settings button, go to “Package sources” tab and disable the source “Microsoft Visual Studio Offline Packages” from the source list. 
7.	Go back to the PM UI, click “Installed” tab and select the source “nuget.org” from Package source drop-down list. 

#### Expected Result:
The installed package from offline source should not be shown in “Installed” tab anymore since it was installed from the disabled source “Microsoft Visual Studio Offline Packages” instead of the current selected “nuget.org”.
#### Actual Result:
The installed package from offline source still shows in “Installed” tab after the source is disabled as the screenshot below.
![image](https://github.com/user-attachments/assets/0fceebc9-2d02-4827-a4fe-4032c184946f)

**Comment by kartheekp-ms** [comment]
I was able to reproduce the issue using the repro steps mentioned in the description. I believe this behavior is by design because the `Installed` tab should list all packages installed in the current project or solution, regardless of whether the source from which they were installed is active or not. My understanding is that disabled sources should not be accessed when performing installations or updates in the future.

**Comment by nkolev92** [comment]
Team Triage: The installed package list is not affected by the package source selected and that's by design. 
What is affected is the package details tab, where the version dropdown will only contain a list of available versions on that particular source. 
In this case, it may be a bit misleading since the dropdown will only show the install package, but that doesn't negate the original point that packages should not be filtered out.

**Comment by v-luzh** [comment]
Hi @nkolev92, @kartheekp-ms, got you, thanks for your descriptions.
