### ISSUE TITLE
NuGet.PackageManagement.UI: Implement upgrade all experience

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#142]
Right now there is not a update-all experience available and it's inefficient to upgrade packages one by one.

**Comment by yishaigalatzer** [comment]
This is now supposed to work from nuget powershell. Lets make sure we have a functional test for this.
If we do and it works please move this bug over to 3.1-Beta to add it to the UI.

Otherwise lets talk, we need to add the test or fix the experience

**Comment by danliu** [comment]
We do have functional tests for updateAll on PowerShell. And they are passing. Move the bug to 3.1-beta.

function Test-UpdateAllPackagesInSolution 
function Test-UpdateAllPackagesInASingleProjectWithMultipleProjects
function UpdatePackageWhenAnUnusedVersionOfPackageIsPresentInPackagesFolder

**Comment by csharpfritz** [comment]
Tracking in TFS 1178242

**Comment by MarcosMeli** [comment]
+1 You need to bring it back, is really annoying to update package by package

**Comment by yishaigalatzer** [comment]
@MarcosMeli we plan to. Are you aware that the functionality is supported from the powershell console? Update-Package command does the same.

**Comment by MarcosMeli** [comment]
@yishaigalatzer Yes I know, but I like to check release notes and inspect packages before Update so the GUI is the most used

Just as another feedback the new way the Filter works
Now is a bit cumbersome: The All option loks like it include updates because it said

All
Installed
Upgrade Available

Maybe will be better:

Online
Installed
Upgrade Available

Moving the Filter to the left of package source will be great too because it is the most used option (package source will be practical only to small number of users)

And finally using another control instead of a combo, maybe some flat exclusive buttons or something like that with a preview if there are Updates Available and the count of packages

Online | Installed (12) | Update Available (2)

Just my two cents
Great work BTW :+1:

**Comment by yishaigalatzer** [comment]
Completely agree with the just of your feedback. We have similar thoughts, and we plan to share mocks when we have more concrete design ready.

**Comment by gulbanana** [comment]
Update-Package from the console does not achieve the same purpose as the old upgrade all command. It isn't capable of finding dependencies from other package sources, so you can't use it to update a solution which contains packages from a private feed which depend on the public feed- a common scenario.

**Comment by yishaigalatzer** [comment]
@gulbanana it is supposed to do exactly that (pick all sources by default), are you saying it doesn't work for you?

**Comment by yishaigalatzer** [comment]
@gulbanana  Just verified this works as expected, Update-Package works with all sources. If you have a bug where this doesn't work for you please open an issue and try to provide very specific repro steps.

**Comment by gulbanana** [comment]
https://github.com/NuGet/Home/issues/1293 this is the exact issue i am experiencing. it's not that Update-Package can't cross _all_ sources; what it's no longer capable of doing is updating all packages from _one_ source without updating their dependencies from _other_ sources.

this is important because we have prerelease internal packages which depend on external packages. we do not want to update to prerelease versions of the external packages when using -IncludePrerelease.

**Comment by paulbatum** [comment]
It would be awesome if the Update All UI allowed for you to specify whether the update should be -ToHighestMajor, -ToHighestMinor or -ToHighestPatch for each of your top level packages. Ideally it would default to -ToHighestMinor so that semantic versioning is respected by default.

**Comment by kevingosse** [comment]
To be in par with current requirements while still keeping the efficiency of the NuGet 2.x "Update All" button, the new button could work in two steps: 
- After clicking the button, the list of packages to be updated would appear. From there, you could manually uncheck a package that you wouldn't want to update for some reason (powering a new use-case for NuGet, when you want to update most package except a select few). This UI could also easily provide the necessary options for paulbatum's proposal
- Once everything is configured, the user can press a "start" button, which will start the whole update process

All updatable packages would be selected per default, so users missing the NuGet 2.x "Update All" button would see almost no difference in the workflow (Update All -> Everything is checked per default -> Start). Actually, that button could be renamed to "Bulk update" as it would reflect more accurately the new purpose.

**Comment by yishaigalatzer** [comment]
We are going with a different approach where you will click select all then update. Or check the selection of packages. Overall less clicks.

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
@paulbatum We will support controlling how packages are being updated (major/minor/patch for top level packages and dependencies, we haven't yet decided how the UI is going to look like)

@KooKiz here is a screen shot of the @feiling 's machine showing what its going to look like (final colors and spacing is not done yet)

![image](https://cloud.githubusercontent.com/assets/1238711/10399917/8986ffb2-6e6a-11e5-9cb6-46abfae474d5.png)

**Comment by feiling** [comment]
Multiselect update was done.
