### ISSUE TITLE
NuGet 3.2 dependencies not added to Output for UWP Class Library

### ISSUE THREAD

**Issue by kamenlitchev** [NuGet/Home#1450]
In Visual Studio 2015 (14.0.23107.0) I have a Universal Class Library for UWP. In it I have Json.NET dependency. However, as of lately the Newtonsoft.Json.dll does not seem to get added to the Debug/Release output directory. As a result simply copying the DLLs in the output directory in order to make a "release" does not work.

NuGet 3.2
Windows Software Development Kit - Windows 10.0.26624

**Comment by yishaigalatzer** [comment]
The newtonsoft.json dll should not be copied to the output folder of a class library. It will get added to the app consuming it.

This is an msbuild behavior, and to work around it you can add:

See - C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets, and set CopyNuGetImplementations to true.

These targets are owned by the C# project team, and they are considering flipping the value to true by default in the next release.

@pilchie

**Comment by kamenlitchev** [comment]
Hm, thanks! But why then those get copied to the output for Windows 8 / .NET 4.0 Class Library?

**Comment by Pilchie** [comment]
Hi @kamenlitchev - In a packages.config based world, msbuild's `ResolveAssemblyReferences` task marked libraries that are referenced to be copied.  However, when references come from project.json, we actually give the compiler different references than you need at runtime.  We use contract assemblies from the `ref` directory of the package for the compiler, but at runtime you need the architecture specific binaries from `lib`.

Therefore, when using project.json, the binaries are copied by `ResolveAssemblyReferences`, they are copied by the new task that resolves assets from a NuGet package.  We don't copy the runtime assets by default for libraries, because in general if you are building a library, you don't know which assets need to be copied - will you end up running on desktop or CoreCLR?  On x86 or x64 or ARM?  Will you be compiling with .NET Native or not if it's a UWP library, etc.  Normally, the _app_ controls that, so we copy the appropriate runtime assets in the app, but don't by default for libraries anymore.

Setting the `CopyNuGetImplementations` to true will change this so that we do copy them, but note that if you have architecture specific binaries, you may not get the right assets if you have an AnyCPU class library.
