### ISSUE TITLE
NuGet deletes packages still in use from source control

### ISSUE THREAD

**Issue by alexangas** [NuGet/Home#1467]
Hello, we are seeing a change in behaviour between VS2013 and VS2015 (NuGet 3.2.60914.10516). The scenario is:
- Multiple solutions, each with their own NuGet.config file
- This file has `repositorypath` set so that packages are shared between solutions, instead of each one having its own copy
- The `packageRestore` options `enabled` and `automatic` are both set to true
- `disableSourceControlIntegration` is not specified anywhere

When updating a package in Solution A that is also used by Solution B, the package is deleted from the shared repository directory in source control. It is not deleted from disk. (Because of the latter, the deletion is not always noticed and the change checked in but builds fail.)

Previously I believe NuGet used to check packages in use from a list it kept updated in repositories.config in the root of the shared package repository directory. This no longer seems to happen or packages in use are ignored in some other way.

**Comment by yishaigalatzer** [comment]
I have been asking other folks about this, and apparently this was never an intended feature. Seems like a by accident behavior of  the usage of `repositories.config`.

`repositories.config` was an internal implementation detail designed to optimize querying the project list from the solution and was used as some sort of a cache, that by the way can safely be deleted.

Also note that in the new nuget system (using project.json) the packages folder is indeed shared, but we don't ever delete packages from it.

And in general checking in packages is kinda a bad idea, particularly when you have automatic package restore set up.

Since I don't think that is a feature we ever intended to support, I'm inclined to to fix it. And I'm moving it to the discussions milestone where we can get more feedback.

**Comment by yishaigalatzer** [comment]
Here is a comment from @davidebbo on stackoverflow on the matter. He might have more input on this subject.

**Comment by alexangas** [comment]
That's interesting, thank you @yishaigalatzer. Your comment has reminded me of an issue we used to have under our scenario with NuGet 2.x, if someone created a branch in TFS but only retrieved a part of it to their local computer. The `repositories.config` file would update with only the solutions on disk which then caused NuGet to delete packages required by those solutions not downloaded. Similar build issues resulted.

Since creating this issue I saw another comment in the repo also stating that checking in packages was a bad idea. I've since changed our build process to download the NuGet packages and we no longer have a shared packages folder or `repositories.config`. Hence we no longer have this issue.

**Comment by yishaigalatzer** [comment]
Thanks you! 

As FYI this is a simple way to do a backup local share for your packages in case you lose network connectivity. I wouldn't add it as a source if you don't need to, but it will perform quite well as an alternate. http://blog.nuget.org/20150922/Accelerate-Package-Source.html
