### ISSUE TITLE
nuget.exe update does not update packages if some of the packages are inaccessible

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1490]
nuget.exe update does not update packages if some of the packages are inaccessible.

If there are 2 packages A and B installed to a project and there is 1 package source X. package source X has updates for A, but, there is no package B on X. 

[NOT A REGRESSION from nuget.exe 2.8.*. Is this by design?]

Repro steps:
1. nuget.exe update <projectFile>

Expected:
Package A gets updated OR there is a clear warning message saying why packages were not updated.

Actual:
Package A does not get updated and there is warning message and it is not clear why it does not work.

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Scanning for projects...
Found 1 project with a packages.config file. (ConsoleApplication4.csproj)
Attempting to gather dependencies information for multiple packages with respect to project 'c:\Users\daravind\Documents\Visual Studio 2015\Projects\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.csproj', targeting '.NETFramework,Version=v4.5'
WARNING: Package 'Newtonsoft.Json' is not found

**Comment by fubar-coder** [comment]
It is a regression from 2.8, because this did work there. Now I have to pass the "packages" folder as source to get NuGet.exe to update all other packages just from a single source...

**Comment by yishaigalatzer** [comment]
@fubar-coder thanks for the clarification and following through on the issues. This makes me think we want to take it for 3.3 or immediately after if we don't get to it

**Comment by wgtmpeters** [comment]
I am running into the same problem. We use local repositories which contain only prerelease version to update a solution's prerelease dependencies with locally build prerelease dependencies.

So far i am unable to find a workaround, @fubar-coder  you mentioned that you add your packages folder but that does not seem to work for me.
I tried adding the prerelease source and the solution packages folder as a source but that still does not work as expected.

Update:
The same problem seems to occur when updating prerelease version with only the nuget -Safe option .
When the -Prerelease is not used errors occur that it cannot find the dependency.
It seems that not adding -Prelease will result in nuget.exe ignoring all prerelease dependencies in the source, and therefore it thinks the file is not available.

This did work with nuget 2.8

I have noticed this while using a filter to only update depedencies that i know are in the source repository.  This filter is needed to bypass the earlier problem/bug that this issue is about.

**Comment by yishaigalatzer** [comment]
I'm assuming the issue you are reporting is related but a bit different. It's hard to tell without a small exact repro. Would you mind sharing one? We will make sure your exact scenario is resolved when we fix this issue

Sent from my Windows Phone

**Comment by wgtmpeters** [comment]
I am not sure it is related. 
Issue 1 (this issue) The warning "Package 'x' is not found is given whenever you try and update packages that are in the packages.config but not in any of the source folders.
So as a workaround we add the current solution\packages folder to make sure it finds all the defined packages.

This was not needed in 2.8 and also not wanted because this will make it impossible to simply only update using the source folder packages/versions. Making a solution update slower and less predictable if you are doing local development.

This is the issue that @deepakaravindr and @fubar-coder  also found.
It should simply ignore the fact that a package is not available and update whatever it is in the Source/Sources.
I can understand that an update fails when a transitive dependency is not found in the sources of the update call.

The  other issue is as  follows:

We are updating a packages.config that contain prerelease dependencies.
Normally you should be able to update prerelease dependencies to new prereleases with using only the -Safe options (as mentioned in the CLI documentation).
However it get the warning:
"Unable to find package "x" . Existing packages must be restored before performing an install or update.
The package and its version are in the solution/packages folder for sure.
When i add the -Prerelease switch it does find the package and will be able to update to the new prereleased version in the source folder.
So it seems that the -Prerelease switch is not only about updating but also about how the nuget client searching for the restored packages in the solution/packages folder.

I only want to use the -Safe switch because i do not want to have all dependencies updated to Prerelease version if they are not already a prerelease dependency. This is needed because of issue 1 workaround.

As a work around i tried to create a Powershell script that does the update by filtering on package name adding those that match the filter in the packages.config to the nuget.exe -update packages.config call per project. But this is a lot slower that the solution update call.

**Comment by johnataylor** [comment]
A clear message is now given on the command line in the most recent builds.
