### ISSUE TITLE
NuGet.exe update does not replace the content files

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1498]
c:\school>nuget.exe update SilverlightApplication1\SilverlightApplication1.sln
.... 
Removed package 'jQuery 1.4.4' from 'packages.config'
Successfully uninstalled 'jQuery 1.4.4' from SilverlightApplication1.Web.csproj
For adding package 'jQuery.2.1.4' to project 'SilverlightApplication1.Web.csproj
' that targets 'net452'.
For adding package 'jQuery.2.1.4' to project 'SilverlightApplication1.Web.csproj
' that targets 'net452'.
Package 'jQuery.2.1.4' already exists in folder 'c:\school\SilverlightApplicatio
n1\packages'
Added file 'jquery-2.1.4.min.map' to folder 'Scripts'.
Added file 'jquery-2.1.4.min.js' to folder 'Scripts'.
Added file 'jquery-2.1.4.js' to folder 'Scripts'.
Added file 'jquery-2.1.4-vsdoc.js' to folder 'Scripts'.
Added package 'jQuery.2.1.4' to 'packages.config'
Successfully installed 'jQuery 2.1.4' to SilverlightApplication1.Web.csproj

![capture](https://cloud.githubusercontent.com/assets/1087852/10209592/fc2c768a-6791-11e5-800e-8cfad3b64467.PNG)

**Comment by danliu** [comment]
In 2.8.6, after nuget.exe update, in scripts folder, 2.1.4 version of scripts were added, whereas 1.4.4 versions were removed. It left behind warning signs for jQuery-1.4.4.js etc. In 3.2.1, we left behind 1.4.4 versions. 

Screenshot for 2.8.6

![default](https://cloud.githubusercontent.com/assets/1087852/10211705/ad756f7e-67aa-11e5-9109-5ed90f051805.PNG)

**Comment by danliu** [comment]
IMO, since we can update the references in IDE after nuget.exe update, can we also update content as well. 
Right now, behaviors in both 2.8.6 and 3.2.1 are not ideal.

**Comment by deepakaravindr** [comment]
Note that nuget.exe update cannot update content files properly, since, nuget.exe MSBuild API to edit the csproj file with references. However, it cannot do the same for content files, since, they could be under solution folders and we need ProjectItemContainers to handle this. This is true for 2.8 as well as already stated. Note that nuget.exe update also does not delete old versions of the packages from the packages directory. This is because, nuget.exe update on a project file cannot decide if a package could be deleted or not, since, the packages folder may be used by other projects and so on. Again, this is not a regression.

However, there is a regression in 3.2.1, wherein, nuget.exe does not delete the old content files from the project directory. In the issue's repro steps, it is the files under the Scripts folder under project directory. We will fix that
