### ISSUE TITLE
UI: Allow multiple selection of packages in Updates tab

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1504]

**Comment by wilson0x4d** [comment]
Can we have this feature structured such that we can perform a "select all" without having to scroll. Probably common-sense, but want to make sure we get a 3.3.x delivery that doesn't have a usability issue because it wasn't noted here.

The company I'm currently working for (and two prior, for that matter) has a few dozen packages, hundreds of solutions that depend on them. I can see manually selecting more than one package to perform an "update all" will become a pain (and doesn't align with the "one click" approach VS2013 provided.)

I could deal with 2 clicks per solution.

5-30 clicks per each solution will kill every developer here.

Thanks :)

**Comment by fubar-coder** [comment]
Just a side note: It would be nice if this would also avoid the creation of assembly binding redirects when the assembly to redirect would also be updated to the latest version and no redirect would be required.

**Comment by feiling** [comment]
Implemented.
