### ISSUE TITLE
Can I use Package manager console powershell outside visual studio?

### ISSUE THREAD

**Issue by GERMANOCARELLA** [NuGet/Home#1512]
I know it is nuget.exe, but it doesn't have uninstall command, find-package command etc. I uninstalled visual studio and I must uninstall some packages from nuget, but, without vs i can't do this. There is a way to run package manager console powershell outside visual studio?

**Comment by davidfowl** [comment]
Nope

**Comment by yishaigalatzer** [comment]
There is no way to do that outside visual studio. You can remove the references manually (content is a bit trickier).

**Comment by dprothero** [comment]
Could this be a feature request? Or is this something that would not even be feasible?

**Comment by yishaigalatzer** [comment]
All that package manager console is providing is access to visual studio objects, so for most packages and scenarios it just wouldn't do a thing.

An uninstall package command for common scenarios (like csproj files without fancy targets) might be able to be built

**Comment by doronshai** [comment]
in PM i have the option to run Update-Package and then the packages.config is updated for each dependencies with the latest avaialbe in artifactory. How can I do it without the studio? via Jenkins...
I tried to use "nuget update mySolution.sln" but it does not do it....

**Comment by hermot** [comment]
I also need to use command line "nuget update mySolution.sln", but it does not update binding redirects in web.config / app.config files.
csproj and packages.config files are updated correctly, just not the app.config / web.config files. Is this a bug or missing feature?

**Comment by mahlzeit** [comment]
The CI scenario is important for me, too. I want to add a nuget package only for (customer) specific builds of a project, so that modules are only included and deployed if needed. So I change the packages.config in the Jenkins build job to include the nuget package and then use nuget cli to restore the packages. That works all good for the binaries included in the nuget package, but not for the content files like CSS, JS, HTML etc. as the csproj is not updated and therefore these files will not be part of the resulting build...

I would love to use PM `Update-Package -reinstall` option in the Build Slave powershell (which should solve the issue I guess).

PS: Any other ideas are very welcome ;)

**Comment by yishaigalatzer** [comment]
You can install visual studio an automate it. This is how our functional tests work. Installing a package is really just automating visual studio. Here is a sample: https://github.com/NuGet/Entropy/tree/master/NuGetFunctionalTestsLauncher

Alternatively consider using bower for delivering CSS and JavaScript (which is a good way forward anyways).

**Comment by mahlzeit** [comment]
Fair point. That should do it as well, although we found another (pretty simple) way in the meanwhile to add all kind of additional files needed. Octopack came to the rescue, as it provides an option to handle the <files> section of a nuspec you add to the project not as an exclusive list, but as "on-top of everything I would normally add based on the csproj file" list ;)

If somebody is interested in more details, see: http://stackoverflow.com/questions/38354630/how-to-inject-nuget-package-in-jenkins-ci-build-job

PS: The last sentence is my feature request for nuget cli :)

**Comment by HarelM** [comment]
I have the following scenario which I have trouble solving:
I have locally created NuGet packages created from open-source projects which are having hard time migrating to .Net core.
While I wish these project finish the migration to .Net core this is not the case.
Since I can't add reference to local .DLL file I need to locally create a nuget package and reference it in the project.
Now I need my CI to be able to build my project.
I need to run Install-package <local-nuget-file-that-is-currently-in-source-control> outside visual studio, How do I do it?

**Comment by davidfowl** [comment]
@HarelM I have some questions:

- Why not push those packages to a myget feed or an internal feed accessible by the CI?
- Why would you need to run install package in this scenario? Aren't you already referencing them?

**Comment by HarelM** [comment]
1. This is what I eventually did, but this assumes I have an internal feed, which might not be the case for everyone.
2. I might be doing it wrong but I haven't found a way to let NuGet know that I have a local package without using install-package command on local NuGet file.

**Comment by benwtrent** [comment]
My issue is that `update` from the given nuget command line interface does not automatically update (as stated in the docs `If an updated package has an added assembly, a new reference is not added`). So, I have to do updates via the package management console, and if I wanted to automate this through some CI server, the work around gets pretty nasty.

https://github.com/Computician/PMCCommand is what I came up with. If there is a better way, please, let me know

**Comment by skolod** [comment]
I cannot update from Nant build script NuGet package that is referenced directly from CsProj via ProjectReference element, while I can do it from VS, because VS launches NuGet Package Manager before MsBuild. I choosed PackageReference format because it allow to write a floating version of package (1.8.0-beta*). I think it is not right that I cannot reproduce VS build process in command line.
The problem is solved when I added /r option to MsBuild command.

**Comment by kevmoens** [comment]
I had been looking for a way to run the Update-Package -reinstall command because I had a NuGet with content only and I wanted it restored each time we clone the package.  I found out that .props or .target files can be used to get ran before the build to pick up these files in the Packages directory.  That solved my issue.
