### ISSUE TITLE
`nuget.exe` creates ugly `~/.nuget\packages\` folder on Linux

### ISSUE THREAD

**Issue by dougbu** [NuGet/Home#1517]
For example `mono .nuget/nuget.exe install Sake -ExcludeVersion -Out packages` correctly downloads the Sake package and installs it into `$PWD/packages/Sake`. However it also expands the package content into `~/.nuget\packages\/Sake`. Obviously `nuget.exe` contains at least one hard-coded Windows path separator.

**Comment by dmccaffery** [comment]
I cannot reproduce this on OS X, as an FYI.

**Comment by akoeplinger** [comment]
Looks like it comes from here: https://github.com/NuGet/NuGet.Client/blob/c20345326cf66a4c6d2791a180426ce459427771/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L14

@yishaigalatzer would be great to get this into 3.3 since it looks like a simple fix. I can also send a PR if you want.

**Comment by yishaigalatzer** [comment]
Go ahead and send a pr

**Comment by akoeplinger** [comment]
https://github.com/NuGet/NuGet.Client/pull/123
