### ISSUE TITLE
Improve embeddeding NuGet packages as part of a template/vsix

### ISSUE THREAD

**Issue by nehmebilal** [NuGet/Home#1530]
Embedding NuGet packages in a VSIX is currently very very painful. 

As far as I understand from the [documentation](http://docs.nuget.org/create/packages-in-visual-studio-templates), all the .nupkg associated with the NuGet packages to be installed to a project template **and all of their dependencies** must be downloaded from the NuGet gallery and included in the VSIX.

There are several issues with this respect:
1. Manually resolving the dependency tree to download each and every NuGet dependency can take hours or days if the dependency tree is big. Why would one do that manually if the NuGet gallery already knows the dependency tree?
2. The time it takes to creates a new project from a project template that contains embedded NuGet packages is too long. It’s better to move the download to build-time and not project creation time (because that’s expected to take longer).
3. The VSIX is bigger and bigger for no reason. All what the VSIX needs to know theoretically is the package id and version of the dependency. The NuGets are available in the NuGet gallery and copying them is pointless.

Is there a better way to author visual studio templates that use NuGet packages? If not, is there any plans to address this issue?

Thanks!

**Comment by yishaigalatzer** [comment]
1. You can install the packages into your project once through nuget UI. That will resolve the first item.
2. It does take longer to install the project, but that is the expected behavior. Users will otherwise get a broken project as soon as they start their projects
3. The VSIX is bigger for a good reason. It allows you to install the packages even if your visual studio is offline. You can go to nuget gallery to create a project, but in that case you wouldn't use the project wizard and you will author your own steps to install packages using IVsPackageInstaller.

There is no plans to make changes in this area at the moment.

**Comment by nehmebilal** [comment]
You still need to download all the .nupkg manually and add them to the VSIX project. Installing packages into the project helps resolving the dependency tree but the experience of creating a VSIX with NuGet packages is still painful and the VSIX is hard to maintain (updates to NuGets means resolving the dependency tree again and finding out which .nupkg need to be replaced).

**Comment by yishaigalatzer** [comment]
You don't need to manually download them manually, they get dropped into the packages folder of your project.

Creating and maintaining a vsix is not something we can speak to, NuGet does not own it. I'll point you offline to other solutions for building templates.

**Comment by emgarten** [comment]
This is fixed by automatic package restore with PackageReference projects in VS 2017.
