### ISSUE TITLE
Failure to install portable nuget packages in VS 2013 + NuGet 2.8.60273.765

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#1563]
**Setup**
- Visual Studio 2013 Update 4
- NuGet 2.8.60273.765

**Repro steps**
- File -> New Project
- Class Library (Portable)
- .NET Framework 4.5 + Windows 8
- Tools -> NuGet Package Manager -> Package Manager Console
- `Install-Package System.Collections.Immutable -Version 1.1.36`

**Expected result**
Package installs successfully

**Actual result**

```
Install-Package : Could not install package 'System.Collections.Immutable 1.1.36'. You are
trying to install this package into a project that targets 'portable-net45+dnxcore50+win', but
the package does not contain any assembly references or content files that are compatible
with that framework. For more information, contact the package author.
```

At first, I thought this might have something to do with version 1.1.37 also having a 'dotnet' folder for nuget 3, but then I tried with version 1.1.36, which does not and definitely worked in Visual Studio 2013 previously...

**Comment by yishaigalatzer** [comment]
I would guess that this could be because of the changes that added dnxcore50 without coordinating with nuget changes.

@ericstj @emgarten

**Comment by emgarten** [comment]
@yishaigalatzer that would be my guess. There is no other way to get dnxcore50 into a portable framework for the project otherwise.

**Comment by yishaigalatzer** [comment]
@nguerrera looks like the .NET team/PCL team needs to revert their changes.

@ericstj @pilchie

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/1562

**Comment by LaylaLiu** [comment]
OData Nuget package installation on a portable library has the same issue.

**Comment by yishaigalatzer** [comment]
@Laylaliu the issue here is not in nuget in .net setup from updating vs2015 to rc, is this your case?

Can you be more specific about your scenario?

**Comment by LaylaLiu** [comment]
@yishaigalatzer, you are right. I think a new profile should be added instead of change this old one. But i also have a quesiton. This profile also contains Xamarin.iOS.xml framework file, but the installation doesn't require this framework?

The error is like this. 
Could not install package 'System.Spatial 5.7.0'. You are trying to install this package into a project that targets 'portable-net45+dnxcore50+win+wpa81+wp80', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ericstj** [comment]
I believe this was already fixed just didn't make it into the public build.  @nguerrera if you install a later build of 2015 Update 1 it should be resolved.
