### ISSUE TITLE
Global Package Management

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1604]
_From @briandrennan on October 18, 2015 6:5_

Hi,

I see there's support for a single download repository on the hard drive in the NuGet docs, but there is no (good) way to let that location be the one referenced by the package manager when you're working on a project. Would like to see support for global package management on the local client, with support for networked drive and server paths so that teams can have locally shared repositories, removing a need for downloading the same packages multiple times. (I use Newtonsoft.Json quite a bit, and have it referenced in several projects).

The best way I've found to manage packages within a solution right now is <HintPath>$(SolutionDir).nugget[packagename]</HintPath>.

_Copied from original issue: NuGet/NuGetGallery#2737_

**Comment by maartenba** [comment]
_From @briandrennan on October 18, 2015 6:12_

By the way, I wouldn't mind working on this one myself if the community agrees it would be a good feature.

**Comment by yishaigalatzer** [comment]
There are two ways to support this, but I would definitely not recommend it to be used across a team, you are opening yourself up to all kinds of trouble (imagine a team member replacing a package on a test project).
1. You can define in nuget.config a package folder (for packages.config scenario). There are people using it across projects, but the cleanup feature will get in your way (because there is really no good way to access all the projects using the packages folder). Perhaps a small tweak settings to say - Don't remove unused packages from the packages folder is all you need to make this fully working.
2. The new project.json support uses a common packages folder, we plan to expand support for features in this mode, so more and more project types will be able to natively support it. It works today pretty nicely for UWP and PCLs, and although not officially it works for console app and normal class libraries. The next phases of adding content will enable more scenarios and packages (scheduled for our next release). Similarly ASP.NET 5 is already in this mode.

**Comment by briandrennan** [comment]
I thought the idea was that NuGet would manage the dependencies on a per-project basis? I understand having a local config to the solution folder - that part we're sort of doing (on new development where we use nuget), but as a colleague pointed out to me, it would just be a nice feature to have a global folder for downloads so that common ones aren't duplicated across the file system. I know simply having access to the system environment variables makes this pretty easy - parse anything inside a percent and then do a string replace. We were trying to achieve something like %systemdrive%\dev.nuget.

I'll have a look. One other thing I haven't investigated fully was the scenario of nuget automatically making references to nuget packages relative. I've been setting mine up with a reference to the solution directory after they're installed, so they always refresh to the same place across environments.

Still somewhat new to the tech, so will try to have a look at the docs to find the most suitable solution. Thanks for the reply!

Best regards,

Brian Drennan

Sent from my Windows Phone
