### ISSUE TITLE
On UI, CheckLicenseAcceptanceAsync fetch UIPackageMetadata for each package, it takes up 23% of whole install time

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#1640]

**Comment by johnataylor** [comment]
This is a fetch for registration blobs. This should now be significantly better because they are compressed to 20% of the original size which on some networks will be noticeable.

However fundamentally this data is needed. And its probably not reasonable to have it all in the initial search result because it involves the metadata for all the dependencies.

When we introduce more effective client caching (which is dependent on having a reasonable way to bust caches when we need to) this scenario should also improve. This is an early stage design level discussion not tracked with issues at this point.

**Comment by emgarten** [comment]
Re-opening this for tracking. Compression does not fix the extra network call here. Search might be a different scenario but for the non-latest version the registration blobs are still being fetched twice with no caching.

**Comment by jainaashish** [comment]
Fixed with 25ff09d3ba6cafecfba67c7f3a0610a3f650324c
