### ISSUE TITLE
NuGet -verbosity quiet doesn't show errors and warnings

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#1648]
Due to the large amount output of `NuGet restore -verbosity normal` blowing through our output buffer on our Roslyn Jenkins server, we've needed to reduce the verbosity to `quiet`. 

NuGet, however, unlike most command-line tools doesn't output errors/warnings in `quiet` mode, so either you need to live with the noise of `normal` or put up with not knowing when something went wrong.

**Comment by xavierdecoster** [comment]
I'm only seeing very few places in the nuget.exe code base where we check the verbosity flag before logging warnings.

@davkean Do you have any specific examples of warning/error messages you no longer see when running nuget with `-verbosity quiet`? It might help me trace the code path that could be affected.

The nuget.exe console writes warnings to `stdout` and errors to `stderr`. I'd assume it does, but are you 100% that Jenkins picks these up correctly? Does it also happen outside of Jenkins?

**Comment by deepakaravindr** [comment]
By default, all the info messages are shown along with errors and warnings. Because, default Verbosity is normal. However, when '-Verbosity Quiet' is used, no messages are shown. This is the bug.

Sample snapshot is shared below based on the 'init' command. 

![image](https://cloud.githubusercontent.com/assets/2380340/11352940/5727c008-91f4-11e5-9f89-415c16cca243.png)

After a fix, it will look like the following. Note that warning messages are shown with Verbosity as Quiet.

![image](https://cloud.githubusercontent.com/assets/2380340/11353139/5dfdfc16-91f5-11e5-8ceb-8ddb3de0c70c.png)

**Comment by ironicnet** [comment]
I know that this bug is closed... but when using a batch file to upload several files...the errors appears in other output stream...

for instance I have this inside a bat: 
`for /f %%f in ('dir /B NugetsServer\Packages\*.nupkg') do nuget push NugetsServer\Packages\%%f -Source PackageFeedUrl -ApiKey FeedApiKey -ConfigFile Nuget.Config`

If i run the .bat like this: 
`uploadpackages.bat > results.txt`
i get the following: 
![image](https://cloud.githubusercontent.com/assets/822050/14566229/f5bc7cc8-0304-11e6-981b-55c5eeb4330d.png)
While in the .txt i don't have the error message...

So it's a little frustrating to see which packages failed and which one didnt...

**Comment by davkean** [comment]
Redirect the error stream: http://www.robvanderwoude.com/battech_redirection.php

**Comment by ironicnet** [comment]
Thanks @davkean. After seeing the code, i see that is writing to the error output.
So the proper command line is:
`.\uploadpackages.bat > UploadResults2.txt 2>&1`

Thanks and sorry for bothering you!
