### ISSUE TITLE
Automatic import of props at top of project file is not always correct.

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1669]
_From @aodennison on November 1, 2015 6:20_

(V 2.8.50926.663) Automatically inserting the include of "xxx.props" file at top of the csproj file does not work if the properties refer to certain MsBuild symbols. It causes MsBuild/VS to throw errors.

For example, the following fails with an unhelpful error about an invalid startIndex passed to Substring if it is included at the start of the project; presumably because TargetFrameworkVersion is not defined yet. It works fine if it is included at the end of the project.

build\Framework.Compilation.Symbols.props

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <DefineConstants>
            $(DefineConstants); TFV_$(TargetFrameworkVersion.Replace("v", "").Replace(".", "_"))
        </DefineConstants>
        <DefineConstants Condition="$([System.Version]::Parse('$(TargetFrameworkVersion.Substring(1))').CompareTo($([System.Version]::Parse('4.6'))))   &gt;= 0">$(DefineConstants);NETFX_46</DefineConstants>
    </PropertyGroup>
</Project>
```

While the documentation [https://docs.nuget.org/release-notes/nuget-2.5]  does say: "The .props file is added at the top, whereas the .targets file is added to the bottom." The implications of this are not obvious. The lack of other documentation/examples make this difficult to debug.

Below is an example which does work as intended, but only if the included properties file is deliberately misnamed "Framework.Compilation.Symbols.targets" so that NuGet insert the include at the end of the csproj file. If it is is named "Framework.Compilation.Symbols.props" it fails.

The entire nuspec is here for completeness. The relevant line is:

```
<file src="build\Framework.Compilation.Symbols.targets" target="build\Framework.Compilation.Symbols.targets" />
```

Framework.Compilation.Symbols.1.0.0-alpha.nuspec

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
    <metadata minClientVersion="2.8">
        <id>Framework.Compilation.Symbols</id>
        <version>1.0.0-alpha</version>
        <authors>Andrew O. Dennison</authors>
        <owners>Andrew O. Dennison</owners>
        <projectUrl>http://stackoverflow.com/questions/3436526/detect-target-framework-version-at-compile-time/29001688?noredirect=1#comment53939916_29001688</projectUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <developmentDependency>true</developmentDependency>
        <description>Defines the cummulative (backwardly compatible) set of compile-time constants for conditionally compiling version dependent code. E.g. if the csproj Target framework specifies ".NET Framework 4", then NETFX_40, NET_35, NETFX_30 and NETFX_20 are defined.
Also defines TFV_XXX, where XXX is the target framework. E.g. TFV_451</description>
        <summary>Defines the .NET Framework version compile time symbols Microsoft forgot: E.g. NETFX_46,  NETFX_45 .. NETFX_20</summary>
        <releaseNotes>1st release (alpha)</releaseNotes>
        <copyright>Copyright © 2015 Andrew O. Dennison. All Rights Released.</copyright>
        <tags>.NET csproj vbproj version-specific compile-time-constants</tags>
    </metadata>
    <files>
        <file src="build\Framework.Compilation.Symbols.targets" target="build\Framework.Compilation.Symbols.targets" />
    </files>
</package>
```

_Copied from original issue: NuGet/NuGetGallery#2766_

**Comment by yishaigalatzer** [comment]
The documentation seems pretty clear to me, what you see is the fact that is is hard to debug msbuild. So I'm not following what is the suggestion here?

**Comment by aodennison** [comment]
Thanks for taking a look at my report.

To summarize:
- Inserting a properties include at the start of the .csproj did not
  work for my use case because of the properties I am setting.
- To get nuget to insert a properties include at the end of the project
  I had to rename the properties file to "something.targets."
- Renaming the file works, but it is not obvious. It will not be obvious
  to any future maintainer why I have deliberately named a properties include
  file with a .targets extension. It looks like I am using the wrong feature
  to accomplish something which should be simple.

My suggestion is that the mechanism be extended to allow for inserting an
include of any type of file, at the start or end of the csproj or elsewhere
if there is a use case for that.

If my use case is rare then update the documentation to reflect this is a
known/intentional limitation of the feature and suggest using powershell to
accomplish my unusual case as shown here:
http://www.bryancook.net/2013/05/props-files-and-nuget-25.html

Thanks again.

**Comment by yishaigalatzer** [comment]
Thanks for getting into the details, it wasn't immediately obvious to me from the onset how this was confusing. So I see your point, and given than this is indeed a relatively rare case. I think we should keep the NuGet feature as is. Modifying it means that we are creating a new package convention that will only work for new nuget clients, which will create IMHO more trouble than value for this case.

I'll be more than glad to change the documentation, and instead of continuing to discuss it over this issue, let us do it over a pull request with your suggestions? It is rather easy to do, just go to this [link](https://github.com/NuGet/NuGetDocs/blob/master/NuGet.Docs/Release-Notes/NuGet-2.5.md) and click the  ![image](https://cloud.githubusercontent.com/assets/1238711/11732336/1b7e7b0c-9f58-11e5-8e04-6d717aadacb8.png) button. You can push the submit pull request button right from there.
