### ISSUE TITLE
nuget client ignores no_proxy setting

### ISSUE THREAD

**Issue by tallandtree** [NuGet/Home#1671]
When you are behind a corporate proxy, you often have to specify environment variables http_proxy, https_proxy and no_proxy for tools like npm, git, nuget, etc.
But if you have an inhouse nuget repository, nuget client fails as it does not respect the no_proxy setting. It tries to find our local nuget repository via the proxy (http_proxy), and therefore fails as the proxy is not aware of our local servers. 
No difference if you specify it via the nuget config or via environment variables.

Nuget should respect the no_proxy setting like other tools.

**Comment by yishaigalatzer** [comment]
The story here is that your proxy should be considered to understand what URLs are inside your network and which are out.

Since we support multiple sources, a simple no_proxy environment variable will not work, and we need to think of something more elaborate here.

Moving this out to a future milestone to be considered.

CC @anurse @feiling

**Comment by tallandtree** [comment]
I do agree with you that proxies should understand the local servers, however: that is not always the case and we can't change our companies proxy policy. 
Allmost all other tools do respect the "no_proxy" setting. Nuget is an exception. If no_proxy contains wildcards and ',' separated, multiple sources are supported.
Definition **no_proxy**: This variable should contain a comma-separated list of domain extensions proxy should _not_ be used for.  For instance, if the value of _no_proxy_ is _.mit.edu_, proxy will not be used to retrieve documents from MIT.
Hope it can be implemented as that will save us a lot of time and build configurations will be much simpler.

**Comment by analogrelay** [comment]
Yeah, `no_proxy` and `http_proxy` are pretty well-known environment variables (like `PATH`, etc.). It would be good to have NuGet support it.

**Comment by patthoyts** [comment]
It would help a great deal if when the proxy instance was created in ProxyCache.cs one of the other constructors was used that includes the `BypassOnLocal` parameter (https://msdn.microsoft.com/en-us/library/234s6ee9(v=vs.110).aspx). The default .Net WebProxy successfully picks up this setting from the system's IE settings but in NuGet the proxy object used does not appear to set either the `BypassOnLocal` property nor populate the `BypassList` which is where the values from `NO_PROXY` should be placed. If NuGet is to use the HTTP_PROXY environment variable to allow setting the proxy then it is important that it also use the corresponding HTTPS_PROXY and NO_PROXY values to interoperate with other software using the unix convention. In particular this currently plays poorly with a system configured to work with Git and GitHub.

**Comment by forderud** [comment]
Any progress on fixing this issue?

**Comment by yishaigalatzer** [comment]
no, it looks more and more like this might be bumped to the next version

**Comment by jmaxxz** [comment]
:+1: this issue. Look forward to seeing pull [#234](https://github.com/NuGet/NuGet.Client/pull/234) in a released version.

**Comment by WayneEllery** [comment]
@jmaxxz I look forward to this issue being fixed too. But how is issue #234 related to this issue?

**Comment by jmaxxz** [comment]
@WayneEllery it is not, this organization is laid out a little strangely. This resulted in the autolink pointing not  to the pull request I was speaking of but another issue (because this repo seems to act as an issue tracker for all the other repos in this org). I have updated my original comment to avoid any future confusion.

**Comment by forderud** [comment]
As of today, NuGet 3.x only has partial support for `no_proxy`, since V2 sources are not fully supported. Full V2 support was merged in https://github.com/NuGet/NuGet2/pull/41, but the current 2.11.0 version version of `NuGet.Core` used by NuGet 3.x predates this fix.

Someone therefore need to pull in a newer version of `NuGet.Core` before resolving this issue.

**Comment by yishaigalatzer** [comment]
Merged, and will be released in nuget,exe 3.4.2

**Comment by ghost** [comment]
This is still a problem; whichever `NuGet.Client` version is included in **.NET SDK 5.0.301**, it ignores `no_proxy` config setting. Cause is different, but the effect is the same.

Fix will be available starting from .NET SDK 5.0.400

See: #10932 and #10902
