### ISSUE TITLE
Feature Request: Add 'Browse' button to UI

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1698]
From the user interface, I would like to be able to browse to a location on disk and add a package directly without having to configure a package source for a folder on disk.

**Comment by punitganshani** [comment]
How will these CI work for these manually added NuGet packages?

**Comment by csharpfritz** [comment]
If the package isn't moved to a repository the CI or other developers can access, they'll fail restore with a typical "cannot install package" error. 

This is to help with the "testing a package" scenario.

**Comment by emgarten** [comment]
For project.json a package testing feature would also need a way to override packages in the global folder since it is likely that the user will be testing the package multiple times with the same id and version. Today that package would get added to the global folder the first time, and then ignored afterwards.

**Comment by punitganshani** [comment]
If a package needs to be tested, a new solution can be used or REPL can be used instead of manually referencing the package. 

Altering project or project.json for testing local packages and finding that the package is not present during team collaboration, in my humble opinion, isn't the best implementation.

**Comment by yishaigalatzer** [comment]
I don't think we should build this feature. It will just create a problem downlevel, as soon as you try to restore package.

**Comment by yishaigalatzer** [comment]
repl is going to support this at some point. 

A potential implementation for this is to detect if the package is already in one of the local sources, then add it from there. Otherwise copy it over to a local folder and add the folder as a source.

We should consider this if/when we integrate nuget with `add reference` UI

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
