### ISSUE TITLE
nuget locals -Clear fails with a bad error message

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1722]
When a file is locked or some other error happens we log this not very useful error.

Cache clear failed: one or more errors occured.

**Comment by xavierdecoster** [comment]
@deepakaravindr do you have an exact repro? There are many ways to simulate this, so I want to verify the exact same situation you encountered when logging the error.

Note that we compromised on detailed error messages in order to avoid custom recursive code, and instead leverage the .NET API `Directory.Delete(..., recursive: true)`. 
The error message thrown by this API when a file handle is locked (e.g. open an http-cache file in notepad) is rather moot:

>  Exception thrown: 'System.IO.IOException' in mscorlib.dll: "The directory is not empty."

However, the file will be deleted.
See also: https://github.com/dotnet/corefx/issues/3993

**Comment by deepakaravindr** [comment]
@xavierdecoster @yishaigalatzer 

No, I don't. Yishai and I were debugging an issue with package extraction on my machine. And, we encountered this error. So, we filed the bug to track the issue.

**Comment by xavierdecoster** [comment]
Besides reverting to the original design of doing recursion over the file system in own code, there's no way to get granular error messages.

**Comment by yishaigalatzer** [comment]
If we have to, then lets do it and add tests to cover it
