### ISSUE TITLE
Odd behaviour with DataTables.AspNet

### ISSUE THREAD

**Issue by PhilPJL** [NuGet/Home#1742]
I've raised this problem with DataTables.AspNet but their opinion is it's a Nuget issue.

See attached screenshot.  In VS2015, Filter='upgrade available',  Include prelease = false.
DataTables.AspNet is used by 1 project.
The pre release version of DataTables shows up as applicable to all projects in the solution.

This doesn't happen in VS2013 with Nuget 2.

![capture](https://cloud.githubusercontent.com/assets/271656/11143709/13def026-89ef-11e5-8663-742b6de9215e.PNG)

**Comment by yishaigalatzer** [comment]
Thanks for your feedback!

We have changed the UI in 3.3. So it should be a bit more easy to understand, but in general this UI says that you can install that package into all these other projects in one go.

I realize the way it shows up right now is confusing which is why we redid the UI to make it clearer.

We plan to release in a few weeks, and feel free to update to 3.3, and provide more feedback if you think it still needs work.

**Comment by PhilPJL** [comment]
@yishaigalatzer I think one of us is missing something.

1) 'include preprelease' = false, but a pre-release item is appearing
2) datatables.aspnet is used/referenced by 1 project not 100 so it should only offer to update 1 project

This is what happens for other packages.

**Comment by yishaigalatzer** [comment]
Like I said we addressed your concerns in 3.3. Shoot me an email if you want to preview.

Y I g a l a t z @msft.com
