### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by jmelosegui** [NuGet/Home#1754]
I am getting this error when ever I try to install a package from https://api.nuget.org/v3/index.json

```
Install-Package : A task was canceled.
At line:1 char:1
+ Install-Package Microsoft.AspNet.Mvc
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by yishaigalatzer** [comment]
What version of nuget are you using? What version of visual studio? What else is installed in your project? Did this work for you in the past and stopped working?

**Comment by joyhui** [comment]
Here is the request list when I execute the same command. It is working will in my computer.
Install-Package Microsoft.AspNet.Mvc

HTTPS://api.nuget.org/v3/index.json
HTTPS://api.nuget.org/v3/registration1/microsoft.aspnet.mvc/index.json
HTTPS://api.nuget.org/v3/registration1/microsoft.aspnet.webpages/index.json
HTTPS://api.nuget.org/v3/registration1/microsoft.aspnet.razor/index.json
HTTPS://api.nuget.org/v3/registration1/microsoft.web.infrastructure/index.json
HTTPS://api.nuget.org/packages/microsoft.aspnet.razor.3.2.3.nupkg
HTTPS://api.nuget.org/packages/microsoft.web.infrastructure.1.0.0.nupkg
HTTPS://api.nuget.org/packages/microsoft.aspnet.webpages.3.2.3.nupkg
HTTPS://api.nuget.org/packages/microsoft.aspnet.mvc.5.2.3.nupkg

Can you try to make the requests manually (chrome, IE, or Fiddler)? It could help to isolate whether it is network issue or not. 

Please also provide information Yishai suggested. It will help us identify the problem faster.

**Comment by jackywang615** [comment]
I have the same problem when I install/restore package from nuget.org. 
This problem is began on last friday.
When I use commandline to install or restore package. most packages will display "Unable to find version **\* of package ****\*  "

![1](https://cloud.githubusercontent.com/assets/9586655/11367580/8fc9a0f6-92ef-11e5-928a-5846a93516ca.JPG)

![default](https://cloud.githubusercontent.com/assets/9586655/11367537/562c5fdc-92ef-11e5-8af9-1862cf73ef5e.PNG)

# Visual Studio Version

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00888-AA285
Microsoft Architecture and Modeling Tools

UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90150-00888-AA285
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00888-AA285
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00888-AA285
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00888-AA285
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC)   14.1.11116.0
ASP.NET and Web Tools 2015 (RC)

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

BuildVision   1.3.1.27
Building process visualization.

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

JetBrains ReSharper Ultimate 10.0.1   Build 104.0.20151114.160203
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

**Comment by joyhui** [comment]
@wanghaolu can you try to request the following URL using IE/Chrome/Fiddler directly?
HTTPS://api.nuget.org/v3/registration1/microsoft.aspnet.razor/index.json
HTTPS://api.nuget.org/packages/microsoft.aspnet.razor.3.2.3.nupkg

@jmelosegui , @wanghaolu , can you share your email? We can send latest NuGet client (They will be release very soon) to you, which may fix the connection problem.

**Comment by wanghaolu** [comment]
@joyhui I can access. my email is: jackyhaolu@163.com

**Comment by joyhui** [comment]
@wanghaolu @jmelosegui 

Can you also try this:
1. MTR log
    http://winmtr.net/how-to/
    Use MTR tool to api.nuget.org, wait for sent >=100, copy text to clipboard
![capture](https://cloud.githubusercontent.com/assets/4565352/11383299/1dcfb522-92bc-11e5-96a9-cf820e4b2666.png)
1. Please let me know your geographical area.. where are you, if 1# report lots of missing package.

**Comment by joyhui** [comment]
Based on MTR log from @wanghaolu, here is our investigation result: 

The problem it's not related the China Firewall. The customer's Internet Service Provider (Chinanet) is experiencing network issues. Their router on 202.97.60.5 is showing 98% packet loss. We suggest having the customer open a ticket with Chinanet and provide them with the MTR.
