### ISSUE TITLE
How to create own Nuget v3 feed?

### ISSUE THREAD

**Issue by SharpNoiZy** [NuGet/Home#1756]
Hi, maybe I'm stupid, blind or both :)
But how do I create my own NuGet feed with v3 like I done it for v2.
Install Nuget.Server into Webproject and it was done.
But this server is nuget v2.

Kind regards

**Comment by emgarten** [comment]
There's no NuGet.Server v3 yet. To help with this would you tell me what your scenarios are? Will you have a v3 authenticated feed, and would you prefer that it be static content, how would you ideally want to host the v3 feed?

**Comment by SharpNoiZy** [comment]
We have currently an private v2 feed only for our company.
I want to upgrade this to v3, to share also corefx nuget packages.

So, I need something running on one company reachable server, nothing local on my PC.

**Comment by yishaigalatzer** [comment]
We do need to update the server, but you don't actually need a V3 server for that. @joyhui we need to update the nuget.server package.

Lets move the bug over to the nugetgallery.

[ ] we want to make sure that all the new packages are supported (DNXCORE50, generations, etc.)
[ ] use the new folder structure supported by nuget.exe init command

**Comment by yishaigalatzer** [comment]
@maartenba is working on a new version of nuget.server, that should support your scenario.

@maartenba can you please verify that corefx packages can be hosted on the server, and can you share early bits with @SharpNoiZy

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2844

**Comment by wpostma** [comment]
Currently it seems Visual Studio doesn't work with Nuget V2 feeds provided by a home-brew "new project with nuget.server 2.22 added".

**Comment by yishaigalatzer** [comment]
I would start by making sure I have the latest nuget.server installed, along with the latest nuget.core as well as latest nuget extension for visual studio. Things do work and we regularly test it, so that would be a good first step to make sure "home-brew" isn't stale ;)

If that doesn't work can you please open an issue on the nugetgallery repo with exact details of what doesn't work?

Please include versions of visual studio/nuget extension/nuget.server/nuget.core used with the server/and what packages/TFMs you are using.
