### ISSUE TITLE
V3+V2 restore fails when server responds to FindPackagesById() with 204-No content

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1759]
_From @jesperll on November 24, 2015 13:51_

I have a Visual Studio 2015 windows 10 app project with references to packages from both nuget.org(V3) and a local TeamCity server(V2). 
During package restore TeamServer is queried for all packages and responds 204 No content to the ones it doesn't know. This causes restore to fail.

_Copied from original issue: NuGet/NuGetGallery#2784_

**Comment by emgarten** [comment]
@jesperll would you provide the nuget restore output with the errors?

Also, what version of teamcity server is it?

**Comment by jesperll** [comment]
It writes "Root element is missing" a bunch of times in the Visual Studio output pane and then just stops.

TeamCity 9.1.4 (latest version)
There's a corresponding issue at TeamCity's issue tracker : https://youtrack.jetbrains.com/issue/TW-39211
The real question is whether 204 is an allowable response but since it works with nuget 2.x I think it should work for v3 as well.

I had a go at looking through the source and found:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/RemoteRepositories/HttpSource.cs#L120 treats 204 as successful and returns the _empty_ response.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/RemoteRepositories/RemoteV2FindPackageByIdResource.cs#L148 tries to load the empty stream into an XmlDocument and fails.

**Comment by yishaigalatzer** [comment]
Looks like the TeamCity server is completely breaking the http protocol and we have supported it in the past unfortunately.

I'm not convinced that we want to bring these hacks back, but will have a discussion with the team on this and reply here.

Note that this bug has been now opened for a full year on the teamcity server. @maartenba do you know who to reach to over there?

**Comment by jesperll** [comment]
If it helps, I think the TeamCity bug is assigned to https://twitter.com/lodkin

**Comment by maartenba** [comment]
Best to check with @ekoshkin

**Comment by yishaigalatzer** [comment]
Having discussed this with the team, we are not inclined to take a fix for this. Although it is not too complicated, it is going to persist a bad legacy.

**Comment by yishaigalatzer** [comment]
@ekoshkin any chance this is getting resolved any time soon?

**Comment by ghost** [comment]
@yishaigalatzer I'll do my best to fix [this particular issue](https://youtrack.jetbrains.com/issue/TW-39211) in scope of next TeamCity bugfix update. 
As for TeamCity NuGet support in general - we are thinking about dropping internal feed functionality since its very time consuming task to provide consistent production ready high performance feed and its out of scope of CI tool development.

**Comment by yishaigalatzer** [comment]
Closing this issue, as we don't want to support this misbehavior of the server.

**Comment by emgarten** [comment]
204s are supported in NuGet 3.4.2

https://github.com/NuGet/NuGet.Client/blob/dd5e3ba23ef9318a7ca117dc85b1342ec6abf1ad/src/NuGet.Core/NuGet.Protocol.Core.v3/LegacyFeed/V2FeedParser.cs#L455

**Comment by yishaigalatzer** [comment]
@ekoshkin we noticed that you guide folks to use the V1 api, which leads to performance issues and more bugs for scenarios we didn't have proper test coverage for.

As we did fix this issue, I would ask you consider looking into reverting the recommendation. At the same time we will work on the V1 issues in NuGet 3.4.3
