### ISSUE TITLE
Nuget 3.3/VS 2015 package causes project to reference dlls but not include content files

### ISSUE THREAD

**Issue by WardBenjamin** [NuGet/Home#1862]
I have been trying to package a project of mine and the associated pdb and dll config files, but the new content v2 (contentFiles) system seems to be not working. Essentially, the dlls are linked to the project and the content is copied with the package, but it is not linked to the actual csproj file or copied into the project folder.

I asked a question on StackOverflow a little while ago, and there's a copy of my nuspec file and result folder structure [there](https://stackoverflow.com/questions/34376215/nuget-3-3-vs-2015-package-causes-project-to-reference-dlls-but-not-include-conte).

I am using VS 2015 and Nuget 3.3.

**Comment by yishaigalatzer** [comment]
You are saying in your SO post, that packages.config is being added, and also you are adding dlls. So I'm a bit confused to what exactly you are trying to achieve because:
1. ContentFiles is designed to only work in project.json scenarios.
2. It is note designed to add dlls, you could add them, but they wouldn't be referenced. You also need to specify build action, because the default build action is compile (which is for source files)
3. If you want stuff going to the output folder, you need to specify that as well with copytooutput
4. All that works with Update I only (some make sure you have that).

https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json

I'm closing because there seem to be no bug here. And since this is not a good answer on SO, we can discuss here, and when we figure out what you want to achieve we can repost there.

Feel free to keep discussing here, closing doesn't mean we don't keep track.

**Comment by WardBenjamin** [comment]
> So I'm a bit confused to what exactly you are trying to achieve

What I'm trying to accomplish with ContentFiles is to copy the dll.config and the pdb files into the project, along with referencing the dlls (that part is done normally). I've managed to do it through a custom .targets file, but this not working seems to be something that should be addressed as a bug

> ContentFiles is designed to only work in project.json scenarios.

I'm not quite sure what you mean, but the spec that you linked seems to say that I can do this in the .nuspec file, and it compiles.

> It is note designed to add dlls, you could add them, but they wouldn't be referenced. You also need to specify build action, because the default build action is compile (which is for source files)

Again, I am referencing the dlls as normal.

> If you want stuff going to the output folder, you need to specify that as well with copytooutput

Yeah, I know. The nuspec that I posted was the smallest reproducible example that did not work for me (aka, any content v2 reference.)

> All that works with Update I only (some make sure you have that).

I've updated Nuget in VS 2015 to 3.3, so I think I have this.

Thanks!

**Comment by yishaigalatzer** [comment]
> > So I'm a bit confused to what exactly you are trying to achieve
> 
> What I'm trying to accomplish with ContentFiles is to copy the dll.config and the pdb files into the project, along with referencing the dlls (that part is done normally). I've managed to do it through a custom .targets file, but this not working seems to be something that should be addressed as a bug
> 
> > ContentFiles is designed to only work in project.json scenarios.
> 
> I'm not quite sure what you mean, but the spec that you linked seems to say that I can do this in the .nuspec file, and it compiles.

What it means is that this works _only_ in a project where the packages are added through a project.json file, rather than through a packages.config file. The scenario is replacing the old content model in new project types, but it explicitly designed not to work when you use packages.config. The way these are added is through the project system by reading a project.lock.json. The project system is only picking them up when this file is written by NuGet. I hope that makes sense. BTW The spec says right at the title that this works only in project.json scenarios, I'll edit it to clarify.

So you could port your project over to use project.json, see this wiki - https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

> > It is note designed to add dlls, you could add them, but they wouldn't be referenced. You also need to specify build action, because the default build action is compile (which is for source files)
> 
> Again, I am referencing the dlls as normal.

If you do then don't add them again as content.

> > If you want stuff going to the output folder, you need to specify that as well with copytooutput
> 
> Yeah, I know. The nuspec that I posted was the smallest reproducible example that did not work for me (aka, any content v2 reference.)

It will not work without specifying the build action, so the sample is not very useful.

> All that works with Update I only (some make sure you have that).

I've updated Nuget in VS 2015 to 3.3, so I think I have this.

Thanks!

**Comment by WardBenjamin** [comment]
> > > It is note designed to add dlls, you could add them, but they wouldn't be referenced. You also need to specify build action, because the default build action is compile (which is for source files)
> > 
> > Again, I am referencing the dlls as normal.
> 
> If you do then don't add them again as content.

Yep! If I was then it was an accident. (Taking a look at the SO post, it does seem like the contentFiles statement there would have included that. Whoops, but not the problem).

> > > If you want stuff going to the output folder, you need to specify that as well with copytooutput
> > 
> > Yeah, I know. The nuspec that I posted was the smallest reproducible example that did not work for me (aka, any content v2 reference.)
> 
> It will not work without specifying the build action, so the sample is not very useful.

I thought it had a default as per [the spec](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json#attributes-defaults)?

Thanks!

**Comment by yishaigalatzer** [comment]
Too much nesting :) Lets flatten again

The spec says the default of a content item is compile - The only things that compile in a C# project are `.cs` files, in your case you added pdb and config files. Also the default is to not copy to output, it means that items are only referenced by the project (so they will show up in the generated dll), but they will not show up in the tree or copied into the folder structure (the latter is the whole point of this feature, the former is a dubious design decision we are still contemplating reversing CC @jasonmalinowski )

The key question remains: Is your project using packages.config or project.json to define package dependencies?

**Comment by WardBenjamin** [comment]
Apparently my project is using packages.config, so I guess that was the issue? 

Two things remain:
- How do I switch to the project.json format?
- Can this be made more clear in the docs?

Thanks!

**Comment by yishaigalatzer** [comment]
1. Changed the docs to make it clear (right on the top of the document)
2. Included a [link](https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json) for moving over right in the docs.

**Comment by yishaigalatzer** [comment]
CC @emgarten who is working on the official docs

**Comment by WardBenjamin** [comment]
Apparently my project is using packages.config, so I guess that was the issue? 

Two things remain:
- How do I switch to the project.json format?
- Can this be made more clear in the docs?

Thanks!
(I meant to post this yesterday but apparently the POST request never made it to github before I closed my laptop lid. Whatever, I guess :smiley: )

**Comment by yishaigalatzer** [comment]
See the answers above :)

**Comment by WardBenjamin** [comment]
Oh, thanks!

**Comment by dls314** [comment]
If I'm attempting to use NuGet to deliver .cs files to both project.json/.xproj style projects and packages.config/.csproj style projects, two questions.

Can I use the content and contentFiles mechanisms in the same package to deliver the same *.cs files?

Would it be better to just use separate packages?

**Comment by yishaigalatzer** [comment]
You can use both mechanisms in the same package

On Aug 12, 2016 6:33 AM, Dave Smith notifications@github.com wrote:

If I'm attempting to use NuGet to deliver .cs files to both project.json/.xproj style projects and packages.config/*.csproj style projects, two questions.

Can I use the content and contentFiles mechanisms in the same package to deliver the same *.cs files?

Would it be better to just use separate packages?

##
