### ISSUE TITLE
All packages generated from the nuget build should have license anb project url in them

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1886]

**Comment by yishaigalatzer** [comment]
There are several packages (from the csproj side) that are missing nuspec files, and none of the DNX based packages have projectUrl and license in them.

We should amend it, and add a test verifying that all packages do have the right license and project url as part of the build

**Comment by deepakaravindr** [comment]
@yishaigalatzer @rrelyea

Change for this has been sent as a PR against dev branch: https://github.com/NuGet/NuGet.Client/pull/422

Upon confirmation, I will do a separate PR for the release-3.4.0.
I cannot cherry-pick this commit, since, versions on project.json file on dev branch is 3.5.0-*

Note that this change, if made to release-3.4.0 branch, need not make it to VS.
This is only for the NuGet packages we will publish to nuget.org (and elsewhere).

**Comment by rrelyea** [comment]
Per Deepak, closable.
