### ISSUE TITLE
UI missing standard keyboard/mouse behaviors

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1896]
From vs-feedback 532441:

When I want to update a somewhat large set of projects and the nuget project window does not support some well established expectations for keyboard/mouse behaviour.
- spacebar does not select/deselect those packages
- the mouse wheel does not scroll the list of projects

**Comment by yishaigalatzer** [comment]
Mouse wheel is now scrolling the list of projects. It wasn't before because you have a list within a list, and the project list didn't have its own scroll bar.

We will take a look at the spacebar.

**Comment by feiling** [comment]
Fixed.

**Comment by Semax** [comment]
Hi. I'm using NuGet 3.4.3.855 and spacebar checks only the latest selected project instead of all selected. And it gets really annoying to check several dozens of projects among hundreds. Could you please make spacebar check all the selected projects and add a way to check all projects that are referencing the selected package (maybe Ctrl + click on the checkbox in the table header)?
Thanks.
