### ISSUE TITLE
The replacement token 'id' has no value

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#1986]
Using the following nuspec

`<?xml version="1.0"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <licenseUrl>http://localhost</licenseUrl>
    <projectUrl>http://localhost</projectUrl>
    <iconUrl>http://localhost</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
    <releaseNotes></releaseNotes>
    <copyright>© 2010-2016 </copyright>
    <tags></tags>
  </metadata>
</package>`

the `nuget pack` v.3.3 produces the following error:

The replacement token 'id' has no value.

**Comment by csharpfritz** [comment]
What was the full syntax of the pack command that you were issuing?

**Comment by brgrz** [comment]
`nuget pack mypackage.nuspec -Prop Configuration=Release -Symbols -outputdirectory "..\..\nuget"`

it results in:

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from 'mypackage.nuspec'.
The replacement token 'id' has no value.

Works fine if I use nuget.exe 2.8.6 for packing.

**Comment by brgrz** [comment]
As a workaround, I now have the new nuget.exe in path and the old one in a separate folder elsewhere but I'm now required to update the calls to nuget.exe with the path to the old one across multiple projects (I have this in Post Build steps).

**Comment by yishaigalatzer** [comment]
You can also provide the Property for the id in the command. Where did it come from in 2.8.6?

**Comment by brgrz** [comment]
From the assembly I guess. It's in the docs, you know? The token replacements in nuspec..

**Comment by toddm** [comment]
If you don't specify a nuspec or project file, it will pack as if you passed in the project filename.  This will use both the project file and the nuspec file and $id$ works.  If you pass in the nuspec file to the pack command, it does not use the project file at all so it won't have a property value for id.
If you're using a nightly build or the soon to be released 3.5 Beta, you can go back to not specifying a filename and it will do the right thing.  Otherwise, change your command to pass the project filename and $id$ will work.
