### ISSUE TITLE
Version number confusion

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#2026]
If I go to the VS Help, About dialog and look at the Nuget package manager I see 3.3.0 - 3 digits.
If I go to the visual studio gallery and look at the package manager for VS 2015 I see 3.3.0.167

Please show the full version number in the Help, About, it is very confusing as I have no way of knowing EXACTLY which version/build is installed when trying to fathom problems,
Thanks

**Comment by yishaigalatzer** [comment]
@deepakaravindr please verify that this is completely fixed in RTM.

@Korporal - Unless you install pre-release versions, our meaningful version numbers are just the first 3, the forth digit is the build number. 

Also completely agree with your comment

**Comment by deepakaravindr** [comment]
@yishaigalatzer @Korporal @rrelyea 

Following is my investigation. I don't think we should fix this. At least, not for this release.
Please let me know if I have missed anything.

Firstly, "3.3.0" shown on the Help->About Dialog is not the product version. Apparently, it is called the Product Id. Meaning, it could be anything that the VSIX or specifically VS Package author wants it to be but has to be unique and is mandatory. Note that several products actually have a GUID or other non-version things on their Help->About.

Secondly, there used to be 3 ways to control this.
1. Registry was one of the ways to control it. Not sure if this is true anymore. Need to investigate further. In any case, I don't think we should take this path for the current release.
2. You can implement an interface called [IVsInstalledProduct](https://msdn.microsoft.com/ru-ru/library/microsoft.visualstudio.shell.interop.ivsinstalledproduct%28v=vs.110%29.aspx). But, this inteface has been **logically deprecated** since VS 2010, since it loads a bunch of packages when Help->About is opened and causes performance issues. Check this [ link](https://blogs.msdn.microsoft.com/visualstudio/2010/01/05/product-registration-for-the-about-box-in-visual-studio-2010-and-the-deprecation-of-ivsinstalledproduct-interface/)
3. Use the [InstalledProductRegistrationAttribute](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.installedproductregistrationattribute.aspx). This is what NuGet uses today and this is the preferred mechanism too.

Now, let us consider the 3rd option which NuGet has already employed. Check code [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/VsExtension/NuGetPackage.cs#L42). You will see that the InstalledProductRegistrationAttribute takes 4 arguments. Product Name, Product Details, Product Id (The one this issue is trying to fix) and Icon Resource ID. You will also note that the first, second and the fourth argument are actually numbers, because they are resource IDs to VSPackage.resx where the string could be localized or be embedded like the icon resource.

I thought we would do the same for the third argument, ProductId, and change the resx file on every build. It turns out that the ProductId cannot come from a resource file anymore. Not sure when this change took place. But, by using ILSpy on the class InstalledProductRegistrationAttribute present in "Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", I can see that all the 4 arguments except the 3rd argument, ProductId could come from VSPackage.resx file, because, strictly speaking, it does not have to be localized or be an embedded resource like the icon.

Considering all this, and the fact that product Id "3.3.0" is most of the actual product version "3.3.0.167", and the fact that you could get the full version from "Extensions and Updates" dialog, IMO, we should not fix this, at least, not for this release.

**Comment by rrelyea** [comment]
Given that VS 2017 version 15.x uses NuGet version 4.x -- this is much less important than it used to be.
