### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#2027]
I'm in VS2015 "Manage Packages for solution" (v 3.3.0).
I can see several projects refer to Some.Component most of them v 1.1, two of them v 1.0.
I select (check) the one's using v 1.0 and then click the Install button at the bottom of the list Window.
I expect (perhaps wrongly) to see those projects update so they too are now using v 1.1
Instead it fails with:

An error occurred while retrieving package metadata for 'Some.Component.1.1' from source 'http://nuget.oursite.com/nuget/'.

The server is v2.8.60318.667

Please provide a way to see more verbose details about the failure, its pretty much impossible to take any remedial steps with such a vague error message.

Thanks

**Comment by The-Futurist** [comment]
Perhaps package manager settings could have a new option "Verbose messages" added or something...

**Comment by yishaigalatzer** [comment]
@Korporal we made quite a few improvements in 3.4 here. But since I don't know your scenario it is hard to tell if your issue is resolved or not.

I do agree with the idea of having a way to get more verbose logs, and the new design is 3.4 (will show up at RTM) is to move the errors to the output pane where there is naturally more room for that kind of stuff.

I'm moving this bug for now to 3.5-Beta, but would highly appreciate your feedback once you try 3.4 and let us know what you think

**Comment by rrelyea** [comment]
If you are able to repro in VS2017 version 15.4 or later, please comment and give us more details on how to repro.
