### ISSUE TITLE
PCLCrypto cannot install into xproj targeting Profile328, although it seems it should

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2063]
Copied from AArnott/PCLCrypto#64

**Repro steps**

```
git clone https://github.com/scottdorman/cadru.git
cd cadru
git checkout 117b042ec9eae7cea569a5b7b9593ca057231a93
```

`dnu restore` at command line doesn't complain, but msbuild does:

> C:\temp\cadru\src\Cadru.Core\project.json(13,18): error NU1002: The dependency PCLCrypto 1.0.86 in project Cadru.Core does not support framework .NETPortable,Version=v4.0,Profile=Profile328. [C:\temp\cadru\src\Cadru.Core\Cadru.Core.xproj]

In VS we see the same error in the error list and References folder.

Yet this version of PCLCrypto targets profile328 and has worked in the past. Why is it broken now?

**Comment by emgarten** [comment]
Has your environment changed from having Xamarin installed to not having Xamarin, or the reverse?

**Comment by scottdorman** [comment]
No, as far as I know nothing has changed in the environment except upgrading from VS 2015 to VS2015 Update 1. This PCL works properly when it's added to the original .csproj, just not when it's added to project.json.

Just in case, here is the information from the About dialog:

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA162
Visual Basic 2015   00322-80000-00000-AA162
Visual C# 2015   00322-80000-00000-AA162
Visual C++ 2015   00322-80000-00000-AA162
Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA162
.NET Portability Analyzer   1.1.10808.0
Add Empty File   2.4
ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
AutoHistory   1.0
Azure App Service Tools v2.7.1   14.0.11112.0
Better Configuration Manager   1.1
Bundler & Minifier   1.7.141
Common Azure Tools   1.6
CssLint   1.0
Developer Assistant   1.0
Exception Breaker   1.0
Extensibility Tools   1.5.109
File Nesting   2.1.2
GitHub.VisualStudio   1.0
Image Optimizer   3.3.51
JustDecompile Tools   1.0
License Header Manager   1.7.0
Microsoft Azure HDInsight HQL Service   2.0.2600.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601
MoveTypeToFile   1.0
MZ-Tools   8.0.0.49
NuGet Package Manager   3.3.0
NuGet References   1.0
NuGetReferenceSwitcher   1.0
Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
OneCodeQuickLaunchPackage   1.0
ORuban.VSExtension.OpenOutput   1.0
PreEmptive Analytics Visualizer   1.2
RoamedExtensionVSPackage Extension   1.0
SQL Server Data Tools   14.0.50730.0
Switch Startup Project   1.0
Telerik ASP.NET MVC VSExtensions   2016.1.111.0
TypeScript   1.7.6.0
Visual C++ for Cross Platform Mobile Development   1.0
Visual Studio Spell Checker   VSSpellChecker
Visual Studio Tools for Universal Windows Apps   14.0.24720.00
VSColorOutput   2.2.3
Web Compiler   1.10.301
Web Essentials 2015   1.0.204
Workflow Manager Tools 1.0   1.0
Xamarin   3.11.450.0 (2ab5145)
Xamarin.Android   5.1.0.115 (d23da369e436488f38c8ab8fe8a9ae7d9ea5256b)
Xamarin.iOS   8.10.0.0 (7741cc495ab0baf04ff0405d0604bc27f0ecae2e)
Xamarin.iOS Unified Migration   1.0
Xamarin.TestCloud.Integration   1.0
XamlFormatter   1.0
```

**Comment by emgarten** [comment]
Does this work with nuget.exe 3.3.0? DNU does not support msbuild projects.

**Comment by scottdorman** [comment]
To be clear, this package installs properly in a csproj based project but fails to install when that same project (on the same machine) is "upgraded" to be an xproj/project.json based project. Nothing else has changed except for the project file(s).

**Comment by emgarten** [comment]
A project.json file used with a csproj is a subset of a project.json file used with an xproj, since csproj contains project references and other metadata while xproj is just a wrapper containing no additional information (with the exception of xproj -> csproj references). You may need to do more than just change the project file.

The current release version of NuGet.exe does not support XProj, but the coming 3.4.0 release will. You can get the 3.4.0 prerelease of nuget.exe from: https://www.myget.org/gallery/nugetbuild  and try restoring your solution with that.

**Comment by yishaigalatzer** [comment]
So at the moment this is not something that NuGet has anything to do with. It is a completely different codebase. even with 3.4 this is not the case, you will need to try the .NET cli where nuget integrates instead of DNU, unfortunately there is no stable build of that just yet.

**Comment by scottdorman** [comment]
@yishaigalatzer I disagree. I think this does have to do with NuGet and it's support for package resolution in xproj/project.json.

To add some additional context, this appears to be a broader issue and isn't just an issue with the PCLCrypto package as I have noticed that there are some other packages (JSON.NET comes to mind) that also exhibit this same behavior. As such, I did a little bit more testing and used the Microsoft.Bcl.Async package as my test package. 

In a csproj based project targeting PCL Profile 328, I’m able to install this package successfully. However, when I try to install this package in to a project.json based project targeting the same PCL Profile, it fails.

Some things to note:
- According to the NuGet package for my project (https://www.nuget.org/packages/Cadru.Core/), I’m targeting `portable-net40+sl50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10`.
- According to the NuGet package for `Microsoft.Bcl.Async`, it doesn’t target my profile but the closest one it does target is `portable-net40+sl4+win8+wp71+wpa81`. This targets a lower version of Silverlight and Windows Phone Silverlight, so my profile can work with it.

On the surface, it appears that the newer NuGet is seeing the `MonoAndroid10+xamarinios10+MonoTouch10` bits and thinking that it’s not compatible. (Short of uninstalling the Xamarin and iOS tools, I can’t unselect those from the targets list because Visual Studio is smart enough to recognize that they share a PCL API surface with everything else I’ve selected and automatically includes them.)

If I look in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.0\Profile\Profile328\SupportedFrameworks`, the list there (Windows Phone Silverlight 8, Xamarin.Android, Xamarin.iOS.Unified, Xamarin.iOS, .NET Framework 4, Silverlight 5, Windows 8, Windows Phone 8.1) matches what my NuGet package says it’s targeting.

To me, this seems to clearly be an issue with the new NuGet package resolution rules for PCLs.

**Comment by yishaigalatzer** [comment]
1. You are mixing two project types and it is really hard to understand the exact scenario. If your project is xproj + project.json you are not using nuget, but dnu. If your project is using csproj + project.json you are indeed using nuget. Which one is it?
2. In general portable tfms are not automatically applicable, and you can use an imports (for csproj + project.json) statement to override the matching rules. Does that work in your case?
3. We are working right now on taking over dnu and merging it into nuget, so the small differences, different team ownership and a diverged codebase leading to bugs and out of sync behavior is going away in one of the upcoming releases.

**Comment by scottdorman** [comment]
Sorry for the confusion. I was using the csproj as an example of the fact that the NuGet packages install properly in that context. I'm actually using xproj + project.json.

I'm not sure if that will work in my case or not as I haven't tried it yet. It sounds like imports are only applicable for csproj + project.json, in which case this wouldn't work for me.

Yes, merging everything together in to NuGet (which I think fits the general expectation that all things NuGet related are owned by NuGet and handled by the NuGet executable) and making the behavior consistent will be good. I think having consistent behavior, especially when it comes to package resolution, is what I've been driving towards and would have prevented this issue from occurring in the first place.

**Comment by yishaigalatzer** [comment]
Thanks for the clarification. We will try this out in the new codebase and see how this works in this scenario

**Comment by scottdorman** [comment]
No problem. Sorry I wasn't being clear from the start. I also pushed up all of the changes I've been working on to my code to support xproj/project.json to https://github.com/scottdorman/cadru/tree/netcore, so feel free to fork and use that as test cases as well. There are a two projects that have a readme.md file in them that provides some notes about the issues I'm running in to or what I'm trying to do. In general, as I move more projects in to project.json format and find other issues, I'll document them in a readme.md for each project.

**Comment by yishaigalatzer** [comment]
@scottdorman the codebase is now merged, you need to pick the latest drop of the CLI to give your latest bits a try. You might have to add an import statement for your specific scenario

**Comment by yishaigalatzer** [comment]
@emgarten the work here is to verify the scenario is supported.

**Comment by emgarten** [comment]
I'm not able to repro this with nuget. This looks like it was a dnu only issue.
