### ISSUE TITLE
EnvDTEProjectUtility.IsClr loads the entire project xml file without using it causes GC pressure in VS.

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#2080]
The IsClr code creates a VcxProject object, which loads the project xml.  However, the code doesn't use it today.  When we investigate some performance issues in reloading a large C++ solution, this code is executed multiple times for each project reloading, and contributes 40% of CLR allocations in some perf traces, and GC is very active in that scenario.  That code should be fixed, and does not load the Xml file for unimplemented function.

**Comment by yishaigalatzer** [comment]
@lifengl can help us with more info on the scenario you are referring to? And also what is the priority.

Please share version of visual studio, version of nuget, and a repro project/steps

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet.Client/blob/11e5ba35c1880f18099ce22f7ef0c2b2b65cab0b/src/NuGet.Clients/PackageManagement.VisualStudio/Utility/EnvDTEProjectUtility.cs#L1244

It is indeed not clear why we create the vcxproject item here and throw it away.

@deepakaravindr @emgarten can you please comment
@lifengl is there a better way to test for the project being a CLR type or not (for actually fixing the bug in this code?) otherwise I would expect us to just cache the result

**Comment by lifengl** [comment]
@yishaigalatzer We saw it in VS 2015 Update 1, with Package Manager Console Host Version 3.3.0.167.  It is a large solution from a customer with lots of C++ projects.  It is one of performance issues in the scenario.
