### ISSUE TITLE
nuget pack -IncludeReferencedProjects partly ignores .nuspec of referenced projects

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2083]
_From @tklingert on February 9, 2016 12:4_

Hi,
it seems like nuget ignores the nuspec-definition of referenced projects up on building the dependency list of a package
e.g.:

> src/LibraryA/LibraryA.csproj  - (Version = 1.0.0.0, InformationalVersion = 1.0.0.0-alpha!d11f62)
> src/LibraryA/LibraryA.nuspec  - (version = 1.0.0.0-alpha)
> 
> src/LibraryA/LibraryB.csproj   - (Version = 1.0.0.0, InformationalVersion = 1.0.0.0-alpha!d11f62)
> src/LibraryA/LibraryB.nuspec  - (version = 1.0.0.0-alpha)
> 
> LibraryB references Library A:
> nuget pack -IncludeReferencedProjects ... LibraryB.csproj 
> 
> The generated package should have dependency to 
> LibraryA >= 1.0.0.0-alpha
> 
> but actually added is (nuget version 3.2.1.10581) 
> LibraryA => 1.0.0.0

_Copied from original issue: NuGet/NuGetGallery#2879_

**Comment by yishaigalatzer** [comment]
Yes, this is by design. There is no strong link between the nuspec and the csproj, it is just a file that could really be anywhere.

When we implement pack for project.json scenarios, the project.json scenarios are really both the dependencies and the nuspec (we are not even sure we will support nuspec packing in that mode), and then we have a strong model to depend on.

**Comment by JackGrinningCat** [comment]
I came over an similar use-case. 

My hope was that the rules of the referenced project for native project would be taken into account when creating the reference on it. 

It seems i need to do that with a big nuspec. 
But my concern I loose the easy of defining dependencies-by-use from the managed projects due to this.
