### ISSUE TITLE
Simple code sample showing how to install a package from a local folder feed

### ISSUE THREAD

**Issue by dazinator** [NuGet/Home#2086]
I have been using NuGet.Core (version 2) in my application, to install packages from a local feed.

I would like to upgrade to NuGet 3, and I am just looking for some basic sample that shows how to do that in NuGet v3.

I have no idea which NuGet packages I need to reference, or even whether these is still a `PackageManager` class..

**Comment by yishaigalatzer** [comment]
A good way to start is to go through the nuget.commandline, and see how things are getting done in the new world.

Specifically here is the code for the install command:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L70

A word of caution: The NuGet 3 code just calls into nuget.core at this point, so there is not much point in migrating at the moment, mostly because we don't guarantee not to change the structure when we finish porting it all over. However the starting point I shared will remain a good place to start going forward as things morph

**Comment by dazinator** [comment]
Thank you!
