### ISSUE TITLE
'packages' not declared when packages.config is open

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#2091]
When my packages.config is open I get the warning "The 'packages' element is not declared."; the warning disappears when I close the file.

I assume this is not intended behavior, and I'd like the warning gone without having to do ugly workarounds. I might be able to make a PR to fix this myself if someone could point me in the right direction.

**Comment by yishaigalatzer** [comment]
This is an XML editor issue, because it cannot find the schema. This issue is tracked in - https://github.com/NuGet/Home/issues/1836.

We would have no problem publishing the schema, this is currently low on our list, but if you wanted  to take a crack at creating one, we could take a look.

Closing this issue as it is a duplicate. We can continue the discussion there. https://github.com/NuGet/Home/issues/1836
