### ISSUE TITLE
nuget.exe, some problems with dependency handling etc

### ISSUE THREAD

**Issue by omtslug** [NuGet/Home#2117]
Hi!
Evaluating nuget for component deployment and have some questions, see below.
I find many other tools very install-centric, tweaks are required to get custom destination folders and multiple instances.
Nuget just downloads things to current directory and no problem to do it in multiple places but the things I've noted 
below is making my life complicated.. We just need xcopy/zip deploys but with good dependency handling.

Feedback highly appreciated, nuget.exe 3.3.0.212.
Please advice how I can work-around these probs.

A. install with packages.config will not download dependencies ?

B. install with a specific package works better (for dependencies) so sure, I could create 'meta' packages for the compositions..

C. nuget.exe does not care about DependencyVersion/DependencyBehavior regardless if specified in local nor global config file ?

D. update and restore requires a packages.config so for that to work I cannot work on a single package id, see A & B.
   I could have a packages.config and do a powershell loop which will install each and dependencies will 
   most likely work but I'm afraid that update will not work? (related to A)

E. restore does not have any -excludeversion so I cannot start with that from the beginning. 
   will 'update' work if install was done with excludeversion.

I've also toyed a bit with packagemanagement + nuget but that seems far from ready..
/stefan

**Comment by yishaigalatzer** [comment]
NuGet is not intended to be a mechanism for deployments, and features or bugs that are only affecting these scenarios will not be prioritized high. Having said that many folks are using it for such scenarios.

Given that this is a bug database and not a support forum, I suggest reposting on SO.

Here are some answers

> A. install with packages.config will not download dependencies ?

Correct, install is a misnomer in this scenario, it basically just restores.

> B. install with a specific package works better (for dependencies) so sure, I could create 'meta' packages for the compositions..

Correct, but you might get in trouble when it comes to target framework resolution, because the install command is very "simple", if you control all the components and the target frameworks inside the packages, you could control it and be succesful.

> C. nuget.exe does not care about DependencyVersion/DependencyBehavior regardless if specified in local nor global config file ?

That's really a visual studio feature, not to say it should never be ported over.

> D. update and restore requires a packages.config so for that to work I cannot work on a single package id, see A & B.
> I could have a packages.config and do a powershell loop which will install each and dependencies will 
> most likely work but I'm afraid that update will not work? (related to A)

Yes, but consider using project.json, where you won't get dependency behavior support but you will get restore to download dependencies. Use the environment variable NUGET_PACKAGES to define the location where the packages go.

> E. restore does not have any -excludeversion so I cannot start with that from the beginning. 
> will 'update' work if install was done with excludeversion.

Install doesn't create a packages.config, so update wouldn't work because there is no baseline.

**Comment by yishaigalatzer** [comment]
Last - Discussion can keep going on. I'm closing because it is not an actual work item.
