### ISSUE TITLE
Set NugetPackagesDirectory in generated <project>.nuget.props file

### ISSUE THREAD

**Issue by kjbartel** [NuGet/Home#2119]
When using `project.json` with a `csproj` project if you set the `NUGET_PACKAGES` environment variable then the Visual Studio NuGet tools will use that directory for installing / restoring packages. But there is an error in Microsoft.NuGet.targets when building a project  saying that it can't find the package. It appears that the `NugetPackagesDirectory` property isn't set. There is a `.nuget.props` file generated for each project which sets `NuGetPackageRoot` but this property isn't used anywhere other than within that file. If it were changed to `NugetPackagesDirectory` instead then the build would work.

For information, I have `NUGET_PACKAGES` set as `packages` which allows me to use the `packages` folder under my solution folder. This is a [bit of a hack](http://stackoverflow.com/a/35431380/1730559) to work around the lack of support for a solution specific `packages` folder with `project.json`. My preference would be that NuGet supports solution `packages` folders with `project.json` if we wish to use them. This is particularly an issue for [hosted builds such as VSO](https://github.com/Microsoft/vso-agent-tasks/issues/311) which looks for a `packages` folder.

**Comment by yishaigalatzer** [comment]
CC @jasonmalinowski @emgarten 

For the VSO issue - I have already started a separate discussion with them to fix this, you shouldn't need to work based on the packages folder only. There are huge advantages to getting rid of the solution packages folder, so we should strive to improve the situation rather than roll it back. We will add more support for specifying a relative packages folder path at some point.

**Comment by kjbartel** [comment]
> There are huge advantages to getting rid of the solution packages folder, so we should strive to improve the situation rather than roll it back.

There are also advantages in having packages committed to source control. One of the main reasons I initially added them was because of the time it took to download and restore on the build server. Whether the packages are restored to a global cache or to the solution's packages directory won't make any bit of difference for this as  new build server image is created in Azure for each build.

The other obviously huge problem is the same which has existed since people started using 3rd party libraries, whether the library will be available in the future when the program needs to be maintained or updated in 5-10-15 years' time. Can you say that the same NuGet packages will be available in the future and the nuget server's will support the same api for access? I doubt that very much. Having the libraries in the repository is the best way to guarantee all required libraries are available.

**Comment by yishaigalatzer** [comment]
Create your own feed, maybe even on top of tfs and you have a guarantee. Checking in packages is much worse. In project.json we don't clean up for you (nor will we ever) so your repo will keep growing

**Comment by kjbartel** [comment]
> Create your own feed, maybe even on top of tfs and you have a guarantee.

Seriously? Talk about making a problem more complicated than it needs to be.

> Checking in packages is much worse.

Why? Give concrete reasons.

> In project.json we don't clean up for you (nor will we ever) so your repo will keep growing

Yes I know. That was a problem I also saw with the hack "solution". The thing is there is no reason why you can't have both a global cache and a solution packages folder. It would simply copy the required packages from the cache if they aren't in the solution's packages folder.

**Comment by yishaigalatzer** [comment]
First let me say it again, we are supporting a localized folder using the NUGET_PACKAGES variable, and we will support it through nuget.config in a relative path mode (it is actually not blocked on nuget code, but on the msbuild task).

> > Create your own feed, maybe even on top of tfs and you have a guarantee.
> 
> Seriously? Talk about making a problem more complicated than it needs to be.

I agree it is more than just having TFS, but setting up packages in a folder or even a simple nuget server is not rocket science.

> > Checking in packages is much worse.
> 
> Why? Give concrete reasons.

Because checking in binaries bloat your syncing process, where many times all you want to do is just get at the code or work on parts of it, now you are in a world where you have to download the whole lot by default.

You are also in a mode that whenever you update packages you now have to check in again, for scenarios where you depend on packages from a ci build (see the \* notation in project.json, where you can always pick the latest of a certain version range without forcing an update).

If you work in a distributed source control system, that most of the world is moving to (e.g. git), you are in a mode where you download pretty much all the binaries and bloat becomes a whole lot worse. So if you are on TFS today, you might not be feeling the pain, but you are missing on a whole lot better development experience with GIT or Mercurial.

> > In project.json we don't clean up for you (nor will we ever) so your repo will keep growing
> 
> Yes I know. That was a problem I also saw with the hack "solution". The thing is there is no reason why you can't have both a global cache and a solution packages folder. It would simply copy the required packages from the cache if they aren't in the solution's packages folder.

The global folder is not a cache, it is the install target for the packages across all the projects using it.

The more I think about it for your scenario (where you freshly create the environment per build) I guess it does not matter as much. We will just not manage the checkin-checkout-delete in TFS.

**Comment by yishaigalatzer** [comment]
As for your top suggestion (where we write out the packages folder to msbuild), this is a great way to pass the values to the msbuild task. We will confer with the owner @jasonmalinowski on this and see if gets us out of having to implement a much more complex change.

The way we think this might work:
- You define the relative packages folder in nuget.config (already supported but not documented)
- We resolve the path to an absolute path, and write it out in the props file.
- We restore into the solution level folder (and pretty much no-op on downloading packages), and write a lock file
- The msbuild task picks up the packages folder path from the props file we dropped

BTW the NUGET_PACKAGES variable is not a hack, it is intended

**Comment by kjbartel** [comment]
Just to expand on this. The problem is that Nuget together with packages committed to source control used to very easily manage a set of libraries required for a particular version of a project. Sure you need to commit new versions of the libraries when you update but people who want to use a specific version of a library don't really see this as a problem because we don't want to use unknow future versions which we haven't tested. New versions often have new bugs.

Moving to a personal NuGet feed is moving the management of the packages into a manual process which used to be all automatically done by NuGet: update a package and the old package folder is deleted which is then picked up by source control and can easily be committed. Done, easy. Now I would have to update the package in my project, then go and download the nupkg file for the package, and then publish it to the private feed. Sure it could probably be automated but the point is that nuget used to be the tool which did all of that for me so that I didn't have to. It made my life easier. 

On VSO, with a freshly created build environment, all of the benefits you're talking about are moot. Whether you get the packages from source control or from nuget restore you'll still need to download them every time. NuGet restore is a hell of a lot slower though.

It doesn't matter if you're using Git or TFS. I am using Git. Indeed some people [use git submodules](http://stackoverflow.com/questions/11318738/managing-3rd-party-sources-and-binaries-used-by-code-under-source-control) for maintaining 3rd party libraries which are shared amongst multiple projects.

**Comment by kjbartel** [comment]
> BTW the NUGET_PACKAGES variable is not a hack, it is intended

Then it's an intended hack. I shouldn't have to set a global environment setting for something which should be solution specific.

**Comment by yishaigalatzer** [comment]
I see your points and thanks for sharing you scenario in detail. Like I mentioned we are going to look at following your suggestion on picking up the path in msbuild by the build task.

So it makes a HUGE difference if you use git of TFS, just wait for a while as new versions accumulate and see you clone and pull time grow rapidly. It is a really bad practice.

> Just to expand on this. The problem is that Nuget together with packages committed to source control used to very easily manage a set of libraries required for a particular version of a project. Sure you need to commit new versions of the libraries when you update but people who want to use a specific version of a library don't really see this as a problem because we don't want to use unknow future versions which we haven't tested. New versions often have new bugs.

No one is suggesting to pick up new versions from the ether. But in a team with a reasonable size where you get multiple project deployed to different git repositories, pulling in latest packages (or constraint say: 2.1.0-beta*) is of a huge value, and it keeps things flowing a LOT better than manually checking things in into source control.

In the VSO environment you have a private NuGet as part of your build, so you really don't have to spin up your own. Over time things will improve in this world with things like auto mirroring of local folders to servers.

At the end of the day - it is your choice of how you want to run your build and for many relatively simple scenarios checking in packages does work, so if it works for you great.

You still need to run restore on the CI server to get the lock file (just like you build clean, restore in project.json is a lot more involved than just downloading the packages). So you do save time on downloading packages, but you don't escape having to run restore.

Last - If you still want to just checkin and you are using Git, just clean the packages folder, run restore and stage the changes, you got exactly what you wanted. use nuget locals -clear all command to clear everything before restore.

> > BTW the NUGET_PACKAGES variable is not a hack, it is intended
> 
> Then it's an intended hack. I shouldn't have to set a global environment setting for something which should be solution specific.

Oh well, we will have to disagree here. It is an intentional mechanism to move the packages folder from disk to disk globally, and you can use it for your scenario. Like I mentioned above we have a different mechanism in nuget.config that is not yet supported by msbuild and we are looking into it.

**Comment by kjbartel** [comment]
> No one is suggesting to pick up new versions from the ether. But in a team with a reasonable size where you get multiple project deployed to different git repositories, pulling in latest packages (or constraint say: 2.1.0-beta*) is of a huge value, and it keeps things flowing a LOT better than manually checking things in into source control.

Yep, I could definitely see it as being good in environments with a larger team and / or with multiple projects using common libraries.

> In the VSO environment you have a private NuGet as part of your build, so you really don't have to spin up your own. Over time things will improve in this world with things like auto mirroring of local folders to servers.

VSO and TFS are still evolving, as are other CI build services. I set everything up for my project before any of these features were available in VSO. There are many people though who would like to keep their code and repositories not tied to one service or another.

> At the end of the day - it is your choice of how you want to run your build and for many relatively simple scenarios checking in packages does work, so if it works for you great.

Precisely.

> You still need to run restore on the CI server to get the lock file (just like you build clean, restore in project.json is a lot more involved than just downloading the packages). So you do save time on downloading packages, but you don't escape having to run restore.

This was not the case with packages.config as it contained a list of all required packages including dependencies.  I think you'll find that people using solution packages folders will [commit their `lock` files to source control also](https://github.com/aspnet/Home/wiki/Lock-file).

> First let me say it again, we are supporting a localized folder using the NUGET_PACKAGES variable, and we will support it through nuget.config in a relative path mode (it is actually not blocked on nuget code, but on the msbuild task).

Ok great. I still think setting a relative path in a **global** variable is a hack. Having a setting in nuget.config is a much much better solution. I tried using `<add key="disableSourceControlIntegration" value="false" />` in nuget.config but it didn't do anything. What is the correct setting now and has this already been released?

The other approach I tried was using a `global.json` file specifying "packages": "packages". Is there any reason you aren't using this setting also? Wouldn't it make sense to use common settings between NuGet and DNX, particularly for solutions which might contain both DNX and normal csproj projects, and for projects which are shared amongst multiple solutions?

**Comment by yishaigalatzer** [comment]
Dnx is going away. There will be only one nuget. We are not sure if we after going to keep this setting in global.json or not.

**Comment by rrelyea** [comment]
This is a 19 month old issue. As such, closing. xproj project.json is no longer supported. 
Moved the world to PackageReference in project files...
