### ISSUE TITLE
Restore-on-build for Blend fails first time, succeeds second time (VS scenario fixed)

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#2121]
Repro:
1. Create UWP project in Blend/VSWinExpress
2. Add a UWP Win2D NuGet package using the package manager
3. Close Blend/VSWinExpress
4. Go to %userprofile%.nuget\packages and delete Win2D.uwp
5. Open Blend/VSWinExpress and reload project
6. Build. No restore takes place and build fails.
7. Build again. Restore takes place and build succeeds.

 Also tracked in internal bug # 194090

**Comment by emgarten** [comment]
What version of NuGet and Visual Studio is this using?

**Comment by drewgillies** [comment]
This is VS 2015 Update 1 and NuGet version 167 (RTM).

**Comment by deepakaravindr** [comment]
The issue occurs in one of the recent NuGet builds 3.4.0.632 as well. I have only tried Blend 14.0.24706.00 Update 1. I have not tried out VSWinExpress.

Note that the issue only occurs if NuGet has not already been loaded in the context of current Blend instance. This means that if NuGet Package Manager Console was already open in Repro step (5) or was opened before Repro step (6), then the issue will not occur.

Context:
1. NuGet registers for Auto Loading of the NuGet VSIX by registering for VSConstants.UICONTEXT.SolutionBuilding_string. This means that NuGet VSIX is loaded in the VS or Blend instance when a solution/project is being built if it is not already loaded.
2. NuGet also registers for _dte.Events.BuildEvents.OnBuildBegin event. This means that NuGet can restore packages as needed when a solution/project is being built.

Observation:

On a freshly opened instance where NuGet has not been loaded yet (not used in any way), when one opens a solution and performs a build
1. VS raises event (1) above to load NuGet VSIX and lets it initialize fully before raising event (2), the OnBuildBegin event, to let NuGet restore packages if needed.
2. However, Blend either raises (2) before (1) or processes (1) and (2) in parallel. Because, NuGet does not get the OnBuildBegin event the first time when the event to load the NuGet VSIX is raised. Once NuGet has been loaded, the OnBuildBegin event is raised properly and NuGet restores packages fine. This is the problem.

Should not Blend behave in the same way as VS to raise OnBuildBegin event after the registrations for VSConstants.UICONTEXT.SolutionBuilding_string are processed?

**Comment by deepakaravindr** [comment]
FYI, I tried VSWinExpress and VSWebExpress
1. Same issue was observed with VSWinExpress UAP application.
2. On VSWebExpress, classic ClassLibrary project was able to restore packages to packages folder on the first build.

**Comment by yishaigalatzer** [comment]
We figured out this is not a NuGet issue, but a visual studio core issue.

**Comment by rrelyea** [comment]
Appears fixed. However in my repro (on a VM), VS was black, and dialog was showing. Please see what you see.

**Comment by mishra14** [comment]
@rrelyea : Seems to be fixed in VS 2017 build d15prerel/15.0.25826.3

Validating on Blend,

**Comment by mishra14** [comment]
Investigated more on blend. Seems like NRM is either not being loaded or Blend/VS platform does not fire the right events. Will investigate further.

**Comment by rrelyea** [comment]
will be fixed by blend team RC2 fix for Bug 297804:NuGet badly broken in blend since NuGet.SolutionRestoreManager (a new pkgdef in RC1), cannot be loaded
