### ISSUE TITLE
Re-thinking how symbols packages work

### ISSUE THREAD

**Issue by vtbassmatt** [NuGet/Home#2122]
Symbols packages have a couple of troubling issues:
- They have the same id and version as their associated "normal" package (even though the filename is different). This violates the "one id+version = one package" principle. In practice, users often try to upload both packages to the same source and are met with 409 Conflict errors they don't understand.
- They contain everything the "normal" package contains + additional content, rather than just the debugging material.

When discussing internally, several potential solutions were floated:
- Create a new package type indicating whether this is a symbols package. Server implementations could then make a choice about how to treat an incoming package.
  - NuGet team is in favor of putting this flag in the manifest.
  - Another option discussed was a new "nusym" package type which wouldn't contain the assemblies and other material.
- The client could choose a convention for symbol package ids - for package "FooBar" perhaps "FooBar.Symbols". This may break debugging tools' expectations about how to retrieve symbols.

Per internal discussion, filing this issue to track a design discussion for Q2 of 2016.

**Comment by yishaigalatzer** [comment]
Comments on options 

> Create a new package type indicating whether this is a symbols package. Server implementations could then make a choice about how to treat an incoming package.
> NuGet team is in favor of putting this flag in the manifest.

This is because the server doesn't get the file name, so it must be part of the package itself

> Another option discussed was a new "nusym" package type which wouldn't contain the assemblies and other material.

This could be a combination of the two, so push only looks for *.nupkg, but not *.nusym

> The client could choose a convention for symbol package ids - for package "FooBar" perhaps "FooBar.Symbols". This may break debugging tools' expectations about how to retrieve symbols.

This will not break debugging tools because they do not consume the package as is, instead they deconstruct the packages into a completely different database with guid->pdb mapping and source mapping, the package id is not part of the debugging API

However this suggestoin will create a real package on nuget.org with the new ID, which results in a much worse experience than we have today, so we shouldn't go there.

**Comment by rrelyea** [comment]
@diverdan92 - may be interesting for you to see this kind of issue with symbols

**Comment by loic-sharma** [comment]
@rrelyea Can we close this issue? We've introduced "snupkg" NuGet packages that cover this :)

**Comment by nkolev92** [comment]
Closing this per the above.
