### ISSUE TITLE
Restore summary has incorrect "packages installed" output

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#2139]
https://github.com/aspnet/dnx/issues/2606

Packages installed is keeping the same number from previous project.json restores during the same program execution

i.e.

```
23 package(s) to C:\project\src\proj1
23 package(s) to C:\project\src\proj2
24 package(s) to C:\project\src\proj3
```

Should be:

```
23 package(s) to C:\project\src\proj1
1 package(s) to C:\project\src\proj3
```

**Comment by emgarten** [comment]
Currently nuget finds the install count based on the starting state, not based on the intermediate state where other projects restoring in parallel have already installed some of the packages. The counts were inconsistent as to which project installed the packages and in some cases there were duplicates counted.

I think the fix for this is to log this information in a different way so that it makes sense for parallel restore. Having large counts for every project is confusing.

**Comment by rrelyea** [comment]
Closing this old bug from xproj project.json days. If this is still an important issue, please update us on the details.
