### ISSUE TITLE
Add "Highest Installed" dependency resolution option

### ISSUE THREAD

**Issue by kamranayub** [NuGet/Home#2144]
**Problem**

When installing a Nuget package for a project that depends on packages I already have installed solution-wide (e.g. Newtonsoft.Json), there is currently no way for Nuget to use my existing installed version of Newtonsoft.Json that satisfies the package's dependency.

**Workaround**

I either have to use the highest version (then consolidate), highest patch/minor (then consolidate), ignore ALL dependencies (and make note of all dependencies to install that I do not have), or leave as-is and consolidate afterwards.

**Expected**

Nuget should have a "Highest Installed" option which would resolve all packages I have already installed that satisfy the package's dependency requirements (and probably, the dependencies' dependencies).

**Comment by yishaigalatzer** [comment]
@kamranayub thanks for the idea!

We have slightly different plans for this area, but the idea sounds viable on its own. So moving out to vNext and we will get to it at some point.

**Comment by kamranayub** [comment]
Fantastic, thank you!

**Comment by nkolev92** [comment]
At this point, we're urging users to move to package reference where they have different type of resolution control, which we're considering enhancing with a true lock to enable repeatable builds etc. 

https://github.com/NuGet/Home/issues/5602

As such, we're not planning on investing in this area. 
Since there aren't too many similar requests here, I'll close this issue.
