### ISSUE TITLE
Adding static analysis tooling to help prevent semantic versioning breaks.

### ISSUE THREAD

**Issue by NickCraver** [NuGet/Home#2195]
This is an idea we've been kicking around internally at Stack Overflow, let me preface with:
- This isn't proposed to be part of the current .Net Core sprint, only kicking off a discussion.
- It wouldn't prevent all breaks in semantic versioning, only the portion that can be found statically.
#### Problem

People break external interfaces on their libraries all the time, often in violation of semantic versioning. Methods, visibility modifiers, and entire classes and interfaces change all the time. In a major versioning this isn't unexpected, but in lesser releases it's a nasty surprise. This surprise is often unintentional on the part of library authors. In most cases I see, they either didn't mean to break it or did not understand it should be different release numbering.
#### What can we do?

What if NuGet had tooling for static analysis on packages? This could happen either on-upload or (hopefully) locally as well before attempting to push to a feed. I'm talking about a comparison of the public API surface for libraries for current code vs. the last public release on NuGet. If we prevents breaks at the source, it's the library author (the only one who's about to fix it anyway) eating the time vs. all of the consumers. I hope many library authors would welcome this, since when you factor in the issues created by the break, it's by far a net time savings.
#### Use Cases

There are several use cases served by the same analysis:
- Preventing breaks that are unintentional
- Informing authors they should (or must?) bump the version for intentional breaks
- Helping authors summarize changes in release notes
- (Potential) Helping users by listing these changes somewhere in the gallery

I realize this doesn't come close to solving all of the breaks possible in code, but the statically analyzable ones _we can help_, with some tooling assistance. It also may not help non-DLL cases at all without significantly more investment, but let's at least discuss adding such a thing to NuGet's functionality.

To get the discussion started,  here's an excellent example of almost-there tooling from @akoeplinger which I think could be used, built-on, or learned from: [ParticularLabs/APIComparer](https://github.com/ParticularLabs/APIComparer).

**Comment by akoeplinger** [comment]
/cc @andreasohlund from Particular who might have some thoughts on this too.

+:100:, I've actually thought about this idea as well for a couple years now and I think this would be a very nice addition to either NuGet itself or the Gallery.

Ideally, as an author I'd have some way of communicating to NuGet (e.g. a flag in the nuspec or the gallery settings) that my package adheres to SemVer. It could then prevent uploads of new packages that break API when compared to the last _stable_ release of the same major version.

In cases where that flag isn't set, NuGet could at least issue a warning.

**Comment by FransBouma** [comment]
Research on this topic: http://avandeursen.com/2014/10/09/semantic-versioning-in-maven-central-breaking-changes/ (paper / slides are linked at the bottom)

This research is on 7 years of Maven packages, so it's similar to what nuget contains and offers. It also offers tools for .NET similar to the tooling they used for Java (Clirr). 

It can help get insight in how much this might occur, but also for the realization that the only breaking changes one can detect is ABI mismatches. 

Before anyone gets excited, the researchers of TUDelft say this about their analysis:

> There was substantial computing power involved to obtain data for this paper: data was obtained on a supercomputer with 100 processing nodes with an aggregated running time of almost six months. Without access to the same amount of computing power, the data will be very hard to reproduce. We nevertheless provide our dataset and tools available for download.

I.o.w.: it might have a high impact on server performance, as analysis isn't very simple.

**Comment by csharpfritz** [comment]
This analysis needs to happen out-of-process if its on the server, and if its performed on a per-package basis during upload the resource needs should be minimized

**Comment by yishaigalatzer** [comment]
Sounds like a great idea, I am parking it for now in the vNext area. This could be a side service, and the analysis shouldn't too expensive if we only compare a diff from the last version.

We could consider this a feature of the staging feature, so location of this bug might move, but I would definitely suspect that we want this as a standalone tool.

**Comment by vbfox** [comment]
About the standalone tool it would be really great as it would allow to compute the potential breakage during Continuous Integration builds.

It's the kind of information that would be invaluable to have in a pull request to know if there are any API compatibility breakage to discuss before accepting it.

**Comment by srivatsn** [comment]
As a more upstream solution, there's a [roslyn analyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs) that is a preliminary attempt to solve this problem. We use it in the roslyn project currently. There's a checked in baseline of the public surface area from last release and any time someone changes the public surface area, it is flagged as a warning. There's an associated codefix that updated the diffs from last release. Since the updated diff shows up during code reviews, we can discuss them.

However, it currently flags any change in surface area and doesn't categorize them as breaking changes vs safe changes. It would be good to extend this analyzer to do that and package the analyzer in a separate package and make it generally available. The [set of rules implemented by the ApiCompat tool](https://github.com/dotnet/buildtools/tree/master/src/ApiCompat/Rules) to analyze binaries maybe a good start for identifying breaking changes.

**Comment by andreasohlund** [comment]
@akoeplinger thanks for involving me, we created http://apicomparer.particular.net/ pretty much in this spirit. As of now we use it to enrich our own release notes with api diffs but also to check for diffs when we're updating our own dependencies, RabbitMQ.Client [has been a pain point](http://apicomparer.particular.net/compare/rabbitmq.client/3.5.0...3.6.0) for us but they are finally coming around to follow semver which makes our life much easier.

From a library provider perspective its so much easier to depend on things that follow semver since that makes things like defining nuget dependency ranges etc.

In short: :+1:  for this, Microsoft in general and NuGet in particular starting to push towards the community being more semver aware will save a huge amount of pain for every one involved like @NickCraver points out.

Having a way to check for breaking changes would be awesome for package updates via nuget/paket/etc, I even proposed that to [paket](https://github.com/fsprojects/Paket/issues/1012) (and dropped the ball :) ), since having this info available is awesome to figure out that amount of pain that awaits. 

It would be great if there was some official "breaking change checker" from Microsoft that could set the standard instead of [every one building their own](https://github.com/ParticularLabs/APIComparer/blob/master/APIComparer.Core/BreakingChanges/BreakingChangeFinder.cs#L6).

### NuGet enforcing this

Yes please!

That said I can see how this would put lots of strain on the NuGet server infrastructure. Perhaps much of the processing can be offloaded to the client? (at least in the beginning)

[In ApiComparer we have an exe](https://github.com/ParticularLabs/APIComparer/blob/master/APIComparer/Program.cs#L10) that does checks for breaking changes by downloading the "previous" version from NuGet/MyGet/CI to run the check locally. Would that be possible as a first step? (ie building this into the thing that pushes the package up)

In my experience its the fetching and extracting of the api surface data that is time consuming so a middle ground could be for the client to "extract" the public api into some data format that is optimized for detecting breaking changes. That way the server work should be pretty minimal. This would also be great for clients since they wouldn't have to download the entire package to get the diff, just getting "https://www.nuget.org/packages/NServiceBus/{version}/publicapi.xyz" would be enough. This data is immutable so it should be super easy to cache.

### Diffs for the package developers

We use [ApiApprover](http://jake.ginnivan.net/apiapprover/) from @jakeginnivan, pretty much identical to what you mentions @srivatsn , and it's awesome for our internal purposes since it highlights all changes to the public api not just the breaking ones. This is something we've learnt the hard way that any public type exposed is a liability and should be scrutinized. Using this means that we need to "ack" changes to the public api and also helps [highlight what was changed in pulls](https://github.com/Particular/NServiceBus/pull/3521/files#diff-1eb180a4f6d35cd0c53fde55c1a077b3). (wish @github could add support for better visualizing this if we could agree on a standard).

**Comment by hmemcpy** [comment]
I have nothing of substance to add to this discussion at this point, but I'd like to show you something I've seen [tweeted](https://twitter.com/doppioslash/status/676845572100333568) about elm-package:

![image](https://cloud.githubusercontent.com/assets/601206/13379436/70e752ac-de2e-11e5-8cc3-8587703425a2.png)

This. I want this in .NET world!

**Comment by tugberkugurlu** [comment]
This would be a good start but still, changes are not only at API level, it can be also part of the behavior w/o introducing any change to the API.

**Comment by andreasohlund** [comment]
> This would be a good start but still, changes are not only at API level, it can be also part of the behavior w/o introducing any change to the API.

Completely agree, api breaks is the easy part. Breaking behavior is the hard part...

For NServiceBus we've tried to tackle this by creating and distributing a suite of "acceptance" tests

https://github.com/Particular/NServiceBus/tree/develop/src/NServiceBus.AcceptanceTests
https://www.nuget.org/packages/NServiceBus.AcceptanceTests.Sources/

that in some regards guarantees that we didn't break the behavior tested there. So if no changes are made to the suite we can say that behavior covered by those test still works as expected. Note that I have no illusion that this is perfect since there is plenty of behavior not covered by said tests but at least its something. (sorry for derailing this conversation, this aspect of semver should be debated separately)

**Comment by tugberkugurlu** [comment]
@andreasohlund that's good enough compared to most other projects I have seen. The problem of baking an analysis like this into NuGet is that it can easily give wrong impression to people. Some can come and say that "NuGet didn't report the breaking change but there was one.". However, this can be eliminated by correct wording and setting the expectations correctly (e.g. this only checks API level changes, etc.).

**Comment by tugberkugurlu** [comment]
Also, a better start would be to start supporting SemVer 2.0.0: https://github.com/aspnet/dnx/issues/3365

**Comment by dittodhole** [comment]
I've got introduced to SemVer [by this guy and his amazing talk](https://youtu.be/tc2UgG5L7WM), and since I watched the video I'm thinking about how to integrate this idea into my projects.

One thing that I want to share, is my recent [solution for SemVersioning my projects with a weaver for Fody](https://github.com/dittodhole/csharp-SemVer.Fody).
My approach with SemVer.Fody is not ideal, but it solves parts of the issues I am mentioning next.

Finally, I want to share some thoughts on this matter:

I would heartly welcome any implementation which would allow me to check if NuGet packages are following SemVer or not, as this would allow me to adapt the upper limit of my dependencies accordingly.
But some packages are simply following their [own logic](https://www.nuget.org/packages/Terryberry.PetaPoco/5.2014.6.25) for version numbers.

Several reasons for that:
- NuGet packages do not always contain binaries, but instead [provide *.cs-files](https://www.nuget.org/packages/PetaPoco/) that are affected by breaking interface changes as well. Another example is [jQuery ](https://www.nuget.org/packages/jQuery/)\- no binaries, yet some interface that might break.
- Changes to the version number should not only be done when uploading a package. (This comes from my believe that .dll-files should match the package's version number, when there is only one assembly in the package - and, whenever possible, instead of referencing helper assemblies, why not make them a package and add them as a dependency?) You have CI, CD, and other stuff, which may base the assembly's version number on commits instead, which would, following my believe for linked versioning, reflect the package's version number. Commiting and uploading might not always overlap.
- Finally, I believe that managing a version number manually is simply wrong. Computers are built to spare me from repetitive tasks, and calculating a version number is such kind of a task. When we give a utility enough information to do things, why not pass this information in and provide some documentation on the effects of such tasks. This may not only be a commit message, but could be some API scanning on the client-side as well. Additionally, breaking changes should not only become visible in the version number, but also in commit/PR messages (not a concrete version number, but the severity of your commit - @vbfox :+1:) - and that should be a bad thing? Yes, this demands more thinking - but reflecting the implication of your actions today (commit) might not be that bad either ...
- I do not believe that a check of packages should solely be done by NuGet and its API - I even argue that checking against SemVer isn't NuGet's specific domain, as it is "just" a convention/idea for version numbers (... yet, an excellent one).

You see, I am more on the dark side/conservative side ...
I consider enforcing a policy always a breaking change in the interface between me and the product, which I am - in this very case - absolutely willing to follow. But putting this demand on all packages might lead into ... broken interfaces.

Nevertheless, I am an advocate of SemVer, and absolutely adore the idea behind it. I welcome the thinking on how to integrate SemVer into NuGet, despite I see the duty in another place - but additional checks are never bad.

**Comment by TravisTheTechie** [comment]
I like the idea, and using Elm with this analysis is pretty awesome. However, I'm thinking through a few usages which I can see a problematic. There might be a simple solution, but I'm just adding thoughts to conversation -- not looking to solve the problems yet. 
1. I'm working on an internet project, we publish to an internal NuGet feed. I do not want any enforcement on version numbers because they are tied to other, external things, and breaking API changes are acceptable since they will likely be coordinated. In this case, I have a whole slew of projects that publish. This isn't really idea, but I expect this is pretty common in many internal, enterprise shops. _We want to ignore semver for some projects._
2. We previously released a new x.0.0 version of Topshelf, there was a lot of refactoring/etc. We messed up by placing an extension method into a nested (`Topshelf.Configuration`, the folder location of the file) namespace, when it should have been at the root namespace (`Topshelf`). We moved this extension method back to the root namespace so it was discoverable (and match the x-1 version behaviour). As far as we were concerned, this was a bug and should be a x.0.1 release, not an x+1.0.0 release. _We want to override the enforcement behaviors because of bad assumptions._

I think this works a lot better in the Elm world because modules have specific exports. Building a library in .NET, there's a much larger surface area than just your exports that can be available. Maybe if we had enforcement of semver, more people would spend more effort considering what the exposed surface area is -- but I am not to the point I want to spend significant time considering what to `internal`. 

Possibly unrelated, it would be awesome to have the surface area for common libraries exposed in some consumable format. I'm sure we come up with some interesting data points over time about how the community builds software.

**Comment by yishaigalatzer** [comment]
Keep in mind that in asp.net core we explicitly expose internal implementations because they are useful many times, they are documented as such (expect breaking changes in minor releases) so some opt out mechanism will be required (attribute? Convention?)

**Comment by thecodejunkie** [comment]
I think it's a good idea to point out that _enforcing_  anything is never a good idea. SemVer is _a_ versioning strategy and while many of us may like it, it is important to realize that there are bound to be many strategies being used by package authors whether we like it or not.

If NuGet were supposed to support anything like this, then I would suggest something like this
- The verification happened during the packaging of the package, not during the publish and definitely not on the server
- Ideally NuGet would support something like the `commands` that we've seen in the DNX tool
- These commands could run independently like `Nuget <command>` or as part of another step `nuget pack .... --command|c <command>` this way there could be one command for SemVer, someone else might complement OurCustomVersionStrategyCommand for their internal nuget feed (or the public one) that followed the company versioning rules and so on

DON'T force a version strategy on someone. DO make it extensible

**Comment by yishaigalatzer** [comment]
Command extensibility is already supported (not forna sub command but definitely for a top level command)

Enforcing will never be a thing here, I completely agree

We could do it on the server as part of the new staging feature where we plan an analysis pipeline before merging to the main feed (and perhaps we can make it extensible)

**Comment by thecodejunkie** [comment]
@yishaigalatzer 

> We could do it on the server as part of the new staging feature

Too late if you ask me. As a package author I want to know before I attempt to push stuff, I might even even run it intermittently, even though I don't plan on releasing anything right there and then, to get an overview of changes and so on

**Comment by yishaigalatzer** [comment]
Yes, I'm saying it should/could be in both.

The staging feature gives you one more step before committing for validation

**Comment by andreasohlund** [comment]
> Keep in mind that in asp.net core we explicitly expose internal implementations because they are useful many times, they are documented as such (expect breaking changes in minor releases) so some opt out mechanism will be required (attribute? Convention?)

That would be awesome. We've used the [editorbrowsableattribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.editorbrowsableattribute%28v=vs.110%29.aspx) in the past to hint users that "stay away from this we use it for internal stuff". It would be great with a `[YesPublicButNotPartOfTheApiSurfaceSoItCanBreakAtAnyTime]` attribute. 

That said, since it can break with any release who can really depend and use it?

**Comment by HowardvanRooijen** [comment]
I wrote a post covering my thoughts (which were geared around integrating this in to TeamCity): https://blogs.endjin.com/2016/02/an-experiment-to-automatically-detect-api-breaking-changes-in-dot-net-assemblies-and-suggest-a-semantic-version-number/

**Comment by GrahamTheCoder** [comment]
Having a sensible default built in would of course be awesome, but as the @thecodejunkie says , I think it's about flexibility, not trying to find the one perfect system that works in for everyone. A reasonably non-constraining way of specifying your versioning system would be good, for [example](https://grahamthecoder.wordpress.com/2014/12/10/whats-in-a-strong-name/), each nuget package listing a lower bound on the next version with a :
- minor API change
- major API change

You'd probably then need a description for how you define each of those, for example whether you opt-in with the `PublicAPI` attribute, or opt-out with the `EditorBrowsableState.Never`.

Also, this issue helped me discover other projects similar to what I was [trying to do](https://github.com/GrahamTheCoder/Semver-AssemblyCompatibility) with Roslyn here, awesome.

**Comment by csharpfritz** [comment]
I am very interested in this effort because my biggest concern with NuGet is the problem of 'reference hell', 'DLL Hell', or 'NuGet Hell'.  How can the package manager tools assist developers in preventing the types of headaches that poor reference updates cause?

NuGet cannot force a package to have a specific version number, nor can it force an author to use any convention.  It can throw errors of various severity if API changes were detected that should be reflected in a version number change.

I think @HowardvanRooijen has an interesting PoC that could help this effort.

I worry that we may start down a path with packages that 'properly enforce semver' and 'everybody else'.  Perhaps we encourage better behavior with an indicator on packages that they have passed 'semver review'.

**Comment by TravisTheTechie** [comment]
I wonder how much of 'xxx hell' can be attributed to just following semver? The biggest 'dll hell' problem I see supporting the libraries I work on are when there is a direct & transitive dependency. I don't believe semver will fix anything related to that.

**Comment by GrahamTheCoder** [comment]
@TravisTheTechie You can mitigate the diamond dependency problem if everyone uses the same scheme where a later version number with the same major component is always binary compatible (you can substitute whatever version you like in using the same assembly version or binding redirects etc.) 

For example, every project should update to the latest major version of any dependencies, but the lowest minor version (as described in the penultimate paragraph [here](https://grahamthecoder.wordpress.com/2015/12/04/semantic-versioning-apis-of-net-assemblies)). If they set their nuspec correctly, a consuming app can then safely unify any libraries on the same major version, and pick the minor version that has the bugfixes they need.

You still need every library to keep with the latest major version, but you could set those up to automatically update/build/test and merge/push if the tests pass.

**Comment by olivier-spinelli** [comment]
Some of you could be interested in CSemVer: http://csemver.org/
By constraining semantic versions, very interesting features become available (such as the "Post Release" semantic versions) and this actually help managing versions correctly.

Thanks to this versioning scheme, version MAY be automatically generated... iif we have a way to detect API breaking changes, new features, etc.

An important note: CSemVer and CSemVer-CI are totally compliant with NuGet V2: the versions are not as clean as their SemVer counterpart (ie. 1.2.0-a02 instead of 1.2.0-alpha.2) but the "ordering magic" is fully functional (including for "Post Release").

We are using it for 6 months now with [SimpleGitVersion](https://github.com/SimpleGitVersion/SGV-Net/wiki) and it works great. I wish other people in the community will be interested in this and I'm totally open to any question or remark.

**Comment by rrelyea** [comment]
Thanks for the interest.

This is not high on our backlog. Closing for now. Believe that other parts of the ecosystem would be better to consider.
Note, Nuget Pack and Nuget.org ingestion have a long way to go to start doing better package validation. 
Once we start doing a respectable job there for simple package characteristics (we do not yet!!!), this kind of request might be considered.
