### ISSUE TITLE
Changes to proj and sln files are not always synced to disk

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2214]
When working with nuget VS prompts to save/discard/ignore changes.

Recommendation: Save changes immediately

**Comment by rohit21agrawal** [comment]
NuGet's behavior is similar to in-built Add Reference behavior in Visual Studio (for non project.json scenarios) . Adding/Removing a reference manually doesn't save the project file automatically. Shouldn't NuGet have a similar behavior too? @yishaigalatzer

**Comment by yishaigalatzer** [comment]
The ask here is to save

**Comment by rohit21agrawal** [comment]
I understand that...my question is does it make sense to save here? @harikm86 @yishaigalatzer @rrelyea

**Comment by yishaigalatzer** [comment]
Yes, that's what this bug says to do :)

**Comment by harikmenon** [comment]
Lets chat tomorrow in person. I will also play around with the scenario a bit as well.

**Comment by harikmenon** [comment]
Looked at this issue in more detail. While this is probably in some cases a cool thing to auto-save. That is not how rest of VS works. There are no cases (I could find ) where the project file is saved to the disk without an explicit gesture like Build or Save. I know we automatically save package.config/project.json but changes to the project are always saved with an explicit gesture. I don't think we should change the behavior. 

Some folks might like the existing mechanism, since it notifies them on unwanted changes on close (they could be playing with adding the packages and closing the solution to revert the changes) and we risk antagonizing a segment by making this change without understanding what the majority usage pattern and sentiment is like on this issue.

Also @rohit21agrawal  will open a bug on VS Project System. The asterisk on the tab only shows up on Close now, which should not be the case.

I recommend a Wont-Fix and closing this issue

**Comment by yishaigalatzer** [comment]
I disagree let's have an offline discussion. Without fixing it we end up in a broken state, im OK with adding a backdoor to avoid saving, but this is a pretty essential  fix.

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/commit/c022ca256a74340a05e25b11f3d8b3d0e90214ca
