### ISSUE TITLE
Make it easier to fix bugs or make changes in dependencies

### ISSUE THREAD

**Issue by ryanackley** [NuGet/Home#2226]
We manage all of our project dependencies in nuget. This includes class libraries developed internally. When I'm working on a project and I need to make a change to a shared class library. Here is the process:
1. Clone the repo
2. Make the change
3. Commit the changes
4. Wait for myget to build the new libary
5. Update the dependency in my original project from myget.

If I'm doing this a lot, I usually just remove the nuget dependency, add the shared class library's project to the solution, then add it as project dependency from the solution. The problem is that I have to put everything back before committing any code. 

Is it possible to add a feature to nuget so it will look in the solution for any package dependencies before trying to resolve them from remote sources?

**Comment by yishaigalatzer** [comment]
We actually built one of these, it's called project.json. The idea is that you can substitute a package with a project reference, you can see it today as part of the xproj project system.

Also note that you can skip steps 3-4, and just build the repo (make sure your build created the package of course), and drop it in a local folder which you can use as a feed (that's exactly how we build nuget today, look at nuget.client repo).

Closing because there is no action to be taken here, but would be glad to continue the discussion. If your projects are csproj based and you are not inclined to adopt the RC xproj just yet, you can see this blog post for an alternative https://oren.codes/2016/02/08/project-json-all-the-things/
