### ISSUE TITLE
update command doesn't remove old <error> element from csproj

### ISSUE THREAD

**Issue by ondrejsevcik** [NuGet/Home#2234]
Hi, I found out while upgrading package with `nuget update` command, it doesn't remove old `<error>` element from `.csproj` file. If I update it through the Visual Studio, it works as expected. 

Nuget.exe version: 3.3.0.212
Visual Studio version: 2015 Update 1 (14.0.24720.00 Update 1)
Nuget Package manager: 3.3.0

I've created an empty project ([here](https://github.com/ondrejsevcik/NugetUpdateError)) where I installed `Kentico.Libraries` package in version `9.0.10`. Then, I updated this package with VS. Everything is updated as expected (see git diff):

![vs update](https://cloud.githubusercontent.com/assets/4136929/13455793/d52e410c-e05f-11e5-887b-a3addbcbb360.png)

But when I try to update it with NuGet command line (`nuget update packages.config -Id Kentico.Libraries`), it won't remove old `<error>` element, which causes issues on our build server (see git diff):

![nuget update](https://cloud.githubusercontent.com/assets/4136929/13455800/dd1fcb6a-e05f-11e5-929c-fb2f84a993d1.png)

I think command line `nuget update` should behave the same way as VS update.

**Comment by emgarten** [comment]
`nuget.exe update` is very limited and should only be used for simple scenarios where the new version of the package has all the same files since only the version number in the project file is updated.

> I think command line nuget update should behave the same way as VS update.

NuGet in Visual Studio calls into the Visual Studio project system to make changes. From the command line nuget.exe updates the project file as raw XML. It currently isn't able to make all the needed changes. This is also why `nuget.exe install` does not add new references into the project file.

**Comment by emgarten** [comment]
Take a look at project.json it is an alternative to packages.config that is used by UWP and dotnet CLI projects. It solves this problem and works cross-platform from the command line.

**Comment by yishaigalatzer** [comment]
We are the ones adding this entry, so it makes complete sense for us to be able to update it. Looks like an oversight.

At the same time, I agree with Justin, Update package from command line is a very limited scenario.

I'm moving this item to the backlog.

**Comment by ondrejsevcik** [comment]
@emgarten thanks for the tip. We're currently investigating our options to work with project.json alternative. 

@yishaigalatzer Will it be fixed into the standard nuget or just into the vnext?

**Comment by yishaigalatzer** [comment]
It is in our backlog, which means it is currently a lower priority item that may take more than one version before it is fixed. Items on vnext may stay for a very long time, but since we are oss we folks are encouraged to tackle them if they'd like.

**Comment by ondrejsevcik** [comment]
thank you for the information :+1:

**Comment by rrelyea** [comment]
Closing this. The best move is to move away from Packages.Config. 
In 2015, the advice was to move to project.json.
Since then, in concert with NetCore SDK based projects, we've enabled PackageReference in csproj. Ideally, moving in that direction will never modify the project file as part of install or restore.
