### ISSUE TITLE
When pack is called and AssemblyInformationalVersionAttribute has an illegal value a package with version 0.0.0 is created

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2281]
Happens with NuGet.exe command line. The desired behavior should be to fail pack

**Comment by toddm** [comment]
The code was using the AssemblyVersion if the AssemblyInformationalVersion is not set or is set to an invalid version.  I'm changing it to fail and show a message if the AssemblyInformationalVersion is invalid.

**Comment by toddm** [comment]
I tried changing the code to fail if the Informational version is invalid, but it's not easy because the code is designed to swallow exceptions and continue on. Changing it would require a large change.
Are we ok with it using the AssemblyVersion if the AssemblyInformationVersion is not parsable?  If it can't find either, it defaults to 1.0.0. @yishaigalatzer

**Comment by toddm** [comment]
Are we ok with this current behavior?  I'm not sure it requires a fix.

**Comment by yishaigalatzer** [comment]
I would blow up

**Comment by toddm** [comment]
https://github.com/NuGet/NuGet.Client/commit/3776553c7c4499ecedf17720377045883d326c2e
