### ISSUE TITLE
Config file best practice

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#2334]
Hello,
we currently have two decoupled solutions : Core and Services.
Services only know Core interfaces and rely on microsoft unity container to inject dependencies.
The dependencies are defined in a unity config file.
We currently have the unity file in the content directory of the core nuget package.
Would it be better to have it in a separate nuget package since services is responsible of setting up its dependencies?
Thanks for your advice.

**Comment by yishaigalatzer** [comment]
We can't really comment on how to structure your projects, its very subjective and hard to tell without getting the full picture. This kind of questions are more adequate to stackoverflow where you can get a wide spectrum of opinions and make your choice at the end.

In general I wouldn't put configuration files for your downstream projects in a content file in a nuget package, because you have no way to override them reliably and keep upgrading the packages. Think of content as an immutable rather than mutable thing you add to your project.

If you still want it in a package, I think putting it in a separate package sounds ok, better yet (if unity supports it), consider making the configuration a code thing.
