### ISSUE TITLE
build starts before build time package restore is finished.

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#236]
When you start a build, the build will begin before build time package restore is finished, so you'll get missing references problems.

To repro, 
- Create a solution. Install some packages. Change the program.cs to reference types used in the packages.
- Close the application. Delete the packages folder.
- Be sure not to build. If you have already built, clean the solution, so that, without package restore build will fail
- Open the solution. Start a build. You'll see that the package restore progress dialog pops up. But you'll also see that the build start too without waiting for package restore to finish. Thus, you'll get build errors of missing types.

**Comment by deepakaravindr** [comment]
It is possible that the code is using Task.WhenAll without a limit on the parallelism or the number of tasks that get created. Need to make sure that this is robust

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/ac0e185c3937158741558c01eea2cc591c43b838,
https://github.com/NuGet/NuGet.PackageManagement/commit/99d0e75a7df19e31f069aecf8e21bfbe0bd39abd
 and 
https://github.com/NuGet/NuGet.VisualStudioExtension/commit/023ef221e00e4b84054643ff77b59ec4ceadedb3
