### ISSUE TITLE
VS2015 Installed Packages Panel Slow

### ISSUE THREAD

**Issue by jamsoft** [NuGet/Home#2364]
When viewing the panel containing the currently installed packages for a whole solution scrolling down the list is painfully slow and regularly just stops scrolling altogether.

**Comment by johnataylor** [comment]
The problem was that as you switched tabs a bunch of http calls were made. It was written such that these needed to complete for the UI to update. We've fixed this by, firstly, populating the pane from the installed packages and secondly moving the additional fetch of details (like whether your feeds have other packages) to the background.

We had similar issues on the Update tab.

related bugs #2089 and #2279
