### ISSUE TITLE
Fail to install Nuget package => 401 Error

### ISSUE THREAD

**Issue by qiansen1386** [NuGet/Home#2388]
I am creating a new Nuget package project using VS2015, and it warp the project with DNX for me. Then when I  try to install some basic NuGet packages, I get this.
![image](https://cloud.githubusercontent.com/assets/1759658/14008173/dbeb35a8-f1b8-11e5-9998-ef57575de405.png)

``` powershell
Warning: FindPackagesById: NuGet.CommandLine
  Response status code does not indicate success: 401 (Unauthorized).
  GET http://nugetrepo.misatravel.net/FindPackagesById()?id='NuGet.CommandLine'
  GET https://www.nuget.org/api/v2/package/NuGet.CommandLine/3.3.0
Warning: FindPackagesById: NuGet.CommandLine
  Response status code does not indicate success: 401 (Unauthorized).
  GET http://nugetrepo.misatravel.net/FindPackagesById()?id='NuGet.CommandLine'
Error: FindPackagesById: NuGet.CommandLine
  Response status code does not indicate success: 401 (Unauthorized).
```

May I know who is responsible for this? You guys? DNX? NuGet.org?
Why Microsoft always make things over complicated...

**Comment by emgarten** [comment]
This error is coming from DNX/DNU which does not appear to support authentication for your feed. Try using a source that does not require a password.

DNU will be going away and NuGet will be used instead as part of the dotnet CLI. Once you move to the CLI this should be fixed since NuGet supports auth.

**Comment by qiansen1386** [comment]
Em, How?
