### ISSUE TITLE
Fix NuGet downgrade warnings in the build

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2396]
They are several of them

/cc @emgarten

**Comment by rrelyea** [comment]
Can you please catalog the current warnings, and loop us in.

**Comment by TimBarham** [comment]
Downgrade warnings are all gone. Will look at some of the build warnings just to clean things up.

**Comment by TimBarham** [comment]
@drewgil looked at the remaining build warnings (which are about VS related assembly version conflics) - I believe he came to the conclusion that they are not able to be resolved.

**Comment by drewgillies** [comment]
@rrelyea @TimBarham: Correct. Most of the remaining warnings are caused by version conflicts on the dependencies Microsoft.Build and Microsoft.Build.Framework--version 4.x.x.x are dependencies of the .NET Framework 4.6, and 14/15.x.x.x are dependencies of project system assemblies. It's an MSB warning and as such cannot be suppressed; app.config changes don't remove the warning from command line builds. VS version-redirects these dependencies to 14/15.x.x.x so there is no runtime conflict.

Other than these, we have some EnvDTE embed interop types inconsistencies which generate warnings (relatively few).
