### ISSUE TITLE
Must manually set SpecificVersion to False for UWP JavaScript apps

### ISSUE THREAD

**Issue by angularsen** [NuGet/Home#2406]
1. Create blank Universal Windows JavaScript app (UWP)
2. Use Visual Studio nuget manager (3.3.0.167) to install `UnitsNet.WindowsRuntimeComponent` or any other nuget targeting `uap10`
3. Build and run

Build warning: 

> Warning   MSB3245 Could not resolve this reference. Could not locate the assembly "UnitsNet". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. JsApp   C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 1819    

Runtime exception trying to access the a type in the assembly:

> Exception is about to be caught by JavaScript library code at line 13, column 8 in ms-appx://981c5554-778f-40df-936b-643c7848abd6/js/default.js
> 0x800a1391 - JavaScript runtime error: 'UnitsNet' is undefined

Workaround:
1. Manually edit the `.jsproj` file and change `<SpecificVersion>` from `True` to `False`

Is this a known issue?

**Comment by emgarten** [comment]
This issue has not come up before. Are you able to tell why MSBuild is unable to find the reference when specific version is false? Is the path or version information in the .jsproj incorrect?

**Comment by angularsen** [comment]
- [UWP .jsproj](https://github.com/anjdreas/UnitsNet/blob/uwp/UnitsNet.TestApps.Uwp.JavaScript/UnitsNet.TestApps.Uwp.JavaScript.jsproj#L85) 
- Example [UnitsNet.WindowsRuntimeComponent.3.30.0-alpha7.nupkg.zip](https://github.com/NuGet/Home/files/192473/UnitsNet.WindowsRuntimeComponent.3.30.0-alpha7.nupkg.zip).
- Diagnostic msbuild output [unitsnet-build.txt](https://github.com/NuGet/Home/files/192408/unitsnet-build.txt). 

Emphasis mine:

> Considered "..\packages\UnitsNet.WindowsRuntimeComponent.3.30.0-alpha6\lib\uap10.0\UnitsNet.winmd", but its name "UnitsNet, Version=3.30.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" didn't match. (TaskId:10)

For some reason it does not accept the name or version of the nuget assembly, although the import statement does not specify any version.

Relevant section in .jsproj:

```
  <ItemGroup>
    <Reference Include="UnitsNet">
      <HintPath>..\packages\UnitsNet.WindowsRuntimeComponent.3.30.0-alpha6\lib\uap10.0\UnitsNet.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
      <CopyLocal>True</CopyLocal>
      <SpecificVersion>True</SpecificVersion>
    </Reference>
  </ItemGroup>
```

Relevant excerpt:

```
1>22:05:27.154     1>
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "UnitsNet". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>                             For SearchPath "{HintPathFromItem}". (TaskId:10)
1>                             Considered "..\packages\UnitsNet.WindowsRuntimeComponent.3.30.0-alpha6\lib\uap10.0\UnitsNet.winmd", but its name "UnitsNet, Version=3.30.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" didn't match. (TaskId:10)
1>                             For SearchPath "{GAC}". (TaskId:10)
1>                             Considered "UnitsNet", which was not found in the GAC. (TaskId:10)
1>                             For SearchPath "{RawFileName}". (TaskId:10)
1>                             Considered treating "UnitsNet" as a file name, but it didn't exist. (TaskId:10)
1>                             For SearchPath "bin\x64\Debug\". (TaskId:10)
1>                             Considered "bin\x64\Debug\UnitsNet.winmd", but its name "UnitsNet, Version=3.30.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" didn't match. (TaskId:10)
1>                             Considered "bin\x64\Debug\UnitsNet.dll", but it didn't exist. (TaskId:10)
1>                             Considered "bin\x64\Debug\UnitsNet.exe", but it didn't exist. (TaskId:10)
1>                     Output Item(s): FileWrites=bld\x64\Debug\UnitsNet.TestApps.Uwp.JavaScript.jsprojResolveAssemblyReference.cache (TaskId:10)
1>                     Output Property: DependsOnSystemRuntime=False (TaskId:10)
1>                   Done executing task "ResolveAssemblyReference". (TaskId:10)
```
1. I'm seeing the exact same behavior with other nugets, such as [GoogleAnalyticsSDK](https://www.nuget.org/packages/GoogleAnalyticsSDK/), which hints this could be a problem with the nuget system rather than my nuspec or binaries.
2. I tried removing `<language>` from .nuspec and `[assembly: AssemblyCulture("")]` from AssemblyInfo.cs, but no effect.
3. I tried changing `<AssemblyName>` from `UnitsNet.WindowsRuntimeComponent` to `UnitsNet`, to match `<RootNamespace>UnitsNet</RootNamespace>` and the filename `UnitsNet.winmd`. I think this is a correct change, but it did not have any effect.

**Comment by emgarten** [comment]
@anjdreas would you try removing the reference from your .jsproj and then adding a reference to UnitsNet.winmd using the Solution Explorer add references dialog in Visual Studio and share the result that Visual Studio puts in your .jsproj?

**Comment by angularsen** [comment]
Here is the diff of referencing the exact same binary in the packages folder:

```
 .../UnitsNet.TestApps.Uwp.JavaScript.jsproj                             | 2 --
 1 file changed, 2 deletions(-)

diff --git a/UnitsNet.TestApps.Uwp.JavaScript/UnitsNet.TestApps.Uwp.JavaScript.jsproj b/UnitsNet.TestApps.Uwp.JavaScript/UnitsNet.TestApps.Uwp.JavaScript.jsproj
index 1d059bb..0f9dff5 100644
--- a/UnitsNet.TestApps.Uwp.JavaScript/UnitsNet.TestApps.Uwp.JavaScript.jsproj
+++ b/UnitsNet.TestApps.Uwp.JavaScript/UnitsNet.TestApps.Uwp.JavaScript.jsproj
@@ -81,8 +81,6 @@
     <Reference Include="UnitsNet">
       <HintPath>..\packages\UnitsNet.WindowsRuntimeComponent.3.30.0-alpha7\lib\uap10.0\UnitsNet.winmd</HintPath>
       <IsWinMDFile>true</IsWinMDFile>
-      <CopyLocal>True</CopyLocal>
-      <SpecificVersion>True</SpecificVersion>
     </Reference>
   </ItemGroup>
   <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\$(WMSJSProjectDirectory)\Microsoft.VisualStudio.$(WMSJSProject).targets" />
```

Meaning SpecificVersion and CopyLocal is removed, presumably defaults to SpecificVersion false?

**Comment by yishaigalatzer** [comment]
Looping in some javascript guys offline

**Comment by jbienzms** [comment]
Just wanted to chime in here. I'm having a similar problem with several Windows Runtime Components I manage. One of them is [AppPromo](https://www.nuget.org/packages/AppPromo).

Like anjdreas, I too am having to set **SpecificVersion** to **False** for WinJS projects. However, when I do set **SpecificVersion** to **False**, my project still doesn't compile as expected. Even though the reference shows up as a valid reference (instead of the yellow warning symbol) I can see that my WinJS application tries to reference the wrong assembly. It attempts to reference:

`packages\AppPromo.1.0.1-beta2\lib\netcore45\AppPromo.winmd`

But according to [this article](https://msdn.microsoft.com/en-us/magazine/mt590972.aspx), any project that’s compatible with the dotnet moniker (.NET Framework 4.6, UWP or ASP.NET 5) should take the UAP folder over the netcore folder. So the reference that _should_ have been added should have been:

`packages\AppPromo.1.0.1-beta2\lib\uap10.0\AppPromo.UWP.winmd`

Do we need to set a minversion in our nuspec and demand NuGet 3.1? I sure hope not since I'm still trying to support back to WP8 with the same NuGet package.

It's also worth reiterating that the exact same package can be referenced and used perfectly well without modification if the project is a C# project. This seems to only be an issue with WinJS projects.

For reference, my [.nuspec is here](https://github.com/jbienzms/AppPromo/blob/master/Packaging/AppPromo.nuspec).

**Comment by angularsen** [comment]
@yishaigalatzer any update from the JS guys?

**Comment by yishaigalatzer** [comment]
Yes, we heard back a few ideas. We will need to spend time trying to get to the bottom of it. I expect the work to start in a few days or a couple of weeks at the latest.

In general I would advise that people that have older versions of NuGet (lower than 3.4.1 at the moment) should just update, and I wouldn't try to support older clients. Since visual studio Update 2, nuget is now in an automatic update mode.

Will loop back on this thread once we know more.

**Comment by angularsen** [comment]
Just to report that this behavior is still reproduced on the latest VS 2015 Update 2 and the latest nuget package manager.
- Microsoft Visual Studio Community 2015 Version 14.0.25123.00 Update 2
- Microsoft .NET Framework Version 4.6.01038
- JavaScript Language Service   2.0
- JavaScript Project System   2.0
- NuGet Package Manager   3.4.2

**Comment by yishaigalatzer** [comment]
Yes, this wasn't fixed yet

**Comment by yishaigalatzer** [comment]
Note that if you don't rely on content packages converting the packages.config to project.json unblocks this scenario. We are going to work on enabling the default scenario.

**Comment by angularsen** [comment]
I can confirm that manually adding a project.json works, but since adding a nuget via nuget package manager (3.4.2) adds a packages.config instead of project.json for a newly created WinJS app means the story is still currently broken. How will this be addressed? 

I see at least two solutions:
1. Fix the SpecificVersion error seen hwen using packages.config
1. Nuget package manager creates a project.json if neither files are present

Working project.json:

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "UnitsNet.WindowsRuntimeComponent": "3.30.0-alpha7"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by yishaigalatzer** [comment]
You are correct.

**Comment by joelverhagen** [comment]
I have verified that the provided `project.json` works when added manually. Example project:
[App1.zip](https://github.com/NuGet/Home/files/438007/App1.zip)

One strange thing I found is that when your platform in VS is set to Any CPU, restore fails since there is no `win10` runtime in the project.json. Adding `win10` doesn't work since the `Microsoft.NETCore.UniversalWindowsPlatform` package does not support this runtime.

```
error : Your project.json doesn't list 'win10' as a targeted runtime. You should add '"win10": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.
```

After adding `win10`:

```
Microsoft.NETCore.Portable.Compatibility 1.0.0 provides a compile-time reference assembly for mscorlib on UAP,Version=v10.0, but there is no run-time assembly compatible with win10.
```

**Comment by joelverhagen** [comment]
In NuGet code, we call the `VSLangProj.References.Add(string bstrPath)` API with the full path to .winmd file. This adds the following code to the .jsproj:

``` xml
<Reference Include="UnitsNet">
  <HintPath>..\packages\UnitsNet.WindowsRuntimeComponent.3.40.0\lib\uap10.0\UnitsNet.winmd</HintPath>
  <IsWinMDFile>true</IsWinMDFile>
</Reference>
```

NuGet then explicitly sets the following two elements:

``` xml
  <CopyLocal>True</CopyLocal>
  <SpecificVersion>True</SpecificVersion>
```

Lifeng Lu (in an email thread) said that `<SpecificVersion>` only works if your identity has a version in it. Notice how the identity is `UnitsNet`, not the strong name `UnitsNet, Version=3.40.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime`. If you manually set this strong name in the .jsproj, things work.

I'm following up with the owners of this project system to determine why the version is not written into the .jsproj. Presumably it can be determined since we are passing them the full path the .winmd.

**Comment by joelverhagen** [comment]
This issue is being tracking internally (Visual Studio bug 257713). More investigation by the project system owner is needed.

**Comment by kwiqniss** [comment]
@joelverhagen Long time no update. Any news?

**Comment by joelverhagen** [comment]
@kwiqniss, this issue will be investigated by the JavaScript project system owners for Visual Studio "15" RC 2. I will update this issue as we have more information.

**Comment by angularsen** [comment]
I know this is closed, but this happens to still be the case for WinJS UWP apps on latest Visual Studio as of 3 February 2018 (v15.5.6). I guess WinJS never got much love and is probably already a fading memory to most people.

**Comment by emgarten** [comment]
Thanks for the update @angularsen. We'll work with the javascript project system to help resolve this.

**Comment by zivkan** [comment]
Visual Studio 2019 removed support for UWP JavaScript apps. I guess we should close this issue?

**Comment by zkat** [comment]
Closing per https://github.com/NuGet/Home/issues/2406#issuecomment-754005681
