### ISSUE TITLE
In 3.4.1.807 search against "Microsoft and .NET" package source for System.Collections.Immutable fails

### ISSUE THREAD

**Issue by xperiandri** [NuGet/Home#2429]
<img width="1124" alt="search" src="https://cloud.githubusercontent.com/assets/2365592/14191839/b841b4d4-f7a2-11e5-9597-2cd4169751df.png">

**Comment by rrelyea** [comment]
That search works fine on nuget.org source. I suspect that this is not a NuGet UI issue, but rather an issue with the microsoftdotnet feed (https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Package/System.Collections.Immutable is not found via a web browser)
-- we are investigating...that web uri may not be the right way to find it..

**Comment by xperiandri** [comment]
Prism too
But installation works from console

**Comment by yishaigalatzer** [comment]
This is not a nuget bug, or a 3.4.1 bug. The curated feed does not include all the packages that nuget.org does.

I've emailed the team that owns this feed to see if they want to update it.

**Comment by Myfreedom614** [comment]
@xperiandri For 3.4.1 version, **the temporary work around** is to delete the C:\Users\{username}\AppData\Roaming\NuGet\nuget.config

**Comment by tbolon** [comment]
I have just solved the exact same problem.

My %appdata%\nuget\nuget.config was this (never edited by hand, never customized in VS):

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
</configuration>
```

In visual studio, the available package sources was empty. Because of a bug in the ui, the "+" and "Delete" buttons where grayed as soon as I click on the machine-wide package. Even when I deselect ths Microsoft and .NET package source, the buttons remains grayed. The only solution to allow the "+" button to be available again was to restart visual studio then go to se options screen, then press "+" without clicking anywhere in the listboxes.

As a workaround, I have deleted the nuget.config.

After having restarted visual studio, my config was:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

And now I can choose "All" (or nuget.org) as a package source when searching in nuget ui.
