### ISSUE TITLE
Issue on NuGet.Client (Visual Stusio 2015) --> The V2 feed at 'http://nuget.syncfusion.com/windows-forms/FindPackagesById()?Id='Syncfusion.Diagram.Windows40'' returned an unexpected status code '404 Not Found'.

### ISSUE THREAD

**Issue by bryjamus** [NuGet/Home#2443]
I get this error on version **3.4.1.807** Package Manager Console in Visual Studio 2015. Package restore works fine on version **3.3.0.167**. 
Source URL added to NuGet configuration is: [http://nuget.syncfusion.com/windows-forms](http://nuget.syncfusion.com/windows-forms)

![nuget_issue](https://cloud.githubusercontent.com/assets/7079299/14240025/b8bb1940-fa41-11e5-892e-ac82a6e7b867.png)

**Comment by fangs87** [comment]
I also have the same issue, couldn't find a workaround yet. Different package url, but the same he V2 feed at '{Url}/FindPackagesById()?Id='{Package}'' returned an unexpected status code '404 Not Found'.

**Comment by nathan-alden-sr** [comment]
I am running into the exact issue, and I bet it has to do with a NuGet Package Manager extension update that was pushed out to Visual Studio late last week. I have an internal package source I use for all my projects, in addition to the nuget.org package source. One annoying regression with the new NuGet tool window in VS 2015 was the inexplicable removal of the "All" selection when filtering package sources. I was stuck checking each package source individually for updates or whatnot. Since I installed the new extension update, however, All has returned. The problem is, the tool window is now _completely useless_ for updating due to this bug. The tool checks my custom package source _first_ for packages like `EntityFramework`; obviously, this results in a 404. What it _should_ do is continue checking the other package sources; instead, it simply aborts the entire update-checking process.

IMO, this needs to be fixed ASAP, as the only work-around I've been able to find is to manually update packages using PowerShell.

**Comment by shagenhokie** [comment]
Having the same issue with latest NuGet client version 3.4.1.807 against a few of our internal NuGet servers (Klondike v1.62).

Only workaround I could find was to downgrade to the previous NuGet client version 3.3.0.167.

**Comment by forderud** [comment]
This might be related to https://github.com/NuGet/Home/issues/2439

**Comment by nathan-alden-sr** [comment]
I think I figured it out! I changed the URL registered in `Tools | Options | NuGet Package Manager | Package Sources` from:

`http://myinternalklondikeserver:8081/api`

to:

`http://myinternalklondikeserver:8081/api/odata`

and now my updates work! I'm not sure _why_ this broke only now. I haven't touched my Klondike server in ages.

I did also notice that the Klondike dashboard page does state to use `/odata` at the end of the URL. I am pretty sure there was once a time that it wasn't necessary, but I guess now it is. :+1:

**Comment by nathan-alden-sr** [comment]
@forderud Looks like a separate issue. It looks like the same web service call, but it's failing for different reasons.

**Comment by emgarten** [comment]
This is a known issue, there is a fix for redirecting the source base url in NuGet 3.5.0.

Adding /odata to the url is the best workaround for this in 3.4.0.

**Comment by Kanimozhi12** [comment]
adding /odata is not working for me, any other workaround there?

**Comment by campersau** [comment]
In NuGet version 3.4.2.830 it works for me.

**Comment by emgarten** [comment]
@Kanimozhi12 update to NuGet 3.4.2

**Comment by bryjamus** [comment]
Version 3.4.2.830 works for me. Thanks.

**Comment by adroach1** [comment]
Try setting Nuget.org package source to the following for VS 2015
https://api.nuget.org/v3/index.json

I had the same 404 error most likely due to upgrading a 2012 solution to 2015. I'm using Nuget 3.4.2

**Comment by maxisam** [comment]
vs2015 update2 + version 3.4.3.855  with https://api.nuget.org/v3/index.json 

it still shows the error message

but it works if I use Install-Package from package manager console.

**Comment by jesslilly** [comment]
Friends!  I have another workaround.  For me, I had to **append my URL with /nuget**.  Then the Search api works.

**Comment by efrainsteinbach** [comment]
Same issue here (when using a TeamCity 8 Nuget feed) .. none of the above fixes seemed to work - I have now downgraded to Nuget Package Manager 3.3.x where it still works.

I was able to find the old version here: https://dist.nuget.org/index.html

**Comment by rlipovski** [comment]
This issue ist still there with the latest release version (3.4.x)

**Comment by emgarten** [comment]
@rlipovski what type of feed are you using? What output are you seeing from NuGet?

**Comment by rlipovski** [comment]
@emgarten we are using an internal nuget service (v1) and the output message is basically the same like in the title. I deleted the version 3.4.x and installed 3.3.x, which did the trick. after downgrading the nuget package manager is working again.

**Comment by emgarten** [comment]
@rlipovski if you are using team city change it from v1 to v2 NuGet feed mode. The 404 you are seeing comes from the request for FindPackagesById returning a 404 since it does not exist in v1.

**Comment by wpostma** [comment]
What is going on? Is Nuget.exe 3.4.4 and Visual Studio 2015 and the latest Nuget.Server v2.11.2.0 NOT compatible?

I thought nuget.server 2.11.x was api v3 compatible but visual studio still gives this kind of error:
`The V2 feed at 'http://something.mycompany.biz/NugetServer/nuget/Packages/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=true&$skip=0&$top=26' returned an unexpected status code '400 Bad Request'.
`

When I browse to `http://something.mycompany.biz/NugetServer/nuget/Packages` I see the RSS XML output I expect.

**Comment by rlipovski** [comment]
@emgarten thanks for the information!

**Comment by kevingoos** [comment]
I will get the following message: The V2 feed at 'http://nuget.com/api/v2/Search()?$filter=IsLatestVersion&searchTerm='AMD'&targetFramework='net452'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '404 Not Found'.

But the actual address of my private server is: http://nuget/api/v2/ so I don't knwo why he is going to nuget.com?

**Comment by emgarten** [comment]
@Ghosttje will you open a new issue for this and include your nuget.config files and repro steps? NuGet shouldn't be changing the URL in this way.

**Comment by somaraghuveer** [comment]
My Solution had different package sources defined. My VS15 was defaulting to a particular source in which I do not have the package I was looking to download. 
Here is what worked for me: 
Manage Nuget Packages >> Clicking on the settings icon next to _Package source_ field and unchecking the other package sources, I was successfully able to install the packages I needed.

**Comment by Latency** [comment]
Having a similar issue.   Unable to access my GitHub repository packages I have uploaded.

Obviously, the package is there since I am able to download it [here](https://github.com/Latency/HearthDb/blob/master/HearthDb/bin/Debug/HearthDb.10.0.1.nupkg)!

**Nuget.config**
```
<packageSources>
  <add key="HearthSim" value="https://github.com/Latency/HearthDb/raw/master/HearthDb/bin/Debug/" />
</packageSources>
```

`[HearthSim] The V2 feed at 'https://github.com/Latency/HearthDb/tree/master/HearthDb/bin/Debug/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.`
