### ISSUE TITLE
Client v3.4 is not up in the distribution link

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#2480]
Even if NuGet v3.4 client has been shipped as a VSIX (https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d), it's still not available from the console client url at https://dist.nuget.org/win-x86-commandline/latest/nuget.exe (not to mention the "old" http://nuget.org/nuget.exe which was never updated after 2.8...

**Comment by yishaigalatzer** [comment]
We plan to update to 3.4.2 by tomorrow. We do not plan to update the old link, because 3.X introduces breaking changes and we want to give it more time before we update there.

In the meantime you can find the bits on myget/nugetbuild feed - http://myget.org/gallery/nugetbuild (or on the latest link in dist)

**Comment by kzu** [comment]
Still not up on the distribution link. It's pretty serious, since more and more people are installing dev15.

As of right now, http://dist.nuget.org/win-x86-commandline/latest/nuget.exe is still 3.3

**Comment by xavierdecoster** [comment]
There was no nuget.exe release today, only vsix

**Comment by kzu** [comment]
We needed the exe :(. Had to switch back all the way to 2.8. Glad I didn't
move to project.json yet ;)

**Comment by xavierdecoster** [comment]
There's the 3.4.2-rc though on dist.nuget.org/index.html, tried that one?

**Comment by yishaigalatzer** [comment]
It is there, just not at the latest link. We have a couple of bugs to fix before calling it rtm.
