### ISSUE TITLE
Verify localization of new strings

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2498]
A test needed: verify that every displayed string, has corresponding values in all languages. This will prevent  a scenario when we add  a new string, but don't have it localized.

**Comment by yishaigalatzer** [comment]
This test should not be run as part of a regular build, because
1. Adding new strings will build the CI
2. The localization is built on a different server, so either the work is to merge the loc work into the main nuget CI build, or the test has to run on the second localization CI
3. The test should only run after localization pass
4. The test should include a mechanism to disable an error for a period of time (or something along this line) to not trip the CI until new strings show up.

The test should also include validation that all parameters in the original string such as `{0}` still appear in the secondary string and they are well formatted.

**Comment by skofman1** [comment]
Moved to: https://github.com/NuGet/Engineering/issues/50
