### ISSUE TITLE
All Source issue: NuGet throw exception when one package is not found in one source in update tab

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2507]
Repro Step:
1. have two sources in setting: nuget.org and http://klondikeserver:8081/api/odata.
2. open a console app and install System.IO.Abstractions 1.6.0 from nuget.org on UI.(make sure System.IO.Abstractions does not exist in http://klondikeserver:8081/api/odata)
3.click update tab.

Expect: no packages there.
actual: Got exception: The V2 feed at 'http://klondikeserver:8081/api/odata/FindPackagesById%28%29?id=%27System.IO.Abstractions%27&$skip=100' returned an unexpected status code '404 Not Found'

![allsource3](https://cloud.githubusercontent.com/assets/7131513/14397788/6601fd26-fd94-11e5-9e5e-136129ff1b73.PNG)

**Comment by damonwildercarr** [comment]
FYI - I installed this version and everything is now working correctly:

https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.2.821.vsix

**Comment by alpaix** [comment]
NuGet behavior is as-expected. The issue is caused by next link incorrectly encoded by Klondike server.
Should be:
`http://localhost:8080/api/odata/FindPackagesById()?id=%27System.IO.Abstractions%27&$skip=100`
Klondike responded with:
`http://localhost:8080/api/odata/FindPackagesById%28%29?id=%27System.IO.Abstractions%27&$skip=100`

Klondike issue https://github.com/themotleyfool/Klondike/issues/135
