### ISSUE TITLE
nuget.exe hangs when installing Microsoft.AspNet.Mvc 6.0.0-beta2

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2512]
```
nuget.exe install Microsoft.AspNet.Mvc -Version 6.0.0-beta2 -NoCache -Source https://api.nuget.org/v3/index.json
```

Output and hang.

```
Feeds used:
  https://api.nuget.org/v3/index.json

Attempting to gather dependency information for package 'Microsoft.AspNet.Mvc.6.0.0-beta2' with respect to project 'C:\Users\jver\Desktop', targeting 'Any,Version=v0.0'
```

While hanging, a single core of my CPU is running at max. Seems to be doing something. Other packages from NuGet.org install just fine. Happens with all NuGet.exe 3.x.

**Comment by yishaigalatzer** [comment]
CC @emgarten

**Comment by jainaashish** [comment]
We are trying to install a pre release version without specifying the prerelease flag so it tries to prune prerelease versions but since it has 190 packages depth dependency with many multiple prerelease versions so it's talking too much time to walk dependencies. So ideal solution is to use -pre flag while trying to install a prerelease version.
But through specified version also, we can come to know whether it's a prerelease version or not and then use it accordingly. I'll update the code accordingly now.

**Comment by jainaashish** [comment]
I'll also log another bug to improve WalkDependencies api performance since even in normal case, it's talking too much time to process.

**Comment by emgarten** [comment]
Porting to 3.4.5

NuGet/NuGet.Client@54e5f252f028ddfbcd123720b0a08a74b62f3cd1
