### ISSUE TITLE
Consider adding `includeInDependencies` property to a tool in project.json

### ISSUE THREAD

**Issue by NTaylorMullen** [NuGet/Home#2564]
## The Problem

For dotnet cli tools that need to load user projects you currently need to add your tool in both the `tools` and `dependencies node`. Example of what you currently need to do:

``` C#
{
  "dependencies": {
    ....
    "dotnet-razor-tooling": {
      "version": "1.0.0-*",
      "type": "build"
    }
  },
  "frameworks": {
    "netcoreapp1.0": { ... }
  },
  "tools": {
    "dotnet-razor-tooling": {
      "version": "1.0.0-*",
      "imports": [ "portable-net45+wp80+win8+wpa81+dnxcore50" ]
    }
  }
}
```

This approach encounters issues when a user tries to upgrade their project (or simply add a tool for the first time) and they then mismatch their tool versions. You can imagine `dotnet-razor-tooling` having v1 in the `tools` node and v2 in the `dependencies` node. This requirement then requires tools that need this dual existence to protect against calling themselves from invalid versions of the tool. Issue covering this requirement: https://github.com/aspnet/Coherence-Signed/issues/276
## The Suggestion

If we were to add an `includeInDependencies` property in `project.json` it could then look like:

``` C#
{
  "dependencies": {
    ....
  },
  "frameworks": {
    "netcoreapp1.0": { ... }
  },
  "tools": {
    "dotnet-razor-tooling": {
      "version": "1.0.0-*",
      "imports": [ "portable-net45+wp80+win8+wpa81+dnxcore50" ],
      "includeInDependencies": true
    }
  }
}
```

With this approach the tool is automatically included in the dependencies and will fail on restore if there happens to be a version conflict. This also enforces both instances of the tool to have the same API/expectations.
## Ideal world

Side thought: If we allowed tools to purely exist in dependencies and were to add net45 based tool support to dotnet (assuming they can be invoked via dotnet in the same way) then you solve this issue, maintain the same API that was agreed upon and no longer need to dispatch. Side thoughts :smile: 

/cc @DamianEdwards @Eilon @davidfowl

**Comment by Eilon** [comment]
BTW in some places you mention `includeInDependencies` and in some you mention `includeInProject`. Fix?

**Comment by NTaylorMullen** [comment]
Thanks @Eilon, fixed :smile:

**Comment by Eilon** [comment]
Talked to @NTaylorMullen some more and perhaps what we really want is a similar feature, but it's really more like `useThisDependency'sGraphToResolveTheProject'sDependency'sButDon'tActuallyDependOnThis`.

In other words, the package resolution system would use "this" dependency's dependencies to "lift" up the main project's dependencies, but it wouldn't actually include any of the dependencies in the graph.

E.g. let's say you have:

```
MyProject depends on:
- foo 1.0.0
- bar 2.0.0

SomeToolProject depends on:
- foo 2.0.0
- baz 3.0.0
```

Now from MyProject I want to use the SomeToolProject tool, so I add a `tools` reference to it. But that doesn't fix dependencies: SomeToolProject requires a newer version of foo (2.0.0) than what MyProject uses (1.0.0). So I add a **dependency** to SomeToolProject as well to "lift" its dependencies. But that's not cool, because I don't really want it to depend on it. I just want to use it to _lift_ the dependencies. And that's what this magical new feature would do: it would use the versions in the dependency closure of tools projects to lift up dependencies in the main project. But no new dependencies would ever be added (not to the tool itself, and not to any bespoke dependencies of the tool).

**Comment by NTaylorMullen** [comment]
One interesting thing that might need some additional thought is where this would leave desktop support for tools. When the project would be built for desktop it'd need to have the tool and all its dependencies side by side in the output directory for a dispatch invoke. Whereas for non-desktop builds it would not because the deps file would have all the information needed.

**Comment by rustd** [comment]
This would help simplify the web templates for ASP.NET Core as well. Here is what project.json looks like https://github.com/aspnet/Templates/blob/release/src/Rules/StarterWeb/IndividualAuth/project.json#L5

The tools are needed to be specified in the dependencies section as well which makes it hard to add and use tools
