### ISSUE TITLE
Statistics - Can we get more insight into 'Other'?

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#258]
From Twitter:
https://twitter.com/sforkmann/status/580061169228075008

tl:dr;

The 'OTHER' category is significantly outpacing other clients for a number of packages.  Can we investigate if there are other clients that need to be added to our statistics report online:

https://www.nuget.org/stats/packages/FAKE?groupby=ClientName

**Comment by yishaigalatzer** [comment]
We are going to add Xamarin, MonoDevelop and TeamCity as known clients. At the moment ASP.NET 5 is not providing us with a `user-agent` header, so until they do, there is going to be pretty large portion of other category because we can't filter it properly from other clients depending on `nuget.core`

See https://github.com/aspnet/dnx/issues/1546

@eilon

**Comment by johnataylor** [comment]
This is fixed in the database and should be visible in tomorrow's reports. We added Mono and Xamarin. JetBrains was already recognised.
