### ISSUE TITLE
Support  ReadMe.MD files in NuGet Packages

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#2583]

**Comment by zhili1208** [comment]
@joelverhagen are you working on something related to this

**Comment by joelverhagen** [comment]
Nope. @chenriksson, @skofman1, @anangaur - what should be done with this client issue? Is this a duplicate?

**Comment by chenriksson** [comment]
I'm closing as a dupe. After the latest discussion, we opened the following:
- client: https://github.com/NuGet/Home/issues/6056
- server: https://github.com/NuGet/NuGetGallery/issues/4730

Note, we also decided 'Documentation' was more appropriate than 'ReadMe' since it's really targeted more at consumers of packages rather than code.
