### ISSUE TITLE
package resolution fails if unreachable source exists

### ISSUE THREAD

**Issue by cocogorilla** [NuGet/Home#2598]
I presume this would work with any project type, however, I'm starting with a fresh F# library.

Visual studio version: 14.0.25123.00 Update 2
.NET framework version: 4.6.01038
Create new f# library
Add a source in nuget package sources "https://unreachable/nuget"
Package manager console -> install-package xunit

**Expected:**
search publicly available nuget source and local cache only, skip any source that's not available (for that matter, if the public nuget isn't available, check cache only)

**Actual:**
install-package : Exception 'System.AggregateException' thrown when trying to add source 'https://unreachable/nuget'.  Please verify all your online package sources are available.

**Workaround:**
If unreachable nuget source can be connected, via vpn or whatever, this solves the problem
Or, remove the unreachable sources.

**Comment by yishaigalatzer** [comment]
@cocogorilla the general reason this happens is because we can't actually guarantee a consistent package install behavior if one of the sources is off.

For example imagine the server is intermittently off, and it has a new version of xunit. As a user you will get quietly an inconsistent experience between multiple installs.

This seems simple enough when you install a single package with no dependencies, but get quickly out of hand when you have a reasonably large package graph, that would lead you to losing days.

So here is what I think should happen
1. We should have a much better error message, you don't want to see an aggregate exception in your face.
2. We should explain how to disable/hide the "misbehaving" feeds, and make it easily doable from any command (we are designing a feature to deal with it) https://github.com/NuGet/Home/issues/1627 
3. Find scenarios where a missing feed doesn't impede the work and enable it (in this case if you installed a specific version of xunit, that might just work, but install latest wouldn't)

**Comment by cocogorilla** [comment]
@yishaigalatzer I think the ability to disable a package source would suffice... I'm not currently aware of a way to do this.

Having said that, are there WARN level exceptions in Nuget?  What if I went to install or update a package and I received a yellow warning that something in my source list was amiss... or possibly require user consent to proceed?

It makes total sense that you would not ever want to find yourself in a situation where package versions were being swapped out without your knowledge just because your feeds were intermittent.  But 9 out of 10 times, I've got 3-12 packages from nuget.org and 0 to 3 package from an internal source.  So, 9 out of 10 times, I want the latest from nuget.org and don't care about the 0 to 3.

Those are just my thoughts.  Like I said, disabling a package source works for me.

**Comment by yishaigalatzer** [comment]
We have thoughts around this area, one of them is just to detect that your source is off and temporarily disable it (after letting you know).

We did enable a warning mode in the command line (-ignore failed sources or something like that), but in the UI it is quite hard to express and even harder to revert. But thinking about it again it might just work if we put enough time into cleaning up the scenario. I'll add a comment to the item
