### ISSUE TITLE
[Question] Can NuGet be hinted as to locations of packages?

### ISSUE THREAD

**Issue by IanKemp** [NuGet/Home#2641]
Please refer to this Stack Overflow question: http://stackoverflow.com/questions/36766798/nuget-restoring-packages-unnecessarily

I'm assuming the simple answer is "NuGet doesn't know/care about `HintPath` in the `.csproj` file, so it can't figure out that referenced packages already exist on disk". That answers the why, but still leaves me with the problem of duplicate packages being downloaded and stored (wasting bandwidth and disk space). Granted, this isn't a massive problem, but it is somewhat annoying (besides being unnecessary).

Is there any way to "hint" to NuGet that it should try to resolve packages from a specific location on disk, not just the root of the current solution? I've looked at the schema for `packages.config` but it seems very minimal.

**Comment by yishaigalatzer** [comment]
#### Good news in a few lines...

This is not supported, and we don't plan to add support directly for this scenario. You merge the packages folders across all the solutions using nuget.config, but porting/moving projects around cannot be supported.

#### Inserting good news

If you move your projects to rely on project.json instead of packages.config (csproj + projcet.json next to it), the packages folder is now common across all of your projects by default and there are no more hint paths or references added to the csproj files, so double win.

A bunch of big projects are already using it although it is still an experimental feature in visual studio. See Roslyn/NuGet/MsBuild. Our project's code is at https://github.com/nuget/nuget.client

#### Here are a couple of blogs/wikis on the subject

https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json
https://oren.codes/2016/02/08/project-json-all-the-things/

**Comment by yishaigalatzer** [comment]
@IanKemp closing as I think I answered your question, feel free to keep this discussion alive, and if there a feature to build/bug to fix we should figure it out as a result
