### ISSUE TITLE
nuget.exe and dotnet restore error experiences for Project.*.json

### ISSUE THREAD

**Issue by javiercn** [NuGet/Home#2654]
If I run nuget restore c:\path\project.something.json nuget client does nothing. It will be good for tools that rely on nuget (installers, etc.) to be able to directly give it a path no matter the name of the file and have nuget discriminate the case based on the file extension, or to have a parameter on restore that can be used to discriminate the case (project.json vs packages.config, vs solution vs msbuild project).

In the scenario that we have, we generate multiple project.json files for our dependencies one project.json file with a set of imports that we manually choose and one project.json without imports that we name project.noimports.json. As part of the verification process of our dependencies we want to run nuget restore on this file in order to determine which packages are causing us to add imports.

**Comment by rrelyea** [comment]
Looks like our Docs are out of date when it comes to this.
Either one of these should work for you:
`NuGet Restore <project.json> | <*.project.json>`

**Comment by javiercn** [comment]
That worked. Thanks! (changed the name for noimports.project.json and it ran fine

**Comment by rrelyea** [comment]
Let's improve the error experience.
`nuget.exe restore project.2.json`
gives no error.
`dotnet restore project.2.json`
gives:
`error: Invalid input 'project.2.json'. The file type was not recognized.`

Let's improve both...and make them the same.
Suggestion: 
if the file ends with `.json` -- but doesn't match the pattern
Say that supported patterns are `project.*` | `*.project.json`
If the file ends with `.config` -- but doesn't match the pattern:
Say that supported patterns are `packages.config` | `packages.*.config`

Let's also give an error experience for Nuget restore hamburger.txt (something that doesn't meat the pattern).

[Edit: updated so that stars are displayed rather than treated as markdown formatting]
