### ISSUE TITLE
Functional test 'UpdateScenariosWithConstraints' fails

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#267]
Functional test 'UpdateScenariosWithConstraints' fails. In order for the bug to get due attention, marked it as P0. Change priority as appropriate

Fails with 'Missing dependency information for package: A'

Perhaps, GetPackageUpdatesReturnAllVersionsAndPrereleaseVersionsIfTwoFlagsAreSpecified is also related. Please test that too. This is likely the case of pre-release versions not showing up on folder repositories

**Comment by emgarten** [comment]
This is failing due to the error message and the way we prune dis-allowed packages.

The test sets a constraint of A [1.0.0, 2.0.0) and then tries to update to 2.0.0. Failure is expected, the current product just does not fail in the same way yet.

Moving this to RTM. We should give better and clear messages around these scenarios.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.VisualStudioExtension@79705888d4a18fc829dc6ad69f3a58ea1e3ec050
