### ISSUE TITLE
Nuget restore should check if downloaded packages are structurally valid and warn if they are not

### ISSUE THREAD

**Issue by cdmihai** [NuGet/Home#2679]
This is the package consumer side of checking whether packages are structurally valid. The issue for the package producer side is #2678

If a user does restore and nuget downloads 500 packages, it would be a good user experience for nuget to check if the packages are structurally valid. Otherwise, somebody could publish a structurally invalid package and break arbitrary clients in arbitrary ways.

Valid needs to be defined

For the CLI, we've hit the issue where a user gets a malformed package in his transitive closure, where a native dll got put in the lib folder and not in the native folder: https://github.com/dotnet/cli/issues/2660

@piotrpMSFT

**Comment by emgarten** [comment]
Checking this at pack time makes sense, but on the consuming side the current behavior is expected, and NuGet doesn't have a way to know what will be done with the selected assets. NuGet doesn't read the assemblies at all today.

For packages.config scenarios in particular having a native dll works, `lib\net45` contains assets needed to make the package work on net45, it's not a guarantee that those items are actually net45 assemblies. This is just due to the way NuGet started where Visual Studio handled detecting what the assets are and what to do with them.

**Comment by cdmihai** [comment]
Does this mean that the CLI only works with a subset of Nuget packages, and should thus check for "CLI friendly packages"?

**Comment by davidfowl** [comment]
What's a structurally valid package?

**Comment by cdmihai** [comment]
Needs to be defined. Can you put anything in nuget packages? Can you zip recycle bin and rename it to .nupkg? :)

There should be some format / meaning to the contents which is checked somewhere. For starters, the directory structure. If a folder with some name has constraints (e.g. only has managed dlls) then nuget pack and maybe post restore should check that.

Maybe multiple Nuget package types need to be defined (managed, native, msbuild targets) each with its own verifiable set of semantics. Otherwise anything can blow up anytime.

And then various consumers of the nuget package model, like CLI, can impose constraints like "I only work with managed packages"

**Comment by rrelyea** [comment]
Triage - won't fix. The package producer is responsible to validate their package.
