### ISSUE TITLE
Version not parsed correctly

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2730]
Scenario:
Using project.json with .NET CLI.

project.json:
`{
    "frameworks": {
        "net451": {
        }
    },
    "dependencies": {
        "NuGet.Services.Metadata.Catalog": "3.0.*",
    }
}`
1. Run from command line: `dotnet restore`
2. Got error: 

```
Errors in C:\Nuget\NuGet.Staging\src\NuGet.Services.V3Repository\project.json
    Unable to resolve 'NuGet.Services.Metadata.Catalog (>= 3.0.0)' for '.NETFramework,Version=v4.5.1'.
```

The package exists on https://www.myget.org/gallery/nugetbuild, and it's version is 3.0.2496-r-master.
When specifying the exact version number in project.json, the package is restored correctly.

**Comment by emgarten** [comment]
The root cause of this is https://github.com/NuGet/Home/issues/912 since floating on the patch version will exclude prerelease packages. 

To make this more obvious I'm adding text to the error to specifically say that no stable version of the package could be found, and the nearest prerelease version that was found.
