### ISSUE TITLE
[Question] NuGet and JFrog - restoring packages without password

### ISSUE THREAD

**Issue by shepherd007** [NuGet/Home#2741]
Did anyone managed to configure NuGet/Artifactory to use ApiKey only? Currently we are using such configuration but every time active directory password changes, NuGet complains while restoring package with error 403. The only way to workaround that is to update password retrieved from JFrog in the NuGet. And since active directory password is changed frequently it is getting annoying.
The same happens when restoring packages by command line or in Visual C++ 2013.

**Comment by rrelyea** [comment]
Sorry, nuget.exe only supports basic auth. So therefore apikey only isn't possible.
We do have extensibility such that if JFrog wanted to support AD auth, they could implement it, like VSTS team has done.

**Comment by raspy** [comment]
@shepherd007 actually you can use Artifactory's API key instead of your password for basic authentication. You need to have Artifactory 4.4.3 at least and re-generate your API key if it was generated with pre-4.4.3 version. Artifactory API key does not expire on password change, it can only be reset on demand.

See [Artifactory 4.4.3 release notes](https://www.jfrog.com/confluence/display/RTF/Artifactory+4.4.3) for reference.

**Comment by shepherd007** [comment]
It seems to work. I just need to check if it works after password change as well.
To sum up:
- regenerating ApiKey password is mandatory (it is not sufficient just to generate ApiKey in JFrog!)
- Encrypted password is not being used - instead of that as a password ApiKey is required (nuget.exe sources add/update -Password ...)
