### ISSUE TITLE
Consider making project.json references case insensitive

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2819]
In `PackageSpecResolver`, we require that a project reference pointing to a `project.json` must have a name matching exactly in case ([source](https://github.com/NuGet/NuGet.Client/blob/f8e3c3c1aed6d6fe277dcbd43b29d978ebe2a3ce/src/NuGet.Core/NuGet.ProjectModel/PackageSpecResolver.cs#L15-L16)). This is an inconsistent experience with packages (which have case insensitive names).

We could make this case insensitive, but this causes a problem on Linux if there are multiple projects with the same name, only differing in case. We could deal with the problem by throwing an error/warning saying "ambiguous project name" or something.

**Comment by rrelyea** [comment]
Because we value the swap (back and forth) between source and nupkgs, this change sounds important.

Let's make the change to be case insensitive, and not check for dupes -- don't check for dupes in the local folder, and don't check for dupes in the global.json directories.

[would be great to check for dupes in verbose mode, or the like, but it sounds like we don't understand that setting.]

**Comment by emgarten** [comment]
Checks on project id should be case insensitive in 4.0.0
