### ISSUE TITLE
Missing developmentDependency attributes in packages.config

### ISSUE THREAD

**Issue by ElStefan** [NuGet/Home#2841]
Hi, I'm not sure if it's a feature request or a bug, but here is my issue:

I've created a .nuspec file with a dependency to another package, i am now able to mark my own package as a development dependency. Then i've installed it on one of my projects, and here comes the problem: just my own package has the attribute `developmentDependency="true"` on it, the dependent package doesn't.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MyPackage" version="1.2.3" targetFramework="net452" developmentDependency="true" />
  <package id="MyDependentPackage" version="3.2.1" targetFramework="net452" />
</packages>
```

The nuspec file looks like this:

```
...
<id>MyPackage</id>
<version>1.2.3</version>
<dependencies>
   <dependency id="MyDependentPackage" version="3.2.1" />
</dependencies>
<developmentDependency>true</developmentDependency>
...
```

I think it is supposed to work like this, but if I create a nuget package of the project, it has the dependency in it, which is not required for the package (code analyzer for example).

Would it be possible to add a new attribute to the .nuspec file to mark the dependent packages also as developmentDependency?

Like this:

```
   <dependency id="MyDependentPackage" version="3.2.1" developmentDependency="true" />
```

Thanks

**Comment by rrelyea** [comment]
This may work if the builder of the outermost package is using project.json, instead of packages.config.
They would need to mark the package as type:build (which is similar to developmentDependency).
Unfortunately, packages.config doesn't maintain information about MyDependentPackage, if it was a top level dependency, or just a subdependency.

We could add a feature for project.json to automatically add type: build when a packages installed by the NuGet system.
We'd love to hear if project.json scenario does work for you.

**Comment by ElStefan** [comment]
Thanks for your quick response.

I tried using project.json, getting even more issues..
I'm using an install script, it is required to set the projects active ruleset, but in [the introduction to project.json](http://docs.nuget.org/consume/ProjectJson-Intro#install/uninstall-scripts) it says, there won't be support for scripts anymore.
Doing this by adding a .props file as described in [here ](http://stackoverflow.com/questions/20267268/add-code-analisys-ruleset-through-nuget-package) did not work for me, so I'm stuck at this solution. Or did i miss something?

Apart from this, I tried to build a nuget package from a project using project.json, but the dependencies are completely missing in the created package (e.g. if one package is required, but the others are for development). It just contains the dlls from the project itself.. I installed it on a test project, but the execution fails, because of missing dlls from the dependencies.

I've never worked with project.json, so maybe I'm still doing something wrong :-)
Using the project.json in the project is working so far. and it's also referencing the dependent package, but it ignores the install script.

The project.json I'm using:

```
{
  "dependencies": {
    "RequiredPackage": "2.3.4",
    "MyPackage": {
      "type": "build",
      "version": "1.2.3"
    }
  },
  "frameworks": {
    "net452": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

The nuget command I'm using:
`NuGet.exe pack LibraryWithDependencies.csproj`

**Comment by aderesh** [comment]
Having the same issue: creating an MSBuild task which depends on Microsoft.Build package; marked `metadata->developmentDependency="true"`.  As a result, my assembly is marked with developmentDependency="true" in packages.config but Microsoft.Build and all dependencies (e.g. Microsoft.Build.Framework) are not, thus, are added as references to the project. I think this is a bug. 

Expected behavior: `metadata->developmentDependency="true"` marked not only a current package but also all package's dependencies as well. 

@ElStefan a temp solution for you would be http://blog.danskingdom.com/have-your-nuget-package-install-itself-as-a-development-dependency/. Long story short: add a ps script to manually set developmentDependency in packages.config upon installation. This is what people did before 'metadata->developmentDependency' was introduced :)
