### ISSUE TITLE
Allow compression level to be set when running `nuget pack`

### ISSUE THREAD

**Issue by hach-que** [NuGet/Home#2852]
We use NuGet to package a lot of internal assemblies and programs, and we'd like to be able to set the compression level to either `Fastest` or `NoCompression` instead of the current `Optimal`.  This is because we know there's a bunch of data in those NuGet packages which aren't compressable, and so `nuget pack` spends a bunch of time trying to compress the data when we don't need it to.  This significantly increases our build times.

We'd like to able to do something similar to:

```
nuget pack -CompressionLevel NoCompression ...
```

**Comment by yishaigalatzer** [comment]
We would gladly take a pull request for this issue if you would like to speed it up

**Comment by thesoftwarejedi** [comment]
@hach-que I created a branch and test release of the 3.4.4-rtm build with compression hardcoded to off so that we could test performance and see if this change was worth it.  

https://github.com/thesoftwarejedi/NuGet.Client/releases/tag/3.4.4-nct

I uploaded the binary in case anyone wanted a quick fix.

**Comment by Saturate** [comment]
@thesoftwarejedi What were the performance improvements? I'm having issues with nuget pach when packing 20.000+ files, it takes around 10 minutes.

**Comment by Artur-A** [comment]
Confirm the information from @Saturate .

We also have a large project, about 20 000 files/ 250 MB, and use NuGet (latest stable v3.5.0) to  pack this project for further transferring to Octopus Deploy. 

It takes __3.5 - 6 minutes__ to run `nuget pack -NoPackageAnalysis .nuspec` in different Windows machines.   

Default zip archiver seems to be a little bit faster, but also takes a lot of time. It would be nice to see the suggested lighter compression options and possibly some optimisation for large projects. 

![slow nuget pack](http://i.imgur.com/1SQM9eL.png "slow nuget pack")

**Comment by emgarten** [comment]
Currently I do not see evidence that changing the compression level would have a large enough impact on perf to justify this option. If someone can provide that please do 🌷

**Comment by richardgavel** [comment]
We have a content-only NuGet package which contains 2 ZIPs totalling 750 MB that gets created as part of our CI pipeline. Considering the frequency of change of the mainline branch, a 40 sec difference does matter. I don't necessary need command line setting of the specific compression level. You could just say, use NoCompression on a file-by-file basis depending on the extension.

**Comment by emmenlau** [comment]
@emgarten I do not understand why this issue was closed as WontFix, please reconsider. Compression takes significant time even on modern machines. You can test this very quickly yourself with `zip`, `tar` or any other tool. As an example, creating an uncompressed tar compared to `gzip`, `bzip` or `lzma` compression reduces the archive creation time to less than 30% in my tests. The same can easily be reproduced with `zip` or `rar` (try their weakest compression compared to standard compression).

For round trip development that involves creating a NuGet, every second counts. I sometimes create a NuGet 100 times a day or more, and reducing this by 10 seconds would be a very relevant improvement.

**Comment by emmenlau** [comment]
> Default zip archiver seems to be a little bit faster, but also takes a lot of time.

@Artur-A The runtime of the default zip archiver is heavily impacted by the compression level. The relevant part of this issue is that people need choice for setting this compression level to lower level, or disabled. Can you re-try with an archiver that has zero compression? 

As a random example, the user here got a 30% speedup when changing zip compression from default level 6 to 1: https://superuser.com/q/591154/1053994. With zero compression, this would very likely have given another 10-20% speedup.

**Comment by emmenlau** [comment]
Could this issue please be reconsidered?

I waste 2 minutes on every build for compression, compared to the time it takes `tar` to just archive the files uncompressed. If we build 30 times a day, we waste one hour of valuable time! This waste of time is really really unpleasant.

**Comment by nietras** [comment]
In https://github.com/NuGet/Home/issues/6208#issuecomment-889114649 I touch on why this is being able to specify maximum compression is a must, since otherwise we cannot put nuget packages on nuget.org due to size limit.

It seems less than ideal that we would have to manually make the `nupkg` files ourselves to over come this. A simple option should be simple to add.

Note that I am advocating for both being able to not compress and compress as much as possible, hence a compression flag. :)

**Comment by corngood** [comment]
Uncompressed packages would be useful in nix so that runtime dependencies (e.g. shared library paths in executables) are not obfuscated.

**Comment by dafunkjoker** [comment]
Is it possible to reopen this issue?
Configurable compression should be simple and useful without a doubt.
