### ISSUE TITLE
Changing the NuGetpath to global location

### ISSUE THREAD

**Issue by bnayae** [NuGet/Home#2883]
When changing the NuGet cache to global location i.e. %appdata%\NuGet\NuGet.Config
some NuGet's packages keep the path to the Cache directory within the project i.e .csproj file
for example: Microsoft.Diagnostics.Tracing.TraceEvent keeping the following information
 `<Import Project="..\packages\Microsoft.Diagnostics.Tracing.TraceEvent.1.0.41\build\Microsoft.Diagnostics.Tracing.TraceEvent.targets" Condition="Exists('..\packages\Microsoft.Diagnostics.Tracing.TraceEvent.1.0.41\build\Microsoft.Diagnostics.Tracing.TraceEvent.targets')" />
`
the outcome is that the project compilation failed, unless the path exist, which may not be the case on multi dev environment

**Comment by yishaigalatzer** [comment]
You probably mean "moving the nuget packages folder" rather than moving the cache?

This is expected and you will have reinstall the packages using `Update-Package -reinstall` command. 

In the newer transitive restore mode (ala UWP apps, xproj) there is no longer a link to the files, and that issue goes away completely.

At least at this point we do not plan to make any changes here going forward.
