### ISSUE TITLE
Add option to suppress automatically adding project output to package

### ISSUE THREAD

**Issue by jcshalom** [NuGet/Home#2886]
When I use a VS project to just produce artifacts of a tools-only package, I do not want the project to automatically inject the project output into the lib folder. I'm basically just using the project as both a creator of some tools artifact and as a trigger to execute my .nuspec that defines the exact contents of the package. This would be enabled if I had a way to suppress nuget pack from auto injecting the project output into the package. Please add this as a new feature. Thanks!

**Comment by toddm** [comment]
Can you tell us more about what you're doing?  Are you packing by passing in a nuspec file or a csproj file?  If you're passing in a nuspec file and you don't want it to pick up other files, you can add an empty <files /> tag outside of <metadata> in the nuspec file.  That will make it so that pack doesn't include any extra files other than what is specified.
Is that the issue, or is it something else?  If it's something else, can you share a nuspec so we can better understand?

**Comment by jcshalom** [comment]
I’m passing a project file, not a .nuspec, and it automatically includes the project output when I do this. I figured out how to work around it using the .nuspec directly in a build step following the compile.

Thanks!
- Karl
