### ISSUE TITLE
Nuget v3 restore issues

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2891]
@ericstj said If I look at the dat file, the bottom has
`<link rel="next" href="https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost'&amp;$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost','1.0.0-rc3-23720'" />
` 
Now if I unescape that string and type it into the browser I get a new payload with 
`<link rel="next" href="https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost'&amp;$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost','1.0.0-beta-23302'" />`

Try again and I get
`<link rel="next" href="https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost'&amp;$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost','1.0.0-rc3-23720'" />`

Repeat at infinitum.

This may have a few fixes...server, moving to v3 protocol.
We should understand if a client fix can detect the cycle on the client, instead of running out of memory.

@jainaashish - will oop you in a mail thread called "Nuget v3 restore issues" with more details.

**Comment by rrelyea** [comment]
we'd consider this fix for 3.4.5 and/or 3.5-beta2 if timeframes match.

**Comment by jainaashish** [comment]
It was a server side cache issue, which has been fixed by Maarten. Also verified at client side, it's working good across nuget client versions. Below is the email communication snapshot:

From: Maarten Balliauw 
Subject: RE: Nuget v3 restore issues

Seems there was a faulty server-side affinity cache at play, which resulted in having a different output cached from different web nodes. Which in turn resulted in what you were seeing below, where each request would come from a different cache that had a different ordering of packages. 
Server-side issue has been solved.

From: Wes Haggard 

> dotnet --version
> 1.0.0-rc2-002673
> dotnet restore project.json --source https://dotnet.myget.org/F/dotnet-core 
> Run that with the attached project.json. I get the following forever:

info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-beta-23302'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-rc3-23720'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-beta-23302'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-rc3-23720'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-beta-23302'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-rc3-23720'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-beta-23302'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-rc3-23720'
info :   CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById?id='runtime.ubuntu.14.04-x64.Microsoft.NETCore.Te
stHost'&$skiptoken='runtime.Ubuntu.14.04-x64.Microsoft.NETCore.TestHost','1.0.0-beta-23302'

**Comment by jainaashish** [comment]
So no fix required from client side. closing this issue.

**Comment by jainaashish** [comment]
reactivating the issue, although it was server side fix, but client should still handle it gracefully instead of going into infinite loop and eventually throwing outofmemory
