### ISSUE TITLE
Files without an extension, not appearing in nupkg using nuget 3.4.3 and above

### ISSUE THREAD

**Issue by holytshirt** [NuGet/Home#2936]
If I create a new .nuspec like this:

``` xml
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>Test</id>
        <version>1.0.0</version>
        <authors>Test</authors>
        <licenseUrl>https://www.test.com</licenseUrl>
        <projectUrl>https://git.test.com/test</projectUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Test Package</description>
    </metadata>
    <files>
        <file src="VERSION" />
    </files>
</package>
```

and  do `nuget pack test.nuspec` with nuget verion 3.3.0 and below there are no problems.

![nuget package pack 3 3 0](https://cloud.githubusercontent.com/assets/90132/15935002/a94a9f80-2e5d-11e6-9c36-56cf2aebc586.PNG)

If I  do `nuget pack test.nuspec` with nuget version 3.4.3 - v3.5.0-beta the VERSION file does not appear in the package metadata.

![nuget package pack 3 4 4](https://cloud.githubusercontent.com/assets/90132/15935065/ecf8d68e-2e5d-11e6-8d00-402cf05af4b5.PNG)

The file is in the package if I unzip it.

So it seems that files without an extension are the issue, if I add a .txt extension and update the .nuspec everything works fine.

Is this a bug or have you dropped support for files without an extension?

Here is the example I'm using: 
[NugetNoExtentionIssue.zip](https://github.com/NuGet/Home/files/307274/NugetNoExtentionIssue.zip)

**Comment by rrelyea** [comment]
Please investigate

**Comment by toddm** [comment]
This was pushed to Dev.  Need to decide if it should go to 3.4.5 or 3.5.0-beta2.

**Comment by holytshirt** [comment]
Awesome thanks all!

**Comment by rovinbhandari** [comment]
@toddm, did this fix eventually make it to 3.5.0-beta2?
The bug regresses if, let's say, `target="lib\net40\"` is specified for a file without an extension. I'm running [3.5.0-beta2](https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe).

Additionally, if for a file without a version, the specified target doesn't have a trailing backslash (i.e., `target="lib\net40"` is specified), nuget pack succeeds; but the package cannot be used/restored. The reason is that the 'file without extension' is just zipped as a new file called 'net40' inside the lib directory. Windows explorer is able to open the zip (but not extract; also, 7-zip couldn't extract it); screenshots below:
![image](https://cloud.githubusercontent.com/assets/729475/17407599/25d35c82-5a68-11e6-8239-5a3e81357a45.png)
![image](https://cloud.githubusercontent.com/assets/729475/17407684/8bc01832-5a68-11e6-9e6e-cc10e43ffd4c.png)

**Comment by JobaDiniz** [comment]
Latest version today is [3.4.4](https://dist.nuget.org/index.html). Issue's _Milestone_ shows `3.4.5`. Question: `3.4.4` has this fix?

**Comment by danielmclaugh** [comment]
This still appears to be a problem in 3.5 especially if you use filters such as below in the nuspec file.
```
<files>
	<file src="foo\**\*.*" target="lib" />
</files>
```
