### ISSUE TITLE
Double dot in file src in .nuspec doesn't work

### ISSUE THREAD

**Issue by kkostrzewa** [NuGet/Home#2947]
nuget.exe 3.4.3.855

When I create a .nuspec file with file entries with src composed of .. paths, the files will not embed into the generated .nupkg, but will not report as errors.

The attached 
[nuget_bug_relpath.zip](https://github.com/NuGet/Home/files/308213/nuget_bug_relpath.zip)

demonstrates the problem.

nuget pack -verbosity detailed
will not display any errors, but it will not embed the 
`<file src="subdir\..\foo.txt" target="lib\" />`
file

**Comment by rrelyea** [comment]
Can you please try nuget.exe v3.4.4 (http://dist.nuget.org/index.html) - do you still see the problem?

**Comment by kkostrzewa** [comment]
nuget.exe v3.4.4.1321 still shows the problem

**Comment by toddm** [comment]
It works for me in Dev and the latest 3.5.0-beta2 build but not in 3.4.5.

**Comment by rrelyea** [comment]
after we finish b2 validation, please port to 3.4.5

**Comment by joelverhagen** [comment]
Hey @kkostrzewa, it looks like this is fixed in our latest release of nuget.exe, which is version `3.5.0-beta2`. You can download it from https://dist.nuget.org/index.html, or with this direct link:
https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe

If your issue still persists, please feel free to comment back and re-open this issue. Thanks!
