### ISSUE TITLE
Should VS UI be able to install unlisted packages?

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3018]
Currently, the `Install-Package` command allows you to install a version of a package that is unlisted if you specify the version explicitly.

```
Install-Package Newtonsoft.Json -Version 8.0.1-beta1
```

This install experience in not available in the UI.

So, the question is, should we allow this? Today we also support restoring unlisted versions, but that should definitely still be allowed.

/cc @jainaashish

**Comment by emgarten** [comment]
This is by design, unlisted just means that the package is hidden from search and the gallery. There are still many reasons why users would install unlisted packages, such as EntityFramework version 7.0.x.  (The highest shown in the gallery is 6.1.3)

For a time it was not possible to install unlisted packages in 3.0.0 RC and it was a problem: https://github.com/NuGet/Home/issues/544

**Comment by joelverhagen** [comment]
Closed as "by design".
