### ISSUE TITLE
Error when "Install-Package jquery.validation" on dev15

### ISSUE THREAD

**Issue by v-sojian** [NuGet/Home#3061]
Nuget: 3.5.0.1544 on dev15
Repro Steps:
1.  Click File -> Visual C# ->Office/SharePoint ->SharePoint Add-in ->click ok
2.  Enter the SharePoint site and select Provider and click next. Then select SharePoint Online click finish.
3.  Start Package Manager Console and type " install-package jquery.validation" then meet the error, as the picture  shows.
![3](https://cloud.githubusercontent.com/assets/19919607/16438925/1d92e252-3de6-11e6-96e2-4928afc76619.png)
4.  Then delete the "Packages" folder from the solution and build the solution, meet the error as the picture shows.
![4](https://cloud.githubusercontent.com/assets/19919607/16438927/2374f822-3de6-11e6-824c-50cd787a1263.png)

Expected:
No errors.

**Comment by joelverhagen** [comment]
This seems to be due to the fact that this template depends on the 3.1.5 version of `AppForSharePointWebToolkit`, which is not available on NuGet.org or in the `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages` installer source.

This is the latest version on NuGet.org:
https://www.nuget.org/packages/AppForSharePointWebToolkit/3.1.4

I am following up with the owner of this package to determine why the 3.1.5 version is not available.

**Comment by joelverhagen** [comment]
This problem only existing in Visual Studio '15 (dev15) Preview 3, which is not publicly released yet. I confirmed with the package owners that the package will be published prior to Preview 3 release.
