### ISSUE TITLE
Is there any way to specify the HintPath of packages?

### ISSUE THREAD

**Issue by z2xlong** [NuGet/Home#3141]
Hi,

I have a system environment variable %REPO% to link to a folder, Is there any way change the default HintPath like '....\packages\dummy.dll'   to '$(REPO)\packages\dummy.dll'  in the .csproj file? 

Thanks.

**Comment by emgarten** [comment]
NuGet doesn't support this, but you can edit your csproj manually after installing to update it.

**Comment by z2xlong** [comment]
IMHO, maybe this is a helpful feature that is used to decouple the path on the dev environment and the path on the build environment.

**Comment by chadgrant** [comment]
yay, I get to update my cs proj's every single time I update a package, yay!

Since the references are at the PROJECT scope, you should be using the proj file as the relative root, not the solution. You can have many solutions that one project file are in.

I could even live with a proj file property to tell it where the root is, right now it's just pooping all over my drive depending on which solution I have open.

**Comment by emgarten** [comment]
Converting to use PackageReference instead of packages.config solves this issue going forward. PackageReference does not make any changes to the project files and packages are discovered from a user wide location.

http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by chadgrant** [comment]
yeah, won't do us any good for years, still need backwards compatibility
