### ISSUE TITLE
Warn when Pack command excludes a file that starts with . 

### ISSUE THREAD

**Issue by gep13** [NuGet/Home#3308]
I recently ran into an issue where executing a `nuget pack` wasn't working, resulting in the following error:

![image](https://cloud.githubusercontent.com/assets/1271146/17614510/df5766d4-605e-11e6-890e-a66a3ae50efa.png)

After doing some digging, it turned out that this was due to the fact that I was using `.build` within the paths of the files that I was trying to include.  When I changed this to use `BuildArtifacts` instead everything started working again.

I reached out to @ferventcoder who mentioned that he had seen something like this before, and had in fact mentioned it here:

https://twitter.com/ferventcoder/status/505048107520765952

Back when there was no formal mechanism to report issues for NuGet.

The particular issue that Rob was referring to is due to the code that is located here:

https://github.com/NuGet/NuGet.Client/blob/a83e1070d7bd4d52d01ec960a5431d32874f9a8f/src/NuGet.Core/NuGet.Commands/PackCommandRunner.cs#L41-L46

More and more build systems/tools are using conventions where a `.` is included in either the file or a directory, so I personally think that this needs to be addressed.

Original bug report here: https://nuget.codeplex.com/workitem/4285

**Comment by gep13** [comment]
The original problem and solution to this is captured here: http://stackoverflow.com/questions/38911494/why-does-nugetpack-respond-with-cannot-create-a-package-that-has-no-dependencie

**Comment by rrelyea** [comment]
@rohit21agrawal - when we get to 3.6b2 issues, can you do an analysis of the info here and discuss the best strategy.

**Comment by mgasparel** [comment]
Came across this thread diagnosing an issue I was having. I was trying to include file with a relative path starting with "./" or "../" and they were being ignored as well.

**Comment by gep13** [comment]
@mgasparel I wasn't sure if they were related or not.  I had thought about this issue when we were talking on Gitter 😄

**Comment by forhot2000** [comment]
I have the same problem in MacOS, and I don't have specified OutputDirectory

my directory structure is:

+ EACPSO.dll
    - EACPSO.dll.nuspec
    + lib
        + 2.0
            - EACPSO.dll

build with command `nuget pack EACPSO.dll.nuspec -verbosity detailed` under directory `EACPSO.dll`

```shell
~/work/EACPSO.dll $ nuget pack EACPSO.dll.nuspec -verbosity detailed
Attempting to build package from 'EACPSO.dll.nuspec'.
System.InvalidOperationException: Cannot create a package that has no dependencies nor content.
  at NuGet.PackageBuilder.Save (System.IO.Stream stream) <0x2cf51c0 + 0x002ff> in <filename unknown>:0
  at NuGet.Commands.PackCommand.BuildPackage (NuGet.PackageBuilder builder, System.String outputPath) <0x2cf4328 + 0x0014b> in <filename unknown>:0
```

NuGet Version: 2.8.5.0

----

sorry, this has been solved after version 3.5.0.1996, it is solved after updated the nuget cli.

**Comment by chwarr** [comment]
I just ran into this issue with version  3.4.4.1321 when one of my intermediate directories (specified via a property) was `.build`:

```
<file src="$SomeRoot$\path\to\foo.h" target="build\native\inc\" />
```

And packing via `nuget pack foo.nuspec -Properties SomeRoot=..\.build`

**Comment by rohit21agrawal** [comment]
try passing -NoDefaultExcludes as a switch.

**Comment by chwarr** [comment]
Yup, `-NoDefaultExcludes` has made it work in my situation (`nuget pack foo.nuspec -Properties SomeRoot=..\.build`).

I can understand by default excluding a file/directory that *matches a glob* if it starts with a dot. I find it a bit of a stretch to exclude an *explicitly listed file/directory that happens to contain a dot prefix* anywhere. Though, I can see how the architecture of the application could easily have this behavior, depending on where in the pipeline the excludes are processed.

**Comment by ferventcoder** [comment]
> I can understand by default excluding a file/directory that matches a glob if it starts with a dot. I find it a bit of a stretch to exclude an explicitly listed file/directory that happens to contain a dot prefix anywhere.

I call this a bug - and I called it a bug 3 years ago at http://nuget.codeplex.com/workitem/4285 and here https://twitter.com/ferventcoder/status/505048107520765952.

The key point of why it is a bug is that it excludes those explicitly included items by default and without warning.

**Comment by ferventcoder** [comment]
The key point was that it still excluded those explicitly included items.

**Comment by Kyle-Muir** [comment]
I'm going to add my comments here since I don't think this warrants a dedicated issue of it's own.

As @ferventcoder indicated this issue is frustrating because nuget.exe (version: 4.5.1.4879) doesn't provide any feedback that these files are being excluded even when passing `-verbosity detailed`.

It would have been much simpler to diagnose and fix if there was any indication at all that my explicitly included files were being dropped out.

**Comment by rohit21agrawal** [comment]
@Kyle-Muir thanks for bringing this to my attention. Agree this is an issue and I have started working on fixing this such that it will warn for each file that is excluded because of the default exclude wildcards. These warnings will be suppressible in the csproj file (or via the -Properties ) switch.

The feature itself will land in NuGet.exe 4.7.0 (equivalent to VS 15.7).

**Comment by ferventcoder** [comment]
@rohit21agrawal So what about fixing the bug? If a user indicates explicitly that they want a file/folder in the package and it doesn't happen, warning or not, it's still a bug. A workaround should not be required either. That's why Chocolatey corrected this behavior in our version of NuGet years ago.

**Comment by rohit21agrawal** [comment]
@ferventcoder  unfortunately, the way the application is written, will require substantial re-work to determine if something was included as a result of being hardcoded or as a result of wildcard. It's especially more difficult with ``` dotnet.exe pack / msbuild /t:pack ``` where msbuild resolves all the wildcards and passes NuGet a full list of files. 

For now, a reasonable workaround of including these files is just passing -NoDefaultExcludes switch, which will also be suggested as part of the warning.

**Comment by ferventcoder** [comment]
> For now, a reasonable workaround of including these files is just passing -NoDefaultExcludes switch, which will also be suggested as part of the warning.

@rohit21agrawal  August 28, 2014 - that's when I logged the bug and informed the team. I was hoping for at least a warning then. I'm glad that you are working to finally address this now, although I'm not sure if *reasonable* bears in mind given that much lead time to fix the architecture. 

That aside, thank you for finally doing something about this.

**Comment by rohit21agrawal** [comment]
@ferventcoder I understand your concern and frustration at the delay in fixing this issue. We are a small team, and as you can see we have over 900 issues in our backlog which we need to prioritize based on user impact. This is apart from all the new features that we have added over the last year to make the user experience better. While I can't tell you the historical reason at why there was so much delay in fixing this issue since I wasn't even a part of the team back then, I do want to say that we are trying our best to be more attentive to feedback, and hopefully, in sometime we will be at a stage where we can allocate time in our backlog to rework our architecture to fix issues like these. 
Thank you for your patience and really appreciate your feedback!

**Comment by ferventcoder** [comment]
@rohit21agrawal no worries. I was part of the NuGet team from 2010-2011ish (non-softie).

**Comment by ferventcoder** [comment]
@rohit21agrawal well that was enough to get me to file the issue https://github.com/NuGet/NuGetGallery/issues/5495

**Comment by jzabroski** [comment]
> It's especially more difficult with `dotnet.exe pack / msbuild /t:pack` where msbuild resolves all the wildcards and passes NuGet a full list of files.

@rohit21agrawal This seems to describe a problem I'm running into where I have a `<Project Sdk="Microsoft.Build.NoTargets/3.0.4">` where the only MSBuild-visible contents are a `.nuspec` file.  The issue is I am manually packing stuff myself via a `.nuspec` file and copying stuff to `$(OutDir)`.

Is there anyway to "ghost-pack" some sentinel file so that MSBuild thinks its packing something that doesnt exist?

Below is a rough sketch of what my csproj looks like

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.Build.NoTargets/3.0.4">
  <!-- ReSharper disable UnknownProperty -->
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyTitle>MyCompany.DatabaseMigrationTool</AssemblyTitle>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BuildPackage>true</BuildPackage>
    <PackageVersion>0.0.0.1-dev</PackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NuspecFile>package.nuspec</NuspecFile>
    <NuspecProperties>version=$(PackageVersion);id=$(AssemblyTitle);description=$(AssemblyTitle);authors=$(Company);copyright=$(Copyright)</NuspecProperties>
    <NoWarn>NU5100,NU5110,NU5111</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MyCompany.DatabaseMigrationTool" Version="*" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageBinDirectoryContents Include="$(PkgMyCompany_DatabaseMigrationTool)\bin\**" />
  </ItemGroup>

  <!-- Copy the files to the output directory -->
  <Target Name="CopyPackageDirectoryFiles" AfterTargets="Build">
    <Copy SourceFiles="@(PackageBinDirectoryContents)" DestinationFolder="$(OutDir)" />
  </Target>

</Project>
```

.nuspec file:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>$Id$</id>
    <version>$Version$</version>
    <description>$Description$</description>
    <authors>$Authors$</authors>
    <copyright>$Copyright$</copyright>
  </metadata>
  <files>
    <file src="bin\release\**\*" target="" />
    <file src="*.config" />
    <file src="*.xml" />
  </files>
</package>
```
