### ISSUE TITLE
Global Tools Deployment

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#334]
Package managers like npm allow us to install tools with the -g switch (e.g. `npm i hjson -g`) so I can use it from the commandline (e.g. `hjson file.hjson`).

Would it be possible to add a similar functionality that can install an exe in my path to NuGet?

**Comment by deepakaravindr** [comment]
Comment from @dimsedane
You could take a look at https://chocolatey.org/, which uses nuget to install applications.

**Comment by deepakaravindr** [comment]
Comment from @ChrisSfanos 

Other teams are working on this type of solution, but we don't have anything we can share - thanks!

Ex: https://github.com/oneget

**Comment by ChrisSfanos** [comment]
NuGet triage has decided not to do this - thanks

**Comment by jasonwilliams200OK** [comment]
Will it be possible to share packages over network drive?
We use global pacakges folder on our server. Every now and then (whenever someone updates a package) it start emitting those `<EnsurePackage>` tags in project file which force the solution build to download not single/missing/renewed but ALL packages locally! This is broken behavior is so many ways. 
So please bring the global installation. Also make sure "ensure package" feature is aware of what is missing and that it only install missing package rather than blindly start installing the plethora of packages.
