### ISSUE TITLE
Publish guidance for minClientVersion

### ISSUE THREAD

**Issue by sandersaares** [NuGet/Home#3346]
I am not able to find any published documentation or guidance about what should be specified as minClientVersion when publishing NuGet packages. It is not at all obvious to know what version supports what feature.

An authoritative reference for this would be very useful.

**Comment by karann-msft** [comment]
@sandersaares see here https://docs.nuget.org/ndocs/schema/nuspec#optional-metadata-elements

> minClientVersion	(2.5+) Specifies the minimum version of the NuGet client that can install this package, enforced by nuget.exe and the Visual Studio Package Manager.

**Comment by sandersaares** [comment]
Not sure why this is closed. By guidance, I obviously mean "How do I determine the proper thing to put in here?" not "What does this field mean". There does not seem to be anything like this covered in the docs.

**Comment by kraigb** [comment]
@sandersaares With https://github.com/NuGet/docs.microsoft.com-nuget/pull/253 I added more details to the minClientVersion nuspec ref, see https://docs.microsoft.com/en-us/nuget/schema/nuspec under "Optional metadata elements". Simply said, if you look at the nuspec ref for any feature that was introduced after version 2.5, like <contentFiles> in 3.3 then you'd want to specify the version like "3.3" in this attribute so that the NuGet client installing the package would understand that part of the nuspec.
