### ISSUE TITLE
Build targets dependencies resolution

### ISSUE THREAD

**Issue by iskiselev** [NuGet/Home#3417]
Looks like there is no way for project that install build targets resolve path to other nuget packages that are declared as it's dependencies from MsBuild targets (unless if dependency version is not fixed).

For example, I'd like to create 2 packets:
1. Packet.Tool, that will contain tools\utility.exe
2. Packet.Build, that dependent on Packet.Tool [1.0,2.0), with build\Packet.Build.targets, that should use  utility.exe from previous package.

Do I miss something?

**Comment by rrelyea** [comment]
In 3.6 beta1, we've changed the sort order for targets and props files from alphabetical to dependency order. As part of this work, A which uses B which uses C will end up including the following, and in this order:

C.props
B.props
A.props

....

C.targets
B.targets
A.targets

In order to achieve your desired goal, you would likely need to include a props for Packet.Tool pointing to setting a property to the path of utility.exe.

**Comment by iskiselev** [comment]
Thank you for quick answer.
Unfortunately it is still not solve problem if original packet is controlled by other persons.
There are lot's of packages that contains some tools in NuGet already, and lot's of authors publish updated version of tool to NuGet.
If I'd like to create package, that will use such tool inside MsBuild, there is no possibility to do it in clear way now.
