### ISSUE TITLE
update command breaks on first package update failure instead of trying to update the rest of packages from packages.config

### ISSUE THREAD

**Issue by Vasilich** [NuGet/Home#3421]
We are using local NuGet Server, that can proxy/cache requests to external Nuger servers. On this server we publish out own nuget packages. Surely our projects use both our and external packages, so first thing our BuildServer does is restoring packages before building the project/solution. After that it should **update only our packages to latest version** so we call update command and define nuget feed where only our packages are present.
With NuGet v2.8 or 2.12 (we tested both) everything works as expected - nuget checks every package in packages.config, writes warnings for those which weren't found in given feed (i.eall extrnal packages), updates all our packages to the latest version, and exits.
But Nuget 3.x unfortunately breaks on first failure to update external package (and hense cannot find it in given feed), writing the message 
`Attempting to gather dependency information for multiple packages with respect to project '<http://192.168.30.207:8080/job/Bfe/ws/Bfe.csproj',> targeting '.NETFramework,Version=v4.5.1'
Package 'System.Reactive.Core' is not found in the following primary source(s): 'http://192.168.30.207:8081/nexus/service/local/nuget/ksc/'. Please verify all your online package sources are available (OR) package id, version are specified correctly.`
and exits.
I can't reproduce this behavior when passing solution file as parameter, but it happens always when passing packages.config file. 
I don't think this is intended behavior.
I have seen issue #1490 where other people stated the same behavior, but that issue was closed with solutiuon 

> A clear message is now given on the command line in the most recent builds. 

Actually I see no way to achieve my needs without learning every BuildServer Job to update only defined packages for every project, and change/adjust it every time project changes its packages, so it is clear regression comparing to v2.

**Comment by yishaigalatzer** [comment]
I'll let the engineers take a deeper look and help with a suggestion, but this is somewhat intentional. When not having all the versions available the end result of an update operation is not deterministic. We have considered mechanism that will allow narrowing down what updates to take. 

I know I'm not answering this specific question, but at the same time, we are moving away from packages.config going forward and want to encourage folks to start looking into this newer model.

In NuGet 3 we introduced support for project.json instead of packages.config as the way to define packages (this is not the .NET core scenario) and we are going to do more work in the next release of visual studio to take it to the next level. With this approach updates on the server become a lot simpler. You can add version ranges to the packages in project.json with a "_" notation e.g. 1._ and these packages will be restored to the latest version required. [here](https://oren.codes/2016/02/08/project-json-all-the-things/) is a blog post talking about this new pattern.

Back to your report I would advise to first use 3.44 or 3.5-RC1 as we made quite a few improvements in update sceanrios there, and @jainaashish will take a look

**Comment by jainaashish** [comment]
This has already been fixed in 3.5.0-rc1 release. Please upgrade from https://dist.nuget.org/win-x86-commandline/v3.5.0-rc1/NuGet.exe and let us know if you still see any issue.

**Comment by jainaashish** [comment]
Dup of #1013

**Comment by Vasilich** [comment]
tested with 3.5 RC1 and found no issues. thanks.
