### ISSUE TITLE
Restore failed for MVC5Application and LightSwitchHTMLApp after delete packages

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#345]
Repro steps:
1.	Create MVC5Application or LightSwitchHTMLApp
2.	Closed the solution and close VS, then delete package folder
3.	Restart VS and open the project created on step1
4.	Rebuild solution, got error. 

Expected results: build succeed
Actual results: build error

The error for MVC5Application:
Assembly strong name "System.Web.Mvc, Version=__MvcPagesVersion__, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\)

The error for LightSwitchHTMLApp:
NuGet Package restore failed for project Application6.HTMLClient: Unable to find version '2.5.3.0' of package 'Microsoft.LightSwitch.Client.JavaScript.Runtime'..

**Comment by deepakaravindr** [comment]
MVC5 application issue does not repro. Package restore is successful when v3 is enabled. Note that due to https://github.com/NuGet/Home/issues/236, you may seen that the build errors, since build starts before package restore ends. That issue is fixed now, so no repro

LightSwitch application issue repros. But, that is because the latest version of package 'Microsoft.LightSwitch.Client.JavaScript.Runtime' used by LightSwitch project template has not been uploaded to nuget.org (@Dan said this). Another point to note here is that package 'Microsoft.LightSwitch.Client.JavaScript.Runtime' is totally absent on api v3. Due to issue https://github.com/NuGet/Home/issues/152. However, on v2 all the other versions are present

Closing this issue since this is not a package restore failure and other issues are already tracked
