### ISSUE TITLE
Documentation:  search index out of date?

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#3513]
**Repro steps:**
1.  Go to https://docs.nuget.org.
2.  In the search box search for:  init.ps1

**Results:**
1.  The [first result](https://docs.nuget.org/docs.nuget.org/create/Creating-and-Publishing-a-Package) mentions init.ps1, but after navigating to the page, init.ps1 is nowhere to be found.
2.  The [second result](https://docs.nuget.org/create/enforced-package-conventions) results in HTTP 404.

**Comment by yishaigalatzer** [comment]
CC @qianjun22

**Comment by harikmenon** [comment]
This just looks like the google search index for the site is out of date. We will need to submit a sitemap with expiry dates and new links to update this. Not sure if we can do this since we have a free account (I don't believe so :)). In that case, it should resolve in some time once the index gets refreshed organizally on their end. @karann-msft

**Comment by kraigb** [comment]
@dtivel Search should be working on docs.microsoft.com/nuget where the docs now live. The search above is https://docs.microsoft.com/en-us/search/index?search=init.ps1&scope=NuGet and yields proper results. You should be able to close this.
