### ISSUE TITLE
[Mono issue] NuGet pack can't find build on Mono.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3525]
related test failure:
PackCommand_BuildProjectJsonWithRelativeBasePath()
PackCommand_BuildProjectJsonWithFullBasePath()
PackCommand_PackJsonCorrectLibPathInNupkgWithOutputName()
PackCommand_PackJsonCorrectLibPathInNupkg()

nuget.exe pack project.json got error "No build found in [targetPath]".

there are some hardcode path issues in tests and PackCommandRunner.AddOutputFiles(),
I fixed them but still got same issue, looks like PathResolver.PerformWildcardSearch() can't find those build dll.

**Comment by zhili1208** [comment]
nuget 3.4.4 doesn't not support packing project.json, this is not an regression from 3.4.4

**Comment by yishaigalatzer** [comment]
This is UWP style projects, suggest we disable the tests for mono at this point.

CC @mrward  @kzu

**Comment by radical** [comment]
@yishaigalatzer Could you please point me to such a project? Is such a project expected to build only on windows?

**Comment by yishaigalatzer** [comment]
The test covers this project - https://github.com/NuGet/NuGet.Client/blob/a6837535175490846af9ea8ff8b89d83efc9d783/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs#L3860

In general it would have been nice to have these build on mono as well, however they never really went main stream beyond UWP and UWP class libraries. Moving forward we are going to support `<PackageReference` instead of project.json, so I'm suggest that we don't spend effort and resources in this area and instead make `<PackageReference` work on mono.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs#L3553
this is one test example

**Comment by radical** [comment]
Okay, IIUC, this is something that needs to be done in `nuget` itself then. Let me know if you need anything from msbuild/mono side for this.

**Comment by yishaigalatzer** [comment]
We currently suggest no fix for mono. We will just disable the tests on mono. @kzu this is more of an FYI at this point. we are open to feedback from customers trying to use it and potentially invest in this at some later point in the 3.6 timeframe. For now we don't plan on tracking any further items.

**Comment by kzu** [comment]
I think with the current and upcoming support from NuGetizer, the need for standalone pack on project.json becomes less critical.
