### ISSUE TITLE
NuGet self update downloads pre-release version, instead of latest stable

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/Home#3562]
Hello,

I'm running NuGet Version: 3.4.4.1321 (command-line) downloaded from `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`

Running a self update, is causing it to download version `3.4.4-rtm-final` instead of version `3.4.4.1321` which should be the correct one (as I'm writing this).

```
PS C:\Users\caioproiete\Desktop> ./nuget update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 3.4.4-rtm-1321.
Updating NuGet.exe to 3.4.4-rtm-final.
Update successful.
```

I'd expect the self update to only download stable versions based on SemVer.

**Comment by yishaigalatzer** [comment]
1. Self update pulls in the latest version regardless if it is stable or not. That has always been the design.
2. The issue you are seeing is that 3.4.4 is misconfigued and the InformationalAssemblyVersion in nuget.exe is 3.4.4-rtm-1321 instead of 3.4.4. Practically speaking nothing is changing, but nuget unintentionally redownloads the same version again and again. This issue is already fixed in 3.5 RTM through #3395
