### ISSUE TITLE
Improved target documentation

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#358]
NuGet is getting a lot of new framework targets. I think the documentation needs to do a better job explaining what they are each for (and for people who don't know, explain a DNX app vs regular .NET app), explain what is loaded in different situations, and explain fallback precedence.

For example if you have a DNX project that references a package with no dnx452 assembly in it, when running on the desktop CLR will it fall back to loading dnxcore50 (because they are both DNX) or fall back to loading net45 (because they are both desktop).

Bonus points if you can also included PCLs in the fallback precedence documentation.

I realize there are a lot of scenarios once you start including Win8, Silverlight and WP - and they could probably wait for now - but this documentation would be helpful to package authors and remove a lot of guess work.

**Comment by yishaigalatzer** [comment]
Thanks for this ask. Yes we definitely need to do that.

@JamesNK  I'm sure you know, but for others please note that the DNX package types are not yet available in any public release other than the bleeding edge dev branch (and perhaps beta4 branch) of projectK,

The 2.8.5 release was mostly about enabling uploading these packages for people that target that release to nuget.org without breaking consumers for older frameworks.

Note that if you use the new target frameworks (particularly if you use more than one in your package) you want to specify min client version of 2.8.5. We will probably have another release or two, before we are done with the set of new TFMs and package formats for Windows 10 targets, with the goal of eventually not to have to rev clients again for adding TFMs.

**Comment by yishaigalatzer** [comment]
This should be done as part of updating to 2.8.6

**Comment by csharpfritz** [comment]
Adding information to 2.8.6 release notes

This documentation should also appear as part of #720

**Comment by yishaigalatzer** [comment]
@csharpfritz we need documentation on docs.nuget.org as well

**Comment by csharpfritz** [comment]
Holding for a proper reference to .NET Platform Standard

**Comment by csharpfritz** [comment]
In progress and based on contents of files:
- https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkConstants.cs
- https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs

**Comment by joelverhagen** [comment]
The precedence algorithm used when selecting from multiple compatible package TFMs is called `GetNearest`. This should be referred to while building the documentation.
https://github.com/NuGet/NuGet.Client/blob/31771f5cde5f62bbc1661e6ef586a09da1a96016/src/NuGet.Core/NuGet.Frameworks/FrameworkReducer.cs

**Comment by ericstj** [comment]
We need documentation on how you expect this to behave.  Even @davidfowl and myself cannot predict what NuGet is going to do in some cases: https://github.com/dotnet/corefx/issues/8828.  Without documentation I don't know if this is a bug or if its a nuance and my own mental model is incorrect.
/cc @seesharper

**Comment by tmenier** [comment]
Related question that I'm hoping someone here can help with. Do specific frameworks always take precedence over `netstandard`, even if they're a much older version than the consuming project? I have a library targeting `netstandard1.3` and `net40`. If I create a .NET 4.6.1 project and pull in this library, NuGet seems to pick the `net40` version. I hoped it would pick `netstandard3.1` since it's likely to contain newer bits, but that's not how it appears to work. Can anyone confirm this is by design?

**Comment by clairernovotny** [comment]
That is by design. Specific TFM's always win over `netstandard`. If you want newer functionality, you can use the SDK-style projects to multi-target to a newer `net` version. You could also put the `netstandard1.3` version in a `net461` directory too. If you do that, make sure to also include a `net461` dependency group that pulls in the right `netstandard.library` version too.

**Comment by tmenier** [comment]
Ok, thank you for the quick reply!

**Comment by jainaashish** [comment]
Moved to NuGet docs -https://github.com/NuGet/docs.microsoft.com-nuget/issues/625
