### ISSUE TITLE
<packageSourceCredentials> ignored when feed defined in higher config

### ISSUE THREAD

**Issue by henkmollema** [NuGet/Home#3580]
Related to #3568 but slightly different as it works the other way around. Tested with NuGet 3.5.0-beta2/.NET CLI 1.0.1.
## Steps
1. Put a `<packageSource>` with `<packageSourceCredentials>` in a NuGet.Config at **application** level, next to project.json.
2. Add a `<clear />` to the `<packageSources>`. Config looks like:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="vsts" value="{some VSTS feed}" />
  </packageSources>
  <packageSourceCredentials>
    <VSTS>
      <add key="Username" value="vsts" />
      <add key="ClearTextPassword" value="blah" />
    </VSTS>
  </packageSourceCredentials>
</configuration>
```
1. Add the same feed to a "higher" NuGet.Config, e.g. the one in `%APPDATA%/NuGet/NuGet.Config`.
2. Call `dotnet restore` on a project.json with a package in the VSTS feed.
## Expected

A clearer error message _or_ that NuGet ignores the feeds configured in  `%APPDATA%/NuGet/NuGet.Config` as `<clear />` was added to a "lower" config and adds an Authorization header to the request.
## Actual

NuGet does not add the Authorization header and the call fails with:

```
λ dotnet restore
log  : Restoring packages for C:\src\ConsoleApp8\src\ConsoleApp8\project.json...
error: Unable to load the service index for source {the feed}/nuget/v3/index.json.
error:   An error occurred while sending the request.
error:   The parameter is incorrect
```

I can see with Fiddler that NuGet sends a bunch of requests to the VSTS with, all without a Authorization header which obviously fails with an HTTP 401.

/cc @tkrick

**Comment by yishaigalatzer** [comment]
I don't understand why you expect an error message? This looks like a valid setup

**Comment by henkmollema** [comment]
@yishaigalatzer the setup is correct, yet the `dotnet restore` error message is rather vague about what is going wrong:

```
error: Unable to load the service index for source {the feed}/nuget/v3/index.json.
error:   An error occurred while sending the request.
error:   The parameter is incorrect
```

**Comment by henkmollema** [comment]
Woops

**Comment by BhaaLseN** [comment]
Just ran into this as well after a colleague added a TFS NuGet feed to a project that is still being built on a legacy build system (running under a local service account that isn't known to TFS, and won't ever be) - breaking the build.
I then found this issue while trying to figure out why it would ignore the credentials placed on that machine in the service accounts' `%APPDATA%\NuGet\NuGet.Config` file...

I don't suppose there's been any progress on it?
Although in my case, it's the other way around - the "lower" (ie. `$vcs\.nuget\NuGet.Config`) application level config adds the stream, but the "higher" one (`%APPDATA%\NuGet\NuGet.Config`) user level provides the credentials in a central location. And there is no `<clear/>` element there.

Edit: I might have a credential issue on my side; so not too sure if there is an actual issue with NuGet in my case. Sorry for bumping the issue if it turns out that it is a local problem (because I fat-fingered some option or whatever, and NuGet simply isn't using it)
