### ISSUE TITLE
DotNetCliToolReference PackageTargetFallback

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3617]
Currently, we do not plan to support PackageTargetFallback for DotNetCliToolReferences.
We are assuming that Microsoft can ship all of our tools, and their dependencies, properly supporting NetStandard by RC/RTM.

**Comment by conniey** [comment]
From the documentation on [extensibility](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/extensibility#building-tools), it appears that .NET expects developers to be able to write their own .NET CLI tools... I am having issues with DotNetCliToolReference not using PackageTargetFallback because some 3rd party dependencies do not compile for .NETStandard yet, but use dotnet or profile259.  Is there a workaround for this?
