### ISSUE TITLE
package.config targetframework not updating

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/Home#3625]
Updating target framework does not update packages.config.

VS 2015 Update 3 All Patches applied as of 10/8/2016

[Video Evidence here.](https://www.youtube.com/watch?v=Qs5WRk0PJe0)

**Comment by jainaashish** [comment]
This is by design. Target framework in packages.config doesn't represent that project's target framework rather it just tells you that package is installed against this framework which might or might not be compatible with your project's framework. And in case, its not compatible with project, then it will generate appropriate error message.
