### ISSUE TITLE
Manage NuGet Packages command requires AssemblyReferences capability

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#3655]
In our custom project (NuGetizer) when we remove the AssemblyReferences capability, the command gets disabled.

This should not be the case, since nuget packages can contribute things other than assembly references, clearly ;)

**Comment by jainaashish** [comment]
@kzu still relevant? what's the expectation from NuGet here?

**Comment by kzu** [comment]
I think this might be on @davkean's or @AArnott since it's CPS?

**Comment by AArnott** [comment]
This doesn't sound like a CPS issue. We prevailed upon NuGet to light up based on project capabilities for CPS based projects. I outlined 3 capabilities that would light up NuGet in the past (I can't find the issue, but [these are related](https://github.com/NuGet/Home/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20DeclaredSourceItems)), and at the time I suggested that a subset of these capabilities should allow installation of a subset of nuget packages (those that exercise just those capabilities).

NuGet probably still just requires them all in order to light up since it made their code simpler. They've never supported a project system that only supported a subset of nuget packages before (like those that contain msbuild .targets but not assemblies). So this would likely be a significant work item for NuGet to support.
