### ISSUE TITLE
[Test Failure] Build error occur after installing package ‘FSharp.Core’ to F# Console Application template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3686]
**Repro Steps:**
1.  New an F# Console Application template. 
2.  Build the project, no error.
3.  Open ‘Manage NuGet Packages…’ and click ‘Browse’ tab.
4.  Search and install package ‘FSharp.Core’.
5.  Build the project again.

**Expected Result:**
No error occur after installing package ‘FSharp.Core’ to F# Console Application template.

**Actual Result:**
Build error occur after installing package ‘FSharp.Core’ to F# Console Application template as below screenshot.
![fsharpcorebuilderror](https://cloud.githubusercontent.com/assets/20632625/19513600/0972c63a-9623-11e6-8e70-00d94670137a.png)

**Note:**
1.  It was found on D15PreRel 25818.03 (NuGet Client 3.6.0-RC-1977).
2.  It repro on D15PreRel 25818.03+NuGet Client 3.6.0-RC-1991.
3.  It doesn’t repro on Dev14 MU3.5 25431.01 (NuGet Client 3.4.4.1321).
4.  It doesn’t repro on Dev14 MU3.5 25431.01+ NuGet Client 3.5.0-RTM-1938.

**Comment by rrelyea** [comment]
@zhili1208 - can you please dig into this issue?

**Comment by zhili1208** [comment]
We didn't change anything about F#, the breaking change is from this API VSLangProj.References.Add(),

dev14 works well with nuget 3.6.0-RC-1977
dev15 is broken.

the issue is 
F# console project referenced FSharp.Core from Gac.
Then nuget installed same dll FSharp.Core from packages folder.

In dev14, NuGet knows this dll is already referenced from Gac and replace FSharp.Core item from csproj with new Hint path.
In dev15, NuGet doesn't know this dll is from Gac and added another Fsharp.Core reference section to csproj, this cause reference conflict

why the Gac check failed on dev15?

Nuget is using  VSLangProj.References.Add() to add reference for the dll from packages folder.
If this dll is already referenced from gac, the returned Reference.Path from VSLangProj.References.Add() will be null or "", but on dev15, the returned Reference.Path is the package folder path. 

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/VSMSBuildNuGetProjectSystem.cs#L390-L403

**Comment by v-luzh** [comment]
@zhili1208, This issue is fixed on D15Rel 26009.00 and D15PreRel 26013.05.
