### ISSUE TITLE
UWP projects - Explicit restore hangs on restore ui

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3728]
Created a UWP project with below project.json file:

{
  "dependencies": {
    "jQuery": "3.1.1",
    "jQuery.Validation": "1.15.1",
    "Newtonsoft.Json": "9.0.1"
  },
  "frameworks": {
    "net452": {}
  },
  "runtimes": {
    "win": {}
  }
}

And then did a restore from menu item, it just hangs on nuget restore dialog and never completes.

**Comment by emgarten** [comment]
From the debugger I see

Thread 1:
1. SolutionRestoreWorker.Restore is on the UI thread
2. JTF is started
3. await TaskScheduler.Default  moves everything to the background thread

Thread 2:
1. RestoreOperationLogger.GetMSBuildOutputVerbositySetting attempts to read DTE 
2. DTE call hangs since it is not in a JTF or on the UI thread

It looks like the verbosity setting is stored as a lazy, this should be done async or with an async lazy, and called within a JTF

**Comment by rrelyea** [comment]
Did @emgarten fix this?

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/959/commits/43ead5b9500b5870146677f9cbe8ca8a06e6dd76
