### ISSUE TITLE
Consider removing DTE queries in Nominate API

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3729]
Response to Nominate call should be fast as possible. Project restore data coming from CPS is supposed to contain all necessary metadata to update the cache. Project system cache needs slight refactoring in primary index not to use DTE properties.

**Comment by jainaashish** [comment]
Calling into DTE at the time of nomination, sometimes create issues to get the project details since project is still being loaded. And throw below error:
`Error occurred while restoring NuGet packages: The operation failed as details for project WebApplication3 could not be loaded.`

Steps to repro this:
1. create asp .net core web app with web api template
2. do restore.

If not repro at first time then try closing and reopening the solution and do restore.
