### ISSUE TITLE
[NuGet.PackageManagement] Reference group in <References> tag is not handled correctly

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#375]
If a package is created with the following nuspec, and then installed into a .net project, reference two.dll is also added as reference, which is not correct. Should be only add one.dll and three.dll.  

     <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
             <metadata>
            <id>RefPackage</id>
                <version>1.0.0</version>
                <title />
               <references>
                   <group targetFramework="net">
                       <reference file="one.dll" />
                       <reference file="three.dll" />
                   </group>    
                    <group targetFramework="silverlight40">
                        <reference file="fear.dll" />
                   </group>
            </references>
        </metadata>
        <files>
            <file src="lib\net40\one.dll" target="lib\net40\one.dll" />
            <file src="lib\net40\three.dll" target="lib\net40\three.dll" />
            <file src="lib\net40\two.dll" target="lib\net40\two.dll" />
        
            <file src="lib\sl40\fear.dll" target="lib\sl40\fear.dll" />
            <file src="lib\sl40\mafia.dll" target="lib\sl40\mafia.dll" />
       </files>
    </package>

**Comment by emgarten** [comment]
Packaging is stricter on this in V3. The group framework needs to match the lib folder. Otherwise a net35 group would filter the lib\net40 folder, which seems wrong. We could bring this behavior back but from my testing I have not seen very many packages that try to use this filtering shortcut.

If the reference group was changed from net to net4 this test would pass. We should decide if we want to keep the old behavior or clean it up.

**Comment by danliu** [comment]
Repro:
run-test InstallPackageRespectReferencesAccordingToDifferentFrameworks

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@2b075cc1538ea56d82df0ac15b563a56a32e6799
