### ISSUE TITLE
[Test Failure] Package ‘Microsoft.NETCore.Portable.Compatibility’ had not been installed into C# Class Library (Portable) project by default

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3829]
**Repro Steps:**
1.	Create a new **C# Class Library (Portable)** project.
2.	When selecting the portable targets, select .NET Framework 4.6 and ASP.NET Core 1.0.
3.	Right-click on the project and Manage NuGet Packages...
4.	Go to the Installed tab, verify the **Microsoft.NETCore.Portable.Compatibility** is eligible for updates.

**Expected Result:**
Package ‘Microsoft.NETCore.Portable.Compatibility’ is in the installed package list.

**Actual Result:**
Package ‘Microsoft.NETCore.Portable.Compatibility’ is not in the installed package list as below screenshot.
![netcore portable compatibility](https://cloud.githubusercontent.com/assets/20632625/19850618/5af843ac-9f94-11e6-921c-736f0ddb99da.png)
**Note:**
1.	It happen on D15PreRel 25830.00 + NuGet 4.0.0-RC-2040.
2.	It doesn’t repro on Dev14 MU3.5 25431.01 (NuGet Client 3.4.4.1321).
3.	It doesn’t repro on D15PreRel 25827.01 + NuGet 4.0.0-RC-2033.

**Comment by jainaashish** [comment]
I see the same behavior with Dev14 MU3.5 25431.01 (NuGet Client 3.4.4.1321). There is no package dependency added in project.json file which is why there is no package installed. More over it gives couple of compatibility warnings at restore as well:

Unknown Compatibility Profile: net46.app
Unknown Compatibility Profile: dnxcore50.app

**Comment by jainaashish** [comment]
And also, what all workloads you added to get pcl projects templates in dev15?

**Comment by v-luzh** [comment]
@jainaashish, we selected all options when we installing Dev15 VS D15PreRel 25830.00.

**Comment by jainaashish** [comment]
I can't repro this issue with D15PreRel 25830.00 + NuGet 4.0.0-2040 tried several times. Can you try again and if it repros again then tell me the exact steps?

![image](https://cloud.githubusercontent.com/assets/18219758/19878172/effae8b6-9fa2-11e6-8e0e-1b93cb1629a1.png)

**Comment by v-luzh** [comment]
@jainaashish, I can repro this issue on D15PreRel 25830.00 + NuGet 4.0.0-RC-2040 (Machine: EXPRBLNVM69521), D15Rel 25831.00 + NuGet 4.0.0-RC-2040 (Machine: EXPRBLNVM66375) and D15Rel 25831.00 w/ its included version NuGet 4.0.0-RC-2039 (Machine: EXPRBLNVM73448). 

**Repro Steps:**
1.  Install VS from UI with all the options selected.
2.  Create a new C# Class Library (Portable) project.
3.  Select **.NET Framework 4.6** and **ASP.NET Core 1.0**.
4.  Right-click on the project and Manage NuGet Packages...
5.  Go to the **Installed** tab.

**More Info:**
Andy and Nancy get the below dialog when creating above C# PCL template, but I have never run into the error even if I login the same machine with same account (that’s weird).
![pclcreating](https://cloud.githubusercontent.com/assets/20632625/19883086/17d0d2ba-a04d-11e6-90a9-951c95b6702a.png)

**Comment by jainaashish** [comment]
@v-luzh can you also try the same issue with dev14 3.4.4 or 3.5 builds on these machines where you see the issue?

**Comment by jainaashish** [comment]
PCL template issue:

There is an issue with creating a new PCL library project since it tries to install Microsoft.NetCore (5.0.0) and Microsoft.NETCore.Portable.Compatibility (1.0.0) but couldn’t find the same versions of these packages in SDKs packages cache at “C:\Program Files (x86)\Microsoft SDKs\NuGetPackages”

Expected packages in packages cache:
Microsoft.NetCore (5.0.0)
Microsoft.NETCore.Portable.Compatibility (1.0.0)

Actual packages in packages cache:
Microsoft.NetCore (5.0.2)
Microsoft.NETCore.Portable.Compatibility (1.0.2)

**Comment by jainaashish** [comment]
External tracking issue# 286754

**Comment by v-luzh** [comment]
@jainaashish, please see below investigation.

D15Rel 25831.00 + NuGet 3.5.0-RTM-1938 on **EXPRBLNVM66375** ---Repro
D15Rel 25831.00 + Dev14 25431.01 (NuGet 3.4.4.1321) on **EXPRBLNVM66375** ---Repro
D15Rel 25901.00 + NuGet 4.0.0-RC-2044 on **EXPRBLNVM70138** ---Repro
Dev14 25431.01 only (NuGet 3.4.4.1321) on another machine (**EXPRBLNVM73825**) ---Doesn’t repro
Dev14 25431.01+ D15Rel 25901.00 on **EXPRBLNVM73825** --- Doesn’t repro

Note: Add you in admin group on above machines.

**Comment by jainaashish** [comment]
Validated and closing since external issue is also closed.
