### ISSUE TITLE
NuGet PM 3.5.0 incorrectly using lowercase path in *.nuget.targets

### ISSUE THREAD

**Issue by martinsuchan** [NuGet/Home#3840]
NuGet PM is incorrectly changing the path to some packages to lowercase in the *.nuget.targets files, for instance it changed path:

    <Import Project="$(NuGetPackageRoot)\PlatformSpecific.Analyzer\2.0.3\build\uap\PlatformSpecific.Analyzer.targets" Condition="Exists('$(NuGetPackageRoot)\PlatformSpecific.Analyzer\2.0.3\build\uap\PlatformSpecific.Analyzer.targets')" />

to this.

    <Import Project="$(NuGetPackageRoot)platformspecific.analyzer\2.0.3\build\uap\PlatformSpecific.Analyzer.targets" Condition="Exists('$(NuGetPackageRoot)platformspecific.analyzer\2.0.3\build\uap\PlatformSpecific.Analyzer.targets')" />

Note the lowercase 'p' in platformspecific. I checked the actual path and the folder has big 'P' in name, so no idea, where this lowercase p comes from.

NuGet PM 3.5.0.1996, VS2015 Update 3, Windows 10 AU. This bug occurs in Windows 10 UWP project.

This bug first appeared once I updated to the Pacakge Manager to 3.5.0 RTM.

Expected behavior: The path should not be changed from "PlatformSpecific" to "platformSpecific". When I used all older versions of NuGet PM, it used the proper "PlatformSpecific" path in *.nuget.targets.

Repro is in the attachment. Open it in VS015 U3 with NuGet PM 3.5.0 and rebuild the project. Result-> The import path has changed.

[NugetBug.zip](https://github.com/NuGet/Home/files/563608/NugetBug.zip)

**Comment by emgarten** [comment]
@martinsuchan do you have a scenario where the case of the package id is important for targets?

Package ids and versions are case insensitive in NuGet and are now written out lowercase to the global packages folder to avoid conflicts on case sensitive file systems.

**Comment by rrelyea** [comment]
@martinsuchan - ??

**Comment by martinsuchan** [comment]
@rrelyea If this is the expected behavior now, then I guess the issue can be closed as "by design".

**Comment by sharwell** [comment]
@emgarten This change broke packages which assumed the packages cache would be written with the *actual* case specified for package IDs. One clear example would be the Microsoft.Net.RoslynDiagnostics package.

**Comment by emgarten** [comment]
@sharwell `Microsoft.Net.RoslynDiagnostics` appears to be broken on many levels and should be fixed. It assumes the case, package folder format (this would be different between packages.config and PackageReference), it also assumes that dependencies are installed to the same folder which may not be true with fallback folders where not all packages are installed to the global folder. For this reason packages should not reference other packages in this way.

Targets/props are imported in dependency order, so this package could be fixed by having dependency packages add their own analyzers, or by exporting properties that the parent package then consumes to find them.

**Comment by sharwell** [comment]
@emgarten You only asked for an example. I didn't (and wouldn't) claim that the example was well-written, yet 1) it exists, 2) projects depended on it, and 3) a change in NuGet broke these projects.

NuGet should not be performing normalization of package IDs to account for case-sensitive file systems. As a user, I expect the client to be fully case-preserving, thus any bug due to a deviation in case can be clearly traced in origin to a package author or consumer failing to use the correct case somewhere.

I'll file a separate bug for this.
