### ISSUE TITLE
Perf regression - DPL work - AutoRestore causes solution load. Instead it should wait to start for solution load.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3844]
Internal bug # 286159

**Comment by jainaashish** [comment]
So the plan is auto-restore will yield to allow solution to be loaded first and then start the auto restore. And in order to get solution load status, we will make 2 calls:
1. Check if VSPROPID_IsSolutionFullyLoaded is true then start auto restore
2. else wait until IVsSolutionLoadEvents (OnAfterBackgroundSolutionLoadComplete) is called and then start auto restore.

**Comment by rrelyea** [comment]
Shifting to RC2 per shiproom discussion. (keeping in RC to further evaluate.)
