### ISSUE TITLE
Project relative paths should be relative to the assets file

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3846]
### Steps

1. Create a new .NETCore console app
1. Create a second .NETCore console app
1. Add a reference from one to the other
1. Add a class to the child project
1. Reference the class from the parent project

### Expected
Class is available

### Actual
Class is not available

The path is relative from the project file path, not from the assets file path which is now under the obj folder.

Actual:
```
    "ConsoleApp2/1.0.0": {
      "type": "project",
      "path": "../ConsoleApp2/ConsoleApp2.csproj",
      "msbuildProject": "../ConsoleApp2/ConsoleApp2.csproj"
    }
```

Expected:
```
    "ConsoleApp2/1.0.0": {
      "type": "project",
      "path": "../../ConsoleApp2/ConsoleApp2.csproj",
      "msbuildProject": "../../ConsoleApp2/ConsoleApp2.csproj"
    }
```

**Comment by rrelyea** [comment]
What scenarios are broken? Does CLI have a ripple effect?

**Comment by emgarten** [comment]
CLI appears to work around the issue here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectJsonMigration/Microsoft.DotNet.Internal.ProjectModel/Resolution/MSBuildDependencyProvider.cs#L68-L71

**Comment by TheRealPiotrP** [comment]
I think it's important we don't allow a new `root` path concept to leak into the build system, ideally including the CLI. All relative paths in msbuild are assumed to be relative to the directory containing the project file. Since relative paths are ~very~ easy to get wrong, I'd hate to introduce another root that folks have to reason about. 

My preference would be to keep these relative paths relative to the project file. If that is not possible, I'd like to see an API in NuGet that disambiguates the relative paths by providing either absolute paths or project-file-relative paths.

The internal structure of this file is a nuget-only concern, in my opinion, but I'd like to keep the implementation details from leaking.

**Comment by emgarten** [comment]
NuGet will continue writing paths in the assets file relative to the project file as we decided in our offline discussion.

If requirements change in the future this can always be fixed by writing the absolute path instead.
