### ISSUE TITLE
NuGet targets and props files should add themselves to MSBuildAllProjects property

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#3851]
Ideally, all imported project files should add themselves to the `MSBuildAllProjects` property, in order to better support incremental builds.  The following currently aren't doing this:

- Microsoft.NuGet.ImportAfter.targets
- NuGet.targets
- NuGet.Build.Tasks.Pack.targets (from the NuGet.Build.Tasks.Pack package)
- The .csproj.nuget.g.props and .csproj.nuget.g..targets files that the restore operation puts in the `obj` folder.

The files can add themselves with the following XML:

```xml
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
```

See also Microsoft/MSBuild#1298

**Comment by emgarten** [comment]
@dsplaisted each of these files should contain this property to append themselves?

**Comment by rainersigwald** [comment]
@emgarten Yes. This is to work around a limitation of MSBuild: incremental builds consider only the inputs and outputs defined _in the current build_. That means that if something causes an item to **no longer** be defined, we might miss the need for a rebuild--_current_ inputs are newer than current outputs, but really there's one less input which means we need to rebuild. The core tasks can add `$(MSBuildAllProjects)` as an additional input, so that if any imported MSBuild file is updated, there will be a (pessimistic) rebuild.

**Comment by bbowman** [comment]
+1

I'm seeing issues where rebuilds always are occuring after a restore even if the restore doesn't pull down a new package (rewrites the generated .props / .targets to the same content as before). This issue in general needs investigated further to make sure that incremental build scenarios work across the board.
