### ISSUE TITLE
Remove XProj pack from XPlat

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3904]
``dotnet nuget pack`` contains a legacy implementation of pack for xproj. This should be removed to avoid confusion with ``dotnet pack`` which is actually ``msbuild /t:Pack``

https://github.com/NuGet/NuGet.Client/blob/6f3ae2d59140f5ea97eb7573535de1c286d6d336/src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs#L76

**Comment by natemcmaster** [comment]
Instead of removing completely, could dotnet-nuget-pack pivot to only supporting nuspec files?

dotnet-pack is meant for packing MSBuild projects. If users only have a nuspec file, it seems unnecessary to require adding an MSBuild file in order to call [`PackNuspecTask`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/PackNuspecTask.cs). And furthermore, it is much harder to discover available parameters for an MSBuild task than to run `dotnet nuget pack --help`.

**Comment by emgarten** [comment]
> Instead of removing completely, could dotnet-nuget-pack pivot to only supporting nuspec files?

Good point on packing nuspecs, we should support that xplat if possible. I would expect dotnet pack to be the entry point for this. What you are seeing with dotnet nuget pack is the old entry point from preview2. It isn't going to be supported going forward.

> it is much harder to discover available parameters for an MSBuild task than to run dotnet nuget pack --help

This sounds like an issue with the top level dotnet pack command, it should have the same optional parameters that can be converted into msbuild properties.

//cc @rohit21agrawal

**Comment by natemcmaster** [comment]
Yes, definitely in favor of dropping the 'pack project.json' piece of this. It's the packing a nuspec w/o MSBuild scenario I'm most interested in.

I'm not sure dotnet-pack is the right place for this as its [current implementation](https://github.com/dotnet/cli/blob/806d5a2589bcb6993a3c44650df0d30a613ce0e1/src/dotnet/commands/dotnet-pack/PackCommand.cs) is designed to always invoke MSBuild...hence the requirement to add an MSBuild project in order to pack a nuspec.  cc @piotrpMSFT @blackdwarf

**Comment by blackdwarf** [comment]
@natemcmaster @emgarten why is there a difference between these two commands in terms of inputs? Sorry if this is slightly off-topic, but since we are talking about potential changes to `dotnet nuget pack` it seems like a good place/situation to ask.

When we were doing the UX labs on the MVP summit, for example, most of the people we talked to were confused with the fact that `dotnet pack` and `dotnet nuget pack` work on different inputs. 

I would think that both of them would allow using the nuspec and the csproj file as inputs to produce nupkgs. 

Thoughts?

**Comment by emgarten** [comment]
> why is there a difference between these two commands in terms of inputs? 

There shouldn't be. The plan is to remove ``dotnet nuget pack``, it is confusing to have both. The old preview2 entry point within nuget just hasn't been deleted yet.

**Comment by blackdwarf** [comment]
@emgarten oh. OK then. 😄 That makes sense.

**Comment by gulbanana** [comment]
I'm currently using dotnet nuget pack as a way to get access to the non-Core packing capabilities of nuget.exe but using the *version* of nuget which comes with an sdk so that it can process p2p references *to* Core projects. Is there a better way to do this? For the foreseeable future we're going to need support for situations like this:

- Solution contains two projects
- Project 1 - .NET Standard csproj producing a nuget package. Uses the new project system and can be built with dotnet pack.
- Project 2 - .NET Desktop csproj producing a nuget package. Depends on project 1, and the package soguld depend on project 1's package. Can not (ever?) use the new project system as it contains e.g. WPF XAML and must be built with nuget pack.

**Comment by rohit21agrawal** [comment]
@gulbanana for your Project 2, you should just use nuget.exe, which you can download from nuget.org/downloads .

**Comment by gulbanana** [comment]
OK, I'm trying that. Unfortunately it doesn't work right now - see the comments here https://github.com/NuGet/Home/issues/4054

**Comment by rohit21agrawal** [comment]
@gulbanana - use nuget.exe for non netcore projects and dotnet.exe for netcore projects

**Comment by gulbanana** [comment]
That is what I am doing, but nuget.exe does not work to pack a noncore project which *depends on* a core/netstandard project.

**Comment by emgarten** [comment]
@gulbanana would you open a new issue to track packing projects with non-core/netstandard mixed dependencies? This will need to work from the same command.

**Comment by rohit21agrawal** [comment]
There is already one open : https://github.com/NuGet/Home/issues/4054
