### ISSUE TITLE
nuget 3.5 update regression for references in vcxproj - we fixed bug, behavior changed for better, package adapted

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#3909]
# Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 3.5.0.1938

OS version (i.e. win10 v1607 (14393.321)): win10 v1607 14393.351

Worked before? If so, with which NuGet version: 3.4.3.855

# Detailed repro steps so we can see the same problem

1. Add a reference (using VS2015) to FubarCoder.RestSharp.Portable.Core (3.2.0)

2. Update the reference to 3.3.0 using `nuget.exe update -safe project.vcxproj`

# Expected Behavior

Update of the reference to 3.3.0 in both the `packages.config` and the `vcxproj` file.

# Actual behavior

Update of the reference to 3.3.0 in the `packages.config`, but not in the `vcxproj` file.

**Comment by yishaigalatzer** [comment]
Thanks for the report, we are going to take a look and try to reproduce. Will loop back once we make a decision.

**Comment by rrelyea** [comment]
@jainaashish Can u please try to repro and understand this issue?

**Comment by jainaashish** [comment]
I can repro this issue locally, investigating root cause.

**Comment by jainaashish** [comment]
So problem here is that package `FubarCoder.RestSharp.Portable.Core` doesn't have any assembly to reference for native target framework (check packages folder `packages\FubarCoder.RestSharp.Portable.Core.3.1.2\lib\native`) So NuGet doesn't add/ remove reference for this package. It's rather being done by package install.ps1 and uninstall.ps1 scripts under `packages\FubarCoder.RestSharp.Portable.Core.3.1.2\tools\native`  

And since NuGet.exe doesn't execute these scripts (since there is no dte project for NuGet.exe) which is why it doesn't update it's reference. But when you install/ update this package through NuGet manager ui, it executes these scripts and update references accordingly.

Now, why it worked with NuGet.exe 3.4.3.855, because there was a bug in that NuGet version is that it was getting wrong target framework for native projects which is why it was able to update reference. With that version, NuGet saw this project referencing `.NETFramework,Version=v4.5.2` which is why it was able to update its reference. But now this bug has been fixed and NuGet correctly detects its target framework as Native.

So, this is the right behavior now. Since there is no assembly reference for Native target framework, NuGet.exe will not update any reference. You can either ask the package owner to add assembly reference for Native framework or update it through UI.

**Comment by rrelyea** [comment]
@fubar-coder - sounds like we fixed a bug that did change the behavior. Sounds like this is the correct behavior. Can you please adapt?

**Comment by fubar-coder** [comment]
@rrelyea Yes, I'll change the libraries to the ".targets" file approach
