### ISSUE TITLE
Update NuGet options to configure the auto-restore behavior.

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3963]
According to the [NRM spec](https://github.com/NuGet/Home/wiki/NuGet-Restore-Manager) restore behavior may be configured to run in 3 distinct modes:

- Automatic restore
- On-Build only
- Manual only

Update the NuGet options page with the new options.

**Comment by bbowman** [comment]
@alpaix I'm a little concerned about the table in "Future VS '15' Restore Behavior". For automatic restore, you mention that on build restore is assumed not needed which is insufficient for wildcard cases as newer packages may have become available since the last edit / open. This is an important scenario for my team's inner loop of trying out package changes.

**Comment by nkolev92** [comment]
Low priority for now.
