### ISSUE TITLE
Report an error if Nuget.Build.Packaging is added not to lib project

### ISSUE THREAD

**Issue by rzaitov** [NuGet/Home#3983]
**NuGetizer**
We discussed this issue on Slack. I report it here for tracking purpose.

When I first played with Nugetizer with XS on my mac I was trying to add Nuget.Build.Packaging into nuget project itself (this is completely wrong). XS/VS/MSBuild should stop the build process (report an error during a build instead of warning)

XS info: https://gist.github.com/rzaitov/59f82e315ab52f572fde10fd3e76c2be
This comes from here https://bugzilla.xamarin.com/show_bug.cgi?id=47372

**Comment by kzu** [comment]
XS issues should not be logged here. This repo is for the open source parts of NuGetizer, which are the targets and the VS integration only.

**Comment by mrward** [comment]
Isn't this a build target problem and not a Xamarin Studio problem though? Whether the build shows a warning or an error is due to the build target.

Currently the build targets report a warning if the NuGet packaging project references another project that does not have the NuGet.Build.Packaging NuGet package installed. This is what the original problem was. I thought the idea was to change it from a warning to an error.

**Comment by rzaitov** [comment]
> I thought the idea was to change it from a warning to an error.

Yea. Exactly!

**Comment by kzu** [comment]
He, good point :). I think I accidentally closed the wrong thing
