### ISSUE TITLE
Restrict adding assemblies in the Windows application while install the custom Xamarin NuGet package

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3997]
@GanesanRengasamy wrote: 
I have created the custom Xamarin forms NuGet package with the below format.

![old lib folder of the package](https://cloud.githubusercontent.com/assets/16695209/20512579/3be2ff5c-b0a6-11e6-8eaf-251043b9d1f0.png)

The packages are installed and assemblies are added successfully for this package.

Then I have changed the lib folder format since I don't need the Windows and Windows phone, winRT assemblies in the project. So I have changed the lib folder format like as below,

![new lib folder of the package](https://cloud.githubusercontent.com/assets/16695209/20512534/e47798e0-b0a5-11e6-867d-75b20076b16d.png)

I got the below error while install the package in the project after change lib folder format.

**Could not install package 'Custompackage.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author**

The **Xamarin.Forms.2.3** package has been installed default while create the Xamarin project.

Why we get this error after change the format of the lib folder in the package?
Any standard format we need to maintain for this Xamarin forms packages?

Please help me on this.

Thanks,
Ganesan R.

**Comment by yishaigalatzer** [comment]
CC @emgarten

**Comment by emgarten** [comment]
> Then I have changed the lib folder format since I don't need the Windows and Windows phone, winRT assemblies in the project.

The folder needs to represent the target framework the assembly was built under so that NuGet can correctly determine compatibility. There should only be one assembly here that is portable and works across all of these frameworks, not individual assemblies for each one.

In your example it looks like the framework was originally PCL Profile259 (net45+win8+wpa81+wp8). When installing into PCL Profile111 (net45+win8+win81) this works. After removing win8 and win81 from the folder name NuGet is unable to find the required win8 and win81 support needed to install into your PCL Profile111 project.

PCLs represent subsets of .NET Framework APIs. To include more APIs you will need to change the target framework of your Xamarin project. Having additional frameworks in the folder name does not this since the assembly is already built.

**Comment by GanesanRengasamy** [comment]
HI @emgarten 

Thanks for your response,

I am new for Xamarin. Please tell me the steps for how to change the .NET framework APIs regarding without Windows platforms?

Thanks,
Ganesan R.

**Comment by jainaashish** [comment]
Closing this since Justin already responded for the original error message, If this are more open questions, then file another bug or contact at nuget client team dl.
