### ISSUE TITLE
VS Client should have a like to NuGet Gallery for a package entry

### ISSUE THREAD

**Issue by jonwchu** [NuGet/Home#3999]
[Moving from NuGetGallery Issue 3333](https://github.com/NuGet/NuGetGallery/issues/3333)

Since there are deep links for package operations in the client to the NuGet Gallery (e.g. Report Abuse), there should also be a link to the package page itself on the website. That way a user can easily switch context between the VS Client and the website.

**Comment by robertmuehsig** [comment]
PR welcome for this issue? I would like to get a small insight into the NuGet VS Client :)

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by stijnherreman** [comment]
@jainaashish What is there to investigate here? It's really simple. Currently the quickest way to navigate from Visual Studio to a package on NuGet, is to click the *Report Abuse* link (e.g. https://www.nuget.org/packages/Microsoft.Net.Compilers/2.6.1/ReportAbuse) and then remove a part of the URL in your browser (e.g. 2.6.1/ReportAbuse).
What is asked here is to add an additional link, *Package URL* for example, to navigate to the package on the NuGet site.

**Comment by jainaashish** [comment]
@stijnherreman Currently NuGet client does not add any metadata to any package on it's own, it just shows whatever it receives from server and a server can be anything here be it NuGet.org or some private myget feed or vsts feed or even file share. And also, there isn't any special handling of NuGet.org feed in client.
So that's why we need further investigation here to decide if we need to change protocol to support new metadata or should client start manipulating this information for each package for each feed and start populating.

**Comment by jainaashish** [comment]
Update: this is now being tracked and worked upon as part of https://github.com/NuGet/Home/issues/5299
