### ISSUE TITLE
VsPackageInstaller.InstallPackage throws InvalidOperationException with NuGet 3 beta

### ISSUE THREAD

**Issue by kimjohnson** [NuGet/Home#403]
I have a project template wizard (an IWizard) which uses a composed instance of IVsPackageInstaller to install NuGet packages to a project. In VS2012 and VS2013 I used the InstallPackage signature which accepts a repository:
     InstallPackage(IPackageRepository repository, Project project, string packageId, string version, bool ignoreDependencies, bool skipAssemblyReferences);

In VS2015 it looks like this signature is no longer supported, so I've tried the following instead:
     InstallPackage(string source, Project project, string packageId, string version, bool ignoreDependencies);

Unfortunately this throws an InvalidOperationException with message "The service 'Microsoft.Internal.VisualStudio.Shell.Interop.SVsUIThreadInvokerPrivate' 
 must be installed for this feature to work. Ensure that this service is available. HRESULT = 0x8000FFFF" 

 My environment - VS Ultimate 2015 CTP6, NuGet Package Manager for VS 2015 v3.0.60225.100.

**Comment by yishaigalatzer** [comment]
Thanks for reporting this. In short you are right and we fixed it for RC.

Here are some details:
The API using `IPackageRepository` was mistakinly exposed. Since that type is not exposed publicly, and was never an officially supported API. I'm sorry you are facing a problem because of this. The rule at the moment is you should just rely on what is in the embedded types, other types even if public are implementation details and not a public API.

As for the other overload, we did have this bug in CTP6 and it got fixed towards RC.
