### ISSUE TITLE
Slow to get dependency information on slow connection

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#4089]
I'm working on a slow (DSL) connection. Every time I select a package as I proceed to consolidate packages for a large solution, I see this kind of message in the VS Output Window:

Attempting to gather dependency information for package 'Dapper.1.50.2' with respect to project...

And it stays that way for some 15 or more minutes!! (as it checks nuget.org).

Questions for ya'll

* Why isn't this dependency information computed and saved at the time the package is published or installed?
* Why does it take 15 or more minutes to fail to get the dependency information if I have inadvertently selected the wrong nuget source?
* Why is the nuget source URL (or at least the server part) not also saved when a package is installed?

With a fast connection one might never notice these, but in fact they strike me as rather large design oversights...

**Comment by rrelyea** [comment]
Thanks for the report. We'll put this in our queue. Won't fit in 4.0, but we want to continue to chip away at scenarios like this.
@jainaashish - feel free to help answer some of these questions if you can do quickly.

**Comment by jainaashish** [comment]
`Why isn't this dependency information computed and saved at the time the package is published or installed?`
because package dependencies can change with newer versions so we need to compute dependencies with every new version or update.

`Why does it take 15 or more minutes to fail to get the dependency information if I have inadvertently selected the wrong nuget source?`
It basically try and get dependency information for all installed packages from all selected sources at one shot. So you can look for how many packages are installed and selected sources? Still few recommendations to improve this time:
- If possible, select specific packages you want to update through NuGet manager UI.
- If you know your source, then select that specific one, instead of selected ALL.

Even after these recommendations, it still takes long time even for slow connection, then share us your sample solution and we'll take a look.

`Why is the nuget source URL (or at least the server part) not also saved when a package is installed?`
Because a package is not always tied up with single source, and it's update can come from any source. So we always need to check for update for your selected packages from selected sources.

**Comment by zhili1208** [comment]
this experience is better in VS 2017 with package reference, we are still improving perf. close it
