### ISSUE TITLE
VSFeedback: Restore fails for a VS 2015 project generated with CMake 3.7.1

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4114]
VSfeedback item: https://developercommunity.visualstudio.com/content/problem/7332/failed-to-resolve-all-project-references.html

Internal bug: 299366

When opening a VS2015 community solution (platform toolset = v140) , generated with CMake 3.7.1, any build operation fails with "Failed to resolve all project references. ". This does NOT happen when generating the v141 project files. Please note also the "invalid cast" errors at the end of the output, which may be related. In my PC I have installed VS2017 RC (updated), VS2015 Community and VS2010 professional; All the versions use the Italian language. This didn't happen using the previous RC.

[see vsfeedback link for rest of report details...]

**Comment by qbprog** [comment]
The issue is more complex than it appeared. It may be an error of cmake instead.
See this example: if you extract to C:/Hello , you'll find the projects in C:/Hello/BuildFiles/ , just open these with VS2017 RC2 and don't upgrade.

In this project the project reference error happens also with the english language pack. Note also that I' don't have Visual C++ Cmake tools installed (only the official cmake installer).

These are the steps to reproduce:
1- Generate the project files with CMake 3.7.1 ,using Cmake or Cmake-gui using the VS 2015 generator. Open It with VS2017.
2- This time the project builds fine.
3- Try to change anything inside the CMakeLists.txt , just a spacing and rebuild *from inside the IDE*. CMake tryes to rebuild the projects and fails somehow.
From now on you see the error. Also in the source dir you see that some wrong dirs get created.

Had to upload with filebin : http://filebin.ca/35RHx2Y7pFg9

**Comment by emgarten** [comment]
NuGet/NuGet.Client@c29b08a049252972361e0e5f4dc159120bdd2d3d
