### ISSUE TITLE
Support for importing .targets file into .csproj in Nuget v3

### ISSUE THREAD

**Issue by rnagpal** [NuGet/Home#4130]
Hello All,

I'm migrating my package from Nuget v2(*.nuproj/*.nuspec) to Nuget v3(project.json) and one of thing that's not working in v3 is the automatic import of the .targets file I used to have it under the build dir. This targets files used to add the unmanaged dlls as Content files with CopyToOutputDirectory set to true. I need these native dlls alongside my managed dll.

This doesn't seem to be happening in Nuget v3. Is this supported?

Are there any other workarounds to have this targets file imported into the .csproj when somebody downloads this nuget package on net45 project?

I'm using dotnet pack command to create the package. Details below. 

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

dotnet.exe --version (if appropirate): 1.0.0-preview2-003133

VS version (if appropriate): VS 2015 Update 3

OS version (i.e. win10 v1607 (14393.321)): Windows 10

Worked before? If so, with which NuGet version: Yes. Nuget v2

**Comment by emgarten** [comment]
@rnagpal dotnet preview2 does not support MSBuild. Try out the latest preivew4 for cross platform msbuild support.

**Comment by rrelyea** [comment]
As this sounds like this is already addressed once you move to current builds of VS2017/CLI tooling for .net core, we'll close. It was by design for the xproj/project.json world of preview2...and the design has changed with the msbuild based tooling now.
Please let us know if you see a problem once you've moved to preview 4 or later.
