### ISSUE TITLE
Order of import has changed in NuGet 2 / 3 / 4

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#4229]
I'm not sure how actionable this is, but I noticed it today as a breaking change and wanted to make you aware.

In NuGet2 package targets are imported at the end of the project file by NuGet writing them to the targets file based on the order of package install (?)

In NuGet3 package targets are imported near the end of Microsoft.Common.targets via ImportAfter hook.  Order of import of after hook is file-system-dependent (MSBuild evaluating the *) then order of packages in NuGet's generated project-specific targets files appears to be alphabetical (?)

In NuGet4 package targets are imported via a new hook, MSBuildProjectExtensionsPath, which occurs before ImportAfter.  This hook has the same order as ImportAfter due to use of MSBuild's wildcard, and likely the same order in NuGet's generated project-specific targets file.

Order of targets is a big deal and can make some things impossible to do if you don't get imported late enough.  Consider a change for NuGet v4 to move later in the evaluation rather than earlier.  Of course this would require a change in MSBuild, but it seems you already have a change in MSBuild to move you earlier, perhaps just put that later instead 😉 

/cc @jeffkl @emgarten

**Comment by jeffkl** [comment]
We debated for a while about where the import should occur.  We settled on [this order](https://github.com/Microsoft/msbuild/pull/994#issuecomment-245946950) because it ensures that your local environment gets to set things first and last.

Technically the NuGet creates things imported via MSBuildProjectExtensionsPath (via a wildcard) and it can control the order of imports within its generated file.  I'm not sure what the order is but I did get the impression that it's alphabetic.

We are pushing teams to use NuGet packages and steering them away from locally installed SDKs which means the ImportBefore/ImportAfter folder location hook would ideally be deprecated.  We will rely on NuGet to get the order correct for packages.  They might need to be imported based on some sort of dependency chain or the order specified in the package config.

**Comment by emgarten** [comment]
On NuGet's ordering of the imports:
1. NuGet 2.8.x would write them in install order, but when updating packages NuGet this could get out of sync. The client wasn't actually reading what was already in the file to decide where the new targets should go.
1. During 3.x XProj didn't support targets/props so this area was not focused on.
1. 4.x ensures everything is in dependency order and has the right behavior now.

To make this easier for package authors in the future NuGet now writes out the tooling version and the project type (packages.config vs project.json vs PackageReference) to the generated .props file so that if needed a package can determine if it needs to work around past problems or error out with a helpful message.

**Comment by ericstj** [comment]
What are your thoughts about making them happen after SDK imports?  The nice characteristic about 2.x was that you could override anything you wanted.

**Comment by jeffkl** [comment]
The SDK is what imports the NuGet props/targets.  

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props#L19
https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Microsoft.Common.props#L59

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets#L40
https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Microsoft.Common.targets#L127

The imports happen fairly early and late but just after and before what is next to the proejcts.  We believe NuGet packages should still be able to extend the build, are there cases where this isn't possible?

**Comment by natemcmaster** [comment]
It's possible to _extend_ the build using current import order, but it's not possible to _override_ some parts of the build. 

For example, if I wanted create a NuGet package that ships a target called "Pack", this cannot override the pack that is in Microsoft.NET.Sdk because Microsoft.NET.Sdk/Sdk/Sdk.targets imports the pack targets at the very end, after MSBuildProjectExtensionsPath targets are imported.

**Comment by jeffkl** [comment]
The only way an SDK could allow someone else to override its targets would be to expose a property like `CustomAfterSdkTargets` that it would import at the end of it.  Technically it could do an import of a place on disk as well but we're trying to move away from that.  

Another established pattern is to use a `DependsOn` property or `BeforeTargets`/`AfterTargets` to extend a target.

+@rainersigwald

**Comment by zhili1208** [comment]
No actionable here, close it

**Comment by ericstj** [comment]
Not even going to document the breaking change?
