### ISSUE TITLE
package management format selector dialog - solution level setting for the default format

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4249]

**Comment by ghost** [comment]
Due to lack of recent activity, this issue has been marked as a candidate for icebox cleanup. It will be closed if no further activity occurs within 14 more days. Any new comment (by anyone, not necessarily the author) will add a `Triage:NeedsTriageDiscussion` label and lead to a triaging process.
This process is part of the experimental [Stale icebox issues cleanup](https://github.com/NuGet/Home/issues/12113) we are currently trialing. Please share any feedback you might have in the linked issue.
