### ISSUE TITLE
Client should report broken links to the server

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#425]
We have seen several cases where the client manages to connect to the server on the base URL, but following links turn up 404s.

For example FindPackage returns a URL for a package download that does not work.

We would like the client to report to the server about the broken link (including the whole stack of calls made), and that should trigger an alert.

We should aggregate the number of broken users, and number of retries etc.

**Comment by yishaigalatzer** [comment]
@joyhui please drive this.

**Comment by emgarten** [comment]
@skofman1 @joelverhagen @xavierdecoster is this something that would be worthwhile? Or do we already have telemetry on 404s?

**Comment by xavierdecoster** [comment]
A 404 is typically a message to the client that a resource does not exist. The server can gather telemetry on 404's too. Having the client report 404's to the server basically means the server gets that information twice. Unnecessary overhead on both client, server and network.

There's a nice side effect, too. Imagine a feed with two packages, and NuGet.org are used. If our project has 100 packages installed, that feed with two packages will get 200 requests during restore (404's + 404 reporting), which is essentially... a bad idea.

For nuget.org, we have AI server telemetry we can leverage.
Instead of generating more http calls, I'd prefer the client to become smarter about which package source to hit first (heuristics). See https://github.com/NuGet/Home/issues/2038

**Comment by xavierdecoster** [comment]
Also related: https://github.com/NuGet/NuGetGallery/issues/3573

**Comment by emgarten** [comment]
I'm going to close this then, it sounds like the client no longer needs to report this.
