### ISSUE TITLE
Perf: ManagedLangs_CS_DDRIT.0500.Add New Project regressed CLR_BytesAllocated_devenv by 2,161,657.333 Bytes (23.4%). Baseline 26112.00

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4369]
Internal bug 369272

**Comment by jainaashish** [comment]
Updated some code and started a VS validation build to see results.

**Comment by jainaashish** [comment]
As per discussion with Ashok, resolved the internal bug. Reason - "NuGet added additional ~1.3mb byte allocation for msbuild storage property instance which will anyways be loaded in real customer scenario. And duration regression is not caused by NuGet, rather some async error list work. There is already a test defect bug for that."
