### ISSUE TITLE
Install native NuGet package to Windows 10 native project does not install targets to vcxproj

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4383]
Filed by @joelverhagen via vsfeedback 744582

Concerning VS bug bash on 1/23/2017 scenario "9. Upgrade hybrid C++/C# solution + Azure".

Installing **wastorage** and **cpprestsdk** packages to Windows 10 native project (PlayMp3 project in this case) succeeds according to NuGet but builds fail to find the header files supposedly included in the package.

The package installs work okay for simple C++ command line applications. The package installation properly places the contents of the .targets file from the NuGet package in the bottom of the .vcxproj.

**Comment by rrelyea** [comment]
@zhili1208 - assuming this used to work in VS 2015?

**Comment by zhili1208** [comment]
this works in VS 2015
This is caused by C++ Fast project load, 
FPL is vc specific thing. It is on by default for desktop projects, but not others.
Also, if there is only one project in the solution, the cache is not used. 
So to test cached projects you need a solution with 2 or more projects and at least one desktop project (i.e. the one which does not define ApplicationType property).

The workaround is disable fast project load

Track this internal bug 374804

**Comment by rrelyea** [comment]
C++/CPS team are bring their fixes with internal Bug:
    374807: NuGet package install is broken in desktop C++ projects w/ FPL on (default)

**Comment by zhili1208** [comment]
validated it in vs d15rel 26129.0, it's fixed
