### ISSUE TITLE
Pack command excludes all *.nuspec files

### ISSUE THREAD

**Issue by joaomoreno** [NuGet/Home#439]
In the [source code](http://nuget.codeplex.com/SourceControl/latest#src/CommandLine/Commands/PackCommand.cs) you can read:

```C#
internal void ExcludeFiles(ICollection<IPackageFile> packageFiles)
{
    // Always exclude the nuspec file
    // Review: This exclusion should be done by the package builder because it knows which file would collide with the auto-generated
    // manifest file.
    var wildCards = _excludes.Concat(new[] { @"**\*" + Constants.ManifestExtension });
    if (!NoDefaultExcludes)
    {
        // The user has not explicitly disabled default filtering.
        wildCards = wildCards.Concat(_defaultExcludes);
    }
    PathResolver.FilterPackageFiles(packageFiles, file => file.Path, wildCards);
}
```

The comment says `Always exclude the nuspec file` but the code is actually excluding **any** `nuspec` file. Including the ones that are in wildcarded folders.

**Comment by yishaigalatzer** [comment]
@joaomoreno what are the side effects you are seeing with this? Is it blocking you in any way?

**Comment by joaomoreno** [comment]
part of the files of the package I am creating are actually nuspec files,
they just go missing

**Comment by ashic** [comment]
Same here. I've got a package that creates other packages. The only workarounds I can currently use are:
* Include it with a different extension. Then use install.ps1 to rename it. (yuck).
* Include it with a different extension. In the script that generates end package, rename it. (yuck).

Would really appreciate it if arbitrary nuspec files weren't ignored, or there were some way of including them.

**Comment by yishaigalatzer** [comment]
Sounds like a scenario we haven't thought about. Feel fee to submit a pr. I don't see us touching this any time soon.

**Comment by amferguson** [comment]
I ran into this as well while trying to use Octopus Deploy with an ASP.NET 5 project. When running `dnu publish` it copies all of the various packages that the site depends on to the publish directory. 

Since Octopus Deploy uses NuGet packages to bundle up and deploy the websites, it causes a problem when NuGet ignores some package directories that contain *only* .nuspec files, because loading the site gives an error about the missing directories as missing dependencies. For what it's worth, it doesn't seem to actually care about the missing .nuspec files--just the absence of the directories.

Admittedly, Octopus Deploy's use of NuGet packages for this is a little bit weird since it's not really a package in the normal sense, but this is at least one other case where ignoring those files yields strange results.

**Comment by yishaigalatzer** [comment]
@amferguson this would be a different bug, around keeping empty folders around, wouldn't you say?

**Comment by amferguson** [comment]
@yishaigalatzer Yes, sort-of. In my particular case, the .nuspec files aren't important in and of themselves, but if all .nuspec files weren't being filtered out, they would be included in the .nupkg along with their folder structure. 

In my case, I would be just as happy if nuget.exe still filtered the .nuspec files but kept the empty folders, but if other people have a use for those files, that behavior works well for me too since the folders would come along with the .nuspecs.

**Comment by eric-swann-q2** [comment]
+1 Ran into this same issue with ASP.Net 5 nuget deploy package.
