### ISSUE TITLE
Support duplicate packages in VS UI (or make it configurable)

### ISSUE THREAD

**Issue by Sam13** [NuGet/Home#4400]
NuGet product used: VS UI 
VS UI version 3.5.0.1484
VS version: 2015

Reproduce: 
Having a project which references the same package more than once in different versions the VS UI fails with the following error message:
`An error occurred while reading file [Path to packages.config] There are duplicate packages: [PackageId]`

NuGet.exe can handle this as long as the package version is added to the folder name in the packages directory.

Having the package referenced in multiple versions is e.g useful for:
- Using different binaries from a package for x86 than for x64
- Support a file format in different versions (each version is a NuGet package).

As a workaround I have to provide different names to the packages which is not nice since they should have the same name...

**Comment by emgarten** [comment]
A project can only reference a single version of a package id. A package that supports both x86 and x64 should either be given different package ids for each architecture, or as single package it should contain targets to provide both x86 and x64.

**Comment by Sam13** [comment]
@emgarten Thanks for the information. 
What do you suggest to do e.g if x64 and x86 need to support different versions (e.g. when x86 no longer provided within new package versions)?
Secondly what do you suggest when having to support e.g. a file format in different versions (for which the API comes in different NuGet packages, same name, different version)?

**Comment by emgarten** [comment]
> What do you suggest to do e.g if x64 and x86 need to support different versions (e.g. when x86 no longer provided within new package versions)?

If x64 and x86 are released under different versions then it sounds like these should be completely separate packages. They should use different package ids.

>  a file format in different versions (for which the API comes in different NuGet packages, same name, different version)?

can you elaborate on this? what would it look like?

**Comment by pgrawehr** [comment]
@emgarten: Consider the case where support for a file format (say an application specific data file) is provided by a certain package. The package is updated whenever the file format changes. Because the file format may undergo major changes from one version to another, one version of the package does not support multiple versions of the file. If the application now wants to be able to read or write multiple versions of the file, it needs to be able to load several versions of the package. (The problem of loading multiple almost-identical assemblies into the same process is not the scope here).

**Comment by Sam13** [comment]
@emgarten I agree with @pgrawehr.
I also have to mention that NuGet command line can already deal with that. Only the VS UI is generating an error.
