### ISSUE TITLE
Rebuild does not create .nupkg if project has multiple TFM's

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#4475]
## Details about Problem

NuGet product used:  VS UI

NuGet version:  4.0.0.2260 + private fixes for NuGet/NuGet.Client#1148 and NuGet/NuGet.Client#1159.

VS version:  D15REL 26131.01

OS version (i.e. win10 v1607 (14393.321)):  Windows 10 10.0.14393 (14393.rs1_release.161220-1747)

Worked before? If so, with which NuGet version:

**Repro steps:**
1.  Create a new C# Class Library (.NET Standard) project.
2.  In Solution Explorer right-click on the project and select "Edit <ProjectName>.csproj".
3.  Replace the contents of the project file with:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageVersion>1.0.0</PackageVersion>
    <TargetFrameworks>net461;netstandard1.4</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

4.  When prompted to reload the project, click Reload.
5.  In Solution Explorer right-click on the project and select Properties.
6.  On the Package tab and enable "Generate NuGet package on build."
7.  Build the project and verify that the .nupkg file is created.
8.  Rebuild the project.

**Expected result:**
The .nupkg file will be created.

**Actual result:**
The .nupkg file is not created.

### Verbose Logs
According to diagnostic build logs the `PackTask` task is not called.

### Sample Project
With this [sample project](https://github.com/NuGet/Home/files/748213/ClassLibrary2.zip) you only need to perform repro steps 7 and 8 above.

**Comment by rohit21agrawal** [comment]
turns out that when msbuild /t:rebuild is called, the condition to detect an innerbuild always evaluates to true:

```<IsInnerBuild Condition="'$(TargetFramework)' != '' AND '$(TargetFrameworks)' != ''">true</IsInnerBuild> ```

@rainersigwald is helping me debug through this from msbuild side

**Comment by rainersigwald** [comment]
This is a result of how `Rebuild` is implemented for multi-tfm projects, which is a bit confusing. Details in https://github.com/Microsoft/msbuild/issues/1663 and https://github.com/Microsoft/msbuild/issues/1065.

A quick fix could be made in https://github.com/NuGet/NuGet.Client/blob/7676e7ff39faf3234e264b7b344e17e6900f3ead/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L55-L56. Just add `Rebuild` to the `AfterTargets` of `_PackAsBuildAfterTarget`. That should be safe even if the MSBuild side is fixed because the engine will ensure that the target runs only once, so it won't happen both after `Build` and then again after `Rebuild`.

**Comment by rrelyea** [comment]
@rainersigwald - would prefer to just let your fix carry the day, if possible. any fix we do requires many insertions. can you guys get yours in? when?
