### ISSUE TITLE
Can update to unlisted NuGet package from the Package Manager Console

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#4553]
It is possible to update to unlisted NuGet package from the Package Manager Console but not from the Manage Packages UI.

## Details about Problem

NuGet product used VS UI | Package Manager Console | dotnet.exe:

NuGet version: 3.5 and 4.0

dotnet.exe --version (if appropriate):

VS version: VS 2015 and VS 2017 RC4

## Detailed repro steps so we can see the same problem

1) Visual Studio 2015 (NuGet 3.5)
2) Create a new C# console project.
3) Right click the project and select Manage NuGet Packages
4) Search for Xamarin.Forms (pre-release is not checked).
5) See Xamarin.Forms 2.3.3.180 is latest stable and install it.
6) Open Updates tab and see no updates.
7) Open NuGet Package Manager console
8) Run `Update-Package Xamarin.Forms`

Expected result:

No update found.

Actual result:

Xamarin.Forms 2.3.3.193 is installed.

The 2.3.3.193 NuGet package is unlisted. So not sure what the expected behaviour should be. There is an inconsistency between the UI and the console.

I see the same behaviour in Visual Studio 2017 RC 4 when using a project with a packages.config file. If I instead opt to use PackageReferences in the project then running Update-Package from the Package Manager Console does not update to the unlisted Xamarin.Forms package.

Also noticed that installing the latest Xamarin.GooglePlayServices.Location into an Android project that has the latest stable Xamarin.Forms NuGet package would also cause the Xamarin.Forms 2.3.3.193 NuGet package to be installed even though it is unlisted.

**Comment by tokyo0709** [comment]
We are having the same issue with VS 2017. We have uploaded our own Nuget package and are installing it on seperate projects and when we do Update-Package it updates to the unlisted version. Related Stack question, https://stackoverflow.com/questions/46977808/updating-nuget-package-yields-unlisted-version

**Comment by emgarten** [comment]
NuGet 4.x should match the original 2.x behavior. We need to verify how 2.x handled this.

**Comment by kirk-quinbar** [comment]
I can confirm this same issue in Visual Studio 2017 15.5.4

**Comment by jainaashish** [comment]
Tried with latest VS prerelase bits 15.6.0 preview3 and couldn't repro it. I tried it with Newtonsoft.json as well as MySql.Data packages and in both cases, it didn't update to the prerelease version.

**Comment by guFalcon** [comment]
Ok. I thought that the update to the unlisted version is the way it's supposed to work.
How else do I 'deprecate' a package if it doesn't update?

IMO:
* Package should update to unlisted version
* Unlisted packages should no longer show up in lists online
* You shouldn't be able to (newly) install unlisted packages

So the update to the unlisted version is OK here, isn't it? (is there something I'm not getting here?)

Because... I want to deprecate a package right now...
* Make an update and add the description, that it's deprecated all over the package info
* Leave a link to the new package and an explanation as to why you're deprecating this old one
* Push the update
* Now everyone using the old one should get the update, read the text and hopefully switch to the new path
