### ISSUE TITLE
internal: deadlock while opening a solution that uses nuget

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4566]
see vsfeedback 804256 - found on build 265050.0
has provided a dump.

**Comment by jainaashish** [comment]
From the dump it looks like, it was not just open solution instead user might have right clicked on solution immediately after opening solution or something like that to get to this state. So it might not be the common scenario. But we are also trying to get watson numbers for this stack trace to get the priority of this issue for RTM.

**Comment by jainaashish** [comment]
Form UIDelays I can see this stack trace only had 2 hits so we can move this to 4.0.1
http://uidelays/#?q=m:Microsoft.VisualStudio.Composition.*%20v:15.*%20f:microsoft.visualstudio.composition.dll!Microsoft.VisualStudio.Composition.ExportProvider%2BPartLifecycleTracker.WaitForState&p=100&s=microsoft.visualstudio.composition.dll!Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory%2BRuntimeExportProvider%2BRuntimePartLifecycleTracker.CreateValue

**Comment by jainaashish** [comment]
Fixed as part of https://github.com/NuGet/Home/issues/4665  and PR# https://github.com/NuGet/NuGet.Client/pull/1196

It was the same root cause since while VSSettings was being MEF constructed, it wanted to switch to UI thread to access ServiceLocator. But since UI thread was already waiting for this to be constructed so deadlocked. So we've moved switching to Main thread from all the MEF constructors.
