### ISSUE TITLE
vsfeedback: NullRef when New Project is not saved yet

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4567]
have a new machine, with newly installed VS:
In Options->Projects->General-> uncheck save new projects
File->New->Project->C#->WPF app
I have no NuGet Packages

Build it, I get :
Error occurred while restoring NuGet packages: Object reference not set to an instance of an object.
1>------ Rebuild All started: Project: AsyncNest, Configuration: Debug Any CPU ------
1>  AsyncNest -> C:\Users\calvinh\AppData\Local\Temporary Projects\AsyncNest\bin\Debug\AsyncNest.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

more details in internal vsfeedback item 790457

**Comment by nkolev92** [comment]
Can repro with 26206. Seems like yet another package initialization/loading problem.

**Comment by nkolev92** [comment]
This is a regression from 3.4.4 + VS2015

**Comment by rrelyea** [comment]
Workaround: Save project.

**Comment by nkolev92** [comment]
The root cause of our null ref is the fact that the DTE returns an empty solution path when this variable is unchecked. 
We make that call right here: 
https://github.com/NuGet/NuGet.Client/blob/b89bb5750c475212213e14f750604d2ecaf704ff/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L531

I am not sure if this is the expected behavior.

**Comment by nkolev92** [comment]
It repros on VS14 with our new bits as well. 
So the path value for such projects is an empty string in both VS14 & VS15

**Comment by nkolev92** [comment]
The changes for this are in the dev-nkolev92-fixrestorenullref branch. I will create a PR when we change branches.
