### ISSUE TITLE
If your solution has projectreferences that refer to the same project, with different casing, restore may not work. This also affects different relative paths, without a difference in casing

### ISSUE THREAD

**Issue by iskiselev** [NuGet/Home#4574]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe, msbuild /t:Restore
NuGet version (x.x.x.xxx): 4.0 RC
VS version (if appropriate): VS 15.0.0-RC4+26206.0
Worked before? If so, with which NuGet version: VS 2015 / NuGet 3.5

## Detailed repro steps so we can see the same problem

1. Checkout example from https://github.com/iskiselev/NuGetCaseSensitiveBug
2. nuget restore Test.sln or msbuild /t:restore Test.sln

Several errors will be reported. Root cause of problem is using path "..\..\services\Proj1\Proj1.csproj" instead of "..\..\Services\Proj1\Proj1.csproj" in file "BusinessLogic\Proj3\Proj3.csproj".
Unfortunately, file with root cause was also never reported in error message, so it was very hard to find it in 100+ project solution.

Solution could be built inside VS 2017 without problems.

**Comment by rrelyea** [comment]
Let's dig into this one and understand the problem. Do nuget.exe and msbuild /t:restore have a problem that VS and dotnet.exe don't?
Or is this just the change in 3.5rtm to treat packages as case insensitive and store them as lower case on disk, etc...
/cc: @joelverhagen

**Comment by iskiselev** [comment]
Sample doesn't work with nuget 4.0, dotnet (1.0.0-rc4-004771), msbuild 2017 RC4. It works with VS 2017 RC4 and nuget 3.5.

**Comment by rrelyea** [comment]
@rohit21agrawal - can you please determine how VS, dotnet add project, and other techniques could let a user get into this. Or is is just hand editing?

**Comment by rohit21agrawal** [comment]
@rrelyea so i have confirmed that you can never get to this inconsistent casing using a tool like VS, or the ```dotnet add project``` command .  The only way to get into this state is if you hand-edit the csproj and add the project reference manually.

However, the issue is not as simple as i thought, this only repro's when more than one project( say ProjB and ProjC) reference a project (say ProjA) such that the casing of their reference is inconsistent. Something like this: 

ProjB: ``` <ProjectReference Include = "..\..\FolderA\projA.csproj"/>```
ProjC: ``` <ProjectReference Include = "..\..\folderA\projA.csproj"/>```

The incosistency of casing in f in FolderA is what causes this issue.

OR

ProjB: ``` <ProjectReference Include = "..\..\FolderA\projA.csproj"/>```
ProjC: ``` <ProjectReference Include = "..\FolderA\projA.csproj"/>```

In this case the relative path string are different.

**Comment by rohit21agrawal** [comment]
This also seems to be a regression as @iskiselev pointed out , since it works with NuGet 3.5, but doesn't work with 4.0.0 builds.
