### ISSUE TITLE
dotnet restore, msbuild /t:Restore and Visual Studio produce different assets files causing unnecessarily design-time builds

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4627]
Build: 26210.2.d15rel

It appears that `dotnet restore`, `msbuild /t:Restore` and Visual Studio all produce different versions of the assets files. ~The difference between dotnet restore and msbuild/Visual Studio is the most alarming because it appears that dependencies changed~(this appears to be an out-of-date dotnet). The difference between msbuild /t:Restore and Visual Studio, is causing Visual Studio to kick off unnecessarily design-time builds when you do a command-line restore for every TFM times the number of projects you have. When you have a large project like MVC, this is a lot of wasted cycles and CPU time.

1. File -> New Console App (.NET Core)
2. Wait for restore
3. Rename `obj\project.assets.json` to `obj\project.assets.json.vs`
4. Open Visual Studio command prompt
5. `msbuilt /t:Restore [project]`
6. `devenv /diff obj\project.assets.json obj\project.assets.json.vs`

Expected: For them to be exactly the same
Actual: They are different

Between msbuild /t:Restore and VS differences are the project section:

Visual Studio
```
  "project": {
    "version": "1.0.0",
    "restore": {
      "projectUniqueName": "c:\\users\\davkean\\documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\ConsoleApp189.csproj",
      "projectName": "ConsoleApp189",
      "projectPath": "c:\\users\\davkean\\documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\ConsoleApp189.csproj",
      "outputPath": "c:\\users\\davkean\\documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\obj\\",
      "projectStyle": "PackageReference",
      "originalTargetFrameworks": [
        "netcoreapp1.0"
      ],
      "frameworks": {
        "netcoreapp1.0": {
          "projectReferences": {}
        }
      }
    },
    "frameworks": {
      "netcoreapp1.0": {
        "dependencies": {
          "Microsoft.NETCore.App": {
            "target": "Package",
            "version": "1.0",
            "autoReferenced": true
          }
        }
      }
    },
    "runtimes": {
      "win": {
        "#import": []
      },
      "win-x64": {
        "#import": []
      },
      "win-x86": {
        "#import": []
      }
    }
  }
```

msbuild /t:Restore

```
  "project": {
    "version": "1.0.0",
    "restore": {
      "projectUniqueName": "C:\\Users\\davkean\\Documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\ConsoleApp189.csproj",
      "projectName": "ConsoleApp189",
      "projectPath": "C:\\Users\\davkean\\Documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\ConsoleApp189.csproj",
      "outputPath": "C:\\Users\\davkean\\Documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\obj\\",
      "projectStyle": "PackageReference",
      "originalTargetFrameworks": [
        "netcoreapp1.0"
      ],
      "files": {
        "lib/netcoreapp1.0/ConsoleApp189.dll": "C:\\Users\\davkean\\Documents\\visual studio 2017\\Projects\\ConsoleApp189\\ConsoleApp189\\bin\\placeholder\\netcoreapp1.0\\ConsoleApp189.dll"
      },
      "frameworks": {
        "netcoreapp1.0": {
          "projectReferences": {}
        }
      }
    },
    "frameworks": {
      "netcoreapp1.0": {
        "dependencies": {
          "Microsoft.NETCore.App": {
            "target": "Package",
            "version": "1.0"
          }
        }
      }
    },
    "runtimes": {
      "win": {
        "#import": []
      },
      "win-x64": {
        "#import": []
      },
      "win-x86": {
        "#import": []
      }
    }
  }

```

Note the casing of the paths,

**Comment by TheRealPiotrP** [comment]
This is very likely due to differences in the vesion of Microsoft.Extensions.DependencyModel used by SDK. I'm surprised that we're seeing different behavior on VS console vs. VS itself. I'd expect those task implementations to be identical.

**Comment by TheRealPiotrP** [comment]
hmm... reread. Since these are diffs in the assets files, DependencyModel should not be involved. We need someone from the nuget team to take a look.

**Comment by emgarten** [comment]
Great issue, I think the outputs should be identical to avoid reloading when running restore from the command line. The package spec section was added in 4.0.0 to the assets file, and it looks like it needs some normalization.

The path casing looks right for the MSBuild output. From what I see in the NuGet code the VS path comes from DTE. It is unclear why this would be making some of these directories lowercase.

AutoReferenced is another difference, it only appears for VS currently since it isn't used in the command line. But this could be fixed.

I've also seen sorting issues with the package spec dependencies. When restoring MVC I saw the order change between VS and MSBuild due to the way that it discovers package references.

**Comment by emgarten** [comment]
@rrelyea the investigation is complete here, does this meet the bar for RTM?

**Comment by emgarten** [comment]
This has been improved in 15.5 as part of noop/normalization.

**Comment by davkean** [comment]
@emgarten I'm still running into this.

1. git clone https://github.com/dotnet/project-system
2. git checkout 4d3123c78fcb3cc854fd39d9421f250337ef8e49
3. open ProjectSystem.sln
4. Wait for restore to finish
5. Close Visual Studio
6. Make a copy of project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\project.assets.json
7. Run build.cmd which implicitly runs restore
8. Compare the new project.assets.json file with the previous one

Expected: No differences
Actual: Differences

Visual Studio:
```
"project": {
    "version": "2.5.0-dev",
```

Command Line:
```
"project": {
    "version": "2.5.0-dev",
    "restoreSettings": {
      "hideWarningsAndErrors": true
    },
```

Visual Studio:

```
          "projectReferences": {
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed\\Microsoft.VisualStudio.ProjectSystem.Managed.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed\\Microsoft.VisualStudio.ProjectSystem.Managed.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.VS\\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.VS\\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj"
            }
```

Command-line:

```
          "projectReferences": {
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.VS\\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed.VS\\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj"
            },
            "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed\\Microsoft.VisualStudio.ProjectSystem.Managed.csproj": {
              "projectPath": "E:\\project-system2\\src\\Microsoft.VisualStudio.ProjectSystem.Managed\\Microsoft.VisualStudio.ProjectSystem.Managed.csproj"
            }
```

**Comment by emgarten** [comment]
//cc @nkolev92 for cmd vs VS asset file issues.

**Comment by emgarten** [comment]
@nkolev92 has this been fixed in 4.5.0?

**Comment by nkolev92** [comment]
Looking at it quickly, the restore settings bit is an issue that I bypass in no-op, but haven't considered not writing in the project.assets.json. 
The difference there is that hideWarningsAndErrors is implied by the SDK in VS. 

Looking at the 2nd part, I don't  think that's fixed. 
Self-assigning, will investigate and try to get it in 4.6.0

**Comment by nkolev92** [comment]
It seems like the projectReferences out of the order is the only issue here, with regards to triggering design time builds. 

The restore settings being written down, at this point is wrong, because despite the name, settings, it currently doesn't affect the restore result, merely affects the decision on who displays the warnings and errors to the error list in VS. As such, I'll remove it. 

Here's why the project references out of order is the only issue. 

No-op already disregards the restore settings. So if only that changes among, VS-CLI, we'd still no-op. 
If no-op happens, we ofc won't try to rebuild the assets file, thus not writing to the disk, which in turn does not trigger a design-time build. 

PR coming soon.

**Comment by jainaashish** [comment]
Merged into release-4.6.0-rtm with commit# c70fa4d23d3824ea642d75bac985439ada0c349a

**Comment by aolszowka** [comment]
I don't think this issue is resolved; we're seeing it in Visual Studio 2017 15.9.12 most notably its the Project Names; it appears that in the Visual Studio version (the diff on the right) makes the assumption that the Output name is the same as the CSPROJ name. Unfortunately due to path length limitations this is not the case in our environment. This causes NuGet to update the project.assets.json thus triggering a full blown build for all 1,000 of our projects (very painful). Its unclear where this is being set; I assume that in Visual Studio's version they are using something like $(MSBuildProjectName) instead of $(AssemblyName).

Here's one of the project.assets.json shown in WinMerge; the version of the left is the one produced by msbuild.exe the one on the right is produced by Visual Studio:

![image](https://user-images.githubusercontent.com/2592881/60274993-58098700-98b6-11e9-9d67-8585a7201394.png)

We can open a new issue if it would help. Or if you can point me to the owners or even the code I'd be happy to make a fix as this affects us daily.

**Comment by davkean** [comment]
@aolszowka Can you open a new issue?

**Comment by aolszowka** [comment]
Opened #8272 Thank you
