### ISSUE TITLE
.NETStandard Target moniker is ignored by nuget / msbuild when creating a nuget package

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4660]
vsfeedback 813319

is the summary of this problem that repository metadata in .nuspec doesn't work in old clients?
if that is the case, do we remove? or do we update downlevel clients?

**Comment by emgarten** [comment]
NETStandard.Library 1.6.0 supports NETStandard 1.0. If you take a look at the packages you can see that there are lib folders containing all target frameworks.

If the project target framework is set to netstandard1.0 you should see the project dll under netstandard1.0. The package dependency on NETStandard.Library 1.6.0 does not indicate what the package targets.

**Comment by rohit21agrawal** [comment]
yeah, i don't think this is a bug . The user is confusing the package dependency NETStandard.Library 1.6.0 that comes as a part of targeting netstandard1.0 with the target framework itself.

**Comment by stormleoxia** [comment]
Hi, I've reported the issue.
If I create in Visual Studio 2015 a .NET Core Library targeting .NETStandard 1.4, it won't be able to use the package created with Visual Studio 2017, because any .NETStandard library created with Visual Studio 2017 is packaged as requiring .NETStandard 1.6.
I've added a screenshot below.
![dependencyconflict](https://cloud.githubusercontent.com/assets/13752108/23202141/45ea3b58-f90f-11e6-8c60-544d1a5674df.png)

And following is the dependencies part of Lx.Performance.nuspec generated by msbuild /t:pack

    <dependencies>
      <group targetFramework=".NETStandard1.0">
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>

In Visual Studio 2017, references will always work because you cannot downgrade the .NETStandard to something below 1.6. Nuget will state the lib is unsupported but it will build nicely.

My use case is providing library on any platforms that doesn't (and likely never) support .NETStandard 1.6, like UWP. I've based my use case on that :

![Platform](https://s3.amazonaws.com/blog.xamarin.com/wp-content/uploads/2016/08/01182307/Platforms.png)
from [Xamarin](https://blog.xamarin.com/net-standard-library-support-for-xamarin/)

And by the way, thank you guys, you do an amazing job ! 👍

**Comment by stormleoxia** [comment]
To fix manually my problem:

- Modifying the nuspec file with the following:

```
<dependencies>
  <group targetFramework=".NETStandard1.0">
    <dependency id="NETStandard.Library" version="1.0.0" exclude="Build,Analyzers" />
  </group>
</dependencies>
```
- Removing repository tag in order to use nuget 3.5.0 on the nuspec file (I don't know how to force msbuild to use the nuspec to pack without regenerating it and overriding my changes).
- Republishing generated package on my nuget server.
- Clean my local nuget package cache (usually in C:\Users\<Username>\.nuget\packages\<libName>)

Tada! No warning anymore in Vs2015 when restoring packages on a .NETStandard 1.4 Library referencing the above mentioned library.

**Comment by rohit21agrawal** [comment]
@stormleoxia to pack a nuspec file using msbuild, here are the steps : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#packing-using-a-nuspec

**Comment by rohit21agrawal** [comment]
@stormleoxia you are confusing Netstandard.Library (which is a package dependency) with the target framework .NetStandard1.4

Just because the target framework is .NetStandard1.0 , doesn't mean it will need Netstandard.Library 1.0.0 . There is no correlation between target framework and netstandard.library versions like that.

It's still interesting as to why your package Lx.Performance is trying to pull in a RC2 version of Netstandard.Library. Could you tell us more about the Lx.Performance package, and if possible, paste the contents of the nuspec file in that package?

Also, knowing what sources do you have listed in your nuget.config will be useful.

**Comment by stormleoxia** [comment]
@rohit21grawal you are right. I was assuming there was a mapping .NETStandard 1.0 <=> .NETStandard.Library 1.0 :) Lx.Performance doesn't depends on RC2. 
In fact, I was confused also because the strange display of Unsupported in nuget package explorer. 
But it seems nexus related. 
Sorry for the wrong bug report :(
And thank you for the nuget link.

**Comment by rohit21agrawal** [comment]
@stormleoxia no problem, happy to help. assuming all your questions have been answered, i am closing this issue. Please reactivate it if you still have issues.
