### ISSUE TITLE
NuGet Restore Allocations hang Visual Studio

### ISSUE THREAD

**Issue by DoRonMotter** [NuGet/Home#4667]
Investigate string allocations during Nuget Restore for certain projects:

The process is doing nuget restore and taking a really long time. It's also pretty high on VM usage (altho low on managed heap)

nuget is allocating a lot of memory on many stacks - e.g. 500MB for nuget.contentmodel
Name               	Inc %	          Inc
nuget.contentmodel	 8.6	  557,513,344

1.3GB of strings allocated - a large chunk from nuget string manipulation functions.

500MB allocations just for DependencyResolver enumerators

More details at 385896

**Comment by jainaashish** [comment]
This is the call stack for ~500MB allocation for NuGet.DependencyResolver.GraphNode

Name                                                                                                                   	Inc %	           Inc
 Type Enumerator[NuGet.DependencyResolver.GraphNode`1[NuGet.DependencyResolver.RemoteResolveResult]]                   	  7.8	   509,059,264
+ clr!?                                                                                                                	  7.8	   509,059,136
 + mscorlib.ni!System.Collections.Generic.List`1[System.__Canon].System.Collections.Generic.IEnumerable.GetEnumerator()	  7.8	   509,059,136
  + nuget.dependencyresolver.core!GraphOperations.ForEach                                                              	  7.6	   496,772,832
  |+ nuget.dependencyresolver.core!GraphOperations.TryResolveConflicts                                                 	  5.2	   340,925,280
  |+ nuget.dependencyresolver.core!GraphOperations.ForEach                                                             	  2.4	   155,847,424

So the main issue here is GetEnumerator() since this code path is inside 3 layers nested while/foreach loop so it tries to load it for 100s of 1000s times which results in this memory allocation. 

Ideal solution is remove GetEnumerator calls through replacing ForEach with For loops which will iterate based on index instead of getting iterator through Enumerator.
