### ISSUE TITLE
[Security] API keys should not be stored as plain text in nuget.config

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4686]
Today one can use setapikey command to set the API key into nuget.config as plain text. This should be allowed.

NuGet should use credential store mechanism to store the API key so that any plain text copy of API key can be avoided.

**Comment by maartenba** [comment]
Many People use this today as a mechanism to store API key in a config file that is used on the build server.

**Comment by xavierdecoster** [comment]
Please note: 
A while ago, a new `-StorePasswordInClearText` switch was added to the `nuget.exe sources` command to explicitly allow storing the password in clear text in `nuget.config`. See this old CodePlex issue tracking it: http://nuget.codeplex.com/SourceControl/network/forks/XavierDecoster/nuget/contribution/4400

Not allowing to store the api key in that file in clear text would be very contradictory. The very reason that command switch was added, was because of **OS specific and/or machine specific** encryption, which made `nuget.config` not portable (e.g. stored in VCS, used on any machine), and the code was not xplat compatible.

**Comment by anangaur** [comment]
Thanks. Makes sense. May be we should 'also' allow usage of credential store mechanism for users, without taking away the present capability. That way we let users decide the security aspect of the keys. 
IMO, API keys are just like passwords and should only be put in a key-vault like implementations.

**Comment by anangaur** [comment]
Closing this in favor of https://github.com/NuGet/Home/issues/6153 where I am planning to put a proposal that covers other related scenarios as well.
