### ISSUE TITLE
Directory structure for sources flattened when included from parent directory and duplicate file warning received

### ISSUE THREAD

**Issue by attilah** [NuGet/Home#4709]
## Details about Problem

When packing with source code and the source files are included from a parent directory relative to the csproj, the cs files are getting flattened and packed that way into the nupkg and if you've the same filenames you get a warning about that file is not included.

dotnet version: 1.0.0
dotnet nuget version: 4.0.0.0

## Detailed repro steps so we can see the same problem

1. dotnet restore
2. dotnet build
3. dotnet pack

## Log

```
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Repro -> C:\13\New\bin\Debug\netstandard1.5\Repro.dll
  Successfully created package 'C:\13\New\bin\Debug\Repro.1.0.0.nupkg'.
C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : File 'C:\13\Old\Sub\Foo.cs' is not added because the package already contains file 'src\New\Foo.cs' [C:\13\New\Repro.csproj]
  Successfully created package 'C:\13\New\bin\Debug\Repro.1.0.0.symbols.nupkg'.
```

### Sample Project

Attached the repro project.

[repro.zip](https://github.com/NuGet/Home/files/806010/repro.zip)

**Comment by rohit21agrawal** [comment]
About the files getting flattened, that is expected behavior.

Every source file should go into the src\<ProjectName> folder maintaining relative path to the csproj file. However, consider scenarios where a source file is included from a directory that is the parent of the grandparent of directory in which the csproj resides. Where would the source file be put in that case?

Therefore, anything which is not in the same or child directories of where the csproj file resides is flattened out.

You can easily workaround this by specifying Pack=true and PackagePath on your source file in the csproj file.

**Comment by attilah** [comment]
So it is expected behavior this way, I see the reasoning behind it and yes determining what can be the root can be vary from project to project.

What I'd expect is to receive a warning in this case about the flattening, since that was not expected, because this does not happen with regular files under the same directory as the project file.
