### ISSUE TITLE
Nugetizer should enable "Edit this.nuproj" command in context menu instead of offer an extra .targets file

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4728]
.NET Core projects, also based on CPS, enable an "Edit this.nuproj" command on the context menu so users can edit the project xml in the editor while the project is still loaded. 

After doing this, the external .targets file that is created so users can conveniently edit project xml is no longer necessary.

**Comment by AArnott** [comment]
CC: @kzu

**Comment by kzu** [comment]
@davkean could you point us to the relevant Roslyn project system that exposes this command? 

Thanks!

**Comment by AArnott** [comment]
I *think* it's [this](https://github.com/dotnet/roslyn-project-system/blob/5c13ac487b74c8a2ab20f85d825235cb016b0b4f/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ManagedProjectSystemPackage.cs#L20-L21) but @davkean should be able to say for sure (and whether there's code to back these capabilities up).

**Comment by davkean** [comment]
These capabilities cannot be in the targets files, they must be up-front and known before the configuration capabilities have flowed into the unconfigured project, otherwise, you will start seeing errors like this: https://github.com/dotnet/roslyn-project-system/issues/1103. This is a timing thing, so you won't see it all the time.

The reason for this is that these capabilities add COM components that the ProjectNode aggregate waay before the configurations have been loaded.

**Comment by kzu** [comment]
Ugh, that's super ugly. Is it a CPS known bug?

**Comment by AArnott** [comment]
Should we reactivate this then?

**Comment by kzu** [comment]
@davkean could you share pointers as to how to provide those capabilities early enough?

**Comment by davkean** [comment]
That exact code that Andrew points shows that, you set it on the project type. :)

This not really a CPS bug because that's how it was designed. We run into the same thing with services that need to figure out configurations. MSBuild evaluation only runs in configs, but there's a bunch of services that need to run _before_ configs are known. Capabilities in targets only take affect when a configuration is promoted to the "Active" config, well after these services are needed and used.

**Comment by davkean** [comment]
To provide some more information, capabilities in targets automatically by their very nature become "dynamic" - that is components that apply to them must also be dynamic if they want to be auto-loaded, ie no tranditional fixed AutoLoad, instead they must implement IProjectDynamicLoadComponent.

**Comment by kzu** [comment]
Gotcha @davkean. Thanks!
