### ISSUE TITLE
Package is being installed into non-supported framework

### ISSUE THREAD

**Issue by prochan2** [NuGet/Home#4776]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet Package Manager for Visual Studio 2015

NuGet version (x.x.x.xxx):
3.5.0.1484

VS version (if appropriate):
2015 Update 3

OS version (i.e. win10 v1607 (14393.321)):
win10 v1607 (14393.693)

Worked before? If so, with which NuGet version:
no, never tried before

## Detailed repro steps so we can see the same problem

1. Create a project (C# Console Application for instance) targeting .NET Framework 4.5.
2. Install package https://www.nuget.org/packages/PostSharp.Patterns.Caching.Redist/5.0.19-preview

## Actual behavior

The package installs and adds no references.

## Expected behavior

The package does not get installed at all since the package should support .NET Framework 4.6 and above only.

## Notes

The only file in the package is lib\net46\PostSharp.Patterns.Caching.dll.

**Comment by jainaashish** [comment]
@prochan2 this is the expected behavior. Since package `PostSharp.Patterns.Caching.Redist` has some dependencies which are compatible with `net46` so it's able to successfully install since you still can use those dependencies assemblies reference. 

It will only fail when there is no compatibility project level content, or tools or dependencies.
