### ISSUE TITLE
nuget will be stuck when calling "uninstall-package" from install.ps1 in VS2017

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4811]
Internal email says: I have a solution with various Windows services, Cloud services, libraries, etc (all C#). Our projects reference both public (nuget.org) and private (internal VSTS) packages. I am able to upgrade the nuget.org packages however when I try to update the internally hosted packages, the package is just removed and it never updated. Is this a known issue? My teammate is experiencing the same problem and we've had to revert back to VS2015.

**Comment by zhili1208** [comment]
the issue here nuget will be stuck when calling "uninstall-package" from install.ps1.

NServiceBus.Azure 7.0.0 has install.ps1 which is calling uninstall-package.

nuget is stuck when installing or updating to this package.

The workaround is remove NServiceBus.Azure 7.0.0 dependency and add NServiceBus to dependency list ,since this package is an empty package and is only used to install NServiceBus 6.0.0

this works in VS2015

**Comment by jainaashish** [comment]
`NServiceBus.Azure 7.0.0 has install.ps1 which is calling uninstall-package.
nuget is stuck when installing or updating to this package.`

Reason NuGet is stuck there is, since post NuGet 4.0 version, it only allows one operation at a time and controls it via semaphore slim lock. Since install package was already started so that acquired the lock and when install.ps1 script tried to run uninstall-package command which again tries to acquire this lock and hangs indefinitely.

Ideally this is not the right approach to uninstall the same package via install.ps1 which you're currently installing, it's a simple hack and I recommend to update the package to remove this hack. But since it was working until 3.5.0 in VS 2015 so we need to take a call here.
