### ISSUE TITLE
nuget.config should allow for Credential Providers search paths

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4841]
Currently only three locations are mentioned at: https://docs.microsoft.com/en-us/nuget/api/nuget-exe-credential-providers are looked at when getting creds. Now that nuget restore is invoked with msbuild.exe /t:Restore this removes any "Zero-config" and "portable" solution to Credential Providers. 

To me it would make sense to allow the Cred Provider search paths to be customized in a nuget.config so that regardless of which nuget.exe is used, cred providers for a given solution / project could be correctly identified.

**Comment by infin8x** [comment]
This is a great idea, thanks! Right now, msbuild /t:restore uses dotnet under the hood, which doesn't support credential providers at all. It's on the medium-term roadmap for the NuGet and VSTS Package Management team to build that feature. We can't right now because dotnet doesn't support cross-platform encrypted credential storage.

**Comment by nkolev92** [comment]
Thanks for creating this issue. 

At this point we believe our authentication story is mature enough to consider this complete. 

Specifically we have built a plugin mechanism solution that works with *every* client (nuget.exe, msbuild.exe, dotnet.exe, VS) and while there are some slight differences the configuration, there are plenty of options available. 

You can read more about it at https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds
