### ISSUE TITLE
The V2 feed at '' returned an unexpected status code '404 Not Found'.

### ISSUE THREAD

**Issue by milan11** [NuGet/Home#4860]
STEPS TO REPRODUCE
- Visual Studio 2015
- Tools -> Extensions and Updates... -> verify that NuGet Package Manager version is 3.5
- Tools -> Options
- NuGet Package Manager / Package Sources
-- add:
--- Name: esa
--- Source: https://esa.eset.com/sdk/packages/nuget
- Manage NuGet Packages for solution
- Package source: select esa
- Browse
- there is Error occurred
- there is error message in Output window / Package manager:
[esa2] The V2 feed at 'https://esa.eset.com/sdk/packages/nuget/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='native%7Cnet40%7Cnet35%7Cnet45%7Cnet452'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '404 Not Found'.

It workes correctly with older NuGet versions, e.g. NuGet 3.3
It does not work with new versions: NuGet 3.5.0.1996, NuGet 3.4.4

HTTP communication captured using Fiddler:
- where it works - [3.3.txt](https://github.com/NuGet/Home/files/857264/3.3.txt)
- where it does not work - [3.5.txt](https://github.com/NuGet/Home/files/857265/3.5.txt)

We assume it is because the server-side uses some older repository structure.
Was support for such old repository deprecated and not supported anymore by clients?
Should the server-side provide something for the client to be able to detect it is the old repository?

**Comment by milan11** [comment]
Maybe related: #4847

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by milan11** [comment]
@emgarten Unfortunately this issue still exists in both NuGet 3.5 and NuGet 3.6.0.2511. Tested again with Visual Studio 2015. Or is there something different that could influence it (e.g. version of some other extension in Visual Studio)?

**Comment by pantonis** [comment]
Can confirm the same issue using VS 2017 15.4.0

**Comment by pantonis** [comment]
It stopped working after I installed .NET 4.7.1 on my nuget server.

**Comment by ghost** [comment]
Have you tried to put virtual repo over remote repo and install packages from virtual?

**Comment by emgarten** [comment]
This sounds like a problem with the feed. This repository tracks issues for the client side of nuget.

**Comment by ghost** [comment]
Ok. Sorry

**Comment by gitvaibhav** [comment]
Facing this issue with VS 2017 Community edition

**Comment by milan11** [comment]
New nuget client and some older nuget servers (e.g. this Java server: https://github.com/JetBrains/teamcity-nuget-support/tree/standalone3) are not compatible.
Creating a new nuget server following some up-to-date instructions will solve this problem.

**Comment by mmorrisuts** [comment]
I had this problem last night in VS2017 15.9.11.
All VS2017 projects were stuck, and I was unable to browse NuGet packages through VS2017.  However, this was only occurring on my computer at the office.... but again, it was occurring for all projects on my computer.  
The error message included a note about .NET 4.6.1... which is what I was generally using for my projects.  A co-worker was using .NET 4.7, and having no issue.  I didn't have .NET 4.7 installed, but I already had 4.6.2 installed (though I hadn't yet used it in a project).  So I upgraded to .NET framework 4.6.2 on that particular project (the one that originally had the issue), and the problem went away on all projects.... even the original project when I reload from version control with .NET Framework 4.6.1.
I can't even regenerate the error... at least so far.

So the problem seems to be solved in my case by switching .NET Frameworks.... even temporarily.

**Comment by mmorrisuts** [comment]
I just had a similar problem last night in VS2017 15.9.11, and the solution in my case was to change .NET Framworks... even temporarily.  

Details:
All VS2017 projects were stuck, and I was unable to browse NuGet packages through VS2017. However, this was only occurring on my computer at the office.... but again, it was occurring for all projects on my computer.
The error message included a note about .NET 4.6.1... which is what I was generally using for my projects. A co-worker was using .NET 4.7, and having no issue. I didn't have .NET 4.7 installed, but I already had 4.6.2 installed (though I hadn't yet used it in a project). So I upgraded to .NET framework 4.6.2 on that particular project (the one that originally had the issue), and the problem went away on all projects.... even the original project when I reload from version control with .NET Framework 4.6.1.
I can't even regenerate the error... at least so far.

So the problem seems to be solved in my case by switching .NET Frameworks.... even temporarily.

**Comment by sirinath** [comment]
I am having a similar error:

```
[nuget.org] The V2 feed at 'https://www.nuget.org/Search()?$filter=IsAbsoluteLatestVersion&searchTerm='ctrader'&targetFramework='net6.0'&includePrerelease=true&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.
```
