### ISSUE TITLE
Symbol server vs. including pdb files in package

### ISSUE THREAD

**Issue by maxtoroq** [NuGet/Home#497]
What are the benefits of using a symbol server instead of simply including the pdb files in the nuget package?

**Comment by yishaigalatzer** [comment]
The main advantage is that the package size is much smaller. So your restore/disk utilization and potentially deployment are smaller by default.

There is also an automatic matching of the pdb to your dll if you deploy an application without the pdb, where you will have to manually match them otherwise.

**Comment by yishaigalatzer** [comment]
@maxtoroq probably a good idea to cross post at stackoverflow.

**Comment by maxtoroq** [comment]
@yishaigalatzer Did post on stackoverflow, but got no answers:
http://stackoverflow.com/questions/27988200/symbol-server-vs-including-pdb-files-in-package

**Comment by yishaigalatzer** [comment]
Now you do :)

-----Original Message-----

**Comment by deepakaravindr** [comment]
Closing this issue as stackoverflow is answered
