### ISSUE TITLE
Restore misses project level config files

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4979]
``RestoreArgs`` caches settings incorrectly based only on the first ``NuGet.Config`` file in the chain. This is typically the machine wide settings under program files. The result of this is that all projects get the same settings, even if they have a ``NuGet.Config`` file in their project directory.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs#L127

Potential fix for this:
```
var cacheKey = string.Join("|", settings.Priority.Select(e => e.Root));
return _sourcesCache.GetOrAdd(cacheKey, (root) => GetEffectiveSourcesCore(settings));
```

**Comment by mishra14** [comment]
I agree with @emgarten's  fix for short term. But that will lead to extra memory foot print because we will land up caching the same config file multiple times in different setting chains.

I propose the following for long term solution - 

`SettingsPerProject-> LinkedList<string>` which maintains the priority of paths of different config files. This will be per project.
`GlobalSettings-> Dictionary<string, NewSettingsClass>`  which maintains the mapping of config file paths to `ISettings ` objects. This can be a global construct which allows using the same `ISettings ` object to be re used between multiple projects.
`NewSettingsClass `-> Same as `ISettings` but without the pointers to the next `ISettings` in the chain.


@emgarten thoughts?

**Comment by emgarten** [comment]
@mishra14 avoiding the reload of each settings file during the restore args load was investigated here https://github.com/NuGet/Home/issues/2297 and no significant improvements came from it. 

I agree that ideally we would only load each file once, and that the settings load would be improved to take a common cache where this info can be stored.
