### ISSUE TITLE
dotnet restore failing in Docker container

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5014]
_From @willseward on April 11, 2017 17:58_

## Steps to reproduce

```dockerfile
# Minimal non-working example
FROM microsoft/dotnet:1.1.1-sdk-nanoserver
...
CMD dotnet restore
```

```powershell
PS \> docker run -it --rm -v "${pwd}:C:\BuildDir" -v "${pwd}\dist:C:\Out" docker-builder
```

## Expected  behavior

Command restores packages.

## Actual behavior

```text
...
  Installing runtime.win7-x64.Microsoft.NETCore.Jit 1.1.1.
  Installing runtime.win7-x64.Microsoft.NETCore.DotNetHostResolver 1.1.0.
  Installing System.Private.Uri 4.3.0.
  Generating MSBuild file C:\<...>\obj\<obfuscated>.csproj.nuget.g.props.
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Access to the path is denied. [C:\<...>\<obfuscated>.sln]
```

### Filtering for solution file access

<img width="959" alt="screen shot 2017-04-11 at 12 53 01 pm" src="https://cloud.githubusercontent.com/assets/5386568/24923059/fab88f82-1eb5-11e7-874c-84e69c1054a9.png">

## Environment data
`dotnet --info` output:

```text
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

_Copied from original issue: dotnet/cli#6296_

**Comment by mechdeveloper** [comment]
I have docker setup on windows server 2016, I am also using HTTP_PROXY environment variable for docker to be able to pull images.

I also have an asp.net core 2.1 api, i am trying to build an image using docker file which fails with following error
`docker build -t testuser/testwebapi .`
Step 12/21 : RUN dotnet restore "TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj"
 ---> Running in 8a33a98d75cd
  Restoring packages for C:\src\TestProject.TP1.DataAccess.TestAPI\TestProject.TP1.DataAccess.TestAPI.csproj...
  Restoring packages for C:\src\TestProject.TP1.Business\TestProject.TP1.Business.csproj...
  Generating MSBuild file C:\src\TestProject.TP1.DataAccess.TestAPI\obj\TestProject.TP1.DataAccess.TestAPI.csproj.nuget.g.props.
  Generating MSBuild file C:\src\TestProject.TP1.DataAccess.TestAPI\obj\TestProject.TP1.DataAccess.TestAPI.csproj.nuget.g.targets.
  Restore completed in 716.64 ms for C:\src\TestProject.TP1.DataAccess.TestAPI\TestProject.TP1.DataAccess.TestAPI.csproj.
  Restoring packages for C:\src\TestProject.TP1.DataAccess.Repo\TestProject.TP1.DataAccess.Repo.csproj...
C:\Program Files\dotnet\sdk\2.1.503\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\src\TestProject.TP1.WebApi\TestProject.TP1.WebApi.csproj]
C:\Program Files\dotnet\sdk\2.1.503\NuGet.targets(114,5): error :   A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failedto respond [C:\src\TestProject.TP1.WebApi\TestProject.TP1.WebApi.csproj]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore "TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj"' returned a non-zero code: 1

To fix the connection issue as per error above, I tried to provide env variable while trying to build the docker image -
`docker build --build-arg http_proxy=http://xx.xx.xx.xx:pp -t testuser/testwebapi .`
Now docker build fails with following error -
Unable to load the service index for source https://api.nuget.org/v3/index.json.

The SSL connection could not be established, see inner exception.

The remote certificate is invalid according to the validation procedure.

Step 14/23 : RUN dotnet restore "TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj"
 ---> Running in 9062e2096749
  Restoring packages for C:\src\TestProject.TP1.DataAccess.TestAPI\TestProject.TP1.DataAccess.TestAPI.csproj...
  Restoring packages for C:\src\TestProject.TP1.Business\TestProject.TP1.Business.csproj...
  Generating MSBuild file C:\src\TestProject.TP1.DataAccess.TestAPI\obj\TestProject.TP1.DataAccess.TestAPI.csproj.nuget.g.props.
  Generating MSBuild file C:\src\TestProject.TP1.DataAccess.TestAPI\obj\TestProject.TP1.DataAccess.TestAPI.csproj.nuget.g.targets.
  Restore completed in 562.16 ms for C:\src\TestProject.TP1.DataAccess.TestAPI\TestProject.TP1.DataAccess.TestAPI.csproj.
  Restoring packages for C:\src\TestProject.TP1.DataAccess.Repo\TestProject.TP1.DataAccess.Repo.csproj...C:\Program Files\dotnet\sdk\2.1.503\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\src\TestProject.TP1.WebApi\TestProject.TP1.WebApi.csproj]
C:\Program Files\dotnet\sdk\2.1.503\NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [C:\src\TestProject.TP1.WebApi\TestProject.TP1.WebApi.csproj]
C:\Program Files\dotnet\sdk\2.1.503\NuGet.targets(114,5): error :   The remote certificate is invalid according to the validation procedure. [C:\src\TestProject.TP1.WebApi\TestProject.TP1.WebApi.csproj]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore "TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj"' returned a non-zero code: 1

**Not really sure how to fix this problem with dotnet restore.** Need help to continue further.


Docker file
```
#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-sac2016 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk-nanoserver-sac2016 AS build
WORKDIR /src

COPY ["TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj", "TestProject.TP1.WebApi/"]
COPY ["TestProject.TP1.Business/TestProject.TP1.Business.csproj", "TestProject.TP1.Business/"]
COPY ["TestProject.TP1.DataAccess/TestProject.TP1.DataAccess.csproj", "TestProject.TP1.DataAccess/"]
COPY ["TestProject.TP1.DataAccess.TestAPI/TestProject.TP1.DataAccess.TestAPI.csproj", "TestProject.TP1.DataAccess.TestAPI/"]
COPY ["TestProject.TP1.DomainModels/TestProject.TP1.DomainModels.csproj", "TestProject.TP1.DomainModels/"]
COPY ["TestProject.TP1.DataAccess.Repo/TestProject.TP1.DataAccess.Repo.csproj", "TestProject.TP1.DataAccess.Repo/"]
RUN dotnet restore "TestProject.TP1.WebApi/TestProject.TP1.WebApi.csproj"
COPY . .
WORKDIR "/src/TestProject.TP1.WebApi"
RUN dotnet build "TestProject.TP1.WebApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TestProject.TP1.WebApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestProject.TP1.WebApi.dll"]

```

**Comment by nkolev92** [comment]
The original issue is a permissions issue. 
The obj folder is not owned by the docker process so NuGet can't write there. 

@mechdeveloper 

The error you are hitting seems to be a generic one. At this point if you are still hitting this problem, it might be helpful if you can file a new issue. 

Closing.
