### ISSUE TITLE
Creat Windows 8.1  Universal App/Azure Mobile Service, "Microsoft.ServiceBus" reference could not found.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#502]
Repro steps:

First scenario:
1.New Project -> C# ->Web->asp.net Web Application->Azure Mobile Service.
2.Expand References and yellow warning signs adjacent to "Microsoft.ServiceBus".
3.Right click the Microsoft.ServiceBus reference to show properties, the path is empty. 

Sceond scenario:
1.New Project->Visual C#->Windows 8.1  Universal Blank App/Hub App
2.Right-click on the References node and select "Add Connected Service"
3.Choose Azure Mobile Services and click Configure.
4.Create new Mobile Services and click Add.
5.Wait complete ,meet the error dialog click OK. 
6.Expand  References(Which project is add Mobile Services name),meet yellow warning.
7.Right click the "Microsoft.ServiceBus" reference to show properties, the path is empty. 

Repro build: D14Rel 22823.01, Main 22827.01,Main 22828.01, WPT 22828.00
![bus](https://cloud.githubusercontent.com/assets/12129698/7384103/419da200-ee5e-11e4-91f3-f4f55b961b1f.png)
![errorlist](https://cloud.githubusercontent.com/assets/12129698/7384104/495dfef4-ee5e-11e4-9bdb-10e27f01a813.png)

**Comment by deepakaravindr** [comment]
@AndriySvyryd Can you please try this?

**Comment by deepakaravindr** [comment]
@danliu , assigning to Dan for verification

**Comment by AndriySvyryd** [comment]
The first error appears because MobileServicesApplicationv1.0\MobileServicesApplication.csproj contains a reference to "Microsoft.ServiceBus.dll" named "WindowsAzure.ServiceBus", it should be renamed to "Microsoft.ServiceBus". Same applies to MobileServicesApplication.vbproj

A similar error is also present in the code that handles "Add Connected Service" for Azure Mobile Services.
