### ISSUE TITLE
Configuring PackageReference version when installing/updating packages through VisualStudio 2017 UI to be consistent with Semantic Versioning

### ISSUE THREAD

**Issue by eroller** [NuGet/Home#5029]
The .csproj PackageReference attribute has support for floating versions and version ranges which is a very nice feature, but when installing or updating packages through the Visual Studio UI we only get one behavior, for example:

`<PackageReference Include="Newtonsoft.Json" Version="9.0.1" />`

Which means allow any version >= 9.0.1 preferring the lowest. It would be nice to allow configuring this to be consistent with semantic versioning where I would typically want to allow the highest version with the same major version number, for example:

`<PackageReference Include="Newtonsoft.Json" Version="[9.0.1,10.0.0)" />`

If there were some Nuget.config attribute to make this the default that would be awesome. I know I can do this with the dotnet add package command, but using the UI is much nicer as I can browse the available package versions. Also having nuget automatically calculate the next major version number would be very convenient.

**Comment by ghost** [comment]
Due to lack of recent activity, this issue has been marked as a candidate for icebox cleanup. It will be closed if no further activity occurs within 14 more days. Any new comment (by anyone, not necessarily the author) will add a `Triage:NeedsTriageDiscussion` label and lead to a triaging process.
This process is part of the experimental [Stale icebox issues cleanup](https://github.com/NuGet/Home/issues/12113) we are currently trialing. Please share any feedback you might have in the linked issue.
