### ISSUE TITLE
Add Manage NuGet packages to context menu for NuGet node

### ISSUE THREAD

**Issue by sayedihashimi** [NuGet/Home#5049]
Any reason why we don't have "Manage NuGet packages" for the NuGet node under Dependencies?

Note: screenshot taken from an asp.net core project.

![image](https://cloud.githubusercontent.com/assets/1283154/25110986/f8b337dc-239c-11e7-8d24-ce4bf9ae7505.png)

**Comment by emgarten** [comment]
Adding the NuGet UI menu item to the NuGet node sounds like a good idea to me.

**Comment by mishra14** [comment]
This seems reasonable. We should improve the UI around this.

**Comment by donnie-msft** [comment]
These options were made available in Release 16.4 Preview 2 in Sprint 159 from [this PR](https://github.com/dotnet/project-system/pull/5538) which merged September 19 2019.

This work was initially thought to be more complex, and require a new NuGet [IProjectItemContextMenuProvider](https://github.com/microsoft/VSProjectSystem/blob/master/doc/extensibility/IProjectItemContextMenuProvider.md), which I had as a work-in-progress, but Project System has since decided this is not necessary for NuGet to inject. Project System also modified the IDs they were using, which changed the menu on the Packages node (formerly, NuGet node).
