### ISSUE TITLE
nuget.exe update doesn't update path in .csproj ItemGroup/Analyzer/@Include

### ISSUE THREAD

**Issue by GlenAppleton** [NuGet/Home#5100]
nuget.exe version : 3.5.0.1938

**Steps:**

1) Add a reference to Microsoft.CodeAnalysis.Analyzers.1.0.0 to your C# project and save the changes.
2) Run the command line:  nuget update [path to packages.config]\packages.config -id Microsoft.CodeAnalysis.Analyzers -version 1.1.0 -fileconflictaction ignore -noninteractive -source "nuget.org"
 
**Result:**

The packages.config file will be updated with the new version of the analyzer package, but the .csproj file will still show the old path to the previous package version in the ItemGroup/Analyzer list.

**Comment by emgarten** [comment]
NuGet doesn't directly add analyzers to projects. Taking a look at ``Microsoft.CodeAnalysis.Analyzers 1.0.0`` I see that install.ps1 and uninstall.ps1 are used to modify the project through Visual Studio.

NuGet.exe update isn't able to run install.ps1 since it requires access to the project in Visual Studio to perform the updates.

You will need to update this package through Visual Studio to fully update the analyzers.
