### ISSUE TITLE
NuGet Pack does not translate floating version correctly

### ISSUE THREAD

**Issue by JoGillis** [NuGet/Home#5150]
NuGet.exe 4.1.0.2450

When using a floating version in a nuspec file it is incorrectly translated into the package:
for example in the nuspec file:
```
    <dependencies>
        <dependency id="ABCD" version="1.0.1.*" />
    </dependencies>
```
Will result in the following entry inside the nupkg file, without any warning or error
```
        <dependencies>
            <dependency id="ABCD" version="1.0.1" />
        </dependencies>
```
This is clearly wrong, because they have a completely different meaning. 

A correct way to handle this could be:
1- (not preferred) Issue an error saying 'not supported' (A warning seems not enough because of the different meaning)
2- support the floating version in the nupkg file, this would also solve several other issues regarding CI posted here

**Comment by nkolev92** [comment]
Related https://github.com/NuGet/Home/issues/6848. 

At this point, this is by design.
NuGet has historically been against allowing author driven package resolution, and we believe that is the right approach given the state of the eco-system. 

We'll of course be happy to reevaluate if/when appropriate.
