### ISSUE TITLE
Transitive build assets not excluded when dependency marked as PrivateAssets="Build"

### ISSUE THREAD

**Issue by JunTaoLuo** [NuGet/Home#5233]
While trying to work around https://github.com/dotnet/sdk/issues/1166, we ran into a problem excluding build assets from dependencies. 

The dependency `sqlitepclraw.lib.e_sqlite3.{osx|linux|v110_xp}` contains .target files (which in this case are only applicable to apps targeting .NET Framework) that we would like to exclude when a project reference it transitively from Microsoft.AspNetCore.All (which is currently a .NET Core only library). To work around the issue we marked these dependencies with `PrivateAssets="Build"`. However, when I run a dotnet restore I still see the following in the *.csproj.nuget.g.targets file:
```
<Import Project="$(NuGetPackageRoot)sqlitepclraw.lib.e_sqlite3.v110_xp\1.1.5\build\net35\SQLitePCLRaw.lib.e_sqlite3.v110_xp.targets" Condition="Exists('$(NuGetPackageRoot)sqlitepclraw.lib.e_sqlite3.v110_xp\1.1.5\build\net35\SQLitePCLRaw.lib.e_sqlite3.v110_xp.targets')" />
```
I also noticed that the .nuspec of the Microsoft.AspNetCore.All package contains:
```
        <dependency id="sqlitepclraw.lib.e_sqlite3.v110_xp" version="1.1.5" include="Runtime,Compile,Native,ContentFiles,Analyzers" />
        <dependency id="sqlitepclraw.lib.e_sqlite3.osx" version="1.1.5" include="Runtime,Compile,Native,ContentFiles,Analyzers" />
        <dependency id="sqlitepclraw.lib.e_sqlite3.linux" version="1.1.5" include="Runtime,Compile,Native,ContentFiles,Analyzers" />
```

As a result the target files which we tried to exclude are still being included and affects our publishing step. Is using `PrivateAssets="Build"` the correct way to work around the sdk issue and if so why does it not work in this case?

## Versions

using dotnet.exe

NuGet version (x.x.x.xxx): 
dotnet nuget --version
NuGet Command Line
4.3.0.0

dotnet.exe --version:
2.0.0-preview2-006071

OS version (i.e. win10 v1607 (14393.321)):
Win 10 15063.250

## Detailed repro steps so we can see the same problem

1. clone github.com:JunTaoLuo/NugetTargets

2. dotnet restore

### Sample Project

I have included a repro here: https://github.com/JunTaoLuo/NugetTargets.

cc @natemcmaster

**Comment by emgarten** [comment]
Other packages reference build assets from the ``sqlitepclraw.lib.e_sqlite3.*`` packages which pulls them in. You will need to exclude build assets for each dependency they are flowing up through.

I see these dependencies that need to have build excluded, there could be others also:
* SQLitePCLRaw.bundle_green
* Microsoft.Data.Sqlite
* Microsoft.EntityFrameworkCore.Sqlite

With including/excluding assets nearest wins doesn't apply, any package that depends on certain assets from a package will get them.

``PrivateAssets=build`` works, at pack time it is converted into ``Exclude=build`` since there is no concept of private assets/build time dependencies for something after it has been built.

**Comment by mishra14** [comment]
This should be fixed/ByDesign with work done for ATF. Please let us know if this is still a problem.
