### ISSUE TITLE
NuGet restore should check local cache before going online to fetch packages

### ISSUE THREAD

**Issue by pierceboggan** [NuGet/Home#5246]
## Details about Problem

NuGet should first check the local cache on the machine for the package before going online to attempt to resolve the package. Right now, a simple NuGet restore is taking a few minutes for me, even though _all_ packages are locally on my machine (and are the correctly versioned).

As the number of packages in a solution grow (especially if you are referencing packages that use .NET Standard), this optimization would save developers lots of time as they wait for things to restore which are already locally in the cache.

NuGet product used: VS UI
NuGet version: 4.0.0.2323
VS: Visual Studio for Mac 1.0
OS Version: macOS 10.12.4

**Comment by anangaur** [comment]
@emgarten Isn't this the current behavior already? My understanding is that unless you have floating versions (like "1.*"), the resolution happens in the following order:
1. Local NuGet caches, FallBack folders
2. Local NuGet feed
3. Rest of the feeds

I think there is a check to see if all the feeds are available or not? This is a separate topic though whether this check should happen everytime vs. in specific cases only.

**Comment by emgarten** [comment]
@anangaur exactly right, restore tries really hard not to go online. Floating is the exception there, and also when there is no exact match (downward floating) such as when package A depends on B >= 1.0.0 and only B 2.0.0 exists.

**Comment by anangaur** [comment]
@pierceboggan Does any of the exceptions discussed above match your package dependencies?

**Comment by mrward** [comment]
This might be a VS for Mac implementation problem then - I need to do some more investigation.

In this particular case a restore is not being run but instead an install of the NuGet packages is run when a new project is created. When you do an install and not a restore then the online package source is checked. The project templates do not use floating versions.

This particular project template does not ship the NuGet packages itself, which other templates do. However this becomes more complicated if the NuGet packages reference a .NET Standard package, since we do not want to ship the entire .NET Core sdk NuGet packages with our project templates.
