### ISSUE TITLE
NuGet restore is too slow with VS 2017 15.3 preview1

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5257]
As reported on twitter:
https://twitter.com/pelleadri/status/865679776731627524

![image](https://cloud.githubusercontent.com/assets/14800916/26271017/8bc54b56-3cb5-11e7-95cb-f1ec7df738ca.png)

**Comment by pellea** [comment]
It's the fastest on .NET core project. But in WPF or UWP project that's another story.
Removing the previously mentioned source from nuget packages sources made the trick.

**Comment by xavierdecoster** [comment]
Is there any actual proof of this package source being slow? Do you have any request traces that highlight this slowness, and would you be able to share these? 

You could use the `-Verbose` switch in the NuGet Package Manager Console to have it print out HTTP requests and the time it took for the client to receive a response. 

cc @maartenba

**Comment by pellea** [comment]
![image](https://cloud.githubusercontent.com/assets/395982/26296810/a2f079e6-3ed0-11e7-99ca-7bb92ab48472.png)

**Comment by xavierdecoster** [comment]
@pellea Thanks! Missed that conversation. 

Cleanup on the `dotnet-core` feed should indeed have a significant positive impact on dependency resolution time.

This to me is not an indicator of _package source_ slowness, however, and may be inherent to the current dependency resolution protocol. Maybe @emgarten can shed more light on this?

**Comment by pellea** [comment]
Why the resolver needs to build dependency graph every times? 
@anangaur mentioned some cache. I don't think it's working properly for building the dependency graph or I would have the problem only the first time (and that's not the case).

**Comment by jainaashish** [comment]
there isn't any cache for building the dependency graph, it happens at each time, since there could be any change at any given feed, so we always need to compute dependency graph. There is packages cache, which is used to skip downloading packages if already exists on the machine, but package's metadata is always downloaded to build dependency graph.

So, if there are too many versions of packages on a feed, then it will slow down the resolver. For now, avoiding that feed should work until the feed is cleaned up or the package is published on nuget.org

**Comment by emgarten** [comment]
@rohit21agrawal was hitting this also, it was taking a very long time when installing packages. After removing the myget feeds and having just NuGet.org as the source things resolved very quickly.

There has been a lot of work done on the client side of this already to optimize things. The issue is that the client needs to know all versions of a package available before it can find the best solution, so if there are 200 possible dependencies or so then each feeds needs to be checked. The client will immediately start calls to each feed once it discovers a new dependency id from any feed to reduce the waterfall impact here, but when a source is slow just making all of the the calls takes a long time,

👍 on more caching, it would be helpful. There are few other things that could be done to optimistically try to resolve less packages and see if things work. This would improve the best case scenario but make the worst case much slower.

I think the best option going forward is to use *PackageReference* which resolves packages differently and already has caching.

**Comment by anangaur** [comment]
@livarcocc, Can the `dotnet-core` myget feed be cleaned up or the relevant version(s) moved to NuGet.org?

**Comment by mishra14** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
