### ISSUE TITLE
Provide a mechanism to opt into legacy project system mode

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#5277]
The following are the [only cases where the CPS behavior](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/CpsPackageReferenceProjectProvider.cs#L80-L96) can be skipped and fall back to legacy:

* `RestoreProjectStyle != PackageReference`
* `TargetFramework && TargetFramework == ''`

For NuGetizer, we are in a tough spot where we really can't avoid either. We need PackageReference (don't want to fall back to packages.config, and project.json is out of the question), and a combination of `TargetFramework` + `PackageTargetsFallback` allows us to restore/build on CI. 

So, we're in a situation where we really need a third mechanism to tell that provider that we don't want it to apply to our project system. One option would be to flip the provider order and have the legacy one evaluate first, another would be for it to evaluate another property from the project to determine if it should apply (i.e. `LegacyProjectSystem=true` or whatever).

The way we worked around this is by having the authoring/project system targets clear out the TargetFramework property. CI will see the TF because the authoring isn't imported in that case.

But it would be good to have it explicitly supported.

**Comment by ghost** [comment]
Due to lack of recent activity, this issue has been marked as a candidate for icebox cleanup. It will be closed if no further activity occurs within 14 more days. Any new comment (by anyone, not necessarily the author) will add a `Triage:NeedsTriageDiscussion` label and lead to a triaging process.
This process is part of the experimental [Stale icebox issues cleanup](https://github.com/NuGet/Home/issues/12113) we are currently trialing. Please share any feedback you might have in the linked issue.
