### ISSUE TITLE
Honor WarningsNotAsErrors

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#5375]
We use TreatWarningsAsErrors=true. We want NuGet warnings to appear, but not to fail build. The concept of NoWarn is too strong as it suppresses them completely, but we still want to be aware of the issue. IMO the best property for this (that CSC also uses) is WarningsNotAsErrors, a list of warnings that should not cause errors even if TreatWarningsAsErrors is enabled.

Scenario:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Moq" Version="4.7.1" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>netcoreapp2.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>$(WarningsNotAsErrors);NU1603</WarningsNotAsErrors>
	</PropertyGroup>
</Project>
```

cc @emgarten

**Comment by anangaur** [comment]
@natemcmaster I am just wondering, why is this not exposed in the UI. IMO this would be the common scenario. Users will start with treating all warnings as errors and then as they understand the warnings from their project, either suppress them completely (possible in UI by "Suppress warnings" OR list them as warnings not treated as errors (WarningsNotAsErrors). May be in the properties UI we should have an option under `Treat warnings as errors`: 
`All except <Textbox>`

Current properties UI for reference:
![image](https://user-images.githubusercontent.com/14800916/26953648-8b8f9a50-4c60-11e7-85f0-b96c2d48fbc6.png)

**Comment by natemcmaster** [comment]
+1 Would be cool if the VS folks could expose this in UI. This property has been a well-known option in the compiler for years. (see [Microsoft.CSharp.Core.targets](https://github.com/dotnet/roslyn/blob/6a98a959cbd296991411e3e9d124aeeb4827ae1f/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L150))

**Comment by natemcmaster** [comment]
Requested: https://github.com/dotnet/project-system/issues/2409

**Comment by mishra14** [comment]
Tagging @rrelyea for triage request.

**Comment by mishra14** [comment]
Closing as there has been no customer traction on this.

**Comment by mishra14** [comment]
Received another request. Reopening this issue for future.

**Comment by rizi** [comment]
Any update on this, it would be great if WarningsNotAsErrors a honored by NuGet.

**Comment by sadjadbp** [comment]
For now I'm using in PropertyGroup

`<NoWarn>NU1701</NoWarn>`

specified [here](https://github.com/NuGet/Home/wiki/NuGet-Errors-and-Warnings)

or better yet transitive warning properties explained [here](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Transitive-Warning-Properties)

**Comment by julealgon** [comment]
When will this be fixed? There is currently no way to temporarily handle a Nuget problem as a warning if you have `TreatWarningsAsErrors`. We don't want to completely disable the warning as it is valid and needs to be fixed eventually, however we can't do it while ensuring other warnings aren't introduced in our project.

This has been opened in 2017 and nuget respects every other common MSBuild property related to warnings. The fact that it completely ignores `WarningsNotAsErrors` is baffling to say the least.

**Comment by nick-beer** [comment]
Here to agree that that this seems like a significant gap.  Many of our builds were just hit with [`NU1803`](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803) with the most recent dotnet SDK (6.0.400), and we don't have any choice but to `NoWarn` it.  We have plans to update our servers, but that work can't be done any time soon.  I'm sure the point of the `NU1803` warning is to remind people that support for HTTP servers is going away, but that's a warning we'll never see because we have to `NoWarn` it.

**Comment by DanJBower** [comment]
Why are NuGet warnings not included `WarningsNotAsErrors`? I'm getting a `NU5104` failing my build even though it is in `WarningsNotAsErrors`

**Comment by nkolev92** [comment]
Adding a Pack label in addition to a restore one, as it's best if functionality is made available in both commands.

**Comment by nkolev92** [comment]
Hey folks, we have a proposal out:https://github.com/NuGet/Home/pull/12134.

**Comment by julealgon** [comment]
@nkolev92 can you let us know when this will become available for use? Will it be included as part of the next VS update?

I'm explicitly asking here since the "Releases" section in this repository is unreliable and can't be used for notification purposes (last published release there was several years ago and does not correspond with actual latest).

**Comment by nkolev92** [comment]
@julealgon 

We'll update the milestone, but it'll for sure VS 17.5, .NET SDK 7.0.200 and NuGet.exe 6.5, which all ship early next year. We don't use the releases since we don't distribute our tooling through GH.

The release notes always contain the exact list of changes within a release: https://learn.microsoft.com/en-us/nuget/release-notes/.
