### ISSUE TITLE
Error occurred while restoring NuGet packages: Value cannot be null -- 15.3 p2 & netcore sdk 2.0 p1

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#5390]
VS 2017 15.3 Preview 2 + NetCore SDK 2.0 preview 1

My .NET Core 2.0 environment is still working from the command line. I can use the command line to create new projects. Opening existing .NET Core 2.0 projects is also ok. However, building the project I see this error in the Output window: “Error occurred while restoring NuGet packages: Value cannot be null”. dotnet restore from the command line is ok. After this, I can compile the existing project with Visual Studio 2017 Update 3.

**Comment by christiannagel** [comment]
Creating a new .NET Core 2 project using the command line, I can open and build the project using Visual Studio 2017 Update 3 Preview 2 running on Windows 10 insider build 16215.
> dotnet new console
Open the project and build it is ok.
I think this works because with the new version of dotnet new, dotnet restore is already included.
If the project files are retrieved from a repository without the project.assets.json file, I get this error trying to build the project from Visual Studio:
Error occurred while restoring NuGet packages: Value cannot be null.
Parameter name: eventId
Error occurred while restoring NuGet packages: The operation failed as details for project PipesWriter could not be loaded.
Error occurred while restoring NuGet packages: Value cannot be null.
Parameter name: eventId

With dotnet restore from the command line, and compiling the project from Visual Studio later on, everything is ok again.

I think this is related to this problem:
https://developercommunity.visualstudio.com/content/problem/67355/new-project-menu-fails-with-error-value-cannot-be.html
It's also value cannot be null with the same parameter name: eventId

**Comment by rrelyea** [comment]
That developer community item says this is addressed in 15.3 Preview 3. Please confirm.

**Comment by rohit21agrawal** [comment]
yes, looks like it works in preview 3.
