### ISSUE TITLE
Packaging a web application fails silently

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5436]
_From @CoskunSunali on June 16, 2017 11:23_

The scenario I am falling into requires me to develop plugins for a .NET Core web app. The plugins are standard NuGet packages. Some of the plugins require plenty of web related stuff and thus the plugin project's SDK is of type `Microsoft.NET.Sdk.Web`. It is also required to use the Web SDK in order to take advantage of Razor related stuff in Visual Studio (highlighting, intellisense, etc). - There was a bug somewhere tracking that issue but I had no luck finding it.

It seems that NuGet packages are not being generated for projects using the Web SDK.

Is this the result expected? If not, are you able to provide a workaround?

## Steps to reproduce

1. Create a web app using .NET Core 2.0 Preview 1 (no further modifications needed to reproduce)
2. Right click the project and click "Package" or proceed to the folder containing the `csproj` file and execute command `dotnet pack`.

## Expected  behavior

NuGet package generated at `.\bin\Debug`

## Actual behavior

No NuGet packages are generated. The `dotnet pack` command produces the following output.

```
C:\Users\Coskun\Documents\Visual Studio 2017\Projects\WebApplication1\WebApplication1>dotnet pack
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\Coskun\Documents\Visual Studio 2017\Projects\WebApplication1\WebApplication1>
```

## Environment data
`dotnet --info` output:

```
C:\WINDOWS\system32>dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

_Copied from original issue: dotnet/cli#6904_

**Comment by smartcaveman** [comment]
I'm running into the same issue.  The only difference is that my preview version is: 2.0.0-preview2-006497.

It is worth noting that removing the `.Web` from the `Sdk` attribute will result in the NuGet file being generated on build.

**Comment by smartcaveman** [comment]
So, I figured this one out.  Details are below, I hope this helps someone else:

- NuGet is exhibiting correct behavior.

- The MSBuild configuration that ships with .NET Core 2.0 Preview disables NuGet packaging for any projects using the `Microsoft.NET.Sdk.Web` project.

- It's reasonable to assume that this is actually not a bug but is an intentional safeguard against packaging web applications with prerelease dependencies.

- The solution is to override the default configuration to disable packaging web applications.  This can be accomplished easily in both the project or global scope.

Project Level Solution
------------------------
- This solution will fix NuGet generation for a single project.
- Add the `IsPackable` property to the web application's `.csproj` with a value of `true`.
- The `csproj` file from my working example of the project-level fix looks like this:
```
    <Project Sdk="Microsoft.NET.Sdk.Web" ToolsVersion="15.0">
      <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
        <IsPackable>true</IsPackable>
        ...
```

SDK-Level Solution
---------------------
- This solution will fix NuGet generation for all projects using the .NET 2.0 / VS 2017 preview.
- Change the `IsPackable` property in the `Microsoft.NET.Sdk.Web.ProjectSystem.props` file of the .NET Core 2.0 Preview installation.
- On my machine, this property was defined on Line 23 of `C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\Microsoft.NET.Sdk.Web.ProjectSystem\build\netstandard1.0\Microsoft.NET.Sdk.Web.ProjectSystem.props` as:
```
    <IsPackable Condition="'$(IsPackable)' == ''">false</IsPackable>
```
- After applying the solution-level fix, Line 23 looks like:
```
    <IsPackable Condition="'$(IsPackable)' == ''">true</IsPackable>
```

**Comment by rohit21agrawal** [comment]
This issue was moved to aspnet/websdk#228
