### ISSUE TITLE
Problem using NuGetizer3000 | Nugget CLI Area:NuGetizer

### ISSUE THREAD

**Issue by mateuszkozlik** [NuGet/Home#5507]
NuGet product used (NuGet.exe | NuGetizer 3000 for VS2017)
NuGet version (4.1.0 | 0.1.324)
VS version: 2017 Enterpise

I'm trying to create NuGet package using CLI and NuGetizer3000 from PCL project. But when I'm trying to add it (the package) to iOS or Droid project, following errors occur:

> Could not install package 'MyPackage 1.0.0'. You are trying to intall this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatibile with that framework...

Same problem with iOS but instead Mono there is Xamarin.iOS

The PCL I'm doing it from targets Xamain.iOS, Xamarin.Android... 

How can I fix it, so the problem dissapears?

**Comment by kzu** [comment]
That looks like a nuget package authoring error. Does your package provide a compatible library that can target XA? Did you inspect the resulting .nupkg to see what's in the `lib` folder?

It may be that the PCL profile selected for the library isn't compatible with XA. You should check that first.

Also, I strongly suggest you move the PCL to NETStandard instead, since PCLs are effectively deprecated.

Alternatively, could you provide the .nupkg so I can take a look at it?

Thanks

**Comment by mateuszkozlik** [comment]
Sorry for this issue. I was making my first steps into programming in C#. It was my bad creating inappropriate .nuspec and what concludes .nupkg
