### ISSUE TITLE
Unable to find package X with version (>= 1.0.0)

### ISSUE THREAD

**Issue by Petermarcu** [NuGet/Home#5522]
## Details about Problem

I'm trying to add a reference to a package that has a version of 0.0.1 on Nuget.org. https://www.nuget.org/packages/Bifrost.Devices.Gpio/

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

## Detailed repro steps so we can see the same problem

Simply try to restore this project.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bifrost.Devices.Gpio" Version="0.0.1" />
  </ItemGroup>

</Project>
```
Let me know if you need more details...

**Comment by Petermarcu** [comment]
Looks like I was able to get it to work by listing all the dependencies explicitly:

```
    <PackageReference Include="Bifrost.Devices.Gpio" Version="0.0.2" />
    <PackageReference Include="Bifrost.Devices.Gpio.Abstractions" Version="0.0.1" />
    <PackageReference Include="Bifrost.Devices.Gpio.Core" Version="0.0.1" />
```

I don't think this is supposed to be required.

**Comment by mishra14** [comment]
@Petermarcu It seems that the package `Bifrost.Devices.Gpio` has a dependency on the following - 

[Bifrost.Devices.Gpio.Abstractions (>= 1.0.0)](https://www.nuget.org/packages/Bifrost.Devices.Gpio.Abstractions/)
[Bifrost.Devices.Gpio.Core (>= 1.0.0)](https://www.nuget.org/packages/Bifrost.Devices.Gpio.Core/)

But if you look at these packages on nuget.org you will see that they do not have any version higher than 0.0.1. Since you are asking for `version >= 1.0.0` the constraint is not met.
