### ISSUE TITLE
https://nuget.org/nuget.exe is not signed

### ISSUE THREAD

**Issue by dannyvv** [NuGet/Home#559]
The nuget.exe file on nuget.org is currently not signed.

Attribute | Data
------------ | -------------
Url|https://nuget.org/nuget.exe 
dd|May 9th 2015 19:22 PST
SHA256|6E0455BBAE41F117C22B080988C48240E58448D7B5583659AFBA2B7873F3DF39
FileVersion|2.8.60318.667

The result is when downloaded through browser (in my case IE11) Users get a prompt the file is not trust-worty.
The last paragraph at the bottom of http://docs.nuget.org/consume/installing-nuget mentions that it should be expected to be signed.

**Comment by feiling** [comment]
There is a signed exe on http://nuget.codeplex.com/releases

**Comment by yishaigalatzer** [comment]
@dannyvv looks like we are not signing `nuget.exe` explicitly because nuget.org is not a Microsoft product. Like @feiling is suggesting we ship a Microsoft product on codeplex.

We are working through the legalities of what it means (and if at all possible) signing the nuget.exe shipping in nuget.org.

**Comment by csharpfritz** [comment]
nuget.exe updated on nuget.org/nuget.exe
