### ISSUE TITLE
NuGet.Client does not have an issue tracker

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5600]
* The [NuGet.Client](https://github.com/NuGet/NuGet.Client) repository does not have an issue tracker
* The readme for the above repository does not point users to an issue tracker in an alternate location

**Comment by eriawan** [comment]
@emgarten 

Pardon, marking this issue as `Up for Grabs` would be wrong and misleading, because people outside Nuget.Client internal member won't be able to participate. 
For example: I'm not a Microsoft employee and also not part of Nuget.Client repo members (hence I don't have the rights to add issue tracking), so I won't be able to grab this issue at all.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/2150. 

@eriawan 

NuGet.Client uses Nuget/Home for issue tracking.

The reason why it was marked up for grabs is because it's only a docs issue.
