### ISSUE TITLE
Optimize Figuring out if package has an update

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#561]
Right now the code relies on downloading all the package versions from the remote repository, and then checks fox Max. The call is very expensive and unnecessary according to @emgarten 

After the changes I'm making this will have low impact for All and Installed filters, but is still expensive for Update available filter. 

Fixing this will save multiple network calls (once per displayed package in the list) and simplify the code quite a bit.

**Comment by csharpfritz** [comment]
Can we also have a fallback scenario if the network isn't present?  I was
working on a plane with no network connection and just wanted my local
versions of packages from my .DNX folder installed.

**Comment by yishaigalatzer** [comment]
@csharpfritz please open a separate bug. The work around is to add your local folder to the feed when the network is down for now.

**Comment by yishaigalatzer** [comment]
@feiling please consider this a part of optimizing update tab (but also look at update-package command). If this is already covered, please resolve/close

**Comment by johnataylor** [comment]
There are a few things to consider for 3.5.

We have discussed publishing resource called "latest." Alternatively fetch the version list from "flat" container and work out the latest from that. It's unfortunate that there are two alternative protocols for the exact same data but toggling between these existing two might be better than introducing a third as its impossible to deprecate either having shipped. Having done that we could also add details to the package version specific resource - currently they only have links to details.

However, another alternative would be to add the ability to the search endpoint. Specifically allow the search endpoint to accept multiple packageid: in the command line. _This would be fast and inline with the original architectural goal to drive the interactive user experience exclusively from the highly responsive search endpoint rather than the current behavior of toggling between different resources many of which duplicate data._ This would be a very small change to the search endpoint. (And that service has already done all the work to get this data ready in memory.)

**Comment by johnataylor** [comment]
Also note the data in 3.4 is reduced by about 80% through gzip compression. The number of http calls remains high, however, the best fix there is to do the fix to the search endpoint as described above.

Moving this to 3.5.

**Comment by rohit21agrawal** [comment]
if we receive more feedback about pef problems in this area, we will open a separate bug.
