### ISSUE TITLE
dotnet restore does not restore older packages

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5623]
_From @nalla on July 20, 2017 8:32_

## Steps to reproduce
~~~bash
mkdir foo
cd foo
dotnet new classlib --framework netstandard1.0
(gc .\foo.csproj).replace('netstandard1.0', 'net40') | sc .\foo.csproj
(gc .\foo.csproj) -replace "\<\/PropertyGroup\>", "$&`n<ItemGroup>`n<PackageReference Include=`"Common.Logging`" Version=`"1.2.0`" />`n</ItemGroup>" | sc .\foo.csproj
dotnet restore
~~~

## Expected  behavior
Restore completes

## Actual behavior
Restore fails, complaining about incompatible framework versions (Possible due to the file layout of the package). But the same package can be used in the old `packages.config` way without problems.
~~~
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package Common.Logging 1.2.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Common.Logging 1.2.0 supports: 10 (1.0,Version=v0.0) [C:\Users\MBlanquett\foo\foo.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETFramework,Version=v4.0. [C:\Users\MBlanquett\foo\foo.csproj]
~~~

## Environment data
`dotnet --info` output:
~~~
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
~~~

_Copied from original issue: dotnet/cli#7202_

**Comment by livarcocc** [comment]
_From @davidfowl on July 20, 2017 9:35_

@emgarten Older versions of nuget used to infer a number without a TFM as .NET Framework (super bad). Do you know if this is still supported?

**Comment by emgarten** [comment]
Commonly used numeric folder names are still supported, but they must be in a list of allowed frameworks so that new packages have to switch to support newer frameworks. 

It looks like Common.Logging is using `1.0` which isn't in the allowed list. I know that the original allow list was created based on nuget.org packages, my guess is that `1.0` is probably only used in this package and didn't make it into the list.

Given how old 1.2.0 is and that there are newer versions of this package that support netstandard I think the fix here is to update the package.

Note that both packages.config and PackageReference use the same framework parsing, this isn't related to NETCore projects. The original change was made in NuGet 3.0.0 for VS 2015.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/NuGetFrameworkFactory.cs#L259-L276
