### ISSUE TITLE
Configuring framework selection

### ISSUE THREAD

**Issue by godrose** [NuGet/Home#5632]
have the following setup:

A nuget package with two folders: net45 - including assemblies AssemblyOne.dll and AssemblyTwo.dll netstandard1.3 - including assemblies AssemblyOne.dll and AssemblyTwo.dll Of course these are different files with the same name.

I install the package into a project targeting 4.6.1 version of .NET Framework.

How can I make sure the assemblies from the netstandard1.3 are added to this project? Right now the net45 ones are added.

**Comment by godrose** [comment]
@alpaix

**Comment by alpaix** [comment]
What package management style does your project facilitate? `package.config`, `project.json` or package reference?

**Comment by godrose** [comment]
package.config

**Comment by emgarten** [comment]
For packages.config you can edit your csproj and change the dll reference path.

Desktop frameworks prefer desktop frameworks over cross-platform frameworks since they are similar in API surface area. 

As the package author if the netstandard1.3 assembly contains additional APIs not available in net45 then you will need to add a lib\net461 folder to the package so that it is selected for net461 projects.

**Comment by godrose** [comment]
Is this configurable in some way? It's somehow counterintuitive in my opinion.

**Comment by emgarten** [comment]
> Is this configurable in some way? It's somehow counterintuitive in my opinion.

No, is there a reason why netstandard should be preferred in your scenario? Do they contain different implementations or APIs?

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
