### ISSUE TITLE
bin and obj folders keep coming back

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5639]
_From @Petermarcu on July 24, 2017 18:10_

## Steps to reproduce
`dotnet build`
Have your project open in VS.
Open the folder for your project in explorer. 
delete the bin and obj folder. 

## Expected  behavior
The folder are gone

## Actual behavior
They come back. The bin folder is empty and the obj folder has assembly info and .cache files.
Delete again and they are gone.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview3-006770)

Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

_Copied from original issue: dotnet/cli#7241_

**Comment by livarcocc** [comment]
@Petermarcu please, move this issue to the project-system or Nuget. This happens because VS will restore the project once it seens it does not have a project.assets.json.

**Comment by livarcocc** [comment]
Moving this to Nuget, since I believe this happens because of automatic restore in VS.

**Comment by sharwell** [comment]
~~@livarcocc~~ @Petermarcu It seems that the current behavior is close to ideal in this regard. Visual Studio's functionality is substantially degraded prior to the resolution of packages, and NuGet information is not the only information that ends up generated (especially in the intermediate build directory, **obj\\**). The critical piece of functionality is the IDE and NuGet do not lock any files in these directories, allowing them to be deleted by a user, and this currently appears to work. Since you have Visual Studio open, it works in the background to ensure it has an accurate model of the open solution so you can continue working.

Given that this information at minimum needs to be available to Visual Studio, do you have thoughts on how it could be otherwise implemented?

**Comment by emgarten** [comment]
Restore here is likely triggered by the project system watching *project.assets.json* and requesting a restore when the file is removed. NuGet itself does not watch these files, it only restores on demand.

To prevent this behavior you can turn auto restore off in Visual Studio.

![image](https://user-images.githubusercontent.com/6381138/28550201-2d8a2648-7094-11e7-85b7-80c6f2f46e31.png)

**Comment by Petermarcu** [comment]
The thing I found most odd is that deleting it once causes it to come back. Delete it a second time and it stays gone. Is something about the first delete triggering an up to date check and a rebuild where the second time its not?

**Comment by sharwell** [comment]
@Petermarcu That may actually be a bug (though I'm not sure where). I would expect a delay, but eventually they should come back as long as the IDE is open and configured to restore packages.

**Comment by emgarten** [comment]
@sharwell any ideas where it is stopping? NuGet should be relying on the .cache file to determine if restore should be skipped, unless it is hitting errors from the missing file after the project system requests another restore.

**Comment by nkolev92** [comment]
This does not repro with 16.8 anymore. 
The project system does not nominate if an assets file is deleted right now.
