### ISSUE TITLE
SolutionRestoreWorker.StartBackgroundJobRunnerAsync blocks thread pool threads

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5657]
Using Visual Studio 2017 (15.3 Preview 6).

### Details

The call to `BlockingCollection.Take` in [StartBackgroundJobRunnerAsync](https://github.com/NuGet/NuGet.Client/blob/5d66754b948c86a39aa2b54e7e3c1d67f6b57979/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs#L337) is blocking a thread pool thread for ~~nearly 3~~ **110** seconds during a profiling run opening Roslyn.sln. This can lead to starvation of the thread pool on machines with fewer available processors, and increase the time it takes for Visual Studio to open.

One of the following approaches should be used to avoid this block:

1. Move the call to `Take` to a thread which is not part of the thread pool
2. Use a different data structure such as `AsyncQueue<T>` which is better able to manage these resources

:memo: Edited to reflect additional time immediately following the initial solution load.

**Comment by nkolev92** [comment]
This issue is still very relevant. 

I'm not sure how frequently this repros, but I think it should be straightforward to use an AsyncQueue instead of the blocking collection: https://github.com/NuGet/NuGet.Client/blob/253a77105feba2fdc481efc041e0f01242902087/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs#L460.

**Comment by nkolev92** [comment]
Actually this was fixed in https://github.com/NuGet/NuGet.Client/pull/1882/files#diff-ed2ac7b55aeda9197754d5bd59bea524R288. 

There's no action here any more. 

The take is synchronous, but there's a check before that.
