### ISSUE TITLE
Visual Studio 2015 RC problem adding existing standard Class Library project and Nuget restore

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#567]
After I add existing Class Library project and try to build to restore packages I am getting exception : Error occured:\nSystem.IndexOutOfRangeException: Index was outside the bounds of the array.

Then I close Visual Studio 2015 RC and re-open and package restore then works correctly.

@radenkozec can you provide us more details. 
packages.config?
and how exactly do you build?

**Comment by radenkozec** [comment]
I build using Visual Studio. I don't have packages.config from that time because I worked on the project for few days after this so it changed.
Anyway I had Class Library Framework 4.5 project, and when I add it to existing VS2015RC solution everything works great. When I try to build it in Visual Studio I am getting this exception. After I close and re-open VS I can build normally.

**Comment by emgarten** [comment]
This may be related to SolutionManager not finding the new project when it enumerates the list at restore time.

**Comment by AndriySvyryd** [comment]
I cannot repro this using VS 14.0.22823.1
This is what I did:
1. Create solution S1 with class library project P1
2. Add a package to P1
3. Close and reopen VS
4. Create solution S2 with class library project P2
5. Add existing project P1
6. Build

@radenkozec am I missing something?

**Comment by radenkozec** [comment]
@AndriySvyryd 
Try to use these steps:
1) Create VS2015RC S1 with Classic .NET Framework 4.5 project P1
2) In same solution create vNext Class Library Project(Package) P2
Put in project.json section for 
  "net451": {},
3) Click produce outputs on Build for vNext Project P2
4) Reference manually this vNext dll from P2 in Classic .NET Framework 4.5 project P1
5) Create new blank solution S2 and add both projects (P1,P2) as existing and try to build in Visual Studio.

This is not exactly how I got this error because I do have 8 projects and I have migrated from VS2015 CTP 6 to RC.

**Comment by AndriySvyryd** [comment]
I hit #584 while following the repro steps, it might be related or hiding the issue you saw

**Comment by radenkozec** [comment]
@AndriySvyryd Maybe. It is difficult to repro this because I had solution with 8 projects and after I closed and re-open VS RC everything worked, so I only got error once.

**Comment by yishaigalatzer** [comment]
As we lock down 3.3, we are not able to repro this. So we are guessing this was fixed in one of the numerous commits since this bug was tried out for the last time.

@radenkozec if you still see a similar issue, please open another issue (I hope that's unnecsssary)
