### ISSUE TITLE
Pack improperly encodes filenames

### ISSUE THREAD

**Issue by phillijw** [NuGet/Home#5726]
## Details about Problem

NuGet product used: Package Manager Console

NuGet version (x.x.x.xxx): 2.8.50926.602

dotnet.exe --version (if appropriate): --

VS version (if appropriate): VS Enterprise 2017 (15.2)

OS version (i.e. win10 v1607 (14393.321)): win 7

Worked before? If so, with which NuGet version: Unsure

## Detailed repro steps so we can see the same problem

1. Create a nuspec file

2. In the <files>, include a file with spaces in the name (you may have to use a wildcard)

3. Generate nupkg by running nuget pack

4. Rename nupkg file to .zip and view. You will see %20 instead of spaces in filenames (same for commas and other special characters)

...

### Verbose Logs

```
PM> nuget pack Data/Data.csproj -verbosity detailed
.....
Added file 'Web.Australia, New Zealand (ANZ) - Dev.config'.
Added file 'Web.Australia, New Zealand (ANZ) - Production.config'.
Added file 'Web.Australia, New Zealand (ANZ) - Staging.config'.
Added file 'Web.Australia, New Zealand (ANZ) - Test.config'.
Added file 'Web.config'.
Added file 'Web.Debug.config'.
Added file 'Web.Europe, Middle East, Africa (EMEA) - Dev.config'.
Added file 'Web.Europe, Middle East, Africa (EMEA) - Production.config'.
Added file 'Web.Europe, Middle East, Africa (EMEA) - Staging.config'.
Added file 'Web.Europe, Middle East, Africa (EMEA) - Test.config'.
Added file 'Web.North America (NA) - Demo.config'.
Added file 'Web.North America (NA) - Dev.config'.
Added file 'Web.North America (NA) - Production.config'.
Added file 'Web.North America (NA) - Staging.config'.
Added file 'Web.North America (NA) - Test.config'.
Added file 'Web.Release.config'.

Successfully created package 'C:\repos\..\Data.1.0.0.0.nupkg'.
...
PM> 
```
As you can see, the filenames appear proper in the output but in the nupkg file itself they are transformed with special characters being URL encoded. When they get unpacked, they are not decoded.

**Comment by phillijw** [comment]
Just saw this which is likely the fix: https://github.com/NuGet/Home/issues/2389

**Comment by nkolev92** [comment]
@phillijw Can you please try using a newer version of the exe? 
You can find them here: https://dist.nuget.org/index.html

**Comment by phillijw** [comment]
Our build server was happy with it using a newer version, yes. So that did work. I expected VS2017 to have a newer version with it although I might misunderstand how they are connected.

**Comment by nkolev92** [comment]
Thanks for checking that @phillijw, Glad it's fixed!
NuGet.exe ship-cycle is now aligned VS 2017 ship cycle, but it doesn't ship within VS. 
Update 4.3 of the exe will be update 15.3 for VS etc.

**Comment by heidemn** [comment]
I tried nuget.exe v4.1.0 and v4.3.0, as well as older versions, and had a problem with filenames containing spaces:

The [Content_Types].xml contained lines like
`<Override PartName="/ElectronDist_1.0.0.0/Contents/Frameworks/Electron Framework.framework/Electron Framework" ContentType="application/octet" />`
This made the package fail to install in VS 2015, and fail to open in the latest version of NuGet Package Explorer, 3.23.0.0:
"Part URI is not valid per rules defined in the Open Packaging Conventions specification"

If I remove all occurrences of "Override" having a "PartName" containing spaces, the package installs successfully.
Please fix, since it is annoying to manually edit the .nupkg file.

Note that this seems to occur only for binary files without a well-known file extension.

**Comment by dander** [comment]
Just a note for others who may run across this... This change makes NuGet generate packages that are incompatible with https://www.nuget.org/packages/NuGet.Core/

It uses System.IO.Packaging to read the package, which cannot even see files that have not been uri encoded.
