### ISSUE TITLE
Lock file has not changed, Skipping lock file write

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5729]
_From @littleKing82 on August 9, 2017 8:11_

## Steps to reproduce
1. Go to 'Package Manager' console
2. Select Project from Default project dropdown (e.g. The project i selected is created in VS2017 and target franework is DotNetCoreApp1.1
3.Install-Package System.ComponentModel.Annotations -Version 4.3.0

## Expected  behavior
Should have installed System.ComponentModel.Annotations successfully.

## Actual behavior
Package not installed. Lock file has not changed. Skipping lock file write.
Output:
Restoring packages for C:\MyTest.csproj... Installing NuGet package System.ComponentModel.Annotations 4.3.0. Committing restore... Writing lock file to disk. Path: C:\MyTest\obj\project.assets.json Restore completed in 816.43 ms for C:\MyTest.csproj. Restoring packages for C:\MyTest.csproj... Committing restore... Lock file has not changed. Skipping lock file write. Path: C:\MyTest\obj\project.assets.json Restore completed in 2.03 sec for C:\MyTest.csproj. Executing nuget actions took 4.12 sec Time Elapsed: 00:00:05.2258592

## Environment data
`dotnet --info` output:

Product Information:
.NET Command Line Tools (1.0.4)
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

_Copied from original issue: dotnet/cli#7400_

**Comment by nkolev92** [comment]
@littleKing82 I am not able to reproduce this issue. 
Which version of Visual Studio are you using?

The logs seem to be incomplete, so it's hard to tell if there really is a problem. There's no "time elapsed" and "finished" log statements etc.

If you are able to reproduce this again, can you please enable diagnostic verbosity by setting
"Tools -> Options -> Projects and Solutions -> Build and Run -> MSBuild projet build output verbosity" to Diagnostic and the pasting the whole output log to the issue here.

Can you also upload the assets.json file?
Thanks.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
