### ISSUE TITLE
Package and Version up-vote and down-vote feature

### ISSUE THREAD

**Issue by WalkerCodeRanger** [NuGet/Home#573]
There are now so many packages that it can be difficult to know which package to use.  The number of downloads provides some guidance for this but a better system would be if developers could upvote and downvote versions and Packages.  Or perhaps flag them in some way with helpful information (like that they are no longer maintained or out of date).

An example:
I use [Cassette](https://www.nuget.org/packages/Cassette/).  The officially supported package for Less with Cassette is [Cassette.Less](https://www.nuget.org/packages/Cassette.Less/), however that uses [DotlessClientOnly](https://www.nuget.org/packages/DotlessClientOnly/) which as of now only supports Less 1.4 with support for Less 1.5 in beta. But, [Less is currently at version 2.5](https://github.com/less/less.js/blob/master/CHANGELOG.md) with lots of useful features added. First, it was not at all apparent from Nuget that Dotless and Cassette.Less were behind. It was only after I wanted to use a feature that I discovered how far behind they were.  So I searched "Cassette Less" on nuget.org for alternatives.  That turned up a number of possible alternative packages.

* [Cassette.Less.Core](https://www.nuget.org/packages/Cassette.Less.Core) v2.1.0-beta6-fixed2
* [Cassette.LessJs.V8](https://www.nuget.org/packages/Cassette.LessJs.V8) v0.1.6
* [Cassette.LessJs](https://www.nuget.org/packages/Cassette.LessJs/) v1.0.2

Now, Cassette.Less.Core I was able to write off pretty quickly because it listed only a single beta version that was 2 years old.  Still, a downvoting system could have made that ever quicker.  Looking at the other packages I had to dig through the github repo for Cassette.LessJs to find they are using less 1.4.2.  Here a voting system or flagging system could have made this much clearer.  So now I will try Cassette.LessJs.V8. However, if I find issues with it, I will have no way of conveying to other Nuget users those issues.

So I think it would be great if we could upvote and downvote versions.  That should probably be the default so that if new versions are released that correct problems they can improve the ranking.  The package would then be ranked based on votes of either the most recent release version of a average of the release versions weighted toward the newer ones.  Perhaps there should be a way to vote on the package overall as well so that if the whole approach is wrong the package can be downvoted. Alternatively, a way to flag versions as out of date would be good.  However, that might not be flexible enough since there could be other issues with versions and packages that doesn't handle.

**Comment by csharpfritz** [comment]
I understand where you are trying to go with this, indicating which
packages are "good" or "up to date", but there can be a problem with your
scenario.

These packages WERE good at one point in time.  If at that time there were
a lot of votes indicating what a great package it was, you would need many
more votes later in time to indicate some community disapproval of the lack
of an update.

You can always review the date of last update for a package to determine if
it is still fit for your needs, and in the case of the JavaScript, LESS,
and CSS communities you will need to see consistent updates to those
packages on a monthly basis in order to keep pace.  This is why Microsoft
is recommending using bower and npm with ASP.NET for static resources,
because the maintainers of those libraries like LESS, jQuery, Angular and
the like update their packages in those environments.

I think we do need some system to promote those packages that are vibrant
and delivering great value to our NuGet community, but I'm not sure that
this is the complete solution.

**Comment by emgarten** [comment]
This is a good problem space, and will keep this in mind as we build the next iteration of the gallery. We do not plan to build this exact feature, but we are looking for a general way to improve discoverability.
