### ISSUE TITLE
Pack warning for SemVer appears as 5 different warnings on VS

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5752]
**Expected:**
1. We should make it a numbered warning
2. One warning with all the text is sufficient IMO

**Actual:**
![image](https://user-images.githubusercontent.com/14800916/29261483-a8f3e486-8084-11e7-9b11-e4c759b94a0b.png)

**Comment by mishra14** [comment]
tagging @rrelyea @rohit21agrawal  for visibility.

**Comment by jnm2** [comment]
I want to be able to use `<NoWarn>` to suppress this and similar warnings:

![image](https://user-images.githubusercontent.com/8040367/32305420-dc35d812-bf4b-11e7-9536-fa4897c41e8e.png)

`<NoPackageAnalysis>true</NoPackageAnalysis>` is a bad solution because it hides any new kinds of problems that might crop up.

I wish `Pack` targets had been considered in the scope of https://github.com/NuGet/Home/wiki/Improved-NuGet-warnings.

**Comment by rohit21agrawal** [comment]
this has been fixed already
