### ISSUE TITLE
VS2017 - .NET Standard - Pack option - referenced projects are not included and not option to include them

### ISSUE THREAD

**Issue by sakher-sawan** [NuGet/Home#5754]
## Details about Problem

NuGet product used (VS UI | Package Manager Console | dotnet.exe):

NuGet version (Package Manager Console Host Version 4.1.0.2427):

dotnet.exe --version (2.0.0-preview2-006497):

VS version (VS2017 26403.7):

OS version (win10):

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a .NET Standard project (class library) which references another project in the same solution.

2. Configure it to create a Nuget package (from project properties, Package tab).

3. Right click on the project, and click Pack.

4. The generated package doesn't include the referenced assembly, and there is no option to reference it.

## Other suggested things
Include an option to include referenced projects.

**Comment by rohit21agrawal** [comment]
@mss37 currently all referenced projects are included as PackageReference in your output nuspec ( that is contained within the nupkg) which is by design. 
We are, however, considering adding capability to add the referenced DLLs as part of the nupkg. Please subscribe to  issue  https://github.com/NuGet/Home/issues/3891 for more updates.
