### ISSUE TITLE
NU1603 warnings when nuspecing four part version dependencies in Nuget 4.3

### ISSUE THREAD

**Issue by blalonde** [NuGet/Home#5757]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): 

NuGet version (x.x.x.xxx): 4.3.0.4406

dotnet.exe --version (if appropriate): 1.1.0

VS version (if appropriate): 15.3

OS version (i.e. win10 v1607 (14393.321)): win10 14393.1480

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a simple ClassLibrary in VS 2017 15.3 for net46 target framework

2. Add NHibernate 4.1.1.4000

3. nuget restore

Produced log : WARNING: NU1603: NHibernate 4.1.1.4000 depends on Iesi.Collections (>= 4.0.0 && < 5.0.0) but Iesi.Collections 4.0.0 was not found. An approximate best match of Iesi.Collections 4.0.0.4000 was resolved.

This was not so in VS 2017 15.2
...

## Other suggested things

When I explicitly install NHibernate v 4.0.0.4000 the warning goes away

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

Running restore with 8 concurrent jobs.
Reading project file C:\POC\NugetSemverPoc\NugetSemverPoc\NugetSemverPoc.csproj.
Restoring packages for C:\POC\NugetSemverPoc\NugetSemverPoc\NugetSemverPoc.csproj...
Restoring packages for .NETFramework,Version=v4.6...
  CACHE https://api.nuget.org/v3-flatcontainer/iesi.collections/index.json
Resolving conflicts for .NETFramework,Version=v4.6...
WARNING: NU1603: NHibernate 4.1.1.4000 depends on Iesi.Collections (>= 4.0.0 && < 5.0.0) but Iesi.Collections 4.0.0 was not found. An approximate best match of Iesi.Collections 4.0.0.4000 was resolved.
Checking compatibility of packages on .NETFramework,Version=v4.6.
Checking compatibility for NugetSemverPoc 1.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for NHibernate 4.1.1.4000 with .NETFramework,Version=v4.6.
Checking compatibility for Iesi.Collections 4.0.0.4000 with .NETFramework,Version=v4.6.
All packages and projects are compatible with .NETFramework,Version=v4.6.
Committing restore...

### Sample Project

Very helpful if you can zip a project and paste into this issue!

[NugetSemverPoc.zip](https://github.com/NuGet/Home/files/1225665/NugetSemverPoc.zip)

**Comment by nkolev92** [comment]
@blalonde This is a new feature that introduced in NuGet 4.3/ 15-3
You can read more about the changes in the 4.3/15-3 release here:
https://blog.nuget.org/20170815/Whats-nu-in-NuGet-with-VS2017-15-3.html
You can read more about the errors and warnings spefically here.
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings

So this is all by design. We want the users to have better transparency on which dependencies they pull in. 

You basically have multiple ways of making this warning go away.
* Fixing the dependency tree, which you've done.
* Adding a "nowarn" which would basically ignore the warning

**Comment by blalonde** [comment]
Alright thanks
