### ISSUE TITLE
Suppress the "To prevent NuGet from restoring..." message output on every build

### ISSUE THREAD

**Issue by duncanawoods** [NuGet/Home#5802]
If I am using visual studio "minimal build output", I do not expect "advice" about how to set configuration options being spammed to the output window on every single build:

    To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'

Please either remove it, make it optional or only show if I have chosen normal/verbose output.

**Comment by rrelyea** [comment]
let's make this for normal and verbose logs only.

**Comment by ghost** [comment]
Is this changed? Any setting i have to change? I still see this output in every build.

**Comment by nkolev92** [comment]
@MrBjorn 
It is changed, this message is now at the "normal" level. 

The average VS user has this set to minimal. 

You can check your verbosity in VS by going to Tools -> Options -> Projects and Solutions -> Build and Run -> MSBuild project build output verbosity.

**Comment by ghost** [comment]
Thanks for fast reply! I Think I still get the verbose output!? or is this the correct output with thsi setting? 

I attach a screenshot. Essentially I only want a onliner, informing if nuget Went good or bad, since it usually goes good, its disturbing see to much info about it.

Regards,
Bjorn
















On Feb 22, 2018, at 02:28 AM, Nikolche Kolev <notifications@github.com> wrote:

@MrBjorn
It is changed, this message is now at the "normal" level.
The average VS user has this set to minimal.
You can check your verbosity in VS by going to Tools -> Options -> Projects and Solutions -> Build and Run -> MSBuild project build output verbosity.
