### ISSUE TITLE
Content file not included when reference via PackageReference instead of packages.config

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#5803]
_From @henning-krause on August 24, 2017 14:48_

I recently switched my project to use the PackageReference method (`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`) to include nuget packages and ran into a problem when I tried import the [evopdf](https://www.nuget.org/packages/EvoPDF/) package.

The packages does two things:
* Add an assembly reference to the current project
* Add a content file of around 50MB to the output of the project (evointernal.dat).

The package is imported just fine when using the packages.config approach and the evointernal.dat appears in the output directory. 

But with the new approach, I have two issues:
1. Even after package restore / build, the package is not shown in the "References" section. The dlls appears in the output directory, however.
2. The evointernal.dat is never copied to the output directory.

I tried the restore both with Nuget 4.3 as well as msbuild 15.3.409.57025.

Is there something wrong with the package or is there a bug in the PackageReference implementation?

_Copied from original issue: Microsoft/msbuild#2466_

**Comment by jainaashish** [comment]
Package author needs to correct this package and specify this content file `.dot` with right attributes in his `.nuspec` file so that when this package is installed, this content is rightly consumed in project. More details are available on these links - https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html https://docs.microsoft.com/en-us/nuget/schema/nuspec#including-content-files 

It just worked out of the box with packages.config since it use to copy everything from /lib folder into project's output folder when build.

**Comment by jainaashish** [comment]
`Even after package restore / build, the package is not shown in the "References" section.`

And about this, then it should have shown a NuGet package reference there. I'll file a bug on legacy project system to look into this.

**Comment by jainaashish** [comment]
Created Project-System bug for the reference issue - https://github.com/dotnet/project-system/issues/2731

**Comment by henning-krause** [comment]
I notified the owner of the package (EvoPdf) and they'll look into it for their next major version.
