### ISSUE TITLE
When Updating Visual Studio, custom Nuget Feeds are lost

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5838]
From feedback ticket 488078:
Recently, I updated from Visual Studio 15.2.x to v15.3.1. Upon starting Visual Studio, I went to update my extensions and noticed that my custom NuGet feeds were no longer available. I went into Visual Studio Tools|Options, and indeed, my custom feed definitions were gone. So I rentered them. Just this morning, I updated to v15.3.3 and once again, upon opening Visual Studio, my custom NuGet feeds were wiped out. I had to reenter them all over again.

**Comment by fourpastmidnight** [comment]
Just posted on the feed back site on ticket 488078 that this has happened yet again upgrading from 15.6.0 to 15.6.2.

**Comment by jainaashish** [comment]
@fourpastmidnight can you tell me where did you preserve your custom feeds? in user level `nuget.config` file under `%appdata%\NuGet` or solution level nuget.config file, etc...? And do you also see this issue with a blank new project?

I just tried it with 15.7 (updating from 15.7.3 to 15.7.5) but wasn't able to repro. I had my custom feeds inside user-level nuget.config file.

**Comment by fourpastmidnight** [comment]
My other NuGet feeds are stored in Visual Studio's settings (Tools | Options...). BTW, this also happened for extra Extension feeds, too.

Actually, the last time I installed an update to Visual Studio (15.7.5 just last week), I was smart enough to export _ALL_ my Visual Studio settings before applying the update since I've had lots of problems with settings, in general, being wiped out or corrupted after updates.

My NuGet feeds were indeed wiped out again after the update, but a simple settings import saved the day. But, it is super annoying that I have to resort to this at all.

Thanks for looking into this and let me know if I can provide further information. FYI: I still need to update my work computer's VS, so if I can provide installation logs or anything else, let me know. I just don't know when I'm going to install the update, as I'm heads down in code right now! 😉  I'm hoping within a week I'll have a few minutes to get that done--my computer is begging to be rebooted anyway.

**Comment by jainaashish** [comment]
can you look into `%appdata%\NuGet\NuGet.config` file on disk and confirm that your custom feeds are listed there?

**Comment by rrelyea** [comment]
@fourpastmidnight - did you see that last question from @jainaashish ?

**Comment by PatoBeltran** [comment]
If this issue is only seen with sources it might be because we used to rewrite the whole packageSources section on an update. With the work we have been doing around nuget.configuration this won't happen so this issue would be solved. Since we don't have a clear repro I will close this issue. Feel free to reopen this issue if it continues after updating to 15.9
