### ISSUE TITLE
RestoreConfigFile property in project is not used by VS restore

### ISSUE THREAD

**Issue by atanasa** [NuGet/Home#5843]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.3.1

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.3.3

OS version (i.e. win10 v1607 (14393.321)): win10 v1703 15063.483

Worked before? If so, with which NuGet version: probably not

## Detailed repro steps so we can see the same problem

1. Edin the project file (.csproj) to contain:

```
  <PropertyGroup>
    <RestoreConfigFile>$(MSBuildThisFileDirectory)\..\CustomNuget.config</RestoreConfigFile>
  </PropertyGroup>
```

2. Do a restore in Visual Studio and observe in the log of the operation the configuration files used.

## Actual behavior

The log from the restore command does not include the configuration file specified.

## Expected behavior

The log from the restore command must include the configuration file specified and that configuration should be used.

### Verbose Logs

Log from restore command:
NuGet Config files used:
    .......\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

### Sample Project

[ReproNugetConfig.zip](https://github.com/NuGet/Home/files/1274138/ReproNugetConfig.zip)

**Comment by emgarten** [comment]
The goal of this property is to allow passing a config file from the command line when calling msbuild. Example `msbuild /t:Restore /p:RestoreConfigFile=path\to\nuget.config`   It works from the command line since project properties and global properties both show up when the property is read during restore.

During VS restore this property is intentionally ignored. The settings in VS are based on the solution root and `RestoreConfigFile` is not supported.

To make this work in VS the UI, PMC, and all VS APIs would need to start reading the project files for these extra settings before any operation. For example getting the list of installed packages from a project would need to check the project for a config, then read that config to the global packages folder path, then it could find the actual install location of the package.

**Comment by emgarten** [comment]
After some further discussion on this, the current approach is that settings in the project file override nuget.config settings. For this reason setting the path to nuget.config in the project file is not a supported.

Having nuget.config as a project property would make it difficult to understand which setting is going to be used if the project contains conflicting values with nuget.config and also references it.

Any values that cannot be set in the project file should be added instead of relying on a nuget.config file in addition to the project file. If you find any that are not supported yet you can open an issue for those settings.
