### ISSUE TITLE
automatic nuget restore in visual studio for custom project system

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#5868]
Visual Studio will automatically restore nuget packages on solution load for .NET SDK projects, or on build for "classic" csproj projects. However, I can't get Visual Studio to restore nuget packages at all for my custom project system. However, it works when I use `msbuild /t:restore` from the command prompt.

How can I get Visual Studio to restore the nuget package?

see also Microsoft/VSProjectSystem#244.

## Details about Problem

NuGet product used: VS UI
NuGet version: 4.3.1
dotnet.exe --version: 2.0.0
VS version: 15.3.3
OS version: win10 1703 (16284.1000)

## Detailed repro steps so we can see the same problem

1. Clone [my fork](https://github.com/zivkan/VSProjectSystem) of the [Visual Studio Common Project System sample (Microsoft/VSProjectSystem)](https://github.com/Microsoft/VSProjectSystem/)
2. Edit `samples/project/sample/WindowsScript1/WindowsScript1.wsproj` and add

```
    <ItemGroup>
      <PackageReference Include="Adfc.Msbuild" Version="0.1.2-preview" />
    </ItemGroup>
```

You can also download the zip I attached to this issue, and avoid the above two steps.

3. Open `samples/WindowsScript/WindowsScript.sln` and build the solution.
4. In the experimental instance of Visual Studio, open `samples/project/sample/sample.sln`
5. At this point I would expect Visual Studio to automatically restore packages, but it does not. Even if I try to build the solution, it will not restore packages. 
6. `msbuild /t:restore WindowsScript1.wsproj` from the command prompt successfully restores the packages
7. Now that packages are restored, building from Visual Studio works.

### Verbose Logs

If you can tell me how to get verbose logs for the Visual Studio UI, I can copy it here.

### Sample Project

This sample already has the PackageReference added, so you can skip step 2 of the repro steps.
[VSProjectSystem.zip](https://github.com/NuGet/Home/files/1291527/VSProjectSystem.zip)

**Comment by zhili1208** [comment]
Project system need to call nuget nominate API for auto restore. @davkean does this sample call nominate API?

**Comment by davkean** [comment]
There's lots of pieces to make this work; dependency node, NuGet nominator, assets file watcher. We're pulling these pieces out in a reusable fashion for other project types to use, @natidea can talk about the details.

**Comment by zivkan** [comment]
Thanks for the info. For a while I've been considering restarting my project system using .NET's project system as a starting point, rather than the sample in the VSProjectSystem repo.  Is everything needed to get nuget restore to work in the dotnet/project-system repro, or does the .NET project system have some special integration, for example with the sdk? If it's all in the project system, is copying Microsoft.VisualStudio.ProjectSystem.Managed enough, or will I need bits from other assemblies too?

**Comment by natidea** [comment]
@zivkan it may be easier to use a bare bones Project System like the examples in VSProjectSystem because the .NET project system probably does a lot more that what you need. However if you want to get nominate/restore working, you can do so on an instance of VS that has the .NET project system installed by leveraging **Capabilities** to MEF import our assemblies. 

I've been experimenting with this and got restore and dependencies tree working on a barebones CPS project. Review [this diff to NuGetizer](https://github.com/NuGet/NuGet.Build.Packaging/compare/dev...natidea:packageRef) for examples of the changes needed. To summarize the steps you will need to replicate this:

1. Add the _PackageReferences_ and _DependenciesTree_ capabilities to your project, and copy [these rules from .NET Project system](https://github.com/NuGet/NuGet.Build.Packaging/compare/dev...natidea:packageRef#diff-e418ff90840f18d695d653aa56e9ca98)
2. You will also need a modified version of .NET Project System that leverages this capability. You could try building this branch: [packRefCapability](https://github.com/natidea/roslyn-project-system/tree/packRefCapability), and unzipping the ProjectSystem.vsix to `%VSINSTALLDIR%Common7\IDE\Extensions\<extension>`
3. Projects created with your project-system will also need to reference the Sdk (or a subset of it). I do this [here](https://github.com/NuGet/NuGet.Build.Packaging/compare/dev...natidea:packageRef#diff-2b7d1b66f423104d6e9a34343698307bL2), except using a stripped down version of the Sdk that only references the file [Microsoft.PackageDependencyResolution.targets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets). (You can create your own SDK by copying `%VSINSTALLDIR%MSBuild\Sdks\Microsoft.NET.Sdk` and removing unneeded targets)

Eventually we hope to provide a formal way to do this on top of CPS (tracked by https://github.com/dotnet/project-system/issues/2491 and https://github.com/dotnet/project-system/issues/1984).

**Comment by rrelyea** [comment]
Thanks @natidea for the details and progress here!
We'll close this nuget issue out. Let us know if/how we can help.

**Comment by natidea** [comment]
@zivkan please follow up on https://github.com/dotnet/project-system/issues/2491 if you have any more questions. Thanks!

**Comment by zivkan** [comment]
Sorry I couldn't reply earlier. Nat, thanks for the detailed info. I really appreciate all the effort. I can't expect users of my project system to install a custom .NET project system, and I don't know what side-effects there will be if I claim the c#, VB or F# capability. So for now, I think I'll investigate using packages.config, or maybe programatically running msbuild /t:restore on project load. Thanks again for everyone's help.
