### ISSUE TITLE
NU1603 false warning

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#6014]
This issue is related to #5757, but not quite the same.

I get the following warning in VS 2017 15.3.4 which I didn't get before:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	ManyConsole 0.4.2.20 depends on NDesk.Options (>= 0.2.0) but NDesk.Options 0.2.0 was not found. An approximate best match of NDesk.Options 0.2.1 was resolved.				

I cannot see how this should lead to a warning. Unlike #5757 this is not a 4-digit vs. 3-digit version comparison.

Best
Søren

**Comment by rohit21agrawal** [comment]
@emgarten does this qualify to be a legit warning?

**Comment by emgarten** [comment]
The warning occurs because `NDesk.Options 0.2.0` does not exist in the feed. `0.2.1` was the lowest version found.

This is fine since the package is within the range, but the warning lets you know that if `0.2.0` was added in the future that your next restore would use that instead.

Typically this is a package authoring error because the package depends on something that doesn't exist.

**Comment by emgarten** [comment]
Here is a more complete answer on NU1603:
https://github.com/NuGet/Home/issues/5764#issuecomment-323613059
