### ISSUE TITLE
Do not reformat web.config when running NuGet Update-Package command

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6018]
FEEDBACKTICKET 505337

The Update-Package command (and maybe other parts of NuGet) seem to competely reformat the web.config file. This removes empty lines and changes e.g. <a b="x"/> to <a b="x" /> (an extra space added).

This causes confusion and spurious source control changes. It makes multiple copies of the web.config file desynchronized. Resyncing them requires lots of manual work with a merge tool.

Please do not reformat config files. The .NET XML APIs all have an option to preserve whitespace.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by bplumlee-sh** [comment]
I too would like this feature. We have to reformat dozens of configuration files after upgrading NuGet packages.

**Comment by hulkbulgur** [comment]
+1 
This causes a lot of frustration in my team. 
We use the VS setting "align attributes on individual lines" for XML files, in order to track changes in the configuration. As we work a lot with nuget packages, the configuration files keep getting normalized, and if we forget reformatting after any package operations (regardless of whether it changes the configuration or not). This includes package operations in referenced projects. It often causes very cumbersome merge problems.
