### ISSUE TITLE
Expose a way to wait on running restore operation running in Visual Studio via IVs apis.

### ISSUE THREAD

**Issue by prafullbhosale** [NuGet/Home#6029]
## Details about Problem
Currently there is no way to await running restore operations in VS. 

VS version (if appropriate): Dev 15.4

Worked before? If so, with which NuGet version: No.

## Detailed repro steps so we can see the same problem

1. Create a new Empty ASP.NET Core 2.0 project targeting .NET Framework.
2. Right click on the project -> Add new scaffolded item. -> Empty Controller.

Scaffolding tries to install multiple NuGet packages to the project and eventually times out waiting for restore to finish and shows an error to the user asking to manually run restore on the project.

## Other suggested things

Scaffolding in ASP.NET Core 2.0 project, adds multiple NuGet packages to a project and needs NuGet restore to finish before proceeding to the next step. 

In this case, NuGet restore tasks are blocked on trying to switch to UI thread, which is held by scaffolding. 

Scaffolding uses the `JoinableTaskFactory.Run()` to allow background tasks to request and switch to UI thread, however JTF needs to be informed about the dependency on the NuGet tasks. 

Exposing a method that lets the caller await the completion of the restore operations will allow the JTF to let the NuGet tasks that need to run on UIThread proceed. 

cc @mlorbetske @emgarten

**Comment by prafullbhosale** [comment]
@emgarten any ideas which milestone this could be included in?

**Comment by emgarten** [comment]
This isn't in the schedule yet, there are a few other high priority features still in the works.
//cc @rrelyea

**Comment by abpiskunov** [comment]
As we chatted in the email, we have a lot of tests waiting for restore status when project is opened or dependency added and the way we hacked it now we look at restore output and check for “restore complete” last statement. However it is not very reliable and for example, on localized machines all our tests are broken since “Restore complete” is localized.  
Running restore before starting test app is not working for many tests since they test new apps or need to wait when initial restore operation is finished in VS (not just for all dependencies are present in asset file).

**Comment by emgarten** [comment]
`IVsSolutionRestoreStatusProvider.IsRestoreCompleteAsync` will true once all nominations and restores are complete.

This will be available as a MEF export. The interface will be part of https://www.nuget.org/packages/NuGet.SolutionRestoreManager.Interop/4.6.0-rtm-4825 and can be used as an embedded interop type (Same as NuGet.VisualStudio).
