### ISSUE TITLE
Add support for the Android Packaging project system (.androidproj) in VS 2015

### ISSUE THREAD

**Issue by mluparu** [NuGet/Home#603]
Currently, installing a nuget package inside a .androidproj via a template seems to succeed but none of the build artifacts get hooked up in the target project.

**Comment by yishaigalatzer** [comment]
We want to track here also work for nuproj and general CPS project support (if possible out of the box).

**Comment by yishaigalatzer** [comment]
@jasonmalinowski can we have the new build task apply to general CPS projects (longish term, Update .I).

CC @AArnott

**Comment by yishaigalatzer** [comment]
CC @sharwel

**Comment by jasonmalinowski** [comment]
@yishaigalatzer: we eventually it will have to be, since we're hoping to get rid of csproj/msvbproj once we ship RTM. If somebody needs it earlier then I guess we'll have to do it earlier.

**Comment by yishaigalatzer** [comment]
@mluparu we might got you part way there already in RTM. We should have a drop shortly after @maartenba merges his PR, and you can try from there.
https://github.com/NuGet/NuGet.VisualStudioExtension/pull/30

**Comment by maartenba** [comment]
Merged NuGet/NuGet.VisualStudioExtension#30.

**Comment by yishaigalatzer** [comment]
Lets close after the android team verifies it

**Comment by AArnott** [comment]
So it sounds like it won't work for them because they don't define the `AssemblyReferences` capability and don't declare a target framework.
NuProj lacks NuGet support for the same reason, which is sad because I already have [a NuGet package](http://nuget.org/packages/Nerdbank.GitVersioning) that targets class libraries _and_ NuProj but users have to manually install the package into NuProj since NuGet will refuse to install it.

Should I open a new issue to specifically track the request to support projects that don't define AssemblyReferences or target frameworks?

**Comment by yishaigalatzer** [comment]
What does a package like that do? Just targets and props or also assembly references?

**Comment by AArnott** [comment]
Mine just adds msbuild imports.

**Comment by mluparu** [comment]
Same here - just msbuild imports. Potentially install.ps1 and init.ps1 too.

**Comment by AArnott** [comment]
Ah yes, I might want ps1 script support as well although that is less critical for me. So perhaps this issue can be used to track the remaining work for both @mluparu and me since they seem the same.

**Comment by AArnott** [comment]
Regarding the error:

> install-package : The parameter 'frameworkName' cannot be an empty string.

I found the code on GitHub and determined you’re calling for TargetFrameworkMoniker via DTE.Properties on the DTE.Project object. CPS cannot return null from any property because it wreaks havoc for a lot of clients. Besides, in MSBuild there is no null property – just properties with empty values. So for those two reasons, and the fact that changing that would be high risk at this point, CPS needs to continue to return an empty string for unknown properties such as this one is for this kind of project. 

So it looks like NuGet needs to tolerate an empty string result and interpret it as an unsupported property (i.e. no target framework). In which case, I would suggest a package be deemed incompatible if it does not contain target framework agnostic assets for every type it contains. For example, if it contains MSBuild props and targets files, they had better be in the build directory itself and not some target framework sub-folder.

Does that work for you?

**Comment by emgarten** [comment]
I've checked in the empty framework fix: 
https://github.com/NuGet/NuGet.VisualStudioExtension/commit/31e3b4e8f04333a97aedeba6ac9fc25fa7c960ae

This project will end up as Unsupported and will install only assets without a target framework filter with this change.

**Comment by yishaigalatzer** [comment]
@mluparu can you see if stuff works for you now? Justin can point you to the build once the CI machine kicks it out

**Comment by AArnott** [comment]
With the latest drop, I'm not getting the frameworkName error any more! I'll test some more to see if NuProj "just works" altogether now.

**Comment by yishaigalatzer** [comment]
@mluparu given that we are in update I now, is this still needed?

**Comment by rohit21agrawal** [comment]
@mluparu ping

**Comment by mluparu** [comment]
hey, sorry for the delay. It looks like NuGet is still blocked for .androidproj projects. This is what I see with VS 2015 Update 2:

![screenshot](https://cloud.githubusercontent.com/assets/12057413/14474878/f5aad3cc-00b3-11e6-8385-6a9846cfc767.png)

I am running NuGet client version 3.4.2.830. Should I try this with a different version?

**Comment by yishaigalatzer** [comment]
No, was asking if you still needed the feature. Trying to prioritize work

**Comment by mluparu** [comment]
Got it. It would be great if you can keep it on your backlog. But there is no urgency right now for this feature though. 

We were considering adding gradle build support to our Android project system via a NuGET package when this ask was made, but we ended up adding the support directly in the core MSBuild targets because of the timing.
