### ISSUE TITLE
Fail to consume architecture-specified package

### ISSUE THREAD

**Issue by huoyaoyuan** [NuGet/Home#6036]
Version used: Visual Studio 15.4, .Net Framework 4.7, built-in nuget
Package used: CNTK.GPU
The package has an assembly under `lib/net45/x64`, and should be only available in x64 platform.
##### When using old `packages.config` format:
The assembly can be consumed, but not platform-conditional.
##### When using new `PackageReference` format:
The assembly cannot be consumed.
##### Expected behaviour:
The build system (and also IntelliSense) should consume the specified assembly when switching the project platform. For example of this package, switching to AnyCPU/x86 should consume nothing, and switching to x64 should consume the x64 assembly.

**Comment by jainaashish** [comment]
This isn't the right way to create package which include architecture based assemblies, which is why you're facing trouble consuming it. You can contact the package author and let him know that they need to update their package in order to get this consumed correctly. There is a [NuGet doc](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) which explain how to create package with architecture based assemblies.
