### ISSUE TITLE
Difference in Nuget Update from Nuget.exe and Nuget Package Manager Console

### ISSUE THREAD

**Issue by dsagar3409** [NuGet/Home#6048]
A custom developed Nuget package that is used in other projects works as expected. However, we see that there is some difference in the way that the reference (in csproj file) being added to the project when you update the Nuget package through nuget command line tool (v 3.4.0) or through Nuget Package Manager Console in VS 2015.

Due to this we see frequent merges and updates by the source control. 

**When updated through Command line**

```
<Reference Include="Dummy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
  <HintPath>..\packages\Dummy.1.27.10\lib\net452\Dummy.dll</HintPath>
  <Private>True</Private>
</Reference>
```
 
**When updated through Nuget Package Manger**

```
<Reference Include="Dummy, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\packages\Dummy.1.27.10\lib\net452\Dummy.dll</HintPath>
  <Private>True</Private>
</Reference>
```

**Requirement: Request to alter operation of the Visual Studio NuGet Package Manager Console.**

In regards to the subject issue, we use automated build tools.  As part of that build, we clean, restore and update NuGet packages for many Visual Studio solutions and projects.  The only means we have today to do that is to make command line calls to the NuGet executable.  However, doing so generates different results than using the Visual Studio NuGet Package Manager as described in the subject issue.    I would be willing to use Visual Studio, if there was a way to execute the Nuget.exe from the command line or make the Package Manage Console generate the same results as the NuGet executable.

**Comment by jainaashish** [comment]
@dsagar3409 NuGet package manager behavior is correct in this respect. But we can't make it consistent between nuget.exe and package manager since project system isn't available while executing via nuget.exe. NuGet doesn't do much there since it only calls into project system to add these references. 
So our recommendation will be to use package manager UI or package manager console in visual studio to always update your packages which will give you consistent behavior and right references. Or you can also look to migrate towards PackageReference where you can define floating ranges for package dependencies which will always take the latest while restoring. Please find more details - https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
