### ISSUE TITLE
Repository.Provider.GetCoreV2() not longer compiles with 4.4.0

### ISSUE THREAD

**Issue by bencyoung** [NuGet/Home#6053]
So I followed Dave Glick's examples and had a working set of client access to NuGet a few months back. I'm now revisiting it and upgraded the packages to version 4.4.0. However there isn't a newer version of NuGet.Protocol.Core.v2 and this depends on NuGet.Protocol.Core.Types which appears to have been retired now has conflicting types with some of the newer packages.

Is there any way to have 

            providers.AddRange(Repository.Provider.GetCoreV2()); // Add v2 API support

work with the latest NuGet packages? I need this as ProGet still uses V2 and isn't planning on changing...

Please please please can we have a stable documented API for downloading and using NuGet packages!

**Comment by bencyoung** [comment]
As an example of the confusion, after the upgrade even with a V3 feed I'm getting errors like:

INSTALL Packages        -       36.09 ms

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at NuGet.Resolver.CombinationSolver`1.<GetSortedList>d__18.MoveNext()
   at NuGet.Resolver.CombinationSolver`1.MoveForward(Int32 i, Boolean& consistent)
   at NuGet.Resolver.CombinationSolver`1.FindSolution(Action`1 diagnosticOutput)
   at NuGet.Resolver.CombinationSolver`1.FindSolution(IEnumerable`1 groupedItems, IComparer`1 itemSorter, Func`3 shouldRejectPairFunc, Action`1 diagnosticOutput)
   at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)

**Comment by jainaashish** [comment]
Thank you for the feedback! We're trying to improve on our public api documentation and be consistent. There are different surface areas like in VS, we always recommend to use NuGet IVS apis to write code instead of making an hard dependency on any NuGet package for the purpose of creating a new extension. Similarly we'll have guidance and proper documentation for our public apis exposed through multiple NuGet packages.
For now, to your current issue, all these packages starting with `NuGet.Protocol.*` were moved into `NuGet.Protocol` package. So try using https://www.nuget.org/packages/NuGet.Protocol/ and you'll be able to use the same api.

**Comment by jainaashish** [comment]
Please comment, if you've any further question.
