### ISSUE TITLE
Cannot attach debugger to Nuget Commandline when built from source

### ISSUE THREAD

**Issue by ap0llo** [NuGet/Home#6084]
I was trying to familiarize myself with the NuGet code base by stepping through the source code while running some basic commands in the nuget commandline with the VS Debugger attached.

However, the application cannot be debugged because after the build, VS thinks the source files are out of date and breakpoints are not hit. I tried both launching the client from VS as well as using the `--debug` switch to attach the debugger after launch.

I assumed it might have to do with the ILMerge call after build, but disabling this did not work either.   
Is there some trick to get the debugger attached that I did not think of? 
If so, it might be worth poiting that out in the README
I would be really thankful for any tips.

## Details about Problem

NuGet product used: NuGet.exe
NuGet version: Nuget.Client at ceb01f8696f29c8fc2c871180c1e552bd98ac154 
VS version: 15.4.0
OS version: Win10 v1709 (16299.19)

## Repro steps 

1. Check out the git repository
2. Run configure.ps1 
3. Open NuGet.sln in Visual Studio
4. Select Nuget.CommandLine as startup project
5. Start Debugging (F5)

**Comment by rrelyea** [comment]
As step 4.5, are you setting command line args in VS debug settings for NUGet.CommandLine?

**Comment by mishra14** [comment]
@ap0llo which file are you trying to debug?

**Comment by ap0llo** [comment]
@mishra14 I tried setting a breakpoint in `Program.Main()` (before the call to `MainCore`)

@rrelyea Yes, it tried, for example `install xunit`, but since I tried hitting a breakpoint in Main I don't think the command line args matter

**Comment by mishra14** [comment]
@ap0llo I double checked and I was able to hit a breakpoint - 

![image](https://user-images.githubusercontent.com/10507120/32029617-a6a381f0-b9aa-11e7-81f4-c048f158d015.png)


You do not need to pass any arguments. I think this is a machine related problem. `ILMerge` is not a problem because VS knows the correct build output directory. 

My suggestions are - 

1. run `git clean -xdf` in the repo then run `build.ps1 -SkipUnitTests` and try again.
2. If you still fail then check if you can debug other net framework projects.

**Comment by rrelyea** [comment]
Closing now, as it appears to be fine. Please let us know if you still are hitting this problem.

**Comment by ap0llo** [comment]
Sorry, I didn't have time to check earlier, but I could no reproduce anymore the issue after updating to Visual Studio 15.5 and debugging works as expected.
Thanks for your help!
