### ISSUE TITLE
Documentation URL forwards user to incorrect location in docs. (from NuGet settings window on VS)

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6100]
https://aka.ms/troubleshoot_nuget_cache 

We should link a docs issue for this if the documentation is not readily available. Also point this link to the right documentation.

![image](https://user-images.githubusercontent.com/14800916/32016124-edd875f4-b977-11e7-8bd3-7faa8015320c.png)

**Comment by karann-msft** [comment]
@mishra14 helped update the URL. We now need to update the doc to call out possible error scenarios and the solution. Ankit, can you please help with that, and then I can work on updating the docs.

cc: @kraigb

**Comment by mishra14** [comment]
Possible points of failures - 
[PathTooLongException](https://msdn.microsoft.com/en-us/library/system.io.pathtoolongexception(v=vs.110).aspx) - path is longer than 260 characters.
[UnauthorizedAccessException](https://msdn.microsoft.com/en-us/library/system.unauthorizedaccessexception(v=vs.110).aspx) -  user does not have permission to the path
[IOException](https://msdn.microsoft.com/en-us/library/system.io.ioexception(v=vs.110).aspx) - one reason is when the file is being used by another process.

**Comment by karann-msft** [comment]
@mishra14 can you share the exact error message that would be displayed in each of those scenarios.

**Comment by mishra14** [comment]
IOException - 
NuGet cache(s) clear failed at 10/26/2017 5:02:53 PM. 
Error: The process cannot access the file 'elmah.1.2.2.nupkg' because it is being used by another process.
Please see https://aka.ms/troubleshoot_nuget_cache for more help.

UnauthorizedAccessException - 
NuGet cache(s) clear failed at 10/26/2017 5:18:28 PM. 
Error: Access to the path 'C:\Users\anmishr\.nuget\packages\newtonsoft.json\10.0.3\lib\netstandard1.3' is denied.
Please see https://aka.ms/troubleshoot_nuget_cache for more help.

PathTooLongException - 
I think it should look something like - 
NuGet cache(s) clear failed at 10/26/2017 5:18:28 PM. 
Error: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Please see https://aka.ms/troubleshoot_nuget_cache for more help.

**Comment by anangaur** [comment]
@karann-msft, I see that the link is now fixed and points to https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-nuget-cache but I still do not see troubleshooting steps there. Can you take care of getting it documented there? I created another [issue in the docs repo](https://github.com/NuGet/docs.microsoft.com-nuget/issues/559) and I am closing this one.
