### ISSUE TITLE
Builds non-deterministically failing with new version of nuget

### ISSUE THREAD

**Issue by katelmaroney** [NuGet/Home#6121]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate): net46

VS version (if appropriate): 15.4.1

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: 

## Detailed repro steps so we can see the same problem

1.  Attempting to build a VS project caused below error: C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): Error : Assets file 'E:\A\_work\8\s\obj\Microsoft.ServiceHub.HostLib\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6'. Ensure that restore has run and that you have included 'net46' in the TargetFrameworks for your project.

See commit [here](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_git/DevCore/commit/6331cca5dc765281a28a53de0fed576781b1e248?refName=refs%2Fheads%2Fv15.4)

Failing builds [here](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_build/index?buildId=1090111&_a=summary) [here](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_build/index?buildId=1093102&_a=summary)

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by emgarten** [comment]
@katelmaroney can you provide some additional details on this?

The error you included indicates that the project did not have `net46` as in the `TargetFramework` or `TargetFrameworks` property. When you look at `obj\project.assets.json` what targets are listed?

Is there any indication as to what causes your build to change when this occurs?

It is likely that something else is changing how your projects are evaluated between when restore runs and when your build runs. This could happen if TargetFrameworks are being set from the command line.

**Comment by AArnott** [comment]
We are not setting `/p:TargetFramework=` at the command line. The build steps are exactly the same between the passing and failing cases. 
You can see the `obj\Microsoft.ServiceHub.HostLib\project.assets.json` for [a failing case](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_build/index?buildId=1093102&_a=summary&tab=artifacts) and yet a very similar commit [built successfully](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_build/index?buildId=1028333&_a=summary&tab=artifacts) earlier. I know I've seen the same commit both pass and fail non-deterministically, but we weren't capturing project.assets.json files as build artifacts until the failures started. Still, I think we can make the case easily enough that the commit that @katelmaroney points out should build successfully, and does (sometimes), but other times we have the project.assets.json files and logs of a failed build.

I suspect you can reproduce at least the failing case or the passing case on a local box (if not both, as we've seen both on our local boxes) for this commit. So I trust that, and the logs and failing project.assets.json files we have, should give you the leads you need in this investigation.

At the moment, we've worked around it by adding a net46 target to our HostLib project. But that unnecessarily bloats our package size and we want to remove that once this bug is fixed.

**Comment by nkolev92** [comment]
Hey all, 

While this is definitely an unfortunate problem it's been a long time since this was investigated and with the build logs gone, likely hard to recreate.

If this is still something you might be hitting/still relevant, let me know and I'd be happy to re-open.
