### ISSUE TITLE
NuGet.ProjectModel reads column/line information producing 15 MB of unneeded garbage

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#6139]
In large solutions, allocating the LineInfoAnnotation object in NewtonSoft.Json is producing about 15 MB (0.3%) of garbage:

![image](https://user-images.githubusercontent.com/1103906/32361248-92271016-c0b2-11e7-9565-a5acc0d9c51d.png)

We shouldn't need the line info for build tasks - can we have an option to turn it off or turn it off always.

**Comment by emgarten** [comment]
@jainaashish @nkolev92 I think this could be turned off for everything except project.json files. Providing specific line/column information for json files makes sense for project.json were the user is editting the file directly and needs to know where to fix it.

For project.assets.json if there is a problem it is caused by an internal issue, and there isn't much the user can do about it, even when the line/column info.

**Comment by emgarten** [comment]
@davkean thanks for the trace and tracking this down!

**Comment by emgarten** [comment]
I made this change and found no difference in the profiler. It turns out that there is a bug in older versions of json.net: https://github.com/JamesNK/Newtonsoft.Json/issues/1249

The `LineInfoHandling` property is reversed. So to turn off line info in older versions it needs to be `LineInfoHandling = LineInfoHandling.Load`, but with a newer version it should be `LineInfoHandling = LineInfoHandling.Ignore`.

For NuGet it is up to the CLI or VS as to which version of Json.NET is used at runtime, so I'm not sure we can actually fix this apart from setting  `LineInfoHandling = LineInfoHandling.Ignore`, and some day when json.net 10.x is used users will save some allocations.
