### ISSUE TITLE
Make NuGet.PackageManagement available as a .NET Standard package

### ISSUE THREAD

**Issue by sandyarmstrong** [NuGet/Home#6150]
It seems that `NuGet.PackageManagement` is the only package in the client libraries that does not have .NET Standard support. It would be great to be able to use this package in other .NET Standard libraries, or in .NET Core apps, etc.

I notice that this package has a dependency on `Microsoft.Web.Xdt`. Is that the only thing blocking this from happening?

**Comment by emgarten** [comment]
> I notice that this package has a dependency on Microsoft.Web.Xdt. Is that the only thing blocking this from happening?

That is the main blocker.

Could you provide some reasons for making this package support netstandard, are you using this cross platform?

**Comment by sandyarmstrong** [comment]
I work on [Xamarin Workbooks](https://developer.xamarin.com/guides/cross-platform/workbooks/), and we use the NuGet client libraries (including this one) on Mac and Windows. We're interested in creating some cross-platform .NET Core apps, and `NuGet.PackageManagement` is the only dependency currently tying us to .NET Framework.

**Comment by emgarten** [comment]
So this would be for installing/uninstalling packages and other things that the VS UI handles?

**Comment by abock** [comment]
@emgarten yes, ultimately we need to provide a VS-like package management experience on .NET Core.

**Comment by aelij** [comment]
I've created my own [package](https://www.nuget.org/packages/NuGet.PackageManagement.NetStandard) (needed it for the xplat version of [RoslynPad](https://github.com/aelij/RoslynPad)). I just added a few `#if`s to remove the XDT and MEF stuff. Would it be acceptable to merge this kind of change? This could be a multi-target package that supports everything on the desktop framework.

https://github.com/aelij/NuGet.Client/commit/3403963d46007c8bf3c6507e6dde29bdfa0a030f

**Comment by aelij** [comment]
The package I published also seems to be used by Cake Build, so there's definitely a need for this.

**Comment by bjorkstromm** [comment]
👍 About to bump @aelij's package to 4.6.0 (currently at 4.3.0)

Yep! There's definitely a need for this. I'd think @daveaglick also would be interested in this for Wyam.

**Comment by bdovaz** [comment]
I'm currently using it with Unity, I have recompiled it for .NET Standard 2.0 but I would want to see it supported officially.

I also encountered other problems like this:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj#L24

You can see that it's using "some" classes from old Microsoft.Extensions.* packages. It should reference the entire package because in my case I got collisions regarding one script defined multiple times (one from Nuget.Commands.dll and another one from the real Microsoft.Extensions dll) and son on. In my case I removed that class references and add the entire package reference from nuget.

**Comment by vdefeo** [comment]
Hello guys, would be very nice to have this lib for .net core.

Any ETA for this migration?

thanks

**Comment by deadlydog** [comment]
We're building a ASP.Net Core app that runs some PowerShell scripts from C# to do some of the work. It dies when trying to run `Install-PackageProvider NuGet`.  Any update on this?
