### ISSUE TITLE
Improve Support for Custom / Wrapped NuGet Clients

### ISSUE THREAD

**Issue by ilexp** [NuGet/Home#6161]
I'm currently trying to migrate a custom NuGet client from an old v2.x version to the latest v4.x NuGet in order to secure long-term support and allow dealing with netstandard packages that require a newer version. Maybe this is just me failing to wrap my head around some concepts, but so far the experience feels like a bit of a downgrade from the old v2.x integration. In any case, any input would be appreciated.

This issue is rather generic, so should we identify actual problems to be solved by NuGet in the process, it probably would make sense to move them to more specific issues.

## Use Case

- I'm maintaining a standalone desktop application that depends on NuGet package management to allow users to install and uninstall plugins, as well as update the applications individual components. 
- Some packages are non-standard and specific to the project, others are just your regular NuGet packages from the main repository, and either of them can depend on any NuGet package out there.
- Packages are installed into a local folder, their contents are examined and selectively copied to or removed from the proper application directories. The application restarts, done.
- A core concept of the application is self-contained, i.e. allowing users to keep any number of installations in separate folders, each being independent from both the system and unknowing of other installations.
- It might be used on systems where no development tools are installed at all, so no Visual Studio or system-wide nuget.

## Issues

- All existing NuGet documentation seems to revolve around publishing and consuming packages using any of the official clients and Visual Studio. The best candidate that I found so far is a [tutorial by Dave Glick](https://daveaglick.com/posts/exploring-the-nuget-v3-libraries-part-1), which is helpful, but only to a degree. There seems to be a lack of both manual pages and code documentation with regard to using NuGet libraries directly.
- There seems to be a big increase in NuGet classes the user has to deal with and learn about in order to get anything up and running, most of which remain somewhat fuzzy in their purpose and hidden behind interfaces. Internal designs are all good and well, but some shortcuts would be appreciated: Simple package manager with N custom repository urls - do I really need to manually instantiate an `ISettings`, an `IPackageSourceProvider`, an `ISourceRepositoryProvider` and a `NuGetProject` for that, all of which may or may not require a custom implementation?
- I haven't figured out a way to either provide no settings, or provide custom / local settings only yet. All of the constructors or static methods seem to load or require machine-wide or user-specific settings in some way, there is no empty constructor, and lots of objects require a settings reference - so how do I sandbox NuGet inside my application folder?
- Not all methods provide a non-async overload. This is a design choice that may match with a developers use case, or it may not - but since async is somewhat viral, the lack of non-async overloads is an inconvenience with technical implications.
- The micro dependency model leads to 15 dependencies and ~30 files in the output directory for a fresh new console project with just nuget, which just feels wrong. Not expecting that my gut feeling will have an impact on architectural design decisions, but kind of need to put that on the list 😄 

So.. thank you for reading this big block of text - feedback and insights appreciated.

**Comment by nkolev92** [comment]
Our documentation of the post-V2 libraries is lacking, so I'll try to give you as many pointers as possible for you to be able to get around.

Since you're moving on from V2, I assume you're only familiar with the concept of packages.config. 
NuGet 4.x now has [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) which is our new and recommended way of dependency management. 
It's transitive, clean and provides better performance than packages.config. 

Unfortunately currently there is no better how-to guides than Dave Glick's blog post. 
Keep in mind that even that blog post is a bit outdated, because now some of the libraries have been merged into one. For example Protocol.V2 and protocol.V3 and now just NuGet.Protocol etc. 

https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Protocol has resouces you would use to search for packages, download etc.

You can use NuGet.Commands for the specific commands to install (in packages.config), restore projects etc. 
Everything is based around the concept of a project in the 4.x world. 

The ISettings object represents all the configuration NuGet needs to perform a restore/install successfully. 
You wouldn't want an empty ISettings object normally, since there'd be no sources etc. 
There's the NullSettings object for convenience though. Unfortunately the constructors are now tied to having actual config files. 

I don't think there's a way to go about without using these abstractions. 

We can assist you if you have other specific questions, but from what I can see, you're on the right track.

**Comment by ilexp** [comment]
Thank you for the quick answer! I will investigate some more and gather a list of more concrete questions to get back to you.

**Comment by ilexp** [comment]
Okay, so I have worked on a test project for a bit and did some research in David Glicks [implementation](https://github.com/Wyamio/Wyam/tree/5a9f5d5e0bfbf48aa3984046864be11982e5eb92/src/core/Wyam.Configuration/NuGet) beyond the tutorial post, but there's still some unclear points.

> You wouldn't want an empty ISettings object normally, since there'd be no sources etc.

While I do have settings like package sources, the project I'm working on has its own way to store those URLs, so I would in fact want to have a completely application-controlled, empty ISettings object to start off with. Any external, machine- or user-wide settings should not interfere, and the easiest way to ensure that is to not load or pass them around. Is there any reasonable way to do this?

Aside from that, here's a bit of test code I've written:
```csharp
// ...

PackageSourceProvider sourceProvider = new PackageSourceProvider(settings);
SourceRepositoryProvider repoProvider = new SourceRepositoryProvider(sourceProvider, resourceProviders);
NuGetPackageManager manager = new NuGetPackageManager(repoProvider, settings, packagesPath);

List<SourceRepository> sourceRepositories = new List<SourceRepository>();
sourceRepositories.Add(sourceRepository);

await manager.InstallPackageAsync(
	project,
	new PackageIdentity("Newtonsoft.Json", new NuGet.Versioning.NuGetVersion(10, 0, 3)), 
	resolutionContext, 
	projectContext, 
	sourceRepositories,
	Enumerable.Empty<SourceRepository>(),
	CancellationToken.None);
	
// ...
```
Suppose I implement my own `PackageSourceProvider`, I would be able to simply not rely on a settings object to maintain a source list, right? All sources are under my implementations control.
```csharp
NuGetPackageManager manager = new NuGetPackageManager(repoProvider, settings, packagesPath);
```
However, the settings object is also passed to the `NuGetPackageManager` - is there any way to omit this as well?
```csharp
List<SourceRepository> sourceRepositories = new List<SourceRepository>();
sourceRepositories.Add(sourceRepository);

await manager.InstallPackageAsync(
	project,
	new PackageIdentity("Newtonsoft.Json", new NuGet.Versioning.NuGetVersion(10, 0, 3)), 
	resolutionContext, 
	projectContext, 
	sourceRepositories,
	Enumerable.Empty<SourceRepository>(),
	CancellationToken.None);
```
Also, when I call `InstallPackageAsync`, it again accepts a list of source repositories to use. If I can just change my mind on every install, why are they passed to the source provider and to the package manager in the first place? And what's the purpose of the secondary package source list, vs. the primary one?

I feel like I'm really not seeing the big picture here, so any insight on this would be appreciated.

**Comment by nkolev92** [comment]
That code is a bit of a mess because this is written with a UI context in mind. So a bunch of those objects are long-lived so it'll be a bit confusing as to where they come from. 
It also install for 2 different project styles which get the sources differently. 

The Settings represent all the settings that NuGet loaded at solution load and all the changes that the user made while in that session. (We don't detect changes on disk after the loading of the solution). 

The primary vs secondary sources tidbit is confusing, and is only used in packages.config case, basically when you install a package from a selected package source, the primary sources represent where the requested package should come from, while the secondary sources, normally a superset, represent the sources from which the dependencies of the requested package can come from. 

In the package reference case however, the NuGetProject => ProjectRestoreMetadata has a sources field which is the one that tells it which sources to use.
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs#L135

Unfortunately, the settings object was not written with that in mind, so it's not really possible to just populate it without an XML, but since ISettings is passed everywhere, you might be able to just implement the interface. 

Looping in @emgarten for more help.

**Comment by ilexp** [comment]
Thanks for the explanation so far! Continuing to look into this.

> That code is a bit of a mess because this is written with a UI context in mind.
> [...]
> It also install for 2 different project styles which get the sources differently.

Are there plans for future versions of NuGet to go back towards a more "frontend agnostic package management library" approach? In my understanding, the core of NuGet is all about communicating with a server, resolving dependencies, downloading and extracting files - so why should it be built with a certain UI or project type in mind?

In the same vein, there seem to be a lot of "is it a msbuild / build-integrated / foo project" kind of special cases throughout the NuGet codebase - but shouldn't that kind of specialization be moved into the actual interface implementations, rather than being scattered in the core lib? Could imagine that stuff like that would cause problems for custom project types that can only provide an interface implementation, but are otherwise unknown beforehand. Since NuGet isn't just used in msbuild or VS, but also Squirrel, Chocolatey and similar projects, core library special cases for the first two seem a bit like a dangerous / flaky direction.

(Please do correct me if I'm wrong, I only just stumbled through the codebase recently, so I'm nowhere near a position to assess and interpret this properly, talking based on gut feeling and first impressions here.)

> [...] but since ISettings is passed everywhere, you might be able to just implement the interface.

Did exactly that and it seems to work well so far! 👍 Not 100% sure about all of the interface methods yet, but for now I just logged all the incoming calls during an install and built my own version to contain the same data, except for the package sources. This also solves the problem of inadvertently having a new `NuGet.config` file created by instantiating a settings object.

Overall, I made a bit more progress and [implemented a custom project type](https://gist.github.com/ilexp/7de2ad91724c2dbef175aa06b58fa623) for my use case. It derives from `FolderNuGetProject`, since that one seems to be the closest match, but one thing I noticed doing that is that it [doesn't seem to report back which packages are installed](https://github.com/NuGet/NuGet.Client/blob/5b6edbb1c6aba9056d6fadd5407ba37b5281f63e/src/NuGet.Core/NuGet.PackageManagement/Projects/FolderNuGetProject.cs#L88-L91) at all, so I'm assuming that there this kind of project can't be handled correctly with regard to package updates and dependency resolving? In order to fix this, I implemented `GetInstalledPackagesAsync` manually:

```csharp
public override Task<IEnumerable<PackageReference>> GetInstalledPackagesAsync(CancellationToken token)
{
	List<PackageReference> installedPackages = new List<PackageReference>();
	foreach (string packageFolder in Directory.EnumerateDirectories(this.Root))
	{
		// ...
		// Adding one PackageReference for every folder with a matching nupkg in it.
		// ...
	}
	return Task.FromResult(installedPackages as IEnumerable<PackageReference>);
}
```

After I did that, I got an exception when attempting to install an already installed package, so I'm assuming this was a success. However, I don't seem to get package updates to work properly - all attempts so far lead to installing the new package version without uninstalling the old one. [Here's what I'm trying](https://gist.github.com/ilexp/1abf3803bb65e03821fe747f6910b6cd), shorter version:

```csharp
// Before: Newtonsoft.Json 10.0.2 installed.

// Trying to update:
IEnumerable<NuGetProjectAction> updateActions = await manager.PreviewUpdatePackagesAsync(
	new PackageIdentity("Newtonsoft.Json", new NuGetVersion(10, 0, 3)),
	new[] { project },
	resolutionContext,
	projectContext,
	sourceRepositories,
	Enumerable.Empty<SourceRepository>(),
	CancellationToken.None);
IEnumerable<NuGetProjectAction> updateActions2 = await manager.PreviewUpdatePackagesAsync(
	new PackageIdentity("Newtonsoft.Json", new NuGetVersion(10, 0, 2)),
	new[] { project },
	resolutionContext,
	projectContext,
	sourceRepositories,
	Enumerable.Empty<SourceRepository>(),
	CancellationToken.None);
IEnumerable<NuGetProjectAction> updateActions3 = await manager.PreviewUpdatePackagesAsync(
	"Newtonsoft.Json",
	new[] { project },
	resolutionContext,
	projectContext,
	sourceRepositories,
	Enumerable.Empty<SourceRepository>(),
	CancellationToken.None);
// All three versions: Only an install, but no uninstall?
```

Any idea what I'm doing wrong?

I also wondered why there is no non-preview version of the update method, when there is one for install and uninstall - am I misunderstanding some of the API here..?

**Comment by nkolev92** [comment]
>Are there plans for future versions of NuGet to go back towards a more "frontend agnostic package management library" approach? 

I think I worded that badly. 

NuGetPackageManager is used from the CLI as well. It's just there's a lot of parameters that overlap in meaning. 
Some are used in packages.config, some are used in package reference, some are used in both. 
What I was trying to communicate is that they are just more complex. The mutable objects are ones being passed down to the methods containing the core logic normally, which is not great. 

The MSBuild/BuilIntegrated project goo is actually pretty straightforward. 
Msbuild projects are packages.config projects and all that's relevant to it, so that would contain a PackagesFolderNuGetProject and a PackageConfigNuGetProject (solution level packages), while the build integrated ones are the package reference and projectjson projects. They are not special cases :) 

So consider using the MSBuildNUGetProject.

Regarding your code example, it seems like you are not executing the actions.
Preview does not commit/execute/download packages. 
You need to do ExecuteNuGetProjectActionsASync or similar. 

Look at UpdatePackageCommand (Package Manager Console) and UpdateCommand (NuGet.Commandline) for examples.

**Comment by ilexp** [comment]
> So consider using the MSBuildNUGetProject.

I'll look into it, but since I do have a custom way to manage installed packages and do not use `packages.config`, I might have to roll out a custom project type. Does it make sense to derive from `PackagesFolderNuGetProject` if I just want the "put packages into a folder" behavior and manage the list of installed packages myself?

> Regarding your code example, it seems like you are not executing the actions.

In the [linked code piece](https://gist.github.com/ilexp/1abf3803bb65e03821fe747f6910b6cd#file-packagetest-cs-L44), I do execute them, I just shortened the excerpt for readability. The problem is not that the actions generated by the "Update" preview are not executed properly, but that the "Update" command actually just generates an install action, but no uninstall action. Am I missing something?

> Look at UpdatePackageCommand (Package Manager Console) and UpdateCommand (NuGet.Commandline) for examples.

Will take a look, thanks!

**Comment by jainaashish** [comment]
Please let us know if there any further questions on this.
