### ISSUE TITLE
RestoreOutputPath is not respected by Visual Studio

### ISSUE THREAD

**Issue by splusq** [NuGet/Home#6186]
When doing a standard msbuild from the command prompt g.props and g.targets get properly generated relative to the project path. However, when building the solution from Visual Studio, the g.props and g.targets gets restored in the intermediate or output path, resulting in the build to ultimately break from Visual Studio on a clean repository. The same repository works when one switches back to command line to msbuild. 

For instance, from Visual Studio:
Generating MSBuild file private\common\Instrumentation.Logging\src\objd\ServerLogging.csproj.nuget.g.props.
Generating MSBuild file private\common\Instrumentation.Logging\src\objd\ServerLogging.csproj.nuget.g.targets.

from command line:
Generating MSBuild file private\common\Instrumentation.Logging\ServerLogging.csproj.nuget.g.props.
Generating MSBuild file private\common\Instrumentation.Logging\ServerLogging.csproj.nuget.g.targets.

**Comment by rrelyea** [comment]
What type of project do you have?
Normal csproj? DotNet SDK based csproj?

How do you import nuget packages?
Packages.config | Project.json | PackageReference

**Comment by emgarten** [comment]
This is related to cloud build. 

Command line restore has an option to set RestoreOutputPath which overrides BaseIntermediateOutputPath. In VS only BaseIntermediateOutputPath is read.

**Comment by emgarten** [comment]
The workaround for this is to set `BaseIntermediateOutputPath`

`RestoreOutputPath` is only intended for advanced scenarios where the user needs to redirect the restore outputs to a different location, which typically doesn't work with build.

**Comment by jeffkl** [comment]
I've created a repo that explains the workaround:

https://github.com/jeffkl/GPropsTest/blob/master/ClassLibrary1.csproj#L3-L15

**Comment by emgarten** [comment]
@jeffkl is there something NuGet should do to improve this?

**Comment by jeffkl** [comment]
@emgarten yes ideally the only property in play here would be `MSBuildProjectExtensionsPath`.  [The intent](https://github.com/Microsoft/msbuild/issues/784#issuecomment-241880891) was to be the one property that all package managers would use as a folder to generate stuff to that extends a project.  It defaults to `BaseIntermediateOutputPath` so in a perfect world:

1. `NuGet.targets` use `MSBuildProjectExtensionsPath` as defaults for `RestoreOutputPath` and `ProjectAssetsFile`
2. Visual Studio uses `MSBuildProjectExtensionsPath` instead of `BaseIntermediateOutputPath`

Is it too late to change this functionality?

**Comment by emgarten** [comment]
Do you mean NuGet.targets use BaseIntermediateOutputPath? 

From the NuGet side we also need to change project.assets.json to be project.csproj.assets.json, and make it easier to set that path. We could look at changing this as part of that.

At this point is there a reason to use BaseIntermediateOutputPath over IntermediateOutputPath? I think there was a timing issue when the SDK being a package that caused this before, but to support generating project.assets.json on a per configuration basis the actual output path would be better.

**Comment by jeffkl** [comment]
Sorry I'm confusing this even more because I meant to say **MSBuildProjectExtensionsPath** not MSBuildExtensionsPath.

> Do you mean NuGet.targets use BaseIntermediateOutputPath?

I don't think `IntermediateOutputPath` is used anywhere, only `BaseIntermediateOutputPath`.  Correct me if I'm wrong.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L534

I think NuGet should only use `MSBuildProjectExtensionsPath`.

`BaseIntermediateOutputPath` is set in [Microsoft.Common.props](https://github.com/Microsoft/msbuild/blob/38fe952a2ec5885b922e8581d33aa09e0904cf8b/src/Tasks/Microsoft.Common.props#L50) but `IntermediateOutputPath` is set much later because it usually includes properties like `Configuration` and `Platform` which are set in the project or at least after Microsoft.Common.props.  NuGet would want to place its stuff in BaseIntermediateOutputPath because the path is generally Platform/Configuration independent.

**Comment by nkolev92** [comment]
I don't think we end up adding RestoreOutputPath to VS, because that's not really the intent of this, but I want to keep this open to track the changes that @jeffkl is recommending. 
/cc @dsplaisted

**Comment by nkolev92** [comment]
NuGet now defaults to MSBuildProjectExtensionsPath. 
That's what needs to be used to change the nuget artifacts drop location. 

https://github.com/NuGet/NuGet.Client/pull/2131

Visual Studio 2017.7
4.7 of NuGet.exe
2.1.200 versions of the SDK

Closing this as won't fix.
