### ISSUE TITLE
Block package reference to tool package type when there is no property to indicate the project is a temporary project to restore the package

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6198]
Tools CLI ask

tool package can reference normal package 
tool package can reference tool package
 normal package **cannot** reference tool package

```
rid split requires

 mytool  ( identity package, tool package) -> win-x64.mytool (rid specific package, a tool package)                                          
                                         ->linux-x64.mytool (rid specific package, a tool package)                                     
                                          -> Microsoft.NETCore.Platform (a normal package to provide rid relation)
```

**Comment by nkolev92** [comment]
Due to the way we do compat checking and performance considerations, we will be doing the follwoing:

ToolPackage cannot be found in the normal project graph (only in the special project graph). 
Top level dependencies of DotnetToolReference projects HAVE to be of DotnetTool type!

So in theory a package can reference a tool project, but it will never be restoreable. 
In addition, people would have to do crazy workarounds to build a package like this.

**Comment by bricelam** [comment]
> ToolPackage cannot be found in the normal project graph

I'm arguing semantics here, but shouldn't this be: *Only Dependency packages are allowed*

**Comment by nkolev92** [comment]
Closed in https://github.com/NuGet/NuGet.Client/pull/1900
