### ISSUE TITLE
NuGet chooses incorrect references for System.Reflection.TypeExtensions.dll for .NET Core for UWP 5.2.2 if Windows SDK Target version is 10.0.16299

### ISSUE THREAD

**Issue by ali-hk** [NuGet/Home#6201]
NuGet chooses incorrect references for System.Reflection.TypeExtensions.dll for .NET Core for UWP 5.2.2 if Windows SDK Target version is 10.0.16299 causing types like System.Reflection.BindingFlags to fail to resolve and consequently build failures.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe via MSBuild called from Visual Studio F5.

NuGet version (x.x.x.xxx): 4.4.0

VS version: 2017 15.4.0

OS version: Windows 10.0.15063

Worked before? If so, with which NuGet version: Yes. Unclear.

## Detailed repro steps so we can see the same problem

1. Create a new Windows Universal Class Library

2. Choose Windows 10 Fall Creators Update (10.0; Build 16299) for target version and min version.

3. Add the following method: `public System.Reflection.BindingFlags GetBindingFlags() => System.Reflection.BindingFlags.Static;` to `Class1`

4. Compiles successfully.

5. Change the NuGet reference for `Microsoft.NETCore.UniversalWindowsPlatform` from 6.0.1 to 5.2.2 (or anything between 5.2.2 and 5.4.1)

6. Clean and recompile. Compilation fails with: `Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.` and `error CS1069: The type name 'BindingFlags' could not be found in the namespace 'System.Reflection'. This type has been forwarded to assembly 'System.Reflection, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.`

7. Diagnostic output (and project.lock.json) shows that `System.Reflection.TypeExtensions.dll` was referenced from `%USERPROFILE%\.nuget\packages\system.reflection.typeextensions\4.1.0\ref\netstandard1.5\System.Reflection.TypeExtensions.dll`

8. Switch the project from Windows SDK Target Version 16299 to 15063 (Creators Update) or lower.

9. Recompile and it builds successfully.

10. Diagnostic output shows that `System.Reflection.TypeExtensions.dll` was referenced from `%USERPROFILE%\.nuget\packages\system.reflection.typeextensions\4.1.0\ref\netstandard1.3\System.Reflection.TypeExtensions.dll` instead, which has the correct redirects for `BindingFlags`.

## Other suggested things
This appears to be a mapping issue where 16299 is mapped such that .netstandard 1.5 is incorrectly chosen for `Microsoft.NETCore.UniversalWindowsPlatform`

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

[Failing16299.txt](https://github.com/NuGet/Home/files/1486755/Failing16299.txt)
[Working15063.txt](https://github.com/NuGet/Home/files/1486756/Working15063.txt)

### Sample Project

[BrokenReflection.zip](https://github.com/NuGet/Home/files/1486754/BrokenReflection.zip)

**Comment by emgarten** [comment]
This doesn't look like a NuGet issue. @diverdan92 where should this go?

**Comment by ali-hk** [comment]
@emgarten are you sure? it appears to be the mapping logic in NuGet that causes the netstandard1.5 reference to be selected instead of netstandard1.3.

**Comment by diverdan92** [comment]
@ali-hk - I'm following up with some folks to better understand the failure, but just to explain why you're seeing slightly different behavior, Windows 10 implements .NET Standard 2.0 in the 10.0.16299.0 build. That means, when you have an application with a TargetPlatformMinVersion of 10.0.16299.0, the NuGet package maps to .NET Standard 2.0 support. In addition, the .NET Core NuGet package version 6.x and higher carries the .NET Standard 2.0 implementation of .NET Core for Windows 10 but *only for apps with a Min Version of 10.0.16299.0 or higher*. 

Any UWP project with a Min Version less than 10.0.16299.0 implements .NET Standard 1.4; and any project that references the .NET NuGet package version < 6.x will also only include the .NET Standard 1.4 implementation. 

So, when you have a project with a TargetPlatformMinVersion of 10.0.16299.0, and are referencing the 5.2.2 version of the .NET NuGet package, you have a .NET Standard 2.0 compliant application carrying the .NET Standard 1.4 implementation of .NET. It *should* work, but the reason it is referencing .NET Standard 1.5 in this example case is because it is the closet implementation to .NET Standard 2.0 that is available in the package (since the app is technically .NET Standard 2.0 compliant).

Does that make sense?

**Comment by diverdan92** [comment]
@ali-hk - if you clean and rebuild the project, what is the behavior you see? When you encounter this failure, can you save obj\project.assets.json file and share the contents?

**Comment by ali-hk** [comment]
@diverdan92, cleaning and rebuilding results in the following build failure:

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>C:\Users\<username>\Documents\Visual Studio 2017\Projects\Playground\BrokenReflection\Class1.cs(11,34,11,46): error CS1069: The type name 'BindingFlags' could not be found in the namespace 'System.Reflection'. This type has been forwarded to assembly 'System.Reflection, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

Attached project.assets.json (renamed .log to play nice with github).
[project.assets.json.log](https://github.com/NuGet/Home/files/1515009/project.assets.json.log)

**Comment by jainaashish** [comment]
@diverdan92 what is the next course of action here?

**Comment by mishra14** [comment]
@diverdan92 🔔

**Comment by diverdan92** [comment]
Sent mail. Not sure if it's NuGet or .NET.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
