### ISSUE TITLE
Any restriction in Package count and size while uploading NuGet in nuget.org?

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#6208]
Hi All,

I have generated my custom NuGet packages and I need to upload my custom NuGet packages in the [nuget.org](https://www.nuget.org) server to install/restore my NuGet packages by using the nuget.org online NuGet feed. 

My question is,
Is there any restriction on package size?
Is there any restriction on packages count to upload under my nuget.org account?
How to get staging server source to upload the test packages via CLI ?

Please give your suggestion regarding this.

Thanks,
Ganesan R.

**Comment by PatoBeltran** [comment]
@joelverhagen as you have more context with nuget server. Can you please answer this questions?

**Comment by joelverhagen** [comment]
Hey @GanesanRengasamy. Just as an FYI, the [NuGet/Home](https://github.com/NuGet/Home/issues) GitHub repository is more targeted to NuGet client issues. [NuGet/NuGetGallery](https://github.com/NuGet/NuGetGallery/issues) is the home for server side issues.

> Is there any restriction on package size?

Yes, the limit is 250 MB. However, it's extremely rare for packages to be that large. In fact, less than 3% of packages are larger than 10 MB (less than 0.1% are larger than 100 MB). I am curious about what your scenario is if it is requiring large packages!

> Is there any restriction on packages count to upload under my nuget.org account?

There is no restriction.

> How to get staging server source to upload the test packages via CLI ?

I'm not 100% sure what you mean here. We have a staging instance of the NuGet gallery here:
https://int.nugettest.org/

This can be used for integration testing with NuGet.org.

I would recommend avoiding using NuGet.org as a destination for all of your CI builds. This is noisy for package consumers since many CI builds are not significantly different enough for a consumer to need a package update. I would think of NuGet.org as a place to put notable releases of your package. Other 3rd party NuGet servers (such as [VSTS](https://docs.microsoft.com/en-us/vsts/package/overview) or [MyGet](https://www.myget.org/)) would be more appropriate for CI builds consumed by your internal team or enterprise.

Please let me know if you have any other questions.

**Comment by GanesanRengasamy** [comment]
Hi @joelverhagen 

Thanks for the response.

I have another question regarding this.

Is there possible to upload the updated NuGet package (v1.2) which is already uploaded by the another user with the same NuGet package id but the version is v1.1?

**For Example :** I need to upload the latest/updated package with the **id - "MySamplepackage** and **version - 1.2** under my nuget.org account. But this **package ID(MSamplepackage)** has been uploaded by the another user under his account with the lowest **version 1.1**

In this case can I upload the latest/updated NuGet package under my account.

Thanks,
Ganesan R.

**Comment by joelverhagen** [comment]
Hey @GanesanRengasamy, unless you are a co-owner of the package, you are not allowed to push new versions. The existing package owner can add you as a co-owner.

**Comment by joelverhagen** [comment]
If you have further questions about NuGet.org, please feel free to contact support@nuget.org.

**Comment by nietras** [comment]
Hi, with more and more ML workloads and NVidia dependencies we are very often hitting this limit and there is no way around it since some NVidia files are >600MB for a single file alone, as shown below.

![image](https://user-images.githubusercontent.com/10798831/127494497-03133f37-180e-4dae-87ff-b0905ee26749.png)

This means one cannot make nuget packages for such dependencies **at all** due to the very low 250MB size limit it seems.

What can I do to get this on nuget?

Note even with `Ultra` compression for `zip` format using 7-zip this cannot get below the 250MB size limit, so even if we worked around the poor compression of nuget.exe we wouldn't be able to put this on nuget.org.

![image](https://user-images.githubusercontent.com/10798831/127497252-3dab9837-03cb-43ec-bbc9-f360476cb236.png)

**Comment by SanftMonster** [comment]
I agree with nietras. Though as some developers said, most of the packages have size smaller than 10M, it's still disappointing that a package has a size limit of 256M. Machine learning packages are very easy to be larger than 256M. For example tensorflow 2.11 linux dynamic library of CUDA is more than 800M. Even after compression of NuGet, the package size is still around 400M. Due to the size limit, some projects have to let users download the binary file and place it in right directory. What a mess!

The issue was opened at 2017. Now that 6 years passed, shall we consider enlarging the size limitation?

**Comment by joelverhagen** [comment]
@nietras and @AsakusaRinne, this is a NuGet.org related issue so I'm move the issue to NuGet/NuGetGallery. Feel free to upvote this issue so we can gauge its priority w.r.t. to our other requests: https://github.com/NuGet/NuGetGallery/issues/9473. 

Let's try to avoid commenting here in the future since it causes notifications for the NuGet client team and the root of the problem is on NuGet.org, not in the client software.
