### ISSUE TITLE
Question: Complete example project of Visual Studio 2017 csproj nuget package including build

### ISSUE THREAD

**Issue by jhermsen** [NuGet/Home#6216]
Going a bit crazy with all the searches on google so I’m finally posting here sorry.

I’m looking for an example visual studio 2017 project for building a nuget package.
This package should include a .targets file in a way that it is installed by the package and imported/made available in the installing project. 
Meaning I can use the build targets from my nuget package.

What I found was that in nuget 2.x it would use a build folder and import tag in the csproj, but now it should work differently and I can’t find how.

**Comment by jainaashish** [comment]
`What I found was that in nuget 2.x it would use a build folder and import tag in the csproj, but now it should work differently and I can’t find how.`

Even with nuget 3.x targets should still be inside build folder, just that instead of being directly included in csproj, they are imported as part of `{projectName}.projectFileExtension.nuget.g.targets` file. Look at below resources, they should give you more details:

https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

**Comment by jhermsen** [comment]
Oke thanks got it working now.
One more thing, I used the following is .csproj to include build files is this the recommended way?
```
<Content Include="build\*.*">
  <Pack>true</Pack>
  <PackagePath>build;</PackagePath>
</Content>
```

**Comment by StingyJack** [comment]
"the classic project format which has limited support for wildcards and globbing." 

...was something said to me recently during an exchange with msft on a support issue. Im still waiting for details on the specific limitations.

**Comment by rohit21agrawal** [comment]
@jhermsen yes that's the correct approach :) 

Closing this for now as a question, but please feel free to ask more questions and we will be happy to help.
