### ISSUE TITLE
bad timestamp on DLL when calling nuget pack on nuspec file

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#624]
issue ported from codeplex: https://nuget.codeplex.com/workitem/4412

> When using NuGet.exe Pack with a nuspec file, referenced files get bad file timestamps. 
> For repro, see this link:  https://github.com/SuaveIO/suave/issues/190 
> 
> I verified that the exe is not modified by re-downloading from this homepage, and they both match SHA1 sum 59b6ea549690ed9728572023576ba0685ce1cc5d.
>
> Screenshot: https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=nuget&WorkItemId=4412&FileAttachmentId=1408127

**Comment by haf** [comment]
@xavierdecoster Thank you!

**Comment by haf** [comment]
Any updates on this??

**Comment by haf** [comment]
Only a year left now.

**Comment by pavelhritonenko** [comment]
Nuget package 0.31.2 have this issue again: https://api.nuget.org/packages/suave.0.31.2.nupkg

![image](https://cloud.githubusercontent.com/assets/2510026/10243292/49520d66-6900-11e5-8114-21a2a379b0ad.png)

**Comment by yishaigalatzer** [comment]
@haf sorry, but this was not a high priority item, given all the other work that was going on. I hope we can get it when we start "really" supporting pack on linux/mac in the next release

**Comment by haf** [comment]
I think it's absolutely absurd you don't fix this faster and for me that has bought you a lot of badwill. Maybe you don't care, what do I know. Or maybe you have a PM from hell who won't let you work on what matters for the community, what do I know.

**Comment by yishaigalatzer** [comment]
Sorry you feel this way, we do have to prioritize our work and the last 6-8 months where spent on stabilizing nuget 3, which affected a much larger set of customers than folks packing on Linux/Mac. This is not caring or ignoring what matters, but a simple case of there are much bigger burning items to deal with.

Going forward: Unfortunately NuGet on mono was never fully supported, and we plan to make NuGet on CoreCLR a first class citizen going forward, so I hope that will make things better.

You might not be aware that you can contribute code to NuGet (if you have the time, skills and desire), that's a big part of what community members of NuGet do to unblock scenarios where we might not choose to act on right away.

Again sorry you feel this way, we obviously want this fixed, as we attempted to get it done in this release but never got to it.

**Comment by haf** [comment]
> we have to prioritize our work

Yes, but you could at least reply to the bug report.

You could have moved the bug report when you moved the first time.

You could have triaged the bug right when you got it.

> stabalizing nuget 3

For no apparent reason, since NuGet 3 doesn't seem to have _anything at all_ that brings package management up a notch on the .Net platform.

> larger set of customers

You don't have a larger set of _active_, _caring_ customers who have [61 nugets published](https://www.nuget.org/profiles/henrik%20feldt) _for free_. So don't give me that bullshit about larger set of customers.

> mono was never fully supported

Sounds like a rationalisation to me.

> make NuGet a first class citizen on CoreCLR

By killing off the competition and complecting building with package management. And by implementing an **insane** resolution algorithm that tries to keep dependency versions _down_ instead of _up_.

> You might be aware that you can contribute code to NuGet

Yes, I'm very aware of that, but if I don't get replies, if my use case "is not fully supported", then why should I? Did you ask the community before you set off a one year+ sprint to finish v3 that noone asked for? No, you didn't.

> choose to act on

Indeed.

No, I don't really think you _are_ sorry that I "feel this way".

**Comment by haf** [comment]
Ping

**Comment by yishaigalatzer** [comment]
We are starting a rewrite of pack shortly. It is going to be natively supported in Linux and mac through coreclr, which is why we are not touching the old code base yet. @emgarten please take this issue into account on both NuGet.exe and xplat nuget.exe.

Timeline wise, we planned to start this week but the work on xplat restore did not conclude yet.

As FYI - we did fix the extraction part that would overwrite time stamps. And it is available on the nightly build feed

**Comment by toddm** [comment]
This seems to be fixed now in the latest builds now that the rewritten XPlat NuGet supports the pack command.  http://myget.org/gallery/nugetbuild
