### ISSUE TITLE
Enhancement Suggestion: Write Hints as $(SolutionDir).

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#6245]
All versions of Visual Studio.
All versions of Nuget.

When adding a reference to the package dlls to the csproj file, the hint path is typically written as
`..\..\packages\*`

I suggest that the hint path be written as
`$(SolutionDir)\packages\*`

This change will make locating the packages folder independent of a specific relative path and depth.

**Comment by jainaashish** [comment]
We're moving from `packages.config` world to `PackageReference` which has better performance, supports transitive dependencies, and other stuff which also get rid of this since it doesn't add separate assembly references. Since our focus is on PackageReference for now, we won't be able to get to this hence I'm closing it as wont' fix. If community feels otherwise, then we can reevaluate it.
