### ISSUE TITLE
Limit maximum package cache size

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#6261]
My organization is a heavy user of NuGet for distributing pre-built C++ & .NET libraries. This works very well, but we sometime struggle with the package cache growing to unreasonable sizes (>100GB) over time. This is causing problems for CI nodes and laptop users with limited disk sizes.

More specifically, we're observing that the `C:\Users\user\.nuget\packages\` folder contains both the nupkg as well as unzipped version of all versions of all nuget packages ever downloaded for a given user. This does not scale very well for users downloading >100MB of new nuget packages every week.

Would it be possible to implement some sort of "maximum cache size" parameter that can be used to limit the maximum amount of disk space used for nuget caching?
Alternatively, a "maximum package version" parameter to limit the number of versions cached for a given package?

**Comment by jainaashish** [comment]
The reason this folder has both nupkg ans unzipped version because this is also used as global packages folder so that there are no more duplicate copies of the same package across multiple solutions. But I do realize this could be an issue with machines with limited disk space. And we already have tracking issue to come up with better plan to age out packages or specific versions.

Although for your case, you can have a scheduled task or utility which clean up this folder every once in a while. or just clean it via Visual studio once in a while.

**Comment by forderud** [comment]
We're already dealing with the problem by manually purging the nuget cache, so I'm not asking for a "quick fix". What I'm requesting are some changes to prevent the cache from growing "too large" in the first place.

**Comment by herebebeasties** [comment]
> And we already have tracking issue to come up with better plan to age out packages or specific versions.

Any chance of a link to that issue? Closing out a ticket reporting unbounded disk space usage as "by design" doesn't seem right.

**Comment by zivkan** [comment]
I guess this is it: https://github.com/NuGet/Home/issues/4980
