### ISSUE TITLE
File Tag in nuspec file bring content files into packages.

### ISSUE THREAD

**Issue by qianghuang1** [NuGet/Home#6265]
## Details about Problem

NuGet product used : NuGet.exe

NuGet version:4.1.0.2450

VS version (if appropriate): 2015 enterprise updates 3

## Detailed repro steps so we can see the same problem
The structure of build results under `bin\Release` folder
```
Areas/**/*.cshtml
Views/**/*.cshtml
aaa.dll (The project assembly)
xxx.dll
```
Originally, i just want `aaa.dll` into my nuget packages, so the `.nuspec` file is like following:
```
<files>
</files>
```
Only `aaa.dll` is included. (The content files are excluded somehow)
Now i want to add `xxx.dll` as well.
Modify `.nuspec` file to 
```
<files>
<file src="bin\Release\xxx.dll" target="lib\net451" />
</files>
```
Not only `xxx.dll` but all `*.cshtml`  are copied into nuget packages.
Why the change of `file` Tag brings content files?
Or is there any way i could exclude those content files?
Thanx!

**Comment by jainaashish** [comment]
It seems you're doing the right thing. Can you also try with `exclude` if that solves it? try something:
<file src="bin\Release\xxx.dll" target="lib\net451" exclude="**\*.cshtml" />

@rohit21agrawal do you see anything wrong with this?

**Comment by rohit21agrawal** [comment]
what exact command are you using to pack?

**Comment by qianghuang1** [comment]
Hi, @jainaashish, I tried exclude, not working.
Hi, @rohit21agrawal i just use `nuget.exe pack --version MYVERSION`

**Comment by rohit21agrawal** [comment]
is there a csproj in the directory where you are running nuget.exe pack?

**Comment by qianghuang1** [comment]
Yep, and its `.nuspec` file

**Comment by rohit21agrawal** [comment]
any chance you can attach a repro project here so we can investigate? Also, suggest downloading latest nuget.exe from https://dist.nuget.org/win-x86-commandline/v4.5.0/nuget.exe

**Comment by qianghuang1** [comment]
Sure, i will post it here when project gets pushed

**Comment by rohit21agrawal** [comment]
@Tony-HQ here is what i found (but for the life of me i can't find the documentation):

If you are packing your csproj with a .nuspec next to it, then the content files from your project will be added if one of the condition is met:

1) There is no nuspec file
2) There is a nuspec file but no files node.
3) There is a nuspec file with non-empty files node.

The only way to prevent content files from your project to be added into the package is to specify an empty files node.

If you instead want more control over the behavior, pass the nuspec as a parameter to the nuget pack command instead of letting it use the csproj.

Does that make sense?

**Comment by qianghuang1** [comment]
Yep, got it. I will pass the nuspec file instead of using both (default). Thank you so much!
