### ISSUE TITLE
Nuget packages are not installed in the path specified in nuget.config file

### ISSUE THREAD

**Issue by Aman3030** [NuGet/Home#6269]
Description:
When creating a solution I want all my nuget packages installed in a specific location so I created a solution-wide nuget.config file -> [nuget.zip](https://github.com/NuGet/Home/files/1538652/nuget.zip) and did a dotnet add package "bla bla bla", It went ahead and installed all of the packages in the user.nuget\packages.

Steps to reproduce :
1. Create a new project -> dotnet new classlib
2. Create a new nuget config file in the same folder -> dotnet new nugetconfig
3. Add repository path key and value in the config file.
4. Add a package reference -> donet add package MongoDB.Driver

Expected behaviour :
The packages should be installed in the path mentioned in the local nuget.config file

Observed behaviour :
Installation of nuget packages is done in the default user.nuget\packages path.

**Comment by jainaashish** [comment]
`repositoryPath` is only applicable for `packages.config` based projects, but since you're using net core project which uses `PackageReference` to manage NuGet dependencies so it's still installing in default user profile location. You should instead use `globalPackagesFolder` property to set a different packages folder for `PackageReference` based projects.

You can find more details in your documentation [here](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file). Please follow these documents to understand the right usage of these properties and let us know if you see anything wrong or missing.
