### ISSUE TITLE
[NuGetizer]Doesn't work with multitargeting projects

### ISSUE THREAD

**Issue by iskiselev** [NuGet/Home#6277]
I'm trying to add reference to multi-targeting (netstandart2.0,net40) project to my nuproj. As soon as I do it, my attempt to build nuproj fails with: C:\projects\Nugetizer.Expirement\ClassLibrarySdkMulti\ClassLibrarySdkMulti.csproj : error MSB4057: The target "GetTargetPath" does not exist in the project.

Nugetizer was installed yesterday from http://bit.ly/nugetizer-2017, NuGet.Build.Packaging package version 0.2.2, Visual Studio 15.5.
Is it supposed to work?

**Comment by rohit21agrawal** [comment]
@kzu

**Comment by kzu** [comment]
Hey @iskiselev could you try the latest nugetizer and see if it works for you? I'm using it in two quite complicated packaging scenarios (https://github.com/kzu/avatar and https://github.com/moq/moq) and it's working just fine with multitargeting from a packaging project (I'm using .msbuildproj as the packaging project now, since it has built-in support in VS).
