### ISSUE TITLE
Make it easier to remove packages that are unused by projects.

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6284]
Package A1 references dependencies D1, D2, and D3. 

When A1 is installed, D1, D2, and D3 are also installed. 

- When A1 is removed, the D packages remain. 
- If upgrading to A1 v2.0 and it no longer requires D3, D3 remains referenced in the project

This leads to a bunch of orphaned dependency packages cluttering up the project, that require special tooling (R# - remove unused references) to determine if they are necessary still. 

Is there a way to define removal of dependencies in the nuspec?  ~~The option is no longer in the VS UI.~~ Glad to see that regression got fixed finally.

**Comment by jainaashish** [comment]
There is a check box on VS UI to remove dependencies when you try to uninstall a package. Similar option is there while you uninstall from PMC `RemoveDependencies` is that what you're looking for or something else?

**Comment by StingyJack** [comment]
the checkbox returning to the ui is nice.  if it defaulted to checked that would be better. some way to have the nuget ui remove unused packages later, should the checkbox not have been checked, would be best

**Comment by jainaashish** [comment]
I see your point, but the reason is not checked by default is, since all the dependencies are also explicitly installed into project and customer might be referencing those explicitly. And if we remove those by default, then it will break their scenario, which is why users have choice to remove all the dependencies if they want to.

It's a good suggestion to remove unused packages, but a hard problem to crack since it's really vague to identify which packages are unused. There are n different ways to consume a package. So for now, I'll say lets keep it this way until it really becomes a major issue for the community and then see what best we can do here.

**Comment by StingyJack** [comment]
If its the VS nuget UI, can you tap into "Find all References" or just scan for the namespaces in the dependency being used in the project?  It could even be a background or build server operation to identify them. Maybe I just want unused code identification to be more aggressive /shrug

I do end up with extra libraries and every one of them is more deployment footprint and surface area for  potential bugs (an assembly binding redirect for SqlServer Types was the latest trigger of this, the assembly wasnt needed anymore but the binding redirect applied to the config file pointed to a different version of the assembly), 

I think those extra bits are the problem I'm interested in eliminating, and seeing as how most of them come from orphaned nuget dependencies, trying to stem them at that point makes more sense.

**Comment by rrelyea** [comment]
Thanks for the feedback. Yes, it would be nice if we can make it easier to understand which packages are actively being used by a project. 
Putting into backlog.

**Comment by rraallvv** [comment]
Could someone please tell me whether this VS UI option is available on Mac? Thanks.

**Comment by StingyJack** [comment]
ui is different on the Mac, but does have a remove [option](https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough#nuget-in-visual-studio-for-mac). Neither have the thread topic.

**Comment by rraallvv** [comment]
@StingyJack Thanks!

**Comment by wstaelens** [comment]
I have a project and after refactoring the project. It contains a lot of packages that I don't know if they are still used or not. Can't see it anywhere.

**Comment by StingyJack** [comment]
@wstaelens  - R# has this covered by ["Remove unused references" and an "Optimize References"](https://www.jetbrains.com/help/resharper/Navigation_and_Search__Finding_Usages__Optimizing_References.html). The only catch is that I have to run it externally to a nuget package removal, as nuget does not take care of this itself. 

> @rrelyea changed the title from "Removing a nuget package should also remove dependencies if they are not used by anything else" to "Make it easier to remove packages that are unused by projects."

@rrelyea - That title changed the topic from something specific to something less specific - whats the reason for watering it down like that?

**Comment by wstaelens** [comment]
@StingyJack not an R# user. 
I just want to have an overview of nuget packages not being used…

**Comment by StingyJack** [comment]
@wstaelens - a [caveman approach](https://stackoverflow.com/a/48700299/16391) then perhaps? XD

There are a few other vs extensions that will visualize (and can remove) unused refs, but R# is about as close as you can get to viewing them as NuGet packages.  Enterprise VS doesn't even have a tool for this.

**Comment by wstaelens** [comment]
Why does it need to be a commercial extension just for something basic.
With this roslyn and core sh*t the only thing it does is loading and loading packages. Spent my day with fixing package conflicts and fixing references. Removing and reinstalling package by package. Very productive Microsoft....

**Comment by rraallvv** [comment]
Even Android Studio has it :smirk:

**Comment by daiplusplus** [comment]
I'd like to add that the "Remove dependencies" checkbox (and the `-RemoveDependencies` command option) doesn't work if other top-level project dependencies depend on a descendant dependency of the package you're wanting to remove.

In my case, I want to remove Microsoft Application Insights from my ASP.NET project. Here's my painful journey:

1. VS > Package Manager Console.
1. (Ensure correct project is selected in console toolbar)
1.  `PM> Uninstall-Package Microsoft.ApplicationInsights`
1. Error:

        Attempting to gather dependency information for package 'Microsoft.ApplicationInsights.2.12.0' with respect to project 'OhGodEverythingIsTerrible', targeting '.NETFramework,Version=v4.7.2'
        Resolving actions to uninstall package 'Microsoft.ApplicationInsights.2.12.0'
        Uninstall-Package : Unable to uninstall 'Microsoft.ApplicationInsights.2.12.0' because 'Microsoft.ApplicationInsights.DependencyCollector.2.12.0, Microsoft.ApplicationInsights.PerfCounterCollector.2.12.0, Microsoft.ApplicationInsights.Web.2.12.0, Microsoft.ApplicationInsights.WindowsServer.2.12.0, Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.12.0' depend on it.

1. "Okay, I don't want to manually remove each one, let's try this:"
1. `PM> Uninstall-Package Microsoft.ApplicationInsights -RemoveDependencies`
1. Error:

        Attempting to gather dependency information for package 'Microsoft.ApplicationInsights.2.12.0' with respect to project 'OhGodEverythingIsTerrible', targeting '.NETFramework,Version=v4.7.2'
        Resolving actions to uninstall package 'Microsoft.ApplicationInsights.2.12.0'
        Uninstall-Package : Unable to uninstall 'Microsoft.ApplicationInsights.2.12.0' because 'Microsoft.ApplicationInsights.DependencyCollector.2.12.0, Microsoft.ApplicationInsights.PerfCounterCollector.2.12.0, Microsoft.ApplicationInsights.Web.2.12.0, Microsoft.ApplicationInsights.WindowsServer.2.12.0, Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.12.0' depend on it.
1. "hmm, that didn't make any difference at all... let's try removing the platform-specific Application Insights package instead"
    * I note that this assumes you know which package is the real "root" package - which none of the built-in tooling will tell you. [People have to write their own programs just to get a dependency graph, which is ridiculous](https://stackoverflow.com/questions/6653715/view-nuget-package-dependency-hierarchy).
    * In my case, the package is `Microsoft.ApplicationInsights.Web`
1. `PM> Uninstall-Package Microsoft.ApplicationInsights.Web`
    * This worked - but it only removed `Microsoft.ApplicationInsights.Web` - all of the other `Microsoft.ApplicationInsights.*` package references are left behind and now orphaned, so tooling can't see that they were only referenced because `Microsoft.ApplicationInsights.Web` depended on them.
1. "Okay, let's re-run the command with `-RemoveDependencies`..."
1. `PM> Uninstall-Package Microsoft.ApplicationInsights.Web -RemoveDependencies`
1. Error (because the package is already removed):

        Uninstall-Package : Package 'Microsoft.ApplicationInsights.Web' to be uninstalled could not be found in project 'OhGodEverythingIsTerrible'

1. "So now I have to re-install the package in order to easily uninstall the rest? considering how much _damage_ the `ApplicationInsights` package installers do to my project (like mangling my `web.config` file) I'm going to say no. Instead I'm going to do a `git reset`. I shouldn't have to do this. What if I wasn't using source-control?
1. (After doing a `git reset` and VS doing a "Reload All"...)
1. `PM> Uninstall-Package Microsoft.ApplicationInsights.Web -RemoveDependencies`
    * "So this should _just-work_, right?"
1. Nope! Error:

        Attempting to gather dependency information for package 'Microsoft.ApplicationInsights.Web.2.12.0' with respect to project 'OhGodEverythingIsTerrible', targeting '.NETFramework,Version=v4.7.2'
        Resolving actions to uninstall package 'Microsoft.ApplicationInsights.Web.2.12.0'
        Uninstall-Package : Unable to uninstall 'System.Memory.4.5.3' because 'Microsoft.Extensions.Primitives.2.2.0, System.Collections.Immutable.1.7.0, System.Text.Encodings.Web.4.7.0' depend on it.

1. At this point I had to manually copy+paste the dependency lists for all of the `Microsoft.ApplicationInsights.*` packages to a spreadsheet (to keep track of them all) and remove them manually, one-by-one by doing the dependency-walking manually by hand. **What I thought would be a 30-second single command-line or GUI operation has turned into a 30-minute exercise in pain**. I actually (yes, literally) feel a spasm of pain every time I get the red error messages from the package-manager console because every time I see it it's because it rejected a command that a reasonably intelligent tool should be be able carry-out - it's the same kind of frustration you get when you deal with unhelpful customer service: you *know* they can do something, but it *isn't* because management/policy/Microsoft decided not to for some undefined, unexplained reason.

I need to invoice Microsoft for my blood-pressure medication.

## Related-but-unrelated rant:

Also, why on earth is the visual NuGet Package Manager UI seemingly so _inefficient_? Why can't it read all of my `packages.config` files and display that information instantly and then load data from the Internet? And why does it have to reload everything whenever I make even the smallest change? I especially dislike how I have to manually scroll to the bottom of the list for the UI to load the rest of the items. And this atrocious UI has been around for over 5-6 years now with no improvement. We'd probably all be better off if the Package Manager UI was removed and we were forced to use the command-line, at least that way the command-line UX would improve.

**Comment by StingyJack** [comment]
I would also like to remind @rrelyea and the nuget team that this should also include cleanup or regeneration of assembly binding redirects.

And that the new title does not match the request. Nuget should cleanup after itself. We arent asking that the Remove button be easier to click, we are asking for proper and complete removal of things that are no longer necessary to be included.

**Comment by StingyJack** [comment]
> Also, why on earth is the visual NuGet Package Manager UI seemingly so _inefficient_? Why can't it read all of my `packages.config` files and display that information instantly and then load data from the Internet? And why does it have to reload everything whenever I make even the smallest change? I especially dislike how I have to manually scroll to the bottom of the list for the UI to load the rest of the items. And this atrocious UI has been around for over 5-6 years now with no improvement. We'd probably all be better off if the Package Manager UI was removed and we were forced to use the command-line, at least that way the command-line UX would improve.

@Jehoel - You mentioned the one filename that will make the nuget team will completely disregard and ignore your entire post. They do not care about your (or my) existing code, or features we had and used, or the performance of the PM UI if you are going to use it for _that filename_.  They can say otherwise (and often do), but actions and behaviors tell a different story.

**Comment by zivkan** [comment]
I've been thinking about this (detect which packages can be removed) recently and started playing around with a prototype during my personal time.

It's very feasible to detect when a compiled assembly used types from a package's `lib` or `ref` assemblies. I think these make up most packages, so that's good.

I can't think of a way to possibly detect if a project uses content from packages (as in a nupkg's `content` or `contentFiles` folders). There's effectively infinite file types that could be content, and different file types have different usage patterns. So effectively no way to do a static analysis to determine if it's actually useful to the project or not.

Similarly, if a package contains a msbuild props or targets file, I don't know of a way to determine whether it's actually useful to the project. Since MSBuild is a scripting language, like any scripting language there's effectively infinite things that can be done. I don't believe there's a way with static analysis to determine with accuracy if the package is useful to the project.

So, while I'm having fun writing code to do static analysis of assemblies, I think this feature request has real feasibility issues.  I can imagine grouping the packages into 3 categories "used", "not used", "I don't know". But the pessimist in me fears users complaining that the tool/feature is useless if it marks too many packages in the "I don't know" category. One advantage of PackageReference and ASP.NET Core is that web asset packages are eliminated, which otherwise would have been a big source of packages too difficult to do static analysis to determine if used.

**Comment by StingyJack** [comment]
You can't really be citing fear of the unknown complainers as a reason for avoiding an attempt at cleaning up unused packages. 

I shouldn't have to go to a third party for reference cleanup.


Edit:
> One advantage of PackageReference and ASP.NET Core is that web asset packages are eliminated

That's may be an advantage for you design wise, but its not an advantage for users. In fact, it's one of the reasons I can't/won't use package reference. Its so "purist", it eliminated a significant utility aspect of private packages.

**Comment by erdembayar** [comment]
Latest VS2022 UI has follow option. 

![image](https://user-images.githubusercontent.com/8766776/144343069-b809eecb-ab81-4694-a690-1205c1107b82.png)
![image](https://user-images.githubusercontent.com/8766776/144343115-25fae2de-c98b-4efa-9bd1-db9e5b2cb78d.png)

@nkolev92 
fyi

**Comment by nkolev92** [comment]
Team Triage: Closing as this is a functionality that's available in the latest version of Visual Studio as per https://github.com/NuGet/Home/issues/6284#issuecomment-984220911

**Comment by alexander-lysenko-88** [comment]
Unfortunately `Remove Unused References`, mentioned in https://github.com/NuGet/Home/issues/6284#issuecomment-984220911, is not available for .Net Framework projects :(
