### ISSUE TITLE
Handle leak

### ISSUE THREAD

**Issue by PaulStovell** [NuGet/Home#632]
For some time we've had users reporting issues with querying NuGet feeds - it seems to be caused by the process running out of handles:

https://github.com/OctopusDeploy/Issues/issues/1071

Here's what we do:

1. We use NuGet.Core's `DataServicePackageRepository` to query NuGet packages
2. It makes a `HttpClient` or `RedirectedHttpClient`
3. This uses a `SendingRequestEventManager` which is a `WeakEventManager`, which is a `DispatcherObject`, which calls `Dispatcher.CurrentDispatcher`

Our app is a Windows Service which runs for long periods of time, with a HTTP frontend using Nancy, so each web request is handled by a thread from the thread pool. Unlike a WPF app, there's no dispatcher, so each thread gets its own dispatcher and weak event manager, which allocates handles. Over time, the number of threads recognised by the application will grow (i.e., thread ID 23, 24, 25...), so we'll be left with lots of weak event managers and dispatchers. 

Here's another description of a similar issue:

http://geekswithblogs.net/akraus1/archive/2014/02/04/155370.aspx

We'd be happy to help fix this and could contribute a PR if you'd give us some direction on the best way to fix it. Should we replace the WeakEventManager usage or have an overload that doesn't use it?

**Comment by yishaigalatzer** [comment]
What you are describing doesn't sound like a leak, it sounds like a manager per thread. Am I correct here?

The code is in nuget.codeplex.com and we plan to move it over the github shortly. Currently we are not accepting PRs for code that is going to ship in Visual Studio into the master branch because of legal issues, but you are more than welcome to fork, fix and we will gladly take it when the ship cycle for RTM is done. It doesn't matter if you start from codeplex or github, we are going to keep it all in sync for a while.

Another thought - You should probably consider recycling your process on a regular basis, this is something IIS does by default and we do the same in NuGet 3, such that slow leaks don't affect the viability of the process. This is not to say a fix is not a good idea, just a general architecture suggestion. I'm assuming the leak is slow and only shows up after days or many hours of running. You can never assume that none of your dependencies will not leak "stuff" be it memory, threads, handles or whatever else.

Last - We are planning to remove the OData client completely in the V3 release (or probably the V3.1 release), so this might become a very temporary fix.

Let us know what you plan to do, thanks for reporting this and thanks for putting up Octopus, we are big funs!

**Comment by yishaigalatzer** [comment]
Given that we are deprecating nuget.core, I don't see a reason to take this bug anymore
