### ISSUE TITLE
Is there a way to direct content files to an alternate root location (or alternate individual locations) within a project on installation?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6326]
I'd like to have some of the commonly used nuget packages like bootstrap, jquery, etc copy files to a specific subfolder within the project instead of the root of the project at `/Scripts` or `/Content`. 

Another example of redirection would be by asset type: like "all package fonts go to `/fonts/packageName`" instead of some going to `/fonts` and some to `/content/fonts`, likewise for `/images` that end up in many several places.  These packages dump files all over my projects and nuget does not deal well with wildcarding in the csproj so trying to manage them is not very fun. Being at the mercy of random-package-author-from-the-internet and hoping their package doesn't hose my project file system layout doesn't sit well either.

Is overriding this install path defined in the nupkg possible? If so, will it remove the package correctly during uninstall?

**Comment by emgarten** [comment]
Setting a location outside of the project root for packages.config content installs isn't possible currently.

This feature has also been requested for ContentFiles with PackageReference projects.

For packages.config this would need a way to track where the base path for the package was, set in either packages.config or the project file so that an uninstall or upgrade could determine where the files were to remove them. This would end up being a large change that is unlikely to happen for packages.config at this point.

**Comment by StingyJack** [comment]
Is there some reason you are treating functionality gaps/requests/handling differently between packages.config and packagereference? 

As a user I do not expect significant functionality differences between the two as they are both responsible for remembering what nuget packages are needed for a project.

**Comment by emgarten** [comment]
PackageReference has some fundamental differences from packages.config such as transitive dependencies, and resolving the complete dependency graph on each restore instead of having explicit install/uninstall actions. The two are very different, and essentially have different code bases within NuGet.

NuGet is both trying to move PackageReference forward, and make it easy to adopt by reducing the differences users will encounter when migrating and using older packages in PackageReference projects. Ideally users will not see the difference, just their dependencies, and everything will just work.

Having this feature for both would be great, but the two handle content differently. ContentFiles in PackageReference can be moved today using custom MSBuild to redirect the links from auto generated package imports. Content for packages.config is different since it is copied into the project.

**Comment by StingyJack** [comment]
Both are just different representations of the same intent, and both in xml (not that that matters). PRef only has transitive dependencies because it was added there. Aside from what has been added to each feature wise, is there really anything that limited the package config from doing all the same things?

I'm fine with scripting something for the near term, I just wanted to pick your brain on the topic cos it looks like more work with no visible benefit to MSFT (and that means less bugfixes and less shiny-but-useful things for us).

**Comment by emgarten** [comment]
> is there really anything that limited the package config from doing all the same things?

It would be a breaking change to packages.config. The two are very different and you can find more info on that in the docs.

Think of this way, PackageReference is packages.config with years of extra features. Use it! If you hit those breaking changes then you should be able to see why both still exist. A hybrid mode with transitive dependencies and just some of the features in packages.config doesn't work well, there are too many issues with it since packages.config relies on Visual Studio to handle most things and cannot run from the command line. Hope that helps explain it a bit better.

**Comment by StingyJack** [comment]
>  Use it! 

I did, back in Jan, And all I got was a few days worth of delays for me and others. Reference hint path battles, TFS 2015 builds wouldn't compile, VS outright crashing, duplicated references in sln explorer.  It was quite the mess when it was pushed as the default setting.

_I_ rely on visual studio, I wouldnt be doing .net projects with anything else (I've tried alternatives and buggy VS 2017 is still better), so I don't really care about packages.config being dependent on VS. I don't suffer this recent nostalgia (CLI all the things!) that has crept into our industry - Alt+T,N,N is preferable. I do eventually suffer from that kind of "oooh , shiny!" behavior when see all the holes in relatively new things I use daily that are unfixed after months or years.

If PRef is not going to suck in the future like it did earlier this year, then another attempt is warranted. I just dread it, because I'm still trying to convince some team members that web forms that perform ad-hod SQL queries (with no abstraction or parameterization, and only JS sanitizing user input) is probably not the best approach. I've just introduced nuget in the last year or so and its only now starting to catch on,
