### ISSUE TITLE
Package upgrade leaves a project in a broken state if the Content files build action was changed to EmbeddedResource

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6327]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.X

dotnet.exe --version (if appropriate):nope

VS version (if appropriate): 15.5.2

OS version (i.e. win10 v1607 (14393.321)): WIn 10.0.15063

Worked before? If so, with which NuGet version: dunno

## Detailed repro steps so we can see the same problem

1. Create new project (windows service for my case, but probably any other type will have the same problem)

2. Install a version prior to current for jquery, jquery ui, bootstrap, and jquery datatables 

3. Unload project file, change all those package files installed in step 2 to Embedded resources, kind of like this. 
```
  <EmbeddedResource Include="Content\\**\*.*" />
    <EmbeddedResource Include="fonts\\**\*.*" />
    <EmbeddedResource Include="Scripts\DataTables\*.*" />
    <EmbeddedResource Include="Scripts\bootstrap.js" />
    <EmbeddedResource Include="Scripts\bootstrap.min.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.intellisense.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.min.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.min.map" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.slim.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.slim.min.js" />
    <EmbeddedResource Include="Scripts\jquery-3.2.1.slim.min.map" />
    <EmbeddedResource Include="Scripts\jquery-ui-1.12.1.js" />
    <EmbeddedResource Include="Scripts\jquery-ui-1.12.1.min.js" />
    <EmbeddedResource Include="Scripts\jquery.dataTables.js" />
    <EmbeddedResource Include="Scripts\jquery.dataTables.min.js" />
```
4. Save the proj file and reload it. 

At this point you should be able to compile the project and get no complaints about missing files. 

5.  Run Update Packages for those packages and wait. 

The packages should declare update successful, if you go look at some of the project folders in solution explorer however, you will see duplicate asset files, like two `/Scripts/bootstrap.js` or duplicates of css files. The csproj file has most of the entries above but also has them as `<Content Include="..."/>`'s.

At this point its easier to unload and re-edit the proj file back to what was described in step 3, as the duplicates appear to just be phantom files.  Deleting from solution explorer actually deletes the physical file but doesnt delete both `<Content>` and `<EmbeddedResource>` project item nodes. 

Is there a less painful way to do this, or can nuget be a bit smarter about file handling ("a file is a file, don't look at the build action as if it would make it a different file when two files with the same name cant be in the same folder")

**Comment by emgarten** [comment]
As a rule NuGet avoids modifying content that was changed by the user. Removing these entries would break that and likely cause problems for other users if they are doing this.

When removing these files NuGet verifies that the contents of the file are the same as the original packages before deleting them. 

Potentially NuGet could check if other items in the project are referencing these files to ensure it is okay to update the package. However through the VS APIs used this isn't as obvious as it is when looking at the XML, and custom metadata would be lost, it wouldn't be possible to just update these paths to point to the new package. The fix for this would probably be to leave the content as-is if it saw EmbeddedResource links, and not update the package.

This would all be a major change to content for packages.config, so it seems unlikely a change in this area would be taken.

As a workaround I suggest adding a target to remove all Content items from the package and re-add the items as EmbeddedResources. This will let the original entries stay as-is but give you the result you are looking for in an upgrade safe way.

**Comment by StingyJack** [comment]
nuget should still understand that the project can only have one file of the same name in a directory, and that its performing an update not a remove + install. 

What kind of target do you mean, something like a gulp job or posh script?

**Comment by emgarten** [comment]
It would be an msbuild script

```xml
<ItemGroup>
  <Content Remove="<path>" />
  <EmbeddedResource Include="<path>" />
</ItemGroup>
```

Make this appears farther down in the file than the original Content item.

You can make it automatically find all files that start with JQuery

**Comment by StingyJack** [comment]
I will try that out now!

**Comment by mishra14** [comment]
@StingyJack Please let us know if you are still facing this issue.

**Comment by StingyJack** [comment]
That was totally easy, and worked. Thanks!

Is there a notification or diagnostic that would tell me if the nuget update is going to ignore specific user-modified files?

**Comment by emgarten** [comment]
There isn't a way to get notified of this unfortunately. NuGet also doesn't have a good way to look through all the referenced files from VS to check.
