### ISSUE TITLE
Nuget Restore "the request timed out" problem

### ISSUE THREAD

**Issue by botio** [NuGet/Home#6334]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget Client

NuGet version (x.x.x.xxx): 2.12.0.0

dotnet.exe --version (if appropriate): none

VS version (if appropriate): none

OS version (i.e. win10 v1607 (14393.321)): ubuntu 16.04 LTS

Worked before? If so, with which NuGet version: no, first time used nuget.

## Detailed repro steps so we can see the same problem

1. $ nuget restore 

Installing 'xxxxxx'
Installing 'xxxxxx'
Installing 'xxxxxx'
Installing 'xxxxxx'

The request timed out 
...

Tried so many times, I don't know how to fix this problem. Please helped me, thanks

**Comment by emgarten** [comment]
> NuGet version (x.x.x.xxx): 2.12.0.0

Try https://dist.nuget.org/win-x86-commandline/v4.5.0/nuget.exe

**Comment by botio** [comment]
.... how to try "nuget.exe" in ubuntu ....??

**Comment by botio** [comment]
hi, thank you, and after I used that version ... the new problem is 

"The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. "

do you know how to fix it ? thank you so much.

**Comment by emgarten** [comment]
Check your network connection and proxy settings.

**Comment by botio** [comment]
sorry, i don't get it. how could I know the proxy has some issues ? and I never change the setting from default in ubuntu 16.04

**Comment by mishra14** [comment]
@botio Are you using `nuget.exe` on linux?

If so, can you try running `dotnet restore` using [dotnet cli](https://github.com/dotnet/cli)?

**Comment by emgarten** [comment]
Closing due to lack of response

**Comment by kgrosvenor** [comment]
Was there a solution to this? I'm getting the same errors on GitLab CI and no way to get it to work currently, what is the issue exactly - i can call the file directly and grab it.

**Comment by le-jzr** [comment]
Same OS version, same issue. Running in VirtualBox. The file that times out can be downloaded using wget, curl or firefox on the same system, so it's not internet connection/configuration issue. Can't try `dotnet restore` because I was unable to find a version that can be installed. And before you ask, no, I can't update the OS, I need to work with two different legacy pieces of software, one is incompatible with newer system and one needs nuget to get dependencies. Any idea what I can do to make it work?

EDIT: I ended up copying the downloaded files over from a newer system and somehow it works. Not much of a "solution", but beggars can't be choosers...
