### ISSUE TITLE
[V2] Actions on missing packages result in error

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#635]
Upgrade and uninstall on a missing package shows package not found error.
Install works, but adds duplicate entry to packages.config if same package is installed.

**Comment by yishaigalatzer** [comment]
Install should just fail as well.

**Comment by harshgMSFT** [comment]
What is meant by a missing package? Is the package not installed ? Or not present at the selected source? Are there any specific repro steps?

**Comment by yishaigalatzer** [comment]
I believe it is missing from the source. But exists in the packages folder. You can email andriy directly as well for more details.

**Comment by harshgMSFT** [comment]
Repros in 2.8.6 except the install works as expected (does not add a duplicate entry).

**Comment by yishaigalatzer** [comment]
Good, so 2.8.6 is safe, lets fix 3.0

**Comment by harshgMSFT** [comment]
3.0 is already fixed it did not repro and here is why 
(https://github.com/NuGet/NuGet.PackageManagement/commit/54d3e1df748cd1910c11b985a8d4b181412a2386

https://github.com/NuGet/NuGet.VisualStudioExtension/commit/41e7428bd3eb8ddeb34b0c31c97550bc406014a6
)

**Comment by yishaigalatzer** [comment]
Is there still a way to get into this code path where two entries exist in package.config? Even if it involves manual removal of the package from the package folder

**Comment by AndriySvyryd** [comment]
It is still possible by installing a package that depends on a missing package:
1. Install jQuery
2. Delete the packages folder
3. Install jQuery.UI.Combined

**Comment by harshgMSFT** [comment]
Yes this repros in 2.8.6 and not in 3.0-rtm lets move it to 2.8.7

**Comment by rohit21agrawal** [comment]
Some findings :
1) NuGet installs the package into the Local Repository first, and then proceeds to add package references  to each of the project that the package was installed. This makes it extremely difficult to error out at the right stage because while installing the package to the repository it does not have context of the projects it is installing to, and by the time we are adding package references, the package is already present in the Local Repository.

2) One possible solution to this could have been to prevent NuGet from adding a duplicate entry to packages.config. This could have been achieved by checking if the package with same id is already in the packages.config file, but based on discussions with @rrelyea and @emgarten , there can be cases when there can two entries in a packages.config file with the same id. This rules out the possibility of this approach being a feasible fix.

3) Another solution could be to be more conservative and error out if any of the projects being installed to, has a missing package but has a corresponding entry in the packages.config. However, this might break a lot of other scenarios as per discussions offline.

Comments, suggestions?

**Comment by rrelyea** [comment]
talked with @yishaigalatzer - believes we should address in future release. so 2.13 it is.
