### ISSUE TITLE
[spec] Client policy specification for signed packages

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6426]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Package-Signing-Client-Policy

**Comment by rido-min** [comment]
We are simplifying the different modes, instead of 3: Dev, Secure, Strict we will reduce it to two: Dev and Strict. 

Thinking on the names, I'm proposing to use:

**AcceptSignedPackages**. This mode will allow unsigned packages, if any signature is found it will try to verify. If the verification does not succeed it will install as unsigned unless there is a critical event like content tampered or revoked certificate, any other issue like untrusted certificate will install the package as unsigned, when that happens a Warning will be produced.

**RequireSignedPackages**. This mode will require that all packages are signed by a list of known certificates specified in the configuration file.
Repository Certificates are described in https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Config-schema-changes-to-enable-repository-signatures 
Author Certificates will follow the same convention.

**Comment by MichaelSteinecke** [comment]
Hello,

in our environment another mode would be helpful: DoNotValidateSignatures or Offline

We're developing in a LAN network, completely disconnected from internet, with a TFS Package Server as source. We're downloading new packages from nuget.org manually and install them on our TFS with push. When installing packages a signature validation is performed, but it will timeout with several retries as the certificate authority is not reachable. This can last for about one min per package to install.

As workaround, sometimes we're sniffing the communication with fiddler, download the certificates and revocation lists manually and install them on dev machines.

**Comment by rido-min** [comment]
@Torgrimm you can configure how NuGet verifies the certificate revocation status , see [this doc](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode) for more information.

If you want a complete disconnected environment (probably because security requirements) you can also overwrite the package signature with another one that is fully trusted in your environment. This will prevent anyone to change or replace the packages from your curated feed.

**Comment by rido-min** [comment]
The feature is complete and available in 4.9+, docs available in [here](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#trustedsigners-section).
