### ISSUE TITLE
[Question] How to check whether a package is listed with the NuGet catalog API

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#6435]
I'm using the [catalog API](https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages) and manually making HTTP requests/parsing the JSON in Python. How do I check whether a package is listed/unlisted?

I noticed that in the JSON for a particular package, such as https://api.nuget.org/v3/catalog0/data/2017.11.01.06.23.18/mapsuitedependency-oracle.11.0.0-beta002.json, there is a `"listed"` attribute. However, [the gallery](https://www.nuget.org/packages/MapSuiteDependency-Oracle/11.0.0-beta002) says mapsuitedependency-oracle is listed (searching for it turns it up), even though `"listed"` is `false` in the JSON. Additionally, some unlisted projects like this https://www.nuget.org/packages/NuGetPackageProject don't even have a `"listed"` attribute.

Based on the JSON responses, is it possible to decide whether a package is listed or not?

**Comment by joelverhagen** [comment]
Concerning MapSuiteDependency-Oracle, this is a case where the listed status changed over time.

There are at least two catalog leaves concerning this package:
[Leaf produced at 2017-11-01T06:23:18.3222319Z](https://api.nuget.org/v3/catalog0/data/2017.11.01.06.23.18/mapsuitedependency-oracle.11.0.0-beta002.json) - listed is false (earlier)
[Leaf produced at 2017-12-22T06:42:54.9637862Z](https://api.nuget.org/v3/catalog0/data/2017.12.22.06.42.54/mapsuitedependency-oracle.11.0.0-beta002.json) - listed is true (later)

As mentioned in the documents, catalog is an append only data structure which means to get the most up-to-date state of a package, you need to process in the events in order, beginning to end. You can use the [cursor concept](https://docs.microsoft.com/en-us/nuget/api/catalog-resource#cursor) to keep track of how much of the catalog you processed and a secondary store (like a DB) to maintain the latest, interesting state of the packages you care about. I've personally had a lot of luck with the `sqlite3` module in Python to maintain my application state. You can even store your cursor in there.

Concerning the NuGetPackageProject package, the latest catalog leaf is here:
https://api.nuget.org/v3/catalog0/data/2015.10.02.05.07.09/nugetpackageproject.0.1.0.json

This has a proper `"listed"` property set to false. The oldest catalog leaf is here:
https://api.nuget.org/v3/catalog0/data/2015.02.01.06.27.41/nugetpackageproject.0.1.0.json

This leaf has no `"listed"` property at all, as you mentioned. As states in the "package details catalog item" [documentation](https://docs.microsoft.com/en-us/nuget/api/catalog-resource#package-details-catalog-items), listed is an optional property. When not present, you can use the `"published"` property to determine the listed status. If the year is 1900, then the package is unlisted. This is in the docs but I admit it is pretty arcane. The reason this is the case is because the listed property was added after the catalog was last generated, meaning there are some old leaves without the property. We treat catalog leaves as immutable so this special case is required in client code.

Note that during your debugging, you can always find the latest catalog leaf per package by inspecting the package metadata (registration) for the package. For example, for MapSuiteDependency-Oracle:
https://api.nuget.org/v3/registration3/mapsuitedependency-oracle/index.json

**Comment by joelverhagen** [comment]
Hey @jamesqo, let me know if you have any other questions. If you have follow-up questions for this issue, please feel free to re-open.
