### ISSUE TITLE
All packages installed gives exit code 1

### ISSUE THREAD

**Issue by snaits** [NuGet/Home#6503]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx): 4.5.0.4651

Worked before? If so, with which NuGet version: 4.4.1

## Detailed repro steps so we can see the same problem

1. From command line, run nuget install "some packages.config"

2. Do it again, verify that output says "All packages listed in some packages.config already installed".

3. echo %errorlevel% - it now says 1.

If you do the above steps with nuget 4.4.1 %errorlevel% holds a value of 0.

**Comment by precisioninfinity** [comment]
Agreed, this is definitely a bug.  I updated NuGet.exe client from 4.4.1 to the recently released 4.5.0 and it's returning %ERRORLEVEL% 1 when "All packages listed in {0} are already installed." whereas 4.4.1 was returning %ERRORLEVEL% 0 for that same case. I don't know why because I looked over the code diff of InstallCommand.cs and doesn't look like anything has changed there that would cause this. 

Reading over all the reported issues and notes regarding error levels it doesn't look like this was an intended change either, and it should not be an intended change (all the packages still succeed, it's just in this case it's using the already downloaded cached versions of them).

This started breaking all our builds.  The weird thing is there is no error message.

**Comment by jimitndiaye** [comment]
I'm having this same issue (raised here https://github.com/NuGet/Home/issues/6505). All our builds are broken as a result.

**Comment by devlead** [comment]
Seems to be very similar to #6144

**Comment by emgarten** [comment]
I'll take a look. As mentioned https://github.com/NuGet/Home/issues/6144 was fixed in 4.5 and has the same repro steps. Before 4.5 `nuget.exe install` **always** returned exit code 0, even if the restore failed. In 4.5 the command will now fail with a non-zero exit code if an error occurred.

**Comment by PNI-GS** [comment]
But should the error code be not 0 even if all packages are already installed?

**Comment by emgarten** [comment]
> But should the error code be not 0 even if all packages are already installed?

Correct, that should be 0.

**Comment by PNI-GS** [comment]
Would it be possible to got this resolved in a hot fix vs. the next release?

**Comment by mayermart** [comment]
A Hotfix would be great, as all our CI Jobs run 'update -self' before the build and fail as a result.

**Comment by emgarten** [comment]
It looks like an older version of nuget.exe in the NuGet.CommandLine package was published to nuget.org yesterday. It does not contain the fix for https://github.com/NuGet/Home/issues/6144 

Download page version: 4.5.0.46**96**
NuGet.CommandLine package version: 4.5.0.46**51**

### Workaround
Use the actual 4.5.0 release version here: https://dist.nuget.org/win-x86-commandline/v4.5.0/nuget.exe  instead of the NuGet.CommandLine 4.5.0 package that was built before the fix was added.

### Fix
A new version of NuGet.CommandLine will be needed to fix this. Since some users already have the 4.5.0 package it will likely need to be 4.5.1 or higher.

**Comment by PNI-GS** [comment]
4.5.1 would be fine, as we use 'update -self' as part of our CI systems.

Side request: If we could also allow for a -version to the 'update -self' so we can override the version number in case of a similar issue in the future so we can just point to the last "working" version.

Thank you,

**Comment by emgarten** [comment]
@PNI-GS the best way to get NuGet.exe is to use the downloads page instead of update -self. You can specify an exact version in the URL or use latest.
https://www.nuget.org/downloads

Latest: `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`
4.5.0: `https://dist.nuget.org/win-x86-commandline/v4.5.0/nuget.exe`
4.4.1: `https://dist.nuget.org/win-x86-commandline/v4.4.1/nuget.exe`
Format: `https://dist.nuget.org/win-x86-commandline/v{VERSION}/nuget.exe`

**Comment by emgarten** [comment]
An alternative workaround, and suggested best practice here is to use `nuget.exe restore <packages.config>` instead of `nuget.exe install <packages.config>`.  

The *restore* command does the exact same thing, but does not have this issue.

`nuget.exe install` when given a packages.config runs the same code as `nuget.exe restore` but with  slightly different error handling since the command also handles installing a package id/version combination without a packages.config file.

**Comment by emgarten** [comment]
Moving to @rohit21agrawal for tracking. Please close this issue once 4.5.1 has been published on nuget.org.

**Comment by rohit21agrawal** [comment]
package has been pushed.
