### ISSUE TITLE
[NuGetizer] Questions about the build system

### ISSUE THREAD

**Issue by jp2masa** [NuGet/Home#6515]
NuGetizer is really interesting and I'd like to help, but I have a couple questions:
1. I see that `NuGet.Build.Packaging.Tasks` currently targets `net46`, so it won't work in the dotnet CLI, right? Will .NET Core support be added? (either by retargeting to .NET Standard or multi-targeting .NET Core too)
2. Will `NuGet.Build.Packaging.Tasks` be distributed as an MSBuild SDK? I think it would be the best way of shipping the build system, the only problem is that the NuGet SDK resolver was implemented recently (MSBuild 15.6), but would it make sense to support older versions?

cc @kzu

**Comment by kzu** [comment]
Hi @jp2masa, both very good questions!

1. Absolutely. When NuGetizer was started, .NET Standard 2.0 hadn't shipped yet. We'll retarget it at some point before v1
2. It makes perfect sense and I was planning on precisely that spike in the coming weeks. I think it makes sense to provide it both as an MSBuild SDK and a regular nuget package like now, so that people on older systems can still use it. The `nuproj` project system, which already supports only 2017+ would likely use the SDK version only, but upstream changes to CPS that will make that possible (related to Dependencies node) haven't shipped yet and are scheduled for some time during the 15.7 preview cycle.

**Comment by jp2masa** [comment]
Thanks for the answers.
