### ISSUE TITLE
allow project reference to override package dependency

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#6536]
This seems to be a regression of #4620, or a different case which was never fixed.

Repro steps:

- Check out https://github.com/dsplaisted/msbuild/tree/update-cli
- `build -skiptests -bootstraponly`
- Comment out the following in `src\MSBuild.Bootstrap\MSBuild.Bootstrap.csproj`:

```xml
    <ProjectReference Include="..\Framework\Microsoft.Build.Framework.csproj" />
    <ProjectReference Include="..\Tasks\Microsoft.Build.Tasks.csproj" />
    <ProjectReference Include="..\Utilities\Microsoft.Build.Utilities.csproj" />
```

- `msbuild /restore src\MSBuild.Bootstrap\MSBuild.Bootstrap.csproj`

**EXPECTED**: Successful build
**ACTUAL**: 

> C:\git\msbuild\src\MSBuild.Bootstrap\MSBuild.Bootstrap.csproj error NU1107: Version conflict detected for Microsoft.Build.Framework. Reference the package directly from the project to resolve this issue. 
 MSBuild.Bootstrap -> MSBuild -> Microsoft.Build.Framework 
 MSBuild.Bootstrap -> NuGet.Build.Tasks 4.7.0-preview1-4846 -> Microsoft.Build.Framework (>= 15.1.1012). [C:\git\msbuild\src\MSBuild.Bootstrap\MSBuild.Bootstrap.csproj]

**Comment by dsplaisted** [comment]
@emgarten

**Comment by emgarten** [comment]
Thanks for the issue @dsplaisted I was able to repro this. It look like this is happening because a project reference is overriding a package dependency. So the result is that a nupkg depends on a project (which is supported).

This should still be ignored since it isn't a downgrade. The fix would be to skip checking the version range constraint if the accepted type is a project here: https://github.com/NuGet/NuGet.Client/blob/0f15286764b44818ddc42a82f54f7fadef3c08e1/src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs#L381

I don't think this is a regression, just a very rare scenario.

**Comment by dsplaisted** [comment]
Thanks for investigating this.
