### ISSUE TITLE
NuGet package's content files are not copied to .NET Core project but are copied to .NET Framework project

### ISSUE THREAD

**Issue by sandersaares** [NuGet/Home#6548]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
4.5.0

dotnet.exe --version (if appropriate):
2.1.4

VS version (if appropriate):
2017 (15.5.6)

OS version (i.e. win10 v1607 (14393.321)):
Windows 10 1709

Worked before? If so, with which NuGet version:
Unknown

## Detailed repro steps so we can see the same problem

As prerequisite find or create a NuGet package with some content files, e.g.:

```
<files>
    <file src="**.ps1" target="content\scripts" />
</files>
```

1. Create a new .NET Framework class library project.
1. Install this package.
1. Observe that the content files (e.g. `scripts\*.ps1`) are added to the project.
1. Create a new .NET Core class library project.
1. Install this package.
1. Observe that the content files (e.g. `scripts\*.ps1`) are **not** added to the project.

This is a critical use case for NuGet packages for me and it appears not to work for .NET Core projects.

**Comment by emgarten** [comment]
packages.config projects use `content/`
PackageReference projects use `contentFiles/` 

You can find more about immutable content for NETCore projects here: https://github.com/NuGet/Samples/tree/master/ContentFilesExample

https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

**Comment by JackGrinningCat** [comment]
> packages.config projects use `content/`
> PackageReference projects use `contentFiles/`
> 
> You can find more about immutable content for NETCore projects here: https://github.com/NuGet/Samples/tree/master/ContentFilesExample
> 
> https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

Please add a disclaimer for all the incompatible cases. 

2019 I struggle to get all the cases right, can consume packages with ease between projects that use package.config, package reference, updates to .Net Core and copy-my-native-output-helpers like Baseclass.Contrib.Nuget.Output (which is my personal tip for anybody @emgarten ) and refrain from thinking that all development is broken after nuget 3.3 for me as none of my colleagues will change in the next 3 years because of back-compatibility with visual studio 2015 was needed.

**Comment by WeihanLi** [comment]
How to config for new project file?
I use the code below, you can find the source [here](https://github.com/WeihanLi/WeihanLi.Common/blob/dev/src/WeihanLi.Common.Logging.Log4Net/WeihanLi.Common.Logging.Log4Net.csproj#L20):

```
  <ItemGroup>
    <None Include="log4net.config" Pack="true" />
  </ItemGroup>
```

it works for .net framework apps, but it can not work for .net core apps

**Comment by DrPepperBianco** [comment]
Hey,

I have the exact same problem. The case is set to "Closed", but I didn't find the answer here.

Neither "files" nor "contentFiles" are copied to the project, if it is referenced.

So what is the solution then?

**Comment by jupaol** [comment]
Same thing here, **files are not being copied**. If this is indeed closed, can you guys post a simple fix/workaround please.
I tried with a combinarion of `<files>` and/or `<contentFiles>` sections
Also with different folder names: _content_ and _contentFiles_
Nothing seems to work.

**Target Net Core 2.1 Class library**
**Visual Studio 2017**

**NuGet source files:**
- XYZ.Analyzers.nuspec
- contentFiles
     - stylecop.json
     - main.ruleset


**Nuspec:**
```
...
<metadata minClientVersion="3.3.0">
    <contentFiles>
        <files include="**/stylecop.json" buildAction="Content" />
        <files include="**/main.ruleset" buildAction="Content" />
    </contentFiles>
    <dependencies>
      <dependency id="Microsoft.CodeAnalysis.FxCopAnalyzers" version="2.9.3" />
      <dependency id="Roslynator.Analyzers" version="2.1.0" />
      <dependency id="Roslynator.CodeFixes" version="2.0.0" />
      <dependency id="SonarAnalyzer.CSharp" version="7.15.0.8572" />
      <dependency id="StyleCop.Analyzers" version="1.1.118" />
    </dependencies>
</metadata>
...
```

**Command line to pack the NuGet**
```
nuget.exe pack .\XYZ.Analyzers.nuspec
```

**Client (after installing NuGet)**

```
...
  <ItemGroup>
    <PackageReference Include="XYZ.Analyzers" Version="1.0.11" />
  </ItemGroup>
...
```

**Result**:
Content files are not being copied.

**Comment by sandersaares** [comment]
As far as I can tell, this is simply not supported anymore by NuGet. I suggest you switch to NPM or a different package manager that can actually perform the complex task of delivering static files.

**Comment by DrPepperBianco** [comment]
After playing with the problem for a while yesterday, I solved it the following way: I added to the PackageReference the new Attribute "GeneratePathProperty" like this (remarks: My problem was, that I wanted to run a PS1 script in post build):

```xml
<PackageReference Include="NuGet.Package" Version="1.0.0" GeneratePathProperty="true" />
```

Then an MSBuild variable with the path is generated like this: "PkgNuGet_Package". (Leading with "Pkg" then the name of the package, but "." replaced with "_".)

Then I could use the files from the Package with this variable. In my case it was a PowerShell script:
```xml
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NonInteractive -Command .'$(PkgNuGet_Package)\Content\MyScript.ps1' -TargetPath:'$(TargetPath)'" />
</Target>
```

The reason for this is, that the new dotnet core approach is not to copy the files into the project, but keep them centralized (probably to prevent having multiple copies of the files in all projects) and link them to the project.

Similar problems with the files maybe can be solved in a similar way.

**Comment by sipsorcery** [comment]
+1 not being able to get the `contentFiles` to work.

My workaround was to use an msbuild `.targets` file to manually copy the files (I was already the `.targets` file for #8573).

In my `.nuspec` file I have the `files` node as below. The content files I want to copy to the output directory of applications consuming my nuget package are the ones corresponding to the final  element and the `media` directory.

````
  <files>
    <file src="nuspec\SIPSorceryMedia.targets" target="build\SIPSorceryMedia.targets" />
    <file src="nuspec\SIPSorceryMedia.props" target="build\SIPSorceryMedia.props" />
    <file src="x64\Release\*.dll" target="build\x64" />
    <file src="Win32\Release\*.dll" target="build\x86" />
	<file src="x64\Release\netcoreapp3.1\SIPSorcery.RtpAVSession.dll" target="build\x64" />
	<file src="Win32\Release\netcoreapp3.1\SIPSorcery.RtpAVSession.dll" target="build\x86" />
	<file src="SIPSorcery.RtpAVSession\media\*.*" target="media" />
  </files>
````

My `.targets` file is below. The second `ItemGroup` of `MediaFiles` is the one I am using to do the content file copy.

````
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <NativeLibs Include="$(MSBuildThisFileDirectory)\..\build\x86\*.dll" Condition="'$(Platform)' == 'x86'" />
    <NativeLibs Include="$(MSBuildThisFileDirectory)\..\build\x64\*.dll" Condition="'$(Platform)' == 'x64' or '$(Platform)' == 'AnyCPU'" />
    <ContentWithTargetPath Include="@(NativeLibs)">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  <ItemGroup>
    <MediaFiles Include="$(MSBuildThisFileDirectory)\..\media\*.*" />
    <ContentWithTargetPath Include="@(MediaFiles)">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>media/%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
</Project>
````

This approach works when building an app that uses the nuget package from Visual Studio or `dotnet` (as expected since they both use `msbuild` under the hood).

**Comment by bryandam** [comment]
FWIW, the info that @emgarten posted worked for me just fine.
If you just want any arbitrary binary content in the root of the project make sure it's in: root\contentFiles\any\any

Then add the following to your nuspec:

```
<contentFiles> 
      <files include="**/*.*" buildAction="None" copyToOutput="true" flatten="true" /> 
</contentFiles> 
```

**Comment by miloszkukla** [comment]
The contentFiles feature is supported as it is present in documentation. In my case the problem was putting content files directly into contentFiles directory. It seems it is not supported - files that are target framework/language independent must be placed into **contentFiles/any/any** directory (https://docs.microsoft.com/en-us/nuget/reference/nuspec#package-folder-structure). That's why **/* is used in examples because "the double wildcard ** implies a recursive folder search".

OP is trying to use the same approach to both .net core (so PackageReferences are used) and .net framework (so packages.config is used by default) which is incorrect according to:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files:

"Content files are included in a package using the <files> element, specifying the content folder in the target attribute. However, such files are ignored when the package is installed in a project using PackageReference, which instead uses the <contentFiles> element.
For maximum compatibility with consuming projects, a package ideally specifies the content files in both elements."

There is no example though so I'm not sure (I didn't tested) whether the following would copy content files to output in both cases (PackageReference and packages.config):

```
  <contentFiles>
    <files include="any\any\data.txt" buildAction="None" copyToOutput="true" /> <!-- include path is relative to contentFiles -->
  </contentFiles>
</metadata>
<files>
    <file src="data.txt" target="contentFiles\any\any" />
</files>
```
@emgarten Can you tell please if this would work for both cases?

**Comment by alex-jitbit** [comment]
So basically, if you want to copy files into a project's root folder, you have to:

1. pack them into "contentFiles/any/any" subfolder (telling nuget it's for "any" language and "any" framework
2. extract them using the `<contentFiles>` node

If you also want your nuget to work with older `package.config` mode - pack the file into "content" folder as before.

I've blogged all the details here: https://www.jitbit.com/alexblog/303-nuget-authoring-copying-content-files-into-you-project-folder/

**Comment by marisks** [comment]
I have tried all the different ways that are described here but nothing helps. Files are not copied over.
After installing the package, it creates a shortcut to the file which resides in the NuGet cache. But the framework I am using expects those files in a specific folder (which should be created by copying the files).

**Comment by brunofrancavalli** [comment]
Some of the answers here don't apply. The title of this issue is "[...] .NET Core project [...]" people are assuming .NET Core is the same as .NET framework to build NuGet package. the .nuspec file is not even supported in .NET Core, so how am I going to add parameters to it? .NET Core NuGet package build is horrible, you have not control over it. I have been trying to add certificate files to my NuGet file so they get deployed during the build for the last 3 months, and I am still unable to make it happen.

So we are trying to solve for .NET Core (also applies to .NET 5 and .NET 6) NuGet package creation. Just trying to add files to "Copy to output" by default when package is created. Any help would be appreciated.

**Comment by marisks** [comment]
@brunofrancavalli We have created a workaround that might help you. 
We have an MS build target file that copies the files on build:
https://github.com/Geta/geta-notfoundhandler/blob/master/src/Geta.NotFoundHandler.Optimizely/msbuild/CopyModule.targets

Then we include it in the csproj: https://github.com/Geta/geta-notfoundhandler/blob/master/src/Geta.NotFoundHandler.Optimizely/Geta.NotFoundHandler.Optimizely.csproj#L48-L55

And here is the way how we include the file that needs to be copied in the project:
https://github.com/Geta/geta-notfoundhandler/blob/master/src/Geta.NotFoundHandler.Optimizely/Geta.NotFoundHandler.Optimizely.csproj#L38-L46

**Comment by brunofrancavalli** [comment]
@marisks 
I had seen this 'hack' before, but it is nasty and I wanted to follow NuGet standards. And I didn't want my NuGet package to do the unexpected.

I have found the solution by creating a nuspec file for .NET core and running the NuGet pack command against the nuspec file instead. This way I bypass the new Visual Studio .NET Core/5/6 way of building packages.

**Comment by sudsy** [comment]
After trying many of the suggestions here, the only thing that worked for me was detailed in this post: https://blog.tonysneed.com/2021/12/04/copy-nuget-content-files-to-output-directory-on-build/

**Comment by saymastermind** [comment]
I first tried suggestion below from alex-jitbit, but the files in contentFiles became part of the build which I had to disable.
1. pack them into "contentFiles/any/any" subfolder (telling nuget it's for "any" language and "any" framework
2. extract them using the <contentFiles> node

I ended up using solution from DrPepperBianco which is cleaner.
    <PackageReference Include="NuGet.Package" Version="1.0.0" GeneratePathProperty="true" />

This is after hours of googling. Wish it could be easier.

**Comment by xiaoxstz** [comment]
> > packages.config projects use `content/`
> > PackageReference projects use `contentFiles/`
> > You can find more about immutable content for NETCore projects here: https://github.com/NuGet/Samples/tree/master/ContentFilesExample
> > https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html
> 
> Please add a disclaimer for all the incompatible cases.
> 
> 2019 I struggle to get all the cases right, can consume packages with ease between projects that use package.config, package reference, updates to .Net Core and copy-my-native-output-helpers like Baseclass.Contrib.Nuget.Output (which is my personal tip for anybody @emgarten ) and refrain from thinking that all development is broken after nuget 3.3 for me as none of my colleagues will change in the next 3 years because of back-compatibility with visual studio 2015 was needed.

How about .NET SDK project?

**Comment by RobertoArmas** [comment]
Hi I have a .NET Framework 4.8 project, this website project uses PackageReference. So I created the nuget package with contentFiles folder to add assets but when I'm installing using PackageReference method assets were not copied to the project root even if assets are on both folders content and contentFiles

**Comment by zivkan** [comment]
PackageReference and contentFiles copy files to the build output (`bin\`) directory on build. Since PackageReference was designed for .NET Core and the new simplified project files where customers are enabled to hand edit project files, rather than being limited to tooling, PackageReference no longer has the concept of (first) "install", which is when content was copied into the project with packages.config.

As the [packages.config to PackageReference migration tool docs](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#content-assets-are-not-available-when-the-package-is-installed-after-the-migration) say, PackageReference no longer uses the package `content` assets. If you want to share content in ASP.NET projects via NuGet packages, you'll need to stick with packages.config.

I don't know how usable ASP.NET Core's tooling is for ASP.NET projects, but when creating a new MVC app from the template, the `wwwroot\js\site.js` file has a comment with the URL https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification. I see LibMan in the table of contents, which I remember they created to try to give an easier experience for ASP.NET developers who are not familiar with npm in their build pipeline. Perhaps that can help you share your web assets.

**Comment by Ohlcdayton** [comment]
> After playing with the problem for a while yesterday, I solved it the following way: I added to the PackageReference the new Attribute "GeneratePathProperty" like this (remarks: My problem was, that I wanted to run a PS1 script in post build):
> 
> <PackageReference Include="NuGet.Package" Version="1.0.0" GeneratePathProperty="true" />
> Then an MSBuild variable with the path is generated like this: "PkgNuGet_Package". (Leading with "Pkg" then the name of the package, but "." replaced with "_".)
> 
> Then I could use the files from the Package with this variable. In my case it was a PowerShell script:
> 
> <Target Name="PostBuild" AfterTargets="PostBuildEvent">
>   <Exec Command="C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NonInteractive -Command .'$(PkgNuGet_Package)\Content\MyScript.ps1' -TargetPath:'$(TargetPath)'" />
> </Target>
> The reason for this is, that the new dotnet core approach is not to copy the files into the project, but keep them centralized (probably to prevent having multiple copies of the files in all projects) and link them to the project.
> 
> Similar problems with the files maybe can be solved in a similar way.





https://react-usecallback82.github.io/4WrcX1P0Z8IEFkrDFrlVzoy46NuhZbhgq-TRgKVG5HSUpqhiMxRtKHg/
