### ISSUE TITLE
Signing:  sign command fails to find untrusted self-issued certificate in certificate store

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6616]
NuGet.exe 4.7 preview (installed from https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine) fails to sign with a certificate if the revocation server is unavailable. 

4.7 should have the same behavior as 4.6, where the sign command succeeds but produce the next warnings:

```
WARNING: NU3018: The revocation function was unable to check revocation for the certificate.
WARNING: NU3018: The revocation function was unable to check revocation because the revocation server was offline.
```

**Comment by anangaur** [comment]
Btw, why two lines for the same warning code. It can be combined into one:
```
WARNING: NU3018: The revocation function was unable to check revocation for the certificate. Reason: The revocation server was offline.
```

**Comment by dtivel** [comment]
Chain building can return 0, 1, or many failure reasons.  NuGet logs each one separately.

**Comment by dtivel** [comment]
The issue has nothing to do with revocation.

The issue is that the sign command's certificate finding utility ignores untrusted certificates [here](https://github.com/NuGet/NuGet.Client/blob/74393a4d8e949cb81dc7f5a42703c1e451f5c403/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs#L142) and [here](https://github.com/NuGet/NuGet.Client/blob/74393a4d8e949cb81dc7f5a42703c1e451f5c403/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs#L146).
