### ISSUE TITLE
Question and help needed. What is best workflow when developing and consuming the nuget packages in the development environment!!

### ISSUE THREAD

**Issue by sherry-ummen** [NuGet/Home#6729]
I would like to know the best workflow when developing and referencing the nuget package in the development environment.

The scenario is that, we have a library which we want to move it to be a nuget package and then reference it in multiple .net solutions and projects. Currently the workflow I am thining is 
* Develop/modify the module
* Package it and increment the version of the nuget
* Publish it
* Search for all the projects which are using this nuget package and update its versions.

This I feel its a bit cumbersome, so do we have a better workflow? 

I found some stackoverflow post https://stackoverflow.com/questions/27711364/pain-free-local-development-while-also-referencing-nuget-packages

But it really did not help. So I wanted to know what is the best workflow to avoid the burden of always publishing, updating version, updating references etc.

We are using packages.config just to give more information.

**Comment by nkolev92** [comment]
Unfortunately, there's no smart way to do this in packages.config. 

If you were to move to PackageReference, you have multiple options though. 
One approach would be to use [floating ](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution)versions for packages you are confident you always want to use the latest version of. 

The [limitation ](https://github.com/NuGet/Home/issues/912)of that is that you can ask for either stable or prerelease packages, but not just the latest. 

Also due to transitivity, you don't necessarily need to specify the package in every project it's used, but rather only at the leaf projects. 
Due to the fact that PackageReference is integrated with MsBuild, it's easier to keep the versions in sync as well by using properties.

**Comment by sethreidnz** [comment]
Not to derail this thread, and I have nothing to do with this library either but it works great and I use it in my projects for the above which much less friction than the current supported way.

https://github.com/nwheels-io/NuLink
