### ISSUE TITLE
UWP Projects show individual references instead the UWP MetaPackage

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6868]
Affected Branch: 15.7
Affected Build:  27625.0
Affected Product Language: 

Steps to reproduce:

1. Create UWP
2. Change TPMinV=16299

Expected. Project is retargeted without errors.
Observed. The references are expanded with individual DLLs 

![image](https://user-images.githubusercontent.com/14916339/39317106-a536e748-492f-11e8-865a-7bbfb9a82361.png)

internal bug: [606826](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/606826)

**Comment by nkolev92** [comment]
Project-system is the one handling the reference nodes there. 

The only thing from NuGet side is whether the correct package is specified in the assets file. 
Since I was not able to repro on 27620 (I know yours is 27625 it's just the version I have installed) it'd be helpful if you can upload the assets file to help them investigate.

**Comment by rido-min** [comment]
Adding the assets file
[project.assets.zip](https://github.com/NuGet/Home/files/1952106/project.assets.zip)

**Comment by nkolev92** [comment]
Thanks @rido-min 
From NuGet side it all looks normal. I will copy the issue to the project system as I don't have rights to move it directly to their repository.

**Comment by nkolev92** [comment]
Copied manually to https://github.com/dotnet/project-system/issues/3491.
