### ISSUE TITLE
nuget.config source filtering by namespace

### ISSUE THREAD

**Issue by flcdrg** [NuGet/Home#7007]
I think it could be useful if you can specify for a particular source in nuget.config, what namespaces/names of packages should be queried for that source.

That way, if you had an internal NuGet source as well as the public nuget.org source, you could configure NuGet not to bother querying nuget.org for your internal packages.

eg. something like:

```
<configuration>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="TeamCity" value="http://build.local:8111/guestAuth/app/nuget/v1/FeedService.svc/" />
    <add key="MyGet Feed" value="https://www.myget.org/F/example/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <filters>
    <add key="TeamCity" value="MyPackages.*" />
  </filters>
</configuration>
```

With the above configuration, when NuGet was asked to restore a package named "MyPackages.Blah", it would only query the TeamCity source

**Comment by nkolev92** [comment]
//cc @anangaur 
A request for similar to the original lineups idea.

**Comment by nkolev92** [comment]
Hey @flcdrg,

Thanks for creating this issue. 
Given that it's been a while since this issue has been created and we haven't gotten a lot of additional enagement, I will merge this issue to https://github.com/NuGet/Home/issues/6867. 

The ask there is similar. The ability to define which package source a package should come from.
