### ISSUE TITLE
Nuget installed panel empty after VS 2017 update

### ISSUE THREAD

**Issue by srdjo** [NuGet/Home#7013]
I updated my VS to 15.7.3 version today and now my Nuget panel with installed packages is empty. Not empty but showing only System.Runtime.

I have a packages.config file in my project and everything worked just fine before the update.

I tried to downgrade VS to 15.5 version but the panel is also empty.

What can I do ?

**Comment by srdjo** [comment]
I tried deleting the .packages folder before installing the packages again via Nuget and the folder .packages was not created

My project path is C:\Users\User\Source\Repos\Project123-Git

Also I see that now I have a folder .nuget at C:\Users\User\.nuget that has the folder packages in it.

I also tried deleting the file packages.config but Nuget still has my newly installed packages even if packages.config does not exist

**Comment by jainaashish** [comment]
Can you provide a sample solution to see what issue you're facing? `.nuget\packages` is a global packages folder which contains all the NuGet packages which are being installed on your machine and later works as NuGet source so that it doesn't download it again.

If you deleted `packages.config` file and still see installed packages, then you might be using `PackageReference` in your project file to manage NuGet dependencies.

So providing a sample solution will help us understand your situation.

**Comment by srdjo** [comment]
The solution is too large to share - what files do you need so I can upload them to Pastebin ?

**Comment by srdjo** [comment]
I tried installing all of the packages again and after I installed a couple of them I saw this in References

![vs2017problem](https://user-images.githubusercontent.com/4582491/41280047-4a95e1f8-6e2e-11e8-8a2d-d57011716419.JPG)


Also Visual Studio is set to use Packages.config

**Comment by jainaashish** [comment]
This image shows that there is a presence of `project.assets.json` file under project's `/obj` folder which is why it's confused between `packages.config` and `PackageReference`. You might have migrated to `PackageReference` in one of your branch which generates `project.assets.json` file where as other branch still using packages.config file. So if you're using git then you can run `git clean -xdf` to clean all the intermediate files or just delete `/obj` folder and build again. That should work for you.

**Comment by srdjo** [comment]
I managed to fix it. Your suggestion guided me to the right path. I unloaded the project, opened the project file and removed all the PackageReference nodes from it. I then deleted the obj folder and Nuget started recognizing my packages again. Project now builds just fine. Thanks a lot @jainaashish
