### ISSUE TITLE
Nuget package installation continues if Init.ps1 fails

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#7039]
_From @jpsalada on June 14, 2018 17:4_

### Steps to reproduce

Install a Nuget package that executes an Init.ps1 script during the installation. The script ends with Exception (we use throw, and also tried Exit 1 or Exit -1), but the installation continues.

### Expected  behavior

We expected that the installation would fail upon Init.ps1 failure.  Basically we have dependencies on external binaries. If the binaries are not found in the system, installation should fail, as our Nuget is not usable.

### Actual behavior

Installation continues if Init.ps1 terminates with error.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.179.6572

OS info:
Windows 10
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio Community 2017 Version 15.7.3

_Copied from original issue: Microsoft/msbuild#3413_

**Comment by jainaashish** [comment]
@jpsalada what happens when you try to explicitly run this script in NuGet PMC console? 

By default NuGet executes these scripts asynchronously with package installation so instead of throwing, they just report those failures and continue. Although there is way to turn this async mode off by setting environment variable `NuGetSyncMode=1` so you can try this and see if that allows to throw on script execution failure?

**Comment by nkolev92** [comment]
@jpsalada Can you please answer @jainaashish's question?

**Comment by nkolev92** [comment]
Closing this as No Repro
