### ISSUE TITLE
[Signing] "IfExists" repository countersignature verification behavior is overridden by "repoAlllowListEntries" setting

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#7042]
Given the following settings:

```
new SignedPackageVerifierSettings(
    ...
    allowNoRepositoryCertificateList: false,
    verificationTarget: VerificationTarget.All,
    signaturePlacement: SignaturePlacement.Any,
    repositoryCountersignatureVerificationBehavior: SignatureVerificationBehavior.IfExists,
    repoAllowListEntries: new List<string> { "abc" });
```

If these settings are used to verify a package that has a primary author signature but no repository countersignature, the verification will fail with the error `NU3034` and the message:

> The package signature certificate fingerprint does not match any certificate fingerprint in repository allow list.

This is unexpected. If `RepositoryCountersignatureVerificationBehavior` is `SignatureVerificationBehavior.IfExists`, verification should not fail on packages with no repository signature regardless of the value of `SignedPackageVerifierSettings.RepositoryCertificateList`.

CC @dtivel and @PatoBeltran

**Comment by PatoBeltran** [comment]
Since https://github.com/NuGet/NuGet.Client/pull/2454, the verification provider in charge of validating allow lists has been refactored and this is not an issue anymore.

Now the user has to provide the allowList itself to the provider. This list is made of `VerificationAllowListEntry`, which include the `VerificationTarget` that each entry should be tested against.
