### ISSUE TITLE
[Test Failure] Installed SDK version show inconsistently between the PM UI of project and the PM UI of Solution

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7047]
## Details about Problem
NuGet version: NuGet Client Release-4.8.0-Preview3 4.8.0.5278
VS Version: D15.8 27820.00
OS Version: Windows 10 RS4_Release 17134.1.180410-1804

## Detailed repro steps 
1.	Create a solution with a C# Console App (.NET Core) and a C# Class Library (.NET Standard)’.
2.	Right-click each project in Solution Explorer, select ‘Manage NuGet Packages…’ and go to ‘Installed’ tab.
3.	Click menu Tools->NuGet Package Manager->Manage NuGet Packages for Solution and go to ‘Installed’ tab.

## Expected
Installed SDK version show consistently between the PM UI of project (step 2) and the PM UI of Solution (step 3).

## Actual
Installed SDK version show inconsistently between the PM UI of project (step 2) and the PM UI of Solution (step 3) as below screenshot.
![pmuiofproject](https://user-images.githubusercontent.com/20632625/41707983-f4ce5e78-752e-11e8-9630-c4e715a75b5c.png)
![pmuiofsolution](https://user-images.githubusercontent.com/20632625/41707992-f966cf2e-752e-11e8-8ca6-16313aee14a9.png)

## Note
It repro on D15.8 27709.01 (default NuGet Client 4.8.0.5222).

**Comment by jainaashish** [comment]
This is by design, Manage UI at solution level shows the latest version available in the list and the installed version on the right side (in detailed view of the package). This is because a package could have multiple versions installed across projects so we can pick a specific installed version on the left side but on the right side, we can show installed version for each project.
