### ISSUE TITLE
Source-Only NuGet packages add <Compile Include="..." /> to csproj, resulting in build errors.

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7053]
_From @btodts on June 22, 2018 11:41_

### Steps to reproduce
Install a source-only NuGet package, e.g. https://www.nuget.org/packages/TinyIoC/. Upon installation, this adds a file to your directory (in this case: `TinyIoC.cs`).

### Expected behavior
As per https://aka.ms/sdkimplicititems, I'd expect the SDK to pick this file up for compilation using the globs in the SDK properties, without modifying the csproj file.

### Actual behavior
A Compile element is added to the csproj file: <Compile Include="TinyIoC.cs" />, leading to a build error:
> Duplicate Compile items were included. The .NET SDK includes Compile items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file.

Manually removing the Compile element from the csproj everytime NuGet packages are installed, is less than desirable. Using `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` and `<Compile Include="**/*.cs" />` (again, as per https://aka.ms/sdkimplicititems), results in other build errors (e.g. `error MSB3105: The item "Foo.cs" was specified more than once in the "Sources" parameter).

_Copied from original issue: dotnet/sdk#2356_

**Comment by livarcocc** [comment]
I am going to move the bug to NuGet to see if it is possible to have some logic to detect and not add the compile item to the project due to globing.

**Comment by rohit21agrawal** [comment]
@btodts the package you refer to contains a "Content" folder, which contains a *.cs file. This kind of package only works with a packages.config based project, and it is by design that it would copy the cs file to the root of the project directory and add a Compile element to csproj.

Are you using a packages.config based project or a PackageReference based project? Could you share your csproj file with us?

**Comment by btodts** [comment]
@rohit21agrawal Neither :) I'm actually using [Paket](https://fsprojects.github.io/Paket/) as my dependency manager. Your comment made me reconsider, I've opened an [issue](https://github.com/fsprojects/Paket/issues/3269) in Paket's repository since it's probably related to their install process.

I suppose this issue can be closed.

**Comment by rohit21agrawal** [comment]
thanks for the clarification @btodts

**Comment by btodts** [comment]
@rohit21agrawal While trying to reproduce the issue, I found that the file now doesn't get copied anymore when using .NET Core. 

Attached, you can find an ASP.NET Core Web Application that includes the `TinyIoC` package. However, when installing the package, the file is not copied to the project directory.

This is the case when using a 'plain' ASP.NET Web Application (_not_ Core): when running e.g. `Install-Package TinyIoC`, a file `TinyIoC.cs` is added to the project.

I can open a new issue for this, if you wish.
[repos.zip](https://github.com/NuGet/Home/files/2170228/repos.zip)

**Comment by btodts** [comment]
Ping! Anybody there?
