### ISSUE TITLE
Flatcontainer - Download package manifest nuspec

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#7065]
The API docs specify a .nuspec is downloadable from the flatcontainer API:
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-manifest-nuspec

We would like to learn which NuGet client is making use of this endpoint.

**Comment by mishra14** [comment]
@NuGet/nuget-client  Does anyone know if we use that endpoint?

**Comment by emgarten** [comment]
As far as I know this isn't used. The nupkg is always downloaded and the nuspec is read from the local nupkg.

The flatcontainer format was meant to be identical to the v3 folder format on disk which has nupkg, nuspec, hash file.

The client could read the nuspec first to find dependencies instead of waiting to continue the walk until the entire nupkg has been downloaded, but the thinking was that 1 network call would be better than 2.

**Comment by maartenba** [comment]
Thanks for clarifying!

**Comment by mishra14** [comment]
@maartenba does this address your question?

**Comment by maartenba** [comment]
It does, thanks!
