### ISSUE TITLE
Access To repositoryPath in MsBuild Target

### ISSUE THREAD

**Issue by Ducatel** [NuGet/Home#7071]
Hi,

I use a custom path for my nugets package. I do that with a `nuget.config` file which contains something like this:
````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="../nugetPackages" />
  </config>
</configuration>
````

In the same time, to build/install properly my own nuget package, I use a targets file like:
````xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0"    xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <PackagesDir>$([System.IO.Path]::Combine($(SolutionDir), "packages"))</PackagesDir>
    </PropertyGroup>
   <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <Reference Include="myPackage">
            <HintPath>$(PackagesDir)\My.Package.9.9.9.9\lib\net461\Debug\My.Package.dll</HintPath>
            <Private>True</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <Reference Include="myPackage">
            <HintPath>$(PackagesDir)\My.Package.9.9.9.9\lib\net461\Release\My.Package.dll</HintPath>
            <Private>True</Private>
        </Reference>
    </ItemGroup>
</Project>
````

So that work fine on project which use the default path to the `package folder`. But with my custom `repositoryPath`, it is'nt working at all.

To make that good, I need to access to variable `repositoryPath` but, it isn't available in targets files.
So do you known How I can have access to `repositoryPath`  ?

Thanks in advance for your help

## Version

NuGet product used: VS UI (install in project), nuget.exe (build nuget package)
NuGet Version: 4.6.2.5055
VS version: 2015 (14.0.25431.01), 2017(15.5.1)
OS version: win 10 version 1803 (17134.81)

**Comment by ghost** [comment]
Due to lack of recent activity, this issue has been marked as a candidate for icebox cleanup. It will be closed if no further activity occurs within 14 more days. Any new comment (by anyone, not necessarily the author) will add a `Triage:NeedsTriageDiscussion` label and lead to a triaging process.
This process is part of the experimental [Stale icebox issues cleanup](https://github.com/NuGet/Home/issues/12113) we are currently trialing. Please share any feedback you might have in the linked issue.
