### ISSUE TITLE
PrivateAssets does not work for non-SDK csproj

### ISSUE THREAD

**Issue by bdukes** [NuGet/Home#7147]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Visual Studio & MSBuild

NuGet version (x.x.x.xxx):
4.6.0

VS version (if appropriate):
15.7.5

OS version (i.e. win10 v1607 (14393.321)):
win10 enterprise v1803 (17134.191)

Worked before? If so, with which NuGet version:
n/a

## Detailed repro steps so we can see the same problem

1. Create a .NET Framework class library project
2. Add a NuGet reference using `PackageReference`
3. Unload project file
4. Edit `PackageReference` in project file to add `PrivateAssets="all"`
5. Reload project file
6. Build project 

### Expected result
Only the project's assembly is in the output directory

### Actual result
The NuGet reference's assembly is also in the output directory

### Verbose Logs
[msbuild.log](https://github.com/NuGet/Home/files/2229662/msbuild.log)

### Sample Project

[frameworklibrary.zip](https://github.com/NuGet/Home/files/2229659/frameworklibrary.zip)

**Comment by zhili1208** [comment]
@nkolev92

**Comment by nkolev92** [comment]
@zhili1208 This is very likely the build tasks and not NuGet itself.

**Comment by nkolev92** [comment]
I think at this point we can close this as buggy by design. 
See https://github.com/NuGet/Home/issues/3507 and https://github.com/dotnet/sdk/issues/8991. 
Publish in SDK depends on `PrivateAssets` but that's not the great design. 
At this point due to backward compat we can't really change the SDK design, but I certainly see no reason to break old projects too. 

Given the low vote count here, I'm closing this as won't fix.
