### ISSUE TITLE
Update-Package modifies PackageReference version 

### ISSUE THREAD

**Issue by chilakamarthi** [NuGet/Home#7193]
HI,

My VS version is 2017. I see there is PackageReference in this version of VS. 

Here is the issue I observed.

I created sample UWPEmpty project. 

1. Added my nuget package UWPClass with version 1.1.2345.2346. 
    Observed my project file got new entry as below
           <PackageReference Include="UWPClass" Version="1.1.2345.2346" />.
2. To control updates, I updated Version no to Version="(1.0,2.0)". 
3. I got new update for my package (Version 1.1.2350.2347)
4. I updated my package. 
In my project file
Expected: Version No should remain "(1.0,2.0)" 
Actual: Version="1.1.2350.2347"

Details: Purpose of wild card version control is defeated if package update modifies my version def

**Comment by mishra14** [comment]
@chilakamarthi `Update-Package` command is meant to update the package version so that your project can use a higher/latest version.

Update package [documentation](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-update-package) states - 
> Updates a package and its dependencies, or all packages in a project, to a newer version.

Can you please elaborate on what are you trying to do? Why do you need to run Update-Package ? 

If you just want to download a version then right click on the solution and click on "Restore NuGet packages"

**Comment by chilakamarthi** [comment]
Sorry for delay in response. 

> If you just want to download a version then right click on the solution and click on "Restore NuGet packages"

This will update all the packages. What I am looking for is, 

- All our custom packages, I would like to use latest. 
- When it comes to other packages (for example Newtonsoft.JSon), I would like to use same version as unless we know new version of this component is compatible for our requirement I will not change this.

**Comment by chilakamarthi** [comment]
Oh that makes life easy. I am new to nuget packaging and using nuget. This solves my requirement.

Thank you
