### ISSUE TITLE
Warnings not displayed in presence of valid and invalid nuget source.

### ISSUE THREAD

**Issue by p-lad** [NuGet/Home#7280]
**Description:**
I added an invalid nuget source and then added a nugget package with an old version in the project. I then closed the solution and reopened it. The package showed an update available and installed it successfully without a warning.

**Steps to reproduce:**
1. Create an application.
2. Add a Package source pointing to an invalid directory as secondary package source (not the selected one).
3. Add a package to project having update available. for ex NUnit 2.6.1
4.  Close and reopen project
5. Update the package.

**Actual Behavior:**
The package updated successfully.

**Expected Behavior:**
The package should be updated with warnings/errors.

**Test Plan Link:**
https://testrail.xamarin.com/index.php?/plans/view/56083

**Test Case link:**
https://testrail.xamarin.com/index.php?/tests/view/24974426&group_by=tests:assignedto_id&group_order=desc&group_id=95

**Build info:**
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.7 Preview (7.7 build 762)

**Build gist:**
https://gist.github.com/p-lad/ab57d34a0ae37e0fc10a55981abcf105

**Build taken:**
https://devdiv.visualstudio.com/_apis/resources/Containers/2290021?itemPath=drop%2FVisualStudioForMac-Preview-7.7.0.762.dmg

**Package console logs:**
https://gist.github.com/p-lad/70dd810ea3e2f398fc55fd1b9dc2058f

**Screencast link:**
https://www.screencast.com/t/l4JxRtoOPUO

**Reproducibility: 100%**

**Attached logs as well.**
[IDE logs.zip](https://github.com/NuGet/Home/files/2359542/IDE.logs.zip)

**Comment by mrward** [comment]
This does not seem to be a problem with Visual Studio for Mac. In both VS Mac and VS on Windows if you have an invalid file path as a secondary package source the NuGet restore or install will succeed without any warnings. If you have an invalid url as a secondary source then NuGet will report a warning. Not sure if this is by design or not - however there is a discrepancy here.

**Comment by mrward** [comment]
@p-lad The bug description is incorrect here. The problem is a package source pointing to an invalid directory not an invalid url. VS Mac and VS on Windows both report a warning when an invalid url is used as a secondary source. I have edited the test steps.

**Comment by rrelyea** [comment]
Testing in VS 16.0, it appears if i add a local package source like c:\temp\foo with that directory not existing, then the first install will not even work.
If i reopen the project after manually adding the package to csproj, it won't restore, let alone update.
This was testing with netstardard project (classlib)
We do fail the operations. ANd messages appear to be written out to the package manager output...but don't get put into errorlist/warnings. (is that the problem that is being raised)

I cannot get to most of those links...can you clarify the repro or bug?

**Comment by mrward** [comment]
In the screencast the project is using packages.config. The invalid package source is a secondary package source not the primary source. Projects that use PackageReferences seem to report an error on trying to update with an invalid directory.

With VS 2017 and 2019 using Update-Package from the NuGet Package Manager console, which is closest to what VS Mac does when it runs an update, you see no warnings/errors when nuget.org is the primary source and you have an invalid secondary source. Not sure if that is by design or not. A long time ago I believe NuGet used to report warnings since it checked every package source for an update.

The original test case was for Xamarin Studio v5 when it was using NuGet v2 so it might not be valid today if it is expected that NuGet ignores failing secondary package sources on updating when the project is using a packages.config file.

The warnings/errors were shown in the package console output not as warnings/errors in the Errors window.

**Comment by nkolev92** [comment]
Merging this into https://github.com/NuGet/Home/issues/9688, which already has a PR going. 

For more context, in PackageReference *all the sources* need to available. There's no concept of primary/secondary sources anymore.
