### ISSUE TITLE
Invalid framework folder netstandard2.0

### ISSUE THREAD

**Issue by iberodev** [NuGet/Home#7296]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet

NuGet version (x.x.x.xxx):

OS version (i.e. win10 v1607 (14393.321)): Linux

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. GitLab CI script that uses a linux container image with nuGet installed as `apt install nuget`

2. Run the script

3. At the following step `nuget pack ./*NuGet/*.nuspec -Version $VERSION -OutputDirectory $NUGET_PACKAGE_FOLDER -Prop Configuration=Release -NoDefaultExcludes -Verbosity detailed` it creates the nuGet package but it issues a warning complaining about the framework not being valid.

...

## Other suggested things

The `.gitlab-ci.yml` with the commands
```
#Stages
stages:
  - ci
  - codequality
  - build
  - publish

#Global variables
variables:
  GIT_STRATEGY: $STRATEGY
  BUILD_NUMBER: $CI_PIPELINE_ID

#Jobs
ci:
  image: my-image.myrepo.com/gitlab-runner-nuget-dotnet-core:latest
  stage: ci
  script:
    - export VERSION=$(echo $(date +"%Y.%-m%d").$CI_PIPELINE_ID)
    - export NUGET_PACKAGE_FOLDER=nupkgs
    - dotnet build --configuration Release
    - dotnet vstest ./*Tests/bin/Release/**/*Tests.dll
    - mkdir $NUGET_PACKAGE_FOLDER
    - nuget pack ./*NuGet/*.nuspec -Version $VERSION -OutputDirectory $NUGET_PACKAGE_FOLDER -Prop Configuration=Release -NoDefaultExcludes -Verbosity detailed
    - cd $NUGET_PACKAGE_FOLDER
    - dotnet nuget push *.$VERSION.nupkg -s $ARTIFACTORY_NUGET_REPOSITORY
```

### Verbose Logs

```
//...
$ dotnet vstest ./*Tests/bin/Release/**/*Tests.dll
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 4.6.26725.06)
[xUnit.net 00:00:00.51]   Discovering: ToolBelt.TestSupport.UnitTests
[xUnit.net 00:00:00.57]   Discovered:  ToolBelt.TestSupport.UnitTests
[xUnit.net 00:00:00.57]   Starting:    ToolBelt.TestSupport.UnitTests
[xUnit.net 00:00:00.72]   Finished:    ToolBelt.TestSupport.UnitTests

Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.5931 Seconds
$ mkdir $NUGET_PACKAGE_FOLDER
$ nuget pack ./*NuGet/*.nuspec -Version $VERSION -OutputDirectory $NUGET_PACKAGE_FOLDER -Prop Configuration=Release -NoDefaultExcludes -Verbosity detailed
Attempting to build package from 'ToolBelt.TestSupport.NuGet.nuspec'.

Id: ToolBelt.TestSupport
Version: 2018.912.2061
Authors: TUI
Description: Project that contains test support for TDD and a Guid generator for tests.
Project Url: https://gitlab.tuiwestern.eu/SalesDistribution/_common-packages/ToolBelt.TestSupport
Dependencies: None

Added file 'lib/netstandard2.0/ToolBelt.TestSupport.dll'.
Added file 'lib/netstandard2.0/ToolBelt.TestSupport.pdb'.

Successfully created package 'nupkgs/ToolBelt.TestSupport.2018.912.2061.nupkg'.

WARNING: 1 issue(s) found with package 'ToolBelt.TestSupport'.

Issue: Invalid framework folder.
Description: The folder 'netstandard2.0' under 'lib' is not recognized as a valid framework name or a supported culture identifier.
Solution: Rename it to a valid framework name.
$ cd $NUGET_PACKAGE_FOLDER
$ dotnet nuget push *.$VERSION.nupkg -s $ARTIFACTORY_NUGET_REPOSITORY
warn : No API Key was provided and no API Key could be found for 'https://artifactory.tuiwestern.eu/artifactory/api/nuget/SalesOrderNuget'. To save an API Key for a source use the 'setApiKey' command.
info : Pushing ToolBelt.TestSupport.2018.912.2061.nupkg to 'https://artifactory.tuiwestern.eu/artifactory/api/nuget/SalesOrderNuget'...
info :   PUT https://artifactory.tuiwestern.eu/artifactory/api/nuget/SalesOrderNuget/
info :   Created https://artifactory.tuiwestern.eu/artifactory/api/nuget/SalesOrderNuget/ 260ms
info : Your package was pushed.
Job succeeded
```

My nuspec file

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ToolBelt.TestSupport</id>
    <authors>iberodev</authors>
    <version>1.0.0</version>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Sample project to generate nuGet</description>
  </metadata>
  <files>
    <file src="bin/*/netstandard2.0/ToolBelt.TestSupport.dll" target="lib/netstandard2.0" />
    <file src="bin/*/netstandard2.0/ToolBelt.TestSupport.pdb" target="lib/netstandard2.0" />
  </files>
</package>
```

*netstandard2.0* should be a valid framework name. Not sure why it complains about it although it seems to generate the nuGet package properly. If I set in my nuspec's file target a `lib/netcore`, for example, it does not complain, although it's not the framework I need to import the nuGet into a netstandard project.
As per https://docs.microsoft.com/en-us/dotnet/standard/frameworks I have tried all these options with the same invalid framework warning result
netstandard
netstandard2.0
netstandard2_0
NETSTANDARD2_0

**Comment by jainaashish** [comment]
This seems strange, @rohit21agrawal any clue about this issue?

**Comment by rohit21agrawal** [comment]
what version of nuget.exe is this?

**Comment by nkolev92** [comment]
I will close this as stale. 
Please upgrade to the latest nuget versions and report back if you are still having issues.

**Comment by erikpaulmiller** [comment]
I have the latest version and this is happening for me running nuget pack in ubuntu.  Can we reopen?

**Comment by aortiz-msft** [comment]
@erikpaulmiller Thank you for reporting back. Would you please add the following information which is currently missing in the template: 

NuGet version (x.x.x.xxx):
OS version: Ubuntu x.x.x.x

**Comment by erikpaulmiller** [comment]
@aortiz-msft 
NuGet Version: 2.8.7.0

Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**Comment by erikpaulmiller** [comment]
@aortiz-msft Any update?

**Comment by erikpaulmiller** [comment]
@aortiz-msft It works when I run the nuget.exe on a windows machine

**Comment by zivkan** [comment]
@erikpaulmiller 
1. NuGet 2.8.7 is a very, very old version. Please download a newer version from nuget.org/downloads. The nuget apt package was not created by us, so we don't maintain it. Please contact your distro provider to update it to a later version if you'd like to use it. Alternatively, I think if you [add mono's repository to your apt configuration](https://www.mono-project.com/download/stable/#download-lin-ubuntu), I think they update nuget.exe.
2. netstandard can only be used in SDK-style projects, and as mentioned by our [project format doc](https://docs.microsoft.com/en-us/nuget/resources/check-project-format), the dotnet cli should be used, rather than nuget cli. Please see [this tutorial on creating a package with the dotnet cli](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli).  If you're only working with .NET Core, you should not need nuget.exe or mono at all.

**Comment by erikpaulmiller** [comment]
@zivkan I have not found a way for using dotnet pack to actually package multiple dlls like nuget can using a nuspec file.

**Comment by zivkan** [comment]
That's a feature request not yet implemented: https://github.com/NuGet/Home/issues/3891

In the thread there are multiple alternatives suggested by various people. For example: https://github.com/NuGet/Home/issues/3891#issuecomment-330668337, or https://github.com/NuGet/Home/issues/3891#issuecomment-330508584 or https://github.com/NuGet/Home/issues/3891#issuecomment-330668337

In general, adding a 👍  reaction to the original comment in an existing issue makes it [rise higher when sorting issues by 👍](https://github.com/NuGet/Home/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), although in this case the issue is already the top of the list.  GitHub doesn't provide us with any way to close new issues as duplicates of other issues and transfer these upvotes.
