### ISSUE TITLE
[Test Failure]The default package source is Microsoft Visual Studio Offline Packages

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7303]
## Details about Problem
NuGet version: Dev\5.0.0.5508
VS version: D16.0stg\28117.3000
OS version: Build 17134.rs4_release.180410-1804 
## Detailed repro steps 
1. Launch VS, create a new project through File -> New -> Project (for example: Console App (.Net Core)).
2. Open PM UI in Solution Explorer window.
3. Check the default package source.
## Excepted
The default package source should be nuget.org.
## Actual
The default package source is Microsoft Visual Studio Offline Packages as below screenshot.
![default package source](https://user-images.githubusercontent.com/40230425/45744116-3c69a580-bbed-11e8-97f1-28e041de6211.png)

## Note
The issue also reproes after creating a new project every time.

**Comment by jainaashish** [comment]
Which release of d16.0stg and d15.9stg and d15.9, this works fine?

**Comment by v-longmin** [comment]
@jainaashish The issue works fine on D16.0stg 28113.3000 + NuGet Client Dev 5.0.0.5495, and start to repro on D16.0stg 28117.3000 + NuGet Client Dev 5.0.0.5508. But it never repro on both D15.9 and D15.9stg 28117.3003 + NuGet Client Release-4.9.0-preview3 4.9.0.5507.

**Comment by jainaashish** [comment]
does it also repros on D16.0stg 28113.3000 + NuGet Client Dev 5.0.0.5508?

**Comment by jainaashish** [comment]
@PatoBeltran this might be related to your setting refactoring change...?

**Comment by v-luzh** [comment]
@jainaashish , sorry we can't verify it on D16.0stg 28113.3000 + NuGet Client Dev 5.0.0.5508 now, since that VS build had been removed from cpvsbuild drops.

**Comment by PatoBeltran** [comment]
I was able to repro this in the latest dev.

@jainaashish this was probably related to my settings change. It seems like the order in which the package sources are loaded changed. For this specific case, according to the [code](https://github.com/NuGet/NuGet.Client/blob/fc0c2072b79674975d6fac5f332ae8359cef094a/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs#L602) there's no requirement to choose nuget.org, it only takes the first active source, which in this case happens to be nuget.org.

What should be the requirement for this fix? Make it so that it looks for nuget.org and selects that as default, and if it doesn't exist it takes the first active source?

**Comment by nkolev92** [comment]
How does the NuGet.Config look in the tests? 

I don't imagine it should be NuGet.org, but rather the first parsed source from the config file, which frequently can be nuget.org.

**Comment by PatoBeltran** [comment]
`NuGet.Config` settings are loaded from top to bottom, so if you list them, you will see first settings from a config further away from the user. It seems like when updating the `PackageSourceProvider` I missed [some logic](https://github.com/NuGet/NuGet.Client/blob/release-4.9.0-preview4/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L87) to order the sources in reverse order of configs (first list sources in configs closer to the user).

I will add some code for this and tests.

**Comment by nkolev92** [comment]
I was merely guessing. 
If it's not too complicated, i'd try to see the behavior of the old vs new code with a similar config structure.

**Comment by jainaashish** [comment]
marking for 4.9 since this is a regression in 4.9 preview3 bits
