### ISSUE TITLE
Solution-file with folders in different case can't be packed correctly on windows.

### ISSUE THREAD

**Issue by Tasteful** [NuGet/Home#7329]
NuGet product used msbuild.exe, nuget.exe and dotnet.exe:

NuGet version: 4.7.1.5393

dotnet.exe --version (if appropriate): 2.1.402

VS version (if appropriate): 15.8.4

OS version: win10 v1607

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a solution file with 2 projects.
    * Project 1 in path: `src\MyProject1.csproj`
    * Project 2 in path: `Src\MyProject2.csproj`
Note the case in the path, you probably need to modify the sln file manually to get this behaivour. In my case we was migrating 2 different src-folders and they have different case.

2. Add a reference between the projects
3. Restore and pack the solution

Now the `project.assets.json` will have paths for the project references with different cases. On windows this will be the same folder.

During creation of the nuspec the https://github.com/NuGet/NuGet.Client/blob/5032a2e592d61639e6c5aefb1d84e26e9c6d4cfb/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L646 is using an `OrdinalComparer` instead of a comparer depend on the OS.

**Comment by zivkan** [comment]
Can you please better explain the repro steps?

Having two projects in one folder isn't supported, as by default both projects will share the same obj folder and therefore they can't both have `project.assets.json` files. Additionally, in an SDK project both projects will be building all `*.cs` files from both projects. If the two projects have the any same files, one will overwrite the other. Anyway, when I tried to test this scenario by using case sensitive folders on Windows, I couldn't even build, so I couldn't get to the point of packing.

If you actually meant that you have two projects `src\MyProject1\MyProject1.csproj` and `Src\MyProject2\MyProject2.csproj`, then in my testing pack worked correctly and created two nupkgs, with MyProject1.1.0.0.nupkg having a dependency on MyProject2 v1.0.0.

Your first message didn't specify what the actual problem was, for example what error message you received.

Is this a scenario where the solution has case sensitive names that work on Linux/Mac and doesn't work on Windows? If you're migrating projects from different directories/repos, even if the src folder had different casing in their respective original locations, are you moving the projects into their own folders, or do you really have 1 folder with 2 or more csproj files?

**Comment by Tasteful** [comment]
I can see now that I missed one part, we need to have 3 packages.

To reproduce the error:
1. Unzip [ReferenceDemo.zip](https://github.com/NuGet/Home/files/2430367/ReferenceDemo.zip)
2. From command line, run `msbuild .\ReferenceMissingDemo.sln /t:Pack`
3. Check outcome in the nuget-package for `ClassLibrary3`

If we check the `project.assets.json` for `ClassLibrary3` we will have the referens to the other projects with the `projectPath` contains different case on the `Src`/ `src`.
```xml
      "frameworks": {
        "netstandard2.0": {
          "projectReferences": {
            "C:\\Work\\ReferenceDemo\\Src\\ClassLibrary1\\ClassLibrary1.csproj": {
              "projectPath": "C:\\Work\\ReferenceDemo\\Src\\ClassLibrary1\\ClassLibrary1.csproj"
            },
            "C:\\Work\\ReferenceDemo\\src\\ClassLibrary2\\ClassLibrary2.csproj": {
              "projectPath": "C:\\Work\\ReferenceDemo\\src\\ClassLibrary2\\ClassLibrary2.csproj"
            }
          }
        }
      },
```

This demo solution was created inside Visual Studio and by purpose I use different case on the `src` folder. If I'm doing the restore of the references inside Visual Studio the path is resolved with the same case but not if I do the restore with `msbuild` from command line.

**Comment by zivkan** [comment]
Thank you very much for the sample solution it really helps.

The original post is missing what the expected/actual issue is, but from your sample I see:

expected: ClassLibrary3's nupkg should have 2 dependencies, to ClassLibrary1 and ClassLibrary2

actual: ClassLibrary3 only has 1 dependency, to ClassLibrary1, which uses the same case as ClassLibrary3. ClassLibrary2, which has a different case to to ClassLibrary3, is missing.


Please reply if this isn't correct, but otherwise the team will triage it as part of normal procedure.
