### ISSUE TITLE
Using the IntermediateOutputPath in an application and deleting the obj directory near the project source breaks the build.

### ISSUE THREAD

**Issue by ezverev** [NuGet/Home#7362]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
4.6.0

dotnet.exe --version (if appropriate):

VS version (if appropriate):
15.8.5

OS version (i.e. win10 v1607 (14393.321)):
win10 1803

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a Xamarin.Android app,
2. Apply the IntermediateOutputPath tweak i.e. append something like this into the .csproj file:
```
  <PropertyGroup>
    <IntermediateOutputPath>C:\Temp\project1</IntermediateOutputPath>
  </PropertyGroup>
```
3. Switch the project to the packages.config style of NuGet reference (like most of the pre-existing projects do).
4. Delete the now-old obj directory which should exist near the .csproj file.
5. Rebuild the app project.

### Verbose Logs
------ Rebuild All started: Project: PGPolyglotRussian3.Droid, Configuration: Release Any CPU ------
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets(39,3): error MSB3371: The file "obj\project.assets.json.stamp" cannot be created. Could not find a part of the path '\obj\project.assets.json.stamp'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

In order to make the project build you will have to manually create the **obj** folder near the project file and create an empty **project.assets.json.stamp** file inside.

### Sample Project
[Problem1.zip](https://github.com/NuGet/Home/files/2447970/Problem1.zip)

**Comment by gordcross** [comment]
Using Visual Studio 2017 (15.8.4), Xamarin.Forms (3.0.0.x) .net (2.0.3) - NuGet set to get missing packages etc, I've been struggling with builds failing because the project.assets.json.stamp file is not being created - may or may not be related to this but I haven't explicitly touched the IntermediateOutputPath setting. Eugene's suggestion to create a file named project.assets.json.stamp does indeed work. Thanks

**Comment by nkolev92** [comment]
@ezverev 

NuGet relies on `MSBuildProjectExtensionsPath` to decide where to write the assets file. 
That in turn defaults to BaseIntermediateOutputPath. 

So it's useful that you overwrite both those properties otherwise you might have nuget assets in a different place from the rest of the build assets.

https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we haven't gotten enough reports to continue investigating this issue. 

Based on the name of the file in question, it's likely an issue on xamarin side. 

If you're still seeing this please consider reporting it in that repo.
