### ISSUE TITLE
Non-SemVer package versions (with 4 parts)

### ISSUE THREAD

**Issue by FlorianHockmann** [NuGet/Home#7376]
First of all, I hope this is the right place to ask such a question. If not, please feel free to close this and direct me in the right direction.

Is using a SemVer compatible version number a requirement for NuGet packages? [The only documentation I could find on this topic](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) talks about SemVer for package versions but it also briefly mentions the possibility of having four part versions:
> A zero in the fourth part of the version number

So, is it possible to use a version number that consists of four parts for a NuGet package? And if it is possible: Does that come with any disadvantages?

The use case is that we are currently working on a database driver and wondered whether we could include the version number of the database in the version of the library to communicate to users which version of the library is compatible with which version of the database. Since the database already has a version number that consists of three parts (like `0.3.0`), a fourth part seems to be necessary to differentiate between versions of the library for the same database version (like `0.3.0.1`, `0.3.0.2`, and so on).

(Some context: The database in question is [JanusGraph](janusgraph.org) and [we are currently discussing](https://groups.google.com/d/msg/janusgraph-dev/A55fIfpdhhA/HnPgl90ZAAAJ) about how to handle versioning for driver libraries.)

**Comment by StingyJack** [comment]
Nuget pack will alter the version number by dropping 0's in the 4th part, forcing semver in these cases but not in others.

It makes package versions go
1.1.1.5
1.1.1.6
1.1.1.7
1.1.2. (instead of 1.1.2.0)
1.1.2.1
Etc...

There is at least one issue here for  ["unwanted version normalization" regarding this](https://github.com/NuGet/Home/issues/3050). There are a few others that describe the normalization added in nuget 3.5

**Comment by nkolev92** [comment]
Since 3.4+ nuget has been normalizing the 4th part version of packages. 

It also considers 1.1.1 and 1.1.1.0 to be equivalent, as the doc you linked indicated. 

They are supported, but we'd discourage that. 

If you want to add build versions, I'd recommend you use semver2 compatible prerelease versions. 

Say have something like, `2.1.0-preview.1.5667`

**Comment by FlorianHockmann** [comment]
OK, thanks for the clarification, especially for this sentence:

> They are supported, but we'd discourage that.

which is also how I interpreted the docs (although I think that it wouldn't hurt to include that explicitly there).
