### ISSUE TITLE
Display whether a nuget package is signed

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7535]
<p>In the Visual Studio 2017 NuGet Package Manager, it would be nice if it displayed whether a package is signed, possibly with a blue checkmark similar to NuGet.org.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/381773/display-whether-a-nuget-package-is-signed.html
VSTS ticketId: 728470_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/13/2018, 11:15 PM (6 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by anangaur** [comment]
Issue moved to [NuGet/NuGetGallery #6693](https://github.com/NuGet/NuGetGallery/issues/6693) via [**ZenHub**](https://www.zenhub.com/)

**Comment by anangaur** [comment]
We have had discussions before whether or not show some kind of checkmark but we decided not to create a 2-tier system for packages based on author signatures that may be trivial to get for everybody. However, since this information is an information on the package, this should be surfaced somewhere as package details IMO.
