### ISSUE TITLE
Existing destination folder casing and package files that contain ~ (tilde)

### ISSUE THREAD

**Issue by lbargaoanu** [NuGet/Home#7546]
I have this package that for some reason has files with ~ in the name. If I try to install it in an existing folder that contains letters in upper case, but specify the folder in lower case, I get an error - NU1402: The package 'Core.2.1.6899.17226' contains an entry which is unsafe for extraction. That's not accurate, but because of the casing difference, the API sees it that way. We get the same error with NuGet.exe.
The cause seems to be that the check is made with StringComparison.Ordinal, not StringComparison.OrdinalIgnoreCase. It can be difficult to control the casing for existing directories, or prevent the users from having ~ in the files inside the packages.
nuget install Core -source c:\TestFeed -OutputDirectory c:\projects
NuGet 4.8 on Windows.
[Core.2.1.6899.17226.nupkg.zip](https://github.com/NuGet/Home/files/2608741/Core.2.1.6899.17226.nupkg.zip)

**Comment by lbargaoanu** [comment]
What happens is that Path.GetFullPath(@"C:\\tools\\~file") == @"C:\\Tools\\~file" when @"C:\Tools" exists. Maybe smth about short file names.

**Comment by PatoBeltran** [comment]
Hey @lbargaoanu this looks really similar to https://github.com/NuGet/Home/issues/7505, I will close this issue in favor of that one. There might be a bug here, but the fix should be a bit more complicated since for windows paths are not case sensitive, but in unix systems they are. We would need to use an utility that takes this into account and performs the comparison correctly. Please feel free to comment and upvote the other issue!
