### ISSUE TITLE
Nuget.exe 4.8.1 reads path incorrectly with space (generates "Could not find part of the path c:\path\  \packages\AngeSharp.0.9.9.2" etc.)

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#7550]
@jeanluc33 commented on [Mon Nov 26 2018](https://github.com/NuGet/NuGetGallery/issues/6696)

I experienced this issue when MSBuild, using the Nuget.targets, downloaded Nuget 4.8.1 as specified int he Nuget.targets file (url: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe ).  When I deleted the 4.8.1 executable and hard coded https://dist.nuget.org/win-x86-commandline/v4.7.1/nuget.exe in Nuget.targets, the error was resolved.

Therefore, I believe an issue was introduced in Nuget 4.8.1 about reading package location paths.  The path is being concatenated incorrectly, introducing a space that is causing the error.

Example MSBuild errors with 4.8.1:
C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\AngleSharp.0.9.9.2'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.AspNet.Razor.3.2.6'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.AspNet.Mvc.5.2.6'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Castle.Core.4.3.1'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): The command ""C:\B\4\57\src\dev\Solution1\.nuget\NuGet.exe" install "C:\B\4\57\src\dev\Solution1\Solution1\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\B\4\57\src\dev\Solution1\ "" exited with code 1.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Microsoft.ApplicationInsights.Agent.Intercept.1.2.0'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\WebGrease.1.5.2'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Respond.1.2.0'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\popper.js.1.14.3'.
 C:\B\4\57\src\dev\Solution1\.nuget\NuGet.targets (100): Could not find a part of the path 'C:\B\4\57\src\dev\Solution1\ \packages\Owin.1.0'.

**Comment by fmerkel** [comment]
Same symptom here with NuGet restore. My RestoreCommand in NuGet.targets looked like this:

`<RestoreCommand>$(NuGetCommand) install "$(PackagesConfig)" -source "$(PackageSources)" $(NonInteractiveSwitch) $(RequireConsentSwitch) -solutionDir "$(SolutionDir) " </RestoreCommand>`

A workaround is to replace the space after $(SolutionDir) with a slash. Simply removing the space produces an "illegal characters in path" error instead, presumably due to some escaping goof (the SolutionDir variable ends in a slash).

**Comment by PatoBeltran** [comment]
Hey @jeanluc33 thanks for opening this issue! I was looking into it and the reason why you see that it works in 4.7.1 and it doesn't in the new versions is because we updated from ne46 to net462. Since net462 .NET updated the way the handled paths to be more consistent with the OS, you can read more about it here: https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/21/more-on-new-net-path-handling/

I will suggest that you fix your nuget.targets to not pass the space at the end of the path since the OS permits this as a legal path and should not be trimmed.

**Comment by jeanluc33** [comment]
Obviously that’s something I can do, but various VS versions are adding the targets file with the space.   Those .targets files are out there and are unfortunately not updated on the build (since nuget is not itself implemented as a nuget package).  

It sort of seems wrong to break those for everyone, no?

**Comment by nkolev92** [comment]
Is this maybe a dup of https://github.com/NuGet/Home/issues/7657? 


@jeanluc33 When you say NuGet.targets, you mean the ones from nuget.build? 

Which version of VS are you using?

**Comment by nkolev92** [comment]
//cc @zivkan

**Comment by jeanluc33** [comment]
I have to admit, since I use the PackageReference approach I no longer experience the issue.  They should still fix it (if they didn’t already) for people who can’t switch.

**Comment by nkolev92** [comment]
@jeanluc33 PackageReference wouldn't have this exact issue. 

This would only happen if you are using the NuGet.Build package which is only 2.x https://www.nuget.org/packages/NuGet.Build/. 

Looking at your repro again it seems like it was addressed by #7657 


That package should not be used by anyone using VS 2015 and later. We have fixed it download for the VS 2013 customer and it just requires them to update their package.

**Comment by dylon** [comment]
I'm not commenting to necro the thread, but I worked around this problem by creating an empty directory named explicitly, `" "` (a single space) in the root of my project directory: `mkdir " "`.  I initially created `" "/packages` but NuGet complained that the `packages/` directory already existed.  It worked when I created just the `" "` directory and let NuGet create `" "/packages`.

**Comment by alessandrozuliani** [comment]
if anyone still has this issue, I've managed a way to make it work on vs 2019 on windows (don't ask why): 


` <PaddedSolutionDir Condition=" '$(OS)' == 'Windows_NT'">"$(SolutionDir) "</PaddedSolutionDir>`

becomes

` <PaddedSolutionDir Condition=" '$(OS)' == 'Windows_NT'">"$(SolutionDir.Trim('\'))"</PaddedSolutionDir>`

all other configurations gave me a "illegal character in path" error

**Comment by zivkan** [comment]
https://github.com/NuGet/Home/issues/7657 is the "main" tracking issue for this, with more history and context.

I strongly recommend everyone migrate/fix their projects to stop using `.nuget/nuget.targets` in their csproj. This is from NuGet's initial integration back in VS2010, 2012 and 2013. It was removed from VS2015 and later. It's adding fragility into your build for no benefit.

**Comment by edwardmiller-mesirow** [comment]
These changes suggested here probably helped, but I also needed to use the 4.6.4 version of NuGet.exe specifically. Not just the latest version.

https://www.nuget.org/downloads
