### ISSUE TITLE
[Test Failure][Signing] Error “Bad gateway (502)” occur after signing a package when timestamp signing certificate does not satisfy certificate requirements

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7556]
## Details about Problem
VS Version: D15.9 28307.145
OS Version: 17763.RS5_Release.180914-1434.
NuGet Version: Release-4.9.2-RTM\4.9.2.5701
## Detailed repro steps
1. Create a new test certificate:  .\CreateTestCertificate.ps1 –AddAsTrustedRootAuthority.
2. sign a package:  NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath> -Timestamper http://freetsa.org/tsr
3. Verify the previous step failed with an error saying "NU3024: The timestamp response has an unsupported digest algorithm (SHA1). The following algorithms are supported: SHA256, SHA384, SHA512."
4. Verify the original package was not changed
## Expected
There is an error saying “NU3024: The timestamp response has an unsupported digest algorithm (SHA1). The following algorithms are supported: SHA256, SHA384, SHA512"
## Actual
Error “Bad gateway (502)” occur after signing a package when timestamp signing certificate does not satisfy certificate requirements as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/49142501-e2dfce80-f333-11e8-9111-9d34857eb563.png)

**Comment by PatoBeltran** [comment]
I think this is not a bug, but freetsa.org is not available anymore... 

@dtivel how should we proceed?

**Comment by dtivel** [comment]
It is a test bug.  The test has an external dependency which is unavailable.  Normally, the test should be updated to not have an external dependency; however, since we already have automated test coverage for this scenario [here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/TimestampProviderTests.cs#L332) and [here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/SignCommandTests.cs#L685), this manual test can be simply deleted.

Ideally, the second test would be updated to also check for the code NU3024.

**Comment by PatoBeltran** [comment]
If we wish to continue with this test we could use http://timestamp.globalsign.com/scripts/timstamp.dll, which is also a SHA1 publicly available free timestamping server... Although in the future this server might not be available and face this same issue.

**Comment by PatoBeltran** [comment]
I created a PR to improve the test. We should not rely on an external service for our tests, and we already have enough automated coverage for this scenario. 

@v-longmin can you delete this test from our signing manual test matrix?

**Comment by v-longmin** [comment]
@PatoBeltran we have deleted this test from our signing manual test.
