### ISSUE TITLE
Reference from SDK project (A) to non-SDK project (B) will result in (A)’s project.assets.json not having (B)’s PackageVersion

### ISSUE THREAD

**Issue by paulomorgado** [NuGet/Home#7559]
VS 15.9

See the repro here: https://github.com/paulomorgado/PackRepro

**Comment by nkolev92** [comment]
The reason for this is a mixture of PackageReference and “unrecognized” projects. 
From a NuGet perspective Project C is not PackageReference so MSBuild /t:pack will have issues. 

There are 2 ways you can approach this.  

The shorter fix is to add “<RestoreProjectStyle>PackageReference</RestoreProjectStyle>” to project C. 

The other fix, is to add NuGet.Build.Tasks.Pack as a dependency (PrivateAssets=”all”) to Package B and Package C, and just restore them using msbuild /t:pack. 
Of course the issue here is that the pack targets used in A, could end up being different from the ones in B and C, because in the first case they are brought to you by the tooling, but the in the second case you are managing them by yourself. 

Hope this makes sense.

**Comment by paulomorgado** [comment]
I don't think the issue is with `msbuild /t:pack`. The issue seems to be with the `project.assets.json` generated by `msbuild /restore`.

The problem with `PackageReference` is that it doesn't support the execution of the PowerShell scripts on install and uninstall and I have some of those. If `PackageReference` was an immediate solution, I'd just convert the project to an SDK project.

The versions in the real scenario are generated by tooling and are the same because they are all projects in the same solution built at the same time.

**Comment by nkolev92** [comment]
> I don't think the issue is with msbuild /t:pack. The issue seems to be with the project.assets.json generated by msbuild /restore.

msbuild /t:pack will have issues when all projects are not PackageReference which is your scenario. 
The pack.targets need to be available in all projects for this to work correctly.  

What you can do is bootstrap the pack targets. 
Download the NuGet.Build.Tasks.Pack package and just include them in your Directory.Build.Targets. 
Save caveat as earlier applies, you can easily get out of sync, but you are doing for a simple reason so it's highly unlikely. 

You can consider bootstrap
> The problem with `PackageReference` is that it doesn't support the execution of the PowerShell scripts on install and uninstall and I have some of those. If `PackageReference` was an immediate solution, I'd just convert the project to an SDK project.

We understand that, it's extremely unlikely PR ever supports those.

**Comment by paulomorgado** [comment]
I've ended up upgrading all projects to SDK.

But this will always be an issue that keeps teams and companies tied to packages.config.
