### ISSUE TITLE
Environment variable support in Nuspec file src attribute

### ISSUE THREAD

**Issue by ZenwalkerD** [NuGet/Home#7582]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 4.8.1.5435

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2013

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Building Nuget package from assemblies. Have a nuspec file where file src attribute contains environment variable as shown: 
`<file src="%build_root%\RC__PUBLIC_PCSW\ComtradeViewer\Out\$platform$\msvs2013_U4\$configuration$\*.exe" target="build\$platform$"/>`

2. Run `nuget pack -properties "Configuration=Debug;Platform=Win32"`

3. The path shows invalid. In my case %build_root% is a system environment variable. Yes i can execute 

...

Kindly please let me know if i can use environment variable? The files which needs to be part of Nuget are in a remote location (Clearcase VOB). Hence the mounted VOB path is set as environment variable.

**Comment by zivkan** [comment]
Firstly, sorry about the late reply.

To answer your question, no, we don't support environment variable expansion in nuspec files. We need to update our docs, but generally we no longer recommend creating nuspec files. Instead, we recommend creating a MSBuild project file (typically a csproj, but since your case doesn't appear to be a .NET project, you could create a `something.proj` and import the NuGet.Build.Pack.targets file). MSBuild adds environment variables as properties, then you can use MSBuild variables to reference the path.

Another option is to write a small program or shell script to generate the nuspec file.

Since we're moving towards packing with MSBuild targets, we're trying to avoid investing into nuspec and `nuget.exe pack`

**Comment by ZenwalkerD** [comment]
Thanks. The future where Nuget is taking as you have mentioned via csproj is for 2017 support onward. Atleast i do not see any documentation on that for 2013/2015 VS. 

Hence, i sometimes had to do via manual nuspec creation or via Nugetpackage explorer tool. But the later had an issue in integrating with the build pipeline and generating it, hence manual way was chosen.
