### ISSUE TITLE
TFS dotnet restore - Unable to load the service index for source

### ISSUE THREAD

**Issue by eliassal** [NuGet/Home#7583]
Hi, I have a package which I added to to TFS feed, I can browse it the feed in VS 2K17, add the packge to add it to a dotnet project compile correctly and it downloads the pkg, on command line also msbuild t:restore works fine.
In TFS, I am using a nugget restore step but it is failing with the following error for the same package

>  C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error : Unable to load the service index for source http://vsalms:8080/tfs/TODOS/_packaging/e475f9ce-1afd-47c9-8aa6-2f0d54948126/nuget/v3/index.json. [C:\agent\_work\2\s\lib\CoreFlogger\CoreFlogger.csproj]
> 2018-12-03T14:24:46.6934510Z C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error :   The token supplied to the function is invalid [C:\agent\_work\2\s\lib\CoreFlogger\CoreFlogger.csproj]
> 

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): I am not sure which version of nugget it uses as there is no indication in the task. I have downloaded nugget and added its path to the environment, typing nugget in console gives the following
NuGet Version: 4.8.1.5435

dotnet.exe --version (if appropriate): 2.1.500

VS version (if appropriate):  2k17

OS version (i.e. win10 v1607 (14393.321)): win 2K16

Worked before? If so, with which NuGet version: not sure as indicated above

**Comment by zivkan** [comment]
Firstly, sorry for the late reply. Are you still having the problem?

If so, can you check what account your build agent is running as, and if that user account has permission to access your TFS NuGet feed? It looks like a permissions problem to me.

**Comment by eliassal** [comment]
The account running the build agent is part of administrator. How/where I check permission for TFS Nuget feed? As I said, opening VS with the same user, I can browse and get packages in nugget management console

**Comment by eliassal** [comment]
I have just revisited the permissions page of the feed, the user running the build agent, his status is "Owner" as well as he is in Projects administrators

**Comment by eliassal** [comment]
In the feed permission, I have the following, should I change something for build services, if yes, how, it seems that I cannt edit those records?
    
![feed](https://user-images.githubusercontent.com/8447864/51756543-914c8980-20c1-11e9-941d-2293dc93df01.jpg)

**Comment by zivkan** [comment]
To be honest, I know little about TFS administration, it's just that the error message you copied (Unable to load the service index for source) is what NuGet reports when it doesn't get a valid JSON response when trying to get the V3 index.json. Before joining the NuGet team, the team I was working for needed to use a private package from another team, and the developers were given access to that private feed, but our CI failed until our CI agent was given permissions on the feed as well. Typically we see the second part of the error say something like HTTP 401 Unauthorized, but in your case you see "The token supplied to the function is invalid". This suggests to me that NuGet was given a token to use by a [credential provider](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers), but the token was invalid.

I only have experience using private NuGet feeds in the cloud hosted Azure DevOps (formerly VSTS), but not on-prem hosted TFS, which I know can be different in some areas. In Azure DevOps, the [NuGet task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azdevops#restore-nuget-packages) has a section to specify which NuGet feed to connect to, and then the build task will automatically set up the credentials. I don't know if TFS's NuGet task works the same way. [TFS's NuGet task documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=tfs-2018#end-to-end-example) doesn't have a section on restore like the cloud-hosted Azure DevOps docs on the nuget task does. Azure DevOps Services (new name for TFS?) has a [how-to on using NuGet feeds](https://docs.microsoft.com/en-au/azure/devops/artifacts/nuget/nuget-exe?view=azdevops&tabs=new-nav#vsts-credential-provider), but it doesn't say anything about build pipelines.

You could try giving docs feedback on one of the pages I linked above, as someone from the Azure DevOps teams should know more about TFS credentials and access tokens than me. If you're not using TFS's NuGet restore task, my first suggestion would be to do so. If you're running `dotnet restore` on the CI server, either as a dotnet.exe task or from a build script, unless the agent is using a credential manager that sets the credentials correctly, you would need to store a [personal access token](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azdevops) [in nuget.config](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials), but checking in credentials into source control is a terrible idea. If this is the only way you can get it to work, I suggest saving the PAT as a pipeline variable and have a pipeline task that writes the PAT into the config file. But if you can use the pipeline NuGet task to get the credentials automatically, it's better.


Since your error message reports an issue in NuGet.targets from a .NET Core SDK folder, this tells you you're calling either "dotnet build" and doing an implicit restore, or calling "dotnet restore". I only have experience using the "NuGet restore" task. Can you please give that a try and see if it works?

**Comment by eliassal** [comment]
Yes, I have 1st task dotnet restore that is failing, followed with Nuget restore

**Comment by eliassal** [comment]
the dotnet restore is for 1 project in the solution, then the nugget restore is for the whole solution

**Comment by zivkan** [comment]
Changing the order, nuget restore first, followed by dotnet restore, will hopefully fix your CI builds, as long as nuget restore can get credentials correctly, because dotnet restore should have nothing to do. Since nuget restore should restore everything correctly, you should also be able to delete the dotnet restore task.

**Comment by eliassal** [comment]
OK I will give it a try
