### ISSUE TITLE
'dotnet restore' --source option is not respected when installing msbuild project sdks

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7589]
## Details about Problem

dotnet.exe --version: 2.2.100

The --source option to 'dotnet restore' is not respected when installing msbuild project sdks

## Detailed repro steps so we can see the same problem

1. Unzip the attached .zip file ([NetCoreConsoleApp.zip](https://github.com/NuGet/Home/files/2646839/NetCoreConsoleApp.zip)) to somewhere on your machine
2. Run repro.bat

...

Essentially, the .bat calls 'dotnet restore' with an empty directory as the source. The .csproj lists a nuget-based msbuild project sdk. If --source was respected, the sdk would not be installed, yet it is.

Note that --option is respected when restoring PackageReferences, which produce an error as expected

**Comment by zivkan** [comment]
Sorry for the late reply.

It's not obvious from a user's point of view, but downloading a SDK package happens on every MSBuild evaluation of the project, whether it's restore, build, pack or running an invalid/non-existant target. Since it happens so early in the process, it's before command line arguments are considered, and most commands don't allow for NuGet package source to be provided anyway. Another issue is that it doesn't work for Visual Studio, VS Code, and if people on different machines don't do the same, they will have different experiences. For testing, you could generate a nuget.config with the source, which should be taking into consideration by the SDK resolver.

If this is still imporant to you, can you please explain the scenario? We'd like to understand why this is important.

**Comment by zivkan** [comment]
closing due to no response.
