### ISSUE TITLE
Missing dependency in NUPKG-file generated from project if indirect dependency already exists with a lower version requirement

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#759]
Copied from: https://nuget.codeplex.com/workitem/4417

Scenario: 
A project C has the following dependencies: 
Package A, version=1.2 
Package B, version=1.0, with a dependency on Package A, version=[1.0,2.0) 

NuGet.exe pack C.csproj will now generate the following packge: 
Package C, with a dependency on Package B, version=1.0 

But since project C directly depends version 1.2 of Package A, I expect: 
Package C, with a dependency on Package B, version=1.0 and a dependency on Package A, version=1.2 

Now, when the Package C is installed into a consumer project, NuGet will install Package A, version=1.0 and Package B, version=1.0, even though the assembly contained in Package C has been linked against the assembly from Package A, version 1.2. 

A real world sample of this is attached in the repro-sample. Here, the Coypu-package only requires Selenium.WebDriver version 2.39 or greater, but the project depends on Selenium.WebDriver version 2.44. 

Affected version 2.8.3 (and 3.0.0-preview / master 86a4b0fb0ecb8a75dae46073e54fb0e492f5ac6c) 

https://nuget.codeplex.com/discussions/577811 
https://nuget.codeplex.com/SourceControl/network/forks/MichaelKetting/dev/contribution/7907

**Comment by yishaigalatzer** [comment]
We think the PR is a good start, but we probably need a better P2P walk than just looking at top level.

We will take a look at this for Update I (or before), and would like to discuss the design here, before re-submitting a PR.

**Comment by MichaelKetting** [comment]
@yishaigalatzer Thanks for porting the bug!

**Comment by MichaelKetting** [comment]
Okay, I know it's been a (long) while, but since this just bit me majorly (broken release), I've decided to put a break on other stuff and look into this.

@yishaigalatzer Back when we discussed this at http://blog.nuget.org/20150601/nuget-3.0-rc2.html, you mentioned that the design is not there yet. Was it just the recurisive angle or is there more? Also, I'm quite happy to do a 'simple' solution for NuGet v2 first, given that that's what I actually need. (I don't see a way forward to NuGet v3 for me at the moment, given the breaking changes.)

What do you need for v2 and what would be required for v3? I'm thinking of starting to tinker with recursive lookup on the NuGet v2 code base this weekend to get things rolling, but if you guys have time before that for discussing things, that'd be great, too! :)

**Comment by yishaigalatzer** [comment]
The code is in nuget2 repo, and applies to the command line built by nuget.client repo.

Yishai

**Comment by MichaelKetting** [comment]
Yes, the nuget2 repo is the one that gets used for creating the NuGet v2 releases these days, correct? That would the NuGet version I'm using when building my NuGet packages via the command line.

**Comment by yishaigalatzer** [comment]
The nuget.exe itself is built out of nuget.client

Please use the 2.10 branch

Sent from my Windows Phone

**Comment by MichaelKetting** [comment]
Great, thanks!

**Comment by yishaigalatzer** [comment]
@MichaelKetting we are still happy to take a PR if you are interested

**Comment by MichaelKetting** [comment]
@yishaigalatzer Thanks for the poke :) Work kind of spiked right after my fateful post. I should never talk about actual timetables... There is a holiday coming up in two weeks, here's hoping to that.

**Comment by MichaelKetting** [comment]
@toddm Thanks so much for sending the fix!
