### ISSUE TITLE
'dotnet restore' enumerates local package sources for MSBuild project sdk packages already in the packages cache

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7594]
## Details about Problem

dotnet.exe --version: 2.2.100

Suppose I have a .csproj that lists a nuget-based MSBuild sdk and that I've already run 'dotnet restore.' The sdk package will be installed to my packages cache. Theoretically, if I re-run restore, it will realize the package is already cached and not bother looking on my package sources.

However, the second restore will indeed look on my package sources. This is a needless performance hit, magnified if I'm using slow-to-respond source (e.g. a network share)

## Detailed repro steps so we can see the same problem

1. Unzip [restore_unneeded_enumeration.zip](https://github.com/NuGet/Home/files/2650022/restore_unneeded_enumeration.zip) to your machine somewhere

2. Ensure [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) is available for use on your machine

3. Run [unzip dir]\repro.bat. It will provide instructions/context as it progresses

**Comment by zivkan** [comment]
@jeffkl should MSBuildNugerResolver issues go to you?

**Comment by jeffkl** [comment]
@zivkan It depends.  There is code in the resolver that attempts to locate a package if its already on disk and the entirety of that code is owned by NuGet.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/NuGetSdkResolver.cs#L206

The API is pretty simple, the resolver is given a package name and version and is expected to return the path to it.  I can certainly help out but I'd imagine that if there's a bug here, the NuGet team is more equipped to root cause it. 

@bergbria are you saying that NuGet is just searching your package cache on disk or its hitting remote feeds and querying for packages?  `MSBuild.exe` caches the lookup for the duration of a build but that cache is thrown away when the process exits.  Each time you run `dotnet build`, each SDK's location is fetched once.  The NuGet SDK resolver will look for the package in your package cache and should return very quickly after doing some `Directory.Exists()` calls.  But it should not hit remote feeds for sure.

**Comment by jeffkl** [comment]
Closing this issue as stale, please let us know if anyone is still encountering the problem and we'll re-open it.
