### ISSUE TITLE
Add dependencies for multiple frameworks in NuSpec file

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7597]
@p0onage commented on [Wed Dec 05 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1206)

I've created a Nuget package from a project targetting .Net Standard 2.0 but when coming to install this project from the Nuget feed it is not visible within a .Net framework 4.7 solution. The reason for the is having .Net Standard 2.0 as a dependency. 

I fixed this in the end by using 
`  <TargetFrameworks>netstandard2.0;net47</TargetFrameworks>`
but it would have been ideal if the NuSpec file has an override dependency area where I could remove this dependency and state any other dependencies. We have a Dependencies field in the metadata of the nuspec file but it doesn't work as expected

**Comment by zivkan** [comment]
As documented in the [.NET Standard docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), .NET Framework 4.6.1 and higher implements .NET Standard 2.0, so a NuGet package with netstadard2.0 libs should work just fine in a net47 project.

The problem you experienced might be due to incorrectly packing the class library project, if you used `nuget.exe pack`. With SDK-style projects, you can/should use `dotnet pack`, which automatically generates a nuspec file, so you don't have to create/edit the nuspec yourself.

If you were already using `dotnet pack` to create your package, then we need more information to understand the problem.

**Comment by p0onage** [comment]
I was using Dotnet pack, this issue occurs due to the Nuget feed. I compiled the nuget locally using Dotnet pack and it finds the package but when it’s on the nuget server it has dependencies in the feed and if it says a dependency of dot net standard 2.0 then it doesn’t appease when searching nuget packages on a .net framework. 

The above shows my work around where I had to use target frameworks but ideally i’d like to remove the dependency to .net standard and use in any framework.

Is there anything else I can provide to help assist?

**Comment by zivkan** [comment]
The nuget protocol doesn't have a way to filter on TFM (target framework moniker), so search results should not be different depending on what TFMs the package contains, or what TFM(s) the local project targets. 

The best thing you could provide us is a sample that reproduces the problem. Otherwise, a step by step instruction list would be helpful, as I'm not sure if the problem you're reporting is related to search results, a restore failure or a build failure. If you got an error, you never told us the error code or error string (but if it's simply missing search results, you wouldn't have an error). You said you edited the TargetFrameworks, I assume you did this in the library project, not the project that uses the package, but did you then push this package to an http source (nuget.org, another public feed, or a private feed), or a local file source? Since your commented about the nuspec file, I'm not sure if you're talking about the generated nuspec file, or if you have your own nuspec file. Did you edit this file, or are you referring to the generated dependencies metadata? You said it didn't work as expected, but I'm not sure what your expectations are, and how it was different to the actual results.

So, [an example](https://stackoverflow.com/help/mcve) would be most helpful as we would be able to see ourselves what's going on, as sometimes answering some questions raise new questions. For now, I don't fully understand your scenario.

**Comment by p0onage** [comment]
Okay I just checked DevOps pipeline and it might be because I'm using Microsoft build step instead of DotNet build?

![image](https://user-images.githubusercontent.com/6472111/49641436-0d9ee680-fa08-11e8-9047-a647769f392d.png)

I'm using these arguments for the MSBuild Arguments 
`/t:Pack /p:PackageVersion="$(GitVersion.NuGetVersion)" /p:Version="$(GitVersion.NuGetVersion)"`

This gets pushed to a public nuget feed.  The problem was that the package wasn't appearing in nuget searches for .net framework projects. If however, I searched for this package in .net standard project then it appeared in the search and worked perfectly. 

The reason for this was that the nuget feed displayed a dependency for .Net standard. To test this further, I download the nuget package locally, added the location as a local nuget package directory in VS/Nuget and this file then appared in a .Net framework project. This test give me the insigt that it must be the dependencies located on the public nuget feed. To be clear, there are no errors anywhere in any of my projects.

I then followed online advice to target both frameworks within the proj file, i pushed this up and then resolved the issue. 

Thanks,
Joshua

**Comment by nkolev92** [comment]
@p0onage 
Apologies for super delayed response. 

As @zivkan said, there is no compat filtering in the PM UI right now (be it client/server side). 

When the Package Manager UI queries feeds, an HTTP happens. 

I'd expect the HTTP calls for all projects to be the same. I have verified that on the latest VS 2019 VIsual Studio installation. 

Given that I'd also expect the server responses to be the same (which you can track with some network tools). 

Can you provide a video or screenshots from the behavior you are describing?

**Comment by nkolev92** [comment]
I am closing this issue as there is nothing actionable here for us to continue investigating.
