### ISSUE TITLE
Package Restore not Working

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7619]
@Rainamay commented on [Sat Dec 08 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1216)

The error is:

This project references NuGet package(s) that are
 missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\buil
d\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.

I already have the settings as they should be:
![settings](https://user-images.githubusercontent.com/24514861/49689094-25e73200-faea-11e8-808e-0731d50dd0ab.PNG)

This happens often.  I also get an error all the time with IIS Express that a bin\roslyn.exe file is missing.

Thank you

**Comment by jainaashish** [comment]
I'm not able to understand the issue here? it simply put an error message without any more context like where did you encounter this error? what happens when you run an explicit restore? was restore not triggered as part of build? is the issue that restore isn't being triggered or restore not able to resolve this dependency or the wrong error message?

It will help to clearly statet the purpose of the issue. And generaly when we open such issues, we also mark them with appropriate labels.
