### ISSUE TITLE
NominateProjectAsync should only restore the project being passed

### ISSUE THREAD

**Issue by adalon** [NuGet/Home#7622]
NuGet version: latest
VS version: dev16 (and probably dev15 too)
OS version: win10

CPS-based projects will trigger a `NominateProjectAsync` when the active configuration changes (or when the project template is unfolded too). 

Repro steps:
1- With nuget package restore settings enabled, create an empty solution 
2- Add New Project -> Class Library (.Net Standard)
3- Add New Project -> Console App (.Net Framework)
4- Change the current active configuration from Debug to Release.

At this stage the CPS-based library will trigger a `NominateProjectAsync` doing [1], [2] and [3] and the expected `restoreinformation` should only contain the `.Net Standard` project but it also contains the another `csproj` library. Resuming:

Expected: `restoreinformation` should only contain the project being nominated
Actual: `restoreinformation` is also containing other projects in the solution which were not nominated

Additional scenarios where this issue also impacts:
- `runintellisensebuild` is also triggered as the result of the `csproj` (unnecessary) nomination and might cause perf impact
- When unfolding a multi-project template which contains at least one netstandard library in it (Xamarin Cross Platform App for instance) the solution perf load might be significantly impacted if any of the other projects being unfolded contain several nuget packages to be restored (Android project for instance in the Xamarin example mentioned above). 

Finally I could not find where the project unique name is being honored in the `VsSolutionRestoreService` [4] or [5]

[1] https://github.com/dotnet/project-system/blob/ddfc471669edc4b2806de3b2a731c7c10c58f2a3/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs#L77

[2] https://github.com/dotnet/project-system/blob/ddfc471669edc4b2806de3b2a731c7c10c58f2a3/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs#L103

[3] https://github.com/dotnet/project-system/blob/ddfc471669edc4b2806de3b2a731c7c10c58f2a3/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/PackageRestoreInitiator.PackageRestoreInitiatorInstance.cs#L148

[4] https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs#L99-L109

[5] https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs#L142-L144

**Comment by jainaashish** [comment]
This is by design for now that NuGet always does a solution restore inside VS either as part of NominateProject or manually triggering a solution restore or restore running as part of build.

But we're having disucssion and evaluation to see if restoring individual projects instead of solution will be more efficient, given we'd still need to figure out P2P (project references) recursively for given project being nominated and restore all those dependent projects as well.

**Comment by adalon** [comment]
In our scenario we really need to avoid restoring the Android project while the solution is unfolded or loaded. It really impacts on solution perf load and makes the metric pretty much useless. Taking account that also the runintellisensebuild is triggered for csproj projects when the restore occurs.

@davkean from your (CPS) point of view is it expected to nominate the project when the solution is being unfolded? Or is it just a non-expected behavior as part of the ActiveConfigurationChanged handler implementation? Because we're also triggering a Nominate but we wait until the solution is fully loaded.

**Comment by davkean** [comment]
In my opinion, NominateProject should not equal Restore. Nominate should be a hint to NuGet that the project's data has changed, and it should use state of the solution to determine whether that means Restore now, or Restore later. 

However, I suspect above is not the real repro, but really what's happening during File -> New?

- You should avoid changing configurations during File -> New, the config should be correct correct when the project is created. Regardless of NuGet restore, this is going to result in wasted evaluation/design-time builds.
- Restore should be a no-op if the project didn't change, the state of the project clearly changing between those steps which is causing legacy to kick off a design-time build.

Action items:

- Pause design-time builds for the legacy project while the template wizard is running via IVsProjectBuildSystem.BeginBatchEdit/EndBatchEdit
- Avoid changing configurations while creating the template - make sure the config is correct when the project is created

**Comment by adalon** [comment]
We're not changing the active configuration. And it can also be reproducible unfolding a single .net standard class library.

What we're doing is changing the platform of the IOS project (which does not trigger the Nomination). And still disabling that IWizard, the restoreinformation is still triggered.

Disabling the designtime build while the Wizard is running is not enough in my opinion. We could try to disable it while the wizard is running but we should wait until the solution is fully loaded.

Anyway I still believe the restore should not happen while the solution is being created/unfolded and Nominate should only applied for the project who triggered it.  I do agree that Nomination should not imply restore intermediately. And waiting for the solution to be fully loaded should be an implementation detail of Nuget.

**Comment by davkean** [comment]
> We're not changing the active configuration. 
> What we're doing is changing the platform of the IOS project

These are the same.

> but we should wait until the solution is fully loaded.

What is "fully loaded" in this context?

**Comment by adalon** [comment]
>> We're not changing the active configuration.
>> What we're doing is changing the platform of the IOS project
> 
> These are the same.

No, we're changing the platform (iPhone or iPhoneSimulator) of the iOS project in the current selected configuration. That does not trigger your Nomination. And still disabling the IWizard which modifies the platform of the IOS project, we get the same result. 
 
> > but we should wait until the solution is fully loaded.
> 
> What is "fully loaded" in this context?

Being pragmatic, it would be to delay anything until the vs/solution/perf/load event occurs. In practice, doing it in the IVsSolutionLoadEvents.OnAfterBackgroundSolutionLoadComplete was not enough in some cases and we had to add a delay to make sure the solution is "fully loaded" for real.

**Comment by davkean** [comment]
I have a trace on my box from a File -> New -> Android solution template that creates 3 projects (1 CPS, 2 legacy). It shows that we kicked off two legacy builds due to a configuration change (1 for each legacy project):

![image](https://user-images.githubusercontent.com/1103906/49866918-2c183e00-fe5d-11e8-88a8-105bfa8d715b.png)

You can also see that Nomination ("RefreshReferencesAfterRestore") only caused two of the design-time builds (which is exactly what I expect for two legacy projects). What makes you think that Nomination is the cause here?

**Comment by kzu** [comment]
Can you share the template without any of our stuff and regular .net
projects @adalon? That should make clearer what we're taking about here.

**Comment by davkean** [comment]
Traces would help, with the VS events turned on.

**Comment by adalon** [comment]
> I have a trace on my box from a File -> New -> Android solution template that creates 3 projects (1 CPS, 2 legacy). It shows that we kicked off two legacy builds due to a configuration change (1 for each legacy project):
> 
> ![image](https://user-images.githubusercontent.com/1103906/49866918-2c183e00-fe5d-11e8-88a8-105bfa8d715b.png)
> 
> You can also see that Nomination ("RefreshReferencesAfterRestore") only caused two of the design-time builds (which is exactly what I expect for two legacy projects). What makes you think that Nomination is the cause here?

For the reason of this issue the only event we're focusing on is the restore and the associated builds (RefreshReferencesAfterRestore) that each csproj is triggering while the solution is being loaded/unfolded.

We're aware that we also have other builds we should avoid such the ConfigChange you're mentioning. And we're evaluating to postpone those changes after the solution is fully loaded or implement the BeginBatch/EndBatch mechanism you're proposing.

And finally the builds associated with the RefreshReferencesAfterRestore seem to be the more expansive ones.

**Comment by davkean** [comment]
How many RefreshReferencesAfterRestore per project do you see? They have to eventually happen if Restore is involved, regardless of when it occurs.

To make progress here we need traces so that we talking about exactly the same thing. I think my definition of solution load and your definition of solution load might diff.

**Comment by kzu** [comment]
Related bug triggered by this restore and its "eagerness": https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753071.

I think it would be useful for nuget to queue all such nominations that happen before `IVsSolutionLoadEvents.OnAfterBackgroundSolutionLoadComplete` and essentially discard all except one (since it does a solution restore anyway) so a single restore is done after that event. This should reduce the randomness we're seeing, at least and definitely help finish the solution load earlier.

**Comment by nkolev92** [comment]
Hey all, 

This has been `fixed`. 
Well sort of :)

We fixed the queueing on solution through: https://github.com/NuGet/Home/issues/9822, https://github.com/NuGet/Home/issues/9984, https://github.com/NuGet/Home/issues/9982. |

NuGet queues the nomination requests until everything NuGet needs is ready. 

Through https://github.com/NuGet/Home/issues/9513 & https://github.com/NuGet/Home/issues/9903, NuGet can be strategic and perform `partial restore` whenever necessary when the nominations are *not* happening on solution load. 
Due to transitivity, a nomination of a leaf project *can* lead to a restore for most of the solution, but that's expected and really the only way to stay `correct`. 

https://github.com/NuGet/Home/issues/9986 has to do with queueing nominations from xamarin projects, and that should soon be addressed.
