### ISSUE TITLE
restore unnecessarily enumerates the contents of all versions of referenced package in the machine cache

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7639]
## Details about Problem

Suppose
* Versions 1 and 2 of package PkgFoo are both present in my global packages cache
* .csproj P contains a PackageReference for PkgFoo version 1

If I run `dotnet restore` on P, dotnet.exe should theoretically only need to access the cached files for version 1. However, it will also recursively enumerate all the directories in the cache for version 2.

In general, this is a perf concern. If enough versions were cached or the packages were large, this could add a significant amount of time to the restore operation.

In my case it is also a correctness problem. I'm running `restore` under a strict build system where all inputs need to be declared beforehand. This issue makes it impossible to predict what `restore` will access, even when a lock file is used.

It's worth noting that if I run `nuget restore` on a packages.config file referencing PkgFoo version 1, it will, as expected, enumerate just the v1 directory.

NuGet product used: dotnet.exe

dotnet.exe --version: 2.2.100

## Detailed repro steps so we can see the same problem

1. Ensure you have [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) available on your machine

2. Download [restore_enumerateOtherVersions.zip](https://github.com/NuGet/Home/files/2681173/restore_enumerateOtherVersions.zip) and extract it somewhere on your machine

3. Run <unzipDir>\repro.bat
   1. Note that the .bat contains additional notes and details on the operations being performed

**Comment by jainaashish** [comment]
Global packages folder is not just a cache, but instead also treated as local feed for restore or installation which is why it enumerates all the versions of dependent package to built the metadata. So this is kind of a design limitation at this point since it understands all the available versions before starting to resolve dependencies.

> In my case it is also a correctness problem. I'm running restore under a strict build system where all inputs need to be declared beforehand. This issue makes it impossible to predict what restore will access, even when a lock file is used.

can you give me real scenario of correctness issue instead of just hypothesis? Becuase this should never give you unpredicable results specially with a lock file.

> In general, this is a perf concern. If enough versions were cached or the packages were large, this could add a significant amount of time to the restore operation.

Have you measure some perf numbers for this? I'd never expect a huge perf implication for this behavior? On the contrary, it has always be more performance optimized to know all the available versions before hand instead of making multiple server calls to fetch individual versions.

**Comment by nkolev92** [comment]
> Global packages folder is not just a cache, but instead also treated as local feed for restore or installation 

Another way to think about it, is that in PackageReference, the global packages folder is **the** installation directory. 
You won't find the package extracted fully in another place on disk. 
It's consumed from that folder during build.

**Comment by jainaashish** [comment]
@bergbria As per our discussion last week I looked into this issue... As I mentioned in my first comment, currently nuget goes through all the versions of a package from global packages folder (%userprofile%/.nuget/packages) and then find the best match. But this can certainly be improved by first looking for the exact version if available just consume that, otherwise fallback to find the best matching version. I'll see if I can quickly come up with a PR.

Another thing about enumerating all the sub folders for a package, then it only enumerates version folders of a package and doesn't go through other sub folders like `lib`
