### ISSUE TITLE
package not shown in Nuget packages in Solution

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#7642]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.0.0.5663

VS version (if appropriate): Community 2017

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Enterprise 1803 17134.471

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Add many projects in one solution

2. Add any nuget package to one project

3. Go to "Manage nuget packages for Solution"

4. I the right side, we cannot see check box ticked against the project having nuget package.
Attaching snapshot for reference.
![1](https://user-images.githubusercontent.com/16834561/50069140-bd393d00-01ee-11e9-97c7-66aeb12e9948.png)

**Comment by zivkan** [comment]
@ranjan-ranjan thanks for your feedback and sorry about the very late reply.

I believe the behaviour you see is by design. The check boxes are used by the action buttons immediately below the project list ("uninstall" and "install" or "upgrade"). None are selected by default because we can't guess which action the developer is going to take, or which projects the action will want to be taken on.

Perhaps part of the confusion is that the number of projects in the solution exceeds the size of the project list in the package manager UI, and none of the projects displayed in your screenshot have the selected package installed. If you scrolled the list down, you should see that one or more project have the package version number listed to the right of the project name, which tells you that the project uses the package.

If you disagree, please explain why and re-open the issue.

**Comment by ranjan-2209** [comment]
> If you scrolled the list down, you should see that one or more project have the package version number listed to the right of the project name, which tells you that the project uses the package.

No, its not this way.
