### ISSUE TITLE
Folder path changes after add new package

### ISSUE THREAD

**Issue by arturians** [NuGet/Home#7659]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI 
NuGet version (x.x.x.xxx): 4.6.0
dotnet.exe --version (if appropriate): 2.1.202
VS version (if appropriate): 15.7.5
OS version (i.e. win10 v1607 (14393.321)): Win 10 v1709 (16299.785)
## Detailed repro steps so we can see the same problem

1. Install https://www.nuget.org/packages/PDFsharp/1.50.4845-RC2a and after that https://www.nuget.org/packages/PDFsharp-MigraDoc/1.50.4845-RC2a.
2. Create copy of **.csproj** file.
3. Remove installed packages and install again in another order.
4. Compare current version of **.csproj** file and copy from step 2. 
5. It will be a different. I assume that behavior is strange and it can be detected as bug.

### Sample Project

[DifferentBehavior.zip](https://github.com/NuGet/Home/files/2702290/DifferentBehavior.zip)

**Comment by StingyJack** [comment]
I assume you are meaning this is the difference...
![image](https://user-images.githubusercontent.com/15381181/50347734-abb0a780-0504-11e9-830d-777299135fc8.png)
... which you are seeing because both packages contain the same files.  Yes, they are different hint paths because you installed them in a different order, but the files are the same so the reference is just getting updated.

![image](https://user-images.githubusercontent.com/15381181/50347812-f03c4300-0504-11e9-8ae9-aee914206797.png)

**Comment by nkolev92** [comment]
@armind13 
The issue is as @StingyJack correctly observed, the same assembly is present in 2 packages.

The closest duplicate I've found is the following: https://github.com/NuGet/Home/issues/738. 

NuGet's packages.config cannot fix this problem in it's current form, it's as implemented in that case. 

This works just fine with PackageReference though where NuGet does not write in your project file. 

The conflicts are resolved at build time by build tasks.
