### ISSUE TITLE
Unexpected resolver conflict 

### ISSUE THREAD

**Issue by ocean-orrick** [NuGet/Home#7680]
## Details about Problem

I am converting to the PackageReference format and ran across this error when restoring which has me fairly confused:

```
NU1603: LibB 17.0.0 depends on Newtonsoft.Json (>= 11.0.0 && < 12.0.0) but Newtonsoft.Json 11.0.0 was not found. An approximate best match of Newtonsoft.Json 11.0.1 was resolved.
NU1605: Detected package downgrade: Newtonsoft.Json from 11.0.2 to 11.0.1. Reference the package directly from the project to select a different version. 
 ProjectA -> LibB 17.0.0 -> LibC 1.2.0 -> Newtonsoft.Json (= 11.0.2) 
 ProjectA-> LibB 17.0.0 -> Newtonsoft.Json (>= 11.0.0 && < 12.0.0)
```

From my understanding I can see how this could occur from the nearest-win rule prioritizes the reference to Newtonsoft.Json (>= 11.0.0 && < 12.0.0), which then uses lowest-version wins to resolve 11.0.1, which in turn is unable to satisfy the 11.0.2 requirement of LibC. 

However, why wouldn't it recognize that 11.0.2 would also satisfy the LibB range and allow for 11.0.2 to be resolved instead. It seems that the combined application of the nearest-win and lowest-version win rules is too aggressive in this case. I would expect that since it is a range that is specified by the nearest-win, that it would then look at all the version requirements across the graph before determining what the lowest applicable version is, rather than applying the lowest applicable version rule to the range without any other context.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe / VS UI

NuGet version (x.x.x.xxx): 4.9.2

VS version (if appropriate): 15.9.4

**Comment by rrelyea** [comment]
My guess is that the builder of LibB ignored warnings but went ahead and packed anyway, without fixing it first.
Although you can likely work around this problem by doing a packageref from projectA to newtonsoft.json to v11.0.2 -- ideally, LibB package author would fix it in their project before packing.

Yes, you could imagine that restore could be taught to handle this situation, i believe the move towards the nearest wins model, was instead of the packages.config strategy of expensively looking for the best solution.

cc @nkolev92 to correct or reinforce or add to my answer.

**Comment by nkolev92** [comment]
@rrelyea is right.
Specific emphasis on:

> Yes, you could imagine that restore could be taught to handle this situation, i believe the move towards the nearest wins model, was instead of the packages.config strategy of expensively looking for the best solution.

**Comment by jainaashish** [comment]
@sxmanton let us know if there is anything else we can help with.
