### ISSUE TITLE
NuGet complains about valid semver 2.0 +metadata

### ISSUE THREAD

**Issue by clehene** [NuGet/Home#7689]
## Details about Problem

```
/usr/local/share/dotnet/sdk/2.2.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): warning NU5105: The package version '1.0.0-alpha+B201901111547266494' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients. 
```

## NuGet Version
```
dotnet nuget --version
NuGet Command Line
4.9.0.6
```

## Expected

https://semver.org/spec/v2.0.0.html#spec-item-10

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

**Comment by jainaashish** [comment]
It's just a warning to let you know that this package will not work with NuGet clients < 4.3.0 since NuGet started supporting SemVer 2.0 with 4.3.0 version. More details at https://docs.microsoft.com/en-us/nuget/reference/package-versioning

So you can ignore this message if you don't intend to support older clients or even set `minClientVersion` metadata in .nuspec file to say that your package only supports nuget clients >=4.3.0

**Comment by clehene** [comment]
@jainaashish thank you for the clarification
