### ISSUE TITLE
add support to `NuGet.exe update` for -DependencyVersion parameter, like install command

### ISSUE THREAD

**Issue by ReyOrtiz** [NuGet/Home#7694]
In the NuGet.exe cli, the update-command has set Dependency Resolution Behavior hard-coded to Highest, this should be a parameter as the NuGet Package Manager Console (https://docs.microsoft.com/en-us/nuget/tools/ps-ref-update-package).

I could create a PR for this change.

**Comment by jainaashish** [comment]
Part of the issue is `DependencyVersion` is not supported with `PackageReference` which is why it hasn't been enabled for command line. But there was some contribution to make it happen for `Install` command through https://github.com/NuGet/Home/issues/1806 So if you want to contribute and add this option for `update` command as well then please feel free to raise a PR.

**Comment by ReyOrtiz** [comment]
Can I get permission to push my local branch?

I basically followed the same approach from #1806

**Comment by jainaashish** [comment]
You can fork this repro in your account, add a upstream, and push it. Then you can create a PR out of that

**Comment by rrelyea** [comment]
looks like this was merged in 5.6
