### ISSUE TITLE
NuGet.Packaging: Package extraction need to handle nuspec only scenario

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#77]
NuGet.Packaging: Package extraction need to handle nuspec only scenario

This is about the PackageSaveMode

**Comment by yishaigalatzer** [comment]
From @MarkOsborneMS - 

e.g running the following command:
 nuget.exe restore packages.config -PackagesDirectory "E:\TestCache" -Source "https://api.nuget.org/v3/index.json" -PackageSaveMode nuspec
 Yields the following files:
 E:\TestCache\NuGet.Core.2.10.1\lib\net40-Client\NuGet.Core.dll
 E:\TestCache\NuGet.Core.2.10.1\NuGet.Core.2.10.1.nupkg

Note the nupkg file rather than the requested nuspec file.

Confirmed this is an issue in 3.2.1.10581.3.4 and latest dev source as of 1/11/2016.
 Confirmed expected behavior in 2.8.50926. This is a regression.

**Comment by pranavkm** [comment]
Merged in https://github.com/NuGet/NuGet.Client/commit/960426fa423e9ba09d24758d109ae21bc9d2c168

**Comment by godefroi** [comment]
Using NuGet 3.3.0.212, still saves the entire .nupkg when using -packagesavemode nuspec

**Comment by yishaigalatzer** [comment]
The current version is 3.4.4 or 3.5 (either rc1 or nightly build that is almost rtm ready on myget).

Are you still seeing an issue?

**Comment by rohit21agrawal** [comment]
@godefroi @yishaigalatzer tried using 3.5rc1 and 3.4.4-rtm and -PackageSaveMode only saves the nuspec and the other files within the nupkg.
Following folders were created on executing the below commandline : 

nuget.exe restore packages.config -PackagesDirectory "D:\TestCache" -Source "https://api.nuget.org/v3/index.json" -PackageSaveMode nuspec

packages.config had only one entry :  `<package id="Newtonsoft.Json" version="6.0.4" targetFramework="net451" />`

"D:\TestCache\Newtonsoft.Json.6.0.4\lib"
"D:\TestCache\Newtonsoft.Json.6.0.4\tools"
"D:\TestCache\Newtonsoft.Json.6.0.4\Newtonsoft.Json.nuspec"

**Comment by godefroi** [comment]
It definitely works in 3.4.4. I don't know how I decided (last week) that 3.3 was the latest, but I was incorrect. Sorry for the noise.
