### ISSUE TITLE
If lock file is deleted, restore does not generate lock file on NoOp 

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7807]
Steps:
1. Enable `RestorePackagesWithLockFile` for a project
2. Run restore (Full restore) - Note it generates the lock file as expected.
3. Delete the lock file
4. Run restore (not `--force`)

Actual: 
1. Lock file is not generated and Restore completes.
2. Even in step 2 above, it does not output any message regarding lock file being generated.

Expected:
1. Lock file should be generated.
2. Whenever lock file is generated, there should be an info message to the user about lock file being generated.

**Comment by rrelyea** [comment]
Please work with @nkolev92 to understand how to add the existance of this file to noop calculation.

**Comment by nkolev92** [comment]
What we do with the rest of the files (nuget.g.targets/props) is we validate their existence. 

No-Op should not validate the integrity of the lock file during the check for performance considerations. 

Making it aware that the property being set requires the existence of a lock file is sufficient I think. 

What I mean with this is: 

3. ~Delete the lock file~. Manually edit the lock file

will not be caught, but I think that's ok.

**Comment by nkolev92** [comment]
@heng-liu 

Relevant code; 

https://github.com/NuGet/NuGet.Client/blob/03079932b62466d38f2577e24f3a6b244bb30a49/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L133

https://github.com/NuGet/NuGet.Client/blob/03079932b62466d38f2577e24f3a6b244bb30a49/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/NoOpRestoreUtilities.cs#L114-L145

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/ProjectLockFile/PackagesLockFileUtilities.cs#L19

**Comment by heng-liu** [comment]
We can solve the problem in the scenario mentioned above. That is, Enable RestorePackagesWithLockFile by setting the property to true, run first restore to generate the lock file, delete the lock file, run second restore will fail the  No-op and regenerate the lockfile.

But we have another scenario: enable restore package with lock file by generating a lock file but not setting the property, then the first restore will fail the No-op and re-generate lock file. Then we delete the lockfile and run the second restrore. Since there is no property set and no lock file exists, no lockfile would be generated. And it would No-op successfully.  Is this result correct? Thanks! @anangaur

**Comment by anangaur** [comment]
Yes this is as expected
