### ISSUE TITLE
How does NuGet choose between netstandard and netframework when installing?

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#7808]
I'm trying to find documentation on this but https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks only says:

> it tries to match the framework name of the assembly with the target framework of the project. If a match is not found, NuGet copies the assembly for the highest version that is less than or equal to the project's target framework, if available

For example, if there is a NuGet package with lib folders for net45 and netstandard2.0, what happens when you install into a net46 project? More generally, how is this decision made across different possible combinations of frameworks and versions?

**Comment by dominoFire** [comment]
> For example, if there is a NuGet package with lib folders for net45 and netstandard2.0, what happens when you install into a net46 project?

NuGet will try match the nearest framework assembly available. In your example, it will use the net45 assembly.
 
> More generally, how is this decision made across different possible combinations of frameworks and versions?

The FrameworkReducer.GetNearest() is the method that resolves the framework assembly to use depending on the available assemblies and the target project:

https://github.com/NuGet/NuGet.Client/blob/0781854111129d4c502fa44849fac974b46cc1f9/src/NuGet.Core/NuGet.Frameworks/FrameworkReducer.cs#L51

You can simulate this behavior in the following page:

http://nugettoolsdev.azurewebsites.net/4.8.0/get-nearest-framework?project=net46&package=net45%0D%0Anetstandard2.0%0D%0A

I will close the issue since it is a question. If you have more questions, you can post it on stackoverflow.com with the "nuget" tag.

**Comment by madelson** [comment]
@dominoFire thanks http://nugettoolsdev.azurewebsites.net/4.8.0/get-nearest-framework?project=net46&package=net45%0D%0Anetstandard2.0%0D%0A is exactly what I was looking for!

Would you consider linking this from https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks ?
