### ISSUE TITLE
Proposal: Allow specifying the package folder path in PackageReference

### ISSUE THREAD

**Issue by JeffCyr** [NuGet/Home#7826]
This is a proposal to allow specifying the package folder path in the PackageReference element, therefore skipping the actual package restore.

# Rationale
In a large mono-repo, it is common to split the projects in multiple solution file. Each solution are built individually, but there can be dependencies between them.

It is possible to configure a local folder as source to handle the local nuget packages, but it is inefficient in a build pipeline and the versioning (and nuget cache) is hard to manage on a dev machine.

It would be useful to set the package path directly in the PackageReference element for those same-repo dependencies.

It would also be useful to have an option in Pack to output the uncompressed package folder instead of a nupkg file. That would be another proposal.

# Usage

```xml
<PackageReference Include="packagename" Path="packagefolderpath" />
```

**Comment by nkolev92** [comment]
The fallback folders feature should cover your use case. 

There's only an old write-up for fallback folders https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders. 

Basically what fallback folders allow you to do, is mimic the consumption side of the global packages folder. 
The package is already fully installed(read extracted) on disk, so whenever NuGet needs to find a package it will find it in the fallback folder and skip any lookup/installation. 

More info https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild (please read the links in order as they'll make the most sense that way).

**Comment by JeffCyr** [comment]
Ideally it would have been simpler if you didn't have to specify the package version, but I can see how to make it work with fallback folders, thanks.

Wouldn't it make sense though to be able to specify the package path in PackageReference?

For `Pack`, do you think it would be a good idea to have an option to output the uncompressed package folder instead of a .nupkg? So the build wouldn't need to compress/uncompress in the same pipeline, it would also be easier to make things work in a IDE build on a dev machine.

**Comment by nkolev92** [comment]
> Ideally it would have been simpler if you didn't have to specify the package version

The version and id are the unique identifiers of a package. Not specifying the version will break all NuGet locking and caching mechanisms. 

> Wouldn't it make sense though to be able to specify the package path in PackageReference?

There's a couple of issues with that. Since we established that you need a version, the problem is the following: 

* The version metadata is really a version range. A range pointing to a specific package is confusing. 
* What happens with the package dependencies? Where are they found? 
* Say you have 10 different local packages. Now you need to specifying 10 paths.

With fallback folders the notion that something is already locally installed is abstracted from the end-user. The build perf optimizations and the project definition are separated. 

> For `Pack`, do you think it would be a good idea to have an option to output the uncompressed package folder instead of a .nupkg? So the build wouldn't need to compress/uncompress in the same pipeline, it would also be easier to make things work in a IDE build on a dev machine.

When you run restore when it extracts a package it generates .nupkg.metadata file that `pack` can't generate so it'd need to do more than just extracting a package. 

It'd be tricky to set-up a fallback folder with pack. 
The fallback folders follow a folder structure like (because it's more efficient than a flatlist): 
```
fallbackFolder
    PackageA
        1.0.0
        2.0.0
    PackageB
        2.1.1
        2.1.2
```

Each project would need to point to the package path to be generated. 

With fallback folders. 
You can have 1 output directory for all the packages. 
And then nuget.exe add through all of them to a certain directory.

**Comment by JeffCyr** [comment]
All good points, thanks for the detailed answer. I'll close the issue.
