### ISSUE TITLE
NuGet command client does not remove old executables when updating

### ISSUE THREAD

**Issue by SeanFarrow** [NuGet/Home#7835]
Whilst updating NuGet.exe (the commandline client) I noticed that it didn't remove the old version.

Would this be desirable behaviour? To my thinking it makes sense to remove a previous version assuming the new version has been extracted from the package successfully.

I'm happy to take this on, if it is a wanted change, but would ask what tests would be required, if any.

**Comment by rrelyea** [comment]
can you explain exact repro steps that you are doing (with paths, etc...) so we can fully discuss this idea with you?

**Comment by SeanFarrow** [comment]
To reproduce this, do the following:

Downgrade to an earlier version of NuGet.exe, I have version 3.3.0.212 here.
Ensure that you are either in the directory in which the NuGet.Exe file is present, or that this directory is in your path. My NuGet.exe file resides in c:\program files\NuGet.
Open a command prompt with administrator privileges.
Now run NuGet update -self.
You will notice that there are now 2 files in the folder that contains your NuGet.exe executable, NuGet.exe and NuGet.exe.old. NuGet.exe will be the latest version and NuGet.exe.old will be the version you were running previously.

I suggest removing the .old file after the .exe file has been extracted from the package

I hope that helps.

**Comment by zivkan** [comment]
NuGet.exe does try to [delete the old file](https://github.com/NuGet/NuGet.Client/blob/3472b01df9577554c536791fc0d848c70a763e4c/src/NuGet.Clients/NuGet.CommandLine/Program.cs#L264-L278). If it fails, it silently continues. Maybe we should write out a warning message, rather than failing silently.

My guess is that your user account has permissions to create and modify files in `c:\program files\nuget`, but not to delete, although you said you ran as Administrator, so that shouldn't be the case.

**Comment by zivkan** [comment]
Actually, what's happening is that during the update, the old nuget.exe renames itself to `nuget.exe.old`, and then downloads the new version to `nuget.exe`. But the old nuget.exe (now nuget.exe.old) can't delete itself because Windows doesn't allow deleting files that are in use, and since it's running, it's in use. However, the first time you run the new nuget.exe, the old one will be deleted.

To have the old file deleted during the update, we'd need the old nuget.exe to run the new nuget.exe, and the new nuget.exe would need to wait until the old nuget.exe process ends, so that the file is now possible to delete.

While not difficult to implement, personally, I consider it low priority, but probably a good/easy feature for anyone wanting to contribute a PR.

**Comment by SeanFarrow** [comment]
I wonder whether we should add a delay/retry to the delete function before doing the process dance?

**Comment by zivkan** [comment]
To be clear, when you run `nuget update -self`, it makes no attempt to clean up after itself. It can't, because on Windows, a process can never delete its own executable. It's the next execution (of the new executable) that cleans up the `.old` file. Therefore, if the `.old` file bothers you, you should run the new `nuget.exe`. The parameters don't matter. You could run `nuget update -self` again, or just `nuget` without parameters, or anything else.

As for an improvement to `update -self`, the problem with a delay is that best case the delay is longer than it needs to be, so the process takes longer to complete than needed, or worst case, tries to delete before the first process exits and therefore the file still can't be deleted. There's a risk with retrying because I wouldn't be surprised if malware scanners detect failed disk IO as a signal of possible malware. The only benefit for retry/delay is fewer lines of code, but I don't believe it would be too many lines of code to implement "correctly".

**Comment by SeanFarrow** [comment]
That workaround makes sense, feel free to close this.

**Comment by rrelyea** [comment]
We'll be doing bigger changes in nuget update -self -- so won't worry about this for now.
