### ISSUE TITLE
NuGet.API not fetching the latest versions of some packages

### ISSUE THREAD

**Issue by VladDerptastic** [NuGet/Home#7869]
## Details about Problem
Upon querying the [NuGet v3 API](https://api.nuget.org/v3/index.json), latest versions of packages are not available on it, in a similar fashion such as reported before (2016): https://github.com/NuGet/NuGetGallery/issues/2927

#### NuGet.Configuration:
Request: https://api.nuget.org/v3/registration3/nuget.configuration/index.json
UI: Latest (non-preview) in VS2017 UI - 4.9.3
API: Latest in API - 4.7.0-preview1-4986

#### NuGet.Packaging:
Request: https://api.nuget.org/v3/registration3/nuget.packaging/index.json
UI: Latest (non-preview) in VS2017 UI - 4.9.3
API: Latest in API - 4.7.0-preview1-4986

The case is the same for 
#### NuGet.Resolver

If they were versions that were uploaded a day or two earlier, I would scoff it off as caching issues, but those versions are available since 25.01.2019.

I can confirm I can also download the versions not mentioned in the index endpoint by requesting their resources explicitly: https://api.nuget.org/packages/nuget.packaging.4.9.3.nupkg

Is there a different source of "truth" for the latest versions that I'm missing? 
(Similar to the gradual change of the API from registration0 to registration3?
https://api.nuget.org/v3/registration0/nuget.packaging/index.json
https://api.nuget.org/v3/registration1/nuget.packaging/index.json
https://api.nuget.org/v3/registration2/nuget.packaging/index.json
https://api.nuget.org/v3/registration3/nuget.packaging/index.json )

**Comment by dominoFire** [comment]
By default, all preview versions in packages are not showed in the PackageManager UI for Visual Studio. You can list preview packages by checking the "Include prerelease" checkbox.

For more information on how to query the API for specific package info, look for the 
[NuGet documentation](https://docs.microsoft.com/en-us/nuget/api/overview ); in special, [Package metadata](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource) and [Package content](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource) sections.

I will close the issue since the VS2017 UI is showing the correct list of packages. If you have more questions, feel free to use stackoverflow.com

**Comment by dominoFire** [comment]
An additional note, in the case of the `RegistrationsBaseUrl` (i.e. https://api.nuget.org/v3/registration3/), it doesn't list package versions with SemVer 2.0.0 enabled; that's the reason why the examples doesn't fetch the latest versions.

You can use `RegistrationBaseUrl/3.6.0` (i.e. https://api.nuget.org/v3/registration3-gz-semver2/) for fetching package versions with SemVer 2.0.0; for example:

https://api.nuget.org/v3/registration3-gz-semver2/nuget.packaging/index.json

**Comment by VladDerptastic** [comment]
Perhaps I wasn't clear enough in my original text.
 
I was aware how to fetch them using the UI, but I was looking to query the API from code and get the latest version there, but the API endpoint I used did not produce the latest version (I was using the UI to manually validate my results against, which is why I mentioned it).

However your additional note addressed and clarified that. Thank you! :)
