### ISSUE TITLE
Fail to install CrossBase.Platform.IOS orEnvoc.Core.Mobile.iOS package to iOS app

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#792]
Repro steps:

1.File->New Project->Visual C#->iOS->iPhone->Blank App(iPhone)/Master-Detail App(iPhone).
2.Right click on the project and click "Manage NuGet Packages…"
3.Select CrossBase.Platform.IOS and Envoc.Core.Mobile.iOS package respectively, click Install button and verify these two packages can be installed correctly.

![1](https://cloud.githubusercontent.com/assets/1087852/8193690/811e3870-142b-11e5-9776-6091fbafa6de.png)

Eto.Forms 2.0.7 has this lib folder - portable-win8+net45+wp8+wpa81+monotouch+monoandroid+xamarin.mac

![2](https://cloud.githubusercontent.com/assets/1087852/8193695/86f3fb2c-142b-11e5-8637-33d87e00ac25.png)

Envoc.Core.Common 4.0.8 has this lib folder - portable-win+net45+MonoAndroid16+MonoTouch40+sl40+wp71

**Comment by danliu** [comment]
Discussed with Justin and this is by design. xamarin.IOS is not considered as compatible with xamarin.mac.

**Comment by mrward** [comment]
Is this the expected behaviour? I would have expected the PCL assembly from Eto.Forms to be referenced when installing it into a Xamarin.iOS project. 

With NuGet 2.8.5 the Xamarin frameworks are treated as optional when they are part of a PCL profile. On the Mac, which has Xamarin.Mac as a supported framework in various PCL directories, I can install Eto.Forms using Xamarin Studio into a Xamarin.iOS project and the assembly from the portable-win+net45+MonoAndroid16+MonoTouch40+sl40+wp71 will be referenced.

In NuGet 3.0 the optional Mono and Xamarin frameworks are [explicitly listed](https://github.com/NuGet/NuGet3/blob/a060bf2811af50f6ca7287d4b21ee3e3b9bbca66/src/NuGet.Frameworks/DefaultPortableFrameworkMappings.cs#L123-L126). In NuGet 2.8.5 the optional Mono and Xamarin frameworks were defined just by the [start of the framework name](https://github.com/mrward/nuget/blob/005f10352a67e8d1508a6980a8c057406c51bfca/src/Core/NETPortable/NetPortableProfileTable.cs#L220-L221).

This is not a problem on Windows with Visual Studio since it Xamarin.Mac is not supported there. On the Mac side I can add support for Xamarin.Mac to Xamarin Studio's version of NuGet.
