### ISSUE TITLE
Regression in 'Nuget sources add' causes "The ':' character, hexadecimal value 0x3A, cannot be included in a name" errors

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7948]
## Details about Problem

NuGet product used: nuget.exe

NuGet version: 4.9.4.5839

Worked before? If so, with which NuGet version: 4.6.0.4653

## Automated Repro

1. Unzip [nugetColonRepro.zip](https://github.com/NuGet/Home/files/3034964/nugetColonRepro.zip) somewhere on your machine
2. Run repro.bat

## Detailed repro steps so we can see the same problem

1. Run `nuget sources add -name http://foo.com -Source http://foo.com -config %workdir%\nuget.config`
   - This succeeds
2. Run `nuget sources add -name http://foo.com -Source http://foo.com -config %workdir%\nuget.config -username user -password password`
   - This fails with the error `The ':' character, hexadecimal value 0x3A, cannot be included in a name.`
   - This used to work fine in 4.6.0

## Verbose Logs

Setting `-verbosity detailed` yields this stack trace:

> The ':' character, hexadecimal value 0x3A, cannot be included in a name.
> System.Xml.XmlException: The ':' character, hexadecimal value 0x3A, cannot be included in a name.
>    at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
>    at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
>    at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
>    at NuGet.Configuration.CredentialsItem.AsXNode()
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
>    at NuGet.Configuration.SettingsGroup`1.AsXNode()
>    at NuGet.Configuration.SettingsGroup`1.Add(T setting)
>    at NuGet.Configuration.NuGetConfiguration.AddOrUpdate(String sectionName, SettingItem item)
>    at NuGet.Configuration.Settings.AddOrUpdate(SettingsFile settingsFile, String sectionName, SettingItem item)
>    at NuGet.Configuration.Settings.AddOrUpdate(String sectionName, SettingItem item)
>    at NuGet.Configuration.PackageSourceProvider.AddPackageSource(PackageSource source, Boolean shouldSkipSave, Boolean& isDirty)
>    at NuGet.Configuration.PackageSourceProvider.AddPackageSource(PackageSource source)
>    at NuGet.CommandLine.SourcesCommand.AddNewSource()
>    at NuGet.CommandLine.Command.ExecuteCommandAsync()
>    at NuGet.CommandLine.Command.Execute()
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
> 
>

**Comment by rrelyea** [comment]
@bergbria  - Can you test with 4.9.x as well?
My guess is the trusted sources and config work we did there may have broken this in 4.9.x.
Workaround for now, avoid ":". 

@donnie-msft  - if this is a regression we introduced in 4.9.x, we should likely understand what other cases might be broken and review with @anangaur  and @rrelyea about the plan.

**Comment by bergbria** [comment]
@rrelyea, I assume you meant to test with 4.**8**.x. I've just now confirmed that 4.8.2 works fine.

**Comment by mrward** [comment]
This is also affecting Visual Studio for Mac 8.1 with NuGet 5.0. It looks like a regression in NuGet 4.9 and 5.0.

Looking at the code the problem seems to be that source url is used as the element name that holds the credentials inside the packageSourceCredentials element. NuGet 4.8 and earlier use the package source name. This following bit of code looks wrong to me. It passes the Source to the CredentialsItem's constructor but the parameter is for the package source name.

https://github.com/NuGet/NuGet.Client/blob/fc0c2072b79674975d6fac5f332ae8359cef094a/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceCredential.cs#L207

The above code is used by NuGet 5.0 and NuGet 4.9.

If I create add a new 'test' package source with username/password but pointing to a local folder (e.g. /Users/UserName/test) then NuGet 5.0 adds the following:

    </packageSourceCredentials>
        <_x002F_Users_x002F_UserName_x002F_test>
          <add key="Username" value="user" />
          <add key="Password" value="..." />
        </_x002F_Users_x002F_UserName_x002F_test>
    </packageSourceCredentials>

NuGet 4.8 would have added:

    </packageSourceCredentials>
        <test>
          <add key="Username" value="user" />
          <add key="Password" value="..." />
        </test>
    </packageSourceCredentials>

Only workaround is to directly edit the NuGet.Config file. Using a package source name without a ':' character, which is what original bug description is doing, does not seem to be a workaround since the source url is being used as the element name.

**Comment by mrward** [comment]
The problem in VS Mac looks to be a bug in VS Mac. VS Mac is passing the package source url to the PackageSourceCredential.FromUserInput. It should be passing in the package source name. With NuGet 4.8 the PackageSourceCredential.Source was not used when saving the NuGet.Config file. With NuGet 4.9 and later it is used.

Looking at the [NuGet 4.9 source code](https://github.com/NuGet/NuGet.Client/blob/fc0c2072b79674975d6fac5f332ae8359cef094a/src/NuGet.Clients/NuGet.CommandLine/Commands/SourcesCommand.cs#L175) where `nuget sources add` is handled that seems to be OK - it uses the name parameter, so as long as that does not use a url, then `nuget sources add` will work.
