### ISSUE TITLE
VS NuGet package manager incorrectly uses project.json when managing csproj's packages

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#797]
I have a csproj and project.json in the same directory.

When I choose to manage the csproj's NuGet packages in VS by right clicking on References and choosing Manage NuGet Packages, the information displayed in VS is from the project.json, not the csproj's packages.config file.

**Comment by emgarten** [comment]
This is expected. Having a project.json file in your project signals to NuGet that it supports the VS 2015 version of NuGet in the same way that packages.config is used today to determine if the project is using NuGet. The newer project.json file will override the older packages.config, which is why you see it used in Manage NuGet Packages.

You can work around this by moving the project.json file to a sub directory and NuGet will start using packages.config again.

**Comment by JamesNK** [comment]
Why doesn't packages.config take precedence?

**Comment by yishaigalatzer** [comment]
The design is for `project.json` to take precedence so that we move you to the new world without having to force you to delete `packages.config`
