### ISSUE TITLE
[NuGet.VisualStudioExtension] Focus jums to the first item of the packages list if next page loaded

### ISSUE THREAD

**Issue by xperiandri** [NuGet/Home#805]
When I navigate with a keyboard within a package list and I reach last loaded item, the list loads more packages and looks like it stays at this point. However when I press key down focus jumps to the first item of the list which is extremely annoying!!!
Fix this, please.

I reported this with "Sand a Frown" from Visual Studio but looks like that feedback was not routed to appropriate team :(

**Comment by yishaigalatzer** [comment]
Thanks for this report.We didn't seem to see this issue for some reason.

I can reproduce it now. Given that we are almost locked down for RTM, I'm going to try and get this fixed if possible in the next two days. Otherwise we will fix it in the following release

**Comment by yishaigalatzer** [comment]
OK, I see what is going on. The last item on the list is the Loading indicator, and it gets selected by the keyboard, since this items gets removed and reinserted the selected item is no longer available and hence the selection jumps to the top.

We should probably disable selection on this item. 

A workaround for you (pretty bad one I must say) is to hit the up key once you get to the bottom of the list and wait for new items to show up. I know it is not a good answer from a product perspective, but it might actually help you in your daily work.

**Comment by xperiandri** [comment]
Cool! Thanks!
