### ISSUE TITLE
Adding a reference to source package depending on another source package

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#8064]
## Details about Problem

VS UI:
![image](https://user-images.githubusercontent.com/41759/56776667-7eaa2500-6782-11e9-93ed-4a4a9903767b.png)

Worked before? If so, with which NuGet version:

No.

## Detailed repro steps so we can see the same problem

1. Create a .NET Standard 2.0 class library.
2. Add a package reference via VS UI to package `Microsoft.CodeAnalysis.Debugging` `3.2.0-beta1-19225-01` from feed `https://dotnet.myget.org/F/roslyn/api/v3/index.json`
3. NuGet correctly discovers two packages to add:
![image](https://user-images.githubusercontent.com/41759/56776733-b913c200-6782-11e9-972d-17e40aefcfff.png)
4. Confirm dialogs and open project file once finished:
![image](https://user-images.githubusercontent.com/41759/56776767-dfd1f880-6782-11e9-9d90-545a5d5c0424.png)

Reference to `Microsoft.CodeAnalysis.PooledObjects` is missing.

**Comment by dominoFire** [comment]
Hi @tmat,

When you're using PackageReference inside the .csproj file, only the main dependency is needed. In this case, because PooledObjects is a dependency of Debugging package but, not a dependency of your .csproj project, you only need to add the PackageReference to Microsoft.CodeAnalysis.Debugging.

It appears that the UI makes some confusion by showing that it will to install two packages to the project but, only one PackageReference is required.

**Comment by tmat** [comment]
The Debugging package depends on files from PooledObjects package, so both must be referenced by the project that references Debugging package.

**Comment by nkolev92** [comment]
This happens because both build and contentFiles are excluded transitively by default. 

The dependency is added as: 

>         <dependency id="Microsoft.CodeAnalysis.PooledObjects" version="[3.6.0-beta1-20060-10, 3.6.0-beta1-20060-10]" exclude="Build,Analyzers" />



https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

The package needs to be rebuilt with a custom PrivateAssets. You can also consider using buildTransitive if VS 2019 is the only VS target version. 

Beyond this I'm not sure there's any action on NuGet side. 
@tmat Can you verify that my suggestions actually fix your package?

**Comment by nkolev92** [comment]
Closing per the above comment.
