### ISSUE TITLE
wrong upgrade prompt

### ISSUE THREAD

**Issue by Varorbc** [NuGet/Home#8136]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.0.2

dotnet.exe --version (if appropriate):

VS version (if appropriate): 16.0.4

OS version (i.e. win10 v1607 (14393.321)): win10 v1809 (17763.437)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.
![image](https://user-images.githubusercontent.com/5714438/57828315-a7e82f00-77dd-11e9-958e-67a6310717d4.png)

2.The preview12 version number is greater than the preview9 version number, but the prompt is upgraded to the latest version preview9

**Comment by zivkan** [comment]
@Varorbc thanks for taking the time to write.

NuGet uses [semantic versioning 2.0.0](https://semver.org/) although extended to also be compatible with [`System.Version`](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=netcore-2.2#remarks) for backwards compatibility with NuGet's earliest history.

Section 9 of the Semantic Versioning 2.0.0 spec defines prerelease labels and says this:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

Notice it says "dot separated". Also notice the examples they provide: `1.0.0-alpha`, `1.0.0-alpha.1`, `1.0.0-0.3.7`, `1.0.0-x.7.z.92`.

Since the prerelease label in your screenshot is not dot separated, the identifier contains both letters and digits and there cannot be parsed as an integer. As a result, it is sorted lexicographically. The package author needs to change the prerelease label to `preview.9` and `preview.12`, in which case the will be two identifiers, the second of which can be parsed as an integer, and then NuGet should order them according in the order you desire.

I appreciate you made the effort to contact us, but in this case I believe that NuGet is working correctly, according to the specification.
