### ISSUE TITLE
Don't warn about native DLLs outside lib

### ISSUE THREAD

**Issue by ClaytonHughes** [NuGet/Home#8142]
## Details about Problem

The warning NU5100 purports to warn about Assemblies outside of the `lib` folder. However, it also warns about Native Dlls outside of the lib folder ([and, indeed, anything with the extension dll](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Packaging/Rules/MisplaceAssemblyOutsideLibRule.cs#L32)).

This can be ignored with nuget.exe's `-NoPackageAnalysis` flag, but that is a bit overkill when I only want to avoid specific instances of a specific warning. If there were a way to disable this specific warning entirely (as the comments in https://github.com/NuGet/Home/issues/5655 seem to suggest is possible, although I don't see anything in `nuget help pack` about how to ignore specific codes), I'd still rather not disable it completely.

I'd like:

**A.** NuGet to inspect the dlls it's complaining about to see if they are indeed managed assemblies

or

**B.**  a way to disable warnings for specific files (in this case the Native dlls)

As a workaround, native dlls can be put in `\lib\native`, although in my case that isn't exactly where I want them.

NuGet.exe (version 5.0.2.5988) 
Windows 10 v1809 (17763.379)
I'm also using  Visual Studio 17, Version 15.8.8

## Detailed repro steps so we can see the same problem

See attached project, below

`HelloNativeDll.dll` is a native dll, and `HelloManagedLibrary.dll` is a Managed Assembly.

The included `nuspec` file puts the native dll where I might want it, but also "misplaces" a .NET assembly, since the point here is that I'd like to reduce spurious warnings without hiding actual problems.

`pack-Expect1WarningGet2.bat` does what it says: runs nuget pack and gets two warnings: one for the native dll put where I wanted it, and one for a managed assembly that is a legitimate warning. Ideally, it would only produce the latter. 

### Sample Project
[NuGetNativeDllExample.zip](https://github.com/NuGet/Home/files/3194659/NuGetNativeDllExample.zip)

**Comment by nkolev92** [comment]
In NuGet.exe pack they are supported by passing the Properties option. 

`nuget.exe pack mixeddlls.nuspec  -Properties NoWarn=NU5100` 
I have created a docs issue to call it out clearly: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1457


> B. a way to disable warnings for specific files (in this case the Native dlls)

 It's challenging to customize warnings because we have plenty of warnings and expressing that would be an open ended exercise where NuGet would need to be reading lots of different customization instructions, which would need to be expressed through properties. 
I'd say by design this warning is working as expected. You are doing a custom thing that NuGet is just suggesting is not the best practice. You are free to suppress, ignore it. 

> A. NuGet to inspect the dlls it's complaining about to see if they are indeed managed assemblies

How does this help your scenario?

**Comment by nkolev92** [comment]
Closing this issue at this point as lower priority.
NuGet examining the content packed is not something we are considering at this point.

**Comment by chtenb** [comment]
@nkolev92 
How do you suppress this warning when you pack on build using `    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
`?

**Comment by chtenb** [comment]
It seems setting `    <NoWarn>NU5100</NoWarn>` takes care of it.
