### ISSUE TITLE
Indirect references not copied when PackageReference Format

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/Home#8149]
I create a class lib project using the sdk format in which I installed a package with dependencies and I only access the classes of the top package.

I then create a console app and reference the class lib, however in the output folder I see the class lib and the the package assembly. The dependency package is missing causing an exception.

This setup works fine in the old csproj format.

**Comment by rrelyea** [comment]
VS version?
Net core sdk version?
Small repro solution?
Was your old csproj example using packages.config or packagereference?

**Comment by apobekiaris** [comment]
[ClassLibrary3.zip](https://github.com/NuGet/Home/files/3206587/ClassLibrary3.zip)
Old project yes with packages.config and if you try to migrate the old to packagereferences again it does not copy so I thought maybe it was the sdk format required.

VS 2017 Enterprise 15.9.11, I am not sure how it gets the sdk as I am new to this, trying to migrate my old projects to the new format to support dotnetcore. But in the system i have the following sdks

```
2.1.202                2.1.202                C:\Program Files\dotnet\sdk
2.1.504                2.1.504                C:\Program Files\dotnet\sdk
2.1.505                2.1.505                C:\Program Files\dotnet\sdk
2.1.600-preview-009497 2.1.600-preview-009497 C:\Program Files\dotnet\sdk
2.2.102                2.2.102                C:\Program Files\dotnet\sdk
```

**Comment by apobekiaris** [comment]
u see in the sample that  i use the Xpand.XAF.Modules.AutoCommit package which have a dependency to Xpand.XAF.Modules.Reactive which dependency does not go to the Console app output. However it goes to the class lib

**Comment by rrelyea** [comment]
I am not able to run your sample. 
Had to downgrade package version to 0.0.26 because 0.0.27 had a dependency that wasn't on nuget.org.
Then ran into build errors:
```
  C:\Users\rrelyea\.nuget\packages\xpand.versionconverter\1.0.22\build\Xpand.Ver
sionConverter.targets(4,9): error : Exception calling "GetVersionInfo" with "1"
argument(s): "The specified path, file name, or both are too long. The  [C:\temp
\cl3\ClassLibrary3\ClassLibrary3.csproj]
  C:\Users\rrelyea\.nuget\packages\xpand.versionconverter\1.0.22\build\Xpand.Ver
sionConverter.targets(4,9): error : fully qualified file name must be less than
260 characters, and the directory name must be less than 248 characters." [C:\te
mp\cl3\ClassLibrary3\ClassLibrary3.csproj]
```

Regardless, I think I understand the problem you are running into.
When you have a project that is PackageReference based, like your classlib project, other projects that reference it (like your console app) should:
1) be PackageReference style also (if not packagerefs, set RestoreProjectStyle - https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#using-packagereference-for-a-project-with-no-packagereferences
2) should use ProjectReference to classlib, not Reference like you currently do:
```
    <Reference Include="ClassLibrary3">
      <HintPath>..\ClassLibrary3\bin\Debug\net461\ClassLibrary3.dll</HintPath>
    </Reference>
```
this is because Restore (in packagereference world) is transitive, and needs to understand details about packages used in classlib project.

Because of the build errors I got on my machine, i wasn't able to test those 2 fixes out completely.
Let me know how that goes.

**Comment by apobekiaris** [comment]
thanks a lot for the fast answer Rob, you suggestions resolved my problem.
