### ISSUE TITLE
Use "$(SolutionDir)\packages\" Instead of Relative Path For Nuget Package References HintPaths

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8233]
<p>My team members each have their own solution (.sln). Some developers manage a larger scale solution while others manage a smaller area of the entire scheme. Some developers include unit test projects in their solution while others don't. Currently, if someone references a package from NuGet, the proj file's hint paths get set to a relative path of the solution that was open when the package manager added the reference. This path may be invalid on another developers machine. <br>My current solution is to edit the proj file xml and change the relative path to the $(SolutionDir) variable. This works great. Could we have this happen by default or as an option?</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/558708/use-solutiondirpackages-instead-of-relative-path-f.html
VSTS ticketId: 887957_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/7/2019, 03:23 AM (37 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team</p>

**Comment by nkolev92** [comment]
One option is to put a NuGet.Config in the common path for all the solutions and set 

```xml
<configuration>
  <config>
    <add key="repositoryPath" value="somePackagesDirectory" />
  </config>
</configuration>
```

SolutionDir is not used because it cannot work when you are building the csproj directly. 
I'd suggest a won't fix for this. @anangaur 

Related: https://github.com/NuGet/Home/issues/5931

**Comment by anangaur** [comment]
Thanks @nkolev92 for the workaround. I agree we need not fix this as the alternative should just work fine.

**Comment by JorgeEscobarPacheco** [comment]
@nkolev92 I tried to put it on a common path ... but it's not working for me.... are there any other configurations I need to check ?

**Comment by nkolev92** [comment]
That should be sufficient. 

Not sure what could be going wrong in your case. 

Try testing them individually...try deleting the packages folder and running restore after you've set the NuGet config etc.

**Comment by ro-jo** [comment]
Can you reopen this issue? It's a problem that's been around since inception and as far as I can see, has never been addressed.

Scenario: C++ solutions
Solution A stores packages in D:\packages
Solution B uses D:\B\temp\packages

When NuGet package manager is used to install Nuget packages, it hard codes the packages folder, relative to the project where possible.

Let's assume each solution contains 100 projects each, and 5 projects appear in both solutions.

Those 5 cannot be maintained using NuGet package manager.

Within solution A, something like this will appear in the project file after installing a c++ package:
<Import Project="..\packages\...

From Solution B it will fail, the packages folder does not exist.

IF NuGet wants to hack project files, please do so responsibly. Here's an idea:

1. Add a new setting in NuGet.config: AssignPackagesFolderToProperty=SomePropName

2. Hack the project file better, e.g. insert this:
`<PropertyGroup>
<SomePropName Condition="'SomePropName'==''">..\packages</SomePropName>`
etc.

3. In each instance, use $(SomePropName) in place of ..\packages

It allows a developer to override that property for each solution.

Simple? Otherwise how is the problem solved while maintaining compatibility with NuGet package manager? If any project is manually fixed, the next use of package manager will undo the fix or will simply function incorrectly, fail to remove previous package imports, and so on.

**Comment by nkolev92** [comment]
@ro-jo 

The packages.config flaws were well noted and PackageReference was designed with those issues in mind. For that reason PackageReference projects do not hard code paths into the project file. 

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

There are no plans to add new features to packages.config at this point.

**Comment by ro-jo** [comment]
Thank you, but did you notice I mentioned the solutions were c++? How is PackageReference going to help?

Is it best to abandon using NuGet for large solutions that share C++ projects?

**Comment by nkolev92** [comment]
@ro-jo 

Upvote https://developercommunity.visualstudio.com/idea/351636/use-packagereference-in-vcxproj.html for that.

**Comment by ro-jo** [comment]
If you don't mind me saying, that's a waste of time. Seen it, ignored it, just like you will at Microsoft - you think we don't know you're going to ignore it? You haven't been able to fix a problem that affects any package with a props or targets file - for years. That issue was posted a year ago after several years of you lot doing nothing about it, even though it's not complicated. I guess it's political... C++ devs hijacking your .Net toys, or are you not clever enough? Your obtuse response to my question says a lot. Thank you so much.
