### ISSUE TITLE
Package Deprecation UI - Open questions

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8314]
There are 2 open questions for the PM UI for 16.3/5.3

https://github.com/NuGet/NuGet.Client/pull/2899#discussion_r297328623

Should the deprecation info be displayed in all source? There's no guarantee of consistency here. 

https://github.com/NuGet/NuGet.Client/pull/2899#discussion_r297327833

Should the alternative package be displayed as:

current:
`BaseTestPackage version 1.0.0 (or higher)`

proposed:
`BaseTestPackage >= 1.0.0`

//cc @xavierdecoster @anangaur

**Comment by anangaur** [comment]
> NuGet/NuGet.Client#2899 (comment)
>
> Should the deprecation info be displayed in all source? There's no guarantee of consistency here.

I think we should show the deprecation info even if multiple sources are selected. Ideally we should list (sxs) all the links to sources where this package ID is present as we do today for nuget.org. Obviously there are questions like the following, I am taking a shot at answering these:

1. What happens if one of the multiple sources have the deprecation info?
[AG] We should show deprecation info even if one of the sources has this info.

2. What if there are varying deprecation infor across multiple sources?
[AG] We could either use the first one but prefer nuget.org if its one of the sources. This is a corner case scenario. We should solve for this multiple sources in a better way, once we start seeing customer reports regarding this.

> NuGet/NuGet.Client#2899 (comment)
>
> Should the alternative package be displayed as:
>
> current:
> BaseTestPackage version 1.0.0 (or higher)
>
> proposed:
>BaseTestPackage >= 1.0.0

I think we can just live with `BaseTestPackage version 1.0.0`. By default today, this means 1.0.0 or higher, doesn't it? e.g. pack 😄

**Comment by nkolev92** [comment]
> Ideally we should list (sxs) all the links to sources where this package ID is present as we do today for nuget.org. 

It's available in the tooltip right now. 

> 1. What happens if one of the multiple sources have the deprecation info?
[AG] We should show deprecation info even if one of the sources has this info.

Not trivial today, as our merging throws out duplicates. 

> 2.What if there are varying deprecation infor across multiple sources?
[AG] We could either use the first one but prefer nuget.org if its one of the sources. This is a corner case scenario. We should solve for this multiple sources in a better way, once we start seeing customer reports regarding this.

You know my thoughts on preferring sources, lol :D We shouldn't do it :D

Both of these only affect the merging in VS, so it's isolated work.

I'd argue we shouldn't do inconsistent stuff until we change that. 
My suggestion is to either do what your recommending in full or just don't bother with deprecation on the all sources. 

> I think we can just live with BaseTestPackage version 1.0.0. By default today, this means 1.0.0 or higher, doesn't it? e.g. pack 😄

I don't know how obvious this is to the packages.config people unfortunately. 
That's why I prefer being explicit, especially since there's no added cost (it's extremely simple for Xavier to change it )

**Comment by xavierdecoster** [comment]
> You know my thoughts on preferring sources, lol :D We shouldn't do it :D

I second that! :)

Regarding the formatting of the alternate package info, I'm sticking to the already used `PrettyPrint` format, but without parentheses: `BaseTestPackage >= 1.0.0`

**Comment by rrelyea** [comment]
@xavierdecoster  - is there still work to be merged for 5.3 involved with this issue? If so, eta? Thx
If not, let's fix the milestone.
Time is ticking on any 5.3 work. Ideally it would come in time for us to insert into VS thursday or friday. 
Issues after that may be fixable in 5.3, or may have to wait until 5.4

**Comment by xavierdecoster** [comment]
The way alternate package info displayed has been fixed and merged, and I just verified behavior for deprecation info when multiple sources are selected and one of them emits deprecation info: LGTM; as @anangaur suggests, _"we should solve for this multiple sources in a better way, once we start seeing customer reports regarding this"_.

No further work involved for this issue.
