### ISSUE TITLE
NuGet no longer uses CPS's JTF

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8317]
zivkan edit: this is the new issue objective:

For years, NuGet was using CPS (Common Project System, later renamed to the Visual Studio Project System) instance of the JoinableTaskFactory (JTF). As [described below](https://github.com/NuGet/Home/issues/8317#issuecomment-510281346), this is no longer necessary, so NuGet can stop obtaining the CPS JTF and just use `ThreadHelper.JoinableTaskFactory`, or using the JTF provided from the package, or other techniques available to all VS extensions.

Note that `ThreadHelper` does not provide a way to set a JTF for unit testing: https://github.com/microsoft/vs-threading/blob/main/doc/testing_vs.md

However, `NuGetUIThreadHelper` does provide a way for us to set the JTF for testing, which some tests use. Updating the product code and tests to use a different pattern is out of scope for this task, so we won't get rid of the `NuGetUIThreadHelper` class at this time, but this is a refactoring concern. It doesn't have the same product risks as changing which JTF instance we use.

edit: this is the old issue objective:

We have lots of inconsistencies in our codebase where we use ThreadHelper.JoinableTaskFactory instead of NuGetUIThreadHelper. 

We need to investigate whether this can cause potential issues and fix them. 

We have 108 references of ThreadHelper.JoinableTaskFactory
and 385 references of NuGetUIThreadHelper.JoinableTaskFactory

**Comment by AArnott** [comment]
That shouldn’t (generally) be an issue: JTF instances all coordinate through the common JoinableTaskContext. So as long as they both point to the same one of those, mixing various JTF instances should not result in a deadlock.

That’s speaking generally. The one caveat here is that CPS/NuGet have a very specialized JTF derived type that can mitigate deadlocks between the main thread and the CPS project lock. In some cases it’s crucial to be using the right JTF instance in that case. I don’t know if the project lock is relevant here though. I haven’t investigated myself (yet).

I suspect that the goal with the mixed use of JTF is to use the common shell one everywhere except where you _must_ use the CPS one in order to avoid loading CPS where it does not apply.

@lifengl and I have discussed a way to completely remove the specialized JTF to make this complexity disappear. It involves changing the syntax for project lock users from a "using" block pattern to a delegate pattern. Looking at the CPS `IProjectLockService` interface it appears that work may have already been done. So *maybe* you can get rid of the `NuGetUIThreadHelper.JTF` altogether and just use `ThreadHelper.JTF` everywhere. @lifengl, can you please comment?

**Comment by AArnott** [comment]
@jviau confirmed that CPS already has the new delegate-based lock that removes the need for the specialized JTF.

> I believe this was addressed in dev16. CPS switched to a delegate style JTF project lock, removing the need for the specialized JTF. The special JTF is still there though to support the old using style project lock. All of CPS moved over to the new style, so if nuget switches to the new style as well they can hopefully get rid of that abstraction layer over what JTF they use.

**Comment by nkolev92** [comment]
Thanks @AArnott 

How involved would that change be? 
I don't imagine is as simple as changing NuGetUIThreadHelper.JoinableTaskFactory to ThreadHelper.JoinableTaskFactory.

What are the benefits of not having to use our JTF facade? 
Less likely to introduce deadlocks? Moves out the complexity out of the NuGet codebase? 
Anything that I'm missing? 

//cc @rrelyea

**Comment by AArnott** [comment]
So the first thing you should probably do is review all your uses of `IProjectLockService` (if any) and make sure you're using the delegate syntax instead of the `using` block syntax. Transitioning should be a low risk change, as you're moving to a safer syntax that guards against deadlocks without you having to be particular about which JTF instance you're using.

After that, you can safely use any JTF instance you want, in terms of deadlock avoidance. But you generally should prefer your own `AsyncPackage.JoinableTaskFactory` instance over `ThreadHelper.JoinableTaskFactory` so that any async work you execute will be tracked and will block IDE shutdown till its done. 

As for a facade, you should always use JTF directly. If you have a helper class you pass around that carries that JTF instance (hopefully from your `AsyncPackage`, that's totally fine. But don't "hide" JTF behind an abstraction as that will defeat many of our analyzers that try to keep you using the safe patterns to avoid deadlocks.

**Comment by nkolev92** [comment]
Thanks for the explanation :)

**Comment by zivkan** [comment]
I updated the title of this issue, and edited the first comment (so anyone reading this issue from NuGet's release notes can clearly see what it's about) to say:

For years, NuGet was using CPS (Common Project System, later renamed to the Visual Studio Project System) instance of the JoinableTaskFactory (JTF). As [described below](https://github.com/NuGet/Home/issues/8317#issuecomment-510281346), this is no longer necessary, so NuGet can stop obtaining the CPS JTF and just use `ThreadHelper.JoinableTaskFactory`, or using the JTF provided from the package, or other techniques available to all VS extensions.

Note that `ThreadHelper` does not provide a way to set a JTF for unit testing: https://github.com/microsoft/vs-threading/blob/main/doc/testing_vs.md

However, `NuGetUIThreadHelper` does provide a way for us to set the JTF for testing, which some tests use. Updating the product code and tests to use a different pattern is out of scope for this task, so we won't get rid of the `NuGetUIThreadHelper` class at this time, but this is a refactoring concern. It doesn't have the same product risks as changing which JTF instance we use.

**Comment by AArnott** [comment]
> Note that ThreadHelper does not provide a way to set a JTF for unit testing: https://github.com/microsoft/vs-threading/blob/main/doc/testing_vs.md

This is no longer true. See https://github.com/microsoft/vssdktestfx. We use this in many VS unit test projects and it successfully mocks up ThreadHelper and a UI thread to even reproduce certain deadlocks from the product within your unit tests.

I'll get the testing_vs.md doc that was referenced here updated.
