### ISSUE TITLE
NU1201 Project is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project supports: net462 (.NETFramework,Version=v4.6.2)

### ISSUE THREAD

**Issue by empz** [NuGet/Home#8318]
I have a ASP.NET Core 2.2 project that references a .NET Framework 4.6.12 class library. This worked without any issue until I migrated the class library to PackageReference and started to get that error.

It was my understanding that a netcore 2.2 project (net standard 2.0) could reference a .NET framwork 4.6.2 (net standard 2.0) without issue and this was the case when using package.config. 

Is this intended? Why?

**Comment by nkolev92** [comment]
@eparizzi 

Your error message suggests the project is net462, which is not supported via AssetTargetFallback (the fallback mechanism that allows netcoreapp2.2 to reference net461 (not higher).

**Comment by empz** [comment]
@nkolev92 So, what are my options here? Is there any net fwk version compatible with this setup? 4.7.2 maybe? Or I have to stick with packages.config?

**Comment by nkolev92** [comment]
.NET 461 is compatible. 

Once .NET Core 3.0 gets released, all of the .NET Framework will be compatible (with a fallback)

**Comment by BruceWangNo1** [comment]
For those who ran into error NU1201, you might have come to the right place. This may not apply to the question asked but I ran into error NU1201 the other day and the reason for that is the nuproj configuration file for our nuget project has target configuration wrong. It should have been 

> `<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>`

 instead of 

> `<TargetFramework>net462</TargetFramework>`

 because the project is not of "SDK-style."

References: [https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019)
