### ISSUE TITLE
Restore with RestoreLockedMode  and no lock file should error.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#8338]
## Details about Problem

The restore with RestoreLockedMode  = true and no lock file does not work or error but a new lock file is created. 

## Detailed repro steps so we can see the same problem

1. Create a project with RestoreLockedMode = true and delete the lock file if present.

2. Build/restore. 

Result: No error and the lock file is created.

**Comment by ite-jankl** [comment]
Isn’t this how you create a lock file? How would that be created then? Through a new, dedicated target/promoting a target to be the recommended way?

**Comment by nkolev92** [comment]
@ite-klass 

The lock file has a dual purpose, sort of an input-output behavior with restore. 

That dual purpose is controlled by the locked mode switch.

In development mode, without `RestoreLockedMode=true`, you can create a file and opt into using a lock file.
If you are in locked mode, the expectation for the user is that there's something to lock to. In particular, you don't want the file to be regenerated. As such, the file not existing is a problem in this.

**Comment by Nigusu-Allehu** [comment]
Based on my observations and tests, when a project with RestoreLockedMode = true is built/restored without the presence of a lock file, it looks like it does not create a new lock file.

**Comment by jvmdc** [comment]
I am not sure why this is marked as completed. As I understand the initial post, the issue is that no error is thrown when running in locked mode, thus you have no guarantee that a lock file was actually used. While you can rely on the individual project having committed a lock-file, for a centralized CI/CD setup, it is nice to be able to enforce this as a requirement to ensure reproducible builds.

The functionality missing here is similar to `npm ci`  which will fail if no lock file is present.

If I am wrong, please point me in the right direction on how to ensure this :)
