### ISSUE TITLE
Binding redirect not added when update the NuGet packages

### ISSUE THREAD

**Issue by ganesanviji** [NuGet/Home#8340]
Hi  

I have tried to update the NuGet packages in my ASP.NET MVC Project. NuGet packages updated to the latest assembly, but the binding redirect entries is not added in the web config file. 

Replication:
1. Create the ASP.NET MVC application
2. Update the NuGet packages using NuGet update command
3. Check the web config entries and the binding redirect is not updated in the web config file 

![image](https://user-images.githubusercontent.com/8706341/61370682-a5bf5100-a8b0-11e9-8b25-27f274681f46.png)

Could you please suggest the solution on this?

Thanks

Ganesan R.

**Comment by ganesanviji** [comment]
Hi 

Could you please any one suggest me on this?

Regards,
Ganesan R.

**Comment by donnie-msft** [comment]
Is it possible that you have disabled binding redirects in any of your nuget.config files? See [this documentation](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#bindingredirects-section).

Other than that, please include a project that reproduces the problem so that we can better understand what's happening.

**Comment by ganesanviji** [comment]
Hi @donnie-msft 

Thanks for the update. Now binding redirect has been updated after update binding redirect skip key as false in nuget.config file.
