### ISSUE TITLE
Question: How does nuget.exe get it's version number (esp. build number)

### ISSUE THREAD

**Issue by penCsharpener** [NuGet/Home#8354]
Maybe this is more a question for StackOverflow but since Nuget is the particular inspiration here, I'll post here.

I've just updated to my local nuget.exe to 5.1 and run `nuget` which showed the following version number:
`5.1.0.6013`

How does the 6013 get there? I've google so many pages in the search for automatic, incrementing build numbers but it never exactly tells me how to implement this. Is `6013` simply incrementing up and doesn't that create git noise? 
Or is it only incremented by the CI?
Is it possible to use the total count of commits in the branch as that number and if yes, how could I get it there?

thanks for considering the question

**Comment by nkolev92** [comment]
It's the CI build number. 

It's only really implemented on the CI. Pretty much all CI/CD services allow for some sort of a build number, that you can embed into your assemblies.

On NuGet side we do some manual [work](https://github.com/NuGet/NuGet.Client/blob/686dd6b060639a0fb401eceb4c3a4029c1482023/build/vsts_build.yaml#L33-L49) to get our CI build id to be the same as the assembly build number, but that usability and discoverability driven.


[Here's](https://github.com/NuGet/NuGet.Client/blob/23d260f6b405db13cc1eb751231f683e0c141913/build/vsts_build.yaml#L143) how we pass it to our build. 

You can implement any custom logic that makes sense for you, but it's probably best if you didn't look at the commit count, as the build number, should be just that, build number, rather than how many changes went into this build. 
If say you change your signing certificates, you don't want your artifacts to have the same identity as old ones.

**Comment by penCsharpener** [comment]
Thanks, really appreciate that you've taken the time for this detailed answer!
