### ISSUE TITLE
[Test Failure] A clickable block show at the bottom of left panel in PM UI of Blend for VS

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8438]
## Details about Problem
NuGet version: NuGet Client Dev\5.3.0.6154
VS Version: Master\29208.39
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps
1. Launch Blend for VS and create a project: C# Blank App (Universal Windows).
2. Open PM UI of this project and click go to “Browse” tab.
3. Type some string (e.g. Blend) in the search box.
4. Hover on the bottom of the left panel.
## Expected
There is no clickable block show at the bottom of the left panel in PM UI.
## Actual
A clickable block show at the bottom of the left panel in PM UI as below screenshot.
![BlockShow](https://user-images.githubusercontent.com/20632625/62773499-e176c080-bad4-11e9-9d28-7ebfa158f0e1.png)
## Note
1. It just repro in Blend, doesn’t repro in VS.
2. Clicking the block will show next package in the list.
3. It is not a regression since it did repro on D15.9 28307.158 (NuGet 4.9.3.5777).

Update a video as below.
![Blend](https://user-images.githubusercontent.com/20632625/62919396-1a64ad00-bdd5-11e9-884e-206b96b55c4d.gif)

**Comment by nkolev92** [comment]
@dominoFire @rrelyea 

Is this a dup of the phantom package in the list issue?

Can it be closed?

**Comment by dominoFire** [comment]
@v-luzh I tried to repro the issue by following your instructions in the latest preview but no success.

According to Accessibility Insights, there's no phantom element at the end of the list.

![image](https://user-images.githubusercontent.com/1192347/81002080-88d31a80-8dfd-11ea-8235-e16f7a4e8b58.png)

I will close the issue for now, since it should be fixed by https://github.com/NuGet/NuGet.Client/pull/3254
