### ISSUE TITLE
Distribute the NuGet CLI as a .NET Core Global Tool

### ISSUE THREAD

**Issue by adamralph** [NuGet/Home#8459]
I.e. so that it can be installed using `dotnet tool install`.

A continuous source of pain is the mismatch between `dotnet` and `nuget.exe`. The former does not support all the operations of the latter, and often lags behind when new features are released. Some of the problems described in https://github.com/dotnet/coreclr/issues/26175 also apply with regard to issues and repos. Often, I find it near to impossible find out which version of the SDK is going to contain a given change to the NuGet client.

While it possible to use nuget.exe instead, bootstrapping this from, for example, a build script is relatively painful in that it requires a non-trivial amount of boilerplate code. Whereas it's trivial to bootstrap a .NET Core Global Tool (`dotnet tool install --tool-path ...`).

If the NuGet CLI was distributed as a .NET Core Global Tool, that would probably solve most of these issues. We could choose to ignore any NuGet commands in the SDK and use the .NET Core Global Tool instead. We could follow issues in the NuGet repo in isolation, and pick up the new versions of the .NET Core Global Tool when we need to.

**Comment by nkolev92** [comment]
Thanks for filling this issue. 

Please refer to https://github.com/NuGet/Home/issues/8263#issuecomment-506024683. 
At this point, we have no plans of doing this. 

Note that as of now, the feature is .NET Core Global Tools. No .NET Framework tools are supported.
 
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

**Comment by adamralph** [comment]
@nkolev92 .NET Core Global Tools is the feature I am referring to.

Can you please offer an explanation of _why_ you are not planning on doing this? The comment you link to does not offer any explanation either.

**Comment by nkolev92** [comment]
Our current approach is to try to deliver true cross platform functionality through the dotnet CLI. 

What are the features that you are missing in dotnet.exe that you'd like to see ported from nuget.exe? We'd like to make sure we are tracking all asks. 

Is the main pain point easier acquisition of NuGet.exe or feature parity?

**Comment by adamralph** [comment]
@nkolev92 the idea sprang from https://github.com/dotnet/coreclr/issues/26175. As I [mentioned there](https://github.com/dotnet/coreclr/issues/26175#issuecomment-521408746) (note how many upvotes that comment has) I feel the same pain points due to the shipping required from NuGet to the .NET CLI as mentioned in the description of that issue.

Whenever I am following issues in the NuGet repo, it's common that no-one can give me a definitive answer to which version of the .NET CLI a given change will be available in. And in other cases, such as https://github.com/NuGet/Home/issues/8100, the work took a while to be done in NuGet, and there is another round of waiting while the feature makes it into the .NET CLI.

If the NuGet CLI were distributed as a .NET Core Global Tool, we wouldn't have the extra wait to get features supported by the .NET CLI, and we'd also be able to much easier track when features will become available. And when those features are available, in a NuGet stable release, all we have to do is update the .NET Core Global Tool locally.

> feature parity

Yes, that's part of it. Or at least removing the delay between changes being released in NuGet and then getting them supported in the .NET CLI. But as I mention above, the problem of issues/PR's spanning repos, uncertainty as to versions, and the confusion caused for consumers is still problematic.

> easier acquisition of NuGet.exe

That's also part of it, but also cross-platform capability, because NuGet.exe is Windows only (or potentially via Mono, but that is a can of worms I would like to avoid).

**Comment by adamralph** [comment]
@nkolev92 here's another example: https://github.com/NuGet/Home/issues/8154#issuecomment-507449455 - if the NuGet CLI were distributed as a .NET Core Global Tool then I could just install version 5.2 and be done with it.

**Comment by nkolev92** [comment]
Thanks for elaborating on this @adamralph. 

> Whenever I am following issues in the NuGet repo, it's common that no-one can give me a definitive answer to which version of the .NET CLI a given change will be available in. 

I believe we've done a better job at that in recent releases. 
The root of the confusion is that NuGet ships at 2 different cadences with Visual Studio and the .NET Core toolset, and our version is closely aligned with Visual Studio instead of .NET Core as most of the other components that flow into both products do. 
NuGet has a significant amount of functionality only applicable in VS, while *most* other components don't have such differences. 
With that in mind, we can still do better with previews. The caveat is that it's difficult for even us to know at the time we make the change at NuGet side. The changes need to flow in VS/CLI.

> And in other cases, such as #8100, the work took a while to be done in NuGet, and there is another round of waiting while the feature makes it into the .NET CLI.

In retrospect personally I think we can say that we should've shipped the changes in both products simultaneously. 

> If the NuGet CLI were distributed as a .NET Core Global Tool, we wouldn't have the extra wait to get features supported by the .NET CLI, and we'd also be able to much easier track when features will become available. And when those features are available, in a NuGet stable release, all we have to do is update the .NET Core Global Tool locally.

This creates a servicing problem for NuGet. It creates an untested matrix. The NuGet functionality in the SDK are tightly coupled, and the SDK depends on certain a behavior from the NuGet tooling it carries. Having this 1-1 relationship helps us improve the quality of the product we ship.

> Yes, that's part of it. Or at least removing the delay between changes being released in NuGet and then getting them supported in the .NET CLI. But as I mention above, the problem of issues/PR's spanning repos, uncertainty as to versions, and the confusion caused for consumers is still problematic.

I think the learning from #8100 is that we shouldn't ship independent unless there's a technical limitation (see cross platform signing), so we don't add to the confusion. 
As far as versioning goes, I'll refer to what I wrote above, as if we change the versioning, it'll introduce confusions on the Visual Studio side. 
I'm not qualified to comment to the multiple repo as it goes beyond NuGet itself.

Note that all of our discussion aside, the NET Core global tools feature does not support .NET Framework tools, so it's not technically possible even if NuGet agreed to do it. 

Hope this clarifies things, a bit. 

A follow up question from me.

Feature lag aside, anything that nuget.exe supports that you feel lacking in the dotnet.exe world? 

fyi @rrelyea @anangaur @karann-msft

**Comment by adamralph** [comment]
@nkolev92 perhaps I can I simplify what I'm proposing slightly:

Every time you build and release NuGet.exe, build and release a NET Core global tool at the same time, with the same version number. Effectively the same code as NuGet.exe built against an appropriate version of `netcoreapp`, with `<PackAsTool>true</PackAsTool>` in its csproj. I know I'm simplifying massively, but is there any technical blocker that prevents the code that produces NuGet.exe being compiled against a version of `netcoreapp`?

**Comment by nkolev92** [comment]
> there is any technical blocker that prevents the code that produces NuGet.exe being compiled against a version of netcoreapp

Yes, there are functionalities that do not apply cross platform (msbuild discovery, extensibility), and others that there are no appropriate .NET Core apis for yet(prior to 3.0) such as encryption/signing. 

Ideally we want customers to use dotnet.exe cross platform.

**Comment by adamralph** [comment]
@nkolev92 OK, thanks. Then I guess this proposal isn't feasible.
