### ISSUE TITLE
NU1107: Version Conflict on mix framework project

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#8464]
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI
NuGet version (x.x.x.xxx): 5.2.0
dotnet.exe --version (if appropriate): N/A
VS version (if appropriate): VS 2019 Enterprise 16.2.2
OS version (i.e. win10 v1607 (14393.321)): Windows 10 Pro Build 1809
Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem
I’m in the process of converting our internal libraries into .NET Standard 2.  As a result, I have packages that are multi-targeting .Net 4.7.2 and .Net Standard 2.0.  At the same time, I’m still developing new applications and updating older applications.

In a new application (Windows service) that targets 4.7.2 there is a conflict pulling in packages.
Here is the actual error message:

> NU1107: Version conflict detected for RabbitMQ.Client. Install/reference RabbitMQ.Client 5.1.0 directly to project MprProductSync to resolve this issue. 
>  MprProductSync -> ScribeClientAPI.MSLogging.Legacy 2019.8.13.6 -> ScribeClientAPI.Legacy 2019.8.13.6 -> Messaging.RabbitMq 2019.8.13.57 -> RabbitMQ.Client (>= 5.1.0) 
>  MprProductSync -> RENAPI.Standard 2019.8.16.2 -> UtilsLibrary 2019.8.15.6 -> RabbitMQ.Client (= 2.5.1).
> NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Below is a list of what frameworks each one of the targets/packages in the above error are using:
MprProductSync :                                  4.7.2
ScribeClientAPI.MSLogging.Legacy:      Standard 2
ScribeClientAPI.Legacy:                         Standard 2
Messaging.,RabbitMQ:                          Standard 2
RabbitMQ.Client:                                   4.5.1/Standard 1.5/Standard 2
RENAPI.Standard:                                  Standard 2
UtilsLibrary:                                           4.7.2/Standard 2
RabbitMQ.Client:                                  4.5.1/Standard 1.5/Standard 2

I understand that NuGet will attempt to match a project targeting 4.7.2 with a library built with 4.7.2. 

My expectation is that if a .NET Standard package was determined to be the best match, that all  descendant packages also resolve to .NET Standard.

For example, RENAPI.Standard is a Standard 2 package.  It has a dependency on UtilsLibrary which also has a Standard 2 version, which would use the RabbitMQ.Client that is also compiled against .NET Standard. Both the UtilsLibrary and RabbitMQ.Client are multi-targeted packages.

Instead it seems that during the package resolution the full framework version of UtilsLibrary is being used, which results in the specific version locked RabbitMQ.Client is being used.

Having to always package the full framework and standard versions separately will lead to other problems.  (1) duplicate packages with just the name and framework being different, (2) unable to seamlessly update existing applications without changing the package name.

This will just make it harder to migrate from the full framework to .NET Core/Standard.

### Verbose Logs
Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
See attached msbuild.log
[msbuild.log](https://github.com/NuGet/Home/files/3510441/msbuild.log)

**Build Environment:**
Windows 10 Pro Build 1809
Visual Studio 2019 Enterprise 16.2.2
.NET Framework 4.7.2 and 4.8

**Also Installed, but not used for this build**
Visual Studio 2019 Enterprise Preview 16.3.0 Preview 2
.NET Core 2.2.401 and 3.0.100-preview8-013656

Thanks
-marc

**Comment by mhsimkin** [comment]
It seems this got overlooked.

Gentleman, any comment?

Thanks

**Comment by rrelyea** [comment]
You filed it on a friday...and we didn't get to it on monday. We hope to look at it today.

**Comment by zivkan** [comment]
I don't beleive this is related to multi-targeting or netstandard.

Messaging.RabbitMq 2019.8.13.57 has a dependency on RabbitMQ.Client (>= 5.1.0)
UtilsLibrary 2019.8.15.6 has a dependency on RabbitMQ.Client (= 2.5.1).

Notice the first one uses `>=`, whereas the second uses `=`. It's impossible for a version to be both greater than equal to 5.1.0 while also exactly equal to 2.5.1.

**Comment by mhsimkin** [comment]
Understood.

However, the package that contained UtilsLibrary has a .NET 472 and .NET Standard 2 versions.  The .NET 472 version was locked to Rabbit version 2.5.1.  The .NET Standard version allowed any version of Rabbit to be referenced.

Here is a screen shot from our internal NuGet server:
![image](https://user-images.githubusercontent.com/1248166/63705860-0c168800-c7fc-11e9-8710-586cc9a4a8c7.png)

As you can see, Rabbit is only referenced when the .NET 472 version is loaded. The Standard version has no references to Rabbit.  The Backbone.Abstractions references the 5.1.0 version of Rabbit.

![image](https://user-images.githubusercontent.com/1248166/63706029-74fe0000-c7fc-11e9-8215-c68e1ea0cb9b.png)

Therefore, the only way that Rabbit is being pulled in with a locked version is because NuGet resolved a child package to 472 instead of Standard.

If I need to upload all the dependencies of all the packages involved, just let me know.

-marc

**Comment by zivkan** [comment]
Perhaps then this issue is a duplicate of #7416, which is requesting the ability to choose which TFM is selected when the project is compatible with multiple TFMs in the package.

In your case, the project using the package is net472, so NuGet will choose the net472 assets and dependencies from the package, not the netstandard2.0. TFM selection is done per package. Even if a package is pulled in transitively, it will not use the same TFM as the "parent" package, the TFM selection is independent.

**Comment by mhsimkin** [comment]
Ok. Thank you for explaining. I've read the issue you referenced. I would say it is similar. 

I look at it this way, if corporate development is going to migrate from the the full framework to Standard in order to start using Core having to maintain two sets of packages for all the internal libraries is a non-starter.  It probably will not happen.

Then when all the libraries have been converted to Standard, go back and rename all the packages to remove the TFM indicator.  This is just a nightmare.

In my case, removing the .Standard on all my package names.

I feel the package selection process should only work at the first level and not down the chain.  Once you are beyond the first level of packages, the TFM selection should be based upon the immediate parent, not the root.

**Comment by zivkan** [comment]
I have several comments, largely due to not understanding how you're approaching the migration to .NET Standard.

Firstly, I find it unusual that `UtilsLibrary` has very different net472 dependencies to netstandard2.0 dependencies. This makes it appear that the two assets come from different codebases, rather than being the same code compiled targeting different TFMs. If this was done as part of a "rewrite" to migrate to .NET Standard, I would normally say this is the problem that Semantic Versioning solves. Make the incompatible rewrite a new major version, and keep "legacy" projects using the previous major version. Using source control branching, you can maintain two major versions of your package until all your projects using the package can migrate to the new code. However, since your version numbers are dates, this option is less feasible.

I'm not sure if it will help you, but the [.NET Portability Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) can help determine which APIs your project uses that are not compatible with all the TFMs that you care about. This can help to target where your code needs `#if` blocks to use different APIs in different TFMs, but otherwise be the same codebase and work the same way.

Secondly, I agree that having separate packages is not ideal. But this is why packages can multi-target multiple TFMs.

Finally, regarding your comment about transitive packages doing asset selection using the TFM chosen from the parent, this can't work when the same package is pulled in multiple times. Imagine a package A with net45 and ns2.0 assemblies, package B is net45 and depends on package A, and package C is ns2.0, also depending on A. My project targeting net472 references packages B and C. Which A assets should be used?  This is just the first example I could think of. Your suggestion is a good one and feels ideal in the simple cases, but when it gets down to the details of different scenarios, it's problematic. Hence independent asset selection provides a more reliable and understandable approach.

**Comment by nguyentuananh921** [comment]
I just create a new MVC projet, add Identity and I got the same erro


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.5.0 directly to project Presentation.MVC to resolve this issue. 
 Presentation.MVC -> Microsoft.EntityFrameworkCore.Tools 8.0.0-preview.7.23375.4 -> Microsoft.EntityFrameworkCore.Design 8.0.0-preview.7.23375.4 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0) 
 Presentation.MVC -> Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.0-preview.6.23360.4 -> Microsoft.DotNet.Scaffolding.Shared 8.0.0-preview.6.23360.4 -> Microsoft.CodeAnalysis.CSharp.Features 4.4.0 -> Microsoft.CodeAnalysis.Common (= 4.4.0).	Presentation.MVC	E:\15. Code Learning\Learning\Presentation.MVC\Presentation.MVC.csproj	1	

.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  7.0.305 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
