### ISSUE TITLE
Encoding of output console need to modified to support unicode better

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#848]
There is characters shown incorrectly, such as the one before "Dependency Behavior"

![capture](https://cloud.githubusercontent.com/assets/1087852/8343907/921b1138-1a8f-11e5-83b8-a670d4818afd.PNG)

**Comment by yishaigalatzer** [comment]
@danliu is this a regression from 2.8.6?

**Comment by feiling** [comment]
Here's the problem: the resource string in Chinese is "正在尝试解析程序包“{0}”的依赖项，DependencyBehavior 为“{1}”". Note that the comma in the string is the Unicode Character 'FULLWIDTH COMMA' (U+FF0C), not the normal comma (U+002C). If you copy and paste the string into another editor you can see that there is no problem with the string. It's a pure display problem: for some reason, the output window can't display this character correctly. The LOC team should fix the string to use comma instead.

**Comment by feiling** [comment]
Further investigation: the problem is the FULL WIDTH COMMA character is not in (latin) fonts. That's why the question mark is shown. However, if you select a chinese font, e.g. NSimSun, then the display will be correct, e.g. 

![untitled](https://cloud.githubusercontent.com/assets/2679220/11381908/c46825b2-92b3-11e5-9a8e-ab919ce1d7d5.png)

Again, the fix is to avoid using such characters.

**Comment by yishaigalatzer** [comment]
@zhili1208 can you please work with the Loc team on this?

**Comment by zhili1208** [comment]
verified with latest bits, it doesn't repro any more.
