### ISSUE TITLE
Package references should include source information for non-default sources

### ISSUE THREAD

**Issue by orcun** [NuGet/Home#8525]
I had this issue dotnet/cli#12289 and it looks like the problem is not limited to dotnet tools.

In short, when adding a package reference with custom source, package reference should also contain the source information.

**Comment by nkolev92** [comment]
Thank you for this feedback. 

We believe that the package identifier should remain the package id and version.
If you want additional protection for this, the lock files ensure repeatability by including the sha of the package in question.

**Comment by orcun** [comment]
Sorry but hash is not relevant here. When adding a package, I can specify a custom source. That information is lost for whoever want to restore or update.

**Comment by orcun** [comment]
Perhaps you confused source by a commit since issue link has been lost due to project migration.
Please see the discussion at dotnet/sdk#10439
I would appreciate if you can reopen this issue.

**Comment by zivkan** [comment]
It's not clear to me what the benefit of this feature request would be compared to adding the source to a `nuget.config` so that the source is available to install any package in the project/solution.

I think it adds unnecessary complexity from a customer point of view. As a developer, if I see a `PackageReference` with a custom source, does that mean the package can only come from that source, or is it in addition to sources defined in `nuget.config`? If the package has dependencies, do the dependencies use the same sources as the package directly referenced, or just the project's "normal" sources?  If the package with the custom source has a dependency that is also a dependency of packages that do not use that custom source, is the custom source allowed to be used to download the dependency if a version was selected that did not originate from the package with the custom source?

For this feature request to progress, I think it needs more justification. In particular, why the workaround of adding the source to a `nuget.config` is not sufficient. What scenarios does it enable that is not possible without this feature?

**Comment by orcun** [comment]
From my point of view as a customer, how do I know which source a package should be downloaded from? What happens if a package is gone, where should I look for? What happens there is a naming conflict? Is `packageSources` a priority list? What happens when I have conflicting priorities? 

Again, from my point of view, keeping the source of a package is neither complex, nor unnecessary. If a package reference has a custom source specified, that should be used. If the package has dependencies, there is no need for complicated either, question is again "Do they specify a custom source?" Custom source is used if they have a custom source specified.

Consider this, what if instead of specifying a package name like:

    PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3"

we always had to write it something like this:

    PackageReference Include="nuget.org/packages/Microsoft.EntityFrameworkCore/3.1.3"

How inconvenient would that have been? At that point, let's say people are asking whether they can omit nuget.org. Would you completely get rid of being able to specify it?

Can we also take a look at: [npm install](https://docs.npmjs.com/cli/install)
I know that npm does much more than what nuget does but, does package.json store only the package name and version? Am I missing something completely obvious?
