### ISSUE TITLE
Add deprecation information by default on the installed tab

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#8541]
Feature: Deprecation

The idea of the feature on VS was to show the deprecation info as warning ⚠️ on the INSTALLED tab. Clicking on this tab leads to the packages listed and are deprecated using the warning ⚠️ icon on package’s installed version. Clicking on this reveals the warning ⚠️ icon and deprecation info on the details pane. Essentially the warning ⚠️ icons leads to the issue details.

This doesn’t happen today because the installed tab shows the package details of the latest version by default and not if the one that’s installed.

Proposed fix, reviewed by UX:
* There is no need to show both the installed  version and the latest version on the installed tab. We can show just the one installed:

Version: \<Installed version in the drop down> UnistallButton

Will update the proposed UX soon.

**Comment by anangaur** [comment]
Default screen

![image](https://user-images.githubusercontent.com/14800916/64212858-9c3d7880-ce5f-11e9-8541-6093770c28a7.png)

If a version not equal to the installed version, then the following:
![image](https://user-images.githubusercontent.com/14800916/64213032-4f0dd680-ce60-11e9-9b28-6ff8decd6102.png)

**Comment by scottbommarito** [comment]
Discussed offline with @anangaur and @rrelyea. The UI proposed above is a consideration for 5.4 but too complex and risky at this point for 5.3.

To mitigate this issue in 5.3, we would like to
- To the dropdown list of versions on the right-side pane, add a warning icon or "(deprecated)" text to indicate which versions are deprecated.
- Make it so that clicking on a version in the list on the left defaults to show the metadata of the installed version instead of the latest version.

**Comment by scottbommarito** [comment]
Reopening because @anangaur believes the fix is insufficient and, although the "(deprecated)" text helps, it doesn't mitigate the UI confusion.
