### ISSUE TITLE
cannot install xamarin.googleplayservice

### ISSUE THREAD

**Issue by 0xpuffy** [NuGet/Home#8548]
I tried to install Xamarin.GooglePlayServices.Base. 
But these error appears.

Error		Package restore failed. Rolling back package changes for 'PushNotification'.				
Error	NU1202	Package Xamarin.GooglePlayServices.Base 71.1610.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.GooglePlayServices.Base 71.1610.0 supports: monoandroid90 (MonoAndroid,Version=v9.0)	PushNotification	F:\Task\Android\Xamarin\PushNotification\PushNotification\PushNotification\PushNotification.csproj	1	

Please help me.

**Comment by heng-liu** [comment]
Hi, [NU1202 ](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202)is caused by the package Xamarin.GooglePlayServices.Base doesn't contain any assets compatible with the project(netstandard2.0). 
From [here](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), we can see that "An app or library can target a version of .NET Standard. .NET Standard versions represent standardized sets of APIs across all .NET implementations." However, the package Xamarin.GooglePlayServices.Base only targets monoandroid so it doesn't work for .netcore nor.netframework. You need to change the project's target framework to one that the package supports.
For example, I tried to create an Android App(Xamarin) project and an Android Wear APP(Xamarin) project,  and they both installed package Xamarin.GooglePlayServices.Base successfully.
