### ISSUE TITLE
[Test Failure][Deprecation] Deprecated info of the deprecated package “test10k” will show on PM UI right pane with 30 seconds’ delay and VS hanging

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8557]
## Details about Problem
NuGet version: NuGet Client Dev\5.3.0.6224
VS Version: D16.3\29305.141
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps 
1. Launch VS and create a project. [e.g. Console Application (.NET Core)]
2. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json.
3. Open PM UI of the project, select the above deprecated package source and search the deprecated package “test10k” in Browse tab.
4. Click the package on the left pane and look at the right pane.
## Expected
Deprecated info of the package should show immediately.
## Actual
Deprecated info of the deprecated package “test10k” will show on PM UI right pane with 30 seconds’ delay and VS hung when loading the deprecated info as below video.

![DeprecationInfoDelay](https://user-images.githubusercontent.com/20632625/64420367-b8e0e700-d0d1-11e9-8300-4292e537cdeb.gif)

**Comment by scottbommarito** [comment]
The package "test10k" has 10,000 versions (more than any actual packages on nuget.org), and the hang is likely associated with that.

Furthermore, the hang also appears to reproduce on 5.2, **without** the changes for deprecation, so I do not believe this is a regression, although whether or not the hang has been worsened in any way by the changes is unclear to me.

As a side note, there are only around 250 or so package IDs on nuget.org with over 1,000 versions, and I believe there are <5 packages with 5,000 versions. I investigated a package with 1,000 versions and didn't reproduce the hang. I don't believe that this bug is very critical.

**Comment by v-luzh** [comment]
Yes, that's not a regression and not a critical bug. That's the reason why we didn't file it before. Base on our disccusion, we think the issue should be fixed somehow (reduce hanging time or prohibit customer making large version like that) since customer may run into it, although the probability is not high.

**Comment by nkolev92** [comment]
Closing this as dup of https://github.com/NuGet/Home/issues/8478.
