### ISSUE TITLE
Signing Validation will now properly reject signatures with timestamps which have 2 values under the same OID

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8629]
As the API AddUnsignedAttribute on netcore3.0 will do merge by the Oid(https://github.com/dotnet/corefx/issues/25449), so the unsignedAttribute will have different formats for net472(NativeCms does it in a P/Invoking way) and netcore3.0 (use API AddUnsignedAttribute from Pkcs package), if we timestamp multiple times for both primary signature and counter signature.

For net472:
```
UnsignedAttributes
    AttributeSet
        oid
        values
            value0
    AttributeSet
        oid
        values
            value1
```
For netcore3.0
```
UnsignedAttributes
    AttributeSet
        oid
        values
            value0
            value1
```
But our [code ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/Signing/Signatures/Signature.cs#L390-L422)can only verify the first format as multiple timestamp. The second format will be treated as valid even if we set allowMultipleTimestamps=false

Here are my thoughts(discussed with @rrelyea) :
1. Change verify code to handle both formats as multiple timestamps.
2. Keep AddUnsignedAttribute for net472 not changed (unmerged format)
3. The two format should have the same results when verifying.
4. It seems we can only get multiple timestamps by using APIs, no way to make it by commandline(we only accept one timestamp in nuget sign command). So there should be no affects to signing part. Pls correct me if I'm wrong.

**Comment by heng-liu** [comment]
@dtivel Can you help review the thoughts? Thanks!

**Comment by krwq** [comment]
@heng-liu I believe `1` should be done regardless if `2` is done or not since the spec doesn't define what should exactly happen and both formats are allowed. Not sure what's the difference between `1` and `3`.

For `2` adding counter signatures (which is also an unsigned attribute) was and is still producing format 1 on both full framework and .NET Core (.NET Core for compat) while adding unsigned attributes explicitly through new API is doing second format and I don't believe there used to be API for that on full framework (unless it was exposed through different class which I'm not aware of).

**Comment by heng-liu** [comment]
@krwq Thanks for your comments!
