### ISSUE TITLE
Restore Nuget package in a publish way

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#8663]
from https://github.com/microsoft/msbuild/issues/4771

Is there any possibility to simply restore a package and all of its dependencies and put them together in one output like a publish build would do it?

My current workaround is to create a temporary project with a package reference to the given package and then perform a build on that temporary project.

Unfortunately I need to know the TargetFramework(s) of the package to create a matching temp project and I get additional output (dll) for the temp project, which I actually don't need. I would like to have a common solution that always works, no matter which package I want to restore (even if I don't know its supported target frameworks).

**Comment by kartheekp-ms** [comment]
@TFTomSun - Refer to [this](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli#install-a-package) article to install a package and its dependencies to a output 
folder. Refer to [this](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli#install-a-package) to know more about nuget feature availability across various tools and operating systems. Let us know more about your specific scenario so that we can assist better. For e.g
- What are you trying to accomplish after installing package and its dependencies to a folder?
- Package Reference or Packages Config style project

**Comment by TFTomSun** [comment]
I try to pack test projects and run the tests using dotnet vstest against their binaries. I could publish the test projects but and then pack the output, but that would mean that the packages always become very big, because of redundant dependencies. So what I would like to do is pack the test in a normal way, then later restore and publish it. To do that I currently new MSBuild. So what I do is create a temporary project, reference the test package and publish the temporary project. The result is one folder that contains the executable test.

If I use nuget install, it just restores all packages but doesn't put all the stuff together how the publish msbuild operation do.

**Comment by kartheekp-ms** [comment]
Unfortunately NuGet by design has no functionality similar to MSBuild publish. The work-around you are following right now seems correct. see [link](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution) to know more about how NuGet resolves package dependencies.
