### ISSUE TITLE
How to install Main NuGet and dependent NuGet with same FrameWork version.

### ISSUE THREAD

**Issue by KarthickR5** [NuGet/Home#8665]
When i install custom nuget package **packages.aspnet.mvc5** in aspnet application with targetFramework 4.6 , The Main package(packages.aspnet.mvc5) dll referred 4.5 Framework. But the dependency of main package **compression.base**(Independent Nuget) dll referred from 4.6 targetframework instead of 4.5 Framework. Due to his bindig redirect entry added in webconfig file. Example,
```
        **<dependentAssembly>
    <assemblyIdentity name="compression.base" publicKeyToken="7285hf33478get3a" 
    culture="neutral" />
     <bindingRedirect oldVersion="0.0.0.0-11.3450.0.14" newVersion="11.3460.0.14" />
    </dependentAssembly>**
```

How to resolve this issue, while insalling the NuGet?

We have tested by , shipping the dependent package(compression.base) dll with Main Package instead of using dependent package. While used like that, it refers all dll from 4.5 Framework. But when uninstall the nuget all dll removed from project. Due to this, when using another package with same dependent package(compression.base), it will removed from project while uninstall the package. So, this is not a correct way.

How to refer main package and dependent package with same framework version while installing the nuget?

**Comment by kartheekp-ms** [comment]
I agree with the comments provided for the same question in asp.net forum [here](https://forums.asp.net/t/2160523.aspx?How+to+install+Main+NuGet+and+dependent+NuGet+with+same+FrameWork+version+).

**Comment by kartheekp-ms** [comment]
By design, binding redirects command is run automatically when installing a package. For e.g. in your case consider main dll has a reference to 1.0 version of `compression.base` assembly and `compression.base` dependent package has 1.1 version of the same assembly in its `lib` folder. When the main package is consumed  NuGet will traverse through all the assemblies and their referred assemblies of main & dependent packages. During this process it detects that `compression.base` assembly referred by main dll has different version than the one fetched from the dependent package and hence a binding redirect will be added. Binding redirects will not be added for assemblies without a strong name.

**Comment by kartheekp-ms** [comment]
@KarthickR5 - Refer to this [doc](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#bindingredirects-section) to learn more about how to skip adding binding redirects when a package is installed
