### ISSUE TITLE
NuGet Output Window for VS Online Environments

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8673]
Refactor NuGet Client code that interacts with VS Output Window. There's a new mechanism that abstracts this functionality to support Live Share and cloud-hosted development environments.

**Comment by nkolev92** [comment]
Dev notes: 

There are a few nuances here, because not every scenario is equal. 
* explicit & implicit scenarios go to a different output window today. 
* in CPS based projects certain warnings are read from the assets file and not written by NuGet, so we might need partner work to complete the experience. 
* The status bar is also a consideration, we might need to use a different API to ensure that all output gets forwarded. 

Might need to split this issue in a few smaller issues.

**Comment by nkolev92** [comment]
The on build scenario is blocked on a service: https://github.com/NuGet/NuGet.Client/tree/dev-nkolev92-vsoBuildOutput for some of the work.
I will convert this issue into an epic when appropriate.

**Comment by nkolev92** [comment]
Moving #9270 out of this epic. 

This epic is the one targeting build.
