### ISSUE TITLE
Fails to install any package

### ISSUE THREAD

**Issue by codermrrob** [NuGet/Home#8689]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.3.0.6251

dotnet.exe --version (if appropriate): .NET Core SDK (3.0.100)

VS version (if appropriate): 16.3.4

OS version (i.e. win10 v1607 (14393.321)): win 10 1903 build 18362.418

Worked before? If so, with which NuGet version:
Same version worked before. Just stopped working.

## Detailed repro steps so we can see the same problem

1. Create a new .Net Core class library, no dependencies, one empty class, also same for a new Console app both created in normal New Project way.

2. From Package Manager console or 'Manage Packages' UI - it is the same result
`install-package autofac`

(the package is unimportant same for all packages)

```
PM> install-package autofac
install-package : The operation failed as details for project ClassLibrary1 could not be loaded.
At line:1 char:1
+ install-package autofac
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 Time Elapsed: 00:00:00.5614007
```
...

## Other suggested things

This is happening for me with both newly created class libraries, console applications and also adding new projects into a solution.

Projects created with the new Worker Service templates are not affected and nuget is working as normal within those projects.

Work around:

1) After the error unload/reload the project or restart VS.
2) Open the 'Manage Packages for Solution' UI
3) Change the package source (it can be changed back to the original, the act of changing seems important not what it is set to; I changed from 'All' to 'nuget.org' and back to 'All'. Without doing this the next step would fail.
4) Browse or search package to install and install it successfully with the UI. Again, without this the next step would fail.
5) Now it is once again possible to install-packages normally with the console as well

This is not a global solution and I have to do for each new project I create (except worker services).

Doing a VS Repair from the installer had no effect.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

There is nothing useful I can see in the log generated from devenv /Log \VSLog.xml but it is attached just in case I missed something. It is the log from starting VS, creating the project and attempting to `install-package autofac` resulting in the above error.

[vslog3.zip](https://github.com/NuGet/Home/files/3723624/vslog3.zip)

And the sample project attached which created this log

[ConsoleApp5.zip](https://github.com/NuGet/Home/files/3723628/ConsoleApp5.zip)

**Comment by codermrrob** [comment]
I realize that the issue doesn't happen with background worker projects because the new template for this installs nuget packages as part of the initial setup.

**Comment by zivkan** [comment]
@codermrrob thanks for providing the activity log, that would have been the first thing I was going to suggest to check.

A little background info: for SDK style projects, NuGet gets information about target frameworks and package references from the project system a mechanism called project nomination. When it gets a nomination, it adds the project to an in-memory cache. When Nuget is instructed to restore (either as a pre-build action, or when right clicking the solution and choosing restore), NuGet checks Solution Manager's project list, and for each project that is SDK style, checks the in-memory cache for details about that project. The error message you see if when NuGet finds an SDK style project that has not been nominated.


You can get nomination information from the project system by setting the PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED environment varibable to 1. For example, run "Developer powershell for VS 2019" and run
```
$env:PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED = 1
devenv
```

The output window will have an additional "project" item in the "show output from" dropdown, and you can check if the new projects are nominated. This will help us narrow where the problem is.

**Comment by codermrrob** [comment]
Here's the Project Output.

This was taken from a new project, empty, except for scaffolding from the ConsoleApp template.

As before attempting to install-package fails, but it seems a bit of a red-herring in my previous description. Changing the Package Source is not required.

The 2nd Project Output below (project2.output.txt) is from a 2nd clean ConsoleApp that I created then installed autofac from Package Manager. That worked and I could again use the Package Manager Console to install. But I must use the Package Manager UI first. The project2.output.txt is taken from the 2nd load of that project (after installing autofac, quit VS, start VS and load project again).

Its a non-urgent bug, because the work around always is working and its not so inconvenient!

[project.output.txt](https://github.com/NuGet/Home/files/3754109/project.output.txt)

[project2.output.txt](https://github.com/NuGet/Home/files/3754135/project2.output.txt)

**Comment by nkolev92** [comment]
Hey @codermrrob 

Given that this is likely an issue with a different component in VS, would you mind opening an issue via the Report Feedback flow in Visual Studio. 

Issues created through that will contain more information for the team to investigate. 

Thank you.
