### ISSUE TITLE
a nuget.config from an upper directory affected the build

### ISSUE THREAD

**Issue by ilatypov** [NuGet/Home#8708]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 4.x

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): 

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. I had an older nuget.config in the upper directory and dotnet restore used it in addition to one in %appdata%\nuget\nuget.config. I did not like that.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Hey @ilatypov 

This is by design. The NuGet.config are hierarchical. 
If you want to exclude the impact from the upper level config you can add clear tags in the respective section. 

We do that in our own repo. See https://github.com/NuGet/NuGet.Client/blob/dev/NuGet.Config and https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources
