### ISSUE TITLE
Installing `Reinforced.Typings` prompts to install system packages, can't seem to stop it

### ISSUE THREAD

**Issue by Daniel15** [NuGet/Home#8734]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Visual Studio UI

NuGet version (x.x.x.xxx):
N/A

dotnet.exe --version (if appropriate):
3.0.100

VS version (if appropriate):
16.3.0

OS version (i.e. win10 v1607 (14393.321)):
Windows 10 v1903 (build 18362.10024)

Worked before? If so, with which NuGet version:
N/A

## Detailed repro steps so we can see the same problem
I'm trying to figure out an issue with the `Reinforced.Typings` project where it tries to install a bunch of system packages for some reason (eg. System.IO 4.3.0, System.IO.Filesystem 4.3.0, etc). See https://github.com/reinforced/Reinforced.Typings/issues/140

For test purposes, I recompiled a version of the package with all dependencies removed from the nuspec, which in theory should help: https://d.ls/dotnet/bugs/Reinforced.Typings.1.5.5.nupkg

I double-checked in NuGet Package Explorer that my modified package has no dependencies:
![](https://d.sb/2019/10/NuGet_Package_Explorer_-_Reinforced.Typings_1.5.5_22-23.26.08.png)

However, when I install the modified package, it still tries to install all those dependencies:
![](https://d.sb/2019/10/WebApplicationReactTest_-_Microsoft_Visual_Studio_22-23.21.50.png)

Why is NuGet doing that? Where are these dependencies coming from? Seems like it's pulling in some .NET Core 2.0 deps even though I'm installing it into a .NET Core 3.0 app.

**Comment by zkat** [comment]
Oh, hey @Daniel15! Nice to see a familiar face around :). I feel like I have an idea what's going on here but I'm going to ask my team, who, as you can imagine, are more familiar with the ins and outs of net core stuff.

**Comment by zkat** [comment]
Okay so! I think I understand now, thanks to @nkolev92 and @zivkan -- the problem is that `Microsoft.NETCore.App` should never have been referenced in that nuspec, and instead used something like `Microsoft.NETStandard.Library`, because platform packages are handled differently by nuget (and dotnet). That said, these assemblies may still be needed at compile time even though they're part of the runtime, and the special handling to hide these even further was added in netcore3. I... think that captures it. I don't fully grok this yet, but it sounds like removing the particular dependency from the nuspec should help.

Beyond that, you might be running into name conflict issues with your no-dependency test, because of how nuget handles its global packages folder.

**Comment by Daniel15** [comment]
Thanks for the reply @zkat! That makes sense.

> Nice to see a familiar face around :)

Same to you! Most of the coding I do in my free time is in C# so you may occasionally see me around in the issue trackers or on pull requests for NuGet, .NET Core, etc. :)
