### ISSUE TITLE
run powershell script after package installed

### ISSUE THREAD

**Issue by ghost1372** [NuGet/Home#8824]
hi i want to execute powershell script for modify a file. 
I noticed that the script runs during installation And so I can't edit the file because it's not there yet and it's being built by Visual Studio
What should i do?
My script is on this path:
**tools\install.ps1**

**Comment by nkolev92** [comment]
To perform actions at build time on build assets, you should use build targets rather than install scripts. 
The build targets will run on every build. 
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#include-msbuild-props-and-targets-in-a-package

Note that powershell install/uninstall scripts are deprecated for PackageReference based projects, so using targets means your package will work correctly with both package management formats.

**Comment by ghost1372** [comment]
@nkolev92  Thank you, can you give me a practical example?

**Comment by nkolev92** [comment]
For example a good package is: https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/

As far as authoring the target, that really depends on your scenario. 
Refer to https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2019. 
Note that you can also write tasks: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-task-reference?view=vs-2019

**Comment by Adinihal** [comment]
Hi @nkolev92  , Actually in my .net standard application when I install a nuget package my PackageReference `<PackageReference Include="sip-si" Version="4.0.10" />` gets updated but the `Target`   copy is not getting updated i have t o do it manually  
`<Target Name="CopyReferenceDll" AfterTargets="Build">`
	`<Copy SourceFiles="..\..\_Common\packages\sip-si.4.0.9\lib\netstandard2.0\Wrapper.dll" DestinationFolder="$(TargetDir)" />`
	`<Copy SourceFiles="..\..\_Common\packages\sip-si.4.0.9\lib\netstandard2.0\FWrapper.pdb" DestinationFolder="$(TargetDir)" />`
 ` </Target>`

could you please suggest me how can I update this target section automatically during installation of sip-si package ,I mean what are the changes i need to do it on nuspec file
