### ISSUE TITLE
Downgrading transitive PackageReferences

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#8833]
_From @jhudsoncedaron on Friday, November 15, 2019 7:52:06 PM_

We have a DLL that contains downgrade instructions, so despite being built in the project containing the latest version, it must inherently be loadable on the oldest version we ever shipped. In order to do so, we used PackageReference Update= to pin reference of dlls when building that version.

Unfortunately this doesn't really work for some reason we don't know. The Update= version force is ignored and the higher version in the dependent dll is used instead. This actually causes the dynamic load to fail whenever we need to update the packages. For some reason, despite the same artifact being present in the dll refrenced by PackageVersion, the dynamic load succeeds there (or we would have noticed the very first time we tried this).

Don't let netstandard2.0 fool you; we are building with the 3.0 toolchain and the executable (omitted from the sample) is linked against netcoreapp3.0. You can check the dependencies of DynamicLoaded.dll with ildasm. It should reference Demo.dll version 1.0.0 but it references Demo.dll version 2.0.0

The real If.dll is not an interface-only dll. It contains quite a bit of code for upgrade and downgrade, and the current version of If.dll used during upgrade can't function with the older version of Demo.dll.

This issue is newly discovered a few days ago, thankfully not by a customer.

[downgradedemo.zip](https://github.com/dotnet/sdk/files/3852941/downgradedemo.zip)

_Copied from original issue: dotnet/sdk#3918_

**Comment by rainersigwald** [comment]
_From @rainersigwald on Monday, November 18, 2019 6:12:42 PM_

Can you point to any docs or issues you used to develop your understanding of what `Update` does in this context? It seems we have something misleading, because it doesn't work the way you expect.

`Update` is an MSBuild language feature that will update items matching the pattern with the specified metadata.
From your example you have

```xml
<PackageReference Update="Demo" Version="1.0.0.0" allowedVersions="[1.0.0.0]" />
```

 It's not applying in this case because your project does not have any Demo items, for example

```xml
<PackageReference Include="Demo" Version="xxx" />
```

`DynamicLoaded.csproj` gets a reference to `Demo` from its `ProjectReference` to `..\If\If.csproj`. NuGet sees that and promotes it to a reference to `Demo` with a matching version in `DynamicLoaded`--but it's not a direct reference, and thus doesn't have an entry in `@(PackageReference)` to update.

I think this is a NuGet feature request; I'll move this issue to the NuGet bug tracker.

**Comment by zivkan** [comment]
@jhudsoncedaron Short version is that NuGet does not currently support transitive version pinning. It will be supported with the future [centrally managed package versions](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions) feature.

The workaround is to directly reference the package in the project, as this causes [NuGet's nearest-wins rule](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins) to select that version of the package. As you commented in the other issue, this causes a NU1605, but when you check the NU1605 docs, you'll see that NuGet considers this a warning, not an error. The reason it's an error is because [the SDK upgrades it to an error](https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L18-L19). I'm not sure why they do that, my guess is that it's related to all the system assemblies being packages in .NET Core 1.x and 2.x, and it causing problems when an app bring in old assemblies. Since .NET Core 3.0 introduced FrameworkReference, this problem should no longer be relevant and perhaps in the future the SDK team will stop elevating NU1605.

To work around the WarningAsError elevation, you can either set `<WarningAsError>;</WarningAsError>` in your project to stop elevating it, or use `NoWarn="NU1605"` either on the project, or on the package reference:  `<PackageReference Include="Demo" Version="1.0.0.0" NoWarn="NU1605" />`.

As Rainer explained, using `Update` instead of `Include` doesn't work because MSBuild hasn't seen the `Demo` item yet, so there's nothing to update. When MSBuild passes all the `PackageReference` items to NuGet, there's nothing about the `Demo` package, so NuGet has no way of knowing that a different version of the package is desired.

By the way, I'm not 100% sure, but I believe that the `allowedVersions` is a packages.config feature only. If you want an exact version with PackageReference, use the appropriate range syntax in the version attribute: `<PackageReference Include="Demo" Version="[1.0.0]" />`

**Comment by nkolev92** [comment]
> @jhudsoncedaron Short version is that NuGet does not currently support transitive version pinning. It will be supported with the future centrally managed package versions feature.

Adding an update for this, this might be something that actually errors, but follow that feature for the exact details.
