### ISSUE TITLE
Improve the VS2015 NuGet UI (applies to NuGet 3.0 - 3.1.1)

### ISSUE THREAD

**Issue by shawnwildermuth** [NuGet/Home#885]
I know that it’s too late to change anything fo r VS2015, but I’d love it if the team considered some of these UI experience problems for the future. I’m purposely not being prescriptive. As a dev, I could write a design for you but that’s not helpful. Here are the pain points I had:

The startup experience is confusing. It shows the installed packages. With small icons for installed and upgrade. These are small enough that I don’t know what they’re for. Also, including prerelease by default seems wrong (unless I’m in a ASPNET5 project which I’m not):

![image](https://cloud.githubusercontent.com/assets/568272/8503769/887647e2-2192-11e5-8920-aae268dd325b.png)

So I use the search and it searches NuGet as expected:
 
![image](https://cloud.githubusercontent.com/assets/568272/8503771/8e0aa3e2-2192-11e5-83c3-dfe5bcbbcf00.png)

But then how do I see my installed packages again?  Clearing search and selecting filter “Installed” isn’t ikntiutive at all.
 
![image](https://cloud.githubusercontent.com/assets/568272/8503773/96a09930-2192-11e5-81ed-4038b15bf1e3.png)

Ok, I’m ready to upgrade some packages. I filter by upgrade and make sure I clear the search. In the UI for the upgradable Are the options related to just this package or all packages? (It seems to stick but it’s not clear). If they are persistent, why not also include them in options so that they can be imported/exported?

![image](https://cloud.githubusercontent.com/assets/568272/8503779/9d76e48a-2192-11e5-815f-f5e8bb8cf411.png)
 
The behavior of loading the list menu on demand (even when I’m just viewing Installed packages) seems silly. I understand you’re paging to the server, but for managing installed or upgraded packages, it’s confusing.

Is there an option to upgrade all? If not, I have to drop down into command-line?

Thanks,
 
Shawn Wildermuth

I’m a Pluralsight Author – see my courses here:
http://shawnw.me/psauthor

**Comment by yishaigalatzer** [comment]
Can you explain in more details what you mean by

> The behavior of loading the list menu on demand (even when I’m just viewing Installed packages) seems silly. I understand you’re paging to the server, but for managing installed or upgraded packages, it’s confusing.

**Comment by csharpfritz** [comment]
Additional UI feedback from VS Feedback:

When looking at the list of packages at a solution level, due to the default 'all projects checked' configuration, it appears that the package is installed in all projects.  This is confusing to some users

**Comment by csharpfritz** [comment]
Additional feedback from many people on VS Feedback:

Upgrade All is missing

**Comment by csharpfritz** [comment]
Additional feedback from several on VS Feedback:

The Installed filter takes a long time to load and does not load everything even though the packages are installed and available locally

**Comment by csharpfritz** [comment]
Additional feedback from VS Feedback:

Developers would like to be able to select text from the package description

**Comment by csharpfritz** [comment]
Additional feedback from VS Feedback:

"Include Prerelease" checkbox is not sticky and developers would prefer it remember the last checked state

**Comment by csharpfritz** [comment]
Additional feedback from VS Feedback:

Uuninstalling a package that is marked as having an Update Available is confusing as there is no Uninstall button immediately available in the user interface

**Comment by csharpfritz** [comment]
Additional feedback from VS Feedback:

A change in network state disconnects the NuGet Package manager tools, rendering them unable to connect to any remote gallery service. Workaround is to close and re-open Visual Studio

**Comment by csharpfritz** [comment]
Additional feedback from VS Feedback:

Developers would like to be able to choose to search across all package sources

**Comment by csharpfritz** [comment]
NOTE:  This is a placeholder issue for user-interface discussion and will be processed once user interface work starts.

**Comment by csharpfritz** [comment]
There has been some chatter on Twitter about being able to control the sort order of the result list in Visual Studio.  An example mention of this:

https://twitter.com/GoodCoffeeCode/status/618443132867379200

**Comment by csharpfritz** [comment]
There is a need to display which NuGet sources come from which nuget.config file as the current display is confusing when managing sources.  It would be beneficial to be able to control which nuget.config file is updated from the feed sources display as well

+ @davidfowl @damianedwards

**Comment by csharpfritz** [comment]
Consideration for an item from the AspNet announcements repo:  it may be beneficial to allow configuration of the version update constraints from the user interface:  http://docs.nuget.org/Create/Versioning#constraining-upgrades-to-allowed-versions

**Comment by csharpfritz** [comment]
Forgot to include a link to  #728 with another developers experiences

**Comment by csharpfritz** [comment]
From vs-feedback: Users would like to have a clickable link to a package details page in the Visual Studio UI so that they can review change log and other package details.

**Comment by yishaigalatzer** [comment]
Support adding the same package version from one project to another. This was supported in V2, but is missing from V3. The scenario is useful for people managing multiple projects that want to use exact same versions without having to re-install them.

**Comment by lucamorelli** [comment]
install all, install multiple packages at the same time, more sort options are very needed.
Other infos to show: number of downloads, date at least of the latest package update.
I think that search for other fields as tags,authors are very useful and working with every filter: search by tags seems to work but just when All is selected.
Other thing I think may be very useful is to filter all binary packages that are compatible with .net core.
Last thing: I possible to show in a specific field the github commit associated to the package?

**Comment by yishaigalatzer** [comment]
Another piece of good feedback - https://github.com/NuGet/Home/issues/1020

**Comment by yishaigalatzer** [comment]
_From @NickCraver on August 6, 2015 3:58_ Copied relevant items from https://github.com/NuGet/Home/issues/1179

1. Uninstalling packages is bad. 2013 wouldn't let you install things that are a dependency, but it was much more usable in this manner. What happens in 2015? Errors. Errors are the first hint that the package is used and can't be installed. Nowhere in the UI are you prevented from clicking right to error town. To test this: Create a new ASP.Net MVC project (File -> New Project -> Web -> MVC), all defaults. Now try and remove Newtonsoft. Here's what that looks like to a user: ![http://i.stack.imgur.com/R2gbA.png](http://i.stack.imgur.com/R2gbA.png) That's just not very usable. 
Oh, and there was no preview window even though the box is checked, it just errors.

@NickCraver - Do you expect an earlier warning?

2. This is a continuation of number 3. Why not show the dependency chain in this much larger amount of space the UI now takes? Where in here was I supposed to know it was a dependency for anything? ![http://i.stack.imgur.com/v907a.png](http://i.stack.imgur.com/v907a.png)

3. Why is the description repeated twice? It's in both the list and the detail pane.

4. The large real-estate tradeoff we've taken isn't (in my opinion) used well. For example, let's compare the old vs. the new (note the working "Installed version"):
![http://i.stack.imgur.com/xK2I3.png](http://i.stack.imgur.com/xK2I3.png) ![http://i.stack.imgur.com/3jFKt.png](http://i.stack.imgur.com/3jFKt.png) Why not show a dependency graph in there instead of expanding the URLs? My point is simply: there are better uses of the space.

5. This one isn't 2015 but I'll throw it in: I can't count the number of times I've seen a dev add a custom package source only to end up with `Package source`/`http://packagesource` because they didn't click "Update" before "OK". Can we get a confirmation prompt or just have it save there? I mention this one because it's another sign that third-party feeds seem largely ignored...it's an area we've hit trouble with repeatedly.

There are more items I can't recall just now, but I wanted to at least some actionable bits here. Please take this as constructive feedback. We're not saying "this is worse" without reason...we just want it on par, then better. The UI is very important now. With the direction everything is going with larger and transient dependency trees more devs than ever will be using this interface.

**Comment by yishaigalatzer** [comment]
Feedback around the upgrade experience https://github.com/NuGet/Home/issues/1182

**Comment by csharpfritz** [comment]
From vs-feedback:  There is no indicator in the UI of whether a package supports the project type being worked on.  This results in installing a package that fails silently.

**Comment by yishaigalatzer** [comment]
@csharpfritz this is now a long list of small bugs, the main issue described in the issue was resolved. Can you please summarize the other features elsewhere and close this bug as completed

**Comment by yishaigalatzer** [comment]
The UI update for 3.3 is now done. We addressed most of the ideas mentioned here, and as we will start working on further update we will create a separate issue covering them.

@csharpfritz will add links to other issues already tracking sorting and other suggestions here.

**Comment by csharpfritz** [comment]
Installed Filter performance and Network connectivity tracked  on #1139

**Comment by csharpfritz** [comment]
Package Description Selection tracked on #1769

**Comment by csharpfritz** [comment]
Sort is tracked on #1739

**Comment by csharpfritz** [comment]
"All Package Sources" is tracked on #1770

**Comment by csharpfritz** [comment]
NuGet.config file settings management is tracked in #1771

**Comment by csharpfritz** [comment]
CLickable package details page link is tracked with #1772

**Comment by csharpfritz** [comment]
Repository sources "Update -> OK" Workflow tracked by #1773
