### ISSUE TITLE
Nuget package restore not working vs2019

### ISSUE THREAD

**Issue by shaipetel** [NuGet/Home#8852]
Building a project throws this error:

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Repos\***\***\\.nuget\NuGet.targets.

I checked and nuget package restore is enabled.

I closed and reopened visual studio, tried to build, opened nuget manager but it is not building and not restoring missing packages.

I followed this article:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting
Which suggests if the packages are not restored automatically to file an issue here.

Please advise.

using visual studio enterprise 2019 version 16.3.9
the project opens and works fine on a different computer with vs2017

**Comment by feilongsword** [comment]
I have the same trouble too. Do you or anyone else find a solution?

**Comment by shaipetel** [comment]
Yes, see my previous comment regarding editing the project file and removing the NuGet there.

**Comment by nkolev92** [comment]
The packages.config project management style by design hardcodes the references to packages inside the csproj file. 

This happens at install. This also means at uninstall time, NuGet needs to figure out which references it added at install time and remove them. 
This works fine for the most part, but it can be a problem if a package uses install/uninstall scripts. Then it's on the package author to help NuGet does the right things.

Note that in PackageReference we removed the concept of install/unistall scripts for this exact reason. 

> Update-Package -reinstall
in the Package Manager Console
removed all references in my project and re-added them one by one, but they all still seem to be missing (yellow triangle).

There's many ways this can go wrong.
Makes me think that some references to some earlier packages might not have been removed or they were potentially manually edited at which point we're going into unsupported scenarios. 

Would you be able to provide us a repro? 
Unfortunately without understanding exactly what the problem is, we won't be able to help much. 

Thanks.

**Comment by gojimmypi** [comment]
@nkolev92 and @shaipetel  I believe I am having this exact problem of a fetched package missing the DLL. I have a sample repo to demonstrate:

```
git clone https://github.com/gojimmypi/ulx3s-examples.git
cd ulx3s-examples\
git checkout SSD1331
```
In Visual Studio, navigate to `ulx3s-examples\nanoFramework\nanoFrameworkSSD1331_demo` and open the `nanoFrameworkSSD1331_demo.sln` solution in Visual Studio 2019. 

Note that I have the [nanoFramework extension](https://marketplace.visualstudio.com/items?itemName=nanoframework.nanoFramework-VS2019-Extension)  installed. Here's my version info: 

![image](https://user-images.githubusercontent.com/13059545/73381599-df6b0e80-427a-11ea-8d8a-f532c308f105.png)

![image](https://user-images.githubusercontent.com/13059545/73381644-f6a9fc00-427a-11ea-8e01-e3497f1b053f.png)


When initially creating this solution, adding NuGet packages via the Visual Studio interface worked fine. Note however, the NuGet packages are excluded from my repo, expecting that any clones will pull their own fresh binaries.

First, right-click on the solution and select `Restore NuGet Packages`. Nothing happens:
![image](https://user-images.githubusercontent.com/13059545/73381760-25c06d80-427b-11ea-9e38-ea7e9b9a95b5.png)

I assume this is due to the way I saved my files in GitHub, excluding the packages. I'd be interested in knowing if I should do something different.

So next, go to `Tools - NuGet Package Manager - Package Manager Console`, ensure the package source is set to `nuget.org` and type:

```
Install-Package nanoFramework.CoreLibrary -Version 1.6.0-preview.1
```
result:
```
PM> Install-Package nanoFramework.CoreLibrary -Version 1.6.0-preview.1
Package 'nanoFramework.CoreLibrary.1.6.0-preview.1' already exists in project 'nanoFrameworkSSD1331_demo'
Time Elapsed: 00:00:00.0511662
PM> 
```
(note the packages directory is still empty)

So instead, reinstall everything. This is where things get interesting:
```
Update-Package -Reinstall -IncludePrerelease
```
all packages appear to be successfully install, however the `packages\nanoFramework.CoreLibrary.1.6.0-preview.1` directory is missing the respective DLL, despite the fact that when initially adding it to a new project, it is there. Other libraries that were just freshly downloaded all have a DLL in the respective `lib` directory.

Note that if you go to the [nanoFramework.CoreLibrary 1.6.0-preview.1](https://www.nuget.org/packages/nanoFramework.CoreLibrary/1.6.0-preview.1) and manually download the zip file, the DLL *is* there.

edit: I see the same result in VS2017:

![image](https://user-images.githubusercontent.com/13059545/73388816-c4eb6200-4287-11ea-821f-77845200f1a3.png)

![image](https://user-images.githubusercontent.com/13059545/73388845-d59bd800-4287-11ea-9ee4-e1ae616a0ff1.png)

![image](https://user-images.githubusercontent.com/13059545/73388919-f6642d80-4287-11ea-829a-a2cc98820297.png)

The DLL is missing from the `lib` directory.

**Comment by marqdouj** [comment]
I believe I am having the same (similar) issue.
I've created a NuGet package that contains 2 .NET Framework 4.7.2 dlls in the files section. If I install the package to a new .NET Framework 4.7.2 class library and select packages.config the second dll is missing and won't install (it shows up with warning icon in the project references). If I change the project to packagereferences then both dlls install correctly.
Am I missing something here?

**Comment by marqdouj** [comment]
I did some more digging...
I moved the second dll to it's own nuget package - same results; the dll won't restore properly unless the project is using packagereference.
The only difference is that this dll is a WPF user control library.

Any ideas?

**Comment by nkolev92** [comment]
@gojimmypi 

The reference in your csproj has `<Private>true</Private>` and that's the override for copy local, so you are opting out of the copying. 

@marqdouj 

>  If I change the project to packagereferences then both dlls install correctly.
There are some differences in how packages.config and PackageReferences work.
Unfortunately I'm having trouble following the scenario without a repro.

**Comment by nkolev92** [comment]
At this point, we are deviating from the original issue. This issue is capturing a very broad topic and we haven't gotten more info from the OP so we can scope it.

As such I'll close this issue. We'd be happy to engage in a new issue if my suggestions above do not address your problem. 

Thanks

**Comment by Pedroma34** [comment]
The way I solved it: delete the entries in packages.config and reinstall your packages
