### ISSUE TITLE
Nuget package can be installed multiple times in different versions

### ISSUE THREAD

**Issue by StarWars999123** [NuGet/Home#8865]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI
VS version : 16.3.10

## Detailed repro steps so we can see the same problem

Use a .NET SDK project
- install at least one nuget package
- Lets assume we have incorrect resolved merge conflict: 
    - open the .NET SDK project with a text editor and
    - copy the Itemgroup with the PackageReferences directly behind the existing package reference item group. 
- Open the project again in visual studio. It builds, restores the files and throws no error

--> I would expect to see an error. Furthermore the GUI does not complain and is not able to resolve this issue by updating the packages.

### Sample Project
The .net sdk project at the end contains code like this: 
```
<ItemGroup>
    <PackageReference Include="Autofac">
      <Version>4.9.4</Version>
    </PackageReference>
</ItemGroup>
<ItemGroup>
    <PackageReference Include="Autofac">
      <Version>4.9.3</Version>
    </PackageReference>
</ItemGroup>
```

**Comment by donnie-msft** [comment]
What do you mean by the GUI not being able to resolve this issue? 
What error do you expect in this case?

What I'm seeing happen is whatever the last PackageReference Version is wins. As soon as you build, there is no conflict, but instead one DLL is put into my bin/debug folder.

The only thing I saw out of sync was when I changed the XML file, saved it, reloaded the project, PMUI still showed the "previous winner" version of the package until I Rebuilt. I'm not sure this is a problem, though, since building is required to actually output the different DLL.

**Comment by nkolev92** [comment]
Closing this per @donnie-msft's comment. 

We don't see a bug at this point. Feel free to file a new issue if you hit more problems.

**Comment by StarWars999123** [comment]
I would expect to see an warning or error message, like "Package is defined with multiple versions (4.9.3, 4.9.3). Please check your referenced projects" or something similar.

**Comment by nkolev92** [comment]
@StarWars999123 

Unfortunately that behavior goes beyond NuGet. 
MSBuild parses in a top to bottom, props first, items next approach. 
It's an MSBuild feature, and NuGet is not handling it in a special way. 

https://docs.microsoft.com/en-us/visualstudio/msbuild/comparing-properties-and-items?view=vs-2019#property-and-item-evaluation-order
