### ISSUE TITLE
Remove workaround of locking SDK version for building

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9029]
We now lock SDK version for building project, as sometimes issues in preview SDK block our work.
When we are ready to ship, we should use the SDK installed on CI machines instead of a specified one.

**Comment by kartheekp-ms** [comment]
Package signing branch has few new entries defined in [build/config.props](https://github.com/NuGet/NuGet.Client/blob/dev-feature-xplatVerification/build/config.props#L40-L49) to define `dotnet` cli version for building and running tests. In the dev branch it looks like we build the source code using the version installed on the CI agent and test using the version based on `CliBranchForTesting` parameter in [config.props](https://github.com/NuGet/NuGet.Client/blob/dev/build/config.props#L39-L40).

**Comment by kartheekp-ms** [comment]
@heng-liu  mentioned that , according to **[doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml),** `Agent.TempDirectory` is a temporary folder that is cleaned after each pipeline job. This directory is used by tasks such as `.NET Core CLI` task to hold temporary items like test results before they are published.

In the current package signing branch build pipeline has been modified to install the pre-release `net5` versions in `Agent.TempDirectory` temporary directory. This approach avoids changing the machine state because installing pre-release versions on `CI agents` can be inconsiderate to others.

As per offline conversation with team, we are leaning towards having the above said work around in the build pipeline until `net5` goes to GA.
