### ISSUE TITLE
dotnet add package --source not imperative

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#9033]
_From @iamalexmang on Tuesday, January 7, 2020 10:52:50 AM_

I strongly believe that if I explicitly mention a --source parameter for the package, especially in the format of a file system path, the CLI should not try validate the package's existence on any other sources. 
As of right now, when I specify the source parameter as a FS path, if either of the sources specified at the solution level, user global level (in %AppData%/NuGet) or computer level (Program Files (x86)), are unauthenticated, the package installation will fail. Regretfully, the error is completely unspecific as it complains which source returns a 401 Unauthorized error, though the package exists on the file system at the specified location.

_Copied from original issue: dotnet/sdk#4137_

**Comment by nkolev92** [comment]
Relevant https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-and-sources. 

> In PackageReference projects, the transitive dependency versions are resolved at restore time. As such, in PackageReference projects all sources need to be available for all restores.

I see this the --source option as the same.

**Comment by iamalexmang** [comment]
I do not want to disagree with you. What I'm saying is that from the CLI perspective, I'm **not** calling
```
dotnet add test.csproj package AlexsPackage
``` 
but instead, I'm calling 
```
dotnet add test.proj package AlexsPackage --source C:\Users\Alex\Packages
```
The way I read it is that I'm explicitly specifying a source. The problem appears because some devs choose to commit the NuGet.config configuration file specific to the solution. As you'd expect, AlexsPackage is in a private package feed.
Upon the CD pipelines, the agent building the solution doesn't have access to the private feed. However, it does have the NuGet package on the FS downloaded directly.

Imagine my surprise that (1) a NuGet.config specific somewhere in a parent folder is more specific than the imperative "add" command where I'm explicitly specifying the source and (2) the logs don't show the source I've specified as restore locations, at all, but instead fails with some bogus locations which don't show up in the user's or computer's NuGet.config file.

What I'm effectively saying here is that the CLI command, when it received a specific source location using the source parameter (**dotnet add package --source**) should not try to look into sources and especially, should not fail if other sources than the one specified are unauthorized.

Frankly, the way the add command works right now is almost like saying "Hey, here are some fresh apples for you", and you tell me "But I don't know how much apples cost at my usual supermarket".

**Comment by nkolev92** [comment]
Quick fingers when I saw this issue. The longer explanation. 

I'd imagine the reasoning behind including the default sources + the ones specified by --source is add package is really just another "restore". When restore happens, all packages get reevaluated. 

Say you have the following package dependency graph. 

A 1.0.0 -> B 2.0.0 -> E 1.5.0
C 2.0.0 -> D 1.5.0

And you are trying to add a package from a source that might have a version of E as a dependency.
Restore needs the old sources as well to make the best decision. 
Other scenarios are when the project is not restored. 

Anyway there is another report of similar scenario.
The whole thing will be reevaluated in that issue.
Duping it out to https://github.com/NuGet/Home/issues/6232
