### ISSUE TITLE
Restore:  excessive deep cloning of ProjectSpec

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9041]
When restoring ([`NuGet.Commands.RestoreRunner.RunAsync(...)`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs#L25)) NuGet makes wasteful use of memory with respect to `PackageSpec` objects.  This is especially noticable on large solutions.

[`DependencyGraphSpec.WithProjectClosure(...)`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L125-L136) creates `PackageSpec` clones by default.  [`PackageSpec.Clone()`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.ProjectModel/PackageSpec.cs#L192-L224) performs a fairly deep and expensive clone.  It's not clear that cloning by default is necessary.  Note that https://github.com/NuGet/NuGet.Client/pull/3094 was a targeted hack in that `DependencyGraphSpec` readonly-ness is not actually enforced and the optimization only applied to a specific command-line scenario.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9802. 

Sometimes we clone for hashing purposes. 
See: https://github.com/NuGet/NuGet.Client/blob/90ad7af83a860cc73ddaac9aa0c74c81fe446ef0/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L576 and https://github.com/NuGet/NuGet.Client/blob/90ad7af83a860cc73ddaac9aa0c74c81fe446ef0/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/NoOpRestoreUtilities.cs#L203. 

If we design a better hashing function that can intelligently decide what data from the packagespec to account for, we won't need to clone here.

**Comment by nkolev92** [comment]
There's 4 clones happening at this point: 

* NetCorePackageReferenceProject - https://github.com/NuGet/NuGet.Client/blob/0b178b9d10f7876fc7daa18487844f28d6bfea6b/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/NetCorePackageReferenceProject.cs#L166 - This is arguably necessary cause the config could've changed. We can change/improve certain things there, but that's a different issue. 

* https://github.com/NuGet/NuGet.Client/blob/0b178b9d10f7876fc7daa18487844f28d6bfea6b/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs#L83 - does plenty of cloning when generating the requests. The answer here is we can remove it, if and only if the restore operation doesn't modify the PackageSpec. If it does, it could affect the no-op hash and things would get funky. I think right now there are some places where the package spec gets modified during restore. Pretty sure CPVM especially does it, so I think there's some more digging that needs/should be done here.  **I will keep this issue open to track whether the package spec cloning here can be avoided. This is equally as bad as the thing fixed in https://github.com/NuGet/NuGet.Client/pull/3675**

* CPVM cloning at dg spec creation for all projects https://github.com/NuGet/NuGet.Client/pull/3658 @cristinamanum already has a PR fixing that. 

* Cloning during no-op hash calculation: https://github.com/NuGet/NuGet.Client/pull/3675 - I have a PR out. @cristinamanum I think my change in https://github.com/NuGet/NuGet.Client/pull/3675 will help your cpvm perf scenarios :)

**Comment by nkolev92** [comment]
Adjusting the estimate for the point 2 work.

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/10068 is where the investigation needs to go at this point. 
Changing the hashing function will make it easier to remove the extra clone.

**Comment by nkolev92** [comment]
Down to 2 clones, impactful, but there are bigger fish to fry right now.

**Comment by nkolev92** [comment]
We can implement a pattern like in LockFileTargetLibrary, https://github.com/NuGet/NuGet.Client/blob/41e98d33e40293d8276015d7a01e4d90610fa9d8/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileTargetLibrary.cs#L62-L65, where we *freeze* the package spec for modification. This would *ensure* that we don't change the package spec, so as such we can't modify it, and thus don't need to *clone* anymore, but use the same reference.

**Comment by KirillOsenkov** [comment]
I've been investigating MSBuild.exe growing to 6 GB while restoring a 1,000-project solution, and I've recorded allocations and indeed `PackageSpec.Clone()` (called by `DependencyGraphSpec.CreateFromClosure()`) is by far the biggest source of allocations:

![image](https://github.com/NuGet/Home/assets/679326/ed4f0a7e-d59c-49db-81a4-fcee1ef45641)

![image](https://github.com/NuGet/Home/assets/679326/9642814d-142d-451f-a05e-e3554ec31233)

I'd suggest maybe look into immutable objects and collections here? Or see if we need to clone at all? Also the way cloning is done it seems inefficient as well. Lots of lists and dictionaries and such. 

I'd say this is worth prioritizing as the top number 1 issue that makes restore slower and less efficient. Also I have a hunch that this memory isn't freed after restore is done, so something might be holding on to it?

**Comment by KirillOsenkov** [comment]
Liberal use of Linq here seems incredibly wasteful:

![image](https://github.com/NuGet/Home/assets/679326/bb279152-b63a-44b4-ba25-618c3d41d372)

https://github.com/NuGet/NuGet.Client/blob/39ea8e8081541fb1eb4702a5546e12f81fcad34d/src/NuGet.Core/NuGet.ProjectModel/PackageSpec.cs#L260-L261

https://github.com/NuGet/NuGet.Client/blob/39ea8e8081541fb1eb4702a5546e12f81fcad34d/src/NuGet.Core/NuGet.ProjectModel/PackageSpec.cs#L266

I think one should very carefully audit what is happening here and be deliberate which of these need to be cloned if at all. Feels like a lot of low-hanging fruit here.

**Comment by jeffkl** [comment]
@KirillOsenkov Static graph-based restore sets a flag on the DependencyGraphSpec that it can be considered read-only and doesn't call Clone().

https://github.com/NuGet/NuGet.Client/blob/39ea8e8081541fb1eb4702a5546e12f81fcad34d/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L103

Restore objects in Visual Studio are considered read/write since its a long running process from what I remember which is why I added this for command-line and static graph restore only.  Are you using static graph-based restore?

**Comment by KirillOsenkov** [comment]
No, we’re using regular restore. I think there was a blocker to adopting static graph restore.

**Comment by nkolev92** [comment]
To address this one, we can introduce the concept of "freeze" to ensure that the project spec won't be changed.
I think currently, this is more of a VS concern than a CLI one.

**Comment by KirillOsenkov** [comment]
Yes, my scenario is command-line msbuild.exe specifically. Would be great even if we just fixed the command line.
