### ISSUE TITLE
Restore:  closure computed for each project 4 times

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9042]
[`DependencyGraphSpec.GetClosure(...)`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L142-L181) is called twice for each project.  Once in [`DependencyGraphSpecRequestProvider.GetRequestsFromItems(…)`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs#L75-L77) and again in [`DependencyGraphSpec.WithProjectClosure(...)`](https://github.com/NuGet/NuGet.Client/blob/74d1935e4e25a90df536ae7cac6cf7c73c6ea678/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L129).  The result of the first call could be reused in `DependencyGraphSpec.WithProjectClosure(...)`.

**Comment by nkolev92** [comment]
3 times! :) 

Here's where **a** modification of the packagespec is happening. https://github.com/NuGet/NuGet.Client/blob/f544960b09be563228afa75e0dc031bb1760be6d/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/NoOpRestoreUtilities.cs#L197-L226

We can have a hash function that just ignores those fields rather than have extra cloning.
