### ISSUE TITLE
PackageReference and transitive dependencies

### ISSUE THREAD

**Issue by avivanoff** [NuGet/Home#9052]
A while back you [changed the default behavior of build dependency asset to transitive](https://github.com/NuGet/Home/issues/6091). I was reading discussions, as well as [spec](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior), but cannot find anything about potential [issue with transitive dependencies](https://curia.me/net-core-transitive-references-and-how-to-block-them/). I will sum it up here:

- Project DAL: references the Json.NET NuGet package and defines the class ClassDB;
- Project BLL: references the DAL project;
- Project UI: references the BLL project.

In this case, UI is able to access both the Json.NET package and the ClassDB class, which is quite dangerous, because it could let the developers to skip the architectural layers set up during design phase.

Is there something I am missing?

**Comment by rrelyea** [comment]
In Project.json & PackageReference, the build assets group were not treated transitively. However, in order to use targets that work even when the package was brought in transitively, we needed to enable build assets to be transitive.

We "Added buildTransitive assets group to allow flowing build assets transitively #2667"

This allows packages to remove need for install.ps1 and XDT files, moving to .targets to replace the functionality. But the package will work as a top-level dependency or as a transitive dependency.

We keep the \build\ asset group as the same behavior.

**Comment by avivanoff** [comment]
@rrelyea, I am talking about "compile" and "runtime" groups. See attached sample solution.
[TransitivePackageReference.zip](https://github.com/NuGet/Home/files/4119994/TransitivePackageReference.zip)

**Comment by rrelyea** [comment]
.NET Core uses transitive package references and transitive project references by default. If you'd like to change that behavior, this blog post details a way to change that:
https://curia.me/net-core-transitive-references-and-how-to-block-them/

**Comment by nkolev92** [comment]
Closing per the above comment.
