### ISSUE TITLE
PackageReference Condition not working

### ISSUE THREAD

**Issue by michal-ciechan** [NuGet/Home#9056]
Using latest Visual Studio2019 (16.4.2) adding a &lt;PackageReference Condition&gt; doesn't work as far as the generated NuGet package goes. The dependency is on all TargetFrameworks. Currently using a separate projects file per distinct targets and importing conditionally via `<Import Project="net451.packagerefs.targets" Condition="'$(TargetFramework)'=='net451'" />` as per StackOverflow answer https://stackoverflow.com/a/56028935/271106

* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#feedback)

**Comment by karann-msft** [comment]
@michal-ciechan - please provide detailed steps to reproduce this issue. For future reference use the send feedback about "This product" button instead of "This page" on the docs page to file product bugs. Here is a template:

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by michal-ciechan** [comment]
Ignore this, not sure what happened yesterday! Some strange behaviour, but trying to replicate this in a new project + in my original project seems to be working correctly! Spent last 30 min trying to replicate in original project and seems to be working. Making me think I went crazy somehow yesterday! Apologies

**Comment by karann-msft** [comment]
No worries @michal-ciechan! Glad you got it working. 👍
