### ISSUE TITLE
Eliminate code redundancy in XmlUtility.cs

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#9091]
While working on a ADO task observed that `XmlUtility` class is coded in 4 different places in NuGet client code. Good to remove code redundancy as part of engineering improvements work. 

$\NuGet.Client\src\NuGet.Core\NuGet.PackageManagement\Utility\XmlUtility.cs
$\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Implementation\Utility\XmlUtility.cs
$\NuGet.Client\src\NuGet.Core\NuGet.Configuration\Utility\XmlUtility.cs
$\NuGet.Client\src\NuGet.Core\NuGet.Packaging\PackageCreation\Utility\XmlUtility.cs

/cc @aortiz-msft

**Comment by rrelyea** [comment]
A few options I see here:
- keep as is
- move to a single xmlutility.cs and include in 4 different projects via relative path to .cs file
- move to a single xmlutility.cs and allow calling from 3 other projects (public exposure or internals visible to, etc...)  
- other?

@nkolev92 @zivkan @dtivel - any suggestions or other ideas?

**Comment by zivkan** [comment]
I don't see code duplication as an inherently bad thing. Duplicating business logic is bad because if requirements change, you might change some implementations and not others, leading to bugs. But if this duplicated code is "technical", rather than "business", it doesn't have the same risk.

Personally, I don't like linked/shared files between projects. I don't know what it is, I can't justify the position, but I don't like it.

Some people say that internals visible to is a code smell. I like it for tests, but think we should avoid it for anything else.

Having said that `NuGet.Common` has no clear focus, it's an API dumping ground, so perhaps is a good target to move it to. I'm not sure about `NuGet.Configuration`, but I'm confident the other assemblies already reference it. I don't want NuGet to be in the business of providing public APIs related to parsing XML, but if it's worthwhile combining them into one place, `NuGet.Common` would be the best place.

**Comment by nkolev92** [comment]
> move to a single xmlutility.cs and include in 4 different projects via relative path to .cs file

We already have prior art for this. 
We make everything internal and it's safe. 

I don't love it, but I don't hate it either. Feel like it has its uses. 

Random thoughts aside: 

* As a min bar, we should not make a breaking change. Specifically stuff that's public and in the NuGet.Core\* projects should not be removed. 

* No InternalsVisible to between production assemblies. See the guidelines: https://github.com/NuGet/NuGet.Client/blob/f00fe22cf7238383e3d0fa1dfa5e7f829092c8e9/docs/coding-guidelines.md#when-to-use-internals-vs-public-and-when-to-use-internalsvisibleto

* Beyond that, I feel like the APIs need to be examined to see how much duplication there is. Making the existing classes delegates to a new complete xml utility is an option too. Personally I think we should not be in the business of defining too many xml utilities as Andy suggested. NuGet.Common unification or shared compilation are where I am leaning.

**Comment by kartheekp-ms** [comment]
Here are my observations regarding the code redundancy.
- All 4 projects mentioned above have reference to `NuGet.Common`
- `NuGet.VisualStudio.Implementation\Utility\XmlUtility.cs` - 4 out of 6 methods have no references
- `NuGet.PackageManagement\Utility\XmlUtility.cs` - 3 out of 11 methods have no references
- `NuGet.Packaging\PackageCreation\Utility\XmlUtility.cs` - 1 out of 3 methods have no references

[Coding guidelines](https://github.com/NuGet/NuGet.Client/blob/f00fe22cf7238383e3d0fa1dfa5e7f829092c8e9/docs/coding-guidelines.md#when-to-use-internals-vs-public-and-when-to-use-internalsvisibleto)  suggests following best practice.
>If two runtime assemblies need to share common helpers then we use shared compilation.

I am learning towards shared compilation approach as suggested in the guidelines. @zivkan @rrelyea @nkolev92 -I really appreciate any additional guidance here.

**Comment by nkolev92** [comment]
Stuff in NuGet.Clients\ can be safely refactor to use lower level stuff if possible. 
Stuff in NuGet.Core shouldn't be changed if it's public. 
Are all these methods public? Is there actually a need for all these methods to exist?

**Comment by kartheekp-ms** [comment]
The only `XmlUtility` under `NuGet.Client` is `$\NuGet.Client\src\NuGet.Clients\NuGet.VisualStudio.Implementation\Utility\XmlUtility.cs` - This utility has `public` API.

All of the following  `XmlUtility` implementations are under `NuGet.Core`.

- `$\NuGet.Client\src\NuGet.Core\NuGet.Configuration\Utility\XmlUtility.cs` - This utility has `internal` API.
- `$\NuGet.Client\src\NuGet.Core\NuGet.Packaging\PackageCreation\Utility\XmlUtility.cs` - This utility has `public` API.
- `$\NuGet.Client\src\NuGet.Core\NuGet.PackageManagement\Utility\XmlUtility.cs` - This utility has `public` API.

**Comment by kartheekp-ms** [comment]
I have completed most of the work already for this issue. I will submit a PR shortly and happy to address the feedback as well.

**Comment by kartheekp-ms** [comment]
The code changes in this PR were reverted because `NuGet 5.7 insertion` into `dotnet ` failed. As per [this](https://github.com/NuGet/Home/issues/9733#issuecomment-654333769) comment, it looks like `NuGet 5.8` is a good time to insert this code. I am planning on rebasing this branch with `dev` and run the CI again. If everything is green, can we merge this PR again ?

**Comment by zivkan** [comment]
I'd feel more comfortable if instead of deleting the old APIs (only the ones that would otherwise trigger changes in PublicAPI.*.txt files), mark them as obsolete. If possible, also change the body to call the new API. We can then consider deleting them in NuGet 6.x. Although I still think it would be surprising if anyone uses NuGet to do XML loading, so I don't feel strongly about this.
