### ISSUE TITLE
Adding a non-supported package to a portable project targeting UWP, NET46 and ASP.NET results in 25 errors

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#910]
I have a project.json like this:

```
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0-beta-23106",
    "EntityFramework.Cache": "1.0.0"
  },
  "frameworks": {
    "dotnet": {}
  }
}
```

This results in 25 errors:

Severity    Code    Description Project File    Line
Error       EntityFramework 6.1.0 is not compatible with DNXCore,Version=v5.0 (win7-x64).           0
Error       EntityFramework 6.1.0 is not compatible with DNXCore,Version=v5.0 (win7-x86).           0
Error       EntityFramework 6.1.0 is not compatible with DNXCore,Version=v5.0.          0
Error       EntityFramework.Cache 1.0.0 is not compatible with .NETPlatform,Version=v5.0.           0
Error       EntityFramework.Cache 1.0.0 is not compatible with DNXCore,Version=v5.0 (win7-x64).         0
Error       EntityFramework.Cache 1.0.0 is not compatible with DNXCore,Version=v5.0 (win7-x86).         0
Error       EntityFramework.Cache 1.0.0 is not compatible with DNXCore,Version=v5.0.            0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-arm).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x86).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).           0
Error       EntityFramework.Cache 1.0.0 is not compatible with UAP,Version=v10.0.           0
Error       Some packages are not compatible with .NETPlatform,Version=v5.0.            0
Error       Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).          0
Error       Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).          0
Error       Some packages are not compatible with DNXCore,Version=v5.0.         0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-arm).            0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).            0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-x64).            0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).            0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-x86).            0
Error       Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).            0
Error       Some packages are not compatible with UAP,Version=v10.0.            0

Instead of showing these all as errors, can instead we make use of the new ErrorList's ability to expand an error, so that we say something like "Some packages are not compatible with this project", then if I want the details, expand the error.

All of this information is just noise, all I want to know is that the package is not compatible with the current targets. None of above makes any sense.

**Comment by yishaigalatzer** [comment]
See also scenario from #2409 

@natemcmaster

Restoring on Entity Framework with verbosity minimal still produced 4,722 lines of warnings resulting from "Detected package downgrade." This includes hundreds of duplicate warnings, such as this line that is logged 108 times when restoring the EF:

warn : Detected package downgrade: System.Resources.ResourceManager from 4.0.1-rc2-23923 to 4.0.1-rc2-23911
Full log: 
restorelog.txt

It is nearly impossible for a human to digest thousands of lines of log output and figure out how to solve the problem.

**Comment by natemcmaster** [comment]
Just FYI: this problem got worse recently. NuGet is now logging >50,000 lines of warning output even with minimal verbosity. This produces so much log output that EF builds on travis-ci.org get cancelled because of "Too much log output."

> The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
> The job has been terminated

**Comment by yishaigalatzer** [comment]
Fix the downgrade warnings?

**Comment by joelverhagen** [comment]
As a workaround until you fix the warnings, you could use

```
dotnet restore --verbosity error
```

This will still give you visibility into big problems but hide those millions of warnings.

**Comment by joelverhagen** [comment]
I am going to set aside the downgrade warnings now produced by the original project.json. I think @davkean's intent here was just the "not supported" errors. I modified the project.json to depend on packages that are on NuGet.org:

``` json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "EntityFramework.Cache": "1.0.0"
  },
  "frameworks": {
    "dotnet": {}
  }
}
```

With this project.json, I am seeing **33 distinct error messages**.

As @davkean said, there is a LOT of output and it's hard to understand as a mere mortal. We can categorize the error messages:
1. Specific errors about a package not being compatible with a TFM/RID pair.
   1. Errors about direct dependencies (`EntityFramework.Cache 1.0.0` in this case)
   2. Errors about transitive dependencies (`EntityFramework 6.1.0` in this case)
2. General errors about there being some incompatible packages with a TFM/RID pair.

There are a lot of TFM/RID pairs because of the `supports`. 

After this categorization, it seems like the following actions could be take. Could you guys comment on each?

### Only report package incompatibilities for the common parents.

Can't think of a better wording so let me give an example. In the project.json mentioned above, both `EntityFramework.Cache` and `EntityFramework` have compatibility issues. Since `EntityFramework.Cache` is the parent of `EntityFramework`, only report the incompatibilities with `EntityFramework.Cache`. Since the user has to solve the problem with `EntityFramework.Cache` anyways, there's no point in talking about problem's with that packages dependencies.

If we apply this strategy, the number of errors would go from 33 to 22.

### If there are incompatibilities in a project's `"frameworks"`, don't report `"supports"` problems.

`"supports"` are guardrails that have no impact on build output. It is only used during restore (as far as I know) and are really a safety check done for convenience. `"frameworks"` are actually what you plan on compiling for. Therefore, the user should solve the `"frameworks"` problems first.

If we apply this strategy, the number of errors would go from 33 to 3.

### If there are RID-less (TFM with no RID) compatibility problems as well was TFM + RID problems, only show the RID-less problems.

As far as I know, we always do a RID-less restore. If there are any RID restores at all, they happen after the RID-less restore. Since we always do that RID-less restore, the user should fix problems the problems there before investigating RID related issues.

If we apply this strategy, the number of errors would go from 33 to 9.

### Summary

Today, our error messages indiscriminately tell the user everything that is going wrong throughout all targets and all dependencies (transitive and direct). We can alter this strategy to show the errors that we think the user should solve first.

If we applied all of the strategies mentioned above, the number of errors would go from 33 to 2. The output would be:

```
error: Package EntityFramework.Cache 1.0.0 is not compatible with dotnet (.NETPlatform,Version=v5.0). Package EntityFramework.Cache 1.0.0 supports:
error:   - net40 (.NETFramework,Version=v4.0)
error:   - net45 (.NETFramework,Version=v4.5)
error: One or more packages are incompatible with .NETPlatform,Version=v5.0.
```

**Comment by rohit21agrawal** [comment]
this experience has improved with our errors and warnings work in nuget 4.x
