### ISSUE TITLE
Excluding specific items from nuget library when using PackageReference

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#9101]
I am a package developer and I want to debug one assembly from my package in the context of an application that consumes the package.  In the old packages.config style all package assemblies were direct references in the project using it.  If MyTestPackage had A.dll and B.dll I could bring the csproj for A.dll into my solution and swap out the references from nuget to local project easily.  Is there anything I can take advantage of in the new PackageReference format to accomplish the same?

**Comment by nkolev92** [comment]
A more general ask for this is in: https://github.com/NuGet/Home/issues/5986

NuGet has some support for controlling the assets pulled in from a package - https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

But it mostly talks about asset groups rather than specific. 

That's really a consequence of the design of PackageReference, assets selection part is abstracted away from the project file, so that things like updates are easier to manage etc.
