### ISSUE TITLE
NU1101: Extremely difficult to fix. need more details in message.

### ISSUE THREAD

**Issue by SimonSDA** [NuGet/Home#9144]
This error has caused me the greatest amount of pain as Visual Studio is really bad at dealing with NuGet PackageReference for non - .net.core projects. I mean REALLY BAD. Here is an example (for an asp.net webservice):

NU1101	Unable to find package Gladstone.ClubCentric.HeadOffice.BackEnd.DataAccess.SDABankOfIrelandEFTCommon. No packages exist with this id in source(s): ClubCentric, Microsoft, Microsoft Visual Studio Offline Packages	SDAMemberWS	C:\Git\Build\ClubCentric\HeadOffice\BackEnd\WebServices\SDAMemberWS\SDAMemberWS.csproj	1	

This package DOES exist. It is correctly references in the project and the nuspec file. I have cleared the nuget cache, wiped obj folders etc. The problem will be down to some OTHER package referencing this package which has some other problem, which is nigh on impossible to find. Why can this error not show the ACTUAL PACKAGE that is causing the problem...

I am in the process of converting a massive (500+ project) set of solutions to using NuGet packages (as fun as it sounds) and had to do most of this manually as Visual Studio has no built-in way to do it. Namely:

1) Creating a NuGet package for a DLL will not include any dependent DLLs in the same solution (i.e. non-nuget references). They have to be manually added in the &lt;files&gt; section in the .nuspec file.

2) Updating an existing package (without changing the version number) requires deleting the bin and obj folders + wiping the .suo file from the hidden .vs folder in the solution, clear the nuget cache then package restore as it tends to hang around in various package.json files and obj folders otherwise causing much frustration.

3) projects have to be set to output to bin\ in all configurations rather then bin\debug / bin\release as you have to hard-code dependent files in the nuspec file as per point 1).

4) Including project-dependent DLLs as per step 1) seems to cause the compiler to build each of their dependencies multiple times leading the much longer compile time when using nuget pack -Build. This doesn't happen with a regular build using msbuild.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c334f18d-66ca-28a9-3350-c20e762bbec1
* Version Independent ID: 2ea96dfa-e016-ae3b-864c-2a1ce513d90e
* Content: [NuGet Error NU1101](https://docs.microsoft.com/en-gb/nuget/reference/errors-and-warnings/nu1101?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-GB%26k%3Dk(NU1101)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1101.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1101.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by olevezinho** [comment]
@jr549 I later discovered that this happened because I was trying to restore a package that I was developing on a unit test within the same solution. Basically it's somewhat a circular dependency which is causing your test projects not to compile. If you think about it it doesn't make any sense, you are probably using a class that you developed in one of those tests and trying to use it as a dependency.

**Comment by jr549** [comment]
VSCode is my opinion is much more error prone than VS since you can easily
clobber your project with a single command. I am still able to follow along
with the textbook instructions using console applications and CLI  commands
to run exercises.I have had my problems with third party extensions like
Xunit. Debugging is still unavailable for my 32 bit machine but at this
point that is not enough to deter my efforts. My problem was resolved by
deleting the nuget.config file which by regeneration allowed for online
access.  The Package Manager of VS allows for greater control of sources,
like deleting cache store and source configuration. Somehow before this Net
Core was creating the template but on restore it was conflicted and could
not find any single source for the XUnit package that it liked even though
I downloaded and upackaged several different versions.

**Comment by nkolev92** [comment]
Hey all, 

Looks like most of you are having trouble because of the configuration in place. 

Can you please refer to: 
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#changing-config-settings for changing the settings and report back? 

Note that the recommended behavior is to have 1 NuGet.config in your repo and the config should in the same directory as the sln file or above it.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
