### ISSUE TITLE
Automated creation of docs for `dotnet nuget` commands.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#9146]
Still needed to finish [NuGet/Home#4126] add `dotnet nuget <add|remove|update|disable|enable|list> source` command:
- [x] docs.tt 
- [x] docs into dotnet docs repo
- [x] sdk checkin
- [x] anything else

**Comment by donnie-msft** [comment]
What's the cost to make `list` identify the nuget.config where it found the listed Source?
Perhaps Verbosity Detailed could be required. 

My understanding is you need to open all the nuget.configs in your directory tree if you want to identify where a Source is being added. Tricky to eye-ball this since a </clear> could be applied upstream.

**Comment by rrelyea** [comment]
I've not investigated this. My guess is that it wouldn't be too big. My impression is that the config data structure keeps track of where it came from. But I haven't dug in.
That isn't tracked by this issue though.

**Comment by donnie-msft** [comment]
Sounds promising.... If you can direct me to the right issue, I'll complain in the appropriate place 🤣

**Comment by rrelyea** [comment]
I replied offline pointing to a new issue tracking this.
