### ISSUE TITLE
NuGetPackageRoot & other properties in csproj.nuget.g.props not set on first build

### ISSUE THREAD

**Issue by realrubberduckdev** [NuGet/Home#9150]
## Details about Problem

The MSBuild properties set in csproj.nuget.g.props, do not get set on the first run of csrpoj file. They are set on subsequent runs. They are set if we build from solution file even on the first clean run.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `msbuild.exe`

NuGet version (x.x.x.xxx): `5.0.2.5988 NOTE: This version of nuget.exe is in the path, I do not think it is relevant to the issue though. Adding in case you find it useful.`

msbuild.exe --version (if appropriate): `16.4.0+e901037fe`

VS version (if appropriate): `VS2019 Professional 16.4.2`

OS version (i.e. win10 v1607 (14393.321)): `Win10 1903`

## Detailed repro steps so we can see the same problem

1. Unzip the attached sample [WithSlnWorks.zip](https://github.com/NuGet/Home/files/4169897/WithSlnWorks.zip)

2. CD into the folder via developer visual studio command prompt.

3. Ensure that bin & obj folders are not present.

4. Run command:

`msbuild .\WithSlnWorks.csproj /t:Restore /t:Rebuild`

See output:
```
ShowMessage:
  NuGetPackageRoot= NuGetProjectStyle=
```

5. Re-run the same command again and see the output.

```
ShowMessage:
  NuGetPackageRoot=C:\Users\<username>\.nuget\packages\ NuGetProjectStyle=PackageReference
```
Notice how NuGetPackageRoot & NuGetProjectStyle are only set on second run and not the first time.
...

## Other suggested things

If delete the bin and obj folder and do the same build with the solution (.sln) file, it works the first time.

### Sample Project

[WithSlnWorks.zip](https://github.com/NuGet/Home/files/4169897/WithSlnWorks.zip)

**Comment by nkolev92** [comment]
Hey @realrubberduckdev 

This is unfortunately by design. Because of NuGet's integration with msbuild, you have to separate the invocations of build and restore to allow msbuild to reload the props/targets nuget writes (nuget.g.* specifically). 

To do the same thing in one invocation, msbuild has added a -restore or /restore switch. 

See: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-and-building-with-one-msbuild-command

That would run restore, throw out the evaluation and then run the target specified. 

Note that this is exactly how dotnet build work, it invokes restore first, then build in a different invocation.
