### ISSUE TITLE
Design API Spec for providing Available Updates for a given Project

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9154]
Define the specification for a new API that would provide the number of currently available updates for NuGet packages  in a given project within a Solution.

Performance would be critical, as the primary use-case will be a call from Project System to display the # of available updates in the nodes of Solution Explorer.

Project System will need the capability of invoking this API for this Epic.

**Comment by nkolev92** [comment]
Closing in favor of: https://github.com/NuGet/Home/issues/11547. 

This issue tracked a particular way of implementing things that is now slightly different due to https://github.com/NuGet/NuGet.Client/commits/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer living in our repo.

It was added in May 2020, a few months after this issue was created
