### ISSUE TITLE
Design API Spec for opening the PMUI Window + specific Tabs & pre-selected Packages

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9155]
Define the specification for a new API that would allow the Package Management UI window to be opened to a specific tab. 

The Updates tab should also be capable of being opened with a set of Packages pre-selected. Automatically focusing on a particular element (likely the Update button) should be considered from an Accessibility perspective, as well as from a  general UX perspective.

The current use-case is only for the Updates tab. Whether the API should support all 4 tabs would be an open question.

Project System will need the capability of invoking this API for this Epic.

**Comment by nkolev92** [comment]
Similar as an earlier issue:

Closing in favor of: https://github.com/NuGet/Home/issues/11547. 

This issue tracked a particular way of implementing things that is now slightly different due to https://github.com/NuGet/NuGet.Client/commits/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer living in our repo.

It was added in May 2020, a few months after this issue was created
