### ISSUE TITLE
Changing the powershell function 'prompt' on NuGet PowerShell console will hang VS

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#917]
Repro steps:
1. Open up Visual Studio 2015, open the NuGet Package Manager Console and paste in this line:
 
    function prompt { Write-Host ("PS " + $(get-location) +">") -nonewline -foregroundcolor Magenta; return " " }
 
2. Press enter.

**Comment by yishaigalatzer** [comment]
This is a regression from visual studio 2013. Can we take a look if we understand the root cause, and if there is any other alarming scenario here?

**Comment by deepakaravindr** [comment]
I investigated the issue. It only happens when the "prompt" function is being overriden

There are 2 reasons why this happens

1.	With NuGet’s Powershell Console, the default prompt function looks like the following. However, the “prompt” function is being overridden by the scenario and it doing a writeline, which will switch to the main thread. So, now pressing enter will explicity switch to the main thread at the end

# default prompt
function prompt {
    "PM>"
}

2.	NuGet has changed its code a lot in this release to comply to the new VS threading rules. This meant that executing powershell scripts synchronously from the UI thread would block the UI thread and wait for the powershell thread (pipeline execution thread) to return. This is the case with the execution of prompt function. In VS2013, we did not comply to the VS threading rules, that is why it does not deadlock

As you can see, from (1) and (2) above, when enter is pressed, NuGet is trying to execute “prompt” function from the UI thread and blocks it. The overridden “prompt” function will try to switch to the UI thread and it cannot. That is the deadlock

**Comment by eriawan** [comment]
@deepakaravindr 
Can we rephrase the issue title? It should be titled "Executing **some** PowerShell commands on **NuGet PowerShell console** will hang VS" instead of just "Executing PowerShell command on PowerShell console will hang VS".
I'm sure this will provide better visibility and less ambiguous meaning, because this rephrase will put emphasize on NuGet Powershell console, instead of any Powershell console.

**Comment by eriawan** [comment]
Thanks, @deepakaravindr 
:+1:

**Comment by remcoros** [comment]
This currently prevents the use of posh-git inside the package manager console of VS 2015.

Whenever I uncomment the following lines from NuGet_Profile.ps1, Visual Studio hangs and needs to be killed from the task manager:

It hangs on the 'Write-Host' call.


```powershell
# Set up a simple prompt, adding the git prompt parts inside git repos 
function global:prompt {
    $realLASTEXITCODE = $LASTEXITCODE

    # Write-Host($pwd.ProviderPath) -nonewline

    # Write-VcsStatus

    $global:LASTEXITCODE = $realLASTEXITCODE
    return "> "
}
```

**Comment by zbrad** [comment]
I finally tracked down a workaround that is working for me, by testing the value of $profile in my profile.ps1, eg:
if (!$profile.Contains("NuGet_profile")) {
   # normal start
  . $PSScriptRoot\prompt.ps1
  }

**Comment by yishaigalatzer** [comment]
@zbrad thanks for sharing!

**Comment by paulmarsy** [comment]
Coming from investigating this in dahlbyk/posh-git#218 the prompt does return after a period of time for me, so there is likely a timeout happening at some point so it isn't totally deadlocked and will return so no changes/work in Visual Studio are lost if someone is patient.

Additionally the use of any 'Out-' commands in the prompt function appear to trigger this problem, Out-File and Out-String both cause the issue despite not (in an obvious way) doing something that is dependent upon the UI thread.
