### ISSUE TITLE
Documentation on how to use the *.csproj CDATA block to provide information?

### ISSUE THREAD

**Issue by diberry** [NuGet/Home#9174]
How do I use the CDATA block as a first class citizent to provide rich text and hyperlinks to information relevant to my customers to use the package? 

Is there reference documentation somewhere?

**Comment by dominoFire** [comment]
> How do I use the CDATA block as a first class citizent to provide rich text and hyperlinks to information relevant to my customers to use the package?

Since the .csproj file is an XML file, you can use CDATA in the nodes. In the following .NET Core sample library, the csproj would look like:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageVersion>0.0.3</PackageVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <Description><![CDATA[<h1>Package Title</h1>

A package with awesome functionalities

<pre>
var x = ClassLib1.AwesomeStuff(param1, param2);
</pre>

<h2>Features</h2>

Lots of features

More info at <a href="https://nuget.org">this website</a>

<ul>
<li>Support for multiple languages</li>
<li>打发发阿飞是否教案反思了啊</li>
</ul>
]]></Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.OData" Version="5.6.3" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.1" />
  </ItemGroup>
</Project>
```
In the preview page in nuget.org, the description appears as follows:

![image](https://user-images.githubusercontent.com/1192347/74580560-55999180-4f5a-11ea-8b1c-dbae048af221.png)

> Is there reference documentation somewhere?

I did a quick search and I couldn't find any documentation. This issue may be related: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1324

**Comment by diberry** [comment]
@dominoFire Thank you. I don't find this information in the docs anywhere. Can you provide the link?

**Comment by aortiz-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1980](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1980) via [**ZenHub**](https://www.zenhub.com/)
