### ISSUE TITLE
packages element with xmlns set makes the nuget discover process find nothing.

### ISSUE THREAD

**Issue by mrpaulreed** [NuGet/Home#9185]
NuGet product used (Package Manager Console):Package Manager Console

NuGet version (x.x.x.xxx):Package Manager Console Host Version 5.4.0.6292

dotnet.exe --version (if appropriate):

VS version (if appropriate): VS2019 Community Edition

OS version (i.e. win10 v1607 (14393.321)):Win 10

---------------------

1. with a nuget based web project there is a packages.config file produced. PackagesReferences are not allowed on this project type.

2. My packages.config file has been altered to give this front tag:

<?xml version="1.0" encoding="utf-8"?>
<packages xmlns="urn:packages">
... <package id=...  references inside in the normal way. >
</packages>

2. Using the xmlns attribute/property removes the nag of the message: "The packages element is not declared" in build output.

3. Unfortunately this breaks the ability to detect packages in the project for nuget.

Q: Could you fix the detector part of the code to ignore the inner attributes of the "packages" tag.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/1836

**Comment by Pxtl** [comment]
This issue burned me so badly I just spent four hours trying to figure it out because Nuget happily chirps "everything is already installed!" or some nonsense when **no nothing is installed you get nothing good day**. Because I googled "what xmlns for packages.config" and in doing so made everything fail *silently*.
