### ISSUE TITLE
migrating to nuget v3 

### ISSUE THREAD

**Issue by omribeni** [NuGet/Home#9187]
I have been using Nuget.core latest version in my .net project  to Connect to the package repository I have sitting in in Azure Artifacts.

something changed in the passed few days and the authentication using my pat failed. (i checked it, its not that).
I saw that azure decided to switch their connection to feeds using nuget v3. and there is no manual doing it other then with 1) .net core cli.  2) visual studio package manager. 3) nuget.exe.

does that mean i can't use c# code using a (nuget client package) to connect to a my feed anymore?

**Comment by zivkan** [comment]
A few years ago NuGet.Core was split into multiple assemblies, most of the projects that you can now see in our [`src\NuGet.Core` folder](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core). This happened before, or about the same time, as the NuGet v3 protocol was created, so the NuGet.Core package never implemented that protocol. I joined the team a long time after the split happened, so I have no idea what the migration to the new packages involves, but all the NuGet client code is open source, and everything that the dotnet cli uses is available in packages, so if the dotnet cli can do it, so can your own app.

We recently added [some docs on basic usage of the `NuGet.Protocol` assembly](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk), which is what you'd need to use to talk to HTTP feeds. Authentication in NuGet is a complex story, and I don't know how the code works, so I can't give API usage advice. Maybe it will "just work" (some authentication code happens in NuGet.Protocol's HttpClient handler), otherwise my best suggestion would be to debug nuget.exe ([`NuGet.Client/src/NuGet.Clients/NuGet.CommandLine/`](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.CommandLine) to figure out how it works.

**Comment by nkolev92** [comment]
Closing per the above.
