### ISSUE TITLE
<Library>.runtimeconfig.json is not copied from lib to output

### ISSUE THREAD

**Issue by Lonli-Lokli** [NuGet/Home#9191]
## Details about Problem
Actual issue -only dotnet-swagger.dll is ocpied, dotnet-swagger.runtimeconfig.json is not copied as assets from nuget to output folder.

It's actually required to run dll with this file as well.

[RuntimeConfigNugetIssue.zip](https://github.com/NuGet/Home/files/4224768/RuntimeConfigNugetIssue.zip)

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):
3.1.101

VS version (if appropriate):
VS 16.4.3
OS version (i.e. win10 v1607 (14393.321)):
win10 v1909

## Detailed repro steps so we can see the same problem

1. Open solution and run rebuild
...

### Sample Project

Sample attached.

**Comment by zivkan** [comment]
NuGet doesn't directly copy files from the lib folder, it advertises the assemblies to MSBuild and the .NET SDK. If files need to be copied to the project output on publish, the package author should use the `contentFiles` [as documented](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files). However, it sounds like `dotnet-swagger` might be intended to be used as a [.NET Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools), rather than a package reference?
