### ISSUE TITLE
Restore:  improve performance by caching solution dependency graph spec

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9201]
Every solution restore begins by [recreating the solution dependency graph (DG) spec](https://github.com/NuGet/NuGet.Client/blob/f67a6083f8a49502f52f0c50492db03452785359/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/DependencyGraphRestoreUtility.cs#L220-L276).

We should be able to improve performance for at least all the non-first restores by caching the solution DG spec.  (We already write it out for error reporting but use it for restore purposes.)  If we keep track of project DG spec file timestamps, we can know if the cached solution DG spec needs to be invalidated and recreated from project DG specs.

**Comment by nkolev92** [comment]
I don't know if this will yield too much benefit. If one has sdk based projects only the expensive part is probably the project list generation as it might use the UI thread. 

* SDK based projects package specs are already cached
* LegacyPackageReference projects, not so much because we don't get nominated for changes. The trick is that if we have restored ones, most likely changes would require one of 2 things, a project reload or a NuGet driven action, so maybe we can benefit from that bit. 

Given that most of the large objects are not duplicated, wouldn't this just save us a bunch of collection objects?

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/pull/3306 out to fix the performance regression from 4.9.

As far as further caching goes it's already happening for SDK based projects and it's impossible to cache for Legacy projects, so we are as good as we can be.
