### ISSUE TITLE
Toolbox and Nuget error

### ISSUE THREAD

**Issue by kaptcha0** [NuGet/Home#9221]
I have added a nuget package to my wpf (.NET Core 3.1) application and I am trying to add the components in the package to the Visual Studio 2019 Toolbox. The problem is that it says that the .dll file doesn't contain any objects that can be added into the Toolbox, even though there should be something! 

For anyone curious, I added the MaterialDesignThemes (v3.1.0-ci981) package, and I am trying to add MaterialDesignThemes.Wpf.dll.

**Comment by debonte** [comment]
Hi @ProgrammerAI,

It sounds like you went into the Choose Toolbox Items dialog, browsed to %USERPROFILE%\.nuget\packages\materialdesignthemes\3.1.0-ci981\lib\ **net45** \MaterialDesignThemes.Wpf.dll, and expected to see the MaterialDesignThemes added to the Choose Toolbox Items list box, but instead got this error:

![image](https://user-images.githubusercontent.com/12820898/75394878-fb77c500-58a5-11ea-95d8-5a7fb45e579a.png)

This is happening because MaterialDesignThemes.Wpf.dll references MaterialDesignColors.dll (from the MaterialDesignColors package) and Choose Toolbox Items doesn't know how to find it. The error message isn't helpful here and unfortunately Choose Toolbox Items isn't smart enough to find the needed DLL in the other package. You can work around this by copying MaterialDesignColors.dll into the same directory as MaterialDesignThemes.Wpf.dll and then trying again.

That said, since your project is a WPF .NET Core project, I assume that you really want Toolbox to show the controls from %USERPROFILE%\.nuget\packages\materialdesignthemes\3.1.0-ci981\lib\ **netcoreapp3.0** \MaterialDesignThemes.Wpf.dll (the package's .NET Core assembly). Although Visual Studio is able to dynamically enumerate controls in .NET Framework WPF control libraries and add them to the Toolbox, it is unable to do this for .NET Core WPF control libraries. So if you try to browse to this .NET Core DLL in Choose Toolbox Items you'll get the following error:

![image](https://user-images.githubusercontent.com/12820898/75369248-f13ed200-5877-11ea-8ae5-10e6fc8e2612.png)

Authors of NuGet packages that contain WPF .NET Core controls should instead explicitly declare the controls that they want to appear in the Toolbox by including a tools\VisualStudioToolsManifest.xml file in the package as described at [https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls](https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls). In this case the package author has not provided a VisualStudioToolsManifest.xml so you could add one by doing the following:

1. Go to %USERPROFILE%\.nuget\packages\materialdesignthemes\3.1.0-ci981
2. Create a tools subdirectory
3. Download [VisualStudioToolsManifest.zip](https://github.com/NuGet/Home/files/4258569/VisualStudioToolsManifest.zip)
4. Unzip it and place the VisualStudioToolsManifest.xml file it contains in the tools directory. I created this file manually and included all of the types from MaterialDesignThemes.Wpf.dll that appeared to be WPF controls.
5. Restart Visual Studio. Reopen your project and XAML file. You should now see the controls in the Toolbox.

**Comment by ProgrammerAI** [comment]
It doesn't work. I need to be able to access all of the components that I would manually write in XAML.

**Comment by kaptcha0** [comment]
> Hi @ProgrammerAI,
> 
> It sounds like you went into the Choose Toolbox Items dialog, browsed to %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981\lib\ **net45** \MaterialDesignThemes.Wpf.dll, and expected to see the MaterialDesignThemes added to the Choose Toolbox Items list box, but instead got this error:
> 
> ![image](https://user-images.githubusercontent.com/12820898/75394878-fb77c500-58a5-11ea-95d8-5a7fb45e579a.png)
> 
> This is happening because MaterialDesignThemes.Wpf.dll references MaterialDesignColors.dll (from the MaterialDesignColors package) and Choose Toolbox Items doesn't know how to find it. The error message isn't helpful here and unfortunately Choose Toolbox Items isn't smart enough to find the needed DLL in the other package. You can work around this by copying MaterialDesignColors.dll into the same directory as MaterialDesignThemes.Wpf.dll and then trying again.
> 
> That said, since your project is a WPF .NET Core project, I assume that you really want Toolbox to show the controls from %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981\lib\ **netcoreapp3.0** \MaterialDesignThemes.Wpf.dll (the package's .NET Core assembly). Although Visual Studio is able to dynamically enumerate controls in .NET Framework WPF control libraries and add them to the Toolbox, it is unable to do this for .NET Core WPF control libraries. So if you try to browse to this .NET Core DLL in Choose Toolbox Items you'll get the following error:
> 
> ![image](https://user-images.githubusercontent.com/12820898/75369248-f13ed200-5877-11ea-8ae5-10e6fc8e2612.png)
> 
> Authors of NuGet packages that contain WPF .NET Core controls should instead explicitly declare the controls that they want to appear in the Toolbox by including a tools\VisualStudioToolsManifest.xml file in the package as described at https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls. In this case the package author has not provided a VisualStudioToolsManifest.xml so you could add one by doing the following:
> 
> 1. Go to %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981
> 2. Create a tools subdirectory
> 3. Download [VisualStudioToolsManifest.zip](https://github.com/NuGet/Home/files/4258569/VisualStudioToolsManifest.zip)
> 4. Unzip it and place the VisualStudioToolsManifest.xml file it contains in the tools directory. I created this file manually and included all of the types from MaterialDesignThemes.Wpf.dll that appeared to be WPF controls.
> 5. Restart Visual Studio. Reopen your project and XAML file. You should now see the controls in the Toolbox.

That doesn't work. I need to access all of the components that I would usually write in XAML.

**Comment by debonte** [comment]
> That doesn't work. I need to access all of the components that I would usually write in XAML.

Can you please be more specific? What are you expecting to see in the Toolbox that is not there? If it's a type that's missing, what specific type? A screenshot might be helpful.

**Comment by kaptcha0** [comment]
@debonte 
What I mean is that I want to follow the steps mentioned in [this video](https://youtu.be/LzBYFVTVjXM?t=630). where he adds all the controls from the .dll. The problem is that when I try to follow the tutorial, I get the error you mentioned above.

**Comment by debonte** [comment]
As I said above, Choose Toolbox Items does not work for .NET Core control libraries. The VisualStudioToolsManifest.xml approach is the only supported way to populate the Toolbox from a WPF .NET **_Core_** NuGet package.

If you follow these instructions you'll achieve the same result (all of the MaterialDesignThemes controls in the Toolbox). Did you try it?

> 1. Go to %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981
> 2. Create a tools subdirectory
> 3. Download VisualStudioToolsManifest.zip
> 4. Unzip it and place the VisualStudioToolsManifest.xml file it contains in the tools directory. I created this file manually and included all of the types from MaterialDesignThemes.Wpf.dll that appeared to be WPF controls.
> 5. Restart Visual Studio. Reopen your project and XAML file. You should now see the controls in the Toolbox.

**Comment by kaptcha0** [comment]
This didn't work. It doesn't  automatically show up in the toolbox.
> As I said above, Choose Toolbox Items does not work for .NET Core control libraries. The VisualStudioToolsManifest.xml approach is the only supported way to populate the Toolbox from a WPF .NET **_Core_** NuGet package.
> 
> If you follow these instructions you'll achieve the same result (all of the MaterialDesignThemes controls in the Toolbox). Did you try it?
> 
> > 1. Go to %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981
> > 2. Create a tools subdirectory
> > 3. Download VisualStudioToolsManifest.zip
> > 4. Unzip it and place the VisualStudioToolsManifest.xml file it contains in the tools directory. I created this file manually and included all of the types from MaterialDesignThemes.Wpf.dll that appeared to be WPF controls.
> > 5. Restart Visual Studio. Reopen your project and XAML file. You should now see the controls in the Toolbox.

**Comment by debonte** [comment]
@ProgrammerAI can you zip the contents of %USERPROFILE%.nuget\packages\materialdesignthemes\3.1.0-ci981 and upload them here?

**Comment by kaptcha0** [comment]
@debonte
[3.1.0-ci981.zip](https://github.com/NuGet/Home/files/4278480/3.1.0-ci981.zip)
ok

**Comment by kaptcha0** [comment]
Nevermind, it just popped up.
Thank you so much.
