### ISSUE TITLE
The pack targets should have PackageOutputPath default to OutputPath

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9231]
In sdk based projects it's already done in the default framework properties.
In legacy package reference projects, the customer is required to set PackageOutputPath.

related https://github.com/NuGet/docs.microsoft.com-nuget/pull/1922

**Comment by Nirmal4G** [comment]
This could be superseded by #9234

### Reason

Pointing to `OutputPath` is bad since it changes for every combination of `Platform`, `TargetFramework` and `RuntimeIdentifier`. So, we can use the `BaseOutputPath` property instead. Also removing from the SDK frees up the possible places where we can set those properties (e.g. `Directory.Build.targets`).

Even though It works now, in the future, this usage might lead to something similar to `RestoreOutputPath`/`MSBuildExtensionsPath` fiasco. We definitely don't want that... right?

**Comment by nkolev92** [comment]
Pack is an outer build target. The OutputPath will always be without a target framework.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/9234

**Comment by Nirmal4G** [comment]
Not when targeting single Framework. Also `Platform` will be present even when we're multi-targeting.
