### ISSUE TITLE
Need nuget package priority for local debugging/testing

### ISSUE THREAD

**Issue by lovettchris** [NuGet/Home#9273]
## Cannot predictably get local debug bits using Nuget.config

The current spec says when there are multiple sources in your Nuget.config "the fastest one wins".  This results in unpredictable development experience.  For example, I'm developing a new nuget package, and I have a bunch of tests to test it.  But if my test projects want to reference my new local bits I tried this:
```
    <add key="Coyote" value="../Coyote/bin"/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
```

but it doesn't work.  It sill picks up the version on nuget.org, even if I nuke all local "packages" caches.

So what I really need is a way to tell Nuget to just for now, please really use the local bits if you can, thanks.  If this is by priority great, but perhaps you could be even smarter and do it based on file timestamps.

NuGet version; 5.4.0.6315

dotnet.exe --version: 3.1.101

VS version: 2019

OS version: win10 1903 (18362.657)

**Comment by donnie-msft** [comment]
Are you incrementing your version? NuGet uniquely identified packages by their identifier and version. This is by design and is documented in https://docs.microsoft.com/en-us/nuget/concepts/package-versioning.

Secondly, you can disable package sources so that Restore use them. In your case, disable NuGet.org by following the instructions in https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources.

**Comment by lovettchris** [comment]
Thanks for your ideas.  I cannot disable NuGet.org because there's lots of other packages that need to come from there.    I could rev the version, but it's a hassle to do that, since I would need to update all my test projects to that version and so on.  But since this is the only thing that works, updating the version of my local package is the only solution right now.

**Comment by nkolev92** [comment]
Hey @lovettchris 
Thanks for filing this issue. 

We are tracking the overall story in https://github.com/NuGet/Home/issues/6579
