### ISSUE TITLE
nuget pack for an sdk style csproj that has a package ref does not create a package that lists that ref as a dependency

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#9276]
## Details about Problem

Nuget pack task in devops build pipeline

NuGet version (x.x.x.xxx): 4.9.4

netfx461

Worked before? If so, with which NuGet version: IDK

## Detailed repro steps so we can see the same problem

I have a netfx461 project (call it  "P") that has nuget package ("NP") installed into it as a package reference. The project format is an SDK style format and uses package reference as the nuget style.

A devops build pipeline  has a nuget pack task that packs the csproj.

The package ("PP") that is created is packed correctly except that there is no mention of NP anywhere in it as a dependency. 

If I consume that package in a program it does not install NP as well, though it means that there will be compilation failures if the code from PP is used in the project. 

I expect that the dependency NP will be listed in PP.

**Comment by ranax404** [comment]
I had the same problem and changed my migrated SDK style projects to "dotnet pack .." instead of "nuget pack ..".

**Comment by StingyJack** [comment]
Yeah, well, `dotnet` isnt going to be an option for me in this case (netfx project). I also resent the entire `dotnet` wrapping of existing tools. In this case it was time spent doing something that took away the time needed to clear the path for, or to actually compose and run regression tests for `nuget pack`. Sometime before I had to lose productivity over this.

I nuspec things all the time as a matter of habit. This was a library that I had to update that was already using the csproj build so I figured I'd let it roll. Turns out the package has been getting created without the correct dependency for some time before I nuspec-ed it..

**Comment by AraHaan** [comment]
actually netfx projects using sdk style projects have no issues with the ``dotnet`` variant of commands. In this case like suggested above the solution is to instead use ``dotnet pack``. I even used it despite targeting ``net48`` or ``net472``, etc. It's much nicer and allows me to have no issues even if I decided to go with ``net4?`` or ``netcoreapp3.0``, ``netcoreapp3.1`` being the project's only targets because of winforms usage. The only issues I get with ``dotnet`` are when it tries to build and there are resources that are non-strings referenced in the ``*.resx`` files in which case I have MSBuild build them and then tell ``dotnet pack`` to pack without building.

**Comment by StingyJack** [comment]
Being able to use dotnet.exe does not release the responsibility of nuget pack from operating correctly.

**Comment by nkolev92** [comment]
As mentioned, the recommended approach is to use dotnet pack or msbuild /t:pack. 

Duplicate of https://github.com/NuGet/Home/issues/4491.
