### ISSUE TITLE
RestoreTaskEx swallows errors

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#9282]
When calling restore on a project with a recent SDK that contains the `RestoreTaskEx` but is missing the `NuGet.Build.Tasks.Console` executable, no failure is logged and no error is thrown.

```
C:\git\runtime4\tools-local\tasks\installer.tasks>dotnet restore /p:RestoreUseStaticGraphEvaluation=true

Microsoft (R) Build Engine version 16.6.0-preview-20105-01+5d872c945 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


C:\git\runtime4\tools-local\tasks\installer.tasks>
```

cc @nkolev92 @jeffkl

**Comment by nkolev92** [comment]
I understand your scenario better now.
Probably the outcome of this would be a no-op as the RestoreEx targets are now in a different package. 
It probably won't hurt to add a check and fail though.

**Comment by nkolev92** [comment]
I think this issue is a chicken or egg problem. 

The feature is not enabled because the assembly is not there, we don't know about the feature because the assembly is not there. 

I understand that it can be painful, unfortunately there's no value to adding this warning/error now. 
Adding this error in 3.1.300 will provide no value because 3.1.300 will always have the assembly. 

Given that I'm closing this as won't fix.
