### ISSUE TITLE
PackageReference NU1604 error handling is different across VS and command line (Restore & Package Manager UI)

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9289]
Specifically if a PackageReference version is a property and that property is not set. 
* On the commandline the customer will get NU1604 and a restore.
* In VS, the whole operation fails. 

Worth clarifying in both SDK and non-SDK cases. 

See internal thread `RE: NuGet Package Manager does not work in VS`

**Comment by nkolev92** [comment]
Specifically when something "goes wrong" with the input in the project file, we need ensure the experience is actionable. 

In restore scenarios, that means a clear message indicating which package reference from which project is missing. 
In Package Manager UI scenarios, that means a clear message indicating which package reference id has a missing version. 

If you are a customer hitting this issue, consider running a command line restore. It will contain more actionable information.

**Comment by nkolev92** [comment]
Another specific scenario in https://github.com/NuGet/Home/issues/9423 raised @cristinamanum. 

Adding a CPVM label to track the scenario too.

**Comment by AmadeusW** [comment]
Just wanted to say that this was happening in one of DevDiv's repos for months and engineers had no idea what's going on. This issue prevented Test Explorer from working correctly, so we ran tests from command line. We had to add Debugger.Launch to the test code in order to be able to debug 🤦‍♂️. That's all because the error message provides no useful information.

**Comment by donnie-msft** [comment]
I'm working on an improvement where I pass the "Additional Messages" from Restore to the UI.
Related: https://developercommunity2.visualstudio.com/t/Nuget-integration-is-broken/1291549
