### ISSUE TITLE
PackageReferences put ref instead of lib assemblies in the BuiltProjectOutputGroupDependencies output group used by VS installer projects

### ISSUE THREAD

**Issue by MSLukeWest** [NuGet/Home#9310]
NuGet product used: VS UI

NuGet version: 5.6.0.6489

VS version (if appropriate): 16.5

OS version: 19h1

Worked before? If so, with which NuGet version: Never worked with PackageRef, still works with Package.json

## Detailed repro steps so we can see the same problem

1)	Create a .NET framework C# console app
2)	Manage Nuget packages, add latest System.ValueTuple (4.5.0)
3)	Right click on packages.config in SE, select "Migrate packages.config to PackageReference …" (Note: No repro if you use packages.config)
4)	Add a setup project that references the primary output of the console app and build (Requires VS extension: https://marketplace.visualstudio.com/items?itemName=visualstudioclient.MicrosoftVisualStudio2017InstallerProjects)
5)	Install the generated msi

Expected: It installs the System.ValueTuple assembly from the “lib” directory
Actual: It installs the assembly from the “ref” directory, causing runtime failures

The output group BuiltProjectOutputGroupDependencies is incorrectly populated when using a package reference to consume nuget packages that have both ref and lib versions of their assemblies.  Some inital inspection of the build logs shows that with packages.config the lib version is added to the "Reference" item group, which eventually makes its way into a ReferencePath item, which gets added to BuiltProjectOutputGroupDependencies.

With PackageReference, ResolveNuGetPackageAssets adds:
- lib to ReferenceCopyLocalPaths
- ref to Reference

So even though the lib version makes it to the bin folder through ReferenceCopyLocalPaths, the ref version is what gets added to BuiltProjectOutputGroupDependencies.

This has been reported by a few different customers, here’s a link to one of the feedback tickets: https://developercommunity.visualstudio.com/content/problem/810090/visual-studio-installer-projects-extensions-incorr.html.  As we mentioned in that ticket, there’s a couple potential workarounds, but neither of them are very reliable.

**Comment by yirkha** [comment]
FYI I think this is not an issue with NuGet but rather the Visual Studio Installer Extensions SDK.

Their MSBuild integration uses `BuiltProjectOutputGroupDependencies` in a way that should not be done – see this issue for details: https://github.com/microsoft/msbuild/issues/3069

I've provided a workaround in https://github.com/Azure/azure-sdk-for-net/issues/3699#issuecomment-612306965 which might potentially work similarly in this case too.

**Comment by MSLukeWest** [comment]
Thanks @yirkha.  I'm adding the work around here for easier access.  Putting this at the end of your csproj file will get around this issue when using installer projects (requires a restart of VS):

 
	<Target
		Name="BuiltProjectOutputGroupDependencies"
		DependsOnTargets="$(BuiltProjectOutputGroupDependenciesDependsOn)"
		Returns="@(BuiltProjectOutputGroupDependency)">
		<ItemGroup>
			<BuiltProjectOutputGroupDependency Include="@(ReferenceCopyLocalPaths->'%(FullPath)');
                                                  @(ReferenceDependencyPaths->'%(FullPath)');
                                                  @(NativeReferenceFile->'%(FullPath)');
                                                  @(_DeploymentLooseManifestFile->'%(FullPath)');
                                                  @(ResolvedIsolatedComModules->'%(FullPath)')"/>
		</ItemGroup>
	</Target>

**Comment by nkolev92** [comment]
Closing as per the previous comments. 
This is not something in NuGet Client's control.

**Comment by xxl-cc** [comment]
i have same problem。

**Comment by mbihler** [comment]
Thanks @yirkha. Your workaround works with my setup project. 
But because COM wrapper assemblies were missing in generated msi, I had to add this to the include list:
`@(ReferenceComWrappersToCopyLocal->'%(FullPath)')`

**Comment by dbeavon** [comment]
@yirkha @MSLukeWest
Thanks for the suggested workaround.

It works well for simple installer packages.
But we are having subtle issues with this solution for more complex projects.
There are files being sent to the setup package as an unintended side-effect, like configs and xml that I don't need.
(these auxiliary files were mentioned here as well: https://github.com/Azure/azure-sdk-for-net/issues/3699#issuecomment-612306965 ).

It is particularly troublesome when config files are mishandled, given their importance.


I can share an example where I tried to prevent the “.config” files from being introduced by way of “Content Files”.  Yet they come along despite that “Exclude Filter”.  

First I set up the exclude filter like so:

![image](https://github.com/user-attachments/assets/4e1563ea-94f3-442b-bfd7-41c547ac38be)

... but the end result is that a bunch of configs get transferred into the package regardless.  (I think the "Exclude Filter" option may be too fragile to overcome this sort of customization in the csproj.  The end result is that **two variations** of the config are targeting the “Application Folder”, and unfortunately the **wrong** config will "win".)

Below are two variations of the config, one from "Content Files", and one provided manually.

![image](https://github.com/user-attachments/assets/4e0104ea-90dc-4362-bd16-20154fb5c39f)

I am going back to using packages.config instead of PackageReference for now.  Maybe we can revisit in another year or so.
