### ISSUE TITLE
No error occurred after packing and installing a package with an invalid .txt format icon

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9311]
## Details about Problem
NuGet version: NuGet Client Dev\5.6.0.6509
VS Version: Master\29916.153
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a Class Library (.NET Framework 4.8) in VS and build the solution.
2.	In the Developer Command Prompt for VS, create a nuspec file by executing command “nuget spec”
3.	Make an invalid image file (size limited to 1 MB with a .txt format) and locate in the package. Note: invalid means size limited to 1 MB with PNG/JPEG format and 128x128 resolution
4.	Add following to nuspec file
```
<package>
  <metadata>
    ...
    <icon>images\icon.txt</icon>
    ...
  </metadata>
  <files>
    ...
    <file src="C:\Users\v-luzh\source\repos\Package1\Package1\icon.txt" target="images\" />
    ...
  </files>
</package>
```
5. Pack the package to local path by executing command “nuget pack”.

## Expected
There should be an error to prevent packing a package with a text format icon in step 5.
## Actual
No error occurred after packing a package with a text format icon in step 5.
## Note
It's not a regression.

**Comment by v-luzh** [comment]
This issue will not make VS crashed on  VS Main\30515.165 with implicit NuGet Client Dev\5.8.0.6842. But it should not be packed and installed successfully since the icon is created with invalid format. Update the title.

**Comment by dominoFire** [comment]
Validation can be added to only accept .png, .jpeg, .jpg images; very similar to license validation

**Comment by dominoFire** [comment]
Filename extension validation mitigates the problem but it doesn't fully solve it.

One way to validate icon image file is to fully read it with WPF and verify if it successfully loads. But, we would need to take a dependency on WPF.

An alternative is to only check magic numbers for JPEG and PNG images at the beginning of the file. This is prone to errors because there's a myriad of JPEG and PNG file format variations.
