### ISSUE TITLE
Add an information message on restore to inform the CPVM users that the feature is in preview

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9340]
## Details about Problem

This is a new feature request. 
Add an information message on restore to inform the CPVM users that the feature is in preview.

**Comment by ransagy** [comment]
I know this issue is a bit old; let me know if you want me to open a new one, but..

Since CPVM is getting some more attention now - Is it possible to make this a once-per-operation message rather than once per project? or even better IMO, make it suppressable, like the ".NET Core Preview SDK" messages?

This adds A LOT of spam to a build when using CPVM.
