### ISSUE TITLE
update-package doesn't show error when source is unreachable

### ISSUE THREAD

**Issue by NikolaR** [NuGet/Home#935]
update-package command in NuGet package manager does not show an error when NuGet repository is unreachable.

I've tried to update, but due to internal network issues connection to nuget.org could not be made.
Command only showed following output:
> No updates available for 'convenience' in project 'XYZ'.

Only when I've tried to uninstall and then install package I noticed the connectivity issue.

**Comment by yishaigalatzer** [comment]
What version of visual studio and NuGet are you using?

**Comment by NikolaR** [comment]
Uh, sorry about that.
It's VS 2013 and NuGet 2.8.5.
![2015-07-13_18-35-10](https://cloud.githubusercontent.com/assets/1903108/8654934/ff2c6044-298d-11e5-9c5a-6f0639c57745.png)

**Comment by yishaigalatzer** [comment]
This is not something we plan to add errors for, we might add a warning.

**Comment by NikolaR** [comment]
Okay. Severity is less important. Just changing the message is fine. It's misleading now in that it makes you believe that there is no newer published package on NuGet.org

**Comment by yishaigalatzer** [comment]
This is now fixed in NuGet 3.3

`
PM> update-package
Attempting to gather dependencies information for multiple packages with respect to project 'ConsoleApplication25', targeting '.NETFramework,Version=v4.5.2'
update-package : The remote server returned an error: (404) Not Found.
At line:1 char:1
- update-package
- ~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

PM> 

```
```
