### ISSUE TITLE
Warnings about unknown compatibility profile when package doesn't exist.

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#938]
Start with the following

```
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0"
  },
  "frameworks": {
    "dotnet": {}
  }
}
```

Add a package reference to a package that doesn't exist:

```
    "Garbageskldfjasjkd": "4.0.10"
```

Observe the following in the error list:

| Severity | Code | Description | Project | File | Line |
| --- | --- | --- | --- | --- | --- |
| Error |  | Unable to resolve Garbageskldfjasjkd (≥ 4.0.10) for .NETPlatform,Version=v5.0. |  |  | 0 |
| Warning |  | Unknown Compatibility Profile: net46.app |  |  | 0 |
| Warning |  | Unknown Compatibility Profile: uwp.10.0.app |  |  | 0 |
| Warning |  | Unknown Compatibility Profile: dnxcore50.app |  |  | 0 |
| Error |  | NuGet Package restore failed for project ClassLibrary1 for 'Garbageskldfjasjkd [4.0.10, )'. |  |  | 0 |

**Comment by anurse** [comment]
This happens because we do the restore and compat check separately (so we continue with the compat check even when the restore fails). As a result, the restore never got to the point of loading the runtime graphs since we bailed early.

There are a few potential fixes that can definitely wait for 3.2.0 in my mind:

* Cancel the compat check if restore fails. Though I vaguely remember we had a reason for doing it even when restore fails...
* Ensure that even when restore fails, the runtime graph is loaded for all the packages that **were** successfully restored.

**Comment by ericstj** [comment]
The latter seems the better option.  We want the compat check so that folks aren't in a wack-a-mole-rebuild situation. /cc @pilchie for the timing question since this impacts PCL.

**Comment by anurse** [comment]
That's part of why I would suggest we defer to 3.2.0 if possible. Given the remaining time, I'd be concerned about implementing the second option for 3.1.0. It means re-examining a whole bunch of code that currently expects to only ever run with a completely resolved graph.

**Comment by Pilchie** [comment]
Yes, I think defer to 3.2 is the right approach.  The warnings are an annoyance, but at least the useful information is there.

**Comment by yishaigalatzer** [comment]
this might go away if we remove guard rails completely, @anurse ?

**Comment by rohit21agrawal** [comment]
our errors and warnings work in nuget 4.x has improved this experience
