### ISSUE TITLE
Investigate accessibility bugs reported by users

### ISSUE THREAD

**Issue by aortiz-msft** [NuGet/Home#9393]

**Comment by donnie-msft** [comment]
This issue tracked the investigation of the following reports:

#### Sluggishness: NonVisualDesktopAccess sluggish when navigating the list of packages (847917)

- Filed a bug against NVDA reporting this behavior https://github.com/nvaccess/nvda/issues/11109 

#### NonVisualDesktopAccess: Screen Reader only announcing package name when arrowing through the list (847919)

- Drill-in with CapsLock + arrow keys allow access to these fields.

#### NonVisualDesktopAccess - Package Descriptions not being read by screen readers (847927)

- Drill-in with CapsLock + arrow keys allow access to these fields.

#### NonVisualDesktopAccess - Checkbox for selecting projects to install to isn't being read by screen reader (847922)
Moving this to https://github.com/NuGet/Home/issues/9578

- AI reports no errors here. I have to drill-in to the checkbox in order to hear its checked state. I have not been able to find guidance on whether this is acceptable behavior. 

- I would expect to hear "Checkbox unchecked/checked" when selecting the grid row. We have the same behavior on the Updates Tab package checkboxes.

**Comment by rrelyea** [comment]
Marking as duplicate..since their was no fix, but several related issues spun out of this.

**Comment by LeonarddeR** [comment]
> Marking as duplicate..since their was no fix, but several related issues spun out of this.

Could you please share the related issues? I'm a NVDA developer as well as a daily Visual Studio user, so happy to collaborate. In fact, I already started to look into the sluggishness, see https://github.com/nvaccess/nvda/pull/11214
