### ISSUE TITLE
Source link missing symbols

### ISSUE THREAD

**Issue by babuch02** [NuGet/Home#9407]
Hi,

Am new to Nuget Package Explorer. i tried to package my dll using utube videos but am getting some error as missing symbols at Health. please advise what i done wrong here

attached the Screenshot for your reference

Thanks.
![Nuget Error](https://user-images.githubusercontent.com/62982614/78778049-3d714c00-79b8-11ea-8a62-1046684f2b05.PNG)

**Comment by dominoFire** [comment]
@babuch02 Those are not errors, just health checks that makes the page a good quality one

- Source Link: More info [here](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects)
- Deterministic is a feature to produce the same package using the exact same package inputs. Deterministic pack is disabled [since 5.3](https://github.com/NuGet/Home/issues/8599).

Check out this NuGet videos: https://channel9.msdn.com/Series/NuGet-101

I will close the issue since it is not a NuGet bug. If you have more comments, please feel free to reply.
