### ISSUE TITLE
PoM/BoM Project/Bill of Materials

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#9408]
_From @peni4142 on Wednesday, April 8, 2020 10:50:25 AM_

I am missing a Project of Materials!

What I expect that to be.

If you include that thing(can even be one file), you are only allowed to include NugetPackages from that List, but you don't have to.

The benefit I expect from that is nothing less than to solve the DLL-hell.

You can define one in your company, including that in every project and you all have the same DLLs/NugetPackages.

### case studies:
- **Update/add/delete a Package** Maybe you have it in a git project. You make a Pull-Request, your buddies can agree or disagree. On agree, everyone has to update.

- **You get to know a Package is corrupt** Just delete it and you are sure, no one is using that anymore

_Copied from original issue: microsoft/msbuild#5251_

**Comment by rainersigwald** [comment]
_From @rainersigwald on Wednesday, April 8, 2020 2:21:42 PM_

This sounds like a NuGet request that may already be satisfied by some features there. I'll move it to the NuGet repo.

**Comment by peni4142** [comment]
Wich feature?

Edit: Maybe I have to mention that the Bill of Materials also specify the version

**Comment by dominoFire** [comment]
@peni4142 I think you're referring at [Maven Bill of Materials](https://www.bing.com/search?q=maven+bill+of+materials).

We have a similar feature in NuGet still in development, called [Central Package Version Management](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions). Note that you can define all packages in one central files but, packages are not installed by default.

In the meantime, you can try MSBuild Centrally Managed Package versions, documented [here](https://github.com/Microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions).

I will close the issue since it doesn't look like a bug. If you have more questions, feel free to reply.

**Comment by peni4142** [comment]
Hui... that is complicated... again I think I am doing something wrong.

I can neither install/add in the old project format nor in the new Microsoft.Build.CentralPackageVersions

At least in the new project format, I can use it.
But if I use the Nuget Package Manager to add a package which is defined in the Packages.props, it is adding a Version. So after adding the package via Nuget Package Manager, I have to open the .csproj file and delete the version.

It is not such a big deal but feels shitty.

In the old project (greetings from WSPs) it does not work at all.

An easy lookup list, a white list, would have done the job.
