### ISSUE TITLE
nuget server as npm proxy

### ISSUE THREAD

**Issue by prabirshrestha** [NuGet/Home#951]
Lot of webapps these days use webpack or browserify and are meant to work well with npm package. In the corporate world we don't have the luxury to download files from public websites including nuget.org or npmjs.org. This means I would have to host a nuget server and a npmjs server. Hosting a server includes maintenance cost (For example: npmjs server could be using a couhdb. Or I can pick some random npmjs server that can disappear anytime in the future.)

What if I nuget server also allowed storing npm packages (it could even be .nupkg).

Then I can use my npm and point to the nuget server.

```bash
npm install --registry http://nuget.org jquery
```

I could also use nuget to install the same package.

```bash
nuget install jquery
```

Same package internally but talking to different tools. We can think of it content-negotiation.

Nuget could also add publishing npm packages. Then we can get internal private npm packages for free :)

This could also solve old nuget packages problem for javascript libraries.

https://github.com/harvesthq/chosen/search?q=nuget&type=Issues&utf8=%E2%9C%93

https://twitter.com/PrabirShrestha/status/621375678194126848

Currently every time I need a new version of a javascript library I need to mail/tweet the nuget owner since most js libraries don't want to publish to nuget directly.

**Comment by prabirshrestha** [comment]
Here is a sample serve. It currently implements only `npm install`

https://www.npmjs.com/package/npm-server
https://github.com/stagas/npm-server

**Comment by csharpfritz** [comment]
ProGet hosts both types of repositories:  http://inedo.com/proget/overview

We have no plans to host npm packages on the NuGet gallery

**Comment by yishaigalatzer** [comment]
Although this sounds like a reasonable idea, this is not something we want to address on nuget.org in the near future. Our focus is on server scalability, uptime and serviceability. For now at least we want to keep our focus where it matters to the bulk of nuget.org users.
Not to say we can't revisit this in the future.

The suggestion for javascript libraries going forward is to use bower directly, visual studio 2015 is adding bower tools exactly for this reason.

Thanks for the suggestion and time taken looking into it. Even though this issue is closed, we are going to continue to get notifications as it gets updated. Feel free to comment further

**Comment by maartenba** [comment]
Www.myget.org also does npm and bower - plus proxying

**Comment by prabirshrestha** [comment]
Another interesting product:

>ProGet supports not only in-house packages, but a growing list of external repositories including NuGet, npm, Bower, Maven, RubyGem, Docker, PowerShell, and more! ProGet serves as your organization's central repository, allowing you to store all your important assets in one convenient place, with security in mind

https://inedo.com/proget/details#repository
