### ISSUE TITLE
`dotnet add package -s sourcename` doesn't work. `-s sourceurl` does.

### ISSUE THREAD

**Issue by Thraka** [NuGet/Home#9511]
_From @varunmankal on Friday, May 1, 2020 10:25:30 PM_

I have added my private source to NuGet.config file. when I run `dotnet nuget list source` it displays the following sources:
* nuget.org
* myprivate

Now, If I want to install a package from myprivate source then I try to run the following command:
`dotnet add package <packageName> -s myprivate`
then it returns an error saying the source `myprivate` not found.
If I run the same command using the myprivate URL instead of source name then it works.

How can I use source name instead of URL in the above command.

**Target framework**

- [3.1.2 ] .NET Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package#options)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

_Copied from original issue: dotnet/docs#18216_

**Comment by Thraka** [comment]
_From @Thraka on Monday, May 4, 2020 6:19:17 PM_

I don't believe this is the way it operates. I'm moving your issue to the nuget repository.

**Comment by kartheekp-ms** [comment]
@Thraka - By design, `dotnet add package` command performs a `dotnet restore` after merging the package sources from `dgspec`  and `nuget.config` files. The unique identifier used during this process is `source URI` but not `source name`. [example 3 in doc to `Add a package using a specific NuGet source`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package#examples)

I think `dotnet add package <packagename> -s myprivate` command worked as follows.
- package is added to the project (if compatible) irrespective of what ever value passed for `-s` parameter because `myprivate` feed is already added to the `nuget.config` file.  
- command log may contain an additional error message saying `error: The local source 'PATH TO FOLDER\myprivate' doesn't exist.`

Please let us know if you are experiencing different behavior or have any additional questions so that we can plan next steps accordingly.

**Comment by Thraka** [comment]
Tagging @varunmankal the creator of this issue

@tdykstra I think we should clarify the docs on this command to indicate that it's the NuGet source URI.
