### ISSUE TITLE
Reference a subset of the dlls from a package

### ISSUE THREAD

**Issue by cmakara** [NuGet/Home#957]
If I add a reference to a nuget package through the Visual Studio extension to a project, all the dlls in the package gets to be referenced in the project. 
Regardless I manually removed the unnecessary references, the update through the Nuget package manager inserted all dlls to the project.
It would be nice to have a way to either declare a set of dlls to reference, or in case of an update just refresh the references to the already referenced dlls and not include the others?

**Comment by davidfowl** [comment]
Only the package author can do this not the consumer. Why would you ever need this? Presumably the reason the package has multiple dlls is because all are needed. Maybe the package you're using is authored poorly?

**Comment by cmakara** [comment]
Thanks for the reply.
We are using nuget packages for distributing subsets of internally developed products.
The one i'm currently working with contains 14 dlls from a product, which against we are developing a separate plugin in a vs solution. This solution has multiple product and test projects and every product has reference to a few dlls from this package but not all, usually to 2-3 and 1-2 overlaps.

**Comment by davidfowl** [comment]
The package needs to be split into multiple packages

**Comment by yishaigalatzer** [comment]
David is right. Split the package, the guidance is to have a single dll per package (typically). You can still make the main package have one or no dll, and make it reference dependent packages with the others. Then you can choose to install a subset of the packages.

See https://www.nuget.org/packages/Microsoft.AspNet.WebApi.WebHost/ for an example of a package with one dll bringing in dependencies developed by the same team.

**Comment by msfcolombo** [comment]
This makes me wonder - why don't we publish DLLs directly instead of Nuget packages?

**Comment by bananacles** [comment]
@msfcolombo The NuGet package is just a renamed .zip, when you publish a package you _are_ publishing the dll. NuGet does other nice things that make life easier.

**Comment by msfcolombo** [comment]
@bananacles The question is more like "Since each Nuget is supposed to have a single DLL and the DLL contains metadata, why can't we simply publish the DLL? i.e. Why we have to pack it inside a zip file and call it a Nuget?"

A similar question but from the other point of view, would be "Why an assembly cannot reference a Nuget package directly? i.e. Why isn't the runtime smart enough to unpack the assembly from the referenced Nuget, store it in a cached location, and hide the fact that assemblies and Nugets are different things?"

This is just food for thought in the trend to simplify things. I know the answer to both questions. Essentially the assembly is not complete - it lacks a PDB that might be useful for developers, the `.text` is not compressed, meaning certain DLLs may take more space than a Nuget (although that is rare), and there are other limitations. The assembly dependencies are not 1-1 mapping to Nuget dependencies, and it doesn't use SemVer, etc.

IMHO, assemblies should have been designed for publication, distribution, portability AND runtime execution, and the fact they were not implies the need of Nuget. Hopefully one day someone will come with an alternate assembly representation that bridges the gap.
