### ISSUE TITLE
[Test Failure] ‘An error occur while attempting to open NuGet’ appeared after reopening the solution in the Experimental instance

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9588]
## Details about Problem
NuGet version: NuGet Client Dev\5.6.0.6489
VS Version: D16.6\29924.181
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. Open Experimental VS Int Preview.
2. Create a SDK project [e.g. Console App (.NET Core 3.1)].
3. Open the solution/project PM UI.
4. Close VS with the PM UI left open.
5. Reopen Experimental VS and the same Solution.
## Expected
‘An error occur while attempting to open NuGet’ appeared as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/82548009-3596f100-9b8d-11ea-82fa-3b25df5394b7.png)
## Note
1. Not repro on 16.5 GA (D16.5\29905.175)- implicit NuGet 5.5.0.6473.
2. Not repro on 16.6 Preview5 (D16.6\30028.174) – implicit NuGet 5.6.0.6591.
3. Not repro on 16.7 Preview1 (D16.7\30114.128) – implicit NuGet 5.7.0.6592.

**Comment by donnie-msft** [comment]
This Issue was for my request to re-verify this bug against that I had already fixed: https://github.com/NuGet/Home/issues/9239

I encountered a similar PMUI error on Experimental Instance (only) - Version 16.7.0 Preview 2.0 [30118.8.master], but @v-luzh was unable to repro on that version.

I will leave this open for now in case I or others find another repro...

**Comment by v-luzh** [comment]
@donnie-msft We didn't repro this issue on VS Master\30229.148 + NuGet Client Dev\5.7.0.6677. The project PM UI and solution PM UI would not be open by default in step 5 even we closed VS with the two PM UI left open in step 4.
