### ISSUE TITLE
ManagedCodeConventions resolves MsBuild files in the root of build directory as NET00 tfm

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#965]
ManagedCodeConventions allows target and prop files to exist at the root of `build` directory. However, it assumes the tfm for these files is '.NetFramework Version = 0.0`. Consequently these files do not get installed in projects that are incompatible with the .net tfm (such as UAP)

**Comment by pranavkm** [comment]
The right fix for this would be to resolve the tfm as `Any` framework. cc @davidfowl  @anurse

**Comment by davidfowl** [comment]
I wouldn't fix this generally. Only for build items

**Comment by pranavkm** [comment]
Yup. Lib items should continue to be treated as `net00`

**Comment by analogrelay** [comment]
I would actually suggest moving to `build\any\...` for these, since the **optional** two-layer folder structure has been the reason NuGet has to update the server before packages can be uploaded for a new framework, even though the server doesn't really care. Isn't the idea of the Managed Code Conventions 2.0 to require a sub-folder, even if that sub-folder is just `any`?

**Comment by emgarten** [comment]
@anurse I think this fix was mainly to get old packages working again, not for the new any convention. We should support build/any/id.targets. 

Should we ignore TFM sub folders if files exist in the root, or should we ignore the root if tfm folders exist? It is messy to support both conventions, but I think we've already decided to do that here.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@26a6fa6cfc92f577e132d073e4a90ac3425cc8da
