### ISSUE TITLE
.NET 5.0 Visual Studio APIs

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9650]
Because of the addition of a platform component to .NET tfms since 5.0 (https://github.com/NuGet/NuGet.Client/pull/3339), any APIs relying on `FrameworkName` have become mostly incompatible with net5.0.

In particular, the VsFrameworkCompatibility APIs rely on these objects. We need to come up with guidance for customers who can't use the extensibility framework APIs to work around this.

We also need to figure out the impact of this change on folks who might be using this.

**Comment by zivkan** [comment]
APIs that use `NuGetFramework`:

```cs
public interface IVsFrameworkCompatibility
{
    IEnumerable<FrameworkName> GetNetStandardFrameworks();
    IEnumerable<FrameworkName> GetFrameworksSupportingNetStandard(FrameworkName frameworkName);
    FrameworkName GetNearest(FrameworkName targetFramework, IEnumerable<FrameworkName> frameworks);
}

public interface IVsFrameworkCompatibility2 : IVsFrameworkCompatibility
{
    FrameworkName GetNearest(
        FrameworkName targetFramework,
        IEnumerable<FrameworkName> fallbackTargetFrameworks,
        IEnumerable<FrameworkName> frameworks);
}

public interface IVsFrameworkParser
{
    FrameworkName ParseFrameworkName(string shortOrFullName);
    string GetShortFrameworkName(FrameworkName frameworkName);
}

public interface IPackage
{
    IEnumerable<FrameworkName> GetSupportedFrameworks();
}

public interface IPackageFile
{
    FrameworkName TargetFramework { get; }
}
```

My thoughts at this time is to deprecate `IVsFrameworkParser` and to add overloads (or something similar where the only difference is return type), to use `string`, rather than `FrameworkName`, with instructions that the value should be the full canonical value obtained from `TargetFrameworkMoniker`. I need to validate this property is created by the common props or CSharp targets for non-SDK projects.

From a quick search of usage, `ParseFrameworkName` is mostly used to find out if the TFI is `.NETCoreApp`, but components can query the project properties for `TargetFrameworkIdentifier`, they don't need to use our VS API to parse the framework. There is at least one usage of `GetShortFrameworkName`. It appears to be using it to determine the `bin\` or `obj\` subdirectory. However, the SDK itself uses `TargetFramework`, so once aliasing is implemented, using `GetShortFrameworkName` will return the wrong result. Therefore, it doesn't appear that `IVsFrameworkParser` should be needed by anyone.

The other APIs likely have useful use-cases, although I'm not so sure about `GetNetStandardFrameworks` and `GetFrameworksSupportingNetStandard`. I believe we should standardize on `TargetFrameworkMoniker`'s string representation. If `IPackage` and `IPackageFile` return the canonical TFM, and the API user gets the `TargetFrameworkMoniker` property from the project, `string` versions of `IVsFrameworkCompatibility` APIs should be suitable. I need to do more investigation to see how it's really used, find out why it's being used.
