### ISSUE TITLE
Save the order of NuGet Package Feeds in VS Options Dialog

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9653]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1062565/save-the-order-of-nuget-packag-feeds.html)._

---
You can add multiple Nuget-Feed-Sources with VisualStudio which is then save to "%AppData%\NuGet\NuGet.Config".
In VisualStudio you can change the order of that sources but the order is not saved into the config. After a VS restart the order has not changed.
Workaround: Editing the file manually.

---
#### Visual Studio Feedback System on 6/3/2020, 01:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
We've been wanting to remove the arrow keys from the options dialog. 
https://github.com/NuGet/Home/issues/8315

Starting with VS 2015, there's no such thing as a preference order of sources (project.json & PackageReference are pretty adamant about it). This is even more of a problem when you can account for the fact that NuGet configs are merged, so sources could be coming from different configs.

My vote would be to close this issue and add a comment about changing the persistence order in https://github.com/NuGet/Home/issues/7973. 

The problem with the current UI is that it's not obvious where the sources are defined. They could be defined in multiple configs and there's no way to express that. The UI redesign in #7973 covers that.

**Comment by donnie-msft** [comment]
8315 - not sure that we said we wanted to remove them. Why not make them change the order?
Lots of input for that here https://github.com/NuGet/Home/issues/3676
You can change the order in a config manually.

7973 - I would call this "a bulleted list of relatively broad UI config concepts". Do we have anything solidified, any mockups?

**Comment by nkolev92** [comment]
> not sure that we said we wanted to remove them.

I discussed with Karan about a year back. Regardless, he doesn't own it anymore so that's a moot point.

> Why not make them change the order?
Lots of input for that here #3676

2 reasons

#### Arrows as priority order

I want to call attention to the specific response the NuGet team gave in the issue you linked https://github.com/NuGet/Home/issues/3676#issuecomment-254570021. 
The customer interpreta priority that does not exist. The only source preference that's existed is packages.config, the selected source was treated as a primary source and that's the one that'd be use to obtain the package when necessary. 
That priority never manifest in the package source options dialog.

#### Arrows as persistence order

In this particular issue a customer wants the arrows to control the persistence order of the sources. So we have examples of 2 different customers misinterpreting the arrows. 
The complexity with this particular aspect is something I described in the above issue: 

> This is even more of a problem when you can account for the fact that NuGet configs are merged, so sources could be coming from different configs.

What happens when you `move` a source lower, in a range of sources defined in a different file. Do you move the declaration from one nuget.config file to another? Is that obvious to the customer? 

#### Wrapping it up

My conclusion from it all, the arrows add no obvious value to the topic and are ambigious. 
The current UI as is, does not provide sufficient enough detail to implement such a functionality. 

> 7973 - I would call this "a bulleted list of relatively broad UI config concepts". Do we have anything solidified, any mockups?

#7973 captures the requirements for a settings UI redesign. I've not seen any finalized mock-ups myself. That issue is not actively worked on. 

#### Incremental progress

Given the cascading behavior of NuGet.config, the current UI is obviously lacking and in need of a refresh. #7973 is used to track the requirements. 
Given the number of people that have been confused by the arrows, I think we should remove them. It's cheap to do and eliminates unnecessary confusion.

**Comment by nkolev92** [comment]
Either way slice it, the feedback here is the same as https://github.com/NuGet/Home/issues/8315, closing it as dup of that.
