### ISSUE TITLE
Feature request: validate TFMs

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#969]
I think that few people know which lib\TFM folder to put their binaries in.

I would like the NuGet packaging tools to look through the lib\TFM folders, look for DLLs inside them, read the TargetFrameworkAssembly attributes in there, and embody some expert-knowledge about whether the TFM folder is valid for this TargetFrameworkAssembly. That'd catch a lot of errors.

(I understand that the NuGet team might not wish to do this, if they want NuGet to remain "pure" and agnostic about what goes where. But my answer is that (1) this is a pressing user confusion point which should be addressed in tooling, and (2) unless we can find a better place in tooling to perform the check then NuGet-packagingis where it should go).

**Comment by davidfowl** [comment]
There are different ways to solve this problem. The bigger reason that there's user error today is because building a project is decoupled from building a package. I'd argue that the better fix would be to couple the 2 things when the desired outcome is a package. This keeps the nuget tools free from digging into the assembly bits after the fact to figure out if the user did something right (which is what the xproj is trying to accomplish)

**Comment by nkolev92** [comment]
We've done a lot of pack improvements in this area, and we're currently adding more pack validation to make sure authors create valid packages. 

As such, I'll close this issue.
