### ISSUE TITLE
Investigate the deduplication of NuGetVersion/VersionRange and other read-only object in PackageMetadataResource & SearchResource

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9731]
Use the MetadataReferenceCache to cache strings, NuGetVersion, VersionRange and other types that are read-only.

**Comment by nkolev92** [comment]
* Check that the search resource is getting cached. 
* MEasure with cortana, Nuget.sln on the consolidate tab.

**Comment by nkolev92** [comment]
@erdembayar When I say search resource, I am referring to https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResource.cs and in particular the following resource: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs

**Comment by erdembayar** [comment]
I'm closing the ticket because we're not seeing enough gain and decided to close for now. Because purging/pruning from cache is very hard at this moment.

I tested it with large solution like "Cortona", but for small solutions benefit will be almost nothing. Overall saving with my change just 3% because not many intertwined packages on  `PackageMetadataResourceV3` path, unlike dependency graph where they might share same packages somewhere on dependency graph between many projects. 

On `PackageMetadataResourceV3` code path saving on `NugetVersion` was about 84% and for `VersionRange` was about 99%(because there was single value `[*, )`). Of course all of this small memory saving comes with runtime cost delay of working with dictionary.

![image](https://user-images.githubusercontent.com/8766776/87071064-8b236d80-c1ce-11ea-8be0-a4cad5846dcc.png)

I didn't add any actual benchmarking because all this memory saving and extra runtime depends of nature of solution, depth of how projects and packages depend each other. Maybe we don't save any memory even solution has 100s projects in it if they don't share same packages.  So doing any benchmarking on imaginary solution is pretty much useless.

Since this is investigation if you think benefit doesn't outweigh cost then no need to merge this PR.
Please let me know.

**Update** (7/16/2020)
I implemented change suggested by Andy and moved cache to SourceRepository and even added caching to `PackageSearchResourceV3 ` path in addition to previous path `PackageMetadataResourceV3`. Also I merged to `dev` to see changes after PM UI closed (other effort [#9757](https://github.com/NuGet/Home/issues/9757)).  
Still gain is negligible for large solution like `Cortona` while `PM UI` is still `open`. Even bit negative on memory wise because dictionary itself has overhead. 

Because one hand we're deduplicating thing on PM UI but on other hand we keep every unique thing in another bucket (cache) even that thing maybe disposed, so result is we're removing water from one bucket but filling other bucket.
In the end if we combine that 2 buckets end result is still same. Caveat is while we doing processing we check through all available packages with all possible version then every time we see unique item then we add to cache it stays there even though that item is already disposed after some processing.

**_Technically what it means is our dictionary itself need pruning time to time. I am not sure it's good idea and if we can do it effectively and I see it as complicated._**

**Case 1:  PM UI Consolidate tab only.**

Here comparison `without any caching` vs `with caching` only open PM UI Consolidate tab, not other tabs. 
Please note all memory dumping made after force GCed to get real picture of what is still in memory.
Even we deduplicated some now we have MetadataReferenceCache with 21258 bytes retained because it has dictionaries and dictionaries have overhead cost(pointer to actual item) for every item in it. We're bothered by this fine details because our gain was almost nothing and on edge, otherwise we don't need to bother such details. 

![image](https://user-images.githubusercontent.com/8766776/87838986-b7ce2980-c84d-11ea-9c38-5dc798b7c14d.png)

**Case 2:   PM UI Browse tab only.**

![image](https://user-images.githubusercontent.com/8766776/87839617-7428ef00-c850-11ea-9b9f-1ad9a2df0516.png)

**Case 3:   PM UI Browse tab. Search for term "serial" then scroll down for 3 pages.**

![image](https://user-images.githubusercontent.com/8766776/87839653-ad615f00-c850-11ea-83cf-a58a2dc40bd6.png)

Again if there were any real gain then we should not be bothered by this fine details, I love to present some benefits with what I did but there isn't unfortunately.
Since this is investigation I believe this cache implementation PR doesn't outweigh cost so I propose to not continue anymore.  I believe my other effort [#9757](https://github.com/NuGet/Home/issues/9757) was good enough.
Please let me know.

For Andy's concern I created separate bug task for SourceRepository memory leak [#9814](https://github.com/NuGet/Home/issues/9814).

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
Would you like me give another try for this issue? My understanding of NuGet better than 1 year before right after I joined.

**Comment by nkolev92** [comment]
@erdembayar 

I'll open a different issue with a different focus and link this one.
String deduping should be a lot more effective.

@aortiz-msft can delegate as needed :D
