### ISSUE TITLE
Multiple VS versions use nuget to search for packages with different results

### ISSUE THREAD

**Issue by hueifeng** [NuGet/Home#9739]
## Description

I searched the package using vs2015 nuget management tool and found that the results returned by vs2019 are different. Some preview packages are missing.

## Reproduce

1、Search for `System.Drawing.Common` through the nuget management tool.

vs2015
![image](https://user-images.githubusercontent.com/34702552/86204785-e932ce00-bb9a-11ea-9614-11f70be7ea61.png)

vs2019

![image](https://user-images.githubusercontent.com/34702552/86204860-2303d480-bb9b-11ea-9d87-82462fd0a298.png)

It can be seen from the picture that he is missing the 4.6 preview version.

## Versions

nuget source : `https://api.nuget.org/v3/index.json`

Microsoft Visual Studio Enterprise 2019
Version 16.6.2
Nuget 5.6.0

---

Microsoft Visual Studio Community 2015
Version 14.0.25.431.01 Update 3
Nuget 3.4.4

**Comment by joelverhagen** [comment]
The reason you are seeing a difference in version list is because Visual Studio 2015 does not support the SemVer 2.0.0 packages protocol. In other words, SemVer 2.0.0 packages (such as version `4.6.0-preview9.19421.4`) will not appear in version lists in the Package Manager UI on the nuget.org package feed. Visual Studio 2019 supports SemVer 2.0.0 packages.

For more information about SemVer 2.0.0 support, please refer to this document:
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200

**Comment by hueifeng** [comment]
@joelverhagen Thank you. But I don’t quite understand why I have two packages with the same version number, only one will appear in the UI `Magicodes.IE.Excel` and `Magicodes.IE.Core`.

**Comment by joelverhagen** [comment]
I'm not exactly sure that I follow what the problem is. I see both the Excel and the Core project in the screenshot above. Provide another screenshot or description of what problem you are facing?

**Comment by hueifeng** [comment]
I understand what I said above, but I have encountered a problem that the stable package cannot be searched out.
## Reproduce
vs2015
![image](https://user-images.githubusercontent.com/34702552/86307876-7123e100-bc4a-11ea-8b72-f793d8fd44bd.png)

vs2019

![image](https://user-images.githubusercontent.com/34702552/86307914-87ca3800-bc4a-11ea-9ea9-c79c75a9d25a.png)

**Comment by joelverhagen** [comment]
Could you provide the package source URLs configured into both your VS 2015 and VS 2019 cases? This can be found in Tools > Options.

My suspicion is that your VS 2015 has a non-standard package source URL configured into it.

**Comment by hueifeng** [comment]
As shown in the picture, use `https://api.nuget.org/v3/index.json`.

![image](https://user-images.githubusercontent.com/34702552/86309307-fc52a600-bc4d-11ea-84e2-28abaf8a3e7c.png)

**Comment by joelverhagen** [comment]
I dug into this. This is also because of the SemVer 2.0.0 filtering. Consider the version 3.0.0-beta1 (absolute latest as seen in VS 2019). This package has a SemVer 2.0.0 version range in one of its dependencies. This also makes the package source consider the package as SemVer 2.0.0:
![image](https://user-images.githubusercontent.com/94054/86310422-e5bb3900-bbd2-11ea-8da0-6af9b48e2af2.png)

**Comment by hueifeng** [comment]
@joelverhagen  Ok,Thank you for your help.
