### ISSUE TITLE
NuGet appending extra '.' to feedurl -- in azure artifacts scenario.

### ISSUE THREAD

**Issue by weirdyang** [NuGet/Home#9743]
## Details about Problem

using  dotnet test, when the project builds and restores packages, Nuget adds an extra '.' to the feed url:
{"count":1,"value":{"Message":"No HTTP resource was found that matches the request URI 'https://pkgs.dev.azure.com/_packaging/MicroserviceAPIHelper/nuget/v3/index.json.'."}}

Worked before? If so, with which NuGet version:
Yes, I'm using the same YAML for different projects. Only this one fails.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
C:\Program Files\dotnet\sdk\3.1.102\NuGet.targets(123,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/ArcstonePteLtd/DEVELOPMENT/_packaging/MicroserviceAPIHelper/nuget/v3/index.json. [C:\Users\Administrator\Desktop\AgentPool DEVOPS\_work\22\s\OrchardCore.EventTask.sln]
C:\Program Files\dotnet\sdk\3.1.102\NuGet.targets(123,5): error :   Response status code does not indicate success: 404 (Not Found - VS800075: The project with id 'vstfs:///Classification/TeamProject/4b99b311-777c-40ba-aa84-7a45b64d3b89' does not exist, or you do not have permission to access it. (DevOps Activity ID: B59435BA-FE3D-4DDC-B501-D43DE75886E0)). [C:\Users\Administrator\Desktop\AgentPool DEVOPS\_work\22\s\OrchardCore.EventTask.sln]

I've tried the following:
>Hi, I missed to clear this out.
There is an option "Limit job authorization scope to current project" in
"Project Settings" > Pipelines > Settings.
This option was enabled by default, if it's disabled, It will work.

And also adding the Build Service as a contributor to the feed.

**Comment by rrelyea** [comment]
there are ways that an additional source may be defined with the extra period.

1) project files may have a property set (via targets/props or project file) that adds this source with a period.
2) there could be other nuget.config files, that only impact this project. (nuget.config files when used via command line can be per project...when run in VS, those same configs don't work)
3) the pipeline, for auth or other reasons, might be generating a nuget.config file -- and defining sources in it. (parts of azure do this during the build...to handle auth for azure artifacts, etc...)

i cannot imagine that this issue is due to nuget...but it is possible.

searching for that exact string in logs, all source code, etc... might help?
digging into binary log of msbuild or similar may help find an msbuild related problem.
also ... looking in obj\project.assets.json will list the configs that the restore did use...so you could hunt down potential config files.
