### ISSUE TITLE
suggest idea: add source of packages "cached packages" for vs2017/19

### ISSUE THREAD

**Issue by aaafgcfg** [NuGet/Home#9885]
suggest idea: add source of packages "cached packages" for vs2017/19
I think this will be helpful?

**Comment by zivkan** [comment]
Could you explain the idea some more? I don't understand what's being suggested.

**Comment by aaafgcfg** [comment]
i think you can add to visual studio's nuget's settings package source C:\Users\username\\.nuget\packages as additional package source .

**Comment by zivkan** [comment]
This is the default global packages folder. As long as you don't have a `nuget.config` file changing the global packages folder to a different location, packages here will be used, so adding it as a source will not have any benefit (and will slow down restore, because it will check the location twice if the package exists, instead of just once).

**Comment by zkat** [comment]
Closing as per the last comment. Please feel free to comment again if you feel like this didn't resolve your issue.
