### ISSUE TITLE
PM UI:  IProjectContextInfo.GetInstalledPackagesAsync(...) should not return IEnumerable<T>

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9936]
Following RPC best practices, `IProjectContextInfo.GetInstalledPackagesAsync(...)` should return `IReadOnlyCollection<IPackageReferenceContextInfo>` instead of `IEnumerable<IPackageReferenceContextInfo>`.

CC @sbanni

**Comment by aortiz-msft** [comment]
@zivkan

**Comment by zivkan** [comment]
I didn't find `IProjectContextInfo` in a quick search of a dev branch, so my guess is that this is in the VS.OE feature branch only. Since it's not part of a shipped NuGet SDK (and chances are I'm guessing it will be part of the NuGet VS code, not part of the NuGet SDK), it's not a breaking change, so go for it.
