### ISSUE TITLE
NuGet PMC memory usage - investigate decreasing the amount of dlls loaded initially

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9988]
Child of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1167790.

To goal is to figure out there is a quick win as far as assembly loading goes. 

Here is break down of loaded DLLs when I open PMC, since powershell related Dlls are most I defer load them until user start typing something.

NuGet dlls:
NuGet.Common.dll - 113k
NuGet.Configuration.dll - 154k
NuGet.Console.dll - 137k
NuGet.PackageManagement.dll - 387k
NuGet.PackageManagement.VisualStudio.dll - 580k
NuGet.Packaging.dll - 651k
NuGet.ProjectModel.dll - 208k
NuGet.SolutionRestoreManager.dll - 1.674k
NuGet.Versioning.dll - 51k
NuGet.VisualStudio.Common.dll- 141
NuGet.VisualStudio.Implementation.dll - 213k
Total:4.309Kb

PowerShell dlls:
Microsoft.PowerShell.Commands.Diagnostics.ni.dll -> 319k
Microsoft.PowerShell.Commands.Management.ni.dll -> 1.815k
Microsoft.PowerShell.Commands.Utility.ni.dll -> 11.608k
Microsoft.PowerShell.ConsoleHost.ni.dll -> 552k
Microsoft.PowerShell.Security.ni.dll -> 319k
Microsoft.WSMan.Management.dll -> 274k
Microsoft.MSMan.Runtime.ni.dll -> 14Kb
System.Management.Automation.ni.dll -> 26.504kb
Total: 41.405k

**Comment by erdembayar** [comment]
@aortiz-msft  @nkolev92 
Here is my initial finding:
When I use `ProcessExplorer` then I saw around 50Mb difference when I opened PMC, not 75Mb.   It looks this number depends on my local environment and computer.
I compared loaded DLLs for PMC open and open a solution on VS without PMC. I found about 46.801Kb of DLL and it's about the same size(50Mb) I found above. Of course I know it's not 1:1 mapping, but very close.
From this 46.801Kb only 4.309Kb was Nuget related, remaining 42.492Kb was Powershell related. 
So I see this point we don't have much room to decrease for Nuget, because mostly it's related to Powershell only.

1. Here what I found common for both cases:4.309Kb
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet

NuGet.Common.dll - 113k
NuGet.Configuration.dll - 154k
NuGet.Console.dll - 137k
NuGet.PackageManagement.dll - 387k
NuGet.PackageManagement.VisualStudio.dll - 580k
NuGet.Packaging.dll - 651k
NuGet.ProjectModel.dll - 208k
NuGet.SolutionRestoreManager.dll - 1.674k
NuGet.Versioning.dll - 51k
NuGet.VisualStudio.Common.dll- 141
NuGet.VisualStudio.Implementation.dll - 213k
Total:4.309Kb

---------------------------------------------------
2. NuGet PMC Only: 42.492Kb
From above 42.492Kb, PowerShell related only dlls: 41.405k
NuGet PMC Total: 4.309Kb + 42.492Kb = 46.801Kb

NuGet.PackageManagement.PowerShellCmdlets.dll - 135k
NuGet.PackageManagement.UI.dll - 780k
Nuget.Resolver.dll -57k
NuGet.Tools.dll - 100k
NuGet.VisualStudio.Contracts.dll - 15k
----NuGetConsole.Host.PowerShell.dll-110k
----NuGet.Core.dll - 647k

Microsoft.PowerShell.Commands.Diagnostics.ni.dll -> 319k
Microsoft.PowerShell.Commands.Management.ni.dll -> 1.815k
Microsoft.PowerShell.Commands.Utility.ni.dll -> 11.608k
Microsoft.PowerShell.ConsoleHost.ni.dll -> 552k
Microsoft.PowerShell.Security.ni.dll -> 319k

Microsoft.WSMan.Management.dll -> 274k
Microsoft.MSMan.Runtime.ni.dll -> 14Kb
System.Management.Automation.ni.dll -> 26.504kb

----------------
3. NuGet Nomination only: 850Kb
Nomination total: 4309Kb + 850Kb = 5.159Kb

Nomination Solution open:
NuGet.Commands.ni.dll - 550k
NuGet.DependencyResolver.Core.ni.dll - 90k
NuGet.Frameworks.ni.dll- 119k
Nuget.LibraryModel.ni.dll - 56k
Nuget.VisualStudio.ni.dll - 35k

**Comment by erdembayar** [comment]
@nkolev92  @zivkan 
I found here is actual loading of Powershell dlls into memory was happening.

 [PowerShellHost.cs#L303](https://github.com/NuGet/NuGet.Client/blob/0e08ef6427b824d051c312392f2a194af0a76d1f/src/NuGet.Clients/NuGetConsole.Host.PowerShell/PowerShellHost.cs#L303)

I tried to move Powershell DLL loading until user start typing with [PR#3667](https://github.com/NuGet/NuGet.Client/pull/3667), and it did defer DLL load until user start typing something into screen.
But there is 2 issues I experienced.

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
Updated latest summarized doc:
https://github.com/erdembayar/pmc_powershell_defer/blob/master/PMC_PowerShell_load.md

**Comment by nkolev92** [comment]
* Create an issue for adding the telemetry. 
* We can leave this issue open because we'll act based on what the telemetry tells us. 

Finally, ensure that the status is communicated on the issue in AzDO.

**Comment by nkolev92** [comment]
The progress here is dependant on what we find through our data.

**Comment by nkolev92** [comment]
We have 1 fewer assembly since this was filled and that's the min.
